-- 0018_seed_20260720T010202Z_01_posts.sql: data seed from pipeline:load run.
-- Generated:  2026-07-20T01:02:04.368777+00:00
-- Run started: 2026-07-20T01:02:02.141703+00:00
-- Source: data/working/load manifest from this run.
--
-- Idempotent: every INSERT is INSERT OR IGNORE, keyed by the
-- table's natural unique constraint.  Wrangler's migration
-- tracking normally prevents re-apply; the OR IGNORE is
-- defense in depth for partial / interrupted re-runs.
--
-- Chunk: 01_posts (1/5)
-- Tables: imported_vibe_posts.
-- Pipeline-state tables (processing_runs, pipeline_artifacts)
-- are intentionally excluded — they're per-run bookkeeping.

INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (244, '1ux0j2b', 'Romance movies that feel like Taiwan (on film)', 'Romance movies that feel like Taiwan (on film)', 'I''d love a movie that feels like way, that''ll have me yearning for the protagonists to get together. Maybe they do, maybe they don''t.

Doesn''t have to be English.

TIA!', 'an0nymm', 1784106511, '/r/MoviesThatFeelLike/comments/1ux0j2b/romance_movies_that_feel_like_taiwan_on_film/', 'https://www.reddit.com/gallery/1ux0j2b', 'MoviesThatFeelLike', 'A yearning for romantic connection in a lush, atmospheric setting with melancholic undertones, evocative of Taiwanese cinema.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (245, '1ux1hba', 'JAKE GYLLENHAAL', 'Jake Gyllenhaal', '', 'raj722', 1784109747, '/r/MoviesThatFeelLike/comments/1ux1hba/jake_gyllenhaal/', 'https://v.redd.it/9ouhrr8n3ddh1', 'MoviesThatFeelLike', 'Yearning to capture the raw intensity and charisma of Jake Gyllenhaal''s performances.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (246, '1ux1twd', 'Movies with that 90s feel good summer feel?', 'Movies with that 90s feel good summer feel?', 'Looking for the 90s summer fun movies. Light hearted, Blues Traveller and Hootie & the Blowfish kinda movies. Already posted PCU, Camp Nowhere, and Heavyweights. Doesn''t need to be centered around camp but hopefully you know understand. ', 'surprisinglynotabot', 1784110887, '/r/MoviesThatFeelLike/comments/1ux1twd/movies_with_that_90s_feel_good_summer_feel/', 'https://www.reddit.com/gallery/1ux1twd', 'MoviesThatFeelLike', 'A nostalgic yearning for the carefree, sun-soaked feeling of 90s summer movies, filled with lighthearted adventures and warm soundtracks.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (247, '1ux2tu4', 'Movies that feel like Alex Ross paintings?', '', '', 'Ok_Relief7546', 1784113947, '/r/MoviesThatFeelLike/comments/1ux2tu4/movies_that_feel_like_alex_ross_paintings/', 'https://www.reddit.com/gallery/1ux2tu4', 'MoviesThatFeelLike', 'A request for films that evoke the heroic, nostalgic, and painterly aesthetic of Alex Ross''s comic book art.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (248, '1ux30su', 'Know any movie/game/book that feel like this song?', 'Know any movie/game/book that feel like this song?', '', 'BenfordAbrahams', 1784114522, '/r/MoviesThatFeelLike/comments/1ux30su/know_any_moviegamebook_that_feel_like_this_song/', 'https://youtu.be/pUX0bE6AQBs', 'MoviesThatFeelLike', 'A surreal and introspective mood, questioning if any media can match the tonal complexity of a mysterious song.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (249, '1ux3921', 'Movies that feel like Steve Rude art?', 'Movies that feel like Steve Rude art', '', 'Ok_Relief7546', 1784115186, '/r/MoviesThatFeelLike/comments/1ux3921/movies_that_feel_like_steve_rude_art/', 'https://www.reddit.com/gallery/1ux3921', 'MoviesThatFeelLike', 'A discussion seeking movies with the distinctive comic book aesthetic of artist Steve Rude, characterized by clean lines, vibrant colors, and retro-futuristic action sequences.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (250, '1ux3bpt', 'Movies that feel like Christopher Mccurdy photographs?', 'Movies that feel like Christopher Mccurdy photographs', '', 'umbertocsaba', 1784115401, '/r/MoviesThatFeelLike/comments/1ux3bpt/movies_that_feel_like_christopher_mccurdy/', 'https://www.reddit.com/gallery/1ux3bpt', 'MoviesThatFeelLike', 'Eerie and atmospheric movie recommendations reminiscent of Christopher McCrudy''s moody, surreal photography, often veering into dark psychological horror and Lynchian unease.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (251, '1ux3hwi', 'Movies that feel like this?', 'Movies that feel like this?', 'The artist is Amy Hill!', 'umbertocsaba', 1784115903, '/r/MoviesThatFeelLike/comments/1ux3hwi/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1ux3hwi', 'MoviesThatFeelLike', 'A collection of films that evoke a melancholic, introspective, and nostalgic atmosphere, often with dramatic and psychological undertones.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (252, '1ux4ziz', 'Choose One', 'Choose One', '', 'thejohnnyr', 1784119893, '/r/MoviesThatFeelLike/comments/1ux4ziz/choose_one/', '/r/Meowi/comments/1ux4ynd/choose_jar_of_dirt_or_totally_not_cursed_gold/', 'MoviesThatFeelLike', 'A quiet tension before a decision.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (253, '1uxaynk', 'Spy, political, espionage?', 'Spy, political, espionage?', '', 'Far-Remove7363', 1784133083, '/r/MoviesThatFeelLike/comments/1uxaynk/spy_political_espionage/', 'https://www.reddit.com/gallery/1uxaynk', 'MoviesThatFeelLike', 'A mood for cold war espionage thrillers, with a focus on atmospheric tension, political intrigue, and gritty realism.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (254, '1uxbqmj', 'It feels like the sapranos in WNY right now', 'It feels like The Sopranos in WNY right now', '(Unedited)', 'cupbeezy', 1784134711, '/r/MoviesThatFeelLike/comments/1uxbqmj/it_feels_like_the_sapranos_in_wny_right_now/', 'https://i.redd.it/lkyh0nnhcfdh1.jpeg', 'MoviesThatFeelLike', 'A dark, crime-drama atmosphere reminiscent of The Sopranos, set in Western New York.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (255, '1uxc6ur', 'Top movies to watch in "Netflix".', 'Top movies to watch in Netflix', '', 'Bulky_Stay_9282', 1784135638, '/r/MoviesThatFeelLike/comments/1uxc6ur/top_movies_to_watch_in_netflix/', 'https://i.redd.it/9njytiz8ffdh1.jpeg', 'MoviesThatFeelLike', 'A casual list of top movies available on Netflix, suggesting a relaxed browsing mood.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (256, '1uxc8md', 'Top movies to watch on "Netflix"?.', 'Top movies to watch on Netflix?', '', 'Bulky_Stay_9282', 1784135737, '/r/MoviesThatFeelLike/comments/1uxc8md/top_movies_to_watch_on_netflix/', 'https://i.redd.it/qhj960mjffdh1.jpeg', 'MoviesThatFeelLike', 'Curiosity for top Netflix movies, met with a few specific suggestions spanning horror, drama, and documentary.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (257, '1uxg0ve', 'Movies that feel aesthetic', 'Movies that feel aesthetic', '', 'Anonymous___0522', 1784144028, '/r/MoviesThatFeelLike/comments/1uxg0ve/movies_that_feel_aesthetic/', 'https://www.reddit.com/gallery/1uxg0ve', 'MoviesThatFeelLike', 'A desire for visually arresting films that evoke a strong aesthetic experience, often through neon colors, striking visuals, and immersive atmospheres.', 'skipped', 'no usable images', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (258, '1uxg64v', 'Movies that feels like this breezy..', 'Movies that feel like this breezy', '', 'Snake_Charmers', 1784144380, '/r/MoviesThatFeelLike/comments/1uxg64v/movies_that_feels_like_this_breezy/', 'https://www.reddit.com/gallery/1uxg64v', 'MoviesThatFeelLike', 'A request for movies with a breezy, lighthearted feel.', 'skipped', 'no usable images', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (259, '1uxg9c9', 'Movies that feels like this..', 'Movies that feels like this', '', 'Snake_Charmers', 1784144596, '/r/MoviesThatFeelLike/comments/1uxg9c9/movies_that_feels_like_this/', 'https://www.reddit.com/gallery/1uxg9c9', 'MoviesThatFeelLike', 'Quiet longing for a cinematic world that feels like a half-remembered dream.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (260, '1uxgg8n', 'fav movies of this girl', 'fav movies of this girl', '', 'trophymermaid', 1784145059, '/r/MoviesThatFeelLike/comments/1uxgg8n/fav_movies_of_this_girl/', 'https://i.redd.it/7kzxwim97gdh1.jpeg', 'MoviesThatFeelLike', 'A personal and nostalgic glimpse into someone''s favorite movies.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (261, '1uxggue', 'Movies that feels like freezing!!', '', '', 'Snake_Charmers', 1784145102, '/r/MoviesThatFeelLike/comments/1uxggue/movies_that_feels_like_freezing/', 'https://www.reddit.com/gallery/1uxggue', 'MoviesThatFeelLike', 'A discussion about movies that evoke a deep sense of cold and freezing environments, from survival thrillers to snowy landscapes.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (262, '1uxgkp4', 'fav movies of this girl', '', '', 'trophymermaid', 1784145358, '/r/MoviesThatFeelLike/comments/1uxgkp4/fav_movies_of_this_girl/', 'https://i.redd.it/jyeiv4f58gdh1.jpeg', 'MoviesThatFeelLike', 'A personal list of favorite movies, possibly seeking connection through shared taste.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (263, '1uxhkeh', 'Movies with lighting like 60''s Star Trek', 'Movies with lighting like 60''s Star Trek', '(Blade Runner(s) and Suspiria are definitely give-ins.)

Feeling tired of the trend of dull, dearly color correction and dimly lit scenes.

Looking for movies with similar lighting to TOS. Doesn''t have to be sci-fi or any specific genre. Just fun to look at.', 'MoonSettler', 1784147674, '/r/MoviesThatFeelLike/comments/1uxhkeh/movies_with_lighting_like_60s_star_trek/', 'https://www.reddit.com/gallery/1uxhkeh', 'MoviesThatFeelLike', 'A vibrant quest for films with bold, colorful lighting reminiscent of 60s Star Trek, rejecting modern dull color grading in favor of vivid, pop-art aesthetics.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (264, '1uxkwtx', 'Movies where the protagonist get''s their face eaten (metaphorically)', 'Movies where the protagonist gets their face eaten (metaphorically)', '', 'Efficient-Pudding177', 1784155295, '/r/MoviesThatFeelLike/comments/1uxkwtx/movies_where_the_protagonist_gets_their_face/', 'https://www.reddit.com/gallery/1uto6ia', 'MoviesThatFeelLike', 'A post seeking stories of ironic comeuppance where those who support a system become its victims.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (265, '1uxl60a', 'Movies that feel like this?', 'Movies that feel like this', 'Like super advanced humans crash landed (or landed peacefully) on an unknown planet that the natives are humans but the technology are either primitive, medieval, 2000s modern humans.

The closest i remember is after earth and battlestar galactica', 'DeezNutts87', 1784155893, '/r/MoviesThatFeelLike/comments/1uxl60a/movies_that_feel_like_this/', 'https://i.redd.it/q76el5ykzech1.png', 'MoviesThatFeelLike', 'A sense of wonder and mystery as advanced humans encounter primitive or medieval human societies on alien worlds, often involving crash landings and cultural clashes.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (266, '1uxmvsc', 'Filmes minimalistas, antigos, e quase silenciosos, com pouca trilha sonora e poucos personagens, cenários destacados e escuros e uma narrativa melancólica com personagens em crise.', 'Filmes minimalistas, antigos, e quase silenciosos, com pouca trilha sonora e poucos personagens, cenários destacados e escuros e uma narrativa melancólica com personagens em crise.', '', 'Less_Hamster_8583', 1784160177, '/r/MoviesThatFeelLike/comments/1uxmvsc/filmes_minimalistas_antigos_e_quase_silenciosos/', 'https://www.reddit.com/gallery/1uxmvsc', 'MoviesThatFeelLike', 'A desire for minimalist, old, almost silent films with sparse soundtrack, few characters, dark settings, and melancholic narratives focusing on characters in crisis.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (267, '1uxnocq', 'Chic, messy, sensual, slightly androgynous ?', 'Chic, messy, sensual, slightly androgynous ?', '', 'youandyourfijiwater', 1784162260, '/r/MoviesThatFeelLike/comments/1uxnocq/chic_messy_sensual_slightly_androgynous/', 'https://www.reddit.com/gallery/1uxnocq', 'MoviesThatFeelLike', 'Films and media that embody a chic, messy, sensual, and slightly androgynous aesthetic, often featuring eroticism, gritty realism, and strong female characters.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (268, '1uxo8a6', 'Movies that feel like this?', 'Movies that feel like this', '[removed]', '5oclockgoldenhour', 1784163750, '/r/MoviesThatFeelLike/comments/1uxo8a6/movies_that_feel_like_this/', 'https://www.tiktok.com/@gkhomemovies/video/7662924111454293261', 'MoviesThatFeelLike', 'A request for movie recommendations that capture a specific, undefined mood', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (269, '1uxod91', 'Movies that feel like this?', 'Movies that feel like this', 'Coming of age/ neon aesthetic', 'Worldpeacee007', 1784164134, '/r/MoviesThatFeelLike/comments/1uxod91/movies_that_feel_like_this/', 'https://www.tiktok.com/t/ZTS3d3KJX/', 'MoviesThatFeelLike', 'A coming-of-age story set in a neon-lit world, blending nostalgia with a vibrant, aesthetic visual style.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (270, '1uxox7z', 'Movies about running away into the wilderness', 'Movies about running away into the wilderness', 'Anything that''s like Moonrise Kingdom if Suzy and Sam managed to escape, I just loved the segments of them walking through the forest 🥹 

I know "Into the Wild" has similar elements of lonesomeness, nature, and is character-focused (which is what I particularly love the most), but I haven''t finished it :0

Honestly if there''s any shows similar too, I''d love to hear about them!

Doesn''t matter if they trek on land or use cars, but ideally nothing action-heavy. I think the slow pace of everything is what I fancied. Drama and angst is cool with me too!', 'doodiedoodahdee', 1784165632, '/r/MoviesThatFeelLike/comments/1uxox7z/movies_about_running_away_into_the_wilderness/', 'https://i.redd.it/7cvf10sfwhdh1.jpeg', 'MoviesThatFeelLike', 'A yearning for slow, character-driven stories about escaping into nature, with a tone of lonesome adventure and quiet angst.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (271, '1uxp3zv', 'Running away into the wilderness / Long Roadtrips', 'Running away into the wilderness / Long Roadtrips', 'Anything like Moonrise Kingdom if Suzy and Sam managed to escape, I just loved the segments of them exploring the forest and reaching to their little part of the island 🥹

I know of Into the Wild since it has similar themes of lonesomeness, nature, and is character-focused (which is what I particularly love), but I have yet to finish :0

Ideally something slow paced. Romance, drama, and angst works for me, as long as it isn''t action-heavy or too intense that it starts feeling like a thriller 😭 I''d love if there was some sort of water scene, maybe a beach or a lake.

I''m also super down for anything like Mr. Bean''s Holiday and Unpregnant because I love a looong journey on the road.

(oh ya and I made the collage at the start 🤭)', 'doodiedoodahdee', 1784166161, '/r/MoviesThatFeelLike/comments/1uxp3zv/running_away_into_the_wilderness_long_roadtrips/', 'https://www.reddit.com/gallery/1uxp3zv', 'MoviesThatFeelLike', 'A nostalgic, slow-paced yearning for escape into nature, with tender romance and bittersweet angst, seeking the quiet adventure of a long road trip or a hidden wilderness sanctuary.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (272, '1uxpwvl', 'Please send me some coming of age recommendations similar to perks of being a wallflower', 'coming of age recommendations similar to perks of being a wallflower', '', 'premegoodeats', 1784168370, '/r/MoviesThatFeelLike/comments/1uxpwvl/please_send_me_some_coming_of_age_recommendations/', 'https://i.redd.it/s5o9642l4idh1.jpeg', 'MoviesThatFeelLike', 'A curated list of coming-of-age films evoking the same emotional resonance and teen angst as ''The Perks of Being a Wallflower'', ranging from nostalgic classics to modern indie gems.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (273, '1uxqt7p', 'movies that feel like this', 'Movies like The Division', 'the division', 'daddylongjohnsliver', 1784170957, '/r/MoviesThatFeelLike/comments/1uxqt7p/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1uxqt7p', 'MoviesThatFeelLike', 'A gritty, post-apocalyptic atmosphere with themes of survival, contagion, and urban decay.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (274, '1uxqv4y', 'Movies like Steel Magnolias?', 'Movies like Steel Magnolias', '', 'ConstantCup4776', 1784171109, '/r/MoviesThatFeelLike/comments/1uxqv4y/movies_like_steel_magnolias/', 'https://i.redd.it/riljxf9qcidh1.jpeg', 'MoviesThatFeelLike', 'Emotional dramas centered on female friendships, often with a mix of humor and heartbreak.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (275, '1uxsi5h', 'Movies that feel like this?', 'Movies that feel like this?', 'Let me know !', 'Worldpeacee007', 1784176039, '/r/MoviesThatFeelLike/comments/1uxsi5h/movies_that_feel_like_this/', 'https://www.tiktok.com/t/ZTS32jaP7/', 'MoviesThatFeelLike', 'A longing for emotionally resonant, atmospheric dramas that evoke melancholy and introspection.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (276, '1uxu2fa', 'Films that feel like Rät by Penelope Scott', 'Films that feel like Rät by Penelope Scott', 'films that feel like realising your influences, heroes and icons are actually kind of assholes also potentially elements of losing that childhood naivety? 

open to tv, books and other songs as well ', 'jaysbaddecisions', 1784181003, '/r/MoviesThatFeelLike/comments/1uxu2fa/films_that_feel_like_rät_by_penelope_scott/', 'https://i.redd.it/fa0h3s356jdh1.jpeg', 'MoviesThatFeelLike', 'A feeling of disillusionment and loss of childhood naivety upon realizing that one''s heroes and influences are flawed or morally questionable.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (277, '1uxu6yc', 'James and the giant peach and his aunts.', 'James and the Giant Peach and His Aunts', 'Any non-animated or animated movies that give off a similar vibe to james and the giant peach or coraline ', '__jude_', 1784181405, '/r/MoviesThatFeelLike/comments/1uxu6yc/james_and_the_giant_peach_and_his_aunts/', 'https://www.reddit.com/gallery/1uxu6yc', 'MoviesThatFeelLike', 'A whimsically macabre longing for worlds where dark fantasy and eccentricity intertwine, where aunts are monstrous and magic lurks in the mundane.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (278, '1uxw03l', 'Movies that feel like this? Kind of like es oblivion', 'Movies that feel like this? Kind of like es oblivion', '', 'anuslitt', 1784187524, '/r/MoviesThatFeelLike/comments/1uxw03l/movies_that_feel_like_this_kind_of_like_es/', 'https://www.reddit.com/gallery/1uxw03l', 'MoviesThatFeelLike', 'A dark medieval fantasy world with snowy landscapes, isolation, and epic quests, reminiscent of The Elder Scrolls IV: Oblivion.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (279, '1uy11w0', 'Movies that feel like', 'Movies that feel like', '', 'ClassicLightbulbs', 1784203805, '/r/MoviesThatFeelLike/comments/1uy11w0/movies_that_feel_like/', 'https://i.redd.it/z25lth6y1ldh1.jpeg', 'MoviesThatFeelLike', 'A raw, gritty, and atmospheric Americana vibe, evoking a sense of nostalgia and decay, similar to the feel of a tattoo.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (280, '1uy19m4', 'The demise of the American family farm', 'The demise of the American family farm', '[deleted]', '[deleted]', 1784204374, '/r/MoviesThatFeelLike/comments/1uy19m4/the_demise_of_the_american_family_farm/', '', 'MoviesThatFeelLike', 'A somber reflection on the disappearance of traditional rural life.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (281, '1uy1axh', 'The demise of the American family farm', 'The demise of the American family farm', '', 'stakes-lines-grades', 1784204471, '/r/MoviesThatFeelLike/comments/1uy1axh/the_demise_of_the_american_family_farm/', 'https://www.reddit.com/gallery/1uy1axh', 'MoviesThatFeelLike', 'A quiet, melancholic exploration of the loss of the family farm and rural American identity.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (282, '1uy1m04', 'Movies about sexless marriage', 'Movies about sexless marriage', '', 'SecondStarpilot', 1784205297, '/r/MoviesThatFeelLike/comments/1uy1m04/movies_about_sexless_marriage/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uy1m04/movies_about_sexless_marriage/', 'MoviesThatFeelLike', 'A somber and introspective collection of films and series that delve into the complexities of sexless marriages, blending humor, drama, and melancholy.', 'skipped', 'no usable images', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (283, '1uy423e', 'Under the Call Sheets, ODYSSEY Casting Call and more...', '', '', 'hollywoodredline', 1784211178, '/r/MoviesThatFeelLike/comments/1uy423e/under_the_call_sheets_odyssey_casting_call_and/', 'https://screenmancer.tv/odyssey-casting-call-top-10-kismet-co-stars/', 'MoviesThatFeelLike', 'Atmosphere of anticipation and inside access to casting secrets.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (284, '1uy6ezu', 'Underground city movie like', '', 'Movies that explores best and explain and scene of best under ground cities,bunker type movie 

Zion 

Silo - this is best till now to explore 

Fallout 

Umbrella copration resident evil 🙈 i forgot it .

So any series movie manga anime any thing', 'AmanYadav19', 1784216416, '/r/MoviesThatFeelLike/comments/1uy6ezu/underground_city_movie_like/', 'https://www.reddit.com/gallery/1uy6ezu', 'MoviesThatFeelLike', 'Exploring underground bunkers and hidden cities in a dystopian or sci-fi setting.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (285, '1uy98g7', 'Eastern European sadness/hope', 'Eastern European sadness/hope', '', 'strberryfields55', 1784222503, '/r/MoviesThatFeelLike/comments/1uy98g7/eastern_european_sadnesshope/', 'https://www.reddit.com/gallery/1h7zyql', 'MoviesThatFeelLike', 'A collection of films that capture the melancholic yet hopeful spirit of Eastern Europe, blending stark realism with moments of resilience.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (286, '1uybvvj', 'What are some good Urban Fantasy movies?', 'Good Urban Fantasy Movies', '', 'MrVoyt', 1784228216, '/r/MoviesThatFeelLike/comments/1uybvvj/what_are_some_good_urban_fantasy_movies/', 'https://www.reddit.com/gallery/1uybvvj', 'MoviesThatFeelLike', 'A sprawling crowd-sourced list of urban fantasy films and series, ranging from classic cult hits like The Crow and Hellboy to newer favorites like Bright and Dorohedoro, with a tone of eager recommendation and occasional debate over genre boundaries.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (287, '1uyc4ch', 'Movies that feel like Goa or any similar locations', 'Movies that feel like Goa or any similar locations', '', 'SpaceTranquil', 1784228735, '/r/MoviesThatFeelLike/comments/1uyc4ch/movies_that_feel_like_goa_or_any_similar_locations/', 'https://www.reddit.com/gallery/1uyc4ch', 'MoviesThatFeelLike', 'A collection of movies capturing the relaxed, party-filled, beachside vibe of Goa.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (288, '1uyc9ju', 'Movies that feels like this?', 'Movies that feels like this?', '[removed]', 'Chillex95', 1784229058, '/r/MoviesThatFeelLike/comments/1uyc9ju/movies_that_feels_like_this/', 'https://www.reddit.com/gallery/1uyc9ju', 'MoviesThatFeelLike', 'A yearning for films that capture an indescribable, moody atmosphere.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (289, '1uycdhy', 'Movies that feels like this? 80/90s wall street vibe', 'Movies that feel like this? 80/90s wall street vibe', '[removed]', 'Chillex95', 1784229300, '/r/MoviesThatFeelLike/comments/1uycdhy/movies_that_feels_like_this_8090s_wall_street_vibe/', 'https://www.reddit.com/gallery/1uycdhy', 'MoviesThatFeelLike', 'A longing for the high-stakes, power-driven atmosphere of 1980s and 1990s Wall Street, with its sharp suits, trading floors, and relentless ambition.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (290, '1uyd1h3', 'Whats the most destroy lonely looking movie?', 'What''s the most Destroy Lonely looking movie?', 'Like what movie looks like his sound the most? 

I', 'alsoim', 1784230782, '/r/MoviesThatFeelLike/comments/1uyd1h3/whats_the_most_destroy_lonely_looking_movie/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uyd1h3/whats_the_most_destroy_lonely_looking_movie/', 'MoviesThatFeelLike', 'A request for a movie that visually embodies the moody, atmospheric sound of rapper Destroy Lonely.', 'skipped', 'no usable images', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (291, '1uydo8f', 'movie that feel like this', '', 'shadow of the colossus', 'daddylongjohnsliver', 1784232201, '/r/MoviesThatFeelLike/comments/1uydo8f/movie_that_feel_like_this/', 'https://www.reddit.com/gallery/1uydo8f', 'MoviesThatFeelLike', 'A longing for movies that capture the epic, lonely scale and melancholic atmosphere of Shadow of the Colossus, with vast landscapes and giant creatures.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (292, '1uye9s2', 'Movies that feels like a cold shady night..', 'Movies that feel like a cold shady night', '', 'Snake_Charmers', 1784233553, '/r/MoviesThatFeelLike/comments/1uye9s2/movies_that_feels_like_a_cold_shady_night/', 'https://www.reddit.com/gallery/1uye9s2', 'MoviesThatFeelLike', 'The chill of a shadowed evening, where the air is still and the dark settles in.', 'skipped', 'no usable images', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (293, '1uyei80', 'Movies that feels like this dark..', 'Movies That Feel Like This Dark', '', 'Snake_Charmers', 1784234082, '/r/MoviesThatFeelLike/comments/1uyei80/movies_that_feels_like_this_dark/', 'https://www.reddit.com/gallery/1uyei80', 'MoviesThatFeelLike', 'A dark, atmospheric, and unsettling collection of film recommendations that evoke dread, mystery, and a haunting, supernatural mood.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (294, '1uyfo6m', 'fav movies of this girl', 'fav movies of this girl', '[removed]', '[deleted]', 1784236774, '/r/MoviesThatFeelLike/comments/1uyfo6m/fav_movies_of_this_girl/', '', 'MoviesThatFeelLike', 'A sense of personal taste and curiosity, wanting to share favorite movies.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (295, '1uylqc2', 'Classic Movies that feel like 50s Sci-Fi era', 'Classic Movies that feel like 50s Sci-Fi era', '', 'Radiant-Boat-5149', 1784251855, '/r/MoviesThatFeelLike/comments/1uylqc2/classic_movies_that_feel_like_50s_scifi_era/', 'https://www.reddit.com/gallery/1uylqc2', 'MoviesThatFeelLike', 'A nostalgic journey through retro-futuristic cinema, where atomic age paranoia and wonder collide with alien invaders, giant monsters, and campy B-movie charm.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (296, '1uylyfz', 'horror movies that feel like 2010s fall ?', 'Horror movies that feel like 2010s fall', 'i’ve already seen the terrifier franchise, but something similar to that', 'Obvious-Selection450', 1784252480, '/r/MoviesThatFeelLike/comments/1uylyfz/horror_movies_that_feel_like_2010s_fall/', 'https://www.reddit.com/gallery/1uylyfz', 'MoviesThatFeelLike', 'A nostalgic longing for the cozy, campy, and chilling horror aesthetics of 2010s autumn evenings.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (297, '1uymrig', 'Kiss Marry Kill', '', '', 'Sukanya_Mj', 1784254723, '/r/MoviesThatFeelLike/comments/1uymrig/kiss_marry_kill/', '/r/Meowi/comments/1uympfr/kiss_marry_kill_kiss_marry_kill_pick_one_each/', 'MoviesThatFeelLike', 'A playful but emotionally charged game of choosing among celebrities, evoking a mix of humor and heartache.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (298, '1uynhbj', 'Moves that feel like this collage 🕳️⏳', 'Movies that feel like this collage', 'Any genre, live-action preferred. A few favorites that come to mind for me: 

The Fountain   
A Ghost Story  
Stay   
Take Shelter  
Aftersun ', 'savvylee17', 1784256745, '/r/MoviesThatFeelLike/comments/1uynhbj/moves_that_feel_like_this_collage/', 'https://i.redd.it/foj4n04gepdh1.jpeg', 'MoviesThatFeelLike', 'A haunting, introspective collection of films exploring memory, loss, and existential dread, with a surreal and melancholic tone.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (299, '1uypax0', 'I need recs for this list ♡', 'I need recs for this list ♡', '', 'Castle-n-the-sky', 1784262027, '/r/MoviesThatFeelLike/comments/1uypax0/i_need_recs_for_this_list/', 'https://i.redd.it/bos0qbpyupdh1.jpeg', 'MoviesThatFeelLike', 'A dark, psychologically intense collection of films with erotic, disturbing, and body horror elements.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (300, '1uyqn08', '90’s summer love vibes', '90s summer love vibes', 'Rohmer’s aesthetic, summer love where I will be kicking my feet giggling and feeling butterflies when watching their first kiss. Beautiful long shots with  intellectual dialogues that feel real and not cheesy romantic comedies. Artsy dreamy male protagonist would be a bonus.  
Are there more similar movies like Before Sunset Trilogy and the Rohmer’s seasons?', 'Luciiiius', 1784266237, '/r/MoviesThatFeelLike/comments/1uyqn08/90s_summer_love_vibes/', 'https://www.reddit.com/gallery/1uyqn08', 'MoviesThatFeelLike', 'A longing for 90s summer romance with intellectual, natural dialogue and dreamy aesthetics, evoking the works of Eric Rohmer and the Before trilogy, with a focus on beautiful landscapes and authentic, non-cheesy love stories.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (301, '1uys9v4', 'Paperman|2012', 'Paperman (2012)', '&#x200B;

Recommendations? Any movies that have the same vibe as the short film, I really enjoyed it, it reminded me of short romance comics I read when I was younger. ', 'SpaceyLadybug', 1784271655, '/r/MoviesThatFeelLike/comments/1uys9v4/paperman2012/', 'https://i.redd.it/jr8h2napnqdh1.jpeg', 'MoviesThatFeelLike', 'A charming, whimsical romance with a nostalgic, hand-drawn feel that evokes classic short romance comics.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (302, '1uyt6uj', 'Movies with this vibe?', 'Movies with this vibe?', '', 'Chillex95', 1784274900, '/r/MoviesThatFeelLike/comments/1uyt6uj/movies_with_this_vibe/', 'https://www.reddit.com/gallery/1uyt6uj', 'MoviesThatFeelLike', 'A curious, open-ended search for films that match an undefined but deeply felt atmosphere.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (303, '1uyu338', 'Movie that feel like the song 500 miles?', '', 'Peter Paul and Mary or Joan Baez versions xx something that even feels like a time gone by, smells like grass and sweat. Liminal vibes thrown in there. ', 'Stunning_Border_895', 1784278022, '/r/MoviesThatFeelLike/comments/1uyu338/movie_that_feel_like_the_song_500_miles/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uyu338/movie_that_feel_like_the_song_500_miles/', 'MoviesThatFeelLike', 'A nostalgic, liminal feeling of a bygone era, evoking grass and sweat, with a sense of being in between places.', 'skipped', 'no usable images', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (304, '1uyue8q', 'Looking for movies with good gun fight scenes and alot of emphasis on tatics.', 'Looking for movies with good gun fight scenes and a lot of emphasis on tactics.', 'Preferably alot of over the shoulder shot, where I can see what the combatants are shooting at. Minimum cut from the shooter to the shoted, I just get headache watching action movies that has 20 cuts in one horrible gun fight scene. ', 'Due-Violinist2132', 1784279090, '/r/MoviesThatFeelLike/comments/1uyue8q/looking_for_movies_with_good_gun_fight_scenes_and/', 'https://www.reddit.com/gallery/1uyue8q', 'MoviesThatFeelLike', 'Intense, realistic combat sequences with coherent action choreography and minimal cuts. The discussion emphasizes tactical gunplay and immersive sound design.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (305, '1uyugjw', 'What movie did you absolutely love as a kid, but can''t stand as an adult?', 'What movie did you absolutely love as a kid, but can''t stand as an adult?', '', 'Mysterious-Pen-1360', 1784279305, '/r/MoviesThatFeelLike/comments/1uyugjw/what_movie_did_you_absolutely_love_as_a_kid_but/', '/r/AskReddit/comments/1uyug23/what_movie_did_you_absolutely_love_as_a_kid_but/', 'MoviesThatFeelLike', 'Nostalgic yearning turned sour as childhood favorites fail to hold up in adulthood.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (306, '1uywx83', 'Going to watch Odyssey but haven''t watched the Troy!', 'Going to watch Odyssey but haven''t watched the Troy', 'But I know a little bit about the story is that enough or should I watch Troy.. is this enough more info.

Looks like I haven''t worried more about exams(haha)', 'Imaginary-Phase-1988', 1784287457, '/r/MoviesThatFeelLike/comments/1uywx83/going_to_watch_odyssey_but_havent_watched_the_troy/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uywx83/going_to_watch_odyssey_but_havent_watched_the_troy/', 'MoviesThatFeelLike', 'Casual and humorous reassurance about enjoying a film without prior knowledge, with a self-deprecating exam joke.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (307, '1uyx0kq', 'Should I watch The Odyssey in the Big Screen?', 'Should I watch The Odyssey in the Big Screen?', '', 'mrBing_2021', 1784287734, '/r/MoviesThatFeelLike/comments/1uyx0kq/should_i_watch_the_odyssey_in_the_big_screen/', '/r/kolkata/comments/1uywywp/should_i_watch_the_odyssey_in_the_big_screen/', 'MoviesThatFeelLike', 'The big screen beckons for Homer''s tale, but a quiet reminder of misdirection shadows the quest.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (308, '1uyy2c8', 'Looking for Thrilling Sci-Fi or Psychological Horror Recommendations!', 'Looking for Thrilling Sci-Fi or Psychological Horror Recommendations', '[removed]', 'Opposite_Jump7737', 1784290648, '/r/MoviesThatFeelLike/comments/1uyy2c8/looking_for_thrilling_scifi_or_psychological/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uyy2c8/looking_for_thrilling_scifi_or_psychological/', 'MoviesThatFeelLike', 'The post expresses a desire for thrilling science fiction or psychological horror media, indicating a mood of seeking intense, suspenseful experiences.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (309, '1uz3zc2', 'Movies that feel like the tv show Strangers with Candy', 'Movies that feel like Strangers with Candy', '', 'YeahWellDesigns', 1784304313, '/r/MoviesThatFeelLike/comments/1uz3zc2/movies_that_feel_like_the_tv_show_strangers_with/', 'https://i.redd.it/7of7m48tctdh1.jpeg', 'MoviesThatFeelLike', 'A collection of offbeat, darkly comedic, and satirical movies and shows that capture the awkward, crude spirit of Strangers with Candy.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (310, '1uz6oqj', 'Recommend whimsical movies with this vibe pls', 'Recommend whimsical movies with this vibe', '', 'whiggachan', 1784310172, '/r/MoviesThatFeelLike/comments/1uz6oqj/recommend_whimsical_movies_with_this_vibe_pls/', 'https://www.reddit.com/gallery/1uz6oqj', 'MoviesThatFeelLike', 'A request for whimsical movies with a dark fantasy forest aesthetic, featuring mystical spirits and epic journeys.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (311, '1uz74xv', 'Odyssey', 'Odyssey', '', 'ConversationMore7011', 1784311136, '/r/MoviesThatFeelLike/comments/1uz74xv/odyssey/', 'https://i.redd.it/e2u8h8zsltdh1.jpeg', 'MoviesThatFeelLike', 'A thrilling and immersive experience with outstanding audio and a compelling performance by Himesh Patel as Agamemnon.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (312, '1uz7t8c', 'Movies that feels like floating on trips..', 'Movies that feels like floating on trips..', '', 'Snake_Charmers', 1784312564, '/r/MoviesThatFeelLike/comments/1uz7t8c/movies_that_feels_like_floating_on_trips/', 'https://www.reddit.com/gallery/1uz7t8c', 'MoviesThatFeelLike', 'A dreamy, cinematic journey that captures the floating sensation of road trips and wanderlust.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (313, '1uza7ud', 'movies where a character feels like "crazy but gets the job done"', 'movies where a character feels like crazy but gets the job done', 'title is from a ben folds five song lmao but i really want movies (or other media) containing a character who''s seen as crazy either by others or the viewer for the way they take on a task or something along those lines. i hope this makes sense LMAO', 'mcpriceley1', 1784317832, '/r/MoviesThatFeelLike/comments/1uza7ud/movies_where_a_character_feels_like_crazy_but/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uza7ud/movies_where_a_character_feels_like_crazy_but/', 'MoviesThatFeelLike', 'A craving for media featuring unhinged yet effective characters who defy conventional methods to achieve their goals.', 'skipped', 'no usable images', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (314, '1uzalk9', 'Desire (2026) Ending Explained: Who Really Killed Matías', 'Desire 2026 Ending Explained Who Really Killed Matías', '', 'Agaberd6600', 1784318689, '/r/MoviesThatFeelLike/comments/1uzalk9/desire_2026_ending_explained_who_really_killed/', 'https://memoria.film/desire-2026-ending-explained/', 'MoviesThatFeelLike', 'A gripping mystery that keeps you guessing about the true killer, with a tense atmosphere and a payoff that redefines the story''s emotional core.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (315, '1uze7ch', 'Movies that feels like this', 'Movies that feels like this', '', 'Chillex95', 1784327224, '/r/MoviesThatFeelLike/comments/1uze7ch/movies_that_feels_like_this/', 'https://www.reddit.com/gallery/1uze7ch', 'MoviesThatFeelLike', 'A request for movies that evoke a specific but unexpressed mood, likely inspired by an image or shared context.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (316, '1uzevds', 'Old, whimsical, colorful, fantastical', 'Old, whimsical, colorful, fantastical', 'Wizard of Oz, Willow, Labyrinth, and Babes in Toyland.

My toddler loves movies like this. The pattern I''ve noticed is they are whimsical and fantastical. The acting is typically more theatrical. The effects are all practical. Lots of color and over-the-top elements. Another thing is that these films are easy to follow without having to understand the dialogue fully. He can get the gist of the story by watching their facial expressions and hearing their tone. Music is optional. 

We''ve tried Willy Wonka and the Chocolate Factory, but that one is a bit dialogue heavy and very dependent on undertones and cynicism. A little over his head at this age. 

We''ve tried newer films, but the CG doesn''t grab him and he doesn''t get as invested in the story. When he''s watching these older ones, he''ll frequently comment about it to us and speak to the TV. (He was very concerned about Toto during the Wizard of Oz. 😅)', 'TheMothGhost', 1784328905, '/r/MoviesThatFeelLike/comments/1uzevds/old_whimsical_colorful_fantastical/', 'https://www.reddit.com/gallery/1uzevds', 'MoviesThatFeelLike', 'A parent seeking whimsical, colorful, and fantastical movies with practical effects that are easy for a toddler to follow visually.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (317, '1uzha6k', 'movies or shows like Logan Lucky (2017)', 'Recommendations similar to Logan Lucky', 'other than talladega nights LMAO

crime, americana, family oriented? even anything visually similar, this movie just tickles my fancy and i need to be tickled MORE', 'imenjoyingthis2much', 1784335226, '/r/MoviesThatFeelLike/comments/1uzha6k/movies_or_shows_like_logan_lucky_2017/', 'https://www.reddit.com/gallery/1uzha6k', 'MoviesThatFeelLike', 'Craving for crime, Americana, and family-oriented heist films with a Southern charm and lighthearted vibe.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (318, '1uzhv9y', 'I need more of Psychological Thrillers films that certainly will blew your mind', '', 'Something fresh, underrated

(already watched most of David Lynch filmography)', 'Tall_Cranberry_4798', 1784336884, '/r/MoviesThatFeelLike/comments/1uzhv9y/i_need_more_of_psychological_thrillers_films_that/', 'https://www.reddit.com/gallery/1uzhv9y', 'MoviesThatFeelLike', 'A post seeking fresh and underrated psychological thrillers that will blow your mind, with a preference for non-Lynch films. The community offers a wide range of mind-bending and obscure titles.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (319, '1uzi91y', 'Unabashed hopecore like Project Hail Mary', '', 'Hello! I am looking for other movies that feel unambiguously hopeful most if not all of the way through, bonus points if it’s space ish. ', 'Aqueraventus', 1784337965, '/r/MoviesThatFeelLike/comments/1uzi91y/unabashed_hopecore_like_project_hail_mary/', 'https://i.redd.it/czsdzifv4wdh1.jpeg', 'MoviesThatFeelLike', 'A collection of unapologetically hopeful films that inspire optimism, many with a space or cosmic theme.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (320, '1uzl8gz', 'Movies in the untamed wilderness', '', '', 'Working_Welder_1751', 1784346764, '/r/MoviesThatFeelLike/comments/1uzl8gz/movies_in_the_untamed_wilderness/', 'https://www.reddit.com/gallery/1uzl8gz', 'MoviesThatFeelLike', 'A collection of movie recommendations centered around survival, adventure, and the harsh beauty of the untamed wilderness, from classic epics to modern thrillers.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (321, '1uzlwyo', 'a night to remember...', 'a night to remember', '', 'Malboro_N1ghts021', 1784348802, '/r/MoviesThatFeelLike/comments/1uzlwyo/a_night_to_remember/', 'https://www.reddit.com/gallery/1uzlwyo', 'MoviesThatFeelLike', 'A nostalgic and heartfelt memory of a special night that left a lasting impression.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (322, '1uzlywb', 'a night to remember...', 'a night to remember...', '', 'Malboro_N1ghts021', 1784348976, '/r/MoviesThatFeelLike/comments/1uzlywb/a_night_to_remember/', 'https://www.reddit.com/gallery/1uzlywb', 'MoviesThatFeelLike', 'A night that lingers in memory, filled with emotion and atmosphere.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (323, '1uzncui', 'Suggest me Sci-Fi,Fiction,adventure and thriller movie or tv series', '', '&#x200B;

PLEASE SUGGEST MOVIES OR SERIES THAT ARE IN 80S,90S OR BEFORE THAT ', 'The_Lazy_Ambivert', 1784353330, '/r/MoviesThatFeelLike/comments/1uzncui/suggest_me_scififictionadventure_and_thriller/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uzncui/suggest_me_scififictionadventure_and_thriller/', 'MoviesThatFeelLike', 'A request for nostalgic sci-fi and thriller movies and TV series from the 80s and 90s, with commenters suggesting classic space operas and cyberpunk adventures.', 'skipped', 'no usable images', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (324, '1uzoknp', 'Movies with devastating karaoke scenes', '', '', 'BitOk8599', 1784357337, '/r/MoviesThatFeelLike/comments/1uzoknp/movies_with_devastating_karaoke_scenes/', '/r/u_BitOk8599/comments/1uzok1o/movies_with_devastating_karaoke_scenes/', 'MoviesThatFeelLike', 'A collection of films with emotionally crushing karaoke or club scenes that evoke deep sadness or nostalgia.', 'skipped', 'no usable images', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (325, '1uzolom', 'Movies that feel like this?', 'Movies that feel like this?', '', 'regression-analysis', 1784357433, '/r/MoviesThatFeelLike/comments/1uzolom/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1uzolom', 'MoviesThatFeelLike', 'A collection of epic historical and legendary films, recommended in response to a request for movies with a grand, adventurous, and ancient-world feel.', 'skipped', 'no usable images', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (326, '1uzqqf0', 'movie feel like this', '', 'watch dogs 2', 'daddylongjohnsliver', 1784364849, '/r/MoviesThatFeelLike/comments/1uzqqf0/movie_feel_like_this/', 'https://www.reddit.com/gallery/1uzqqf0', 'MoviesThatFeelLike', 'A tech-savvy, hacker-themed urban adventure with a light-hearted, rebellious tone.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (327, '1uztnqz', 'Trying to find a movie: a horned man asks a woman to show him her new scar in the opening scene', 'Trying to find a movie: a horned man asks a woman to show him her new scar in the opening scene', '', 'f1erce_74', 1784374945, '/r/MoviesThatFeelLike/comments/1uztnqz/trying_to_find_a_movie_a_horned_man_asks_a_woman/', '/r/whatmoviewasthat/comments/1uzt12i/trying_to_find_a_movie_a_horned_man_asks_a_woman/', 'MoviesThatFeelLike', 'The post evokes a sense of eerie mystery, as the opening scene depicts a horned man requesting to see a woman''s new scar, hinting at a dark and intriguing narrative.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (328, '1uzwsqi', 'The Last Refuge - 18 x 24 inches - acrylic on canvas', '', '', 'metropolitanpuddle', 1784383510, '/r/MoviesThatFeelLike/comments/1uzwsqi/the_last_refuge_18_x_24_inches_acrylic_on_canvas/', 'https://i.redd.it/u6arf33h0zdh1.jpeg', 'MoviesThatFeelLike', 'A sense of final sanctuary, peaceful yet melancholic, evoking solitude and safety.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (329, '1uzwuij', 'Mountains, hiking, nighttime, seeking shelter', 'Mountains, hiking, nighttime, seeking shelter', '', 'metropolitanpuddle', 1784383639, '/r/MoviesThatFeelLike/comments/1uzwuij/mountains_hiking_nighttime_seeking_shelter/', 'https://i.redd.it/u6arf33h0zdh1.jpeg', 'MoviesThatFeelLike', 'A tense and isolated survival atmosphere set in cold, mountainous terrain, often involving hiking and seeking shelter at night.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (330, '1uzxyze', 'Movies that feel like BTAS', 'Movies that feel like BTAS', '', 'Anonymous___0522', 1784386381, '/r/MoviesThatFeelLike/comments/1uzxyze/movies_that_feel_like_btas/', 'https://www.reddit.com/gallery/1uzxyze', 'MoviesThatFeelLike', 'A request for movies that capture the dark, art-deco noir atmosphere of Batman: The Animated Series.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (331, '1uzykdi', 'Movies that feel like Spore', 'Movies that feel like Spore', '', 'TriggerHappyGremlin', 1784387802, '/r/MoviesThatFeelLike/comments/1uzykdi/movies_that_feel_like_spore/', 'https://www.reddit.com/gallery/1uzykdi', 'MoviesThatFeelLike', 'Movies that capture the evolutionary wonder and creative spirit of the Spore video game, blending cosmic exploration, biological mutation, and whimsical adventures.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (332, '1uzzgxk', 'Movies with this vibe?', 'Movies with this vibe?', '', 'Accomplished-City959', 1784389983, '/r/MoviesThatFeelLike/comments/1uzzgxk/movies_with_this_vibe/', 'https://www.reddit.com/gallery/1uzzgxk', 'MoviesThatFeelLike', 'A neon-soaked, party-centric world of glamorous excess, youthful rebellion, and dark undertones.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (333, '1v01mt8', 'Movies with this feel', 'Movies with this feel', '', 'JohnnyMoxRIP', 1784395083, '/r/MoviesThatFeelLike/comments/1v01mt8/movies_with_this_feel/', 'https://i.redd.it/ssobp6upu0eh1.jpeg', 'MoviesThatFeelLike', 'A gritty mix of crime dramas, neo-noir thrillers, and cult classics with a Southern or retro aesthetic.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (334, '1v026lt', 'Movies that feel like Man vs Nature', 'Movies that feel like Man vs Nature', 'Looking for movies where the main conflict is literally humans trying to survive against nature. Stuff like:

Everest (2015)  
Send Help (2026)  
The Edge (1997)  
Jungle (2017)  
Vertical Limit (2000)  
I shouldn’t be alive (2005)  
127 Hours (2010)', 'Ordinary-Gal', 1784396364, '/r/MoviesThatFeelLike/comments/1v026lt/movies_that_feel_like_man_vs_nature/', 'https://www.reddit.com/gallery/1v026lt', 'MoviesThatFeelLike', 'A collection of survival films where the main conflict is humans versus the natural elements, featuring stories of endurance against harsh environments, true events, and life-or-death struggles.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (335, '1v03pva', 'Films with Forced Wedding aka ''And Now You Must Marry Me'' Trope', '', 'Any films that may have this trope at all. Basically, if a woman (or man) is being forced into a wedding against their will, with perhaps someone coming in to save the day at the last moment, or perhaps it goes through and they are doomed to eternal misery. 

Bonus points for International cinema finds. ', 'macgregorc93', 1784399925, '/r/MoviesThatFeelLike/comments/1v03pva/films_with_forced_wedding_aka_and_now_you_must/', 'https://www.reddit.com/gallery/1v03pva', 'MoviesThatFeelLike', 'A diverse collection of films featuring the forced wedding trope, ranging from classic fairy tales to tragic dramas.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (336, '1v03ubv', 'Movies that take place in apartment blocks like this', 'Movies that take place in apartment blocks like this', '', 'SpaceTranquil', 1784400220, '/r/MoviesThatFeelLike/comments/1v03ubv/movies_that_take_place_in_apartment_blocks_like/', 'https://i.redd.it/mze6r29y91eh1.jpeg', 'MoviesThatFeelLike', 'A gritty, claustrophobic atmosphere of brutalist housing estates, filled with tension, despair, and survival stories.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (337, '1v05tch', 'Gdzie mogę obejrzec za darmo bully', 'Gdzie mogę obejrzec za darmo bully', 'gdzie mogę obejrzeć bully może za darmo', 'Ornery_Context7349', 1784404905, '/r/MoviesThatFeelLike/comments/1v05tch/gdzie_mogę_obejrzec_za_darmo_bully/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v05tch/gdzie_mogę_obejrzec_za_darmo_bully/', 'MoviesThatFeelLike', 'A frustrated search for a free stream, met with dismissive coldness.', 'skipped', 'no usable images', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (338, '1v05ybn', 'Movies & shows about surfing & beach life', 'Movies & shows about surfing & beach life', 'Beautiful shots, atmospheric, immersive, contemplative. Towns, lagoons, inlets, islets, islands, swimming, surfing, boat rides, exploration. Intimate, tender moments. Both living with the characters as well as following a narrative. No matter the depth or simplicity of it; What matters is that it''s interesting and fun to watch.

Documentaries & anime, too. I don''t mind lol.

  
I''ve already watched The Beach (2000), The Blue Lagoon (1980), Aftersun (2022). All great and worth rewatching. I have my eye on Pacifiction (2022).', 'Fair_Associate7883', 1784405230, '/r/MoviesThatFeelLike/comments/1v05ybn/movies_shows_about_surfing_beach_life/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v05ybn/movies_shows_about_surfing_beach_life/', 'MoviesThatFeelLike', 'Atmospheric, contemplative, and immersive beach life films with intimate moments and a sense of exploration.', 'skipped', 'no usable images', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (339, '1v072l0', 'fav movies of this girl?', 'fav movies of this girl?', '', 'trophymermaid', 1784407972, '/r/MoviesThatFeelLike/comments/1v072l0/fav_movies_of_this_girl/', 'https://i.redd.it/onqtjye1x1eh1.jpeg', 'MoviesThatFeelLike', 'Inquisitive tone, seeking personal movie preferences.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (340, '1v086v4', 'Movies that look and feel like this', 'Movies that look and feel like this', '', 'KevinHarryPhoto', 1784410816, '/r/MoviesThatFeelLike/comments/1v086v4/movies_that_look_and_feel_like_this/', 'https://i.redd.it/fx9r521i52eh1.jpeg', 'MoviesThatFeelLike', 'A request for visually stunning wuxia films with poetic action and rich colors, reminiscent of Zhang Yimou and Wong Kar-wai''s works.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (341, '1v08ggc', 'Movies that feel like summertime at the lake', '', '', 'PalmPine69', 1784411493, '/r/MoviesThatFeelLike/comments/1v08ggc/movies_that_feel_like_summertime_at_the_lake/', 'https://www.reddit.com/gallery/1v08ggc', 'MoviesThatFeelLike', 'A nostalgic collection of films that capture the sun-drenched, lazy days of lakeside summers, evoking feelings of warmth, first love, and bittersweet endings.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (342, '1v09ke1', 'What movie comes to mind when you see these images?', '', '', 'Jealous-Hurry1316', 1784414355, '/r/MoviesThatFeelLike/comments/1v09ke1/what_movie_comes_to_mind_when_you_see_these_images/', 'https://www.reddit.com/gallery/1v09ke1', 'MoviesThatFeelLike', 'A neon-drenched, hedonistic nightlife where glamour and danger intertwine, evoking feelings of intoxicating beauty and underlying menace.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (343, '1v09v8w', 'Movies like this', '', '', 'Idek163', 1784415189, '/r/MoviesThatFeelLike/comments/1v09v8w/movies_like_this/', 'https://www.reddit.com/gallery/1v09v8w', 'MoviesThatFeelLike', 'A nostalgic collection of early 2000s teen comedies and dramas, evoking a sense of youthful, carefree fun.', 'publishable', NULL, NULL, '2026-07-20 01:02:04', '2026-07-20 01:02:04');
