-- 0023_seed_20260720T040203Z_01_posts.sql: data seed from pipeline:load run.
-- Generated:  2026-07-20T04:02:06.397522+00:00
-- Run started: 2026-07-20T04:02:03.433040+00:00
-- Source: data/working/load manifest from this run.
--
-- Idempotent: every INSERT is INSERT OR IGNORE, keyed by the
-- table's natural unique constraint.  Wrangler's migration
-- tracking normally prevents re-apply; the OR IGNORE is
-- defense in depth for partial / interrupted re-runs.
--
-- Chunk: 01_posts (1/5)
-- Tables: imported_vibe_posts.
-- Pipeline-state tables (processing_runs, pipeline_artifacts)
-- are intentionally excluded — they're per-run bookkeeping.

INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (344, '1uvga06', 'Movie that has father-daughter/son relationship', '', 'i seen aftersun, interstellar and beautiful boy, i need more. Any suggestions? something underrated', 'Tall_Cranberry_4798', 1783959763, '/r/MoviesThatFeelLike/comments/1uvga06/movie_that_has_fatherdaughterson_relationship/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uvga06/movie_that_has_fatherdaughterson_relationship/', 'MoviesThatFeelLike', 'A request for emotional and underrated movies focusing on father-child relationships, evoking a sense of longing and nostalgia.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (345, '1uvgcrw', 'Movies like this', 'Dark gangsters sitting in a car in the rain', 'Lie dark gangsters sat in a car while its raining', 'Sorry_Towel7478', 1783959932, '/r/MoviesThatFeelLike/comments/1uvgcrw/movies_like_this/', 'https://www.reddit.com/gallery/1uvgcrw', 'MoviesThatFeelLike', 'Dark, rainy city nights with gangsters and suspense, evoking a noirish, thriller atmosphere.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (346, '1uvgcva', 'Movie that has father-daughter/son relationship', 'Movie that has father-daughter/son relationship', 'I seen aftersun & Beautiful boy, i need more. Anything would be appreciated, something underrated/indie', 'Tall_Cranberry_4798', 1783959937, '/r/MoviesThatFeelLike/comments/1uvgcva/movie_that_has_fatherdaughterson_relationship/', 'https://www.reddit.com/gallery/1uvgcva', 'MoviesThatFeelLike', 'A heartfelt and emotional thread seeking underrated indie movies about father-daughter/son relationships. The recommendations are deeply touching and often gut-wrenching, focusing on family bonds and poignant storytelling.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (347, '1uvi1lt', 'Movies about depression in women?', 'Movies about depression in women?', 'Most movies I''ve watched about depression and suicidal ideation are centered on male characters

I''m not saying that''s a bad thing, I just want to see more movies about depression in women', '11_16', 1783963515, '/r/MoviesThatFeelLike/comments/1uvi1lt/movies_about_depression_in_women/', 'https://i.redd.it/v5ac89yf71dh1.jpeg', 'MoviesThatFeelLike', 'A post seeking movie recommendations that depict depression and suicidal ideation in women, expressing a desire for more female-centered narratives in mental health cinema.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (348, '1uvii2q', 'Any movie with dark/gothic western vibe', '', 'Yeah, as you can tell im playing Hunt Showdown and i wanna get into the dark/gothic vibe western vibe of the game', 'Careful_Efficiency42', 1783964481, '/r/MoviesThatFeelLike/comments/1uvii2q/any_movie_with_darkgothic_western_vibe/', 'https://www.reddit.com/gallery/1uvii2q', 'MoviesThatFeelLike', 'A dark and gritty atmosphere blending gothic horror with western elements, evoking the eerie, supernatural feel of the game Hunt: Showdown.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (349, '1uvj1p2', 'What is a movie that completely changes genres or vibes halfway through?', 'Movie that completely changes genres or vibes halfway through', 'I''m looking for movies that start as one thing (like a romance, comedy, or normal drama) but suddenly take a massive, unexpected turn into horror, thriller, or sci-fi. I really love that feeling when a film completely flips the script and catches the audience off guard, changing the entire atmosphere, lighting, and stakes halfway through the story. 

Please don''t post any major spoilers, just drop the titles of the films! I want to go into these movies as blind as possible to get the full experience. It can be from any language or era, as long as the genre shift is dramatic and well-executed. What are your absolute best recommendations for this specific trope? ', 'Dalyy6002', 1783965631, '/r/MoviesThatFeelLike/comments/1uvj1p2/what_is_a_movie_that_completely_changes_genres_or/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uvj1p2/what_is_a_movie_that_completely_changes_genres_or/', 'MoviesThatFeelLike', 'A post seeking movies with dramatic genre shifts, with commenters enthusiastically recommending films that surprise and disorient, creating a mood of anticipation and delight in the unexpected.', 'skipped', 'no usable images', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (350, '1uvj5hu', 'Movies or documentries or series that feel like don''t fck with cats(documentry)....in love with true crime', '', 'Just as title.... It should be thrilling tho', 'Fabulous_Rain3845', 1783965851, '/r/MoviesThatFeelLike/comments/1uvj5hu/movies_or_documentries_or_series_that_feel_like/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uvj5hu/movies_or_documentries_or_series_that_feel_like/', 'MoviesThatFeelLike', 'A request for thrilling true crime documentaries and series similar to ''Don''t Fck With Cats'', with a focus on suspense and investigation.', 'skipped', 'no usable images', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (351, '1uvjom8', 'Movies that feel like CIA conspiracy horror/mystery?', 'Movies that feel like CIA conspiracy horror/mystery?', '', 'SpinachWomb', 1783966969, '/r/MoviesThatFeelLike/comments/1uvjom8/movies_that_feel_like_cia_conspiracy_horrormystery/', 'https://www.reddit.com/gallery/1uvjom8', 'MoviesThatFeelLike', 'A request for movies that evoke paranoia, secrecy, and government conspiracies, blending horror and mystery elements.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (352, '1uvlmur', 'Movies that have a Creepy Summer vibe ?', 'Movies that have a Creepy Summer vibe', 'Main inspo is a Gregory Crewdson photograph. I just watched obsession, and am still missing stranger things. Something exciting, even supernatural would be fun! ', 'discreetPeach2979', 1783971096, '/r/MoviesThatFeelLike/comments/1uvlmur/movies_that_have_a_creepy_summer_vibe/', 'https://www.reddit.com/gallery/1uvlmur', 'MoviesThatFeelLike', 'A craving for films that evoke a creepy, muggy summer atmosphere with supernatural or thrilling elements, reminiscent of Gregory Crewdson''s photography.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (353, '1uvm17l', 'any movies that give off this vibe?', 'any movies that give off this vibe?', '[deleted]', '[deleted]', 1783971945, '/r/MoviesThatFeelLike/comments/1uvm17l/any_movies_that_give_off_this_vibe/', '', 'MoviesThatFeelLike', 'A mysterious and unstated atmosphere, leaving room for personal interpretation.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (354, '1uvm1pc', 'any movies that give off this vibe?', 'Movies that give off this vibe', '', 'kinginacity', 1783971977, '/r/MoviesThatFeelLike/comments/1uvm1pc/any_movies_that_give_off_this_vibe/', 'https://www.reddit.com/gallery/1uvm1pc', 'MoviesThatFeelLike', 'A collection of films that evoke a sense of awe, mystery, and isolation, set against dramatic coastal, mountainous, or alien landscapes, often with supernatural or survival elements.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (355, '1uvmbxj', 'Movie that feels like this.. 🦉', '', '', 'Snake_Charmers', 1783972566, '/r/MoviesThatFeelLike/comments/1uvmbxj/movie_that_feels_like_this/', 'https://www.reddit.com/gallery/1uvmbxj', 'MoviesThatFeelLike', 'Tense isolation and home invasion horror with a lone protagonist fighting for survival in a remote setting.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (356, '1uvon4j', 'A sense of enormity, impossible dread, vast yet claustrophobic. Unyielding and suffocating but beautiful', 'A sense of enormity, impossible dread, vast yet claustrophobic. Unyielding and suffocating but beautiful', '', 'battlebun1516', 1783977601, '/r/MoviesThatFeelLike/comments/1uvon4j/a_sense_of_enormity_impossible_dread_vast_yet/', 'https://www.reddit.com/gallery/1uvon4j', 'MoviesThatFeelLike', 'An overwhelming sense of cosmic dread and claustrophobic vastness, where beauty and suffocation coexist in unyielding despair.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (357, '1uvpseh', 'Movies like this the odds against you', 'Movies like this the odds against you', '', 'musicismytherapy-', 1783980185, '/r/MoviesThatFeelLike/comments/1uvpseh/movies_like_this_the_odds_against_you/', 'https://v.redd.it/kw85tgwyk2dh1', 'MoviesThatFeelLike', 'A tense and determined atmosphere, evoking the struggle against overwhelming odds, with a focus on perseverance and underdog resilience.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (358, '1uvqjbu', 'movies with a survival / manhunt theme set in the wilderness', 'movies with a survival / manhunt theme set in the wilderness', 'https://preview.redd.it/1zm6itmrp2dh1.png?width=650&format=png&auto=webp&s=4da562f77806d843c3b95d2cfbef3564b8a15b35

https://preview.redd.it/g4ixhsysp2dh1.png?width=396&format=png&auto=webp&s=4841d904d2b9a038cde809fcda6f66362fc29030

https://preview.redd.it/lcjpom1vp2dh1.png?width=1200&format=png&auto=webp&s=53a22d82391079432a051da290c3dfc370175dbf

https://preview.redd.it/9g0vbopvp2dh1.png?width=960&format=png&auto=webp&s=0afb39058fca0a4f392d2dafa90b057b76a23847

https://preview.redd.it/j59g55z8q2dh1.png?width=736&format=png&auto=webp&s=6d8377be880915a19cb7d5afc6d60ddc7a9d20e4

https://preview.redd.it/h0g5mxj9q2dh1.png?width=1200&format=png&auto=webp&s=d1f301b99f0e8bf6d6f92cd5a036ac77cde497dc

', 'eletronicdesire', 1783981970, '/r/MoviesThatFeelLike/comments/1uvqjbu/movies_with_a_survival_manhunt_theme_set_in_the/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uvqjbu/movies_with_a_survival_manhunt_theme_set_in_the/', 'MoviesThatFeelLike', 'A collection of movies that capture the raw tension of survival and pursuit in the unforgiving wilderness.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (359, '1uvqwoy', 'This', 'This', '', 'Jellypathicdream', 1783982871, '/r/MoviesThatFeelLike/comments/1uvqwoy/this/', 'https://i.redd.it/w7i1fiwzs2dh1.jpeg', 'MoviesThatFeelLike', 'A wistful, snow-covered atmosphere invoking loneliness, introspection, and eerie beauty.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (360, '1uvrnbk', 'Movies that feel like a Molchat Doma song(besides bladerunner)', 'Movies that feel like a Molchat Doma song (besides Blade Runner)', '', 'dmnwilson44', 1783984734, '/r/MoviesThatFeelLike/comments/1uvrnbk/movies_that_feel_like_a_molchat_doma_songbesides/', 'https://www.reddit.com/gallery/1uvrnbk', 'MoviesThatFeelLike', 'Cold, atmospheric, Soviet-era melancholy with a bleak yet captivating beauty.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (361, '1uvrp21', 'Movies that feel like this', 'Movies that feel like this', '3,4,5,6 by jakub rozalski', 'espertempX2', 1783984852, '/r/MoviesThatFeelLike/comments/1uvrp21/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1uvrp21', 'MoviesThatFeelLike', 'Epic historical and fantasy atmospheres with desolate landscapes and large-scale conflicts, inspired by Jakub Rozalski''s images.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (362, '1uvs3yd', 'Movies that feel like this', 'Movies that feel like this', '', 'Jazz4ursoul', 1783985906, '/r/MoviesThatFeelLike/comments/1uvs3yd/movies_that_feel_like_this/', 'https://i.redd.it/tsuh11w023dh1.jpeg', 'MoviesThatFeelLike', 'A chaotic and high-energy collection of absurd comedies, capturing over-the-top reactions and outrageous humor typical of late 90s and 2000s stoner/party movies.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (363, '1uvtndc', 'A non-gory film where the horror is explained and logical', 'A non-gory film where the horror is explained and logical', 'My initial idea was animatronic horror—kind of like "Five Nights at Freddy''s" but without the supernatural elements—but if you know of anything else in that vein, feel free to suggest it!

It''s worth noting that since I''m a bit of a scaredy-cat and gore doesn''t really appeal to me, I''m looking more for psychological horror', 'Big-Tax-8921', 1783989928, '/r/MoviesThatFeelLike/comments/1uvtndc/a_nongory_film_where_the_horror_is_explained_and/', 'https://www.reddit.com/gallery/1uvtndc', 'MoviesThatFeelLike', 'A cautious horror enthusiast seeks unnerving yet explainable scares, with an emphasis on psychological tension and animatronic horror, avoiding gore and supernatural elements.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (364, '1uvwt2j', 'Like Sissy (2022)', 'Like Sissy 2022', 'Hi guys! I''m trying to find movies with the similar colors, aesthetic, and cinematography like Sissy.', 'nymphpie', 1783998560, '/r/MoviesThatFeelLike/comments/1uvwt2j/like_sissy_2022/', 'https://www.reddit.com/gallery/1uvwt2j', 'MoviesThatFeelLike', 'A request for movies with vibrant colors and stylish cinematography similar to ''Sissy''.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (365, '1uvy03r', 'Stories that utilize some of Warhammer''s elements (War not included)', 'Stories that utilize some of Warhammer''s elements (War not included)', '', 'LeonardoKlotzTomaz', 1784002063, '/r/MoviesThatFeelLike/comments/1uvy03r/stories_that_utilize_some_of_warhammers_elements/', 'https://www.reddit.com/gallery/1uvy03r', 'MoviesThatFeelLike', 'A search for stories that capture the grimdark, religious, and dystopian essence of Warhammer 40k while avoiding direct warfare, focusing on themes of hellish space travel, oppressive regimes, and cosmic horror.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (366, '1uvz77c', 'Movies/games that feel like this', 'Movies/games that feel like this', 'Just wanna find some movies/games with this vibe', 'catholic_batman', 1784005746, '/r/MoviesThatFeelLike/comments/1uvz77c/moviesgames_that_feel_like_this/', 'https://www.reddit.com/gallery/1uvz77c', 'MoviesThatFeelLike', 'A longing for movies and games set in dystopian cyberpunk worlds with towering megastructures and gritty, atmospheric sci-fi.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (367, '1uw0g1j', 'Movies themed around surgery and modifications', '', 'Hey all! Looking for movies with subjects around surgery aesthetics around elective surgery and body modifications. Some examples that scratch this itch are Repo! The Genetic Opera and American Mary. I''m not just looking for unethical doctors (we mildly considered putting Reanimator on the list, but not quite the vibe) but the surgeries themselves. Thanks!', 'bone_thaddy', 1784009848, '/r/MoviesThatFeelLike/comments/1uw0g1j/movies_themed_around_surgery_and_modifications/', 'https://i.redd.it/roqjlbs715dh1.jpeg', 'MoviesThatFeelLike', 'A craving for the visceral and aesthetic experience of elective surgery and body modification, blending horror, transgression, and dark beauty.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (368, '1uw1fnd', 'Movies that start off normal and realistic, but something supernatural happens midway through and the entire vibe changes', 'Movies that start off normal and realistic, but something supernatural happens midway through and the entire vibe changes', '', 'Original-Tax1392', 1784013169, '/r/MoviesThatFeelLike/comments/1uw1fnd/movies_that_start_off_normal_and_realistic_but/', 'https://i.redd.it/se1ol573b5dh1.jpeg', 'MoviesThatFeelLike', 'A collection of films that transition from a grounded, realistic setting to a supernatural or otherworldly twist, altering the overall mood and genre.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (369, '1uw1m0s', 'Movies that feels like this', 'Movies that feel like this', 'Movies where the main character is left alone and has to survive on their own', 'Minimum_Store8439', 1784013777, '/r/MoviesThatFeelLike/comments/1uw1m0s/movies_that_feels_like_this/', 'https://i.redd.it/g3323h9wc5dh1.jpeg', 'MoviesThatFeelLike', 'A request for survival films where the protagonist is utterly alone and must rely on themselves to endure harsh circumstances.', 'skipped', 'no usable images', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (370, '1uw3b3b', 'Something Movie/series close to the horror shown in The Walten Files?', 'Something Movie series close to the horror shown in The Walten Files', '', 'AipomSilver00', 1784019758, '/r/MoviesThatFeelLike/comments/1uw3b3b/something_movieseries_close_to_the_horror_shown/', 'https://www.reddit.com/gallery/1uw3b3b', 'MoviesThatFeelLike', 'A request for movies or series that evoke the same unsettling, analog horror atmosphere as The Walten Files.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (371, '1uw3fx0', 'What is her name', 'What is her name', '[removed]', 'Aggravating_Gas_3511', 1784020229, '/r/MoviesThatFeelLike/comments/1uw3fx0/what_is_her_name/', 'https://www.reddit.com/gallery/1uw3fx0', 'MoviesThatFeelLike', 'A quiet, persistent curiosity hangs in the void, seeking an identity that remains just beyond reach.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (372, '1uw4940', 'Was the music the best part of Pritam and Pedro?', 'Was the music the best part of Pritam and Pedro?', '', 'khushijogani7877', 1784023104, '/r/MoviesThatFeelLike/comments/1uw4940/was_the_music_the_best_part_of_pritam_and_pedro/', 'https://v.redd.it/oycfjndm46dh1', 'MoviesThatFeelLike', 'A reflective question about the emotional power of music, hinting at a story where soundtracks outshine other elements.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (373, '1uw4rls', 'If we had a different version of Caddyshack film who would have played Maggie instead of Sarah Holcomb and who would have played Cindy Morgan''s character Lacey?', 'If we had a different version of Caddyshack film who would have played Maggie instead of Sarah Holcomb and who would have played Cindy Morgan''s character Lacey?', 'They were both great as the characters in Caddyshack, but can you guys imagine different actress playing them instead back in 1980 and what if Sarah and Cindy both turned down Caddyshack and Sarah does either Private Benjamin or Airplane instead and Cindy does another role maybe like Stri Crazy film or Stripes.

Here are my list who would have played them starting with Maggie, I think people like Ally Sheedy, Lisa Baur who plays Shelly from Animal House, That lady who plays Dean''s Secretary from Animal House, Jane Curtin from Saturday Night Live, That Sales girl from the toy shop in The Blues Brothers film, Eliza Roberts, Martha Smith who plays Babs also from Animal House, Aseneth Jurgenson who plays Beth and Katerine Denning who plays Noreen also from Animal House. I feel like one of them would be perfect fit as Maggie as well since they are nervous and awkward like Maggie during the scene in road trip and the Otis Day club. Also last one is PJ Soles but unsure because I think she had kind of the vibe of Maggie in Private Benjamin since they were both awkward kind of. Also Cindy Grover, those of you guys might remember her from Network film and Jaws 2.

For Cindy Morgan''s character Lacey, I think Molly Ringwald would have been great or Demi Moore or that lady Lari Taylor who was the big daughter sitting next to her father in The Blues Brothers film in the dinner table or maybe Lisa Baur or Daryl Hannah or Debra Winger or Jamie Lee Curits. Also I don''t know if you guys might know Cindy Luedke who plays Susan in her only one film Avalanche, she was Rock Hudson''s character''s secretary. But That Avalanche 1978 film was a huge flop. I think Cindy Luedke might have been forgotten by the public. I still put her on the list for Cindy Morgan''s character role.

So who do you guys pick between these ladies which one you think would be perfect fit as Maggie who is Sarah Holcomb''s character one side, the other side which ladies would a perfect fit as Lacey who is Cindy Morgan''s character. Well any suggestions about this?', 'JazzlikeTea7432', 1784024759, '/r/MoviesThatFeelLike/comments/1uw4rls/if_we_had_a_different_version_of_caddyshack_film/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uw4rls/if_we_had_a_different_version_of_caddyshack_film/', 'MoviesThatFeelLike', 'A speculative and nostalgic discussion about alternative casting for Caddyshack, intertwined with mentions of other 1980s comedies, but ultimately misplaced for the subreddit.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (374, '1uw7m31', 'Please recommend me movie universe like conjuring', 'Recommend me a movie universe like The Conjuring', '', 'demonkingte', 1784033000, '/r/MoviesThatFeelLike/comments/1uw7m31/please_recommend_me_movie_universe_like_conjuring/', '/r/u_demonkingte/comments/1uw7kod/please_recommend_me_movie_universe_like_conjuring/', 'MoviesThatFeelLike', 'A request for horror movie universes with interconnected supernatural stories, evoking a creepy and mysterious atmosphere.', 'skipped', 'no usable images', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (375, '1uw7rnt', 'Movie that feels like the upcoming movie Hope (2026)', 'Movie that feels like upcoming movie Hope 2026', 'Monsters hunting in a group.

See the aftermath of destruction.

The human is not too glazed by the plot but still manages to fight back.

Perfer if it was set in the countryside or a small town.

I''m just really like the premise and vibe of the trailer very much.', 'Typical_Ad9140', 1784033400, '/r/MoviesThatFeelLike/comments/1uw7rnt/movie_that_feels_like_the_upcoming_movie_hope_2026/', 'https://www.reddit.com/gallery/1uw7rnt', 'MoviesThatFeelLike', 'A search for tense, monster-hunting survival thrillers set in rural or small-town environments, focusing on group predation and human resilience.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (376, '1uw8iz4', 'Movies that give off this kind of adventure vibe', '', '', 'Motor_Speaker_8841', 1784035236, '/r/MoviesThatFeelLike/comments/1uw8iz4/movies_that_give_off_this_kind_of_adventure_vibe/', 'https://i.redd.it/mhjzzw7p47dh1.jpeg', 'MoviesThatFeelLike', 'A collection of movies and games that evoke a sense of adventure, often quiet and introspective, with themes of exploration and nature.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (377, '1uw8zhr', 'Movies that feel like this', '', 'Looking for movies with that cinda creepy but comforting Moomin / Tove Jansson vibes.', 'Scienceiscool_', 1784036344, '/r/MoviesThatFeelLike/comments/1uw8zhr/movies_that_feel_like_this/', 'https://i.redd.it/a5z2jrcr77dh1.jpeg', 'MoviesThatFeelLike', 'A request for movies that blend creepiness with comfort, evoking the whimsical yet eerie atmosphere of Moomin and Tove Jansson''s illustrations.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (378, '1uwaih4', 'Similar to this', '', 'Please not true detective season 1 ', 'CodGroundbreaking803', 1784039804, '/r/MoviesThatFeelLike/comments/1uwaih4/similar_to_this/', 'https://www.reddit.com/gallery/1uwaih4', 'MoviesThatFeelLike', 'A request for dark, psychological crime thrillers similar to True Detective season 1. The recommendations lean toward gritty, suspenseful mysteries with a noir feel.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (379, '1uwaqe3', 'Movies with this vibe', 'Movies with this vibe', '', 'umbertocsaba', 1784040295, '/r/MoviesThatFeelLike/comments/1uwaqe3/movies_with_this_vibe/', 'https://www.reddit.com/gallery/1uwaqe3', 'MoviesThatFeelLike', 'A provocative blend of homoeroticism, youthful masculinity, and gritty hedonism, evoking the raw energy of college parties and coming-of-age angst.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (380, '1uwb692', 'Movies that would Fit this album', 'Movies that Would Fit this album', '', 'Imaginary-Bread9838', 1784041265, '/r/MoviesThatFeelLike/comments/1uwb692/movies_that_would_fit_this_album/', 'https://i.redd.it/l9xtv7qmm7dh1.jpeg', 'MoviesThatFeelLike', 'A request for movies that complement the mood of an album, with a suggestion of The Favourite.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (381, '1uwcc71', 'Movies that feel like the opening of Half-Life 1', 'Movies that feel like the opening of Half-Life 1', '', 'Asleep_Ad6304', 1784043808, '/r/MoviesThatFeelLike/comments/1uwcc71/movies_that_feel_like_the_opening_of_halflife_1/', 'https://i.redd.it/c2zds527u7dh1.jpeg', 'MoviesThatFeelLike', 'A collection of films that evoke the isolated, industrial, and eerie atmosphere of the opening sequence of Half-Life 1, featuring underground facilities, corporate conspiracies, and apocalyptic themes.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (382, '1uwcn7c', 'Why every forest looks same', '', 'Why in every movie and tv show the forest in USA ,us movie and maximum tv show always looks same type. Almost looks fake forest.

In other country movies or shoots location feels real. Any other countries show, movies forest looks real compare to Hollywood ', 'AmanYadav19', 1784044466, '/r/MoviesThatFeelLike/comments/1uwcn7c/why_every_forest_looks_same/', 'https://www.reddit.com/gallery/1uwcn7c', 'MoviesThatFeelLike', 'A sense of longing for authentic, diverse natural landscapes in film, overshadowed by the repetitive greenery of Hollywood''s go-to forests.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (383, '1uwe54n', 'Horror series/films similar to The Walten Files? I like the way the horror is shown and in general for me it represents an improved version of FNAF.', 'Horror series films similar to The Walten Files', 'Maybe the films/series even with totally different plots but I would like the way of showing horror to be similar to that of WF', 'AipomSilver00', 1784047632, '/r/MoviesThatFeelLike/comments/1uwe54n/horror_seriesfilms_similar_to_the_walten_files_i/', 'https://www.reddit.com/gallery/1uwe54n', 'MoviesThatFeelLike', 'Seeking atmospheric, analog horror with a focus on unsettling visuals and storytelling.', 'skipped', 'no usable images', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (384, '1uwfvxs', 'Movies that feel like this', 'Movies that feel like this', '', 'musicismytherapy-', 1784051346, '/r/MoviesThatFeelLike/comments/1uwfvxs/movies_that_feel_like_this/', 'https://v.redd.it/9w266k1eg8dh1', 'MoviesThatFeelLike', 'A request for movies that evoke a particular, unspecified feeling.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (385, '1uwgt11', 'A world hidden right under your nose.', 'A world hidden right under your nose', 'Games/Movies like:

[Men In Black](https://www.imdb.com/title/tt0119654/)

[R.I.P.D.](https://www.imdb.com/title/tt0790736/)

[League of Extraordinary Gentlemen](https://www.imdb.com/title/tt0311429/)', 'DaleGribbleShackle', 1784053212, '/r/MoviesThatFeelLike/comments/1uwgt11/a_world_hidden_right_under_your_nose/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uwgt11/a_world_hidden_right_under_your_nose/', 'MoviesThatFeelLike', 'A sense of hidden worlds and secret societies lurking beneath everyday reality, with recommendations of media that reveal the extraordinary concealed within the ordinary.', 'skipped', 'no usable images', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (386, '1uwi0zs', 'Movie that feels like this', 'Movie that feels like this', 'Something just chill and comforting idk 🤷‍♀️🤷‍♀️', 'CryGroundbreaking945', 1784055811, '/r/MoviesThatFeelLike/comments/1uwi0zs/movie_that_feels_like_this/', 'https://www.reddit.com/gallery/1uwi0zs', 'MoviesThatFeelLike', 'A request for a film that exudes a chill and comforting atmosphere, evoking a sense of cozy nostalgia.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (387, '1uwib44', 'Glamorous, retro, surreal', 'Glamorous retro surreal', '', 'lildixiedoodle', 1784056432, '/r/MoviesThatFeelLike/comments/1uwib44/glamorous_retro_surreal/', 'https://i.redd.it/m5qtqrgqv8dh1.jpeg', 'MoviesThatFeelLike', 'A dreamy fusion of glamorous, retro aesthetics and surreal, stylish cinema, evoking the visual and emotional allure of films like The Love Witch.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (388, '1uwjm5x', 'Movies that feel like FNV?', 'Movies that feel like Fallout: New Vegas?', 'Please give me movies that feel like new Vegas!! Also yes I have seen the show. ', 'Aqueraventus', 1784059342, '/r/MoviesThatFeelLike/comments/1uwjm5x/movies_that_feel_like_fnv/', 'https://www.reddit.com/gallery/1uwjm5x', 'MoviesThatFeelLike', 'Seeking movies that capture the essence of Fallout: New Vegas: a post-apocalyptic desert wasteland with western themes, retro-futuristic technology, and a darkly comedic tone.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (389, '1uwjpxz', 'Some magical ancient timeline drama movies.. that can make the mind travel there!!', 'Some magical ancient timeline drama movies that can make the mind travel there', '', 'Snake_Charmers', 1784059567, '/r/MoviesThatFeelLike/comments/1uwjpxz/some_magical_ancient_timeline_drama_movies_that/', 'https://www.reddit.com/gallery/1uwjpxz', 'MoviesThatFeelLike', 'A longing for movies that transport the mind to magical ancient worlds, blending drama and wonder.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (390, '1uwjvbs', 'Some ancient timeline drama with magic and fiction.. which makes the mind time travel', 'Some ancient timeline drama with magic and fiction which makes the mind time travel', '', 'Snake_Charmers', 1784059890, '/r/MoviesThatFeelLike/comments/1uwjvbs/some_ancient_timeline_drama_with_magic_and/', 'https://www.reddit.com/gallery/1uwjvbs', 'MoviesThatFeelLike', 'A desire for ancient mythological tales with magical elements that evoke a sense of time travel and epic fantasy.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (391, '1uwkc1g', 'Movies that feel like this?', 'Movies that feel like this?', '', 'umbertocsaba', 1784060971, '/r/MoviesThatFeelLike/comments/1uwkc1g/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1uwkc1g', 'MoviesThatFeelLike', 'A nostalgic, earthy mood evoking rural and urban Latin America, with raw, poetic, and often melancholic undertones.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (392, '1uwmh21', 'Campy and fun movies', 'Campy and fun movies', 'Looking for campy movies, examples of what I mean:
Beetlejuice 
Death becomes her
The witches of westwick
The love witch
Hocus pocus
The princess bride', 'himynameishuman2', 1784065780, '/r/MoviesThatFeelLike/comments/1uwmh21/campy_and_fun_movies/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uwmh21/campy_and_fun_movies/', 'MoviesThatFeelLike', 'A nostalgic craving for campy, fun, and over-the-top movies that are playful and unapologetically silly.', 'skipped', 'no usable images', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (393, '1uwmntu', 'Movies that feel peaceful and calm.', 'Movies that feel peaceful and calm.', '', 'Southern_Check_6827', 1784066204, '/r/MoviesThatFeelLike/comments/1uwmntu/movies_that_feel_peaceful_and_calm/', 'https://v.redd.it/fq9yc21jn9dh1', 'MoviesThatFeelLike', 'A gentle craving for films that radiate peace and calm, often set in serene natural landscapes.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (394, '1uwnlna', 'Movies that feels like this', 'Movies that feels like this', '', 'musicismytherapy-', 1784068401, '/r/MoviesThatFeelLike/comments/1uwnlna/movies_that_feels_like_this/', 'https://v.redd.it/zf8k2er3v9dh1', 'MoviesThatFeelLike', 'The post seeks movies that evoke a certain mood, likely melancholic or nostalgic, but the specific feeling is undefined.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (395, '1uwo2fu', 'Movies showing mathematical/scientific concepts being discovered. Not sci-fi.', 'Movies showing mathematical/scientific concepts being discovered. Not sci-fi.', 'Or shows ', 'WildCartographer5027', 1784069507, '/r/MoviesThatFeelLike/comments/1uwo2fu/movies_showing_mathematicalscientific_concepts/', 'https://www.reddit.com/gallery/1uwo2fu', 'MoviesThatFeelLike', 'A collection of biographical films depicting the human drama behind mathematical and scientific breakthroughs, from codebreaking to astrophysics.', 'skipped', 'no usable images', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (396, '1uwp7wu', 'LOST in these masterpieces', 'Lost in these masterpieces', '', 'last-Kauai', 1784072309, '/r/MoviesThatFeelLike/comments/1uwp7wu/lost_in_these_masterpieces/', 'https://www.reddit.com/gallery/1uw5g9l', 'MoviesThatFeelLike', 'A feeling of being utterly immersed and captivated by masterpieces, losing oneself in their beauty and depth.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (397, '1uwpi2e', 'What are your thougts on movie ''Paris, Texas''?', 'What are your thoughts on movie ''Paris, Texas''?', '[removed]', 'Necessary_Bother_875', 1784073041, '/r/MoviesThatFeelLike/comments/1uwpi2e/what_are_your_thougts_on_movie_paris_texas/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uwpi2e/what_are_your_thougts_on_movie_paris_texas/', 'MoviesThatFeelLike', 'A deep yearning to inhabit the world of a film, a desire for the cinematic experience to become reality.', 'skipped', 'no usable images', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (398, '1uwq38p', 'Movies that feel like fall', 'Movies that feel like fall', '', 'Anonymous___0522', 1784074527, '/r/MoviesThatFeelLike/comments/1uwq38p/movies_that_feel_like_fall/', 'https://www.reddit.com/gallery/1uwq38p', 'MoviesThatFeelLike', 'A request for movies that capture the essence of autumn—cozy, nostalgic, and slightly spooky.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (399, '1uwqwpz', 'Movies that feel like this?', 'Movies that feel like this', '', 'Neat_Ostrich9966', 1784076728, '/r/MoviesThatFeelLike/comments/1uwqwpz/movies_that_feel_like_this/', 'https://i.redd.it/ya7mwmu2kadh1.jpeg', 'MoviesThatFeelLike', 'A disorienting blend of mundane horror and surreal dread, evoking the tension of everyday nightmares.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (400, '1uwrflc', 'Movies or series with these vibez', 'Movies or series with these vibes', '', 'IWantTheBestForYOU', 1784078160, '/r/MoviesThatFeelLike/comments/1uwrflc/movies_or_series_with_these_vibez/', 'https://www.reddit.com/gallery/1uwrflc', 'MoviesThatFeelLike', 'A dark, edgy, and mind-bending atmosphere of late 90s and early 2000s punk and psychological thrillers, tinged with teen angst and cult classic nostalgia.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (401, '1uwtkhs', 'Movies with this kind of aesthetic besides Children Of Men?', 'Movies with this kind of aesthetic besides Children Of Men?', '', 'Garidur', 1784084160, '/r/MoviesThatFeelLike/comments/1uwtkhs/movies_with_this_kind_of_aesthetic_besides/', 'https://www.reddit.com/gallery/1uwtkhs', 'MoviesThatFeelLike', 'A request for grimy, dystopian, and noir-tinged films similar to the aesthetic of Children of Men.', 'skipped', 'no usable images', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (402, '1uwva1o', 'Looking for titles with real "aura"!', 'Looking for titles with real aura!', 'I''m looking for titles that have that certain aura – a specific feeling or vibe. It''s not really tied to adrenaline or testosterone, though I don''t mind that either — it can honestly just be about that feeling itself.

Mr. Robot is honestly a perfect example of what I mean. Here are a few more, a bit different in genre but still great examples: Top Gun: Maverick, American Assassin, Southpaw, and Hacksaw Ridge.

Any recommendations for similar titles?', 'Outside-Purple-2663', 1784089119, '/r/MoviesThatFeelLike/comments/1uwva1o/looking_for_titles_with_real_aura/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uwva1o/looking_for_titles_with_real_aura/', 'MoviesThatFeelLike', 'Films that exude a distinct, intense aura—moody, gripping, and atmospheric, blending tension with emotional weight.', 'skipped', 'no usable images', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (403, '1uwxot9', 'ENEMY 2013', '', '', 'raj722', 1784096814, '/r/MoviesThatFeelLike/comments/1uwxot9/enemy_2013/', 'https://v.redd.it/afzfk13j7cdh1', 'MoviesThatFeelLike', 'A suffocating atmosphere of paranoia and hidden truths envelops the scene, like a slow-burning nightmare.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (404, '1uwy80z', 'Movies like Doom', 'Movies like Doom', 'I''ve been playing Doom a lot. I need anything like this please. (Don''t make a redundant doom movie joke pls).', 'SpinachWomb', 1784098577, '/r/MoviesThatFeelLike/comments/1uwy80z/movies_like_doom/', 'https://www.reddit.com/gallery/1uwy80z', 'MoviesThatFeelLike', 'A request for high-octane, violent sci-fi/horror movies with a similar feel to the Doom video game, emphasizing gore, demons, and relentless action.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (405, '1uwyi10', 'Looking for movies with this vibe', '', 'I love berserk if that helps, dune too. What I’m looking for is visibly much weirder.', 'anuslitt', 1784099502, '/r/MoviesThatFeelLike/comments/1uwyi10/looking_for_movies_with_this_vibe/', 'https://www.reddit.com/gallery/1uwyi10', 'MoviesThatFeelLike', 'A request for films that are visibly weirder and more surreal than Dune and Berserk, evoking a dark, psychedelic, and epic fantasy atmosphere with strange landscapes and dreamlike imagery.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (406, '1uwynz4', 'Investigators who Investigate the Paranormal?', 'Investigators who Investigate the Paranormal?', '', 'hehzehsbwvwv', 1784100061, '/r/MoviesThatFeelLike/comments/1uwynz4/investigators_who_investigate_the_paranormal/', 'https://www.reddit.com/gallery/1uwtq3q', 'MoviesThatFeelLike', 'A desire for stories about investigators exploring paranormal phenomena, with a mix of horror, mystery, and supernatural elements.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (407, '1v0br9c', 'A warm Japanese summer', 'A warm Japanese summer', 'This could be a movie TV show cartoon anime IDC', 'HelpWithFicoReddit', 1784420209, '/r/MoviesThatFeelLike/comments/1v0br9c/a_warm_japanese_summer/', 'https://www.reddit.com/gallery/1v0br9c', 'MoviesThatFeelLike', 'A desire for media that captures the warm, comforting atmosphere of a Japanese summer.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (408, '1v0c2ys', 'Movies that feel like these?', '', '', 'secretly_lenin', 1784421125, '/r/MoviesThatFeelLike/comments/1v0c2ys/movies_that_feel_like_these/', 'https://www.reddit.com/gallery/1uy9wvh', 'MoviesThatFeelLike', 'A curious search for atmospheric films, evoking a sense of longing and exploration.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (409, '1v0c9i8', 'Movies that feel like Desert-Egypt', 'Movies that feel like Desert-Egypt', '', 'NoTabooGirl222', 1784421646, '/r/MoviesThatFeelLike/comments/1v0c9i8/movies_that_feel_like_desertegypt/', 'https://www.reddit.com/gallery/1v0c9i8', 'MoviesThatFeelLike', 'A mix of adventure, fantasy, and historical films set in or evoking the deserts of Egypt, from classic mummy tales to epic sandscapes.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (410, '1v0cyh8', 'Is it possible to find the Morally Grey Shadow Daddy, Monster, and/or Vampire Romance in a movie that I find in books in movies and shows? Recommendations below please?', 'Looking for Morally Grey Shadow Daddy/Monster/Vampire Romance in Movies and Shows', 'First part says it all but also I love gothic romances. I love beautifully dark cinematography. I love beautiful costume design too. Help? Recommendations appreciated! 🩸🖤 I’ve seen A LOT of movies and shows so the more obscure the better xo', 'PlaymateAngel', 1784423656, '/r/MoviesThatFeelLike/comments/1v0cyh8/is_it_possible_to_find_the_morally_grey_shadow/', 'https://www.reddit.com/gallery/1v0cyh8', 'MoviesThatFeelLike', 'A request for gothic, atmospheric films and shows featuring morally ambiguous monstrous love interests, with a focus on dark romance, beautiful cinematography, and elaborate costumes.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (411, '1v0dess', '👋Welcome to r/Channingtatumfans - Introduce Yourself and Read First!', 'Welcome to r/Channingtatumfans - Introduce Yourself and Read First!', '', 'Channingtatumofficia', 1784425004, '/r/MoviesThatFeelLike/comments/1v0dess/welcome_to_rchanningtatumfans_introduce_yourself/', '/r/Channingtatumfans/comments/1v0de1k/welcome_to_rchanningtatumfans_introduce_yourself/', 'MoviesThatFeelLike', 'A warm and enthusiastic invitation for new members to introduce themselves and join a fan community centered around Channing Tatum.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (412, '1v0djw9', 'Movies/shows with the southern gothic vibe?', 'Movies/shows with the southern gothic vibe?', '', 'anxietytoasterbath', 1784425423, '/r/MoviesThatFeelLike/comments/1v0djw9/moviesshows_with_the_southern_gothic_vibe/', 'https://www.reddit.com/gallery/1v0djw9', 'MoviesThatFeelLike', 'A request for movies and TV shows that evoke a Southern Gothic atmosphere, with recommendations ranging from horror to drama, focusing on eerie, atmospheric, and often supernatural elements.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (413, '1v0e7ai', 'Movies that feels like this?', 'Movies that feel like this?', '', 'NuclearF4rt', 1784427367, '/r/MoviesThatFeelLike/comments/1v0e7ai/movies_that_feels_like_this/', 'https://v.redd.it/xa7cjralm2eh1', 'MoviesThatFeelLike', 'The post conveys a campy, awkward military comedy vibe with strong homoerotic undertones. Commenters recommend films that blend raunchy humor, dance sequences, and clumsy masculinity.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (414, '1v0ehhl', 'Movies that feel like this vibe of pictures.', 'Movies that feel like this vibe of pictures.', 'Go through the whole album. There’s just such a unique and enthralling vibe to these pictures. Preferably shot in the 70s! ', 'stokedchris', 1784428231, '/r/MoviesThatFeelLike/comments/1v0ehhl/movies_that_feel_like_this_vibe_of_pictures/', 'https://www.reddit.com/gallery/1uzqowy', 'MoviesThatFeelLike', 'Nostalgic, gritty, and free-spirited vibe of 1970s America captured through films set in that era, often focusing on youth, rebellion, and retro aesthetics.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (415, '1v0en5c', 'Movies with the Haus aesthetic', 'Movies with the Haus aesthetic', 'From the Dead Island 2 DLC called Haus', 'the_ghost_1386', 1784428694, '/r/MoviesThatFeelLike/comments/1v0en5c/movies_with_the_haus_aesthetic/', 'https://www.reddit.com/gallery/1v0en5c', 'MoviesThatFeelLike', 'Neon-infused, hyper-stylized horror with a retro-futuristic visual flair.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (416, '1v0g62r', 'Movies with similar vibes? (Specially 2000s ones)', 'Movies with similar vibes? (Specially 2000s ones)', '', 'Mist156', 1784433401, '/r/MoviesThatFeelLike/comments/1v0g62r/movies_with_similar_vibes_specially_2000s_ones/', 'https://www.reddit.com/gallery/1v0g62r', 'MoviesThatFeelLike', 'A collection of eerie, unsettling horror and thriller films, many from the early 2000s, with an emphasis on psychological dread and supernatural elements.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (417, '1v0js2t', 'Movies w this gloomy vibe pls <3', 'Movies with this gloomy vibe please', '', 'bluegenesis_', 1784445333, '/r/MoviesThatFeelLike/comments/1v0js2t/movies_w_this_gloomy_vibe_pls_3/', 'https://www.reddit.com/gallery/1v0js2t', 'MoviesThatFeelLike', 'A request for movies that evoke a gloomy, melancholic atmosphere. The recommended films deal with mental health struggles, isolation, and dark themes.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (418, '1v0k9h9', 'PEAK STORYTELLIN', 'PEAK STORYTELLIN', 'Another masterpiece by NOLAN , what r ur reviews ', 'best_sugardad_2024', 1784447051, '/r/MoviesThatFeelLike/comments/1v0k9h9/peak_storytellin/', 'https://i.redd.it/vdr7byn855eh1.jpeg', 'MoviesThatFeelLike', 'Excited admiration for a Christopher Nolan film, inviting discussion.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (419, '1v0lfq8', 'horror/thrillers with religious, southern gothic, vampiric themes', 'horror thrillers with religious southern gothic vampiric themes', '', 'forwhatpurpose777', 1784451258, '/r/MoviesThatFeelLike/comments/1v0lfq8/horrorthrillers_with_religious_southern_gothic/', 'https://i.redd.it/0sadqq1rh5eh1.jpeg', 'MoviesThatFeelLike', 'Dark, eerie atmosphere blending religious dread, southern gothic decay, and vampire mythology.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (420, '1v0mh7y', 'I desperately need a film that feels like this song', '', '', 'Ordinary_Witness3225', 1784455018, '/r/MoviesThatFeelLike/comments/1v0mh7y/i_desperately_need_a_film_that_feels_like_this/', 'https://i.redd.it/2i7gesmxs5eh1.jpeg', 'MoviesThatFeelLike', 'The post seeks a movie that matches the mood of an unspecified song, and the comments point to John Hughes films like The Breakfast Club, which embody teen angst, nostalgia, and 80s coming-of-age drama.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (421, '1v0mhp7', '1600s witchy vibes', '1600s witchy vibes', 'No comedy or gore', 'No-Bluebird97', 1784455067, '/r/MoviesThatFeelLike/comments/1v0mhp7/1600s_witchy_vibes/', 'https://www.reddit.com/gallery/1v0mhp7', 'MoviesThatFeelLike', 'Dark, atmospheric witchy films and series set in the 1600s, avoiding comedy and gore.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (422, '1v0n4xs', 'Films or series with this vibe', 'Films or series with this vibe', '', 'cervidae313', 1784457312, '/r/MoviesThatFeelLike/comments/1v0n4xs/films_or_series_with_this_vibe/', 'https://www.reddit.com/gallery/1v0n4xs', 'MoviesThatFeelLike', 'The post evokes the chaotic, scandalous, and nostalgic feel of early 2000s celebrity culture, with tabloid headlines, partying, and ''manic pixie dream girl'' aesthetics.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (423, '1v0pfq4', 'Classic style exploration and adventure.', 'Classic style exploration and adventure.', '', 'DreadCaptainE0', 1784464455, '/r/MoviesThatFeelLike/comments/1v0pfq4/classic_style_exploration_and_adventure/', 'https://www.reddit.com/gallery/1v0pfq4', 'MoviesThatFeelLike', 'A thread filled with recommendations for classic adventure and exploration films, evoking a sense of nostalgia and thrill.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (424, '1v0pm6h', 'it''s Sunday, looking for a movie.', 'Looking for a movie on Sunday', '', 'Quiet_Concert1545', 1784464967, '/r/MoviesThatFeelLike/comments/1v0pm6h/its_sunday_looking_for_a_movie/', 'https://i.redd.it/xs7ommrfm6eh1.jpeg', 'MoviesThatFeelLike', 'A calm Sunday afternoon, searching for a movie to complement the quiet atmosphere.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (425, '1v0pw2b', 'Would you use a tool that recommends movies based in a specific feeling or vibe?', 'Would you use a tool that recommends movies based in a specific feeling or vibe?', 'Hi folks, I’m exploring an idea for a movie discovery tool and wanted to get some honest feedback. 

The idea is that instead of choosing genres or scrolling through generic recommendations, you could describe the kind of movie you feel like watching, such as something lonely and atmospheric like *Her*, a tense space movie like *Alien* but less scary, or something that feels like *Interstellar* without necessarily being about space. 

The tool would then suggest movies based on mood, atmosphere, pacing, themes, and overall feeling. 

Would something like this be useful to you?', 'og_pussy_crusher', 1784465737, '/r/MoviesThatFeelLike/comments/1v0pw2b/would_you_use_a_tool_that_recommends_movies_based/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v0pw2b/would_you_use_a_tool_that_recommends_movies_based/', 'MoviesThatFeelLike', 'A hopeful and enthusiastic discussion about a proposed movie discovery tool that recommends films based on mood and atmosphere, with commenters expressing strong interest and support.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (426, '1v0q1ws', 'Movies that feel like this?', 'Movies that feel like this?', '', 'NagitoKomaeda_987', 1784466163, '/r/MoviesThatFeelLike/comments/1v0q1ws/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1v0q1ws', 'MoviesThatFeelLike', 'A raw, unsettling portrait of social outcasts, chronic loneliness, and the weird underbelly of internet culture.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (427, '1v0tgl4', 'Silo', 'Silo', 'Silo , underground civilization like sifi webseries not exactly like this genre that can made me think for weeks about them.

It shows how realistic this is based on current date technology.

It also says Iran and Donald, nuclear all them in books in 2010s 

Closest i think ex machina, Elysium ', 'AmanYadav19', 1784474818, '/r/MoviesThatFeelLike/comments/1v0tgl4/silo/', 'https://www.reddit.com/gallery/1v0tgl4', 'MoviesThatFeelLike', 'A thought-provoking and realistic sci-fi series about an underground civilization that sparks deep reflection.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (428, '1v0txm0', 'You''re stuck in a madhouse', '', '', 'NovaCorpse', 1784475953, '/r/MoviesThatFeelLike/comments/1v0txm0/youre_stuck_in_a_madhouse/', 'https://www.reddit.com/gallery/1v0txm0', 'MoviesThatFeelLike', 'A claustrophobic and disorienting journey through confinement and madness, blending horror, psychological tension, and surreal dread.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (429, '1v0xhr0', 'Movies that feel like new-age crystals, mysticism, and cgi', 'Movies that feel like new-age crystals, mysticism, and cgi', 'I''m looking for movies that look like new-age musical cgi. Any suggestions?', 'Magickcloud', 1784484229, '/r/MoviesThatFeelLike/comments/1v0xhr0/movies_that_feel_like_newage_crystals_mysticism/', 'https://www.reddit.com/gallery/1v0xhr0', 'MoviesThatFeelLike', 'A request for movies with a trippy, mystical aesthetic reminiscent of new-age crystal visions and early CGI.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (430, '1v0zhha', 'Movies with this vibe?', 'Movies with this vibe', '', 'AlecitaMor15', 1784489115, '/r/MoviesThatFeelLike/comments/1v0zhha/movies_with_this_vibe/', 'https://www.reddit.com/gallery/1v0zhha', 'MoviesThatFeelLike', 'A whimsical, fairy-tale aesthetic with enchanted forests, tiny creatures, and magical houses.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (431, '1v10jra', 'Movies', 'Movies', 'Do you ever watch a movie or series and suddenly feel inspired to do something just because a character did it?

There were moments where I found myself thinking, “Wow, I want to be like her,” or “I want to do that too!” 

It’s not necessarily about wanting to become the character completely, but sometimes their personality, confidence, or the things they do make me want to try something similar in my own life.

Does anyone else experience this😂

  
By the I just finish watching off campus ', 'New_Evidence9146', 1784491862, '/r/MoviesThatFeelLike/comments/1v10jra/movies/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v10jra/movies/', 'MoviesThatFeelLike', 'Feeling inspired by fictional characters to emulate their confidence or actions.', 'skipped', 'no usable images', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (432, '1v1186r', 'Movies that feel like this song?', 'Movies that feel like this song', '', 'Wide_Distribution167', 1784493568, '/r/MoviesThatFeelLike/comments/1v1186r/movies_that_feel_like_this_song/', 'https://www.youtube.com/watch?v=DKxXHEx-XnU', 'MoviesThatFeelLike', 'A search for visual parallels to a song''s mood, inviting contemplation and emotional resonance.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (433, '1v11c89', 'I desperately need more media of people wandering through the American countryside in fall', '', '(Oh Brother Where Art Thou and Over the Garden Wall respectively)', 'FaZe_poopy', 1784493873, '/r/MoviesThatFeelLike/comments/1v11c89/i_desperately_need_more_media_of_people_wandering/', 'https://www.reddit.com/gallery/1v11c89', 'MoviesThatFeelLike', 'A longing for autumnal, pastoral narratives of wandering through the American countryside, filled with nostalgia and a sense of adventure.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (434, '1v11zs3', 'Movies that feel like: Medieval Europe, plague, cult-religious tones, dirty, dark', 'Medieval Europe plague cult religious tones dirty dark', '', 'WhiskeyLothbrok', 1784495645, '/r/MoviesThatFeelLike/comments/1v11zs3/movies_that_feel_like_medieval_europe_plague/', 'https://www.reddit.com/gallery/1v11zs3', 'MoviesThatFeelLike', 'A collection of recommendations for movies (and some games) that evoke a dark, grim medieval European setting with themes of plague, religious cults, and dirt.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (435, '1v1251h', 'Movies that feels like this long worthy journey..', 'Movies that feel like a long worthy journey', '', 'Snake_Charmers', 1784496058, '/r/MoviesThatFeelLike/comments/1v1251h/movies_that_feels_like_this_long_worthy_journey/', 'https://www.reddit.com/gallery/1v1251h', 'MoviesThatFeelLike', 'A film that feels like a long, worthwhile journey, evoking a sense of epic progression and eventual reward.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (436, '1v126qu', 'Movies like this long deserving path..', 'Movies like this long deserving path', '', 'Snake_Charmers', 1784496180, '/r/MoviesThatFeelLike/comments/1v126qu/movies_like_this_long_deserving_path/', 'https://www.reddit.com/gallery/1v126qu', 'MoviesThatFeelLike', 'A yearning for films that capture the emotional and physical journey of a long and meaningful path.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (437, '1v13ogq', 'Movies that feel like another life?', '', 'Animated movies can be included as well', 'JAGAAAN-01', 1784500097, '/r/MoviesThatFeelLike/comments/1v13ogq/movies_that_feel_like_another_life/', 'https://www.reddit.com/gallery/1v13ogq', 'MoviesThatFeelLike', 'A collection of films that evoke a sense of living an alternate existence or experiencing profound otherworldly journeys.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (438, '1v14qsr', 'Movies/TV recs all welcome!', 'Movies TV recommendations all welcome', '[deleted]', '[deleted]', 1784502764, '/r/MoviesThatFeelLike/comments/1v14qsr/moviestv_recs_all_welcome/', '', 'MoviesThatFeelLike', 'An open and welcoming invitation for any movie or TV show suggestions, eager to hear all recommendations.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (439, '1v14w4y', 'Nautical Dark Fantasy', '', 'Somewhere between Pirates of the Caribbean and The Lighthouse. Master and Commander with a Kraken. Rime of the Ancient Mariner meets Moby Dick typeshii. What you got?', 'happyman395', 1784503137, '/r/MoviesThatFeelLike/comments/1v14w4y/nautical_dark_fantasy/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v14w4y/nautical_dark_fantasy/', 'MoviesThatFeelLike', 'A blend of nautical adventure and dark fantasy, evoking tales of sea monsters, maritime horror, and cosmic dread.', 'skipped', 'no usable images', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (440, '1v15ia0', 'Boulevard', 'Boulevard', 'I can''t move on from Boulevard.Any suggestions on film similar to this?', 'BillEnvironmental907', 1784504719, '/r/MoviesThatFeelLike/comments/1v15ia0/boulevard/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v15ia0/boulevard/', 'MoviesThatFeelLike', 'A lingering obsession with a film, seeking similar cinematic experiences that evoke its haunting and nostalgic mood.', 'skipped', 'no usable images', NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (441, '1v15tyh', 'Movies that feel like Evil Dead 1 & 2', 'Movies that feel like Evil Dead 1 & 2', '', 'UniversityNo1170', 1784505561, '/r/MoviesThatFeelLike/comments/1v15tyh/movies_that_feel_like_evil_dead_1_2/', 'https://i.redd.it/6mv2u218z9eh1.gif', 'MoviesThatFeelLike', 'A frantic, gory, and absurdly comedic vibe, blending horror with slapstick and supernatural mayhem.', 'publishable', NULL, NULL, '2026-07-20 04:02:06', '2026-07-20 04:02:06');
