-- 0037_seed_20260729T024006Z_02_recommendations.sql: data seed from pipeline:load run.
-- Generated:  2026-07-29T02:40:10.857820+00:00
-- Run started: 2026-07-29T02:40:06.560790+00:00
-- Source: data/working/load manifest from this run.
--
-- Idempotent: every INSERT is INSERT OR IGNORE, keyed by the
-- table's natural unique constraint.  Wrangler's migration
-- tracking normally prevents re-apply; the OR IGNORE is
-- defense in depth for partial / interrupted re-runs.
--
-- Chunk: 02_recommendations (2/5)
-- Tables: recommendations.
-- Pipeline-state tables (processing_runs, pipeline_artifacts)
-- are intentionally excluded — they're per-run bookkeeping.

INSERT OR IGNORE INTO "recommendations" ("id", "tmdb_id", "imdb_id", "igdb_id", "title", "original_title", "media_type", "release_year", "poster_url", "backdrop_url", "overview", "external_url", "platforms", "popularity", "vote_average", "is_ambiguous", "evidence_score", "created_at", "updated_at") VALUES (5026, 16392, 'tt0780595', NULL, 'Redline', 'Redline', 'movie', 2007, 'https://image.tmdb.org/t/p/w500/lE1XfidwJml7lNGi0D4KlB8uQFY.jpg', 'https://image.tmdb.org/t/p/original/qcKMgi3tge6PDdhyIFlLomn9Lqj.jpg', 'A gorgeous young automobile fanatic--and front to the hottest unsigned band on the West Coast--finds herself caught up in illegal drag-racing competitions organized by exotic car fanatics.', NULL, NULL, 1.7767, 5.099, 0, 2.015, '2026-07-29 02:40:10', '2026-07-29 02:40:10');
UPDATE "recommendations" SET "tmdb_id"=858017, "imdb_id"='tt15574270', "igdb_id"=NULL, "title"='I Saw the TV Glow', "original_title"='I Saw the TV Glow', "media_type"='movie', "release_year"=2024, "poster_url"='https://image.tmdb.org/t/p/w500/hS4GYkYpN1rfl4GIxyc02sCyfAj.jpg', "backdrop_url"='https://image.tmdb.org/t/p/original/jKulL2hdp5S7dVbpoItAtdCyzXI.jpg', "overview"='In late-90s suburbia, a lonely teenager meets a girl at school who introduces him to a mysterious late-night T.V. show — a vision of a supernatural world pulsing beneath their own. As time goes on, however, questions begin to arise about why the show sometimes seems more real than their own lives. In the pale glow of the television, their view of reality begins to crack.', "external_url"=NULL, "platforms"=NULL, "popularity"=7.3409, "vote_average"=6.2, "is_ambiguous"=0, "evidence_score"=30.272, "created_at"='2026-07-15 12:01:52', "updated_at"='2026-07-29 02:40:10' WHERE "id"=291;
UPDATE "recommendations" SET "tmdb_id"=10494, "imdb_id"='tt0156887', "igdb_id"=NULL, "title"='Perfect Blue', "original_title"='PERFECT BLUE', "media_type"='movie', "release_year"=1998, "poster_url"='https://image.tmdb.org/t/p/w500/6WTiOCfDPP8XV4jqfloiVWf7KHq.jpg', "backdrop_url"='https://image.tmdb.org/t/p/original/mHG7dpLb0ZScSY3LpP443IHRmjy.jpg', "overview"='Rising pop star Mima Kirigoe quits singing to pursue a career as an actress. After she takes up a role on a popular detective show, her handlers and collaborators begin turning up murdered. Harboring feelings of guilt and haunted by visions of her former self, Mima''s reality and fantasy meld into a frenzied paranoia.', "external_url"=NULL, "platforms"=NULL, "popularity"=14.8965, "vote_average"=8.3, "is_ambiguous"=0, "evidence_score"=1.51863636363636356e+01, "created_at"='2026-07-15 12:01:52', "updated_at"='2026-07-29 02:40:10' WHERE "id"=1028;
UPDATE "recommendations" SET "tmdb_id"=4977, "imdb_id"='tt0851578', "igdb_id"=NULL, "title"='Paprika', "original_title"='パプリカ', "media_type"='movie', "release_year"=2006, "poster_url"='https://image.tmdb.org/t/p/w500/bLUUr474Go1DfeN1HLjE3rnZXBq.jpg', "backdrop_url"='https://image.tmdb.org/t/p/original/6oXn0037WWw4fTCc3Qczof71lSp.jpg', "overview"='Dr. Atsuko Chiba is a research psychologist who uses a device called the DC Mini to enter her patients'' dreams, wherein she adopts the alter-ego "Paprika". When the device is stolen, she must stop rogue elements from merging the dream and waking worlds.', "external_url"=NULL, "platforms"=NULL, "popularity"=8.3434, "vote_average"=7.8, "is_ambiguous"=0, "evidence_score"=1.2373333333333333e+01, "created_at"='2026-07-15 12:01:52', "updated_at"='2026-07-29 02:40:10' WHERE "id"=1221;
UPDATE "recommendations" SET "tmdb_id"=94404, "imdb_id"='tt11147852', "igdb_id"=NULL, "title"='Dorohedoro', "original_title"='ドロヘドロ', "media_type"='tv', "release_year"=2020, "poster_url"='https://image.tmdb.org/t/p/w500/zSMmRTopPIRr6913KX8pyiV6zsK.jpg', "backdrop_url"='https://image.tmdb.org/t/p/original/sASxGVO6wioRG6jNM2LHOjBAgWu.jpg', "overview"='Amnesiac Caiman seeks to undo his lizard head curse by killing the sorcerer responsible, with his friend Nikaido''s help. In the Hole, that''s a threat.', "external_url"=NULL, "platforms"=NULL, "popularity"=15.3424, "vote_average"=8.4, "is_ambiguous"=0, "evidence_score"=7.005, "created_at"='2026-07-20 01:02:04', "updated_at"='2026-07-29 02:40:10' WHERE "id"=3031;
UPDATE "recommendations" SET "tmdb_id"=96713, "imdb_id"='tt11639414', "igdb_id"=NULL, "title"='The Midnight Gospel', "original_title"='The Midnight Gospel', "media_type"='tv', "release_year"=2020, "poster_url"='https://image.tmdb.org/t/p/w500/me3kxfiFRkdto6SmDQv0nczjfmP.jpg', "backdrop_url"='https://image.tmdb.org/t/p/original/xCcFixrguEYfVOXonSWzMyjG9Nq.jpg', "overview"='Traversing trippy worlds inside his universe simulator, Clancy the space caster explores existential questions about life, death and everything in between.', "external_url"=NULL, "platforms"=NULL, "popularity"=4.6911, "vote_average"=8.3, "is_ambiguous"=0, "evidence_score"=6.505, "created_at"='2026-07-21 03:32:24', "updated_at"='2026-07-29 02:40:10' WHERE "id"=4549;
UPDATE "recommendations" SET "tmdb_id"=430214, "imdb_id"='tt6335734', "igdb_id"=NULL, "title"='Night Is Short, Walk On Girl', "original_title"='夜は短し歩けよ乙女', "media_type"='movie', "release_year"=2017, "poster_url"='https://image.tmdb.org/t/p/w500/cDp45WZNqgAli3u4GTnUhsqFn5K.jpg', "backdrop_url"='https://image.tmdb.org/t/p/original/iBl3hhtHC7qQX7jGphIAYLpmpPC.jpg', "overview"='As a group of university students go out for a night on the town, a sophomore known only as "The Girl with Black Hair" experiences a series of surreal encounters with the local nightlife – all the while unaware of the romantic longings of "Senpai", a senior student who has been creating increasingly fantastic and contrived reasons to run into her in an effort to win her heart.', "external_url"=NULL, "platforms"=NULL, "popularity"=2.2668, "vote_average"=7.443, "is_ambiguous"=0, "evidence_score"=6.505, "created_at"='2026-07-21 03:32:24', "updated_at"='2026-07-29 02:40:10' WHERE "id"=5015;
