-- 0041_seed_20260729T205104Z_01_posts.sql: data seed from pipeline:load run.
-- Generated:  2026-07-29T20:51:09.473372+00:00
-- Run started: 2026-07-29T20:51:04.655698+00:00
-- Source: data/working/load manifest from this run.
--
-- Idempotent: every INSERT is INSERT OR IGNORE, keyed by the
-- table's natural unique constraint.  Wrangler's migration
-- tracking normally prevents re-apply; the OR IGNORE is
-- defense in depth for partial / interrupted re-runs.
--
-- Chunk: 01_posts (1/5)
-- Tables: imported_vibe_posts.
-- Pipeline-state tables (processing_runs, pipeline_artifacts)
-- are intentionally excluded — they're per-run bookkeeping.

INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (545, '1v6ykbd', 'Movies/shows that feel like these scenes', '', 'A blend of generally realistic setting and some surreal gravity-defying elements/scenes

--- 

^(PS: not "flying" in ways like superheroes do)

Thanks~', '__ephemeral_', 1785056544, '/r/MoviesThatFeelLike/comments/1v6ykbd/moviesshows_that_feel_like_these_scenes/', 'https://v.redd.it/26rglwj1hjfh1', 'MoviesThatFeelLike', 'A blend of realistic settings and surreal, gravity-defying moments, evoking a dreamlike and psychological atmosphere.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (546, '1v6ypnr', 'Movies & anime that feel like the works of Yoshitaka Amano.', 'Movies and anime that feel like the works of Yoshitaka Amano', 'One of my favourite illustrators ever.

I need movies that....you know...movies that speak to....that speak to the themes of, like....movies that show....you know.....that dec......yeah.

Whatever your instincts tell you tbh. Mine tell me, "whimsical goth" "high fantasy" "Romanticism with ukiyo-e" "phantasmagorical imagery."

Just throw me in the deep end, I''ll figure it out. Please and thanks.', 'Fair_Associate7883', 1785057036, '/r/MoviesThatFeelLike/comments/1v6ypnr/movies_anime_that_feel_like_the_works_of/', 'https://www.reddit.com/gallery/1v6ypnr', 'MoviesThatFeelLike', 'A dreamlike, gothic fantasy atmosphere with whimsical and phantasmagorical imagery, blending high fantasy and romanticism with an ethereal, surreal edge.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (547, '1v6z2ot', 'Movies like this', 'Movies like this', '', 'Tricky_cielito00', 1785058260, '/r/MoviesThatFeelLike/comments/1v6z2ot/movies_like_this/', 'https://i.redd.it/02h0xcjomjfh1.jpeg', 'MoviesThatFeelLike', 'Seeking movie recommendations similar to an unspecified reference.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (548, '1v70mih', 'Looking for Fantasy movies where the world itself feels like a main character', '', '[removed]', 'Mbkim3', 1785063289, '/r/MoviesThatFeelLike/comments/1v70mih/looking_for_fantasy_movies_where_the_world_itself/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v70mih/looking_for_fantasy_movies_where_the_world_itself/', 'MoviesThatFeelLike', 'Craving an immersive fantasy world where the setting feels alive and central to the story.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (549, '1v7141l', 'What movie that has this vibe??', '', 'Hey Reddit i was wondering if there is any dream core movies i can watch and i decided to ask y''all for some movie recommendations. So I don''t want the same movies i watched and I''ll tell you what liminal space movies I watched and I DON''T want you to repeat it.

Backrooms 

Vivarium 

Skinnamarink ', 'tadcfanlover143', 1785064775, '/r/MoviesThatFeelLike/comments/1v7141l/what_movie_that_has_this_vibe/', 'https://www.reddit.com/gallery/1v7141l', 'MoviesThatFeelLike', 'Dreamlike, liminal, and surreal atmosphere with an unsettling, nostalgic edge.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (550, '1v71k8p', 'On the road to Ruidoso was a area a, New Mexico', 'On the road to Ruidoso, New Mexico', '', 'mailroomkimchi', 1785066123, '/r/MoviesThatFeelLike/comments/1v71k8p/on_the_road_to_ruidoso_was_a_area_a_new_mexico/', 'https://i.redd.it/uizmj0f3poeh1.jpeg', 'MoviesThatFeelLike', 'A scenic drive through mountainous New Mexico terrain with a sense of isolation.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (551, '1v732fk', 'Movies for Cry?', 'Movies for Cry', 'I prefer underrated movies', 'Character-Bat-7397', 1785070298, '/r/MoviesThatFeelLike/comments/1v732fk/movies_for_cry/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v732fk/movies_for_cry/', 'MoviesThatFeelLike', 'A collection of poignant, underrated films that evoke deep emotional responses and tears.', 'skipped', 'no usable images', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (552, '1v775q5', 'Realistic space movies', 'Realistic space movies', '', 'girlysxxface', 1785080096, '/r/MoviesThatFeelLike/comments/1v775q5/realistic_space_movies/', 'https://www.reddit.com/gallery/1v775q5', 'MoviesThatFeelLike', 'Grounded, scientifically plausible space stories that emphasize realism and often explore isolation or existential dread.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (553, '1v797ve', 'Movies that feel like dark fantasy', '', '', 'prettygirlyxxx', 1785084637, '/r/MoviesThatFeelLike/comments/1v797ve/movies_that_feel_like_dark_fantasy/', 'https://www.reddit.com/gallery/1v797ve', 'MoviesThatFeelLike', 'A dark, medieval fantasy atmosphere with gothic and epic elements, often evoking 80s fantasy and folklore.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (554, '1v7a7x8', 'Suggest me Slasher movies', 'Suggest me Slasher movies', 'Help me!', 'Character-Bat-7397', 1785086827, '/r/MoviesThatFeelLike/comments/1v7a7x8/suggest_me_slasher_movies/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v7a7x8/suggest_me_slasher_movies/', 'MoviesThatFeelLike', 'Dark, intense, and terrifying slasher horror recommendations.', 'skipped', 'no usable images', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (555, '1v7b2pt', 'Serene, snow-covered mountains, ancient chinese temples, martial arts and explosive fireworks', 'Serene, snow-covered mountains, ancient chinese temples, martial arts and explosive fireworks', '

I absolutely adore the Sly Cooper video game franchise and especially the atmosphere and vibe of the different worlds.

The location of the fourth world, *Fire in the Sky*, in the first game is the Kunlun Mountains of China, where the villain, the Panda King, has built a vast fireworks empire among ancient temples and snow-covered peaks. 

Panda King is equal parts discipline and vengeance, and with that vengeance and thirst for power he has transformed the sacred mountain monasteries into heavily fortified strongholds. The hero of the game describes him as: "a frustrated fireworks artist turned homicidal pyromaniac."

The landscape is a breathtaking blend of towering cliffs, frozen forests, ornate temples, dragon statues, and explosive firework factories, where centuries-old tradition stands alongside dangerous, explosive ingenuity.

I''m looking for tranquil mountain monasteries perched high above the clouds. Endless snow-covered peaks stretching into the horizon. Ancient stone stairways winding through pine forests dusted with fresh snow. Ornate pagodas, red temple gates, and towering guardian statues overlooking silent valleys. Warm lantern light glowing against the cold blue of winter nights. Fireworks illuminating the sky above frozen cliffs, their colours reflecting across pristine snow.

  
Live action and animated are both welcomed. Thank you in advance!', 'AndersHolbeak96', 1785088730, '/r/MoviesThatFeelLike/comments/1v7b2pt/serene_snowcovered_mountains_ancient_chinese/', 'https://www.reddit.com/gallery/1v7b2pt', 'MoviesThatFeelLike', 'Tranquil mountain monasteries, endless snow peaks, ancient temples, and explosive fireworks, where centuries-old tradition meets dangerous ingenuity.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (556, '1v7bce1', 'Movies that feels stressful', '', 'Could be a race against the clock or just the overall vibe that feels unrelentless and nerve racking   
   
Movies like: Uncut Gems, Whiplash, The long walk, Run Lola run, and Chappie ', 'PapaJeffKap', 1785089310, '/r/MoviesThatFeelLike/comments/1v7bce1/movies_that_feels_stressful/', 'https://www.reddit.com/gallery/1v7bce1', 'MoviesThatFeelLike', 'A relentless and nerve-wracking atmosphere of anxiety, tension, and high-stakes stress.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (557, '1v7biea', 'Movies that give similar horror vibe', 'Movies that give similar horror vibe', '', 'girlyxvibez', 1785089669, '/r/MoviesThatFeelLike/comments/1v7biea/movies_that_give_similar_horror_vibe/', 'https://www.reddit.com/gallery/1v7biea', 'MoviesThatFeelLike', 'Giallo-inspired horror with a sleek, murderous aesthetic.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (558, '1v7c62y', 'Movies that feel like the Cure (1997)', '', 'A movie with a similair ambience horror like  
the Cure, also something like  
the Wailing too.', 'Zoro-88', 1785091114, '/r/MoviesThatFeelLike/comments/1v7c62y/movies_that_feel_like_the_cure_1997/', 'https://i.redd.it/m3lmw2gdcmfh1.jpeg', 'MoviesThatFeelLike', 'Atmospheric horror with a dark, eerie ambiance.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (559, '1v7c8e2', 'Movie Idea Would Anyone Want To See The Finished Result? What director would do it justice?', '', '', 'itdjents007', 1785091252, '/r/MoviesThatFeelLike/comments/1v7c8e2/movie_idea_would_anyone_want_to_see_the_finished/', 'https://v.redd.it/6xk32fhvbmfh1', 'MoviesThatFeelLike', 'Curious speculation about a movie idea', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (560, '1v7cbl3', 'Movies like The Grand Budapest Hotel', 'movies like the grand budapest hotel', 'Any movies that are similair but not Anderons other movies', 'Zoro-88', 1785091449, '/r/MoviesThatFeelLike/comments/1v7cbl3/movies_like_the_grand_budapest_hotel/', 'https://www.reddit.com/gallery/1v7cbl3', 'MoviesThatFeelLike', 'Whimsical, colorful, and meticulously designed films with a vintage European aesthetic.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (561, '1v7eky6', 'A night that accidently become philosophical', 'A night that accidentally become philosophical', '', 'Legitimate_Tale_734', 1785096498, '/r/MoviesThatFeelLike/comments/1v7eky6/a_night_that_accidently_become_philosophical/', 'https://www.reddit.com/gallery/1uk4gfb', 'MoviesThatFeelLike', 'A night of unexpected deep conversation and existential reflection.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (562, '1v7fv8v', 'Hell and demons', 'Hell and demons', '', 'HotShrekBoi', 1785099394, '/r/MoviesThatFeelLike/comments/1v7fv8v/hell_and_demons/', 'https://www.reddit.com/gallery/1v7fv8v', 'MoviesThatFeelLike', 'A collection of movies and media featuring hellish landscapes, demonic entities, and infernal imagery.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (563, '1v7g0qf', 'Darkest movies That watched?', 'Darkest movies you''ve watched?', 'Suggest me!', 'Character-Bat-7397', 1785099733, '/r/MoviesThatFeelLike/comments/1v7g0qf/darkest_movies_that_watched/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v7g0qf/darkest_movies_that_watched/', 'MoviesThatFeelLike', 'A request for the bleakest, most disturbing films, with recommendations that delve into extreme horror, psychological trauma, and despair.', 'skipped', 'no usable images', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (564, '1v7g8kt', 'Movies About motherhood?', 'Movies About motherhood?', 'Suggest me!', 'Character-Bat-7397', 1785100229, '/r/MoviesThatFeelLike/comments/1v7g8kt/movies_about_motherhood/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v7g8kt/movies_about_motherhood/', 'MoviesThatFeelLike', 'A heartfelt search for movie recommendations exploring the many facets of motherhood, from tender to terrifying.', 'skipped', 'no usable images', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (565, '1v7gef0', 'Quirky Science Fiction Movies That Feel Romantic', '', '', 'Uh_October', 1785100593, '/r/MoviesThatFeelLike/comments/1v7gef0/quirky_science_fiction_movies_that_feel_romantic/', 'https://i.redd.it/g8vn6u2j4nfh1.png', 'MoviesThatFeelLike', 'A selection of offbeat science fiction movies with romantic undercurrents, from time-travel love stories to existential comedies.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (566, '1v7gmi5', 'Movies that Protogonist get level up🤔', 'Movies that Protagonist get level up', 'Suggest me!', 'Character-Bat-7397', 1785101096, '/r/MoviesThatFeelLike/comments/1v7gmi5/movies_that_protogonist_get_level_up/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v7gmi5/movies_that_protogonist_get_level_up/', 'MoviesThatFeelLike', 'Empowering progression as protagonists level up their abilities.', 'skipped', 'no usable images', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (567, '1v7gxqb', 'Suggest movies that full suspension', 'Suggest movies that full suspension', 'Help me!', 'Character-Bat-7397', 1785101830, '/r/MoviesThatFeelLike/comments/1v7gxqb/suggest_movies_that_full_suspension/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v7gxqb/suggest_movies_that_full_suspension/', 'MoviesThatFeelLike', 'Intense, suspenseful movies sought.', 'skipped', 'no usable images', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (568, '1v7gztq', 'Which movie is full poignant scenes ?', 'Which movie is full of poignant scenes?', 'Anything could to be!', 'Character-Bat-7397', 1785101968, '/r/MoviesThatFeelLike/comments/1v7gztq/which_movie_is_full_poignant_scenes/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v7gztq/which_movie_is_full_poignant_scenes/', 'MoviesThatFeelLike', 'A contemplative and deeply emotional atmosphere, driven by poignant, life-affirming scenes.', 'skipped', 'no usable images', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (569, '1v7h60d', 'Best movie in 2026?', '', 'Till now?', 'Character-Bat-7397', 1785102370, '/r/MoviesThatFeelLike/comments/1v7h60d/best_movie_in_2026/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v7h60d/best_movie_in_2026/', 'MoviesThatFeelLike', 'Seeking and sharing top 2026 movie picks.', 'skipped', 'no usable images', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (570, '1v7hlzd', 'Movies about unlikely friendship?', '', 'Anything could to be!', 'Character-Bat-7397', 1785103422, '/r/MoviesThatFeelLike/comments/1v7hlzd/movies_about_unlikely_friendship/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v7hlzd/movies_about_unlikely_friendship/', 'MoviesThatFeelLike', 'Heartwarming and quirky, celebrating unexpected bonds.', 'skipped', 'no usable images', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (571, '1v7ii8c', 'Here are more plots i thought of that I really want to see movies of', 'Here are more plots i thought of that I really want to see movies of', 'Stalker x stalker, but they don’t know the other person is a stalker   
Horror movie about a dream but its from the pov of a person in the dream, not the person dreaming   
Starts out as a shitty teen movie like high school musical or something, and devolves into much more serious topics  
Early dinosaur movies with poor reconstructions of what dinosaurs looked like  
A movie with a really REALLY dumb plot, but it’s actually really good', 'Remarkable-Slide5376', 1785105622, '/r/MoviesThatFeelLike/comments/1v7ii8c/here_are_more_plots_i_thought_of_that_i_really/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v7ii8c/here_are_more_plots_i_thought_of_that_i_really/', 'MoviesThatFeelLike', 'A playful, creative exploration of unconventional movie plots, with commenters eagerly suggesting existing films that match the quirky ideas.', 'skipped', 'no usable images', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (572, '1v7ijxi', 'Movies that have funeral home theme', 'Movies that have funeral home theme', 'In school to work at a funeral home and wanna watch a film about it ', 'Maximum_Hurry_3708', 1785105738, '/r/MoviesThatFeelLike/comments/1v7ijxi/movies_that_have_funeral_home_theme/', 'https://www.reddit.com/gallery/1v7ijxi', 'MoviesThatFeelLike', 'Curious and professional, seeking funeral home films for study and inspiration.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (573, '1v7ik9l', 'Movies about Godfathers?', '', 'Anything could to be ', 'Character-Bat-7397', 1785105760, '/r/MoviesThatFeelLike/comments/1v7ik9l/movies_about_godfathers/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v7ik9l/movies_about_godfathers/', 'MoviesThatFeelLike', 'Playful, humorous community riffing on the request with fake sequels and memes.', 'skipped', 'no usable images', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (574, '1v7j18i', 'Movies that feel like 2005-2012optimism', 'Movies that feel like 2005-2012optimism', 'Movies that feel like living in Bushwick or St John, New Brunswick in 2007. Girls with short hair and twee outfits, guys on bikes, live music, barista lead cafes, retro cars and dresses, stomp clap HEY! music and co-op IPA pizza places. I miss that vibe and I want to watch peak hipster movies. ', 'Positive-Sun5969', 1785106926, '/r/MoviesThatFeelLike/comments/1v7j18i/movies_that_feel_like_20052012optimism/', 'https://www.reddit.com/gallery/1v7j18i', 'MoviesThatFeelLike', 'A nostalgic yearning for the hipster optimism of 2005-2012, characterized by indie culture, co-op cafes, and stomp-clap music.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (575, '1v7k19q', 'Movies /TV show that about trapped in creepy place?', 'Movies /TV show that about trapped in creepy place?', 'Suggest me', 'Character-Bat-7397', 1785109525, '/r/MoviesThatFeelLike/comments/1v7k19q/movies_tv_show_that_about_trapped_in_creepy_place/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v7k19q/movies_tv_show_that_about_trapped_in_creepy_place/', 'MoviesThatFeelLike', 'Seeking movies and TV shows about being trapped in creepy, unsettling locations, with horror and psychological tension.', 'skipped', 'no usable images', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (576, '1v7kjas', 'Movies that feel like Darkest Dungeon', '', 'Dark fantasy/cosmic horror as well as a certain tone of dread **please please please!**', 'bone_thaddy', 1785110796, '/r/MoviesThatFeelLike/comments/1v7kjas/movies_that_feel_like_darkest_dungeon/', 'https://www.reddit.com/gallery/1v7kjas', 'MoviesThatFeelLike', 'A craving for dark fantasy and cosmic horror with an overwhelming sense of dread.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (577, '1v7kvk8', 'Modern fantasy/ fantasy treated realistically', '', '', 'BillythenotaKid', 1785111711, '/r/MoviesThatFeelLike/comments/1v7kvk8/modern_fantasy_fantasy_treated_realistically/', 'https://www.reddit.com/gallery/1v7kvk8', 'MoviesThatFeelLike', 'Modern fantasy woven seamlessly into mundane reality, often with a darkly comedic or gritty tone.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (578, '1v7mgz8', 'Ireland/Scotland/Wales', 'Ireland/Scotland/Wales', 'Preferably not horror! ', 'Warm_Willow_4116', 1785116104, '/r/MoviesThatFeelLike/comments/1v7mgz8/irelandscotlandwales/', 'https://www.reddit.com/gallery/1v7mgz8', 'MoviesThatFeelLike', 'Misty, rugged Celtic landscape with echoes of folklore and melancholy.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (579, '1v7myf2', 'Glimpses of something horrible in the middle of a raging storm.', '', 'Clip is from Midnight Mass, which I couldn''t recommend more.', 'TridiObject', 1785117434, '/r/MoviesThatFeelLike/comments/1v7myf2/glimpses_of_something_horrible_in_the_middle_of_a/', 'https://v.redd.it/lm982z0diofh1', 'MoviesThatFeelLike', 'Eerie and tense as fleeting glimpses of something monstrous appear in a storm.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (580, '1v7mzcu', 'Werewolf movies (similar to these ones)', 'Werewolf movies similar to these ones', 'Specifically, I''m looking for one with these traits:

\- Eerie, isolated forest atmosphere 

\- Imposing lycan design with great creature effects 

\- Gruesome, meanspirited kills 

\- Down-to-earth, likable characters 

Obviously they don''t have to be an exact match of the list as long as they have one or the other, thanks!', 'FreakyFreak2005', 1785117507, '/r/MoviesThatFeelLike/comments/1v7mzcu/werewolf_movies_similar_to_these_ones/', 'https://www.reddit.com/gallery/1v7mzcu', 'MoviesThatFeelLike', 'A craving for atmospheric, creature-driven werewolf horror set in isolated forests with brutal kills and empathetic characters.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (581, '1v7oscc', 'Sentimental', 'Sentimental', 'What is the most deeply sentimental movie you''ve ever seen that kind truly touched your inner self and made you view life differently?

My personal all time fav is "Sixth Sense".', 'Antique-Eye-4532', 1785122640, '/r/MoviesThatFeelLike/comments/1v7oscc/sentimental/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v7oscc/sentimental/', 'MoviesThatFeelLike', 'Deeply sentimental films that touch the soul and shift your perspective on life.', 'skipped', 'no usable images', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (582, '1v7qil9', 'movies like cigarette daydreams by cage the elephant', 'movies like cigarette daydreams by cage the elephant', '', 'horsecraze', 1785127857, '/r/MoviesThatFeelLike/comments/1v7qil9/movies_like_cigarette_daydreams_by_cage_the/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v7qil9/movies_like_cigarette_daydreams_by_cage_the/', 'MoviesThatFeelLike', 'Nostalgic, bittersweet, and dreamy, evoking fleeting moments of youth and romance.', 'skipped', 'no usable images', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (583, '1v7qyet', 'Weird fever dream horrors + thrillers.', 'Weird fever dream horrors + thrillers', '', 'throwaway67171717', 1785129218, '/r/MoviesThatFeelLike/comments/1v7qyet/weird_fever_dream_horrors_thrillers/', '/r/MovieRecommendations/comments/1v7qy7d/weird_fever_dream_horrors_thrillers/', 'MoviesThatFeelLike', 'A surreal, disorienting blend of horror and thriller that feels like a fever dream.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (584, '1v7rtee', 'Movies that feel like this 🤍', 'Movies that feel like this', '', 'JuicyVanilla23', 1785132043, '/r/MoviesThatFeelLike/comments/1v7rtee/movies_that_feel_like_this/', 'https://i.redd.it/yesrzjm2qpfh1.jpeg', 'MoviesThatFeelLike', 'A cozy, whimsical, and romantic atmosphere reminiscent of Parisian streets and heartfelt stories.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (585, '1v7ti6t', 'Something like these games', 'Something Like These Games', '', 'cervidae313', 1785137758, '/r/MoviesThatFeelLike/comments/1v7ti6t/something_like_these_games/', 'https://www.reddit.com/gallery/1v7ti6t', 'MoviesThatFeelLike', 'A dark, surreal, and eerie atmosphere blending childlike innocence with macabre horror.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (586, '1v7ualq', 'What are some visually beautiful movies?', '', '[removed]', 'Klein_Moretti2', 1785140580, '/r/MoviesThatFeelLike/comments/1v7ualq/what_are_some_visually_beautiful_movies/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v7ualq/what_are_some_visually_beautiful_movies/', 'MoviesThatFeelLike', 'Yearning for visually stunning and aesthetically pleasing cinema.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (587, '1v7uzc7', 'Clone movie. Super fun to watch.', 'Clone movie. Super fun to watch.', 'There''s a place 100 percent in the world right now really ', 'AmanYadav19', 1785143013, '/r/MoviesThatFeelLike/comments/1v7uzc7/clone_movie_super_fun_to_watch/', 'https://www.reddit.com/gallery/1v7uzc7', 'MoviesThatFeelLike', 'Playful and lighthearted discussion about a fun clone movie with inside jokes.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (588, '1v7v4hp', 'Movies about Romance&Break up?', 'Movies about Romance and Break Up', 'Suggest me! ', 'Character-Bat-7397', 1785143498, '/r/MoviesThatFeelLike/comments/1v7v4hp/movies_about_romancebreak_up/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v7v4hp/movies_about_romancebreak_up/', 'MoviesThatFeelLike', 'A collection of films exploring the highs and lows of romantic relationships, from passionate beginnings to painful breakups.', 'skipped', 'no usable images', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (589, '1v7zpco', 'Movies that feel like whatever this is', 'Movies that feel like whatever this is', '', 'Secure-Pickle-5391', 1785157165, '/r/MoviesThatFeelLike/comments/1v7zpco/movies_that_feel_like_whatever_this_is/', 'https://i.redd.it/ywf9hvtpsrfh1.jpeg', 'MoviesThatFeelLike', 'A hazy, undefined mood, searching for a cinematic equivalent to an unnamed feeling.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (590, '1v80owf', 'Movies with this kind of vibe', '', '', 'voyagestone', 1785159507, '/r/MoviesThatFeelLike/comments/1v80owf/movies_with_this_kind_of_vibe/', 'https://i.redd.it/j7jyf2hqzrfh1.jpeg', 'MoviesThatFeelLike', 'No atmospheric description provided.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (591, '1v81b4k', 'Films that feel like the group of boys from season 4 of the wire', '', 'Specific attention to the hangout moments and conflict between each other. Family dynamic themes, interesting character tropes, motive clashing with expectations or environment. Kids-teens against the system, drugs, violence, institutions. Anything that gives off familiarity to any of these parameters drop the rec!', 'Smart_Material_5466', 1785160943, '/r/MoviesThatFeelLike/comments/1v81b4k/films_that_feel_like_the_group_of_boys_from/', 'https://www.reddit.com/gallery/1v81b4k', 'MoviesThatFeelLike', 'Gritty, raw, and poignant coming-of-age stories about boys fighting against systemic oppression, violence, and the streets.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (592, '1v81bcp', '90’s Halloween Time.', '90s Halloween Time', '', 'smeapunique', 1785160957, '/r/MoviesThatFeelLike/comments/1v81bcp/90s_halloween_time/', 'https://www.reddit.com/gallery/1v81bcp', 'MoviesThatFeelLike', 'A nostalgic, cozy Halloween atmosphere from the 1990s, filled with classic spooky movies and TV shows that evoke childhood memories of autumn and trick-or-treating.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (593, '1v82bas', 'Movies with the vibe of these books 💙💛', 'Movies with the vibe of these books', 'Looking for movies with this vibe and also any movie that includes the colors blue and yellow together! ', 'OttieStar', 1785163207, '/r/MoviesThatFeelLike/comments/1v82bas/movies_with_the_vibe_of_these_books/', 'https://www.reddit.com/gallery/1v82bas', 'MoviesThatFeelLike', 'A whimsical, storybook-like atmosphere with an emphasis on blue and yellow colors, evoking nostalgia and childlike wonder.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (594, '1v83g2l', 'Other places in New York (that aren''t the ghetto/hoods)', 'Other places in New York (that aren''t the ghetto/hoods)', '', 'Alex_and_cold', 1785165650, '/r/MoviesThatFeelLike/comments/1v83g2l/other_places_in_new_york_that_arent_the/', 'https://www.reddit.com/gallery/1v83g2l', 'MoviesThatFeelLike', 'Seeking New York''s quieter, less stereotypical neighborhoods, with cozy cultural enclaves and atmospheric local color.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (595, '1v84gxr', 'Movies that feel like this?', 'Movies that feel like this?', 'Mysterious town, foggy forests', 'yonkou_akagami', 1785167889, '/r/MoviesThatFeelLike/comments/1v84gxr/movies_that_feel_like_this/', 'https://v.redd.it/zpannstnosfh1', 'MoviesThatFeelLike', 'A mysterious small town shrouded in fog, evoking a haunting and atmospheric Pacific Northwest setting.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (596, '1v853te', 'Movies that feel like this', 'Movies that feel like this', '', 'prettygirlyxxx', 1785169214, '/r/MoviesThatFeelLike/comments/1v853te/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1v853te', 'MoviesThatFeelLike', 'Lavish and gritty tales of wealth, crime, and indulgence.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (597, '1v85gaz', 'A movie where a gigantic cake is eaten', 'A movie where a gigantic cake is eaten', '', 'SecondStarpilot', 1785169949, '/r/MoviesThatFeelLike/comments/1v85gaz/a_movie_where_a_gigantic_cake_is_eaten/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v85gaz/a_movie_where_a_gigantic_cake_is_eaten/', 'MoviesThatFeelLike', 'A playful quest for a film where a giant cake is eaten.', 'skipped', 'no usable images', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (598, '1v86or3', 'Movies that have this mythic old vibe', 'Movies that have this mythic old vibe', '', 'girlyxvibez', 1785172563, '/r/MoviesThatFeelLike/comments/1v86or3/movies_that_have_this_mythic_old_vibe/', 'https://www.reddit.com/gallery/1v86or3', 'MoviesThatFeelLike', 'A mythic, old-world atmosphere steeped in medieval legend and fairy tale.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (599, '1v877dq', 'Expanding film knowledge and looking for recs!', '', '', 'Traditional_Win_8348', 1785173646, '/r/MoviesThatFeelLike/comments/1v877dq/expanding_film_knowledge_and_looking_for_recs/', 'https://www.reddit.com/gallery/1v87321', 'MoviesThatFeelLike', 'Curious and eager to discover new films.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (600, '1v877em', 'Delapitiated concrete brutalism feelings!', '', 'Talking especially European/slavic style (rather than places like Kowloon) with delapitation, cold concrete, dingy hallways etc. 
_Ideally_ not sci-fi or futuristic but open to it. 

Would love drama, thrillers and horrors! 

What I’ve already seen/listed:
• Let the right one in 
• Dune 
• Blade runner(s)
• Enemy, 2013 (oddly enough)
• Chernobyl series 
• Degalok 
', 'pohzu', 1785173647, '/r/MoviesThatFeelLike/comments/1v877em/delapitiated_concrete_brutalism_feelings/', 'https://www.reddit.com/gallery/1v877em', 'MoviesThatFeelLike', 'Gritty, dilapidated concrete brutalist environments with a cold, Eastern European atmosphere.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (601, '1v899if', 'Movies that Feel like Chicago', 'Movies that Feel like Chicago', 'I know Ferris Bueller, The Fugitive, While You Were Sleeping, Home Alone, Thief, The Untouchables, Chicago Cab, High Fidelity, Adventures in Babysitting. Did I miss any? 

Such a beautiful city. ', 'surprisinglynotabot', 1785177845, '/r/MoviesThatFeelLike/comments/1v899if/movies_that_feel_like_chicago/', 'https://www.reddit.com/gallery/1v899if', 'MoviesThatFeelLike', 'A nostalgic and urban atmosphere, celebrating iconic Chicago movie settings.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (602, '1v89hkp', 'Mira 👇', '', 'Cual de todos estos ,seria mi.mejor perfil ?', 'Admirablenabil4212', 1785178321, '/r/MoviesThatFeelLike/comments/1v89hkp/mira/', 'https://www.reddit.com/gallery/1v89hkp', 'MoviesThatFeelLike', 'Baffling off-topic self-promotion creating user hostility.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (603, '1v8a7lk', 'Movies that feel like', '', '', 'ExitExpert3954', 1785179827, '/r/MoviesThatFeelLike/comments/1v8a7lk/movies_that_feel_like/', 'https://www.reddit.com/gallery/1v8a7lk', 'MoviesThatFeelLike', 'A dark, noir-infused art deco atmosphere with retro-futuristic cityscapes and shadowy gothic undertones.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (604, '1v8asww', 'Movies that feel like this', 'Movies that feel like this', '', 'Virtual_Low_7202', 1785181080, '/r/MoviesThatFeelLike/comments/1v8asww/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1v8asww', 'MoviesThatFeelLike', 'A mood of vast, open landscapes and deep cultural narratives, evoking both the beauty and tragedy of the American West and Indigenous life.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (605, '1v8bck9', 'How many of you watched whole avengers movies or particular character whole movies??', '', '[removed]', 'Wide-Reality-1196', 1785182263, '/r/MoviesThatFeelLike/comments/1v8bck9/how_many_of_you_watched_whole_avengers_movies_or/', 'https://i.redd.it/rd9syqjevtfh1.jpeg', 'MoviesThatFeelLike', 'A fan inquiring about others'' viewing habits of Avengers films or individual character arcs.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (606, '1v8eni2', 'movies that feel like this album?', '', '', 'DesperateVariety5418', 1785189508, '/r/MoviesThatFeelLike/comments/1v8eni2/movies_that_feel_like_this_album/', 'https://i.redd.it/ccxy5t9ygufh1.jpeg', 'MoviesThatFeelLike', 'A vague request for movies matching an undisclosed album, leaving the mood undefined.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (607, '1v8eul3', 'Shoot something inspirational', '', '', 'SimpleDoughnut9131', 1785189950, '/r/MoviesThatFeelLike/comments/1v8eul3/shoot_something_inspirational/', 'https://www.reddit.com/gallery/1v8eul3', 'MoviesThatFeelLike', 'A call for inspirational films that uplift and motivate through stories of human achievement and resilience.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (608, '1v8fd85', 'Which movie synonym to your life?', 'Which movie synonym to your life?', '', 'Khon2510', 1785191145, '/r/MoviesThatFeelLike/comments/1v8fd85/which_movie_synonym_to_your_life/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v8fd85/which_movie_synonym_to_your_life/', 'MoviesThatFeelLike', 'Reflective and deeply personal, with a sense of existential contemplation and emotional resonance.', 'skipped', 'no usable images', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (609, '1v8fnjl', 'Movies that feel like', 'Movies that feel like the Strange Man from Red Dead Redemption', 'In that eerie, deathly, devil-is-watching-you-esk. For those curious: he is the strange man from the red dead redemption series.', '_stibor', 1785191832, '/r/MoviesThatFeelLike/comments/1v8fnjl/movies_that_feel_like/', 'https://i.redd.it/scjq7bvunufh1.jpeg', 'MoviesThatFeelLike', 'Eerie, deathly, devil-is-watching-you atmosphere inspired by the Strange Man from Red Dead Redemption.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (610, '1v8fu7u', 'Any recommendations for movies like the russian movie called Coma?', 'Any recommendations for movies like the russian movie called Coma?', '', 'DisasterPhysical527', 1785192287, '/r/MoviesThatFeelLike/comments/1v8fu7u/any_recommendations_for_movies_like_the_russian/', 'https://i.redd.it/xehtvsn7pufh1.jpeg', 'MoviesThatFeelLike', 'Surreal and mind-bending movies about alternate realities and dreams.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (611, '1v8hcrv', 'Any movies with this type of vibe?', 'Any movies with this type of vibe?', 'I''ve always liked older movies but I have never seen a movie that gives me the same creepy vibes of the Texas towers from the 1960s/50s.', 'Affectionate_Tree_94', 1785195963, '/r/MoviesThatFeelLike/comments/1v8hcrv/any_movies_with_this_type_of_vibe/', 'https://www.reddit.com/gallery/1v8hcrv', 'MoviesThatFeelLike', 'Creepy, isolated underwater or oil rig settings from past decades.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (612, '1v8huz8', 'fav movies of this girl', 'fav movies of this girl', '', 'trophymermaid', 1785197175, '/r/MoviesThatFeelLike/comments/1v8huz8/fav_movies_of_this_girl/', 'https://i.redd.it/6j38jvtq3vfh1.jpeg', 'MoviesThatFeelLike', 'Curious and inviting, seeking to discover personal favorites.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (613, '1v8jo5r', 'movies that feel like DIS', 'Movies That Feel Like DIS', '', 'noizuchan', 1785201815, '/r/MoviesThatFeelLike/comments/1v8jo5r/movies_that_feel_like_dis/', 'https://www.reddit.com/gallery/1v8jo5r', 'MoviesThatFeelLike', 'A nostalgic, spooky Halloween aesthetic reminiscent of early 2000s low-poly animation and holiday specials.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (614, '1v8jqd3', 'Movies that feel like the Ride music video', 'Movies that feel like the Ride music video', 'Preferably set in the 70s/80s', 'dryadfairie', 1785201974, '/r/MoviesThatFeelLike/comments/1v8jqd3/movies_that_feel_like_the_ride_music_video/', 'https://www.reddit.com/gallery/1v8jqd3', 'MoviesThatFeelLike', 'A nostalgic, gritty road trip through 70s/80s America with a rebellious, sun-baked desert atmosphere.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (615, '1v8n77v', 'Movies with a similar vibe of this image', 'Movies with a similar vibe of this image', '', 'CommonWar7535', 1785211395, '/r/MoviesThatFeelLike/comments/1v8n77v/movies_with_a_similar_vibe_of_this_image/', 'https://i.redd.it/ad3gn281awfh1.jpeg', 'MoviesThatFeelLike', 'Enchanted and eerie fantasy with a surreal, dreamlike atmosphere.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (616, '1v8n7hn', 'Movies TV shows cartoons or video games with a similar vibe of this image', 'Movies TV shows cartoons or video games with a similar vibe of this image', '', 'CommonWar7535', 1785211414, '/r/MoviesThatFeelLike/comments/1v8n7hn/movies_tv_shows_cartoons_or_video_games_with_a/', 'https://i.redd.it/z25qc7a3awfh1.jpeg', 'MoviesThatFeelLike', 'Dark, atmospheric, and survivalist with a touch of the unknown.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (617, '1v8oqh2', 'Movies that feel like this?', '', '', 'Ractzkindness', 1785216035, '/r/MoviesThatFeelLike/comments/1v8oqh2/movies_that_feel_like_this/', 'https://i.redd.it/99kwo0qtnwfh1.jpeg', 'MoviesThatFeelLike', 'A discussion recommending chivalric and romantic medieval fantasy films, inspired by a mysterious image.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (618, '1v8ou9m', 'Movies like Danger: Diabolik', 'Movies like Danger: Diabolik', 'Ayy I''ve been obsessed with this what else should I check out. Ideally something sexier than Adam West era Batman lol', 'Background-Bed1691', 1785216358, '/r/MoviesThatFeelLike/comments/1v8ou9m/movies_like_danger_diabolik/', 'https://www.reddit.com/gallery/1v8ou9m', 'MoviesThatFeelLike', 'A request for stylish, sexy 1960s spy thrillers with campy and vibrant aesthetics, similar to Danger: Diabolik.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (619, '1v8pau9', 'movies that feel like:', 'movies that feel like:', '', 'Wild_Steak7', 1785217819, '/r/MoviesThatFeelLike/comments/1v8pau9/movies_that_feel_like/', 'https://www.reddit.com/gallery/1v8pau9', 'MoviesThatFeelLike', 'Sun-drenched, melancholic coastal nostalgia.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (620, '1v8pxqo', 'Movies that feel like soulmates in every lifetime?', '', 'Its one of my favorite tropes.

 Any genre.', 'LeSolLaLune', 1785219834, '/r/MoviesThatFeelLike/comments/1v8pxqo/movies_that_feel_like_soulmates_in_every_lifetime/', 'https://www.reddit.com/gallery/1v8pxqo', 'MoviesThatFeelLike', 'A yearning for romantic connections that transcend time, with stories of soulmates finding each other across different lifetimes and dimensions.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (621, '1v8qycy', 'Looking for classic adventure movies', 'Looking for classic adventure movies', 'Not Deliverance or Jaws. Both great movies and I enjoy them but all too common', 'LACarGuy23', 1785223143, '/r/MoviesThatFeelLike/comments/1v8qycy/looking_for_classic_adventure_movies/', 'https://www.reddit.com/gallery/1v8qycy', 'MoviesThatFeelLike', 'Rugged wilderness and nautical adventures with a classic, outdoor feel.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (622, '1v8sw33', 'Movies that feel like these scene queen songs', '', 'Preferably horror and no on screen SA scenes in the movies please <3', 'Dreamdust1600', 1785229745, '/r/MoviesThatFeelLike/comments/1v8sw33/movies_that_feel_like_these_scene_queen_songs/', 'https://www.reddit.com/gallery/1v8sw33', 'MoviesThatFeelLike', 'Dark and edgy horror atmosphere inspired by scene queen songs, with a request to avoid on-screen SA.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (623, '1v8sxku', 'Movies like the crazy dream I had', '', 'I had an absolute bananas dream last night, where I was in a rundown Victorian home, had big 1980''s vibes, on a hilly, dreary street full of other Victorian homes and trees. I was in the home with Ian Mckellen, a woman who looked like Mandy Smith, and Richard Jenkins. They leave the house, and return still looking like them, but clearly aren''t still them, like something creepy or alien inhabited their bodies. The rest of my dream was them trying to get into the house and saying creepy, off things and trying to trick me into letting them back in. Is there anything at all like this, or was my dream completely far out there? Definitely not zombies, they could still talk and think, they were just creepy.', 'Smooth_Island_2393', 1785229879, '/r/MoviesThatFeelLike/comments/1v8sxku/movies_like_the_crazy_dream_i_had/', 'https://www.reddit.com/gallery/1v8sxku', 'MoviesThatFeelLike', 'Creeping dread in a rundown Victorian home as familiar faces become sinister impostors, with a surreal and dreamlike atmosphere.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (624, '1v8unp7', 'What''s the First Film You Ever Remember Watching?', 'What''s the First Film You Ever Remember Watching?', 'Do you remember the very first film you ever watched from your earliest childhood memory?For me, I think it was either Baby''s Day Out or Night at the Museum.

What about you? What''s the first movie you can remember watching, and do you still have a soft spot for it? Share your earliest movie memory in the comments', 'Aggressive-Heart4989', 1785235328, '/r/MoviesThatFeelLike/comments/1v8unp7/whats_the_first_film_you_ever_remember_watching/', 'https://i.redd.it/pmuubdp69yfh1.jpeg', 'MoviesThatFeelLike', 'Nostalgic sharing of earliest childhood movie memories.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (625, '1v8wrs2', 'Movies that are similar or have that vibe?', '', 'https://preview.redd.it/jrsvnthvpyfh1.jpg?width=4000&format=pjpg&auto=webp&s=397ecc7c5b54a42330cddb6b0f4d8a292ffbcb0e

https://preview.redd.it/an3ly3ivpyfh1.jpg?width=6240&format=pjpg&auto=webp&s=b140bf0a35abb3a83b1c72856ed7e9c65ccd990f

https://preview.redd.it/642yzvhvpyfh1.jpg?width=3641&format=pjpg&auto=webp&s=32cef195ed8c1f1488432bbc98b35ff12fca8dac

', 'Careless_Reveal_6285', 1785240947, '/r/MoviesThatFeelLike/comments/1v8wrs2/movies_that_are_similar_or_have_that_vibe/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v8wrs2/movies_that_are_similar_or_have_that_vibe/', 'MoviesThatFeelLike', 'Dark, tense, and unsettling crime thriller with a gritty investigative atmosphere.', 'skipped', 'no usable images', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (626, '1v8x9rm', '70s female coming of age', '', '', 'pinkdragapult', 1785242246, '/r/MoviesThatFeelLike/comments/1v8x9rm/70s_female_coming_of_age/', 'https://www.reddit.com/gallery/1v8x9rm', 'MoviesThatFeelLike', 'A nostalgic yet surreal dive into female adolescence in the 1970s, blending soft-focus dreaminess with gritty realism and moments of horror.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (627, '1v8y4ku', 'Series/Movie where the mystery is somewhere between "fantasy/myth and human science (or even beyond).', 'Series/Movie where the mystery is somewhere between fantasy/myth and human science (or even beyond)', '1) For those who know the Higurashi franchise, you know what the true nature of the events in Hinamizawa is, but in Kai I love how the mystery gives concrete clues that everything happens ALSO for human reasons and not because of the curse.

2) Lost manages to combine mystery very well by placing the myth/fantasy with the "human and scientific" side, even reaching science fiction by talking about the mystery behind the island

3) The X-Files.

I had a lot of doubts about whether to include it or not because the mysteries were often "fanciful," but there was always a human touch, and sometimes the episodes were a mix of "that''s a real creature" and "the American government is involved."

P.S 

Gravity Falls also tends to have these peculiarities.', 'AipomSilver00', 1785244345, '/r/MoviesThatFeelLike/comments/1v8y4ku/seriesmovie_where_the_mystery_is_somewhere/', 'https://www.reddit.com/gallery/1v8y4ku', 'MoviesThatFeelLike', 'A mysterious atmosphere blending elements of fantasy and myth with human science, focusing on mysteries that straddle both realms.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (628, '1v8ypdn', 'Movies/Shows that feel like a cozy city/apartment building with whymsical characters that go on about their daily lives', 'Movies/Shows that feel like a cozy city/apartment building with whimsical characters that go on about their daily lives', 'https://preview.redd.it/snadlqz73zfh1.jpg?width=736&format=pjpg&auto=webp&s=8145b56ad5806304bc8283ec4b0cf939c327542a

https://preview.redd.it/h6h3b8n83zfh1.jpg?width=256&format=pjpg&auto=webp&s=3232cbcb45e214459b0ca7b5a7530e1c4ea2e553

https://preview.redd.it/rgh41hs93zfh1.jpg?width=735&format=pjpg&auto=webp&s=562734a41b6c5c5b0ef1e35bb2f85c77c1700592

https://preview.redd.it/y2phscla3zfh1.jpg?width=561&format=pjpg&auto=webp&s=4bd5f4a53474fdc8db06627f3ba82a44a75c0f76

https://preview.redd.it/8zjz2tmb3zfh1.jpg?width=736&format=pjpg&auto=webp&s=f9fd1f45516ef4070eeb0b9159b4cfc364dc35d0

https://preview.redd.it/m1h04vvm3zfh1.jpg?width=635&format=pjpg&auto=webp&s=983a8e23418d56e54fdf1dd600e7b65e7a7bad21

', 'm00n_l0v3r_', 1785245702, '/r/MoviesThatFeelLike/comments/1v8ypdn/moviesshows_that_feel_like_a_cozy_cityapartment/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v8ypdn/moviesshows_that_feel_like_a_cozy_cityapartment/', 'MoviesThatFeelLike', 'A cozy perspective of city life with whimsical characters living their daily routines.', 'skipped', 'no usable images', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (629, '1v8yupa', 'Movies Similar to Riding in Cars with Boys', 'Movies Similar to Riding in Cars with Boys', 'Hello! I’m trying to find other movies that feel like Riding in Cars with Boys. It can be the similar type of aesthetic, themes that they discuss, the kind of humor and seriousness, etc.', 'iamnotmothman', 1785246051, '/r/MoviesThatFeelLike/comments/1v8yupa/movies_similar_to_riding_in_cars_with_boys/', 'https://i.redd.it/el3c79y25zfh1.jpeg', 'MoviesThatFeelLike', 'A nostalgic and bittersweet coming-of-age story blending humor and serious life themes.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (630, '1v8zfr5', 'Rain and nature, action thrillers?', '', 'Looking for some movie recommendations to enjoy while it’s warm and cosy inside and cold and rainy outside - something with beautiful natural scenery and lots of rain, drizzle, cold as the backdrop to an action/thriller - thanks! ', 'Cantona66', 1785247360, '/r/MoviesThatFeelLike/comments/1v8zfr5/rain_and_nature_action_thrillers/', 'https://www.reddit.com/gallery/1v8zfr5', 'MoviesThatFeelLike', 'Cozy thrillers set in cold, rainy natural landscapes.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (631, '1v8zyma', 'Movies thatfeel like "Last Train Home" by Pat Methany?', 'Movies that feel like ''Last Train Home'' by Pat Metheny?', 'https://preview.redd.it/vuve9i0iczfh1.png?width=349&format=png&auto=webp&s=910c56dd005ba295d658a8bdcb59f6cdfe5af8d6

', 'armpitliker', 1785248556, '/r/MoviesThatFeelLike/comments/1v8zyma/movies_thatfeel_like_last_train_home_by_pat/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v8zyma/movies_thatfeel_like_last_train_home_by_pat/', 'MoviesThatFeelLike', 'A melancholic and nostalgic atmosphere, evoking a scenic train journey and reflective solitude.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (632, '1v900us', 'Looking for movies that are heartbreaking but also feel like home', '', 'looking for movies that are emotionally devastating but still feel warm, comforting, or like home.The kind of films that leave you crying but also make you feel understood.', 'ishitaa07', 1785248690, '/r/MoviesThatFeelLike/comments/1v900us/looking_for_movies_that_are_heartbreaking_but/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v900us/looking_for_movies_that_are_heartbreaking_but/', 'MoviesThatFeelLike', 'Emotionally devastating films that feel warm, comforting, and like home.', 'skipped', 'no usable images', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (633, '1v934lb', 'I''m looking for more movies stylized with this strong blue/green-ish tint and heavy contrast.', '', '', 'gen-mod-ape', 1785255429, '/r/MoviesThatFeelLike/comments/1v934lb/im_looking_for_more_movies_stylized_with_this/', 'https://www.reddit.com/gallery/1v934lb', 'MoviesThatFeelLike', 'Cool, stylized, and moody films with a strong blue-green tint and heavy contrast.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (634, '1v9390s', 'Movies that make you ask "who was this made for?"', 'Movies that make you ask "who was this made for?"', 'Feel like torturing myself today, recommend me some movies that, miss the mark with the target audience, themes, tones, music that clash with each other, movies that only the director could enjoy, etc. I want the bad and bizarre (or a misunderstood gem). ', 'Jellypathicdream', 1785255694, '/r/MoviesThatFeelLike/comments/1v9390s/movies_that_make_you_ask_who_was_this_made_for/', 'https://www.reddit.com/gallery/1v9390s', 'MoviesThatFeelLike', 'A desperate craving for bizarre, misfired movies that make you question their existence.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (635, '1v94skh', 'movies with this feeling', '', '', 'brenna_is_so_sad', 1785258961, '/r/MoviesThatFeelLike/comments/1v94skh/movies_with_this_feeling/', 'https://www.reddit.com/gallery/1v94skh', 'MoviesThatFeelLike', 'A peaceful, contemplative atmosphere that invites introspection and quiet reflection on everyday life.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (636, '1v95rgr', 'Movie like Chemtrails over the Country Club', 'Movie like Chemtrails over the Country Club', 'Hey guys, I‘m going through a tough time atm. Somehow one bad thing happening after another. For whatever reason I wanna indulge in that feeling. And even though I know that chemtrails isn’t necessarily a song about sadness and grief but it’s vibe embodies these feelings for me. And now to my question: do you have recommendations for movies that feel like Chemtrails over the Country Club by Lana del Rey? Somehow this song scratches a weird itch for me and I am looking for the same movies with this dreamy, nostalgic, melancholic, sad,americana (also southern gothic???)) vibe. I hope you get what I mean. Even if you don’t have any specific recommendations, I’d be interested if you get what I mean and have the same feeling towards the song.  
Thx xxxx', 'Bloom5398', 1785261019, '/r/MoviesThatFeelLike/comments/1v95rgr/movie_like_chemtrails_over_the_country_club/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v95rgr/movie_like_chemtrails_over_the_country_club/', 'MoviesThatFeelLike', 'A dreamy, nostalgic, melancholic, sad Americana/southern gothic atmosphere.', 'skipped', 'no usable images', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (637, '1v95tjh', 'Rate this Series from 1 to 10', '', '', 'Sensitive-Level-5386', 1785261140, '/r/MoviesThatFeelLike/comments/1v95tjh/rate_this_series_from_1_to_10/', 'https://i.redd.it/gqpsmirud0gh1.jpeg', 'MoviesThatFeelLike', 'Seeking ratings for a series.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (638, '1v96qr2', 'Movies that about forbidden Love?', '', 'Suggest me!', 'Character-Bat-7397', 1785263044, '/r/MoviesThatFeelLike/comments/1v96qr2/movies_that_about_forbidden_love/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v96qr2/movies_that_about_forbidden_love/', 'MoviesThatFeelLike', 'A collection of films exploring forbidden love across various eras and genres, from tragic classics to modern romances, evoking passion, longing, and the pain of societal barriers.', 'skipped', 'no usable images', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (639, '1v96xs4', 'What movie left you sitting like this for days?', 'What movie left you sitting like this for days?', '', 'girlysxxface', 1785263446, '/r/MoviesThatFeelLike/comments/1v96xs4/what_movie_left_you_sitting_like_this_for_days/', 'https://i.redd.it/rn6uwurnk0gh1.jpeg', 'MoviesThatFeelLike', 'A collection of devastating films that leave you emotionally stunned and contemplative for days.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (640, '1v97dkq', 'Best movies/TV show about Revenge?', 'Best movies/TV show about Revenge?', 'Suggest me!', 'Character-Bat-7397', 1785264350, '/r/MoviesThatFeelLike/comments/1v97dkq/best_moviestv_show_about_revenge/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v97dkq/best_moviestv_show_about_revenge/', 'MoviesThatFeelLike', 'A seeking of intense, cathartic, and dark revenge narratives across film and television.', 'skipped', 'no usable images', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (641, '1v97qy5', 'Movies/TV show about poor people turn to rich?', 'Movies/TV show about poor people turn to rich?', 'Suggest me!', 'Character-Bat-7397', 1785265135, '/r/MoviesThatFeelLike/comments/1v97qy5/moviestv_show_about_poor_people_turn_to_rich/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v97qy5/moviestv_show_about_poor_people_turn_to_rich/', 'MoviesThatFeelLike', 'Upward mobility and rags-to-riches stories with dramatic transformations.', 'skipped', 'no usable images', NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (642, '1v97yq3', 'Movies that give Harry Potter vibes', '', '', 'prettygirlyxxx', 1785265589, '/r/MoviesThatFeelLike/comments/1v97yq3/movies_that_give_harry_potter_vibes/', 'https://www.reddit.com/gallery/1v97yq3', 'MoviesThatFeelLike', 'A magical and whimsical blend of childhood wonder, dark fantasy, and nostalgic adventure, with an undercurrent of British charm and gothic horror.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (643, '1v98kx5', 'A movie that gives the same experience as Evangelion', '', 'I''m looking for something that captures the same feeling as Evangelion: surrealism and weirdness, loneliness, depression, existential crisis, self-hatred and hatred of others, and a portrayal of people''s hypocrisy how they appear happy and strong on the outside while they''re actually miserable and broken inside. I also love unique, strange art styles, mystery, and events that aren''t fully explained.

It doesn''t have to be a movie. I''m also interested in TV shows, Western animation, anime, or novels.', 'Reasonable-Quit5869', 1785266908, '/r/MoviesThatFeelLike/comments/1v98kx5/a_movie_that_gives_the_same_experience_as/', 'https://www.reddit.com/gallery/1v98kx5', 'MoviesThatFeelLike', 'Surreal existential dread, psychological turmoil, and emotional despair.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (644, '1v98ljx', 'Movies that feel like this', '', '', 'girlyxvibez', 1785266947, '/r/MoviesThatFeelLike/comments/1v98ljx/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1v98ljx', 'MoviesThatFeelLike', 'A romantic, nostalgic, and whimsical mood set in historical or fantastical periods, evoking wistful longing.', 'publishable', NULL, NULL, '2026-07-29 20:51:09', '2026-07-29 20:51:09');
