-- 0051_seed_20260731T033312Z_01_posts.sql: data seed from pipeline:load run.
-- Generated:  2026-07-31T03:33:23.627478+00:00
-- Run started: 2026-07-31T03:33:12.609128+00:00
-- Source: data/working/load manifest from this run.
--
-- Idempotent: every INSERT is INSERT OR IGNORE, keyed by the
-- table's natural unique constraint.  Wrangler's migration
-- tracking normally prevents re-apply; the OR IGNORE is
-- defense in depth for partial / interrupted re-runs.
--
-- Chunk: 01_posts (1/5)
-- Tables: imported_vibe_posts.
-- Pipeline-state tables (processing_runs, pipeline_artifacts)
-- are intentionally excluded — they're per-run bookkeeping.

INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (741, '1v2s0fb', 'Guys one underrated ROM-Drama you have come across?Would really help as a precedence for my script? Something raw, real , emotionally sound , infectiously romantic. Anyone?', 'Guys one underrated ROM-Drama you have come across? Would really help as a precedence for my script? Something raw, real, emotionally sound, infectiously romantic. Anyone?', '', 'No-Shoulder9489', 1784660850, '/r/MoviesThatFeelLike/comments/1v2s0fb/guys_one_underrated_romdrama_you_have_come/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v2s0fb/guys_one_underrated_romdrama_you_have_come/', 'MoviesThatFeelLike', 'Searching for a raw, emotionally sound, and infectiously romantic underrated romantic drama, something real and teary-eyed.', 'skipped', 'no usable images', NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (742, '1v2so5c', 'Movies with this same horror vibe?', 'Movies with this same horror vibe?', '', 'Jealous-Hurry1316', 1784662255, '/r/MoviesThatFeelLike/comments/1v2so5c/movies_with_this_same_horror_vibe/', 'https://www.reddit.com/gallery/1v2so5c', 'MoviesThatFeelLike', 'Gothic, occult-tinged horror with old-world dread and a sinister religious undercurrent.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (743, '1v2u7tw', 'Movies that feel like that?', 'Movies that feel like that?', '', 'AlecitaMor15', 1784665604, '/r/MoviesThatFeelLike/comments/1v2u7tw/movies_that_feel_like_that/', 'https://www.reddit.com/gallery/1v2u7tw', 'MoviesThatFeelLike', 'A warm, nostalgic, and magical friendship vibe with summer coming-of-age energy.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (744, '1v2umhf', 'Movies that feel like this?', 'Movies that feel like this?', 'Basically, dark sci-fi with cool outfits and techno music', 'batcave444', 1784666493, '/r/MoviesThatFeelLike/comments/1v2umhf/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1v2umhf', 'MoviesThatFeelLike', 'A dark, futuristic mood with sleek outfits and pounding techno, evoking cyberpunk corridors and cold sci-fi dread.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (745, '1v2v50j', 'Movies with this vibe?', 'Movies with this vibe?', '', 'DependentBrother6817', 1784667636, '/r/MoviesThatFeelLike/comments/1v2v50j/movies_with_this_vibe/', 'https://v.redd.it/o86sego5dneh1', 'MoviesThatFeelLike', 'A moody, rain-soaked, neon-lit urban atmosphere with a sense of loneliness, nostalgia, and dreamy melancholy.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (746, '1v2vdfh', 'Frederik Heyman''s Works', 'Frederik Heyman''s Works', 'For those who aren''t familiar with him, he''s a belgian artist that I discovered a few years ago after watching Arca''s music video for their songs. 

I tried to look him up online for his other projects and that''s when I fell in love with his work. His art''s visual language is very striking and I love the fusion of human bodies + technology that is a common theme in his projects. I also added a screenshot from an interview about his creative process and how he creates these worlds, just to provide more context I guess.

As of now, I can only think of "Crash" by David Cronenberg, and maybe even Blade Runnee 2049 (Denis Villeneuve) 

Hoping you guys could provide some other suggestions. I really dig this person''s artistic vision and I just wanna immerse myself more in these environments🥹', 'drinkablesausage7', 1784668145, '/r/MoviesThatFeelLike/comments/1v2vdfh/frederik_heymans_works/', 'https://www.reddit.com/gallery/1v2vdfh', 'MoviesThatFeelLike', 'A dark, immersive fascination with biomechanical worlds and striking body-horror aesthetics, seeking art and films that feel alien, technological, and visceral.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (747, '1v2w35z', 'Feels like a VSCO filter and fairy lights', 'VSCO filter and fairy lights', 'Feels like a rainy Sunday evening, soft/ambient lighting, indie soundtrack. 2018/19 cozy romance', 'dontaskmeaboutmath', 1784669768, '/r/MoviesThatFeelLike/comments/1v2w35z/feels_like_a_vsco_filter_and_fairy_lights/', 'https://www.reddit.com/gallery/1v2w35z', 'MoviesThatFeelLike', 'Cozy, rainy Sunday evening with soft ambient lighting, fairy lights, and an indie soundtrack—definitely 2018/19 cozy romance vibes.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (748, '1v2z576', 'Movies like Incantation recommandations', 'Movies like Incantation recommendations', 'Does anyone have a list of films like Incantations. I’ve been obsessed with this movie and I need to find similar things to watch!! ', 'Valuable-Current-881', 1784677076, '/r/MoviesThatFeelLike/comments/1v2z576/movies_like_incantation_recommandations/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v2z576/movies_like_incantation_recommandations/', 'MoviesThatFeelLike', 'An obsessed horror fan urgently seeking similarly creepy and dread-filled films to Incantation.', 'skipped', 'no usable images', NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (749, '1v30973', 'Movies that feel like this', 'Movies that feel like this', 'Sort of an optimistic green future that a lot of millennials thought the future would be.', 'hikingandtravel', 1784679860, '/r/MoviesThatFeelLike/comments/1v30973/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1v30973', 'MoviesThatFeelLike', 'A nostalgic yearning for an optimistically green utopian future that millennials imagined, full of clean tech and hopeful wonder.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (750, '1v31u5z', 'Movies that feel like this?', 'Movies that feel like this?', '', 'Seaofcloud1866', 1784684036, '/r/MoviesThatFeelLike/comments/1v31u5z/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1v31u5z', 'MoviesThatFeelLike', 'A kitschy, colorful fever dream of a retro-futuristic space diner.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (751, '1v32cgo', 'Exhausting, haunting, potentially cathartic', 'Exhausting, haunting, potentially cathartic', 'Pics for references

Burnhouse Lane (Game)

Malice@Doll (anime series/movie)

Silent Hill 3 (game)

Where the Dead Go to Die (movie)', 'battlebun1516', 1784685402, '/r/MoviesThatFeelLike/comments/1v32cgo/exhausting_haunting_potentially_cathartic/', 'https://www.reddit.com/gallery/1v32cgo', 'MoviesThatFeelLike', 'Exhausting, haunting, and potentially cathartic—a bleak surreal nightmare that may offer emotional release.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (752, '1v32d1p', 'movies that are like Hotel', 'movies that are like Hotel', 'I saw this last night and it blew my mind... someone had recommended it from another post and whoever you are THANK YOU!! I''d love to know if there are any more movies out there like this one... foreign, arthouse, psychological, etc. Thank you!!', 'JenSlice', 1784685444, '/r/MoviesThatFeelLike/comments/1v32d1p/movies_that_are_like_hotel/', 'https://i.redd.it/da5a3gswtoeh1.jpeg', 'MoviesThatFeelLike', 'A thrilled and curious viewer looking for more mind-bending, eerie arthouse films with a similarly unsettling, indefinite atmosphere after being blown away by Hotel.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (753, '1v32yor', 'soul crushing heartbreak', 'Soul Crushing Heartbreak', 'movie recommendation’s for someone going through a breakup? I don’t want funny comedy. I want to watch the most gut wrenching heart breaking poetic romance unfold. maybe just to feel something. 
Bonus points for - Despair & Internal battle of love ', 'Awkward_Sundae2669', 1784687047, '/r/MoviesThatFeelLike/comments/1v32yor/soul_crushing_heartbreak/', 'https://i.redd.it/qzhpgthvyoeh1.jpeg', 'MoviesThatFeelLike', 'Aching for a soul-crushing, poetic romance to mirror the despair and internal battle of heartbreak.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (754, '1v348cw', 'Movies or shows that feel like this. Isolated, Comforting, Peace, Calming', 'Movies or shows that feel like this. Isolated, Comforting, Peace, Calming', 'I listen to a lot of YouTube music with this type of feel to it. A few examples:

* https://www.youtube.com/watch?v=DaabM_HRQtc&list=RDDaabM_HRQtc&start_radio=1
* https://www.youtube.com/watch?v=E-197j8OHi4&list=RDurP8Qwihk9A&index=10
* https://www.youtube.com/watch?v=ys-QrzqOs2w&list=RDys-QrzqOs2w&start_radio=1

Not entirely sure what I''m looking for here or if it even exists. I find this type of music so very calming. Was wondering if there was a movie or show I could have on in the background that give a similar vibe.', 'kerghan41', 1784690499, '/r/MoviesThatFeelLike/comments/1v348cw/movies_or_shows_that_feel_like_this_isolated/', 'https://www.reddit.com/gallery/1v348cw', 'MoviesThatFeelLike', 'A search for quietly absorbing, isolated, and calming films or shows to play in the background.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (755, '1v34dul', 'Movies with this summer aesthetic?', 'Movies with this summer aesthetic', '', 'Enchant23', 1784690936, '/r/MoviesThatFeelLike/comments/1v34dul/movies_with_this_summer_aesthetic/', 'https://www.reddit.com/gallery/1v34dul', 'MoviesThatFeelLike', 'Sun-bleached seaside nostalgia with a carefree, slightly edgy summer energy.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (756, '1v34ffu', 'underseen, otherworldly', 'underseen, otherworldly', 'water, painterly, otherworldly...preferably low budget or experimental, something underseen or underground', 'lithiumpokes', 1784691061, '/r/MoviesThatFeelLike/comments/1v34ffu/underseen_otherworldly/', 'https://www.reddit.com/gallery/1v34ffu', 'MoviesThatFeelLike', 'A request for underseen, painterly, and otherworldly films with water themes and low-budget or experimental sensibilities.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (757, '1v35w92', 'Movies that feel like this', 'Movies that feel like this', '', 'Classic_Recover2114', 1784695390, '/r/MoviesThatFeelLike/comments/1v35w92/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1v35w92', 'MoviesThatFeelLike', 'A nostalgic, cozy yet unsettling atmosphere centered on beautiful craftsman homes and autumnal domesticity.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (758, '1v367c5', 'Feels like Florida Man', 'Feels like Florida Man', '', 'ForsakenAssistant201', 1784696321, '/r/MoviesThatFeelLike/comments/1v367c5/feels_like_florida_man/', 'https://www.reddit.com/gallery/1v367c5', 'MoviesThatFeelLike', 'Sweltering, chaotic, and delightfully deranged—a sun-baked fever dream of weird Floridian antics.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (759, '1v36cu2', 'A 39 year old emotional log jam just broke open in me last night. Give me a movie that will wreck me now that I’m open.', 'A 39 year old emotional log jam just broke open in me last night. Give me a movie that will wreck me now that I’m open.', '', 'Milhouse242', 1784696774, '/r/MoviesThatFeelLike/comments/1v36cu2/a_39_year_old_emotional_log_jam_just_broke_open/', '/r/MovieSuggestions/comments/1v33ouw/a_39_year_old_emotional_log_jam_just_broke_open/', 'MoviesThatFeelLike', 'An emotional log jam finally breaks, leaving you raw and desperate for a movie that will absolutely wreck you.', 'skipped', 'no usable images', NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (760, '1v3719z', 'movies where you watch someone grow up until they wonder where all the joy of their simpler childhood went', 'movies where you watch someone grow up until they wonder where all the joy of their simpler childhood went', '', 'AyyArmaan', 1784698914, '/r/MoviesThatFeelLike/comments/1v3719z/movies_where_you_watch_someone_grow_up_until_they/', 'https://i.redd.it/8z6wbizuxpeh1.png', 'MoviesThatFeelLike', 'A wistful, nostalgic mood about growing up and losing the simple joy of childhood.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (761, '1v391wn', 'Movies that feel like a neutral milk hotel song', 'Movies that feel like a neutral milk hotel song', '', 'No_Individual_8663', 1784705539, '/r/MoviesThatFeelLike/comments/1v391wn/movies_that_feel_like_a_neutral_milk_hotel_song/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v391wn/movies_that_feel_like_a_neutral_milk_hotel_song/', 'MoviesThatFeelLike', 'A whimsically melancholic and nostalgic search for films with the eccentric, emotionally raw atmosphere of a Neutral Milk Hotel song.', 'skipped', 'no usable images', NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (762, '1v3aeff', 'Movies that feel like this?', 'Movies that feel like this', '', 'regression-analysis', 1784710144, '/r/MoviesThatFeelLike/comments/1v3aeff/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1v3aeff', 'MoviesThatFeelLike', 'Sun-scorched African adventure nostalgia — wide savannas, wildlife, and classic 80s/90s movie energy.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (763, '1v3aj55', 'Is there anything where there is a similar vibe?', 'Is there anything where there is a similar vibe?', '', 'Conscious_Loss_3279', 1784710617, '/r/MoviesThatFeelLike/comments/1v3aj55/is_there_anything_where_there_is_a_similar_vibe/', 'https://www.reddit.com/gallery/1v3aj55', 'MoviesThatFeelLike', 'A wistful, unsettling search for surreal dreamlike media where glowing light and hidden doors hint at a thin layer of reality.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (764, '1v3g3jp', 'Movies that feel like this shot', 'Movies that feel like this shot', '', 'Male-2003', 1784726686, '/r/MoviesThatFeelLike/comments/1v3g3jp/movies_that_feel_like_this_shot/', 'https://i.redd.it/xmcu50rq8seh1.jpeg', 'MoviesThatFeelLike', 'A stark, sun-bleached expanse where lone figures stand against towering natural forces, evoking isolation, endurance, and the sublime.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (765, '1v3gntl', 'Movies that rugpull you so hard you do a flip mid air and break your neck upon landing.', '', 'Here''s two examples of what I mean:


- Tusk (2014) : You sign up for a funny story with a bizarre premise and end up gruesomely exposed to some grade A body horror of the most mean spirited variety. 

- Bone Tomahawk (2015): You sign up for a cowboys and Indians western and end up with a story about a bunch of very human people suffering mercilessly at the hands of chalky, giant man-eating, all-male cavemen.

- (A slightly less horrifying example) Sinners (2025): You sit down to watch a crime and action movie but it turns out it is actually about two criminals up against honest to god blood drinking vampires. ', 'WetBerri3s', 1784728009, '/r/MoviesThatFeelLike/comments/1v3gntl/movies_that_rugpull_you_so_hard_you_do_a_flip_mid/', 'https://www.reddit.com/gallery/1v3gntl', 'MoviesThatFeelLike', 'A celebration of cinematic rug-pulls: films that start as one thing and violently become something else, mixing dread, disbelief, and excitement.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (766, '1v3gwy8', 'Movies that feel like an intensely deep, character-driven, and semi-plausible future history based on Gnosticism and Jungian psychology.', 'Movies that feel like an intensely deep, character-driven, and semi-plausible future history based on Gnosticism and Jungian psychology.', '', 'Zythomancer', 1784728595, '/r/MoviesThatFeelLike/comments/1v3gwy8/movies_that_feel_like_an_intensely_deep/', 'https://www.reddit.com/gallery/1v3gwy8', 'MoviesThatFeelLike', 'A deep, character-driven search for meaning that blends Gnostic mysticism, Jungian psychology, and speculative future history, evoking an intense and philosophical atmosphere.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (767, '1v3lxvr', 'I wanted to feel warm', 'I wanted to feel warm', '', 'PracticalMagic3015', 1784739368, '/r/MoviesThatFeelLike/comments/1v3lxvr/i_wanted_to_feel_warm/', 'https://www.reddit.com/gallery/1v3lxvr', 'MoviesThatFeelLike', 'A cozy, nostalgic warmth with a gentle, tender melancholy, seeking comfort in familiar and compassionate stories.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (768, '1v3pgnh', 'Other movies that feel like this?', 'Other movies that feel like this', '', 'Forsaken_Bison_475', 1784746598, '/r/MoviesThatFeelLike/comments/1v3pgnh/other_movies_that_feel_like_this/', 'https://i.redd.it/vvoa2u9yvteh1.png', 'MoviesThatFeelLike', 'Craving hyper-stylized, CGI-heavy mythological epics filled with over-the-top action, ancient-world grandeur, and larger-than-life characters.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (769, '1v3ponv', 'Loser girl/girl failure', 'Loser girl/girl failure', '', 'BillythenotaKid', 1784747044, '/r/MoviesThatFeelLike/comments/1v3ponv/loser_girlgirl_failure/', 'https://www.reddit.com/gallery/1v3ponv', 'MoviesThatFeelLike', 'Raw, tender, and achingly awkward portraits of young women who are broke, lost, or messy — failure as a vibe.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (770, '1v3q7bw', 'Movies feels like that?', 'Movies that feel like that?', '', 'AlecitaMor15', 1784748128, '/r/MoviesThatFeelLike/comments/1v3q7bw/movies_feels_like_that/', 'https://www.reddit.com/gallery/1v3q7bw', 'MoviesThatFeelLike', 'Creepy, dark rural horror with an unsettling, supernatural dread.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (771, '1v3rqtu', 'Movies that feel like this?', 'Movies that feel like this?', '', 'Ractzkindness', 1784751318, '/r/MoviesThatFeelLike/comments/1v3rqtu/movies_that_feel_like_this/', 'https://i.redd.it/mqe28oez9ueh1.jpeg', 'MoviesThatFeelLike', 'A moody, misty gothic castle scene that feels like a dark fantasy fairytale with medieval horror overtones.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (772, '1v3s0xz', 'Postpartum and boreddd', 'Postpartum and boreddd', '', 'Mission-Camera8072', 1784751875, '/r/MoviesThatFeelLike/comments/1v3s0xz/postpartum_and_boreddd/', '/r/MovieSuggestions/comments/1v3s0qc/postpartum_and_boreddd/', 'MoviesThatFeelLike', 'Postpartum and bored, craving high-energy movies that are anything but slow, with a touch of tragedy.', 'skipped', 'no usable images', NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (773, '1v3se1v', 'Liminal ocean horror 🌊🌑🦭', 'Liminal ocean horror', '', 'Ok-Papaya-6745', 1784752666, '/r/MoviesThatFeelLike/comments/1v3se1v/liminal_ocean_horror/', 'https://www.reddit.com/gallery/1v3se1v', 'MoviesThatFeelLike', 'Liminal, eerie ocean horror with a sense of isolation and dread.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (774, '1v3t938', 'Movies that have this vibe?', 'Movies that have this vibe?', '', 'vladkudas', 1784754568, '/r/MoviesThatFeelLike/comments/1v3t938/movies_that_have_this_vibe/', 'https://i.redd.it/5ydst3bjjueh1.png', 'MoviesThatFeelLike', 'A monochrome, fog-drenched nightmare of quiet dread, ancient forests, and existential unease.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (775, '1v3u8q5', 'Movies that feel like this that aren’t Practical Magic, The Craft, or The VVitch', 'Witchy movies that feel like Practical Magic, The Craft, or The VVitch', '', 'knitbitch007', 1784756770, '/r/MoviesThatFeelLike/comments/1v3u8q5/movies_that_feel_like_this_that_arent_practical/', 'https://www.reddit.com/gallery/1v3u8q5', 'MoviesThatFeelLike', 'A witchy, autumnal atmosphere with 90s nostalgia and dark feminine magic, mixing cozy Halloween charm with occult eeriness.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (776, '1v3ubec', 'Megalomania? Either way Adam Driver doesn’t understand how an Architectural T-Square is different from his light saber. What Blockbuster movie had no real impact?', 'Megalomania? Either way Adam Driver doesn’t understand how an Architectural T-Square is different from his light saber. What Blockbuster movie had no real impact?', '', 'Least-Improvement439', 1784756933, '/r/MoviesThatFeelLike/comments/1v3ubec/megalomania_either_way_adam_driver_doesnt/', '/r/AlignmentChartFills/comments/1v3ua2w/megalomania_either_way_adam_driver_doesnt/', 'MoviesThatFeelLike', 'A sarcastic, mocking critique of a would-be epic blockbuster that failed to leave any cultural mark.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (777, '1v3utck', 'Movies/Animes That Give This Vibe', 'Movies/Animes That Give This Vibe', 'Help me please find more Animes or movies', 'Character-Bat-7397', 1784758073, '/r/MoviesThatFeelLike/comments/1v3utck/moviesanimes_that_give_this_vibe/', 'https://www.reddit.com/gallery/1v3utck', 'MoviesThatFeelLike', 'A nostalgic, sun-washed high-school summer atmosphere—sunsets through classroom windows, soft longing, and bittersweet romance.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (778, '1v3v688', 'Movies that feel like Swing Girls, Kamikaze Girls, Uptown Girls, and Welcome to the Dollhouse', 'Movies that feel like Swing Girls, Kamikaze Girls, Uptown Girls, and Welcome to the Dollhouse', 'The through line of the movies is female adolescence.', 'blink_twice_9465', 1784758900, '/r/MoviesThatFeelLike/comments/1v3v688/movies_that_feel_like_swing_girls_kamikaze_girls/', 'https://www.reddit.com/gallery/1v3v688', 'MoviesThatFeelLike', 'A nostalgic, quirky celebration of female adolescence and teenage girlhood.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (779, '1v3vc5g', 'Bring lost film, Crazy Times 1981 to viewers, Ray Liotta, David Caruso', 'Bring lost film, Crazy Times 1981 to viewers, Ray Liotta, David Caruso', 'Hey everyone!

I’m a Ray Liotta fan and have been going through his entire filmography but hit a real roadblock with the 1981 TV film Crazy Times. I personally reached out to Warner Bros. Licensing, and they officially confirmed that the master tape for this film is safe in their vault.

The film also features early performances by David Caruso, Michael Paré, and Amy Madigan. However, corporate policy prevents the studio from releasing copies to individuals, so an official archival release is our only way to see it!

Change.org notes that petitions reaching 1,000 supporters are 5x more likely to get more attention and that can help reach a studio decision maker''s attention. I created a petition to show Warner Archive that there is a real audience ready to buy or stream this piece of TV history and this coming of age story set in the 1950’s.

Please take 10 seconds to sign and share and thank you for your support in bring this film out of the vault!

LINK:  
https://c.org/rg6KLr97Nb', 'AdhesivenessJust96', 1784759290, '/r/MoviesThatFeelLike/comments/1v3vc5g/bring_lost_film_crazy_times_1981_to_viewers_ray/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v3vc5g/bring_lost_film_crazy_times_1981_to_viewers_ray/', 'MoviesThatFeelLike', 'A dedicated fan''s campaign to bring a lost Ray Liotta film to light, filled with hopeful persistence and community support.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (780, '1v3vofv', 'What are some films that absolutely Devastate you?', 'What are some films that absolutely Devastate you?', '', 'Omnishambles_88', 1784760096, '/r/MoviesThatFeelLike/comments/1v3vofv/what_are_some_films_that_absolutely_devastate_you/', '/r/u_Omnishambles_88/comments/1v3vo4w/what_are_some_films_that_absolutely_devastate_you/', 'MoviesThatFeelLike', 'Heavy, devastating films that leave you emotionally wrecked and numb.', 'skipped', 'no usable images', NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (781, '1v3zi1s', 'Stories that are sci-fi on the outside, but fantasy on the inside', 'Sci-fi on the outside, fantasy on the inside', '', 'LeonardoKlotzTomaz', 1784769941, '/r/MoviesThatFeelLike/comments/1v3zi1s/stories_that_are_scifi_on_the_outside_but_fantasy/', 'https://www.reddit.com/gallery/1v3zi1s', 'MoviesThatFeelLike', 'A curious hunt for stories with a sci-fi surface but a fantastical, mythic core.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (782, '1v3zmtn', 'Norse or British folk horror', 'Norse or British folk horror', 'Sacred rites, Norse spirituality, nature, isolation. I''ve already seen the Ritual, Midsommar, The Northman and Hagazusa', 'TheEggnoggamer', 1784770295, '/r/MoviesThatFeelLike/comments/1v3zmtn/norse_or_british_folk_horror/', 'https://www.reddit.com/gallery/1v3zmtn', 'MoviesThatFeelLike', 'A yearning for atmospheric, ritual-driven folk horror rooted in Norse and British traditions, emphasizing nature and isolation.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (783, '1v40htt', 'Horror Movies that feel like “The Knick” (HBO)', 'Horror Movies that feel like The Knick (HBO)', '', 'CryGroundbreaking945', 1784772595, '/r/MoviesThatFeelLike/comments/1v40htt/horror_movies_that_feel_like_the_knick_hbo/', 'https://www.reddit.com/gallery/1v40htt', 'MoviesThatFeelLike', 'A dark, grimy, historical medical-horror atmosphere with early-1900s surgical and asylum eeriness.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (784, '1v42ba4', 'Movies with a similar feel to Underworld?', 'Movies with a similar feel to Underworld?', '', 'premegoodeats', 1784777644, '/r/MoviesThatFeelLike/comments/1v42ba4/movies_with_a_similar_feel_to_underworld/', 'https://i.redd.it/jbzs9am9gweh1.jpeg', 'MoviesThatFeelLike', 'Fans seeking films that match Underworld''s dark, gothic vampire-action atmosphere and stylishly brooding tone.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (785, '1v42gsu', 'Looking for movies with these kinds of vibes', 'Looking for movies with these kinds of vibes', '', 'Only_Fee2422', 1784778082, '/r/MoviesThatFeelLike/comments/1v42gsu/looking_for_movies_with_these_kinds_of_vibes/', 'https://www.reddit.com/gallery/1v424zn', 'MoviesThatFeelLike', 'Curious and open, searching for movies that match a particular unspecified mood.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (786, '1v42owy', 'Movies that give any of these vibes', 'Movies that give any of these vibes', 'Soo I’m aware that all of them are very different so basically I’m searching for different movies, the one you find most similar to any of the pictures, if that makes sense.

Is there a movie that comes to mind when you see any of the pictures? Every suggestion is welcomed!! (Even if it’s not as accurate)', 'Only_Fee2422', 1784778745, '/r/MoviesThatFeelLike/comments/1v42owy/movies_that_give_any_of_these_vibes/', 'https://www.reddit.com/gallery/1v42owy', 'MoviesThatFeelLike', 'A whimsical dark-fantasy fairytale collage with carnival curiosities, surreal dreamscapes, and nostalgic childhood wonder.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (787, '1v42v81', 'Have any of you made LB lists of the suggestions here?', 'Have any of you made LB lists of the suggestions here?', 'I’d love the links if you have!!', 'H0llywoodBabylon', 1784779254, '/r/MoviesThatFeelLike/comments/1v42v81/have_any_of_you_made_lb_lists_of_the_suggestions/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v42v81/have_any_of_you_made_lb_lists_of_the_suggestions/', 'MoviesThatFeelLike', 'A curious community member asking for links to Letterboxd lists of suggested movies, seeking shared curation and connection.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (788, '1v42xci', 'Need something like these movies', 'Need something like these movies', 'https://preview.redd.it/depl0grclweh1.png?width=1920&format=png&auto=webp&s=1816a1d8c629687648e88778e0ea2db8ff8de300

https://preview.redd.it/4t21t0tskweh1.png?width=599&format=png&auto=webp&s=8276b06547150b02dc12dc6dd1a03a55cf1b6a20

https://preview.redd.it/j5w0orovkweh1.png?width=1200&format=png&auto=webp&s=a7bb91bc1dd872f91e7dba5946c983c83975c551

https://preview.redd.it/3hqn1m7xkweh1.png?width=640&format=png&auto=webp&s=dd4878a565341cb2922f7cecf59af8581b70d5a6

https://preview.redd.it/e5x1v8d2lweh1.png?width=518&format=png&auto=webp&s=9e233189a757681434e28d4e7aad07b15a2d9d74

https://preview.redd.it/1o9mk384lweh1.png?width=1080&format=png&auto=webp&s=e05280f25cf357d8c24b374e49f16f13fe0547b6

https://preview.redd.it/py1x78wclweh1.png?width=1920&format=png&auto=webp&s=1493eefed503273f4ec5e797f9892dab0d816a97

https://preview.redd.it/eoyyazgdlweh1.png?width=1920&format=png&auto=webp&s=8f30b0334d85c94a855949bd906ec5f6b2ac6af2

', 'HenriqueGAYMER', 1784779416, '/r/MoviesThatFeelLike/comments/1v42xci/need_something_like_these_movies/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v42xci/need_something_like_these_movies/', 'MoviesThatFeelLike', 'A request for recommendations similar to a set of films referenced via images, conveying a desire to capture the same atmosphere or style.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (789, '1v4318u', 'Need something like these movies', 'Need something like these movies', '', 'HenriqueGAYMER', 1784779738, '/r/MoviesThatFeelLike/comments/1v4318u/need_something_like_these_movies/', 'https://www.reddit.com/gallery/1v4318u', 'MoviesThatFeelLike', 'Offbeat and awkward, with a raw DIY energy and an undercurrent of dread.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (790, '1v47ypl', 'movies with this vibe', 'movies with this vibe', '', 'FUCKTHEWORLD1990', 1784795790, '/r/MoviesThatFeelLike/comments/1v47ypl/movies_with_this_vibe/', 'https://www.reddit.com/gallery/1v47ypl', 'MoviesThatFeelLike', 'A wistful request for films that evoke a nostalgic, gritty, small-town American atmosphere with a strong sense of place and raw coming-of-age energy.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (791, '1v487ro', 'Movies/shows that feel like this?', 'Movies/shows that feel like this?', '', 'Ok-Sea-388', 1784796677, '/r/MoviesThatFeelLike/comments/1v487ro/moviesshows_that_feel_like_this/', 'https://i.redd.it/m5wgkh9t0yeh1.png', 'MoviesThatFeelLike', 'A neon-soaked, late-night urban mood searching for movies and shows with a tense, stylish atmosphere.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (792, '1v49fk3', 'Movies that feel like Cyberpunk 2077''s Badlands?', 'Movies that feel like Cyberpunk 2077''s Badlands', 'Futuristic wasteland, not apocalyptic wasteland like Mad Max.', 'the_ghost_1386', 1784800816, '/r/MoviesThatFeelLike/comments/1v49fk3/movies_that_feel_like_cyberpunk_2077s_badlands/', 'https://www.reddit.com/gallery/1v49fk3', 'MoviesThatFeelLike', 'A sun-scorched future wasteland where broken tech and desolate desert merge, evoking dystopian drift and outlaw survival.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (793, '1v49ua9', 'TV series like "mindmunster"', 'TV series like Mindhunter', '', 'Exact-Formal6956', 1784802089, '/r/MoviesThatFeelLike/comments/1v49ua9/tv_series_like_mindmunster/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v49ua9/tv_series_like_mindmunster/', 'MoviesThatFeelLike', 'Seeking shows like Mindhunter, with a tone of dark psychological intrigue and a bit of title confusion.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (794, '1v49v5t', 'English Movies That Feel Like This?', 'English Movies That Feel Like This?', '', 'regression-analysis', 1784802169, '/r/MoviesThatFeelLike/comments/1v49v5t/english_movies_that_feel_like_this/', 'https://i.redd.it/rceiwlc6hyeh1.jpeg', 'MoviesThatFeelLike', 'A user asks for English movies that capture a specific, undefined vibe.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (795, '1v4bljw', 'Odessy was amazing', 'Odyssey was amazing', '', 'Adept_Loquat5154', 1784807293, '/r/MoviesThatFeelLike/comments/1v4bljw/odessy_was_amazing/', 'https://www.reddit.com/gallery/1v4bkur', 'MoviesThatFeelLike', 'Awe for an odyssey, with a cryptic comment about the Bronze Age collapsing, evoking an epic and mythic mood.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (796, '1v4fvbg', 'Dark Fantasy Nightmares', 'Dark Fantasy Nightmares', 'Big fantasy lover, open to suggestions. Tried to combine as much of the vibes I’m looking for as possible. I love the darker films like Sleepy Hollow and Crimson Peak, but also really enjoy more campy movies like Hocus Pocus and The Addams Family. Any films in this genre that gave you childhood trauma such as Return to Oz I would very much like to hear about. Not really looking for LOTR/epic battle type fantasy (as much as I love them) more wanting spooky, witchy etc if that makes sense lol', 'Sydnee_Guy', 1784817638, '/r/MoviesThatFeelLike/comments/1v4fvbg/dark_fantasy_nightmares/', 'https://www.reddit.com/gallery/1v4fvbg', 'MoviesThatFeelLike', 'A haunting blend of gothic darkness, campy spookiness, and childhood-trauma-level fantasy, craving witchy, eerie, and unsettling fairy-tale vibes.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (797, '1v4hp8c', 'A movie that feels like Steve universe', 'A movie that feels like Steven Universe', '', 'daddylongjohnsliver', 1784821652, '/r/MoviesThatFeelLike/comments/1v4hp8c/a_movie_that_feels_like_steve_universe/', 'https://www.reddit.com/gallery/1v4hp8c', 'MoviesThatFeelLike', 'A search for a whimsical, coming-of-age movie that captures the nostalgic, small-town magic of Steven Universe.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (798, '1v4ioxc', 'Bro i need this type', 'Movies Like This AI Scene', 'Ya that''s ai but can anyone suggest movies like this', 'AmanYadav19', 1784823704, '/r/MoviesThatFeelLike/comments/1v4ioxc/bro_i_need_this_type/', 'https://i.redd.it/sqb8k20590fh1.png', 'MoviesThatFeelLike', 'A chaotic AI-generated blockbuster mashup that users mock as ''slop'', while one suggests a similar cinematic spectacle.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (799, '1v4iu3x', '(Warning: Scary images) Movies/shows/games that feel like Shane Acker’s 9?', 'Movies/shows/games that feel like Shane Acker''s 9', '', 'TriggerHappyGremlin', 1784824010, '/r/MoviesThatFeelLike/comments/1v4iu3x/warning_scary_images_moviesshowsgames_that_feel/', 'https://www.reddit.com/gallery/1v4iu3x', 'MoviesThatFeelLike', 'Dark, eerie, and haunting—seeking media with the post-apocalyptic handmade-doll atmosphere of Shane Acker''s 9.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (800, '1v4lm01', 'Movies that feels like this', 'Movies that feels like this', '', 'Chillex95', 1784829868, '/r/MoviesThatFeelLike/comments/1v4lm01/movies_that_feels_like_this/', 'https://www.reddit.com/gallery/1v4lm01', 'MoviesThatFeelLike', 'High-stakes corporate greed and ruthless ambition in the financial world, with sharp suits and tense power plays.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (801, '1v4oa3q', 'IS there a movie like this?', 'Is there a movie like this?', 'So i''ve just watched the oddysey and while i loved how the movie felt and looked and sounded, i really disliked some of the casting and how Nolan cut out some of the good parts from the original, so i was wondering if anyone knows a movie thats basically like this tonally with a strong soundtrack visuals, and not so out of place casting like that, for example like a lord of the rings but more historically medieval and serious and less fantasy but still with the elements of fantasy, and just the visuals like dune or smth

(Btw i get this IS probably a shit explanation but i really dont know how else to formulate IT, Also in not asking if there''s a different adaptation of oddysey like this but just a movie set in the past thats liek what i asked)', 'General-Rice254', 1784835437, '/r/MoviesThatFeelLike/comments/1v4oa3q/is_there_a_movie_like_this/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v4oa3q/is_there_a_movie_like_this/', 'MoviesThatFeelLike', 'A desire for serious, visually stunning historical-epic cinema with fantasy undertones and a powerful soundtrack.', 'skipped', 'no usable images', NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (802, '1v4q5a9', 'Movies that feel like OldMoney/Murder mistery', 'Movies that feel like OldMoney/Murder mistery', '', 'S3XY_mis', 1784839468, '/r/MoviesThatFeelLike/comments/1v4q5a9/movies_that_feel_like_oldmoneymurder_mistery/', 'https://www.reddit.com/gallery/1v4q5a9', 'MoviesThatFeelLike', 'A search for elegant, old-money settings wrapped in murder mystery and noir suspense, with a stylish, glamorous, and dangerous atmosphere.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (803, '1v9y0ul', 'Movies that feel like this ?', 'Movies that feel like this', 'Preferably set in the early 20th century ', 'desperate_thang', 1785335784, '/r/MoviesThatFeelLike/comments/1v9y0ul/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1v9y0ul', 'MoviesThatFeelLike', 'A nostalgic, candlelit longing for early 20th-century English country estates, blending cozy romance with gothic mystery and pastoral melancholy.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (804, '1vadnwp', 'Movies that feel like Ghost World', 'Movies that feel like Ghost World', 'Where not a ton happens but it''s quirky and enjoyable', 'DapperLow6726', 1785370099, '/r/MoviesThatFeelLike/comments/1vadnwp/movies_that_feel_like_ghost_world/', 'https://www.reddit.com/gallery/1vadnwp', 'MoviesThatFeelLike', 'Quirky and enjoyable with no major plot, just offbeat everyday moments.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (805, '1vaf0b0', 'Movies with the most stylized and experimental editing', 'Movies with the most stylized and experimental editing', '', 'LeonardoKlotzTomaz', 1785373661, '/r/MoviesThatFeelLike/comments/1vaf0b0/movies_with_the_most_stylized_and_experimental/', 'https://www.reddit.com/gallery/1vaf0b0', 'MoviesThatFeelLike', 'A celebration of jaw-dropping, rule-breaking editing and vivid visual experimentation.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (806, '1vai5gt', 'Movies where the slasher becomes the protagonist? (this is the only one I can think of)', 'Movies where the slasher becomes the protagonist?', '', 'beemaister', 1785382323, '/r/MoviesThatFeelLike/comments/1vai5gt/movies_where_the_slasher_becomes_the_protagonist/', 'https://i.redd.it/9fcq8ll1eagh1.png', 'MoviesThatFeelLike', 'A craving for horror movies that flip the script and make the killer the unlikely center of the story, pulling viewers into a slasher''s perspective.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (807, '1val2t4', 'The Conversation (1974)', 'The Conversation', '', 'cineswipe', 1785391314, '/r/MoviesThatFeelLike/comments/1val2t4/the_conversation_1974/', 'https://i.redd.it/stjv19ug4bgh1.png', 'MoviesThatFeelLike', 'A tense, paranoid atmosphere of surveillance and isolation.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (808, '1valkg2', 'Films that feel like this?', 'Films that feel like this?', '', 'Effective_Story_516', 1785392879, '/r/MoviesThatFeelLike/comments/1valkg2/films_that_feel_like_this/', 'https://i.redd.it/1bjbworn9bgh1.jpeg', 'MoviesThatFeelLike', 'A request for films that evoke a specific but unstated mood or atmosphere.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (809, '1vam2xx', 'Pretty obscure, I know.', 'Pretty obscure, I know.', 'Im just lost for ideas. Like, I cant think of anything that fits the vibe? 

Thank god I havent seen 37 other posts this week like this. ', 'tom_friday_', 1785394627, '/r/MoviesThatFeelLike/comments/1vam2xx/pretty_obscure_i_know/', 'https://www.reddit.com/gallery/1vam2xx', 'MoviesThatFeelLike', 'A cheeky, self-aware request for Twin Peaks-like media, joking about how repetitive these ''obscure'' asks have become.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (810, '1van0h4', 'Movies that feel like this?', 'Movies that feel like this?', '', 'Ractzkindness', 1785397807, '/r/MoviesThatFeelLike/comments/1van0h4/movies_that_feel_like_this/', 'https://i.redd.it/dcwr3sqbobgh1.jpeg', 'MoviesThatFeelLike', 'An eerie, dread-laden mood of isolation and psychological horror, with remote settings and a creeping sense that something is watching or about to go wrong.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (811, '1van2i2', 'Which movie would you watch here?', 'Which movie would you watch here?', '', 'Sev7nGGGGGG', 1785398006, '/r/MoviesThatFeelLike/comments/1van2i2/which_movie_would_you_watch_here/', 'https://i.redd.it/1dgdiu5xobgh1.jpeg', 'MoviesThatFeelLike', 'A dim, analog-horror living room lit by an old TV, where the atmosphere begs for unsettling, supernatural, and VHS-era movie picks.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (812, '1vapiwy', 'Movies where weird unexplainable things keep happening that leaves you thinking “wtf did I just watch?”', 'Movies where weird unexplainable things keep happening that leaves you thinking wtf did I just watch?', '', 'One-Future2932', 1785406436, '/r/MoviesThatFeelLike/comments/1vapiwy/movies_where_weird_unexplainable_things_keep/', 'https://www.reddit.com/gallery/1vapiwy', 'MoviesThatFeelLike', 'Delightfully unsettled craving for surreal, unpredictable films that leave you muttering ''wtf did I just watch?''', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (813, '1vapy4i', 'My Favorite Movie Genre 🤌🏼✨️', 'My Favorite Movie Genre', '', 'OrganizationSome8016', 1785407810, '/r/MoviesThatFeelLike/comments/1vapy4i/my_favorite_movie_genre/', 'https://i.redd.it/x0d6g7j0gbgh1.jpeg', 'MoviesThatFeelLike', 'An enthusiastic celebration of a favorite movie genre, with playful comments referencing Jason Bourne.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (814, '1varvwq', 'movie that feel like this ?', 'Movies that feel like this?', '', 'Necessary-Light-3704', 1785413547, '/r/MoviesThatFeelLike/comments/1varvwq/movie_that_feel_like_this/', 'https://www.reddit.com/gallery/1varvwq', 'MoviesThatFeelLike', 'A bleak, industrial, post-apocalyptic mood of damp concrete, desolation, and quiet dread.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (815, '1vary4y', 'What is your favorite Anime?', 'What is your favorite Anime?', 'Just One?!', 'Character-Bat-7397', 1785413713, '/r/MoviesThatFeelLike/comments/1vary4y/what_is_your_favorite_anime/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vary4y/what_is_your_favorite_anime/', 'MoviesThatFeelLike', 'A nostalgic fan-favorites thread full of cherished anime classics and personal picks.', 'skipped', 'no usable images', NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (816, '1vass0b', 'The grainy quality/low bitrate makes it scarier', 'The grainy quality low bitrate makes it scarier', 'First image: Possible Fallen Angel in Catalonia (YT video)

Second image: M. Night Shamalyan''s Signs', 'punishedscootedburb', 1785415866, '/r/MoviesThatFeelLike/comments/1vass0b/the_grainy_qualitylow_bitrate_makes_it_scarier/', 'https://www.reddit.com/gallery/1vass0b', 'MoviesThatFeelLike', 'The grainy, low-bitrate aesthetic makes the horror feel more unsettling and real, evoking a creeping dread that lingers in the static.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (817, '1vat72p', 'Pirates and Magic', 'Pirates and Magic', 'ANY movie or tv show (animated is ok too) that isn’t Pirates of the Caribbean thanks!', 'Due_Distribution_485', 1785416916, '/r/MoviesThatFeelLike/comments/1vat72p/pirates_and_magic/', 'https://www.reddit.com/gallery/1vat72p', 'MoviesThatFeelLike', 'Swashbuckling fantasy adventures where magic, ghostly pirates, and treasure-filled seas collide.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (818, '1vat7vd', 'Movies that feel like Scarface', 'Movies that feel like Scarface', '', 'girlysxxface', 1785416970, '/r/MoviesThatFeelLike/comments/1vat7vd/movies_that_feel_like_scarface/', 'https://www.reddit.com/gallery/1vat7vd', 'MoviesThatFeelLike', 'Craving flashy, over-the-top crime dramas about rise and fall.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (819, '1vatkrj', 'Movies set in far future rusted industrial slumscapes?', 'Movies set in far future rusted industrial slumscapes?', 'Ones that already come to mind - Alien 3, Blade Runner, Cube (1997)… maybe Dune and obviously some moments in Star Wars', 'TrashBloke1796', 1785417860, '/r/MoviesThatFeelLike/comments/1vatkrj/movies_set_in_far_future_rusted_industrial/', 'https://www.reddit.com/gallery/1vatkrj', 'MoviesThatFeelLike', 'A bleak, grimy future of rusted industrial decay, oppressive machinery, and dystopian slums.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (820, '1vaty5g', 'Space movies that feel like interstellar', 'Space movies that feel like interstellar', '', 'girlyxvibez', 1785418762, '/r/MoviesThatFeelLike/comments/1vaty5g/space_movies_that_feel_like_interstellar/', 'https://www.reddit.com/gallery/1vaty5g', 'MoviesThatFeelLike', 'A passionate hunt for space movies that capture the awe, isolation, and emotional stakes of Interstellar, with debates about philosophical depth and cinematic pacing.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (821, '1vaua91', 'Movies that gives those haunted castle, secret forest, murder mystery and in general horror vibe', 'Movies that give those haunted castle, secret forest, murder mystery, and in general horror vibe', '', 'S3XY_mis', 1785419573, '/r/MoviesThatFeelLike/comments/1vaua91/movies_that_gives_those_haunted_castle_secret/', 'https://www.reddit.com/gallery/1vaua91', 'MoviesThatFeelLike', 'Gothic horror atmosphere of haunted castles, secret forests, and murder mystery dread.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (822, '1vaxham', 'What movies feel like this :)', 'What movies feel like this', '', 'applegoes4awalk', 1785426691, '/r/MoviesThatFeelLike/comments/1vaxham/what_movies_feel_like_this/', 'https://www.reddit.com/gallery/1vaxham', 'MoviesThatFeelLike', 'Sun-drenched, fuzzy teenage nostalgia with coastal summer-day warmth and a free-spirited beach-town yearning.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (823, '1vay030', 'What''s the most mind-blowing plot twist you''ve seen in a movie?', 'What''s the most mind-blowing plot twist you''ve seen in a movie?', '', 'No_Letterhead3697', 1785427786, '/r/MoviesThatFeelLike/comments/1vay030/whats_the_most_mindblowing_plot_twist_youve_seen/', 'https://i.redd.it/pmk1dotg5egh1.png', 'MoviesThatFeelLike', 'A collective love for jaw-dropping, mind-bending plot twists and the visceral shock of a reveal.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (824, '1vb0bj2', 'i dream about this alot', 'I Dream About This a Lot', 'PLEASE', 'jayversay', 1785432716, '/r/MoviesThatFeelLike/comments/1vb0bj2/i_dream_about_this_alot/', 'https://www.reddit.com/gallery/1vb0bj2', 'MoviesThatFeelLike', 'A wistful, dreamy longing for a romantic European escape filled with charming streets, delicious food, and cozy holiday warmth.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (825, '1vb0zfl', 'Movies that feel like this', 'Movies that feel like this', '', 'dark90smagic', 1785434120, '/r/MoviesThatFeelLike/comments/1vb0zfl/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vb0zfl', 'MoviesThatFeelLike', 'Gloomy, gothic-cartoon otherworldliness with twisted Tim Burton-esque cityscapes, 90s dark animation nostalgia, and a whimsically eerie atmosphere.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (826, '1vb4bq1', 'What movie would you watch in a room like this?', 'What movie would you watch in a room like this', 'Also, just realized I took this picture exactly 5 years ago to this day', 'SpaceTranquil', 1785441305, '/r/MoviesThatFeelLike/comments/1vb4bq1/what_movie_would_you_watch_in_a_room_like_this/', 'https://i.redd.it/0rx1hszk9fgh1.jpeg', 'MoviesThatFeelLike', 'A nostalgic and slightly eerie vibe, as if the room sits at the crossroads of 80s horror and 2000s cult cinema.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (827, '1vb4c49', 'What movies give these vibes (coming of age)', 'What movies give these vibes (coming of age)', '', 'applegoes4awalk', 1785441331, '/r/MoviesThatFeelLike/comments/1vb4c49/what_movies_give_these_vibes_coming_of_age/', 'https://www.reddit.com/gallery/1vb4c49', 'MoviesThatFeelLike', 'A nostalgic, messy, and heartfelt coming-of-age mood with a mix of awkward teenage parties, friendship, and self-discovery.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (828, '1vb5hzx', 'Looking for more movies with this exact vibe. What would you add?', 'Looking for more movies with this exact vibe. What would you add?', '', 'Few-Juggernaut-1240', 1785443824, '/r/MoviesThatFeelLike/comments/1vb5hzx/looking_for_more_movies_with_this_exact_vibe_what/', 'https://i.redd.it/cq5hs1i3hfgh1.jpeg', 'MoviesThatFeelLike', 'A craving for more movies that match an exact, elusive vibe.', 'skipped', 'no enriched recommendation matches', NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (829, '1vb617n', 'Movies that won''t make me sad at any point', 'Movies that won''t make me sad at any point', '', 'Cats_and_Candy', 1785445008, '/r/MoviesThatFeelLike/comments/1vb617n/movies_that_wont_make_me_sad_at_any_point/', 'https://www.reddit.com/gallery/1vb617n', 'MoviesThatFeelLike', 'Cozy, warm, and gentle—a supportive thread of users seeking comfort films and sharing wholesome, feel-good TV to avoid sadness.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (830, '1vb72tz', 'Bei film psichedelici da vedere?', 'Bei film psichedelici da vedere?', '[removed]', 'Previous-Vehicle-556', 1785447388, '/r/MoviesThatFeelLike/comments/1vb72tz/bei_film_psichedelici_da_vedere/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vb72tz/bei_film_psichedelici_da_vedere/', 'MoviesThatFeelLike', 'A curious and open-minded search for psychedelic films.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (831, '1vb8ot4', 'New York City', 'New York City', 'I know a million movies are set in NYC but we’re going there for the first time and total tourists and want movies to set the vibe. My family has suggested Home Alone 2 and Eloise. Our trip will be at Christmas but any time of year movie works. ', 'Ok_Conversation_9336', 1785451197, '/r/MoviesThatFeelLike/comments/1vb8ot4/new_york_city/', 'https://www.reddit.com/gallery/1vb8ot4', 'MoviesThatFeelLike', 'A family planning a Christmas trip to New York City wants on-screen inspiration that blends holiday magic, landmark nostalgia, and gritty urban character.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (832, '1vb8xvg', 'Movies that feel like this', 'Movies that feel like this', '', 'Double_Concentrate_4', 1785451836, '/r/MoviesThatFeelLike/comments/1vb8xvg/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vb8xvg', 'MoviesThatFeelLike', 'A melancholic, heavy atmosphere, seeking films that capture existential despair and emotional bleakness.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (833, '1vb9ndg', 'Movies that feel like this?', 'Movies that feel like this?', '', 'No-Guitar728', 1785453603, '/r/MoviesThatFeelLike/comments/1vb9ndg/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vb9ndg', 'MoviesThatFeelLike', 'A cold, oppressive atmosphere of isolated forests and misty frontiers where soldiers and hunters are stalked by feral, folkloric creatures.', 'publishable', NULL, NULL, '2026-07-31 03:33:23', '2026-07-31 03:33:23');
