-- 0056_seed_20260803T143149Z_01_posts.sql: data seed from pipeline:load run.
-- Generated:  2026-08-03T14:31:56.469905+00:00
-- Run started: 2026-08-03T14:31:49.356343+00:00
-- Source: data/working/load manifest from this run.
--
-- Idempotent: every INSERT is INSERT OR IGNORE, keyed by the
-- table's natural unique constraint.  Wrangler's migration
-- tracking normally prevents re-apply; the OR IGNORE is
-- defense in depth for partial / interrupted re-runs.
--
-- Chunk: 01_posts (1/5)
-- Tables: imported_vibe_posts.
-- Pipeline-state tables (processing_runs, pipeline_artifacts)
-- are intentionally excluded — they're per-run bookkeeping.

INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (834, '1vbbswc', 'Movies that feel like the song “The Morning” by The Weeknd', 'Movies that feel like the song “The Morning” by The Weeknd', '', 'Sad_Loan31', 1785459159, '/r/MoviesThatFeelLike/comments/1vbbswc/movies_that_feel_like_the_song_the_morning_by_the/', 'https://i.redd.it/t0ggnshrqggh1.jpeg', 'MoviesThatFeelLike', 'A melancholic, hedonistic morning-after haze.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (835, '1vbbxi1', 'Movies that feel like Earthbound (SNES)', '', 'Making my way through my first full playthrough and besides the fact that I need a walkthrough, this is far and away my favourite video game of all time. It has so much personality and offbeat humour while also delving into incredibly dark and mature concepts. I’ve never really experienced much else like it outside of David Lynch’s filmography.', 'ShiftlessBridgrKid', 1785459502, '/r/MoviesThatFeelLike/comments/1vbbxi1/movies_that_feel_like_earthbound_snes/', 'https://www.reddit.com/gallery/1vbbxi1', 'MoviesThatFeelLike', 'Offbeat humor meets dark, mature surrealism.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (836, '1vbbz1k', 'Movies that feel like Earthbound (SNES)', 'Movies that feel like Earthbound', 'Making my way through my first full playthrough and besides the fact that I need a walkthrough, this is far and away my favourite video game of all time. It has so much personality and offbeat humour while also delving into incredibly dark and mature concepts. I’ve never really experienced much else like it outside of David Lynch’s filmography.', 'ShiftlessBridgrKid', 1785459618, '/r/MoviesThatFeelLike/comments/1vbbz1k/movies_that_feel_like_earthbound_snes/', 'https://www.reddit.com/gallery/1vbbz1k', 'MoviesThatFeelLike', 'Quirky offbeat childhood adventure with dark surreal humor.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (837, '1vbf9vn', 'Movies that feel like driving through West Virginia with "Take Me Home, Country Roads" playing?', 'Movies that feel like driving through West Virginia with "Take Me Home, Country Roads" playing?', 'I''m looking for movies that capture that peaceful, nostalgic country feeling. Rolling hills, small towns, winding roads, forests, old diners, sunsets, bluegrass or folk music something that feels like home, even if you''ve never been there. ', 'Limp_Context_4598', 1785468638, '/r/MoviesThatFeelLike/comments/1vbf9vn/movies_that_feel_like_driving_through_west/', 'https://www.reddit.com/gallery/1vbf9vn', 'MoviesThatFeelLike', 'Peaceful, nostalgic country road trip through rolling hills and small towns.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (838, '1vbfjmc', 'Movies that feel like', '', 'Didn''t sleep last night so now I just gotta watch something, could be any genre but I want the vibe. A movie I won''t forget.', 'Movie_LoVeR7', 1785469426, '/r/MoviesThatFeelLike/comments/1vbfjmc/movies_that_feel_like/', 'https://v.redd.it/cwln6ifalhgh1', 'MoviesThatFeelLike', 'Haunting, contemplative, and unforgettable atmospheric journey.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (839, '1vbg0we', 'Movies about individuals developing / living their inner lives', 'Movies about individuals developing / living their inner lives', 'Where people grow into who they are and want to be. Developing away from group shared values and pursuing the things they individually deem of value.
  
Amelia and Spirited Away are it for me. Highly introspective characters with richer inner lives. Amelia you know due to the narrator what and why she does things. While Chihiro you need to infer but she also considers things as the person she is instead of some grand society value.', 'Ambitious_Pudding177', 1785470776, '/r/MoviesThatFeelLike/comments/1vbg0we/movies_about_individuals_developing_living_their/', 'https://www.reddit.com/gallery/1vbg0we', 'MoviesThatFeelLike', 'Quietly introspective films about personal growth and inner life.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (840, '1vbg3gy', 'How many characters can you recognise here?', '', '', 'Omni_Chroma', 1785470978, '/r/MoviesThatFeelLike/comments/1vbg3gy/how_many_characters_can_you_recognise_here/', 'https://v.redd.it/iinw1h9wphgh1', 'MoviesThatFeelLike', 'Nostalgic chaos of iconic film characters.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (841, '1vbgudm', 'Whoever wants movie suggestions according to their preferred genre, leave a comment.', '', '[removed]', 'Suspicious-Vast5736', 1785473226, '/r/MoviesThatFeelLike/comments/1vbgudm/whoever_wants_movie_suggestions_according_to/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vbgudm/whoever_wants_movie_suggestions_according_to/', 'MoviesThatFeelLike', '', 'skipped', 'no usable images; no vibe summary; no enriched recommendation matches', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (842, '1vbi0zn', 'Movie suggestion', 'Movie suggestion', 'I''m looking for movies centered around friends or a couple going on a trip or road trip. I want something wholesome, funny, feel-good, and emotional at the same time—beautiful scenery, great chemistry between the characters, memorable conversations, and a journey that changes them by the end.', 'ishitaa07', 1785476829, '/r/MoviesThatFeelLike/comments/1vbi0zn/movie_suggestion/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vbi0zn/movie_suggestion/', 'MoviesThatFeelLike', 'Wholesome and funny road trip journeys with emotional depth and beautiful landscapes.', 'skipped', 'no usable images', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (843, '1vbiaew', 'Movies that feel like this Cannibal Corpse music video.', '', '', 'Aggravating-Web-3707', 1785477639, '/r/MoviesThatFeelLike/comments/1vbiaew/movies_that_feel_like_this_cannibal_corpse_music/', 'https://v.redd.it/l4okfhap9igh1', 'MoviesThatFeelLike', 'Brutal and grotesque death metal horror.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (844, '1vbkdfj', 'Movies that Feel Like Meditative, Slow-Motion Drift Through the Sublime', '', 'I''ve recently rewatched *2001: A Space Odyssey* and its lesser-known sequel, *2010: The Year We Make Contact*. They are great films. I especially enjoyed those meditative, slow-motion drifts through the void of deep space. The stunning images of planets and spaceships felt incredibly immersive, like floating through the Solar System. It was sublime!  
Are there other films with that specific feel? I''m not focused on narrative, but rather slow, hyper-polished visuals with an intense sense of awe.  
It doesn''t strictly have to be deep space. I can see this style working with undersea or other alien (or not) environments.  
Please, **NO** ***Baraka***, ***Samsara***, ***Koyaanisqatsi***, etc. I''m not looking for frenetic editing, but long, continuous takes. Plus, I have already watched them.', 'TexturesOfEther', 1785484430, '/r/MoviesThatFeelLike/comments/1vbkdfj/movies_that_feel_like_meditative_slowmotion_drift/', 'https://www.reddit.com/gallery/1vbkdfj', 'MoviesThatFeelLike', 'Meditative, slow-motion drift through awe-inspiring cosmic vistas.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (845, '1vbkzz6', 'films like Moonrise Kingdom?', 'films like Moonrise Kingdom', '', 'ZookeepergameFun4201', 1785486562, '/r/MoviesThatFeelLike/comments/1vbkzz6/films_like_moonrise_kingdom/', '/r/criterion/comments/1vbkznh/films_like_moonrise_kingdom/', 'MoviesThatFeelLike', 'Whimsical, offbeat coming-of-age charm.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (846, '1vbml9z', 'Movies that feel like: rag tag teams, found family action/adventure', '', 'Films like: The Goonies, Guardians Of The Galaxy trilogy, Shaun Of The Dead, Black Friday, Dungeons & Dragons: Honor Amongst Thieves', 'welmanshirezeo', 1785492023, '/r/MoviesThatFeelLike/comments/1vbml9z/movies_that_feel_like_rag_tag_teams_found_family/', 'https://www.reddit.com/gallery/1vbml9z', 'MoviesThatFeelLike', 'Misfit groups form unlikely families through chaotic and humorous adventures.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (847, '1vbmuoc', 'Movies that feel like the tension is unbearable', 'Movies that feel like the tension is unbearable', 'Slow burn - where they barely touch. Where the tension is the point.', 'Zer0_T0nin', 1785492872, '/r/MoviesThatFeelLike/comments/1vbmuoc/movies_that_feel_like_the_tension_is_unbearable/', 'https://www.reddit.com/gallery/1vbmuoc', 'MoviesThatFeelLike', 'Unbearable romantic tension and aching longing in slow-burn films.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (848, '1vbseu7', 'Movies where money changes a person', 'Movies where money changes a person', '', 'CodGroundbreaking803', 1785507847, '/r/MoviesThatFeelLike/comments/1vbseu7/movies_where_money_changes_a_person/', 'https://www.reddit.com/gallery/1vbseu7', 'MoviesThatFeelLike', 'The corrupting allure of wealth twists souls and breaks bonds.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (849, '1vbsnuv', 'Films that feels like this please, a bit dreampop and watery, thank you!', 'Films that feels like this please, a bit dreampop and watery, thank you!', 'That type of nostalgia... half summer half dream. Don''t know if I expressed the feeling right enough ', 'Rainforest____', 1785508415, '/r/MoviesThatFeelLike/comments/1vbsnuv/films_that_feels_like_this_please_a_bit_dreampop/', 'https://www.reddit.com/gallery/1vbsnuv', 'MoviesThatFeelLike', 'Dreamy, watery nostalgia with a dreampop aesthetic, evoking half-summer half-dream sensations.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (850, '1vbt9d4', 'I need to do something so badly this rainy days so help me out🥀', 'I need to do something so badly this rainy days so help me out🥀', '[removed]', 'Inevitable-Pea9797', 1785509776, '/r/MoviesThatFeelLike/comments/1vbt9d4/i_need_to_do_something_so_badly_this_rainy_days/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vbt9d4/i_need_to_do_something_so_badly_this_rainy_days/', 'MoviesThatFeelLike', 'Restless rainy day melancholy', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (851, '1vbtnsw', 'I need to do something so badly this rainy days so help me out🥀', 'I need to do something so badly this rainy days so help me out🥀', '[removed]', 'Inevitable-Pea9797', 1785510641, '/r/MoviesThatFeelLike/comments/1vbtnsw/i_need_to_do_something_so_badly_this_rainy_days/', 'https://www.reddit.com/gallery/1vbtnsw', 'MoviesThatFeelLike', 'A restless longing for activity during melancholy rainy days.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (852, '1vbue5l', 'I need to do something so badly this rainy days so help me out🥀', 'I need to do something so badly this rainy days so help me out', '[removed]', 'Inevitable-Pea9797', 1785512245, '/r/MoviesThatFeelLike/comments/1vbue5l/i_need_to_do_something_so_badly_this_rainy_days/', 'https://www.reddit.com/gallery/1vbue5l', 'MoviesThatFeelLike', 'Restless longing on a rainy day', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (853, '1vbutxd', 'A quiet movie that brings this video to mind?', 'A quiet movie that brings this video to mind?', 'Something a bit like the story in the graphic novel "Snapdragon", this style I like to call "American urban supernatural"', 'Big-Tax-8921', 1785513191, '/r/MoviesThatFeelLike/comments/1vbutxd/a_quiet_movie_that_brings_this_video_to_mind/', 'https://v.redd.it/uno9rjux6lgh1', 'MoviesThatFeelLike', 'Quiet, introspective films with subtle supernatural elements set in American landscapes.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (854, '1vbvryz', 'I need to do something so badly this rainy days so help me out🥀', 'I need to do something so badly this rainy days so help me out', '', 'Purple-Check3284', 1785515201, '/r/MoviesThatFeelLike/comments/1vbvryz/i_need_to_do_something_so_badly_this_rainy_days/', 'https://www.reddit.com/gallery/1vbvrhg', 'MoviesThatFeelLike', 'Ethereal and magical rainy-day comfort.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (855, '1vbvyyd', 'Which of these is the best?', 'Which of these is the best?', '[deleted]', '[deleted]', 1785515620, '/r/MoviesThatFeelLike/comments/1vbvyyd/which_of_these_is_the_best/', '', 'MoviesThatFeelLike', 'No discernible atmosphere.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (856, '1vbw4jd', 'Favorite Love Movie of 2026💕', 'Favorite Love Movie of 2026', '[removed]', 'yeyu_yyy', 1785515966, '/r/MoviesThatFeelLike/comments/1vbw4jd/favorite_love_movie_of_2026/', 'https://i.redd.it/mkszjmrnflgh1.jpeg', 'MoviesThatFeelLike', 'Futuristic romantic nostalgia', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (857, '1vbwrlp', 'I miss when movies had strange creatures like this🥀', 'I miss when movies had strange creatures like this', 'I’m looking for movies or shows with really cool/weird creature designs that are actually handmade, like puppets, animatronics, creature suits, stop motion, etc.

I love the feeling of watching something where you can tell someone actually built the creature instead of it just being CGI. Stuff that feels kinda creepy, magical, or just really unique.

Some examples I like:

The Dark Crystal (1982) Where the Wild Things Are (2009) Labyrinth (1986) The NeverEnding Story (1984) Pan’s Labyrinth (2006)

I’m mostly looking for that old-school practical effects vibe, but I’m open to anything — fantasy, horror, sci-fi, weird kids movies, whatever.

Any recommendations for movies/shows with amazing creature designs?', 'Purple-Check3284', 1785517376, '/r/MoviesThatFeelLike/comments/1vbwrlp/i_miss_when_movies_had_strange_creatures_like_this/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vbwrlp/i_miss_when_movies_had_strange_creatures_like_this/', 'MoviesThatFeelLike', 'A nostalgic craving for handcrafted, weird, and creepy creature designs.', 'skipped', 'no usable images', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (858, '1vc1vaf', 'Movies that feels like this..', '', '', 'That_Firefly', 1785528661, '/r/MoviesThatFeelLike/comments/1vc1vaf/movies_that_feels_like_this/', 'https://www.reddit.com/gallery/1vc1vaf', 'MoviesThatFeelLike', 'A lone journey through nature’s vastness, blending introspection with awe-inspiring landscapes.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (859, '1vc2apz', 'Movies that are like this', '', '', 'Idek163', 1785529618, '/r/MoviesThatFeelLike/comments/1vc2apz/movies_that_are_like_this/', 'https://www.reddit.com/gallery/1vc2apz', 'MoviesThatFeelLike', 'A surreal, neon-drenched dreamscape blending youthful nostalgia, chaotic romance, and dark whimsy.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (860, '1vc39a6', 'Movies that feel like hitman: blood money?', '', 'Hitman (2007) doesn''t count because that would be too easy.', 'UnlikelyTwo7070', 1785531803, '/r/MoviesThatFeelLike/comments/1vc39a6/movies_that_feel_like_hitman_blood_money/', 'https://www.reddit.com/gallery/1vc39a6', 'MoviesThatFeelLike', 'Stylish hitman thriller with a tense, atmospheric, and occasionally sleazy vibe.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (861, '1vc5j32', 'Any like Absolution by Muse?', '', '', 'KnownAd5917', 1785537220, '/r/MoviesThatFeelLike/comments/1vc5j32/any_like_absolution_by_muse/', 'https://www.reddit.com/gallery/1vc5j32', 'MoviesThatFeelLike', 'Seeking dramatic, apocalyptic rock anthems akin to Muse''s Absolution.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (862, '1vc6an1', 'looking for a film similar to céline (1992) by Jean-claude Brisseau', '', 'Can you suggest me a film similar to céline (1992) by Jean-claude Brisseau . I loved the yoga and healing themes, and also how beautiful and calm the scenes looked overall.', 'amalll2310', 1785539093, '/r/MoviesThatFeelLike/comments/1vc6an1/looking_for_a_film_similar_to_céline_1992_by/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vc6an1/looking_for_a_film_similar_to_céline_1992_by/', 'MoviesThatFeelLike', 'Beautiful, calm atmosphere with healing and yoga themes.', 'skipped', 'no usable images', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (863, '1vc6ojr', 'Movies that feel Iike this?', 'Movies that feel like this?', '', 'Chillex95', 1785540048, '/r/MoviesThatFeelLike/comments/1vc6ojr/movies_that_feel_iike_this/', 'https://v.redd.it/gihq0a9afngh1', 'MoviesThatFeelLike', '80s NYC street atmosphere', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (864, '1vc6uc2', 'Movies that feel like this', 'Movies that feel like this', '', 'CaptainFreeSoil', 1785540462, '/r/MoviesThatFeelLike/comments/1vc6uc2/movies_that_feel_like_this/', 'https://i.redd.it/bq39zj7hgngh1.png', 'MoviesThatFeelLike', 'Surreal blend of bleak despair and whimsical absurdity.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (865, '1vc6zxj', 'Which movies made you cry? Made you all teary?', 'Which movies made you cry? Made you all teary?', '[deleted]', '[deleted]', 1785540864, '/r/MoviesThatFeelLike/comments/1vc6zxj/which_movies_made_you_cry_made_you_all_teary/', '', 'MoviesThatFeelLike', 'Searching for films that evoke tears.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (866, '1vca17d', 'Horror movies that feel like P.T.', 'Horror movies that feel like P.T.', '', 'AdventurousTie9845', 1785549007, '/r/MoviesThatFeelLike/comments/1vca17d/horror_movies_that_feel_like_pt/', 'https://i.redd.it/yu365sex5ogh1.jpeg', 'MoviesThatFeelLike', 'Oppressive psychological horror with looping dread and surreal, inescapable tension.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (867, '1vca2im', 'Horror movies that feel like P.T.', 'Horror movies that feel like P.T.', '', 'AdventurousTie9845', 1785549114, '/r/MoviesThatFeelLike/comments/1vca2im/horror_movies_that_feel_like_pt/', 'https://i.redd.it/mnikdlt86ogh1.jpeg', 'MoviesThatFeelLike', 'Claustrophobic, looping dread with psychological horror and an oppressive, silent atmosphere.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (868, '1vcapse', 'Movies that feel like nostalgia?', 'Movies that feel like nostalgia?', '', 'saloonofstardrops', 1785550956, '/r/MoviesThatFeelLike/comments/1vcapse/movies_that_feel_like_nostalgia/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vcapse/movies_that_feel_like_nostalgia/', 'MoviesThatFeelLike', 'A wistful longing for the simplicity and warmth of bygone days.', 'skipped', 'no usable images', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (869, '1vcb6hx', 'Monastic, hermetic, ascetic', 'Monastic, hermetic, ascetic', '', 'lalalatortuga', 1785552305, '/r/MoviesThatFeelLike/comments/1vcb6hx/monastic_hermetic_ascetic/', 'https://www.reddit.com/gallery/1vcb6hx', 'MoviesThatFeelLike', 'A contemplative and solitary atmosphere of monastic life, marked by religious devotion and ascetic simplicity.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (870, '1vcd0qq', 'Non-musical movies but music play a big part', '', 'Music doesn''t necessarily need to be the main focus.

1. Yesterday, Fantasy Romcom with Beatles music

2. Pitch Perfect, about college Acapella group

3. Gurdian of Galaxy vol 1, scifi space stuff with catchy 80s songs

I didn''t like Bohemian Rhapsody, Begin Again, A star is born and Sing (the animated movie) ', 'PowerfulAnxiety9729', 1785557648, '/r/MoviesThatFeelLike/comments/1vcd0qq/nonmusical_movies_but_music_play_a_big_part/', 'https://www.reddit.com/gallery/1vcd0qq', 'MoviesThatFeelLike', 'Movies that feel like a transcendent needledrop', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (871, '1vcdb9f', 'Movies with time-travel vibes', 'Movies with time-travel vibes', '', 'Ancient_Win_2837', 1785558517, '/r/MoviesThatFeelLike/comments/1vcdb9f/movies_with_timetravel_vibes/', 'https://www.reddit.com/gallery/1vcdb9f', 'MoviesThatFeelLike', 'Mind-bending temporal paradoxes and time-loop adventures.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (872, '1vcdgat', 'What are your top 10 movies that feel like found family?', '', 'Any genre, I just want movies that have that found family feeling.', 'Zer0_T0nin', 1785558954, '/r/MoviesThatFeelLike/comments/1vcdgat/what_are_your_top_10_movies_that_feel_like_found/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vcdgat/what_are_your_top_10_movies_that_feel_like_found/', 'MoviesThatFeelLike', 'Cozy gatherings and unwavering loyalty among misfits who become family.', 'skipped', 'no usable images', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (873, '1vcdyzs', 'Solarpunk punk types movie', 'Solarpunk movie recommendations', 'Tomorrow land is not.', 'AmanYadav19', 1785560542, '/r/MoviesThatFeelLike/comments/1vcdyzs/solarpunk_punk_types_movie/', 'https://www.reddit.com/gallery/1vcdyzs', 'MoviesThatFeelLike', 'Lush, high-tech eco-utopia blending nature and technology harmoniously.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (874, '1vcfvbo', 'Movies that are bleak or set in difficult circumstances but are optimistic at their core.', 'Movies that are bleak or set in difficult circumstances but are optimistic at their core.', '', 'Sea-Conclusion959', 1785566651, '/r/MoviesThatFeelLike/comments/1vcfvbo/movies_that_are_bleak_or_set_in_difficult/', 'https://www.reddit.com/gallery/1vcfvbo', 'MoviesThatFeelLike', 'A journey through bleak and difficult circumstances illuminated by an underlying optimism and enduring human spirit.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (875, '1vcgpca', 'Movies that feel like this apartment complex in Spain', 'Movies that feel like this apartment complex in Spain', '', 'Neat_Ostrich9966', 1785569421, '/r/MoviesThatFeelLike/comments/1vcgpca/movies_that_feel_like_this_apartment_complex_in/', 'https://i.redd.it/hmaxopgmupgh1.jpeg', 'MoviesThatFeelLike', 'A vibrant and surreal maze of geometric pastel architecture evoking a dreamlike Mediterranean atmosphere.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (876, '1vchzua', 'Movies that feel like something done by Mountain Dew while playing Xbox', 'Movies that feel like something done by Mountain Dew while playing Xbox', '', 'LeonardoKlotzTomaz', 1785573928, '/r/MoviesThatFeelLike/comments/1vchzua/movies_that_feel_like_something_done_by_mountain/', 'https://www.reddit.com/gallery/1vchzua', 'MoviesThatFeelLike', 'Hyper-caffeinated early 2000s action excess drenched in a grungy green tint.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (877, '1vcij6b', 'Movies about reclaiming your identity after spending your whole life living for others?', '', '', 'coveredisel', 1785575764, '/r/MoviesThatFeelLike/comments/1vcij6b/movies_about_reclaiming_your_identity_after/', '/r/MovieSuggestions/comments/1vciiuj/movies_about_reclaiming_your_identity_after/', 'MoviesThatFeelLike', 'Contemplative search for authenticity and self-reclamation.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (878, '1vcinr1', 'What’s a movie or video game you wish you could experience for the first time again?', 'What’s a movie or video game you wish you could experience for the first time again?', '', 'International-Mix101', 1785576224, '/r/MoviesThatFeelLike/comments/1vcinr1/whats_a_movie_or_video_game_you_wish_you_could/', '/r/AskReddit/comments/1vcii4n/whats_a_movie_or_video_game_you_wish_you_could/', 'MoviesThatFeelLike', 'Nostalgic longing for the magic of a first viewing or playthrough.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (879, '1vck3kx', 'Can you suggest me movies, that feel like this', 'Can you suggest me movies, that feel like this', 'This movie feels like home.', 'Opening_Line1330', 1785581193, '/r/MoviesThatFeelLike/comments/1vck3kx/can_you_suggest_me_movies_that_feel_like_this/', 'https://i.redd.it/9ow5v3mmtqgh1.jpeg', 'MoviesThatFeelLike', 'Warm, nostalgic coming-of-age movies that feel like home.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (880, '1vconer', 'Pre-2000s Films Like This Set Design From ‘Spray Of The Days’ (1968)?', '', 'Love the colourful, kinda surreal and absurd set design of this room in Spray Of The Days. It’s like something pulled out of a weird dream and I love it. 

Any ideas? Language doesn’t matter. My only preference is it being pre-2000s and in colour.

Thank you!', 'isopodsoup_', 1785593950, '/r/MoviesThatFeelLike/comments/1vconer/pre2000s_films_like_this_set_design_from_spray_of/', 'https://www.reddit.com/gallery/1vconer', 'MoviesThatFeelLike', 'A vibrant, surreal dreamscape of colorful 60s sci-fi and fantasy set designs.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (881, '1vcrn4s', 'Movies and documentaries regarding workshops, architecture, and or inventions', 'Movies and documentaries regarding workshops, architecture, and or inventions', '[deleted]', '[deleted]', 1785601315, '/r/MoviesThatFeelLike/comments/1vcrn4s/movies_and_documentaries_regarding_workshops/', '', 'MoviesThatFeelLike', 'Curious and inventive spirit seeking workshop, architecture, and invention content.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (882, '1vcrsvz', 'Movies and documentary films regarding workshops, architecture, and or inventions', 'Movies and documentary films regarding workshops, architecture, and or inventions', '', 'Radiant-Boat-5149', 1785601703, '/r/MoviesThatFeelLike/comments/1vcrsvz/movies_and_documentary_films_regarding_workshops/', 'https://www.reddit.com/gallery/1vcrsvz', 'MoviesThatFeelLike', 'A sense of wonder in the act of creation, from intricate workshops to grand architectural designs, fueled by the thrill of invention.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (883, '1vcs2ik', 'Looking for movies with a Black Metal atmosphere (not about Black Metal)', '', 'I’m looking for films that capture the **atmosphere** of black metal—not movies about metal bands.  
Cold, bleak, atmospheric: forests, mountains, snow, fog, solitude, pagan/folk elements, dark spirituality, and that haunting, melancholic feeling.  
Genre doesn’t matter (horror, drama, arthouse, fantasy, etc.) as long as it feels like the music of bands such as Gorgoroth, Burzum, Drudkh, or Paysage d’Hiver.  
Any recommendations?', 'Longjumping-Drop9230', 1785602356, '/r/MoviesThatFeelLike/comments/1vcs2ik/looking_for_movies_with_a_black_metal_atmosphere/', 'https://www.reddit.com/gallery/1vcs2ik', 'MoviesThatFeelLike', 'Cold, bleak, and hauntingly atmospheric with pagan and folk elements, evoking solitude and dark spirituality.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (884, '1vcuskf', 'Spy, conspiracy or mystery stories set in Russia or the Soviet Union', 'Spy, conspiracy or mystery stories set in Russia or the Soviet Union', 'I’m looking for movies or TV shows about espionage, conspiracies, political intrigue or mysteries that are actually set in Russia or the Soviet Union (not just Cold War stories that happen elsewhere)

I’ve already watched these movies and shows:

The Americans (2013–2018)  
The Russia House (1990)  
Gorky Park (1983)  
Chernobyl (2019)  
Tinker Tailor Soldier Spy (2011)  
Bridge of Spies (2015)  
No Way Out (1987)  
Atomic Blonde (2017)  
The Death of Stalin (2018)', 'Ordinary-Gal', 1785608880, '/r/MoviesThatFeelLike/comments/1vcuskf/spy_conspiracy_or_mystery_stories_set_in_russia/', 'https://www.reddit.com/gallery/1vcuskf', 'MoviesThatFeelLike', 'Paranoid Cold War intrigue with Soviet secrets and spy games.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (885, '1vcut48', 'Bagdad Cafe', 'Bagdad Cafe', '[removed]', 'adminsaremeanb', 1785608914, '/r/MoviesThatFeelLike/comments/1vcut48/bagdad_cafe/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vcut48/bagdad_cafe/', 'MoviesThatFeelLike', 'Quirky desert roadside cafe charm', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (886, '1vcvy9m', 'Movies that feel like this?', 'Movies that feel like this?', 'Borrowing from books that feel this again! I’m excited for what you guys have for me', 'GreenChiliGronk', 1785611628, '/r/MoviesThatFeelLike/comments/1vcvy9m/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vcqvta', 'MoviesThatFeelLike', 'Literary yearning for an undefined feeling', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (887, '1vcw4mx', 'Movies that feel like this?', 'Movies that feel like this?', 'Borrowing from books again! I’m excited for what you guys have for this one', 'GreenChiliGronk', 1785612043, '/r/MoviesThatFeelLike/comments/1vcw4mx/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vcqvta', 'MoviesThatFeelLike', 'A dark, neon-lit aesthetic blending cyberpunk, gothic, and stylized action.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (888, '1vcw8ax', 'Des livres qui ressemblent à ça ?', 'Des livres qui ressemblent à ça ?', '', 'Melimel49', 1785612284, '/r/MoviesThatFeelLike/comments/1vcw8ax/des_livres_qui_ressemblent_à_ça/', 'https://i.redd.it/o4qxjcl9xsgh1.jpeg', 'MoviesThatFeelLike', 'Quest for visually evocative literature', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (889, '1vcw9cm', 'Movies that feel like this?', '', '', 'Melimel49', 1785612356, '/r/MoviesThatFeelLike/comments/1vcw9cm/movies_that_feel_like_this/', 'https://i.redd.it/o4qxjcl9xsgh1.jpeg', 'MoviesThatFeelLike', 'Eerie nautical horror with psychological dread.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (890, '1vcwgfi', 'Movies that feel like this?', 'Movies that feel like this?', 'The more magical the better. I recently watched “Never Ending Story” & “Mad God”   
That’s generally the feel I’m after. Embellished with weird and wonderful imaginings.', 'OkScarcity926', 1785612823, '/r/MoviesThatFeelLike/comments/1vcwgfi/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vcwgfi', 'MoviesThatFeelLike', 'magical, surreal, and dreamlike wonder', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (891, '1vcy57r', 'The dangerous game hunt', '', 'I''d like to ask you to suggest the movies which feature hunting big and dangerous game hunt as a significant part of the plot. I''ve been reading Jim Corbett and J.A.Hunter, Grigory Fedoseev and other writers on the topic. Preferably something about pre-1960s era.

The gloomy poster is a GDR poster for "Evil Spirit of Mt. Yambui", the adaptation of Fedoseev''s account on encountering the maneating bear in the Russian Far East and hunting it with the Evenk natives.', 'Adorable-Bend7362', 1785616856, '/r/MoviesThatFeelLike/comments/1vcy57r/the_dangerous_game_hunt/', 'https://www.reddit.com/gallery/1vcy57r', 'MoviesThatFeelLike', 'Tense pursuit of deadly beasts in rugged wilderness.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (892, '1vczrr1', 'Movie or tv series with hive city feel…', 'Movie or tv series with hive city feel', '', 'Airport_potato89', 1785620869, '/r/MoviesThatFeelLike/comments/1vczrr1/movie_or_tv_series_with_hive_city_feel/', 'https://www.reddit.com/gallery/1vczrr1', 'MoviesThatFeelLike', 'A dense, claustrophobic urban sprawl where towering cities oppressively cluster with industrial decay.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (893, '1vd0ya1', 'Need a movie that FEELS like Gia. Not with like the same premise or anything. Just the same vibe', 'Need a movie that FEELS like Gia. Not with like the same premise or anything. Just the same vibe', '', 'Admirable_Link1736', 1785623925, '/r/MoviesThatFeelLike/comments/1vd0ya1/need_a_movie_that_feels_like_gia_not_with_like/', 'https://i.redd.it/qkqifa1pcugh1.jpeg', 'MoviesThatFeelLike', 'A raw, melancholic, and gritty atmosphere similar to the movie ''Gia''.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (894, '1vd25y7', 'Movies that feel like this?', '', '', 'Cultofluke', 1785627177, '/r/MoviesThatFeelLike/comments/1vd25y7/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vd25y7', 'MoviesThatFeelLike', 'Nostalgic suburban teen angst with a blend of dark humor and coming-of-age drama.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (895, '1vd2ass', 'Movies that feel like this (preferably not crime)', 'Movies that feel like this (preferably not crime)', '', 'BenfordAbrahams', 1785627553, '/r/MoviesThatFeelLike/comments/1vd2ass/movies_that_feel_like_this_preferably_not_crime/', 'https://www.reddit.com/gallery/1vd2ass', 'MoviesThatFeelLike', 'Gritty 90s urban atmosphere with graffiti-covered streets, skate culture, and neon lights.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (896, '1vd6l1p', 'Road trip movie vibes?', 'Road trip movie vibes?', '', 'Kbudz', 1785639867, '/r/MoviesThatFeelLike/comments/1vd6l1p/road_trip_movie_vibes/', 'https://www.reddit.com/gallery/1vd6l1p', 'MoviesThatFeelLike', 'A yearning for the open road and the freedom of a long drive, capturing the spirit of adventure and self-discovery.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (897, '1vd9lkf', 'Movies like these movies', 'Movies like these movies', '', 'Idek163', 1785649225, '/r/MoviesThatFeelLike/comments/1vd9lkf/movies_like_these_movies/', 'https://www.reddit.com/gallery/1vd9lkf', 'MoviesThatFeelLike', 'Bleak and psychologically intense', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (898, '1vd9rye', 'Movies that feel like this', 'Movies that feel like this', '', 'Key_Finding4586', 1785649797, '/r/MoviesThatFeelLike/comments/1vd9rye/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vd9rye', 'MoviesThatFeelLike', 'Gritty desert highways, neon-lit diners, and leather-clad rebels collide in a dust-choked, wild Americana fever dream.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (899, '1vdckiu', 'Movies that feel like…', 'Movies that feel like…', 'Dark Beach : Pastel Ghost, Go (1999), Last Night In Soho,Evil Dead II , and Donnie Darko

Ignore the guy on the fifth slide, he just seemed to belong there.', 'Scabalor10', 1785659341, '/r/MoviesThatFeelLike/comments/1vdckiu/movies_that_feel_like/', 'https://www.reddit.com/gallery/1vdckiu', 'MoviesThatFeelLike', 'A hazy, retro-tinged descent into neon-noir unease.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (900, '1vdd0vz', 'What''s a movie with stunning mountain views and a peaceful vibe?', 'What''s a movie with stunning mountain views and a peaceful vibe?', '', 'aapkihonewalibiwii', 1785660996, '/r/MoviesThatFeelLike/comments/1vdd0vz/whats_a_movie_with_stunning_mountain_views_and_a/', 'https://i.redd.it/v13v7x6xexgh1.jpeg', 'MoviesThatFeelLike', 'A serene collection of films showcasing majestic mountain landscapes and tranquil atmospheres.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (901, '1vdfdla', 'Movies that feel like this', 'Movies that feel like this', 'Help me!', 'Character-Bat-7397', 1785669184, '/r/MoviesThatFeelLike/comments/1vdfdla/movies_that_feel_like_this/', 'https://i.redd.it/rtpelke93ygh1.jpeg', 'MoviesThatFeelLike', 'A dark folk horror dread permeates misty, isolated landscapes.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (902, '1vdfi0f', 'Movies that feel like this', '', '', 'Character-Bat-7397', 1785669593, '/r/MoviesThatFeelLike/comments/1vdfi0f/movies_that_feel_like_this/', 'https://v.redd.it/r7sqmrrg4ygh1', 'MoviesThatFeelLike', 'An eclectic mix of eerie, contemplative, and unsettling atmospheres.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (903, '1vdfjct', 'Movies that feel like Gilmore Girls if Lane was the main character', '', '', 'Accomplished_Rip2583', 1785669719, '/r/MoviesThatFeelLike/comments/1vdfjct/movies_that_feel_like_gilmore_girls_if_lane_was/', 'https://www.reddit.com/gallery/1vdfjct', 'MoviesThatFeelLike', 'Indie-rock fueled coming-of-age about a rebellious young woman breaking free from strict expectations through music and friendship.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (904, '1vdg7gm', 'Movies that feels like this?', 'Movies that feel like an Indian research facility in Antarctica', 'Indian research facility at Antarctica  ', 'Important_War_8574', 1785671899, '/r/MoviesThatFeelLike/comments/1vdg7gm/movies_that_feels_like_this/', 'https://i.redd.it/6cd4kwv7bygh1.png', 'MoviesThatFeelLike', 'An isolated, frozen research station where scientific pursuit meets creeping paranoia and extraterrestrial mystery.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (905, '1vdgc9r', 'Movies that feel like this?', '', '', 'jeezogee', 1785672248, '/r/MoviesThatFeelLike/comments/1vdgc9r/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vdgc9r', 'MoviesThatFeelLike', 'A glitched-out, psychedelic digital nightmare blending organic and synthetic forms.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (906, '1vdhc3r', 'Movies that feel like this', 'Movies that feel like this', '', 'Character-Bat-7397', 1785675164, '/r/MoviesThatFeelLike/comments/1vdhc3r/movies_that_feel_like_this/', 'https://i.redd.it/2tyx0l01lygh1.jpeg', 'MoviesThatFeelLike', 'An eerie, foggy road where unseen footsteps crunch on wet gravel.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (907, '1vdjfdc', 'looking for futuristic movies with a unique atmosphere', '', '[removed]', 'meowwowwie', 1785680685, '/r/MoviesThatFeelLike/comments/1vdjfdc/looking_for_futuristic_movies_with_a_unique/', 'https://www.reddit.com/gallery/1vdjfdc', 'MoviesThatFeelLike', 'A futuristic and uniquely atmospheric mood.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (908, '1vdjj1z', 'movies that feel like wandering through a futuristic city at night', 'movies that feel like wandering through a futuristic city at night', '[removed]', 'meowwowwie', 1785680946, '/r/MoviesThatFeelLike/comments/1vdjj1z/movies_that_feel_like_wandering_through_a/', 'https://www.reddit.com/gallery/1vdjj1z', 'MoviesThatFeelLike', 'Wandering through a futuristic city at night', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (909, '1vdkkq6', 'A movie that feels like The Hateful Eight', 'A movie that feels like The Hateful Eight', 'a group of people trapped together in one location during a snowstorm, heavy rain, or freezing weather, with growing tension and conflict between the characters.', 'Reasonable-Quit5869', 1785683507, '/r/MoviesThatFeelLike/comments/1vdkkq6/a_movie_that_feels_like_the_hateful_eight/', 'https://www.reddit.com/gallery/1vdkkq6', 'MoviesThatFeelLike', 'Snowbound paranoia and simmering conflict among strangers.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (910, '1vdlsxs', 'Something with a vibrant visual style like Margo’s Got Money Troubles and Me and Earl and the Dying Girl. Preferably heartfelt as well', 'Something with a vibrant visual style like Margo’s Got Money Troubles and Me and Earl and the Dying Girl. Preferably heartfelt as well', '', 'sadkinz', 1785686459, '/r/MoviesThatFeelLike/comments/1vdlsxs/something_with_a_vibrant_visual_style_like_margos/', 'https://www.reddit.com/gallery/1vdlsxs', 'MoviesThatFeelLike', 'Vibrant, heartfelt visual storytelling with a quirky, emotional tone.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (911, '1vdm0gf', 'Movies with this vibe', 'Movies with this vibe', '', 'capibarawithsocks', 1785686944, '/r/MoviesThatFeelLike/comments/1vdm0gf/movies_with_this_vibe/', 'https://v.redd.it/czu2grx2kzgh1', 'MoviesThatFeelLike', 'Vibrantly colorful and whimsically surreal dreamscapes.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (912, '1vdoidb', 'Movies feel like this..', 'Movies feel like this..', '', 'brat_3434', 1785692892, '/r/MoviesThatFeelLike/comments/1vdoidb/movies_feel_like_this/', 'https://www.reddit.com/gallery/1vdoidb', 'MoviesThatFeelLike', 'Unspecified vibe', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (913, '1vdokxz', 'Movies that feel like this...', '', '', 'brat_3434', 1785693064, '/r/MoviesThatFeelLike/comments/1vdokxz/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vdokxz', 'MoviesThatFeelLike', 'A descent into unsettling, nightmarish horror with surreal imagery and existential dread.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (914, '1vdqrvv', 'movies that feel like it follows (2014)?', '', 'this movie is SO good in terms of vibes and horror and plot. have yet to find a single other movie like it. ', 'CryGroundbreaking945', 1785698121, '/r/MoviesThatFeelLike/comments/1vdqrvv/movies_that_feel_like_it_follows_2014/', 'https://i.redd.it/vzhkhugbh0hh1.jpeg', 'MoviesThatFeelLike', 'Synth-drenched suburban dread with an unrelenting shape-shifting entity.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (915, '1vdugvh', 'Movies with Good-Looking loners', 'Movies with Good-Looking loners', 'Looking for movies where there is a good-looking loner/rebel. Female characters especially!!! ', 'Talilala', 1785706920, '/r/MoviesThatFeelLike/comments/1vdugvh/movies_with_goodlooking_loners/', 'https://www.reddit.com/gallery/1vdugvh', 'MoviesThatFeelLike', 'Alluring, independent loners—especially women—radiating cool detachment and rebellious spirit.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (916, '1vdvhcj', 'Movies truly melancholic', '', 'i need it ', 'iankdoria', 1785709460, '/r/MoviesThatFeelLike/comments/1vdvhcj/movies_truly_melancholic/', 'https://www.reddit.com/gallery/1vdvhcj', 'MoviesThatFeelLike', 'A deeply melancholic and somber atmosphere, reflecting themes of loss, loneliness, and existential despair.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (917, '1vdwb1q', 'The dated boarding school/ family comedic vibe, especially in Irish or England, possibly based on book', '', 'Could think of Derry Girls and Wild Child for now, movies or shows both please', 'Comfortable_Metal334', 1785711612, '/r/MoviesThatFeelLike/comments/1vdwb1q/the_dated_boarding_school_family_comedic_vibe/', 'https://www.reddit.com/gallery/1vdwb1q', 'MoviesThatFeelLike', 'Nostalgic and mischievous comedy-drama set in Irish or British boarding schools and families, often with literary roots.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (918, '1vdww19', 'Movies like Birdman or (The Unexpected Virtue of Ignorance)', '', '', 'Garidur', 1785713131, '/r/MoviesThatFeelLike/comments/1vdww19/movies_like_birdman_or_the_unexpected_virtue_of/', 'https://i.redd.it/sn2jgl3yp1hh1.jpeg', 'MoviesThatFeelLike', 'Surreal backstage drama with dark comedy and a seamless-shot illusion.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (919, '1vdxdkd', 'Movies with this vibe?', 'Movies with this vibe', '', 'Disastrous-Bag-1725', 1785714435, '/r/MoviesThatFeelLike/comments/1vdxdkd/movies_with_this_vibe/', 'https://www.reddit.com/gallery/1vdxdkd', 'MoviesThatFeelLike', 'Coastal melancholy with hints of magic and isolation.', 'publishable', NULL, NULL, '2026-08-03 14:31:56', '2026-08-03 14:31:56');
