-- 0061_seed_20260804T031859Z_01_posts.sql: data seed from pipeline:load run.
-- Generated:  2026-08-04T03:20:14.043665+00:00
-- Run started: 2026-08-04T03:18:59.386101+00:00
-- Source: data/working/load manifest from this run.
--
-- Idempotent: every INSERT is INSERT OR IGNORE, keyed by the
-- table's natural unique constraint.  Wrangler's migration
-- tracking normally prevents re-apply; the OR IGNORE is
-- defense in depth for partial / interrupted re-runs.
--
-- Chunk: 01_posts (1/5)
-- Tables: imported_vibe_posts.
-- Pipeline-state tables (processing_runs, pipeline_artifacts)
-- are intentionally excluded — they're per-run bookkeeping.

INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (920, '1ut8l56', 'Movies that feel like a calm evening with thunderstorms? there is chaos abounds but at a distance', 'Movies that feel like a calm evening with thunderstorms, chaos abounds at a distance', '', 'SinisterSpectr', 1783739523, '/r/MoviesThatFeelLike/comments/1ut8l56/movies_that_feel_like_a_calm_evening_with/', 'https://v.redd.it/9pgf7xaepich1', 'MoviesThatFeelLike', 'A calm evening with distant thunderstorms and looming chaos, where disaster feels both threatening and serene.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (921, '1ut8qme', 'Movies like this', 'Movies like this', '', 'Idek163', 1783739976, '/r/MoviesThatFeelLike/comments/1ut8qme/movies_like_this/', 'https://www.reddit.com/gallery/1ut8qme', 'MoviesThatFeelLike', 'A nostalgic, whimsical dark fairy-tale atmosphere blending medieval fantasy with magical, dreamlike visuals.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (922, '1ut9lvs', '[Request] Looking for cozy movies.', 'Looking for cozy movies.', '', 'Sad-Abrocoma-6947', 1783742597, '/r/MoviesThatFeelLike/comments/1ut9lvs/request_looking_for_cozy_movies/', '/r/NetflixBestOf/comments/1url06q/request_looking_for_cozy_movies/', 'MoviesThatFeelLike', 'cozy', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (923, '1ut9pp9', 'Movies with this kind of feel?', 'Movies with this kind of feel', 'I''m looking for a gritty but kinda bouncy vibe with some horror thrown in

If it''s early CGI animation, even better!

Malice@doll is already on my list', 'dumbpuppyabouttown', 1783742922, '/r/MoviesThatFeelLike/comments/1ut9pp9/movies_with_this_kind_of_feel/', 'https://www.reddit.com/gallery/1ut9pp9', 'MoviesThatFeelLike', 'Gritty bouncy horror with early CGI aesthetic.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (924, '1ut9xgp', 'movies that feel like this also please read the body text', 'movies that feel like this also please read the body text', 'what is this aesthetic even called?

', 'Daoyinyang1', 1783743577, '/r/MoviesThatFeelLike/comments/1ut9xgp/movies_that_feel_like_this_also_please_read_the/', 'https://www.reddit.com/gallery/1ut9xgp', 'MoviesThatFeelLike', 'A whimsical, faintly eerie vintage animation style reminiscent of early 20th-century children''s book illustrations and folk art.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (925, '1ut9ypf', 'God ends here.', 'God ends here.', '', 'Tasty_Equivalent_305', 1783743673, '/r/MoviesThatFeelLike/comments/1ut9ypf/god_ends_here/', 'https://i.redd.it/4i3dx1oq1jch1.jpeg', 'MoviesThatFeelLike', 'A grim, religious horror atmosphere where ancient doorways mark the end of divinity.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (926, '1uta42a', 'Movies that feel like my newest painting.', 'Movies that feel like my newest painting.', '', 'YeahWellDesigns', 1783744138, '/r/MoviesThatFeelLike/comments/1uta42a/movies_that_feel_like_my_newest_painting/', 'https://i.redd.it/zkqxtmf43jch1.jpeg', 'MoviesThatFeelLike', 'Unsettling and surreal horror.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (927, '1utdoti', 'Movies that feel like untouched culture', '', 'Or shows ', 'No-Crazy-1159', 1783755941, '/r/MoviesThatFeelLike/comments/1utdoti/movies_that_feel_like_untouched_culture/', 'https://www.reddit.com/gallery/1utdoti', 'MoviesThatFeelLike', 'An immersive, unspoiled glimpse into indigenous and pre-colonial worlds.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (928, '1utfpmy', 'selling 4 tickets for baby do die do on 12 July , 10.20 pm show, vega city mall', '', '', 'blueberry_addict_', 1783763094, '/r/MoviesThatFeelLike/comments/1utfpmy/selling_4_tickets_for_baby_do_die_do_on_12_july/', 'https://www.reddit.com/gallery/1utfeu7', 'MoviesThatFeelLike', 'A ticket sales announcement', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (929, '1uthcsd', 'Cozy, low-stake with these vibes', 'Cozy, low-stake with these vibes', '', 'Due_Fly_6934', 1783768615, '/r/MoviesThatFeelLike/comments/1uthcsd/cozy_lowstake_with_these_vibes/', 'https://www.reddit.com/gallery/1uthcsd', 'MoviesThatFeelLike', 'Cozy and low-stakes, gentle and heartwarming atmosphere.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (930, '1uti7h1', 'Similiar to "Pearl", "Revenge" and "Promising Young Woman"?', '', '[removed]', 'Curious_Question_232', 1783771191, '/r/MoviesThatFeelLike/comments/1uti7h1/similiar_to_pearl_revenge_and_promising_young/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uti7h1/similiar_to_pearl_revenge_and_promising_young/', 'MoviesThatFeelLike', 'Feminine fury wrapped in dark glamour; a thirst for retribution.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (931, '1utj7pd', 'Can be any genre btw (except romance)', 'Can be any genre btw (except romance)', '', 'ProfessionalOnion727', 1783774001, '/r/MoviesThatFeelLike/comments/1utj7pd/can_be_any_genre_btw_except_romance/', 'https://www.reddit.com/gallery/1utj7pd', 'MoviesThatFeelLike', 'Eerie, rain-soaked Pacific Northwest forest with a supernatural atmosphere.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (932, '1utl154', 'I watched A mist and Requiem for a dream in a single day. I dont feel good.', 'Devastating double feature: The Mist and Requiem for a Dream', 'Tbh I wanted to try these movies for a long time as they were sitting in my watchlist. Yesterday I got a reel where both of them were suggested. I started to watch A mist yesterday night and i was prepared for a sad ending ( i do like thriller movies and twisted endings) however this was just something else. I couldn’t sleep well. Then today i woke up and thought lets just get it over with and decided to watch Requiem for a dream.     
By the time i was watching it i was predicting the ending just so yk i can prepare myself. I thought the worst is all of them die due to addiction. They all lived and somehow it was worse. The fact that the person who got his arm amputated was the most well off among them is soo tragic !

The whole experience has taken a toll on my mental health. Nonetheless brilliant movies.

And at last dont need spoilers but how’s A Serbian Film ? ', 'UTKARSH0078', 1783778732, '/r/MoviesThatFeelLike/comments/1utl154/i_watched_a_mist_and_requiem_for_a_dream_in_a/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1utl154/i_watched_a_mist_and_requiem_for_a_dream_in_a/', 'MoviesThatFeelLike', 'A harrowing dive into relentless despair and emotional devastation, leaving a lingering hollow ache.', 'skipped', 'no usable images', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (933, '1utlhvq', 'SPEDIZIONE CINA ITALIAr', 'Spedizione Cina Italia', '', 'Fit_Animal2909', 1783779871, '/r/MoviesThatFeelLike/comments/1utlhvq/spedizione_cina_italiar/', 'https://www.reddit.com/gallery/1usp913', 'MoviesThatFeelLike', 'transactional', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (934, '1utlm6g', 'Gimme something that feels like', 'Gimme something that feels like a misty mountain above the clouds', '', 'JoshHartsMilkMustach', 1783780172, '/r/MoviesThatFeelLike/comments/1utlm6g/gimme_something_that_feels_like/', 'https://i.redd.it/0wq7f9s92mch1.jpeg', 'MoviesThatFeelLike', 'Awe-inspiring mist-veiled peak soaring above a sea of clouds, evoking serene solitude and grand adventure.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (935, '1utp51e', 'Period piece that feels like a painting left out in the rain', 'Period piece that feels like a painting left out in the rain', 'I love the cinematography of The Color of Pomegranates, but hoping to find something more dialogue and story driven ', 'urstepdad', 1783788552, '/r/MoviesThatFeelLike/comments/1utp51e/period_piece_that_feels_like_a_painting_left_out/', 'https://www.reddit.com/gallery/1utp51e', 'MoviesThatFeelLike', 'Films with painterly, rain-washed aesthetics, decaying beauty, and melancholic historical settings.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (936, '1v23ak5', 'Movies that feel like', 'Movies that feel like', '', 'please-kill-me-69', 1784594672, '/r/MoviesThatFeelLike/comments/1v23ak5/movies_that_feel_like/', 'https://i.redd.it/w1az0o77cheh1.jpeg', 'MoviesThatFeelLike', 'A vast desert world under a looming sky, evoking cosmic solitude and surreal sci-fi grandeur.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (937, '1v23wzp', 'This beautiful vibe in any movies/shows ? I love it smmmm', '', '', 'donutz-4-berries8', 1784596345, '/r/MoviesThatFeelLike/comments/1v23wzp/this_beautiful_vibe_in_any_moviesshows_i_love_it/', 'https://www.reddit.com/gallery/1v23wzp', 'MoviesThatFeelLike', 'Moody, windswept coastal isolation with a touch of gothic romance and melancholic mystery.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (938, '1v25hvp', 'movies that feel like this?', 'Coastal New England summer, beach houses, nostalgia, and romantic drama', '', 'ConsciousRest4726', 1784600656, '/r/MoviesThatFeelLike/comments/1v25hvp/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1v25hvp', 'MoviesThatFeelLike', 'Sun-drenched New England summer, beach houses, and romantic nostalgia.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (939, '1v27x2h', 'Movies that feel like', '', '', 'CAyukon', 1784607600, '/r/MoviesThatFeelLike/comments/1v27x2h/movies_that_feel_like/', 'https://www.reddit.com/gallery/1v27x2h', 'MoviesThatFeelLike', 'Dark industrial sci-fi with survival horror undertones', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (940, '1v28p3m', 'Movie like this', 'Movie like this', '[removed]', '[deleted]', 1784610005, '/r/MoviesThatFeelLike/comments/1v28p3m/movie_like_this/', '', 'MoviesThatFeelLike', '', 'skipped', 'no usable images; no vibe summary; no enriched recommendation matches', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (941, '1v29k9p', 'Movie like this', 'Movie like this', '', 'Tricky_cielito00', 1784612807, '/r/MoviesThatFeelLike/comments/1v29k9p/movie_like_this/', 'https://i.redd.it/jdrlpq54uieh1.jpeg', 'MoviesThatFeelLike', '', 'skipped', 'no vibe summary; no enriched recommendation matches', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (942, '1v2ablw', 'Movies that feel like found footage vibe', 'Movies that feel like found footage vibe', '', 'Ancient_Win_2837', 1784615300, '/r/MoviesThatFeelLike/comments/1v2ablw/movies_that_feel_like_found_footage_vibe/', 'https://i.redd.it/rj644z5j1jeh1.jpeg', 'MoviesThatFeelLike', 'Gritty, immersive first-person horror that blurs the line between fiction and reality.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (943, '1v2hix2', 'Eerie, Poetic, and Immersive Films with an atmosphere like "The Last Wave"', '', '*"The Last Wave* is a hypnotizing, mood- and rain-drenched dreamscape, portending of apocalyptic horror." Looking for similar films that are deeply immersive and atmospheric, and have supernatural elements....

Films that I know (and that are similar):

\- All Lynch movies

\- Stalker

\- First half of Alien (1979)

\- Bela Tarr films

The films should be eerie, brooding and "poetic" (with great cinematography), but no full out horror please (no or not much blood and gore, etc.).

I do not need a good story either - it is all about the atmosphere and immersion, I love "slow and boring" films with not much action... 

Thank you!

Bonus for having a deeply immersive synth soundtrack like The Last Wave.

', 'Fichtenwald', 1784638214, '/r/MoviesThatFeelLike/comments/1v2hix2/eerie_poetic_and_immersive_films_with_an/', 'https://youtu.be/g3pWBS0HmsA?si=565J9K_NBOod_OC1', 'MoviesThatFeelLike', 'A hypnotic, rain-drenched dreamscape of brooding apocalyptic horror, with a poetic and immersive atmosphere.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (944, '1v2hszk', 'Movies that feels like the game Thief', 'Movies that feel like the game Thief', '', 'Radiant-Boat-5149', 1784638905, '/r/MoviesThatFeelLike/comments/1v2hszk/movies_that_feels_like_the_game_thief/', 'https://www.reddit.com/gallery/1v2hszk', 'MoviesThatFeelLike', 'A shadowy, gothic atmosphere with stealthy protagonists navigating dark medieval streets and forbidden places.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (945, '1v2ima7', 'A movie that feels like this...', '', '', 'the-maximalist', 1784640833, '/r/MoviesThatFeelLike/comments/1v2ima7/a_movie_that_feels_like_this/', 'https://i.redd.it/prykrwpf5leh1.png', 'MoviesThatFeelLike', 'A chaotic blend of absurdist humor and satirical dystopia.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (946, '1v2j22x', 'Movies that feel like this?', 'Movies that feel like this?', '', 'regression-analysis', 1784641862, '/r/MoviesThatFeelLike/comments/1v2j22x/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1v2j22x', 'MoviesThatFeelLike', 'Rugged isolation and the stark, unforgiving beauty of the wilderness.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (947, '1v2jb5u', 'Movies that feel like this?', 'Movies that feel like this?', 'Feminine, ethereal, dark and perhaps a little mysterious', 'silver_he4rt', 1784642437, '/r/MoviesThatFeelLike/comments/1v2jb5u/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1v2jb5u', 'MoviesThatFeelLike', 'Feminine, ethereal, dark, and mysterious.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (948, '1v2jlz0', 'Flicks that have this mystical feel?', '', 'I''ve already seen Aladdin and 1001 nights ', 'MrMonster480', 1784643107, '/r/MoviesThatFeelLike/comments/1v2jlz0/flicks_that_have_this_mystical_feel/', 'https://www.reddit.com/gallery/1v2jlz0', 'MoviesThatFeelLike', 'A mystical journey through ornate, dreamlike tales of wonder and enchantment.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (949, '1v2kb3r', 'Movies that feel like scholastic utopia', '', '', 'JazzlikeCharge8665', 1784644648, '/r/MoviesThatFeelLike/comments/1v2kb3r/movies_that_feel_like_scholastic_utopia/', 'https://www.reddit.com/gallery/1v2kb3r', 'MoviesThatFeelLike', 'Whimsical and imaginative adventures that blend wonder, nostalgia, and a touch of scholastic curiosity.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (950, '1v2lhqo', 'lighthouses, the cosmos, &/or storms.', 'lighthouses, the cosmos, &/or storms.', 'NOT MY POST, just loved this so much and wanted more of it!!! ', 'Maleficent-Bend1611', 1784647208, '/r/MoviesThatFeelLike/comments/1v2lhqo/lighthouses_the_cosmos_or_storms/', 'https://www.reddit.com/gallery/1uqen82', 'MoviesThatFeelLike', 'A moody, atmospheric fusion of lighthouse isolation, cosmic mystery, and stormy turbulence.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (951, '1v2mszz', 'Movies that feel like Rides With Strangers (Horror videogame, 2016).', '', 'Movies with a hitch hiker that always pretends to be nice but that is the villain for the whole movie and pushing boundaries at extreme.

The weather can be rainy, sunny and other weathers.

The plot can take place in day or night.', 'SmallEconomics6173', 1784649998, '/r/MoviesThatFeelLike/comments/1v2mszz/movies_that_feel_like_rides_with_strangers_horror/', 'https://www.reddit.com/gallery/1v2mszz', 'MoviesThatFeelLike', 'Tense psychological horror with a deceptively friendly hitchhiker antagonist.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (952, '1v2pcph', 'Movies that feels like the novel Salt to the Sea', 'Movies that feels like the novel Salt to the Sea', 'I really like Salt to the Sea, and I always imagine if there''s a movie adaptation to this that would be so cool. So I wonder if there are movies/series that have the same storytelling, like having many character''s pov as introduction and then they all eventually meet in an event/incident.', 'pricklepies', 1784655389, '/r/MoviesThatFeelLike/comments/1v2pcph/movies_that_feels_like_the_novel_salt_to_the_sea/', 'https://i.redd.it/dde0o4lqcmeh1.jpeg', 'MoviesThatFeelLike', 'Multiple character perspectives introduced separately before converging at a shared event', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (953, '1v2popb', 'Dark atmosphere, MATURE Romance and Sci-Fi themes', '', 'Preferably not anime even though most of the reference shots are.', 'PurifiedDrinkinWater', 1784656083, '/r/MoviesThatFeelLike/comments/1v2popb/dark_atmosphere_mature_romance_and_scifi_themes/', 'https://www.reddit.com/gallery/1v2popb', 'MoviesThatFeelLike', 'Dark, mature sci-fi romance.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (954, '1v2rf7r', 'Horror movies with this larger than life ocean horror vibe', 'Horror movies with this larger than life ocean horror vibe', '', 'Clockerton2', 1784659655, '/r/MoviesThatFeelLike/comments/1v2rf7r/horror_movies_with_this_larger_than_life_ocean/', 'https://www.reddit.com/gallery/1v2rf7r', 'MoviesThatFeelLike', 'An oppressive sense of dread as unimaginably vast horrors lurk beneath the dark ocean surface.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (955, '1v47xbt', 'Can yall give me movies and books that are going to make me cry.. like ball my eyes out cry', 'Can yall give me movies and books that are going to make me cry.. like ball my eyes out cry', 'Themes of extreme loneliness, alienation, safety, fear', 'Ok-Algae-4521', 1784795657, '/r/MoviesThatFeelLike/comments/1v47xbt/can_yall_give_me_movies_and_books_that_are_going/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1v47xbt/can_yall_give_me_movies_and_books_that_are_going/', 'MoviesThatFeelLike', 'Extreme loneliness and alienation intertwined with fear and fragile safety.', 'skipped', 'no usable images', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (956, '1v49k83', 'Movies with completely over-the-top autumn Hallmark vibes; foliage, cozy decor, endless fall activities 🍁🍂🎃', 'Movies with completely over-the-top autumn Hallmark vibes; foliage, cozy decor, endless fall activities', 'Sometimes, I just want an over-the-top autumn movie. Fall is my favorite season, and I''m looking for films where the foliage, sweaters, pumpkin patches, fall festivals, and small towns covered in gourds are dialed up to 11. They can be Hallmark/Lifetime, but they definitely don''t have to be. Indie films, lesser-known films, and hidden gems from any genre are welcome. I have seen thousands of films, so the lesser-known, the better! Thank you all. 🎃🍂', 'savvylee17', 1784801222, '/r/MoviesThatFeelLike/comments/1v49k83/movies_with_completely_overthetop_autumn_hallmark/', 'https://www.reddit.com/gallery/1v49k83', 'MoviesThatFeelLike', 'Over-the-top autumn atmosphere with vibrant foliage, cozy sweaters, pumpkin patches, and charming small-town fall festivals.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (957, '1vbal6e', 'That sleek European underground resistance...', '', '', 'Master-Permission527', 1785456003, '/r/MoviesThatFeelLike/comments/1vbal6e/that_sleek_european_underground_resistance/', 'https://www.reddit.com/gallery/1vbal6e', 'MoviesThatFeelLike', 'Sleek, clandestine European resistance with a tense, stylish atmosphere.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (958, '1vbjros', 'Movies with this vibe', 'Movies with this vibe', 'Any movies that feel like this or would have been on in these pictures? I am 23 so looking for all suggestions that are fit for any age, not just kids movies but those are welcome too', 'cnstntwrthlssnss', 1785482332, '/r/MoviesThatFeelLike/comments/1vbjros/movies_with_this_vibe/', 'https://www.reddit.com/gallery/1vbjros', 'MoviesThatFeelLike', 'Early 2000s teenage girl nostalgia, sleepovers, and colorful pop culture.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (959, '1vbls1d', 'Movies that bring in an expert to solve a problem', 'Movies that bring in an expert to solve a problem', 'You know the familiar trope where the government or anyone dealing with a problem calls upon an expert in some niche field to solve it. Not limited to any genre specifically either.   
Examples include:  
\-Arrival when Amy Adam’s is flown in to speak to Abott and Costello  
\-Jaws  
\-Interstellar Matt McConaughey’s Coop  
\-Girl with the dragon tattoo when they bring in Daniel Craig and Rooney Mara    
Thanks for any recommendations!', 'MichaelVthatsme', 1785489236, '/r/MoviesThatFeelLike/comments/1vbls1d/movies_that_bring_in_an_expert_to_solve_a_problem/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vbls1d/movies_that_bring_in_an_expert_to_solve_a_problem/', 'MoviesThatFeelLike', 'The calm authority of a specialist stepping into chaos', 'skipped', 'no usable images', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (960, '1vbq8au', 'Big, colorful, hyper violence.', '', 'I think this has become one of my favorite genres over the past few years. I love the way these movies are colorful, with fun graphics on screen (ammo counter for guns akimbo, pee meter from Scott Pilgrim), super styleized violence, and a soundtrack to match. 

These are the first three films that popped into my head, but I want to see more!

Any other suggestions?', 'AtlasPeacock', 1785502672, '/r/MoviesThatFeelLike/comments/1vbq8au/big_colorful_hyper_violence/', 'https://www.reddit.com/gallery/1vbq8au', 'MoviesThatFeelLike', 'Stylized action with vibrant colors, on-screen graphics, and over-the-top violence set to energetic soundtracks.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (961, '1vbzla6', 'Movies that feels like a shoegaze', 'Movies that feel like a shoegaze', 'Literally anything,thank you very much', 'East_Emphasis_8259', 1785523530, '/r/MoviesThatFeelLike/comments/1vbzla6/movies_that_feels_like_a_shoegaze/', 'https://www.reddit.com/gallery/1vbzla6', 'MoviesThatFeelLike', 'Dreamy, hazy, melancholic atmosphere akin to shoegaze music.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (962, '1vcmhya', 'Movies about alien abductions, cryptids and conspiracies?', 'Movies about alien abductions, cryptids and conspiracies?', 'Helloo, I''m searching for something with this vibe, very classic X-files. For reference I''ve loved Bugonia but i''d prefer to see something low budget, B-movie like The Wicksboro Incident. The more obscure, strange and underground the better. Cryptids and cults are welcome as well!!! Does anybody have ideas? Thank youu', 'Volpina17', 1785588388, '/r/MoviesThatFeelLike/comments/1vcmhya/movies_about_alien_abductions_cryptids_and/', 'https://www.reddit.com/gallery/1vcmhya', 'MoviesThatFeelLike', 'Classic X-Files-style paranoia: low-budget, conspiracy-laden mysteries with alien abductions, cryptids, and cults, wrapped in an obscure, eerie atmosphere.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (963, '1vd3qkz', 'I''m making a short film for a project and I need some inspiration', 'I''m making a short film for a project and I need some inspiration', 'I was thinking surreal and liminal and fuzzy while theres a normal person who gets sucked into this zone and isnt supposed to be there, but I want some inspiration of more elements to incorporate. ', 'AffectionateBat5232', 1785631568, '/r/MoviesThatFeelLike/comments/1vd3qkz/im_making_a_short_film_for_a_project_and_i_need/', 'https://www.reddit.com/gallery/1vd3qkz', 'MoviesThatFeelLike', 'Surreal, liminal, and eerie, with a normal person trapped in a distorted reality.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (964, '1vdb9bg', 'Movies and series that center about music and record stores', 'Movies and series that center about music and record stores', '', 'GuitarJunkie12', 1785654765, '/r/MoviesThatFeelLike/comments/1vdb9bg/movies_and_series_that_center_about_music_and/', 'https://www.reddit.com/gallery/1vdb9bg', 'MoviesThatFeelLike', 'A nostalgic hangout in a record store, surrounded by vinyl and music snobbery.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (965, '1vdbe68', 'Please drop anything', 'Please drop anything', 'Need movies that feel like a spiritual high (dark) fantasy world from another planet, set in a time that could be either past or present, steampunk elements are welcome - for reference two movies are Vampire Hunter D and Treasure Planet ', 'cornflakesdude', 1785655229, '/r/MoviesThatFeelLike/comments/1vdbe68/please_drop_anything/', 'https://www.reddit.com/gallery/1vdbe68', 'MoviesThatFeelLike', 'A mystical, otherworldly journey through dark fantasy landscapes blending ancient and futuristic elements.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (966, '1vdetom', 'YEARNING for this', 'yearning for this', 'Any and all suggestions welcome 🤠🪩', 'newsforyababy', 1785667366, '/r/MoviesThatFeelLike/comments/1vdetom/yearning_for_this/', 'https://www.reddit.com/gallery/1vdetom', 'MoviesThatFeelLike', 'A longing for sultry, neon-lit country bar nights with mechanical bulls, live music, and a sense of freedom.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (967, '1vdrf40', 'Movies that feels like this..', 'Movies that feels like this..', '', 'That_Firefly', 1785699629, '/r/MoviesThatFeelLike/comments/1vdrf40/movies_that_feels_like_this/', 'https://www.reddit.com/gallery/1vdrf40', 'MoviesThatFeelLike', 'A misty, ethereal fantasy forest alive with glowing magic, blending dark fairy-tale enchantment with spiritual wonder.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (968, '1vduziw', 'Películas que se sientan como esto', 'Películas que se sientan como esto', '', 'aleannyqueen', 1785708214, '/r/MoviesThatFeelLike/comments/1vduziw/películas_que_se_sientan_como_esto/', 'https://www.reddit.com/gallery/1vduziw', 'MoviesThatFeelLike', 'unknown atmosphere', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (969, '1vdykrx', 'Movies that feel like the paintings of Edward Hopper', 'Movies that feel like the paintings of Edward Hopper', '', 'Lukotheduko', 1785717655, '/r/MoviesThatFeelLike/comments/1vdykrx/movies_that_feel_like_the_paintings_of_edward/', 'https://www.reddit.com/gallery/1vdykrx', 'MoviesThatFeelLike', 'lonely, still, and beautifully melancholic Americana', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (970, '1vdzbpa', 'Visual Style Like ‘School In The Crosshairs’ (1981)?', '', 'Another I can think of immediately is ‘House’. Which is fantastic and chaotic. 

Crazy Japanese films from the 80s are some of my favourites. Do ya’ll have any personal recommendations? 

Thank you! ', 'isopodsoup_', 1785719737, '/r/MoviesThatFeelLike/comments/1vdzbpa/visual_style_like_school_in_the_crosshairs_1981/', 'https://www.reddit.com/gallery/1vdzbpa', 'MoviesThatFeelLike', 'chaotic and fantastical 80s cinema', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (971, '1vdznhk', 'Movies that feel like this', 'Movies that feel like this', '', 'Electronic-Cricket77', 1785720682, '/r/MoviesThatFeelLike/comments/1vdznhk/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vdznhk', 'MoviesThatFeelLike', 'Psychological thrillers centered on obsession, stalking, and dangerous love.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (972, '1ve086e', 'Movie’s that feel like this?', '', 'Sorry if it’s too niche.', 'Personal-Crazy6179', 1785722348, '/r/MoviesThatFeelLike/comments/1ve086e/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1ve086e', 'MoviesThatFeelLike', 'Uncanny valley doll-like aesthetic with a plastic, hyper-feminine, and slightly menacing undertone.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (973, '1ve0nnr', 'Movies that feel like this…?', 'Movies that feel like this', '', 'AppleBonker666', 1785723537, '/r/MoviesThatFeelLike/comments/1ve0nnr/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1ve0nnr', 'MoviesThatFeelLike', 'Nostalgic, melancholic suburban adolescence blending gritty realism with fleeting beauty.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (974, '1ve0p0r', 'Movies that feel like this?', 'Movies that feel like this', 'All genres welcome but I’d love a good romance or fantasy film :)', 'siento_1227', 1785723647, '/r/MoviesThatFeelLike/comments/1ve0p0r/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vdswwf', 'MoviesThatFeelLike', 'A dreamy, ethereal atmosphere with romantic and fantasy undertones, reminiscent of fairy tales and wistful melancholy.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (975, '1ve0vrd', 'Movies like this?', 'Movies like this?', 'Dumb, I know. 

Any movies that feel like the old roblox game ''scuba diving in quill lake''? ', 'SpaceyLadybug', 1785724192, '/r/MoviesThatFeelLike/comments/1ve0vrd/movies_like_this/', 'https://i.redd.it/cv3sb9aum2hh1.jpeg', 'MoviesThatFeelLike', 'Underwater exploration with a nostalgic, serene, and slightly eerie mood.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (976, '1ve3i3b', 'Movies that feel like this.', 'Movies that feel like this.', '', 'wormword46', 1785732119, '/r/MoviesThatFeelLike/comments/1ve3i3b/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1ve3i3b', 'MoviesThatFeelLike', 'A bleak, raw, and emotionally devastating exploration of human despair and isolation.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (977, '1ve4uj1', '(Relatively) contemporary Southern gothic horror', '', 'Preferably stories set in the 60s-80s or even modern times. Slashers preferred, but I''ll settle for thrillers in general.', 'radbot027', 1785736499, '/r/MoviesThatFeelLike/comments/1ve4uj1/relatively_contemporary_southern_gothic_horror/', 'https://www.reddit.com/gallery/1ve4uj1', 'MoviesThatFeelLike', 'dark rural Southern Gothic atmosphere with slasher horror', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (978, '1ve5oez', 'Movie that feel like regular show', 'Movies that feel like Regular Show', '', 'daddylongjohnsliver', 1785739314, '/r/MoviesThatFeelLike/comments/1ve5oez/movie_that_feel_like_regular_show/', 'https://www.reddit.com/gallery/1ve5oez', 'MoviesThatFeelLike', 'Absurdist slacker comedy with surreal adventures', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (979, '1ve60ab', 'looking for movies that feel like la la land', '', '[removed]', 'Scary-Amount-9339', 1785740449, '/r/MoviesThatFeelLike/comments/1ve60ab/looking_for_movies_that_feel_like_la_la_land/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1ve60ab/looking_for_movies_that_feel_like_la_la_land/', 'MoviesThatFeelLike', 'Dreamy, nostalgic musical romance', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (980, '1ve66yg', 'No req just saying LY TY', '', 'New fav thread alert 🚨 ', 'atidalweave', 1785741060, '/r/MoviesThatFeelLike/comments/1ve66yg/no_req_just_saying_ly_ty/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1ve66yg/no_req_just_saying_ly_ty/', 'MoviesThatFeelLike', 'Appreciative excitement for a beloved thread', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (981, '1ve72br', 'Movies That Feel Like This', '', 'Y2K Futurism type vibes.

I''m thinking along the lines of:

I, Robot

Minority Report

Ultraviolet

Maaaybe:

Johnny Mnemonic

Men In Black

The Matrix - but it feels too organic/dirty/cyberpunk', 'welmanshirezeo', 1785744087, '/r/MoviesThatFeelLike/comments/1ve72br/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1ve72br', 'MoviesThatFeelLike', 'Y2K futurism: sleek, neon-drenched, techno-utopian aesthetic with early 2000s sci-fi optimism.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (982, '1ve9rky', 'Movies that feel like this...', 'Movies that feel like this...', '', 'MathematicianKey4726', 1785753313, '/r/MoviesThatFeelLike/comments/1ve9rky/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1ve9rky', 'MoviesThatFeelLike', 'Gritty 1970s nightlife with disco hedonism and streetwise swagger.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (983, '1ve9xvi', 'Cool, foggy, lush', 'Cool, foggy, lush', '', 'mermay799', 1785753900, '/r/MoviesThatFeelLike/comments/1ve9xvi/cool_foggy_lush/', 'https://www.reddit.com/gallery/1ve9xvi', 'MoviesThatFeelLike', 'A cool, foggy, and lush atmosphere', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (984, '1ve9zmk', 'Eerie movies but not intended', 'Eerie movies but not intended', 'There’s many movies that I watch that have this eerie trapped vibe in a simulator, the substance for example was sucha like suffocating film to watch it was like this girl trapped in a cycle that never was gonna end but it wasn’t just that it was also the lack of background actors and the repeating settings it made it eerie what is that style of movie called?

American psycho as well it had that no new characters and it feels as if the characters can’t exit like a Truman show situation for a character in a movie I’ve watched many movies that give off the characters are in a simulator and we’re watching them being punished through cameras and the settings are always repeated I noticed it mostly with the substance with demi Moore and Margaret qualley and American psycho with Christian bale 

They’re almost uncomfortable not for the plot but how the cameras are set up what’s this like thing called and what movies have that vibe that you’ve realised?', 'Old_Reach_9072', 1785754060, '/r/MoviesThatFeelLike/comments/1ve9zmk/eerie_movies_but_not_intended/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1ve9zmk/eerie_movies_but_not_intended/', 'MoviesThatFeelLike', 'Eerie, trapped-in-a-simulator atmosphere with suffocating repetition and surveillance-like camerawork.', 'skipped', 'no usable images', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (985, '1vecuad', 'Movies that feel like 90/2000s Programming Book Covers', 'Movies that feel like 90/2000s Programming Book Covers', '', 'waslous', 1785762204, '/r/MoviesThatFeelLike/comments/1vecuad/movies_that_feel_like_902000s_programming_book/', 'https://www.reddit.com/gallery/1vecuad', 'MoviesThatFeelLike', 'Retro-futuristic digital surrealism with early CGI, cyberpunk aesthetics, and tech-utopian wonder.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (986, '1vee9by', 'Movies that feel like this?', 'Movies that feel like this?', '', 'No-Sprinkles229', 1785765607, '/r/MoviesThatFeelLike/comments/1vee9by/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vee9by', 'MoviesThatFeelLike', 'Dreamlike reality-warping with surreal, atmospheric visuals and mysterious interconnections.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (987, '1vefb5r', 'Movies that feel like', 'Movies that feel like', 'Blade 2

Aliens

Army Of The Dead

Hellboy

Dog Soldiers 

Spectral', 'Zer0_T0nin', 1785767949, '/r/MoviesThatFeelLike/comments/1vefb5r/movies_that_feel_like/', 'https://www.reddit.com/gallery/1vefb5r', 'MoviesThatFeelLike', 'Gritty military-horror with monster-hunting misfits', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (988, '1vefe0e', 'Feel good Movies like dead poets society, Good will hunting', 'Feel good Movies like dead poets society, Good will hunting', '', 'ElderberryAdvanced91', 1785768123, '/r/MoviesThatFeelLike/comments/1vefe0e/feel_good_movies_like_dead_poets_society_good/', '/r/MovieSuggestions/comments/1vef9th/feel_good_movies_like_dead_poets_society_good/', 'MoviesThatFeelLike', 'Heartwarming dramas centered on mentorship and personal growth, evoking inspiration and nostalgia.', 'skipped', 'no usable images', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (989, '1vehgxr', 'Films that look/feel like Bela Tarr films but with a little more going on?', '', 'I absolutely love the way his films look and feel, and I even love how slow the pacing is, but the few I''ve watched were just lacking a little in terms of impact and weight of the events and stories. Are there any films or directors that have a similar feeling but maybe hit a little harder? Not quite sure what I''m asking for. Maybe a less polite way would be: Films like his that are not as boring?', 'ogodprotectme', 1785772688, '/r/MoviesThatFeelLike/comments/1vehgxr/films_that_lookfeel_like_bela_tarr_films_but_with/', 'https://www.reddit.com/gallery/1vehgxr', 'MoviesThatFeelLike', 'Slow, stark black-and-white cinema, long takes, contemplative pacing, but yearning for greater narrative weight and emotional impact.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (990, '1vehnp9', 'Movies that feel like this music.', 'Movies that feel like this music.', '', 'Cold-Bed498', 1785773071, '/r/MoviesThatFeelLike/comments/1vehnp9/movies_that_feel_like_this_music/', 'https://youtu.be/1IIyzob_yi8?is=M6t0Zpk78nHwrDjW', 'MoviesThatFeelLike', 'Unknown musical atmosphere; seeking movies that match an unspecified music-inspired mood.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (991, '1veholr', 'Movies that feel like this song.', '', '', 'Cold-Bed498', 1785773126, '/r/MoviesThatFeelLike/comments/1veholr/movies_that_feel_like_this_song/', 'https://youtu.be/1IIyzob_yi8?is=M6t0Zpk78nHwrDjW', 'MoviesThatFeelLike', '', 'skipped', 'no vibe summary; no enriched recommendation matches', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (992, '1vei63z', 'We turned a dog grooming salon into a spaceship and shot an entire sci-fi short in one day.', 'We turned a dog grooming salon into a spaceship and shot an entire sci-fi short in one day.', '', 'Dangerdogproductions', 1785774167, '/r/MoviesThatFeelLike/comments/1vei63z/we_turned_a_dog_grooming_salon_into_a_spaceship/', 'https://www.reddit.com/gallery/1vei5if', 'MoviesThatFeelLike', 'Resourceful DIY sci-fi filmmaking transformed a mundane space into a futuristic set.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (993, '1veiync', 'any movies with dark lighting and characters like this?', '', 'Are there any movies? (preferably between 1990-2015) that have female lead characters like these women? I need a good movie that is centered around a very good lying woman, who usually gets what she wants throughout the film (And yes i know alison isn’t from a movie) ', 'Extension-Pretniss', 1785775872, '/r/MoviesThatFeelLike/comments/1veiync/any_movies_with_dark_lighting_and_characters_like/', 'https://www.reddit.com/gallery/1veiync', 'MoviesThatFeelLike', 'Darkly lit psychological drama centered on a manipulative female lead', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (994, '1vejdfr', 'Movies that feel like this?', '', 'Is there any movies or shows that feel like this? and are actually interesting? i’ve already watched thirteen, jennifer’s body, tvd, and pll so there’s are off the table 😭', 'dobryoesty', 1785776733, '/r/MoviesThatFeelLike/comments/1vejdfr/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vejdfr', 'MoviesThatFeelLike', 'Edgy, brooding early 2000s teen angst with a body count.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (995, '1vel9fk', 'Movies that feel like analog horror / found footage.', 'Movies that feel like analog horror / found footage.', '', 'stelicag', 1785780806, '/r/MoviesThatFeelLike/comments/1vel9fk/movies_that_feel_like_analog_horror_found_footage/', 'https://www.reddit.com/gallery/1vel9fk', 'MoviesThatFeelLike', 'Analog horror and found-footage dread steeped in grainy VHS-era unease.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (996, '1velb4t', 'Dystopic movie with this criteria', 'Dystopic movie with this criteria', 'I want some movie recommendations with specific criteria: Chased people from government which they didn''t obeyed to system,having fun to hiden illegal clubs with goth clothing,techno music,neon lights,full of whores,drugs etc.In club scenes i would like also to be and the elite ones. (probably in different club 😂) I also mainly want to find and explore this kind of music! It is in dark quick beat rhythm,sexy,serious (not cheerful),and with no or bit (mainly sexy lyrics) on it!', 'kos25k', 1785780908, '/r/MoviesThatFeelLike/comments/1velb4t/dystopic_movie_with_this_criteria/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1velb4t/dystopic_movie_with_this_criteria/', 'MoviesThatFeelLike', 'A dystopian world of illegal goth clubs, pulsing techno beats, and neon-drenched rebellion against an oppressive government.', 'skipped', 'no usable images', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (997, '1vem8p1', 'Movies that are either centered around dark secrets, or involves stalkers?', 'Movies that are either centered around dark secrets, or involves stalkers?', 'Hi guys! are there any really tense movies that have stalkers? or maybe some horror movies that are kind of centered around anonymity? for example when a stranger calls. If so, please name them! ', 'Extension-Pretniss', 1785782912, '/r/MoviesThatFeelLike/comments/1vem8p1/movies_that_are_either_centered_around_dark/', 'https://www.reddit.com/gallery/1vem8p1', 'MoviesThatFeelLike', 'Tense, paranoid stories about stalkers and hidden dark secrets.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (998, '1veo8m9', 'Silence of the Lambs', 'Silence of the Lambs', 'Silence of the Lambs is a old time favorite, but lets face it, way hollywood is going, doubt they can ever make a better remake of it. ', 'USPgaming', 1785787281, '/r/MoviesThatFeelLike/comments/1veo8m9/silence_of_the_lambs/', 'https://v.redd.it/hjswxi5o40gh1', 'MoviesThatFeelLike', 'A nostalgic appreciation for classic psychological thrillers, paired with skepticism toward modern Hollywood remakes.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (999, '1veqpr4', 'like a song and photos', 'House of the Rising Sun and photos', 'Likes House of the Rising Sun - The Animals vibe

https://open.spotify.com/track/4mn2kNTqiGLwaUR8JdhJ1l?si=n\_JAVGl0Q36FeZOzqxeqxw&utm\_source=copy-link&sci=spotify%3Acard-config%3A6CsV4EjcpHh22DJ6jdbnPC', 'koyunsuyubardaga', 1785792822, '/r/MoviesThatFeelLike/comments/1veqpr4/like_a_song_and_photos/', 'https://www.reddit.com/gallery/1veqpr4', 'MoviesThatFeelLike', 'A haunting, sun-scorched western panorama with a melancholic folk ballad soul.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1000, '1ver49m', 'Looking for something to watch with this vibe', '', 'This looks like AI but I am looking for a tv show to watch has this vibe and type of characters/ambiance

This is a very general request so I am open to any genre

I am looking for the same aesthetics ', 'jira12345', 1785793779, '/r/MoviesThatFeelLike/comments/1ver49m/looking_for_something_to_watch_with_this_vibe/', 'https://www.reddit.com/gallery/1ver49m', 'MoviesThatFeelLike', 'Sleek, neon-drenched cityscapes with stylish animated characters and a noirish, futuristic atmosphere.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1001, '1ver95v', 'Best romance movies that you have seen', '', 'Prefer underrated ', 'Character-Bat-7397', 1785794089, '/r/MoviesThatFeelLike/comments/1ver95v/best_romance_movies_that_you_have_seen/', '/r/MovieRecommendations/comments/1ver8iv/best_romance_movies_that_you_have_seen/', 'MoviesThatFeelLike', 'Seeking underrated romantic gems.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1002, '1vermvk', 'Movies that feel like The White Lotus s1 if it was more wholesome/less unsettling', '', '', 'nuyaray', 1785794968, '/r/MoviesThatFeelLike/comments/1vermvk/movies_that_feel_like_the_white_lotus_s1_if_it/', 'https://www.reddit.com/gallery/1vermvk', 'MoviesThatFeelLike', 'Wholesome tropical vacation vibes with beautiful ocean scenery, personal growth, and lighthearted comedy.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1003, '1ves48c', 'Movies where friends realize that one of them is sadistic/going mad with power', 'Movies where friends realize that one of them is sadistic/going mad with power', 'Doesn''t have to be a friend group and it can also be through external means like possession or something idk', 'allisforgivenbutme', 1785796141, '/r/MoviesThatFeelLike/comments/1ves48c/movies_where_friends_realize_that_one_of_them_is/', 'https://www.reddit.com/gallery/1ves48c', 'MoviesThatFeelLike', 'Power corrupting once-close bonds.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1004, '1ves6sm', 'Movies/documentaries/cartoons that feel like an 80s African trip with best friends', '', 'Inspiration: a little of vaporwave, Africa by TOTO, late 70s-80s photo books, 80s'' adventure/travelling vibes, feeling of a global connection by traveling and Men at work'' songs such as "who can it be now" and "Down under"', 'IconWave_1985', 1785796316, '/r/MoviesThatFeelLike/comments/1ves6sm/moviesdocumentariescartoons_that_feel_like_an_80s/', 'https://www.reddit.com/gallery/1ves6sm', 'MoviesThatFeelLike', 'A nostalgic, vaporwave-tinged African adventure evoking the carefree spirit of 80s travel and global connection.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1005, '1vet7an', 'Anything similar?', '', '', 'BenjyYahu', 1785798839, '/r/MoviesThatFeelLike/comments/1vet7an/anything_similar/', 'https://i.redd.it/p1su57pss8hh1.gif', 'MoviesThatFeelLike', 'Over-the-top, cheesy, dumb blockbuster fun.', 'publishable', NULL, NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1006, '1vet9c3', 'Any Film Antagonists Like Judge Holden in BLOOD MERIDIAN?', '', '', 'MissMayDoesNotExist', 1785798982, '/r/MoviesThatFeelLike/comments/1vet9c3/any_film_antagonists_like_judge_holden_in_blood/', '/r/classicliterature/comments/1vet5hr/any_film_antagonists_like_judge_holden_in_blood/', 'MoviesThatFeelLike', 'A dark, mythic, intellectual evil akin to Judge Holden.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1007, '1vetbda', 'Movies with Antagonists like Judge Holden in BLOOD MERIDIAN', '', 'Cinema Antagonists who embody a pure evil at the heart of cultured Western Civilization. One of the closest I can think of is Alex in A CLOCKWORK ORANGE (also a book character, of course, though that character eventually considers redemption): intelligent, cultured, and downright evil — but unlike the Judge, Alex isn’t all powerful and is ultimately vulnerable to the indifferent evil of state power — Holden somehow seems to be above it all, and Will Never Die. BLUE VELVET’s Frank Booth also gives me The Judge vibes, but his evil and power trips seem to come from a deeply wounded and powerless place, so again, doesn’t quite fit. Curious to hear what you all think!
Will be cross posting this in film and literature subreddits to see what each community thinks', 'MissMayDoesNotExist', 1785799121, '/r/MoviesThatFeelLike/comments/1vetbda/movies_with_antagonists_like_judge_holden_in/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vetbda/movies_with_antagonists_like_judge_holden_in/', 'MoviesThatFeelLike', 'A chilling exploration of intellectual, absolute evil, often in western or crime settings.', 'skipped', 'no usable images', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1008, '1vetdte', 'Movies about slackers please!', '', 'I really want a film about a slacker who kinda does nothing with their life (bonus points if not a comedy) ', 'Fun_Hope_8319', 1785799291, '/r/MoviesThatFeelLike/comments/1vetdte/movies_about_slackers_please/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vetdte/movies_about_slackers_please/', 'MoviesThatFeelLike', 'Aimless and laid-back, capturing the disaffected yet chill lifestyle of slackers.', 'skipped', 'no usable images', NULL, '2026-08-04 03:20:13', '2026-08-04 03:20:13');
