-- 0076_seed_20260807T033931Z_01_posts.sql: data seed from pipeline:load run.
-- Generated:  2026-08-07T03:39:39.328526+00:00
-- Run started: 2026-08-07T03:39:31.969561+00:00
-- Source: data/working/load manifest from this run.
--
-- Idempotent: every INSERT is INSERT OR IGNORE, keyed by the
-- table's natural unique constraint.  Wrangler's migration
-- tracking normally prevents re-apply; the OR IGNORE is
-- defense in depth for partial / interrupted re-runs.
--
-- Chunk: 01_posts (1/5)
-- Tables: imported_vibe_posts.
-- Pipeline-state tables (processing_runs, pipeline_artifacts)
-- are intentionally excluded — they're per-run bookkeeping.

INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1156, '1uocdr4', 'A world of illusions and amnesia. The prisoners cherish their shackles.', '', '', 'Ok-Seat-2108', 1783282796, '/r/MoviesThatFeelLike/comments/1uocdr4/a_world_of_illusions_and_amnesia_the_prisoners/', 'https://www.reddit.com/gallery/1uocdr4', 'MoviesThatFeelLike', 'A mind-bending descent into worlds of illusion, control, and lost memory.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1157, '1uof9o9', 'what are some movies or yt series that feel like this?', '', 'I’ve already seen Sinister and The Mandela Catalogue.', 'weepingparis', 1783289977, '/r/MoviesThatFeelLike/comments/1uof9o9/what_are_some_movies_or_yt_series_that_feel_like/', 'https://www.reddit.com/gallery/1uof9o9', 'MoviesThatFeelLike', 'Unsettling analog horror and found-footage dread.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1158, '1uofgb8', 'Movies that feel like this?', '', '', 'premegoodeats', 1783290429, '/r/MoviesThatFeelLike/comments/1uofgb8/movies_that_feel_like_this/', 'https://i.redd.it/h1g0wbi0mhbh1.jpeg', 'MoviesThatFeelLike', 'Dark, foggy Victorian streets filled with Gothic mystery and horror.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1159, '1uoh8ih', 'What movie changed the way you see life even a little? Could be deep, emotional, disturbing, inspiring whatever?', 'What movie changed the way you see life even a little? Could be deep, emotional, disturbing, inspiring whatever?', '[deleted]', '[deleted]', 1783295000, '/r/MoviesThatFeelLike/comments/1uoh8ih/what_movie_changed_the_way_you_see_life_even_a/', '', 'MoviesThatFeelLike', 'Seeking films that offer a profound shift in perspective', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1160, '1uoh8wj', 'What movie changed the way you see life even a little? Could be deep, emotional, disturbing, inspiring whatever?', 'What movie changed the way you see life even a little? Could be deep, emotional, disturbing, inspiring whatever?', '', 'Parking_Toe4793', 1783295029, '/r/MoviesThatFeelLike/comments/1uoh8wj/what_movie_changed_the_way_you_see_life_even_a/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uoh8wj/what_movie_changed_the_way_you_see_life_even_a/', 'MoviesThatFeelLike', 'A profound and eclectic collection of films that challenge perspectives, evoke deep emotions, and inspire reflection on life''s meaning.', 'skipped', 'no usable images', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1161, '1uohsig', 'Evil corporations', 'Evil corporations', '[deleted]', '[deleted]', 1783296434, '/r/MoviesThatFeelLike/comments/1uohsig/evil_corporations/', '', 'MoviesThatFeelLike', 'menacing corporate dystopia', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1162, '1uoie3n', 'Which is your favourite movie ?', '', '', 'Harry3000000', 1783298047, '/r/MoviesThatFeelLike/comments/1uoie3n/which_is_your_favourite_movie/', '/r/AskReddit/comments/1uoa6ti/which_is_your_favourite_movie/', 'MoviesThatFeelLike', 'Curious inquiry into favorites', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1163, '1uoj1iu', 'Shows and movies and give the same vibe as house of the rising sun by the animals?', '', '', 'moon_rain06', 1783299856, '/r/MoviesThatFeelLike/comments/1uoj1iu/shows_and_movies_and_give_the_same_vibe_as_house/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uoj1iu/shows_and_movies_and_give_the_same_vibe_as_house/', 'MoviesThatFeelLike', 'Haunting, dusty, blues-infused Americana with an air of doomed fate and seedy melancholy.', 'skipped', 'no usable images', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1164, '1uoj90r', 'What film would you say has the best use of color for expressing both emotion and POV throughout?', 'What film would you say has the best use of color for expressing both emotion and POV throughout?', 'I’ve reached Hero for the 100th time and I am still enraptured by the use of color to visually convey the POV to the audience. What movie would you recommend to someone along this same vein?', 'JoyBlade-JanAug8082', 1783300471, '/r/MoviesThatFeelLike/comments/1uoj90r/what_film_would_you_say_has_the_best_use_of_color/', '/r/AskReddit/comments/1uoj7wq/what_film_would_you_say_has_the_best_use_of_color/', 'MoviesThatFeelLike', 'visually expressive, emotion-driven use of color', 'skipped', 'no usable images', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1165, '1uojk6v', 'Movies that feel like this. Particularly within crime genre (PI, detective etc.). Can be animated or live action', 'Movies that feel like this. Particularly within crime genre (PI, detective etc.). Can be animated or live action', 'I have been listening to a lot of Jazz noir lately, and feel like a movie that fits the genre would be interesting. Thanks for suggestions ', 'Robbie292', 1783301396, '/r/MoviesThatFeelLike/comments/1uojk6v/movies_that_feel_like_this_particularly_within/', 'https://www.reddit.com/gallery/1uojk6v', 'MoviesThatFeelLike', 'Moody detective noir infused with jazz, rain-soaked city streets, and shadowy intrigue.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1166, '1uok6w6', '[meta] Half of the posts on this sub are of AI-generated pictures. Any one else feel like they’re doing free data training by commenting?', 'Half of the posts on this sub are of AI-generated pictures. Any one else feel like they’re doing free data training by commenting?', '', 'itmfg', 1783303245, '/r/MoviesThatFeelLike/comments/1uok6w6/meta_half_of_the_posts_on_this_sub_are_of/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uok6w6/meta_half_of_the_posts_on_this_sub_are_of/', 'MoviesThatFeelLike', 'An uneasy realization of being unwitting participants in AI training, echoing a pervasive digital disillusionment.', 'skipped', 'no usable images', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1167, '1uokn42', 'Don’t pout, darling. It’s only the end, and look how beautiful it is.', 'Don’t pout, darling. It’s only the end, and look how beautiful it is.', 'Borrowing this one from r/SongsThatFeelLikeThis. I know it’s a lot of slides and there is a lot going on but I’d love to find some material that will allow me to immerse myself in this setting! ', 'GreenChiliGronk', 1783304573, '/r/MoviesThatFeelLike/comments/1uokn42/dont_pout_darling_its_only_the_end_and_look_how/', 'https://www.reddit.com/gallery/1uoe5a3', 'MoviesThatFeelLike', 'Melancholic beauty at the end of the world.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1168, '1uolc4n', 'Japanese movies - small village forest horror vibe', 'Japanese movies small village forest horror vibe', 'Hello everyone

Looking for Japanese specifically, max Asian movies 

That feel like this vibes

Rural, small towns, forest

Preferably horror but open to any style', 'daweasel27', 1783306734, '/r/MoviesThatFeelLike/comments/1uolc4n/japanese_movies_small_village_forest_horror_vibe/', 'https://www.reddit.com/gallery/1uolc4n', 'MoviesThatFeelLike', 'Eerie rural isolation with folkloric forest horror in small Japanese villages.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1169, '1uolm9g', 'Movies like this', 'Movies like this', '', 'Idek163', 1783307578, '/r/MoviesThatFeelLike/comments/1uolm9g/movies_like_this/', 'https://www.reddit.com/gallery/1uolm9g', 'MoviesThatFeelLike', 'Dreamy, nostalgic romance with a touch of fantasy and retro glam.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1170, '1uomz0i', 'Movies that feel like a fever dream?', 'Movies that feel like a fever dream?', '', 'Ancient_Win_2837', 1783311523, '/r/MoviesThatFeelLike/comments/1uomz0i/movies_that_feel_like_a_fever_dream/', 'https://i.redd.it/uiz1eiiqcjbh1.jpeg', 'MoviesThatFeelLike', 'A surreal and disorienting cinematic experience that blurs the line between reality and nightmare, leaving you feeling unsettled and consumed by a lingering sense of dreamlike dread.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1171, '1uoncxu', 'I fused this glass fish bone spoon rest', '', '', 'CrispyCozy', 1783312752, '/r/MoviesThatFeelLike/comments/1uoncxu/i_fused_this_glass_fish_bone_spoon_rest/', 'https://www.reddit.com/gallery/1uk6xi9', 'MoviesThatFeelLike', 'Darkly whimsical underwater melancholy, where the macabre meets the beautiful.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1172, '1uonen6', 'Movies or TV Shows like Widow''s Bay?', 'Movies or TV Shows like Widow''s Bay', '', 'TomorrowSilent1233', 1783312903, '/r/MoviesThatFeelLike/comments/1uonen6/movies_or_tv_shows_like_widows_bay/', 'https://i.redd.it/dt8y0yttgjbh1.jpeg', 'MoviesThatFeelLike', 'A small-town island community mixing quirky humor with creeping supernatural dread, where eccentric locals face uncanny mysteries.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1173, '1uonzuc', 'movies that feel like this album', '', '', 'Dip_Shit289', 1783314789, '/r/MoviesThatFeelLike/comments/1uonzuc/movies_that_feel_like_this_album/', 'https://i.redd.it/rw3vl93gmjbh1.png', 'MoviesThatFeelLike', 'Dissonant, intense, and suffocating exploration of alienation and despair.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1174, '1uoodye', 'Movies like Undertone', 'Movies like Undertone', '', 'Flashy_Notice_1575', 1783316087, '/r/MoviesThatFeelLike/comments/1uoodye/movies_like_undertone/', '/r/MovieRecommendations/comments/1uoo4fu/movies_like_undertone/', 'MoviesThatFeelLike', 'Psychological horror with creeping dread and mind-bending terror.', 'skipped', 'no usable images', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1175, '1uopo0l', 'If you ever feel like watching the obscure movie or jamming to cool music....', 'If you ever feel like watching the obscure movie or jamming to cool music', 'Hi y''all, what up doe? I got a YouTube channel devoted to entertainment & films. This is my 2nd posting at Reddit. Check it out & comment, it''s called **Forrest Green III''s Films** and here''s a link to a link: [movies & music FG III thinks U ought to get in](https://www.reddit.com/r/anything/comments/1ugbxxf/see_my_youtube_channel_guys/). 1st up, is *La Jetée* by Chris Marker, which is composed almost completely of photographic stills. So, stream & like I like to say here live: ENJOY.

Pleased to introduce myself -- I''m out.', 'Cav_01', 1783320496, '/r/MoviesThatFeelLike/comments/1uopo0l/if_you_ever_feel_like_watching_the_obscure_movie/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uopo0l/if_you_ever_feel_like_watching_the_obscure_movie/', 'MoviesThatFeelLike', 'Obscure cinematic gems and cool music curated by an enthusiastic host.', 'skipped', 'no usable images', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1176, '1uopt9x', 'Like The Birthday Massacre''s visuals', 'Like The Birthday Massacre''s visuals', '', 'AlexSomething789', 1783320993, '/r/MoviesThatFeelLike/comments/1uopt9x/like_the_birthday_massacres_visuals/', 'https://www.reddit.com/gallery/1uopt9x', 'MoviesThatFeelLike', 'Dreamy and darkly whimsical nostalgia evoking childhood fairy tales with a gothic edge.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1177, '1uoqryg', 'Movies that feel like chemical brothers - believe', 'Movies that feel like chemical brothers - believe', '', 'DE_X_IY', 1783324400, '/r/MoviesThatFeelLike/comments/1uoqryg/movies_that_feel_like_chemical_brothers_believe/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uoqryg/movies_that_feel_like_chemical_brothers_believe/', 'MoviesThatFeelLike', 'Industrial-tinged paranoia and fractured reality.', 'skipped', 'no usable images', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1178, '1uou6sj', 'Movies or tv shows that feels like this picture , don''t know how to describe this.', 'Movies or tv shows that feels like this picture , don''t know how to describe this.', 'https://preview.redd.it/j3gb0nf8dlbh1.png?width=1920&format=png&auto=webp&s=296da2d215c51128169622d32ce8b04949f3234b

', 'BreathNational1747', 1783335987, '/r/MoviesThatFeelLike/comments/1uou6sj/movies_or_tv_shows_that_feels_like_this_picture/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uou6sj/movies_or_tv_shows_that_feels_like_this_picture/', 'MoviesThatFeelLike', '', 'skipped', 'no usable images; no vibe summary; no enriched recommendation matches', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1179, '1uou977', 'Movies or tv shows that feels like this picture , don''t know how to describe this.', 'Movies or tv shows that feels like this picture', '', 'BreathNational1747', 1783336190, '/r/MoviesThatFeelLike/comments/1uou977/movies_or_tv_shows_that_feels_like_this_picture/', 'https://i.redd.it/qgbl09f2elbh1.png', 'MoviesThatFeelLike', 'A haunting, poetic desolation with gothic undertones.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1180, '1uous33', 'Movies that have that southwestern Americana feel to them?', 'Movies that have that southwestern Americana feel to them?', '', 'Original-Tax1392', 1783337772, '/r/MoviesThatFeelLike/comments/1uous33/movies_that_have_that_southwestern_americana_feel/', 'https://i.redd.it/4gskspdsilbh1.jpeg', 'MoviesThatFeelLike', 'Dusty highways, desert motels, and small-town Americana under endless skies.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1181, '1uox97w', 'Instead of songs, any movies that feel like this?', 'Instead of songs, any movies that feel like this?', '', 'Lukotheduko', 1783344210, '/r/MoviesThatFeelLike/comments/1uox97w/instead_of_songs_any_movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1uomcs5', 'MoviesThatFeelLike', 'Lonely urban nightscapes and introspective solitude, bathed in neon glow.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1182, '1uoysv7', 'Girl sleepover and perfect life, inspo: the hot chick', '', '', 'dontaskmeaboutmath', 1783347779, '/r/MoviesThatFeelLike/comments/1uoysv7/girl_sleepover_and_perfect_life_inspo_the_hot/', 'https://www.reddit.com/gallery/1uoysv7', 'MoviesThatFeelLike', 'A nostalgic, feel-good slumber party vibe celebrating early 2000s teen movies and female friendship.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1183, '1up05sc', 'Movies/series that feel like this', 'Movies/series that feel like this', '', 'Grainrain19', 1783350751, '/r/MoviesThatFeelLike/comments/1up05sc/moviesseries_that_feel_like_this/', 'https://www.reddit.com/gallery/1up05sc', 'MoviesThatFeelLike', 'Surreal small-town mystery with dark undercurrents, misty Pacific Northwest forests, and retro Americana', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1184, '1up4kin', 'Pls a movies look this', 'Pls a movies look this', '', 'Markstevenjacky', 1783359938, '/r/MoviesThatFeelLike/comments/1up4kin/pls_a_movies_look_this/', 'https://i.redd.it/by94yz1pcnbh1.jpeg', 'MoviesThatFeelLike', 'Surreal expressionist fantasy with theatrical sets and whimsical dread.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1185, '1up6ez4', 'Movies that feel like: World ending event and one plan to save the world', 'Movies that feel like: World ending event and one plan to save the world', '', 'Unlucky_Image4526', 1783363688, '/r/MoviesThatFeelLike/comments/1up6ez4/movies_that_feel_like_world_ending_event_and_one/', 'https://www.reddit.com/gallery/1up6ez4', 'MoviesThatFeelLike', 'Humanity''s last-ditch missions to avert global catastrophe', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1186, '1up83jr', 'Movie Recommendations App - Qouch Potato Version 2.0', 'Movie Recommendations App - Qouch Potato Version 2.0', '', 'data_guy42', 1783367296, '/r/MoviesThatFeelLike/comments/1up83jr/movie_recommendations_app_qouch_potato_version_20/', 'https://www.reddit.com/gallery/1uoobgu', 'MoviesThatFeelLike', 'Couch potato cozy movie night', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1187, '1up97lh', 'Here''s one that may stump you (can be any form of media, movie, tv, game, etc)', '', 'https://preview.redd.it/dipfr9355obh1.png?width=1200&format=png&auto=webp&s=2529795f9e51f5a0cdb22c22408633c963269651

https://preview.redd.it/u3zh72o85obh1.png?width=736&format=png&auto=webp&s=26e6a8fe2670ca77930a85847d094ff7176e131e

https://preview.redd.it/h646wvld5obh1.png?width=1199&format=png&auto=webp&s=5bfb0a220adcb194e0a9bcf9a365f9f31a334f1e

https://preview.redd.it/9mwy7zzd5obh1.png?width=1199&format=png&auto=webp&s=96c5920e59e00b7488541400ce4bd02e56f8460e

https://preview.redd.it/kpb0jg8f5obh1.png?width=1200&format=png&auto=webp&s=7dcd2c4281e21b731333a9a3b588ac684861cebd

https://preview.redd.it/ihkbwkbk5obh1.png?width=780&format=png&auto=webp&s=24ba479812506de18085f7dee3dc5e19712b59e2

', 'IVEBEENBANNED4TIMESx', 1783369711, '/r/MoviesThatFeelLike/comments/1up97lh/heres_one_that_may_stump_you_can_be_any_form_of/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1up97lh/heres_one_that_may_stump_you_can_be_any_form_of/', 'MoviesThatFeelLike', 'Brutalist architecture and high-tech stealth aesthetics.', 'skipped', 'no usable images', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1188, '1up98wg', 'A War Drama Romance Story.. Maybe full of action and thrill too!!', 'War Drama Romance Story with Action and Thrill', '', 'Curiosity_Lovers', 1783369796, '/r/MoviesThatFeelLike/comments/1up98wg/a_war_drama_romance_story_maybe_full_of_action/', 'https://www.reddit.com/gallery/1up98wg', 'MoviesThatFeelLike', 'A sweeping wartime epic blending intense battles with passionate romance.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1189, '1up9owl', 'The imposing inanimate? I watched penda''s fen and I couldn''t get these scenes in particular out of my head. The appearance of the statues really made me feel something, they look so out of place almost personal in a way (really fitting for the movie, very great overall).', 'The imposing inanimate? I watched penda''s fen and I couldn''t get these scenes in particular out of my head. The appearance of the statues really made me feel something, they look so out of place almost personal in a way (really fitting for the movie, very great overall).', 'https://preview.redd.it/mz5surrc8obh1.png?width=638&format=png&auto=webp&s=6ed05b7a98a5e1b86bf5b034d0d0a083f56770cc

https://preview.redd.it/jvjijqgf8obh1.png?width=600&format=png&auto=webp&s=5e4da9a37fbb782d3ea53734118d186fe57e57cd

', 'IVEBEENBANNED4TIMESx', 1783370797, '/r/MoviesThatFeelLike/comments/1up9owl/the_imposing_inanimate_i_watched_pendas_fen_and_i/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1up9owl/the_imposing_inanimate_i_watched_pendas_fen_and_i/', 'MoviesThatFeelLike', 'Eerie, imposing statues in a pastoral landscape evoke a mysterious and personal presence.', 'skipped', 'no usable images', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1190, '1up9peq', 'Movies that match this care-free, Summer vibe', '', '', 'SpaceTranquil', 1783370828, '/r/MoviesThatFeelLike/comments/1up9peq/movies_that_match_this_carefree_summer_vibe/', 'https://www.reddit.com/gallery/1up9peq', 'MoviesThatFeelLike', 'Sun-drenched, carefree summer nostalgia', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1191, '1upakr8', 'Movies that feel like Time out of mind by Bob Dylan?', '', '', 'Jeef_1st', 1783372768, '/r/MoviesThatFeelLike/comments/1upakr8/movies_that_feel_like_time_out_of_mind_by_bob/', 'https://i.redd.it/6v6h6ljueobh1.jpeg', 'MoviesThatFeelLike', 'Weary, atmospheric Americana with a bluesy, introspective mood.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1192, '1upb48y', 'reunion on a desert planet', 'reunion on a desert planet', 'This scene from Ahsoka reminds me of something else but can''t put my finger on it! Where a character was lost/stranded and then found living among non human creatures...?', 'daisypeach94', 1783373980, '/r/MoviesThatFeelLike/comments/1upb48y/reunion_on_a_desert_planet/', 'https://www.reddit.com/gallery/1upb48y', 'MoviesThatFeelLike', 'A lone wanderer stranded on an alien desert world, taken in by strange creatures.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1193, '1upba70', 'This', '', 'Kun Lan from Killer7 ', 'Jellypathicdream', 1783374353, '/r/MoviesThatFeelLike/comments/1upba70/this/', 'https://i.redd.it/6xwcm79kjobh1.jpeg', 'MoviesThatFeelLike', 'A hallucinatory blend of psychedelic visuals and brutal violence.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1194, '1upedtg', 'Movies to watch after a breakup?', 'Movies to watch after a breakup?', '', 'siivenn', 1783381553, '/r/MoviesThatFeelLike/comments/1upedtg/movies_to_watch_after_a_breakup/', 'https://i.redd.it/nb6c1rzy4pbh1.jpeg', 'MoviesThatFeelLike', 'bittersweet catharsis', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1195, '1upfbz2', 'VOICEMAILS FROM ISABEL 2026', 'VOICEMAILS FROM ISABEL 2026', '', 'Dry_Ratio4614', 1783383946, '/r/MoviesThatFeelLike/comments/1upfbz2/voicemails_from_isabel_2026/', '/r/romancemovies/comments/1upfaqw/voicemails_from_isabel_2026/', 'MoviesThatFeelLike', 'Eerie digital nostalgia from the near future', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1196, '1upg0g6', 'Keeping up with the Joneses', 'Keeping up with the Joneses', 'I really enjoy tv shows and movies where there’s a plot (or subplot) around losing financial status, but trying to maintain the same lifestyle. But the protagonist is still trying to keep up with the joneses. Card gets declined while eating out, headmaster calls about the bounced check for little Timmy’s private school. You name it.

I’ve recently enjoyed Your Friends and Neighbors on Apple TV, Fun with Dick and Jane, and even desperate housewives. 

Any other movies where there’s is absolutely no compromise on their current lifestyle? Not willing to avoid lifestyle creep. They’re going to ride it out and find a way?', 'harrisce44', 1783385776, '/r/MoviesThatFeelLike/comments/1upg0g6/keeping_up_with_the_joneses/', 'https://www.reddit.com/gallery/1upg0g6', 'MoviesThatFeelLike', 'Desperately clinging to a luxurious facade while secretly broke.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1197, '1upgdsc', 'Movies like this', 'Movies like this', '', 'BatRevolutionary3064', 1783386751, '/r/MoviesThatFeelLike/comments/1upgdsc/movies_like_this/', 'https://www.reddit.com/gallery/1upgdsc', 'MoviesThatFeelLike', 'Nostalgic neon-lit diners and late-night urban hangouts, blending retro cool with a touch of loneliness.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1198, '1upgjls', 'Movies that feature a Marian woman/figure', 'Movies that feature a Marian woman/figure', 'Character and films listed in the images:

* **Lady Galadriel** \- *The Lord of the Rings: The Fellowship of the Ring* (2001)
* **Lady Galadriel** \- *The Lord of the Rings: The Return of the King* (2003)
* **Lady Galadriel** \- *The Hobbit: An Unexpected Journey* (2012)
* **Lady Galadriel** \- *The Hobbit: The Battle of the Five Armies* (2014)
* **Lady Jessica** \- *Dune: Part Two* (2024)
* **Blue Fairy** \- *A.I. Artificial Intelligence* (2001)
* **Blue Fairy** \- *Pinocchio* (2002)
* **Fairy with Turquoise Hair** \- *Pinocchio* (2019)', 'Lissandra_Freljord', 1783387199, '/r/MoviesThatFeelLike/comments/1upgjls/movies_that_feature_a_marian_womanfigure/', 'https://www.reddit.com/gallery/1upgjls', 'MoviesThatFeelLike', 'Luminous and reverent, with an ethereal, saintly atmosphere.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1199, '1uphl55', 'Movies that feel like The Evelyn Game (Recent Horror videogame).', 'Movies that feel like The Evelyn Game (Recent Horror videogame)', 'I watched the entire videogame and I send this direct link to the gameplay that was surprising me and well, I want to watch horror, suspense or similar movies with this horror game.', 'SmallEconomics6173', 1783390029, '/r/MoviesThatFeelLike/comments/1uphl55/movies_that_feel_like_the_evelyn_game_recent/', 'https://youtu.be/_oS-l1xmeAo?si=74hjipTQHyAEZ0GU', 'MoviesThatFeelLike', 'Psychological horror and suspense akin to a modern horror game.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1200, '1upj18s', 'Show me what you gottt', '', '', 'RyanTheBlockhead', 1783393973, '/r/MoviesThatFeelLike/comments/1upj18s/show_me_what_you_gottt/', 'https://www.reddit.com/gallery/1upj18s', 'MoviesThatFeelLike', 'An eerie, blue-drenched dreamscape blending horror, neon-noir, and surreal dread.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1201, '1upmnsm', 'Recommend a movie.', 'Recommend a movie.', '', 's7kyz', 1783405149, '/r/MoviesThatFeelLike/comments/1upmnsm/recommend_a_movie/', 'https://i.redd.it/twghysu43rbh1.jpeg', 'MoviesThatFeelLike', 'Cozy late-night laptop movie session with snacks and tea.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1202, '1upnqga', 'discovering cosmic signals/puzzling universe mysteries', '', 'If I had to be specific -

Movies about an academic''s discovery of strange cosmic signals or baffling universe mysteries followed by an obsessive and surreal investigation into them.

Media matching this vibe -

Movies : 

Contact (1997)

Cosmos(2019) 

Vast of the night(2019) 

Clara(2018) 

Shows : Three Body Problem

Books :

A for Andromeda by Fred Hoyle & John Elliot. 

Comet Halley by Fred Hoyle

Three Body Problem Triology

Audio Show:

Observable Radio', 'PastEagle8722', 1783408732, '/r/MoviesThatFeelLike/comments/1upnqga/discovering_cosmic_signalspuzzling_universe/', 'https://www.reddit.com/gallery/1upnqga', 'MoviesThatFeelLike', 'Obsessive, surreal investigation into cosmic mysteries.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1203, '1upsv5i', 'Movies with this vibe?', 'Movies with this vibe?', '', 'SketchyMikey', 1783425336, '/r/MoviesThatFeelLike/comments/1upsv5i/movies_with_this_vibe/', 'https://www.reddit.com/gallery/1upsv5i', 'MoviesThatFeelLike', 'Neon-drenched tactical action with intense, gritty, and stylized violence', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1204, '1upv7rs', 'Movies that feel like this', 'Movies that feel like this', '', 'pinkdragapult', 1783431107, '/r/MoviesThatFeelLike/comments/1upv7rs/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1upv7rs', 'MoviesThatFeelLike', 'Atmosphere unspecified.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1205, '1upxrwd', 'Movies about secret Soviet military tech/science experiments', '', 'Open to shows and games too. Looking for something about secret cold war-era cutting edge tech, especially if it goes wrong, like some sort of combination of Chernobyl and Tales from the Loop.', 'ObamiumCrystalHunter', 1783436713, '/r/MoviesThatFeelLike/comments/1upxrwd/movies_about_secret_soviet_military_techscience/', 'https://www.reddit.com/gallery/1upxrwd', 'MoviesThatFeelLike', 'Paranoid Cold War dread meets inexplicable Soviet experiments, blending industrial decay with sci-fi horror.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1206, '1uq4qwo', 'Want to see a crazy psychopath thriller movie.. maybe with some detective vibes too!! 👀', 'Want to see a crazy psychopath thriller movie.. maybe with some detective vibes too!! 👀', '', 'Curiosity_Lovers', 1783451313, '/r/MoviesThatFeelLike/comments/1uq4qwo/want_to_see_a_crazy_psychopath_thriller_movie/', 'https://www.reddit.com/gallery/1uq4qwo', 'MoviesThatFeelLike', 'Unsettling and intense psychopath thrillers with a detective edge.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1207, '1uqdai0', 'Thrillers/horrors/dramas that feel like...', '', 'Think suburban everyday horrors. Serial killers, people you don''t suspect are evil living next door, the terror of the mundane, the casual cruelty of the every day. 

Think Virgin Suicides meets Little Children meets Widows Bay meets American Beauty meets Fright Nite (1985)', 'oddbutnice', 1783470736, '/r/MoviesThatFeelLike/comments/1uqdai0/thrillershorrorsdramas_that_feel_like/', 'https://www.reddit.com/gallery/1uqdai0', 'MoviesThatFeelLike', 'Suburban domestic dread and the terror of mundane life, where evil hides behind picket fences and neighborly smiles.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1208, '1uqfczw', 'Romances that are just two psychopaths matching each others freak', 'Romances that are just two psychopaths matching each others freak', '', 'GrapeConsistent3471', 1783476352, '/r/MoviesThatFeelLike/comments/1uqfczw/romances_that_are_just_two_psychopaths_matching/', 'https://i.redd.it/7hzpopzuywbh1.jpeg', 'MoviesThatFeelLike', 'An unhinged whirlwind of violent passion and darkly comic love between two equally deranged souls.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1209, '1uqgsza', 'Movies that feel like a 1950s house wife’s fever dream', 'Movies that feel like a 1950s house wife’s fever dream', 'I’ve already seen The Stepford Wives and Don’t Worry Darling ', 'Razurrkat', 1783480427, '/r/MoviesThatFeelLike/comments/1uqgsza/movies_that_feel_like_a_1950s_house_wifes_fever/', 'https://www.reddit.com/gallery/1uqgsza', 'MoviesThatFeelLike', 'Lurid domestic surrealism with undercurrents of paranoia and repression.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1210, '1uqqyhf', 'Very pink, coming of age', 'Very pink, coming of age', '', 'pinkdragapult', 1783512935, '/r/MoviesThatFeelLike/comments/1uqqyhf/very_pink_coming_of_age/', 'https://www.reddit.com/gallery/1uqqyhf', 'MoviesThatFeelLike', 'A playful, nostalgic, and unabashedly pink coming-of-age atmosphere.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1211, '1urxnwi', 'Summer movies with central mystery or intrigue', 'Summer movies with central mystery or intrigue', 'Teenagers and lakes, steamy hot intrigues, summer mysteries, high tensions and summer nights. ', 'fidodogstoyevsky', 1783619556, '/r/MoviesThatFeelLike/comments/1urxnwi/summer_movies_with_central_mystery_or_intrigue/', 'https://www.reddit.com/gallery/1urxnwi', 'MoviesThatFeelLike', 'Steamy hot summer intrigues and mysteries with high tensions and summer nights.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1212, '1ust1da', 'Movies that use religious imagery ?', 'Movies that use religious imagery ?', 'Im really interested in movies that use “blasphemy” like the image or characters cosplaying as certain religious characters like virgin mary (love exposure , johnny 316 , saint maud) or just the topic of it (like antichrist , nymphomaniac , antiporno) I’m really interested and need more films that do this! Thank u  ', '7xnie', 1783701920, '/r/MoviesThatFeelLike/comments/1ust1da/movies_that_use_religious_imagery/', 'https://i.redd.it/srzy6i4llfch1.jpeg', 'MoviesThatFeelLike', 'Provocative, transgressive exploration of religious iconography and blasphemy.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1213, '1uszv4r', 'movies that feel like this??', 'movies that feel like this', '', 'Limp-Act6', 1783716783, '/r/MoviesThatFeelLike/comments/1uszv4r/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1uszv4r', 'MoviesThatFeelLike', 'A surreal, psychedelic trip through lush forests and rainbow-hued cosmic distortions, where reality warps in mind-bending and often unsettling ways.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1214, '1vgq9n4', 'The Tell-Tale Heart kinda vibe', 'The Tell-Tale Heart atmosphere', 'I''ve always loved the whole vibe and atmosphere of the The Tell-Tale Heart, was curious if you guys felt like there are any movies that remind you of it', 'BackgroundMortgage91', 1785979595, '/r/MoviesThatFeelLike/comments/1vgq9n4/the_telltale_heart_kinda_vibe/', 'https://www.reddit.com/gallery/1vgq9n4', 'MoviesThatFeelLike', 'A suffocating, guilt-ridden atmosphere of creeping paranoia and psychological unraveling, reminiscent of Poe''s tale of hidden crime and haunting conscience.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1215, '1vgqeta', 'Movies that feel like Nightswimming by REM', 'Movies that feel like Nightswimming by REM', 'Other than Perks of Being a Wallflower ', 'MAGAPUNKSFUCOFF', 1785979987, '/r/MoviesThatFeelLike/comments/1vgqeta/movies_that_feel_like_nightswimming_by_rem/', 'https://i.redd.it/vvpm6c9frnhh1.png', 'MoviesThatFeelLike', 'Nostalgic and serene, evoking reflective summer night memories.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1216, '1vgrg9t', 'any other movies for this list?', 'any other movies for this list?', '', 'ohyaz', 1785982851, '/r/MoviesThatFeelLike/comments/1vgrg9t/any_other_movies_for_this_list/', 'https://i.redd.it/b0jcf35wznhh1.jpeg', 'MoviesThatFeelLike', 'dark autumn atmosphere with eerie and cozy Halloween vibes', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1217, '1vgrtj4', 'Movies that feel like this music', 'Movies that feel like this music', '', 'SputnikSenpai', 1785983868, '/r/MoviesThatFeelLike/comments/1vgrtj4/movies_that_feel_like_this_music/', 'https://youtube.com/shorts/xizo2egW0UY?is=y7Fs1LI6FE5gpc2Q', 'MoviesThatFeelLike', 'Nostalgic, lighthearted band-room humor.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1218, '1vgxt0w', 'Wanna know any feel good cozy movies .... please recommend', 'Wanna know any feel good cozy movies .... please recommend', 'just wanna know what you watch when u are having a really bad or emotional day ... i wanna know about the gems', 'Intelligent_Ask4695', 1786002980, '/r/MoviesThatFeelLike/comments/1vgxt0w/wanna_know_any_feel_good_cozy_movies_please/', 'https://i.redd.it/xp9hu93tnphh1.jpeg', 'MoviesThatFeelLike', 'Seeking warm, comforting films to lift spirits on a tough day.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1219, '1vgxzy5', 'Movies that give off these vibes.', 'Movies that give off these vibes.', '', 'quicksilverspider', 1786003656, '/r/MoviesThatFeelLike/comments/1vgxzy5/movies_that_give_off_these_vibes/', 'https://www.reddit.com/gallery/1vgxzy5', 'MoviesThatFeelLike', '', 'skipped', 'no usable images; no vibe summary; no enriched recommendation matches', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1220, '1vgytml', 'A good mecha show ,anime, movies', 'A good mecha show, anime, movies', 'I have watched transformer and Pacific rim.

I just want to see a best good story and cool mecha robots .

Just recommend me one ', 'AmanYadav19', 1786006616, '/r/MoviesThatFeelLike/comments/1vgytml/a_good_mecha_show_anime_movies/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vgytml/a_good_mecha_show_anime_movies/', 'MoviesThatFeelLike', 'Seeking thrilling mecha action with compelling stories.', 'skipped', 'no usable images', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1221, '1vh7n9s', 'Movies tha feel like vibe of american teenagers college university life', '', '', 'Aggravating_Gas_3511', 1786030521, '/r/MoviesThatFeelLike/comments/1vh7n9s/movies_tha_feel_like_vibe_of_american_teenagers/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vh7n9s/movies_tha_feel_like_vibe_of_american_teenagers/', 'MoviesThatFeelLike', 'The youthful, energetic atmosphere of American college life.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1222, '1vh87ib', 'Movies that feel like this?', '', '', 'jeezogee', 1786031737, '/r/MoviesThatFeelLike/comments/1vh87ib/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vh87ib', 'MoviesThatFeelLike', 'Whimsical journeys through starry skies and fantastical worlds.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1223, '1vh8kg8', 'Movies which gives american college university life', 'Movies which gives american college university life', '', 'Aggravating_Gas_3511', 1786032471, '/r/MoviesThatFeelLike/comments/1vh8kg8/movies_which_gives_american_college_university/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vh8kg8/movies_which_gives_american_college_university/', 'MoviesThatFeelLike', 'The vibe of American college life.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1224, '1vhejev', 'movies that feel like how sea, swallow me sounds', 'movies that feel like how sea, swallow me sounds', 'or any cocteau twins song for that matter', 'Economy_Upstairs703', 1786045372, '/r/MoviesThatFeelLike/comments/1vhejev/movies_that_feel_like_how_sea_swallow_me_sounds/', 'https://www.reddit.com/gallery/1vhejev', 'MoviesThatFeelLike', 'Dreamy, ethereal, oceanic atmosphere reminiscent of Cocteau Twins.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1225, '1vhghe9', 'I built MoodWatch a movie/show recommender that works off how you feel, not just genre. Here''s the story, and I''d love your feedback.', 'I built MoodWatch a movie/show recommender that works off how you feel, not just genre.', '', 'Alarmed-Plan-7010', 1786049765, '/r/MoviesThatFeelLike/comments/1vhghe9/i_built_moodwatch_a_movieshow_recommender_that/', 'https://moodwatch-dun.vercel.app/mood', 'MoviesThatFeelLike', 'emotion-driven cinema exploration', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1226, '1vhi4e6', 'Vintage cute witch', 'Vintage cute witch', '', 'dontaskmeaboutmath', 1786053656, '/r/MoviesThatFeelLike/comments/1vhi4e6/vintage_cute_witch/', 'https://www.reddit.com/gallery/1vhi4e6', 'MoviesThatFeelLike', 'A cozy, whimsical, and nostalgic witchy atmosphere with a charming vintage feel.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1227, '1vhjo6k', 'Can you suggest movies that feel like this', '', '', 'Unusual-Maybe-6211', 1786057520, '/r/MoviesThatFeelLike/comments/1vhjo6k/can_you_suggest_movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vhjnqz', 'MoviesThatFeelLike', 'Rain-soaked noir mystery with a haunting, melancholic atmosphere.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1228, '1vhk6za', 'They live a life so fantastic, it''s hard to really believe', '', 'I love all these movies, I''m hoping for suggestions closer to Big Fish though ', 'angry-key-smash6693', 1786058835, '/r/MoviesThatFeelLike/comments/1vhk6za/they_live_a_life_so_fantastic_its_hard_to_really/', 'https://www.reddit.com/gallery/1vhk6za', 'MoviesThatFeelLike', 'Whimsical and heartfelt tales of larger-than-life stories, blending magical realism with deep emotional resonance.', 'publishable', NULL, NULL, '2026-08-07 03:39:39', '2026-08-07 03:39:39');
