-- 0081_seed_20260808T022334Z_01_posts.sql: data seed from pipeline:load run.
-- Generated:  2026-08-08T02:23:50.030281+00:00
-- Run started: 2026-08-08T02:23:34.979708+00:00
-- Source: data/working/load manifest from this run.
--
-- Idempotent: every INSERT is INSERT OR IGNORE, keyed by the
-- table's natural unique constraint.  Wrangler's migration
-- tracking normally prevents re-apply; the OR IGNORE is
-- defense in depth for partial / interrupted re-runs.
--
-- Chunk: 01_posts (1/5)
-- Tables: imported_vibe_posts.
-- Pipeline-state tables (processing_runs, pipeline_artifacts)
-- are intentionally excluded — they're per-run bookkeeping.

INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1229, '1un3hk5', 'something you weren’t supposed to see.', 'something you weren’t supposed to see.', 'hey so i love found footage, have seen things like gonjiam, blair witch and the poughkeepsie tapes, so i’m looking for something to leave me sleepless haha. i am looking for something quite good/well made.

 lmk any suggestions! thanks : )', 'koipoi1', 1783153055, '/r/MoviesThatFeelLike/comments/1un3hk5/something_you_werent_supposed_to_see/', 'https://www.reddit.com/gallery/1un3hk5', 'MoviesThatFeelLike', 'Eerie, forbidden glimpses into unsettling secrets, captured on tape and not meant to be seen.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1230, '1un5mor', 'Movies that feel like Urban decay, homelessness, car-centric infrastructure and general anti-social behavior.', '', 'https://preview.redd.it/9rkwo1gms6bh1.png?width=800&format=png&auto=webp&s=2c636bcfe6b7934e83feee69de3c29086405282a

https://preview.redd.it/tacbpe5sw6bh1.png?width=445&format=png&auto=webp&s=eee0a9aa0cd4c093dfb33d376c9e94318cd9b31e

https://preview.redd.it/wj46w06vw6bh1.png?width=740&format=png&auto=webp&s=f6195c524c7557bad9be66ae06757b2ff2e8fae7

https://preview.redd.it/f5swv9zxw6bh1.png?width=1200&format=png&auto=webp&s=f227d29fe37657398534e9b36a39e47f88ff9fb8

', 'Efficient-Pudding177', 1783160932, '/r/MoviesThatFeelLike/comments/1un5mor/movies_that_feel_like_urban_decay_homelessness/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1un5mor/movies_that_feel_like_urban_decay_homelessness/', 'MoviesThatFeelLike', 'Bleak urban decay, homelessness, and car-centric anti-social atmosphere.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1231, '1un6eh9', 'Movies that feel like Urban decay, homelessness, car-centric infrastructure and general anti-social behavior.', 'Movies that feel like Urban decay, homelessness, car-centric infrastructure and general anti-social behavior.', '', 'Efficient-Pudding177', 1783163617, '/r/MoviesThatFeelLike/comments/1un6eh9/movies_that_feel_like_urban_decay_homelessness/', 'https://www.reddit.com/gallery/1un6eh9', 'MoviesThatFeelLike', 'Gritty, decaying urban landscapes with pervasive homelessness and anti-social behavior.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1232, '1un8hrm', 'Guy''s What''s your All time favorite Movie ? Mine is Nadiya ke Paar', 'Guys what''s your all time favorite movie? Mine is Nadiya ke Paar', '', 'AdInevitable3716', 1783170021, '/r/MoviesThatFeelLike/comments/1un8hrm/guys_whats_your_all_time_favorite_movie_mine_is/', '/r/nagpur/comments/1un7xza/guys_whats_your_all_time_favorite_movie_mine_is/', 'MoviesThatFeelLike', 'Nostalgic rural charm and simple romance.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1233, '1un9dq5', 'Movies that take a slow decent through chaos (preferrably non-horror genres)', 'Movies that take a slow descent through chaos', '1st image - Come And See (1985)

2nd image - Children of Men (2006)

3rd image - The Pianist (2002)

4th image - Hereditary (2018)

5th image - Harakiri (1962)', 'Garidur', 1783172458, '/r/MoviesThatFeelLike/comments/1un9dq5/movies_that_take_a_slow_decent_through_chaos/', 'https://www.reddit.com/gallery/1un9dq5', 'MoviesThatFeelLike', 'A slow-burn descent into overwhelming chaos and despair.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1234, '1unal8k', 'Movies that feel like Salad Fingers', 'Movies that feel like Salad Fingers', 'Looking for films that give Salad Fingers vibes. Interpret that as you wish. 🥗🖐', 'savvylee17', 1783175581, '/r/MoviesThatFeelLike/comments/1unal8k/movies_that_feel_like_salad_fingers/', 'https://www.reddit.com/gallery/1unal8k', 'MoviesThatFeelLike', 'Creepy, surreal, and darkly humorous with a handcrafted uncanniness.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1235, '1unbgur', 'A sci-fi horror that could easily work as dark synthwave cover art.', 'A sci-fi horror that could easily work as dark synthwave cover art.', '', 'ScientificBeastMode', 1783177791, '/r/MoviesThatFeelLike/comments/1unbgur/a_scifi_horror_that_could_easily_work_as_dark/', 'https://www.reddit.com/gallery/1unbgur', 'MoviesThatFeelLike', 'Neon-drenched cosmic horror and synthwave dread.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1236, '1unc1zc', 'What is the most American movie of all time?', 'What is the most American movie of all time?', '', 'SomeSortOfBrit', 1783179239, '/r/MoviesThatFeelLike/comments/1unc1zc/what_is_the_most_american_movie_of_all_time/', '/r/movies/comments/1unc1iy/what_is_the_most_american_movie_of_all_time/', 'MoviesThatFeelLike', 'A boisterous, stars-and-stripes salute to the American cinematic spirit.', 'skipped', 'no usable images', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1237, '1undh8p', 'Movies that Feel like these still shots... Quest Adventures, Going on a Journey, Being Chased through Markets, Caves, Jungles, Islands etc...', 'Movies that Feel like these still shots... Quest Adventures, Going on a Journey, Being Chased through Markets, Caves, Jungles, Islands etc...', 'https://preview.redd.it/9avuaqvop8bh1.jpg?width=1300&format=pjpg&auto=webp&s=8de6f168c633a41803a7a6c25bd80a24ef871ada

https://preview.redd.it/onvoxx8xo8bh1.jpg?width=1920&format=pjpg&auto=webp&s=fb9169c85b585e34df83dd1606cdad2eaf63357f

https://preview.redd.it/5bfhs3rxo8bh1.jpg?width=783&format=pjpg&auto=webp&s=d96962c88512625db520c811f17006e7341c3b33

https://preview.redd.it/yzgijd5yo8bh1.jpg?width=1500&format=pjpg&auto=webp&s=b8a14a4855c917ab97db269b4b805de228025a26

https://preview.redd.it/kvtj92jyo8bh1.jpg?width=1495&format=pjpg&auto=webp&s=1b3e86eac098cb320f94dd0c9ab936d86e673b04

https://preview.redd.it/xle7pogzo8bh1.jpg?width=1200&format=pjpg&auto=webp&s=836cef2fe0cdac4bc926a73fe41c2ef4f6e10a2b

https://preview.redd.it/0g1rj7ldp8bh1.jpg?width=1400&format=pjpg&auto=webp&s=55ba2f21bf458635d42f9fb5e9028d2677e9e2b5

', 'SeaAd5168', 1783182754, '/r/MoviesThatFeelLike/comments/1undh8p/movies_that_feel_like_these_still_shots_quest/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1undh8p/movies_that_feel_like_these_still_shots_quest/', 'MoviesThatFeelLike', 'An adventurous, exotic quest vibe with treasure hunts, chases through markets and jungles, and lush island settings.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1238, '1unedj7', 'Desperately need recommendations', 'Desperately need recommendations', '', 'Fit-Detective-8279', 1783184956, '/r/MoviesThatFeelLike/comments/1unedj7/desperately_need_recommendations/', '/r/MovieRecommendations/comments/1uned26/desperately_need_recommendations/', 'MoviesThatFeelLike', 'Desperate search for recommendations', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1239, '1unefhm', 'Movies or Tv Episodes That Feel Like The Last Day of School Before Winter Break', 'Movies or Tv Episodes That Feel Like The Last Day of School Before Winter Break', '', 'pixiedream095', 1783185087, '/r/MoviesThatFeelLike/comments/1unefhm/movies_or_tv_episodes_that_feel_like_the_last_day/', 'https://www.reddit.com/gallery/1unefhm', 'MoviesThatFeelLike', 'Giddy anticipation of winter break filled with cozy festive cheer and childlike excitement.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1240, '1unexzm', 'Movies like this song', 'Movies like this song', '', 'Idek163', 1783186317, '/r/MoviesThatFeelLike/comments/1unexzm/movies_like_this_song/', 'https://youtu.be/4w8D1xL_8hs?is=p3M7l29_81LEyCjC', 'MoviesThatFeelLike', 'Neon-drenched, hedonistic teenage chaos', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1241, '1ungux7', 'Best of Genre category review series', 'Best of Genre category review series', '', 'LTFiam', 1783190996, '/r/MoviesThatFeelLike/comments/1ungux7/best_of_genre_category_review_series/', '/r/FPSPodcast/comments/1ungtwn/best_of_genre_category_review_series/', 'MoviesThatFeelLike', 'Curating the pinnacle of cinema genres.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1242, '1unhl0h', 'A gore movie with lots of chasing scenes.. may include lots of action, racing or fighting scenes!!', '', '', 'Curiosity_Lovers', 1783192794, '/r/MoviesThatFeelLike/comments/1unhl0h/a_gore_movie_with_lots_of_chasing_scenes_may/', 'https://www.reddit.com/gallery/1unhl0h', 'MoviesThatFeelLike', 'Brutal, high-octane action with relentless violence and intense chase sequences.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1243, '1unirt9', 'Movies with a Mediterranean Romance Thriller Aesthetic', 'Movies with a Mediterranean Romance Thriller Aesthetic', '', 'FitResearcher2865', 1783195800, '/r/MoviesThatFeelLike/comments/1unirt9/movies_with_a_mediterranean_romance_thriller/', 'https://www.reddit.com/gallery/1unirt9', 'MoviesThatFeelLike', 'Sun-drenched Mediterranean romance thriller with suspense.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1244, '1unl4xc', 'Movies that feel like this part of Industrial America', 'Movies that feel like this part of Industrial America', 'The rust belt, left behind and rotten as concrete is rained and poured on, overcast skies, trash lining the ground and overall looking miserable. Not really anything cyberpunk, more the current state of places in the rust belt.

The best I can describe it. I hope you get it!', 'sourberryskittles', 1783202120, '/r/MoviesThatFeelLike/comments/1unl4xc/movies_that_feel_like_this_part_of_industrial/', 'https://www.reddit.com/gallery/1unl4xc', 'MoviesThatFeelLike', 'Grimy, overcast rust-belt decay.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1245, '1unm0y1', 'Tinder but for choosing movie in a friends group', '', '', 'Jesperi93', 1783204567, '/r/MoviesThatFeelLike/comments/1unm0y1/tinder_but_for_choosing_movie_in_a_friends_group/', '/r/movies/comments/1unl423/tinder_but_for_choosing_movie_in_a_friends_group/', 'MoviesThatFeelLike', 'A playful, social way to settle movie night debates.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1246, '1unnogr', 'Vsco girl vibe', '', '', 'Whole_Bid1839', 1783209321, '/r/MoviesThatFeelLike/comments/1unnogr/vsco_girl_vibe/', 'https://i.redd.it/gtiid1stwabh1.jpeg', 'MoviesThatFeelLike', 'A nostalgic, carefree summer vibe with beach days, scrunchies, and Hydroflasks, capturing the 2019 VSCO girl aesthetic.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1247, '1unou2h', 'What are some of everyone’s favorite films directly adapted from or inspired by The Odyssey?', 'What are some of everyone’s favorite films directly adapted from or inspired by The Odyssey?', '', 'Consistent_Abies_652', 1783212793, '/r/MoviesThatFeelLike/comments/1unou2h/what_are_some_of_everyones_favorite_films/', '/r/films/comments/1unot9s/what_are_some_of_everyones_favorite_films/', 'MoviesThatFeelLike', 'Seeking epic cinematic journeys that capture the mythical allure of Homer''s Odyssey.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1248, '1untiyg', 'If you ever feel like watching the obscure movie or jamming to cool music....', 'If you ever feel like watching the obscure movie or jamming to cool music....', 'Hi y''all, what up doe? I got a YouTube channel devoted to entertainment & films. This is my 2nd posting at Reddit. Check it out & comment, it''s called **Forrest Green III''s Films** and here''s a link to a link: [movies & music FG III thinks U ought to get in](https://www.reddit.com/r/anything/comments/1ugbxxf/see_my_youtube_channel_guys/). 1st up, is *La Jetée* by Chris Marker, which is composed almost completely of photographic stills. So, stream & like I like to say here live: ENJOY.

Pleased to introduce myself -- I''m out.', 'Cav_01', 1783228481, '/r/MoviesThatFeelLike/comments/1untiyg/if_you_ever_feel_like_watching_the_obscure_movie/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1untiyg/if_you_ever_feel_like_watching_the_obscure_movie/', 'MoviesThatFeelLike', 'Casual, enthusiastic promotion of obscure cinematic gems.', 'skipped', 'no usable images', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1249, '1unw8a5', 'Please a need a brazilian vibes movies', 'Please a need a brazilian vibes movies', '', 'Consistent-Fox3396', 1783238000, '/r/MoviesThatFeelLike/comments/1unw8a5/please_a_need_a_brazilian_vibes_movies/', 'https://www.reddit.com/gallery/1unw8a5', 'MoviesThatFeelLike', 'A sun-soaked, leisurely Rio de Janeiro daydream with iconic landmarks.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1250, '1unxuep', 'Movies that feel like the anime Smoking Behind the Supermarket with You', '', 'New anime crush unlocked, damn i want some cigs and i don''t even smoke', 'maz323bf', 1783243895, '/r/MoviesThatFeelLike/comments/1unxuep/movies_that_feel_like_the_anime_smoking_behind/', 'https://www.reddit.com/gallery/1unxuep', 'MoviesThatFeelLike', 'Melancholic late-night convenience store encounters over shared cigarettes.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1251, '1unzjn1', 'cyberpunk world with monsters and creatures', 'cyberpunk world with monsters and creatures', 'Would like to stick to  movies or visual media.

But sure any other alternatives could also be included', 'Adorable-Quarter2994', 1783250029, '/r/MoviesThatFeelLike/comments/1unzjn1/cyberpunk_world_with_monsters_and_creatures/', 'https://www.reddit.com/gallery/1unzjn1', 'MoviesThatFeelLike', 'Neon-soaked cyberpunk cityscapes teeming with monstrous creatures and high-tech dangers.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1252, '1unzvxz', 'Movies that feel like this?', 'Movies that feel like this?', '', 'vladkudas', 1783251166, '/r/MoviesThatFeelLike/comments/1unzvxz/movies_that_feel_like_this/', 'https://i.redd.it/5vsoe0b1debh1.png', 'MoviesThatFeelLike', 'Dark, industrial body horror surrealism.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1253, '1uo00ya', 'Which medium of entertainment/learning is better', 'Which medium of entertainment/learning is better', '', 'Able-Salt5709', 1783251608, '/r/MoviesThatFeelLike/comments/1uo00ya/which_medium_of_entertainmentlearning_is_better/', 'https://i.redd.it/1hjx51u1eebh1.png', 'MoviesThatFeelLike', 'Curious inquiry into medium preferences.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1254, '1uo1dgu', 'Vibrant visuals with a hypnotizing soundtrack that you can lose yourself in?', 'Vibrant visuals with a hypnotizing soundtrack that you can lose yourself in?', 'This movie documentary was like a 2h vacation for my mind, I desperately need something similar ', 'Substantial-Ruin-866', 1783255682, '/r/MoviesThatFeelLike/comments/1uo1dgu/vibrant_visuals_with_a_hypnotizing_soundtrack/', 'https://i.redd.it/or15kyyoqebh1.jpeg', 'MoviesThatFeelLike', 'A mesmerizing audiovisual escape that washes over you.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1255, '1uo386c', 'Movies that feel like Robot/Cyborg Horror', '', 'Virus (1999)

Hardware (1990)

Terminator (1984)

Judge Dredd (1995)

Quake 4 (2005)

Fallout 4 (2015)

\- I know the Synths probably stand out the most but I was inspired to include them after seeing the Defective Synths mod.', 'Brass0Maharlika', 1783260769, '/r/MoviesThatFeelLike/comments/1uo386c/movies_that_feel_like_robotcyborg_horror/', 'https://www.reddit.com/gallery/1uo386c', 'MoviesThatFeelLike', 'A gritty fusion of mechanical dread and body horror, where circuits and sinew intertwine in a dystopian nightmare.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1256, '1uo3owg', 'Styrlish, surreal Japanese movies that reminds you of that (once) virla Mouse commercial?', 'Stylish, surreal Japanese movies that remind you of that (once) viral Mouse commercial?', 'https://preview.redd.it/l1t5dcx39fbh1.jpg?width=1280&format=pjpg&auto=webp&s=6135dcc716aae4bbc8baf08fca0036545477258e

Listen at your on risk, it''s highly addictive: [https://www.youtube.com/watch?v=GNqAAQOow9c&list=RDGNqAAQOow9c&start\_radio=1](https://www.youtube.com/watch?v=GNqAAQOow9c&list=RDGNqAAQOow9c&start_radio=1)', 'Dramatic-Lime5993', 1783261962, '/r/MoviesThatFeelLike/comments/1uo3owg/styrlish_surreal_japanese_movies_that_reminds_you/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uo3owg/styrlish_surreal_japanese_movies_that_reminds_you/', 'MoviesThatFeelLike', 'Stylish and surreal Japanese cinema with a vibrant, commercial-like energy.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1257, '1uo3ra4', 'Stylish, surreal Japanese movies that remind you of that (once) viral commercial for "Mouse"?', 'Stylish, surreal Japanese movies that remind you of that (once) viral commercial for "Mouse"?', 'Click at your own risk, it''s highly addictive:

[https://www.youtube.com/watch?v=GNqAAQOow9c&list=RDGNqAAQOow9c&start\_radio=1](https://www.youtube.com/watch?v=GNqAAQOow9c&list=RDGNqAAQOow9c&start_radio=1)', 'Dramatic-Lime5993', 1783262132, '/r/MoviesThatFeelLike/comments/1uo3ra4/stylish_surreal_japanese_movies_that_remind_you/', 'https://i.redd.it/d716dm1j9fbh1.jpeg', 'MoviesThatFeelLike', 'Stylish and surreal Japanese aesthetics with addictive visuals.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1258, '1uo5xtu', 'Movies/TV Series in the Highlands', 'Movies/TV Series in the Highlands', 'Besides Braveheart', 'zawwery', 1783267491, '/r/MoviesThatFeelLike/comments/1uo5xtu/moviestv_series_in_the_highlands/', 'https://www.reddit.com/gallery/1uo5xtu', 'MoviesThatFeelLike', 'Misty, rugged highlands landscape with a sense of ancient history and solitary wilderness.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1259, '1uo710b', 'Movies taking place during the night, countryside, same vibe than KRZ.', 'Movies taking place during the night, countryside, same vibe as KRZ.', '', 'Embarrassed_Bag8880', 1783270109, '/r/MoviesThatFeelLike/comments/1uo710b/movies_taking_place_during_the_night_countryside/', '/r/kentuckyroutezero/comments/1ulue3u/movies_taking_place_during_the_night_countryside/', 'MoviesThatFeelLike', 'A lonely, surreal road trip through moonlit backroads, steeped in quiet southern gothic melancholy.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1260, '1uo7tvy', 'The movie that’ll have you questioning your senses:', 'The movie that’ll have you questioning your senses', 'This is a weird little gem from 1935 with some humorous, MST3K-style commentary.  Hope you enjoy!', 'Hairy-Falcon-730', 1783272001, '/r/MoviesThatFeelLike/comments/1uo7tvy/the_movie_thatll_have_you_questioning_your_senses/', 'https://youtu.be/ryR-nEXH-2k', 'MoviesThatFeelLike', 'A surreal, offbeat vintage film that feels like a bizarre dream.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1261, '1uo7zx1', 'Pirating movies', 'Pirating movies', '', 'Visual_Ability_6187', 1783272388, '/r/MoviesThatFeelLike/comments/1uo7zx1/pirating_movies/', '/r/PiratingWebsites/comments/1uo7xo6/pirating_movies/', 'MoviesThatFeelLike', 'A digital-age sense of rebellion and illicit access.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1262, '1uo8jis', 'Movies with an African resort kind of aesthetic', 'Movies with an African resort kind of aesthetic', '', 'FitResearcher2865', 1783273688, '/r/MoviesThatFeelLike/comments/1uo8jis/movies_with_an_african_resort_kind_of_aesthetic/', 'https://www.reddit.com/gallery/1uo8jis', 'MoviesThatFeelLike', 'Sun-drenched African resort getaway with luxury, wildlife, and exotic adventure.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1263, '1uo96qh', 'Old internet and tech dreams', 'Old internet and tech dreams', 'Please suggest some movies that feel like the old (90s, early 2000s) internet aesthetic and tech dreams. Like Geocities and Neuromancer. 

Some of the movies that I have watched and adored are: War Games (a bit further back in time but still), Sneakers, Ghost in The Shell, The Net, Hackers... TIA. ', 'notdesperatejustdumb', 1783275183, '/r/MoviesThatFeelLike/comments/1uo96qh/old_internet_and_tech_dreams/', 'https://www.reddit.com/gallery/1uo96qh', 'MoviesThatFeelLike', 'A retro-futuristic hacker vibe steeped in 90s internet aesthetics and cyberpunk daydreams.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1264, '1uoapsd', 'Movies with diner vibes', 'Movies with diner vibes', 'Love the old fashioned diner vibe; would love to find more movies that heavily feature old fashioned diners or movies that have fun diner scenes in general.', 'Remote-Leather6565', 1783278772, '/r/MoviesThatFeelLike/comments/1uoapsd/movies_with_diner_vibes/', 'https://www.reddit.com/gallery/1uoapsd', 'MoviesThatFeelLike', 'Nostalgic old-fashioned diner atmosphere', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1265, '1uob52l', 'Oriental aesthetic', 'Oriental aesthetic', '', 'Whole_Bid1839', 1783279782, '/r/MoviesThatFeelLike/comments/1uob52l/oriental_aesthetic/', 'https://v.redd.it/4w7sfdmbqgbh1', 'MoviesThatFeelLike', 'Desert landscapes, flowing robes, and mystical ancient-meets-future Orientalist grandeur.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1266, '1uoc18x', 'Eating cup noodles in the middle of the night, while someone could end me at any given moment.', 'Eating cup noodles in the middle of the night, while someone could end me at any given moment.', '', 'Adventurous_Mood1303', 1783281918, '/r/MoviesThatFeelLike/comments/1uoc18x/eating_cup_noodles_in_the_middle_of_the_night/', 'https://www.reddit.com/gallery/1uoc18x', 'MoviesThatFeelLike', 'Nocturnal urban paranoia with neon-lit danger', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1267, '1uohx6t', 'Evil corporations', 'Evil corporations', '', 'TheLetterBoxder', 1783296790, '/r/MoviesThatFeelLike/comments/1uohx6t/evil_corporations/', 'https://www.reddit.com/gallery/1uohx6t', 'MoviesThatFeelLike', 'Sinister megacorporations wielding unchecked power in dystopian and sci-fi settings.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1268, '1vf34s9', 'MC with severe OCD or something similar', 'Movies with main characters having severe OCD', 'Would love if it explored how isolating these kinds of disorders can be like how these images feel

Extra points if protagonist is a girl/woman', 'BackgroundMortgage91', 1785827643, '/r/MoviesThatFeelLike/comments/1vf34s9/mc_with_severe_ocd_or_something_similar/', 'https://www.reddit.com/gallery/1vf34s9', 'MoviesThatFeelLike', 'Claustrophobic anxiety and repetitive, isolating rituals.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1269, '1vg02hd', 'Movies that feel like...a quaint little town...with something going on...', 'Movies that feel like...a quaint little town...with something going on...', 'Not including the films where I got these pictures from (Time Crimes, Phantasm, The Monkey, Messiah of Evil, Innocence (2004), A Nightmare on Elm Street)', 'XipeTotecwithGlitter', 1785913765, '/r/MoviesThatFeelLike/comments/1vg02hd/movies_that_feel_likea_quaint_little_townwith/', 'https://www.reddit.com/gallery/1vg02hd', 'MoviesThatFeelLike', 'Quaint little towns with dark secrets lurking beneath the surface.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1270, '1vgoq5r', 'Movies with a doomed marriage or weird bride', 'Movies with a doomed marriage or weird bride', 'The only thing is that even if they''re only engaged in the film and never make it to the altar, I want recs where she''s actually in her dress even if she''s just trying it on.', 'MysteriousMine2115', 1785975452, '/r/MoviesThatFeelLike/comments/1vgoq5r/movies_with_a_doomed_marriage_or_weird_bride/', 'https://www.reddit.com/gallery/1vgoq5r', 'MoviesThatFeelLike', 'A darkly romantic tableau of bridal anxiety and marital catastrophe, steeped in gothic dread.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1271, '1vgr0uu', 'Movies with unsettling mothers and/or househould', 'Movies with unsettling mothers and/or househould', 'Loved Hereditary, but I''m looking for ones that don''t necessarily explicitly scare or be horror-esque, but give a haunting, ominous, and heavy feeling? ', 'sveltegoddess_', 1785981675, '/r/MoviesThatFeelLike/comments/1vgr0uu/movies_with_unsettling_mothers_andor_househould/', 'https://www.reddit.com/gallery/1vgr0uu', 'MoviesThatFeelLike', 'Haunting, ominous domestic dread with unsettling maternal figures.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1272, '1vgz0pi', 'Movies with this vibe?', 'Movies with this vibe?', 'I was looking to see if there were any films that had this almost grungey feminine multimedia aesthetic. I already got kinda clowned on in r/AestheticWiki so save the criticism on this probably uncohesive collection of images. ', 'CleotheSimp', 1786007298, '/r/MoviesThatFeelLike/comments/1vgz0pi/movies_with_this_vibe/', 'https://www.reddit.com/gallery/1vgz0pi', 'MoviesThatFeelLike', 'A grungy, feminine, multimedia collage vibe blending punk energy with dreamy nostalgia.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1273, '1vh8yb1', 'Space movies or TV shows that feel like you''re small and isolated', 'Space movies or TV shows that feel like you''re small and isolated', 'Having a large sense of scale is something I find super intriguing in Space sci-fi, and I can''t get enough.

One of my favorite films is Interstellar for some of the early space scenes.

I''ve seen 2001 and enjoyed it as well.

The Expanse is one of my favorite shows, for the space stuff.

Any suggestions?

(sources of Images are Elite: Dangerous, X4 Foundations, and Erik Wernquist youtube videos)', 'RDman12', 1786033300, '/r/MoviesThatFeelLike/comments/1vh8yb1/space_movies_or_tv_shows_that_feel_like_youre/', 'https://www.reddit.com/gallery/1vh8yb1', 'MoviesThatFeelLike', 'A vast, lonely cosmos where humanity confronts its insignificance.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1274, '1vhb7d0', 'Introspective movies with low stakes', 'Introspective movies with low stakes', ' The examples I selected have a western/Midwest vibe but open to other vibes as well as foreign films.', 'opididitagain', 1786038128, '/r/MoviesThatFeelLike/comments/1vhb7d0/introspective_movies_with_low_stakes/', 'https://www.reddit.com/gallery/1vhb7d0', 'MoviesThatFeelLike', 'Quiet, contemplative journeys through everyday life, often with a midwestern or road-trip backdrop.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1275, '1vhfnpm', 'Movies that feel like I''m a single 20something in 2015 looking for love', 'Movies that feel like I''m a single 20something in 2015 looking for love', 'Basically just finished HBO Girls, also What if? (2013) and looking for movies with a similar rom com/insta filter/indie vibe. Bonus points if it takes place in a city or in fall.

Sorry if some of these photos are AI I just pulled off Pinterest mostly', 'thesingingmoose', 1786047854, '/r/MoviesThatFeelLike/comments/1vhfnpm/movies_that_feel_like_im_a_single_20something_in/', 'https://www.reddit.com/gallery/1vhfnpm', 'MoviesThatFeelLike', 'Bittersweet indie romance with the Instagram-filtered feel of 2015 city life and a longing for love in the autumn', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1276, '1vhg7fh', 'Urban Fantasy', 'Urban Fantasy', 'Looking for some urban fantasy / cyberpunk fantasy that might be new to me. Its my favorite sub genre of media and Ive seen a lot of it so hoping for new fun stuff to watch

Sources shown:

Shadowrun

Bright

Hellblazer comic (although I do love the movie)

Lovecraft country

Big Trouble in Little China

Thanks in advance!', 'RealStevenMattor', 1786049123, '/r/MoviesThatFeelLike/comments/1vhg7fh/urban_fantasy/', 'https://www.reddit.com/gallery/1vhg7fh', 'MoviesThatFeelLike', 'Gritty neon-noir streets where ancient magic collides with urban decay.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1277, '1vhi6sl', '1970''s/Early 80''s movies. Dark, sleezy, dirty, crime movies with big city urban decay. The city is a character itself.', '', '', 'Beard_Of_Serpico', 1786053818, '/r/MoviesThatFeelLike/comments/1vhi6sl/1970searly_80s_movies_dark_sleezy_dirty_crime/', 'https://www.reddit.com/gallery/1vhi6sl', 'MoviesThatFeelLike', 'Dark, sleazy, dirty urban decay with the city as a menacing character.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1278, '1vhjqch', 'Gothic, not Goth, movies, that aren’t Gothic Monster movies?', 'Gothic, not Goth, movies, that aren’t Gothic Monster movies?', '', 'Ihatemylifewishtodie', 1786057664, '/r/MoviesThatFeelLike/comments/1vhjqch/gothic_not_goth_movies_that_arent_gothic_monster/', 'https://www.reddit.com/gallery/1vhjqch', 'MoviesThatFeelLike', 'Brooding medieval atmosphere, existential dread, and dark, morbid beauty.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1279, '1vhlyzh', 'Movies with a thunder/rainstorm aesthetic throughout but where the weather isn’t the main plot?', 'Movies with a thunder/rainstorm aesthetic throughout but where the weather isn’t the main plot?', 'To clarify, I’m not looking for like natural disaster movies or things where there’s a hurricane going on or anything. Just a good movie set on a stormy night or in a stormy world. Examples would be Clue, Dark City, Identity, and The Crow. Noir/mystery preferred, but I’ll take anything!', 'No-Chemistry-28', 1786063565, '/r/MoviesThatFeelLike/comments/1vhlyzh/movies_with_a_thunderrainstorm_aesthetic/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vhlyzh/movies_with_a_thunderrainstorm_aesthetic/', 'MoviesThatFeelLike', 'Rain-drenched noir mystery.', 'skipped', 'no usable images', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1280, '1vhn4bn', 'Movies that feel like this ?', '', '', 'Ok_Item9755', 1786066750, '/r/MoviesThatFeelLike/comments/1vhn4bn/movies_that_feel_like_this/', 'https://i.redd.it/p0mnn7uexuhh1.jpeg', 'MoviesThatFeelLike', 'bittersweet yearning', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1281, '1vhpdyh', 'Any movies that give the same feeling as these photos?', 'Any movies that give the same feeling as these photos?', '', 'madmax10001', 1786073228, '/r/MoviesThatFeelLike/comments/1vhpdyh/any_movies_that_give_the_same_feeling_as_these/', 'https://www.reddit.com/gallery/1vhpdyh', 'MoviesThatFeelLike', 'A wintry, isolated atmosphere of creeping dread, often with psychological horror elements, set in snow-covered and remote locations.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1282, '1vhsnxu', 'Movies with this type of feeling and atmosphere?', '', 'Would appreciate some help. Thank you.', 'I-like-it-in-here', 1786083638, '/r/MoviesThatFeelLike/comments/1vhsnxu/movies_with_this_type_of_feeling_and_atmosphere/', 'https://www.reddit.com/gallery/1vhsnxu', 'MoviesThatFeelLike', 'Claustrophobic, densely-layered urban scenes with neon glows and pockets of greenery, evoking gritty cyberpunk decay.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1283, '1vhsqhi', 'Movies like this', '', '', 'Idek163', 1786083870, '/r/MoviesThatFeelLike/comments/1vhsqhi/movies_like_this/', 'https://www.reddit.com/gallery/1vhsqhi', 'MoviesThatFeelLike', 'A dreamy, melancholic atmosphere tinged with whimsy and coming-of-age introspection.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1284, '1vhtbli', 'Any movies or tv shows that feels like this?', '', '', 'themiracleLuna', 1786085918, '/r/MoviesThatFeelLike/comments/1vhtbli/any_movies_or_tv_shows_that_feels_like_this/', 'https://www.reddit.com/gallery/1vhtbli', 'MoviesThatFeelLike', 'A dreamy, nostalgic, and subtly sinister atmosphere surrounding suburban adolescence.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1285, '1vhw5yp', 'Need movie suggestions for candy flip (acid +ecstasy)', 'Candy flip (acid + ecstasy) movie suggestions', '', 'RareBox1497', 1786096162, '/r/MoviesThatFeelLike/comments/1vhw5yp/need_movie_suggestions_for_candy_flip_acid_ecstasy/', '/r/enlightenment/comments/1vhw2r6/need_movie_suggestions_for_candy_flip_acid_ecstasy/', 'MoviesThatFeelLike', 'Trippy, euphoric visuals for a candy flip', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1286, '1vhwqkn', 'what movies feel like a psychological rollercoaster', 'what movies feel like a psychological rollercoaster', '', 'Dull-Bid9243', 1786098041, '/r/MoviesThatFeelLike/comments/1vhwqkn/what_movies_feel_like_a_psychological/', '/r/MovieSuggestions/comments/1vhwpox/what_movies_feel_like_a_psychological/', 'MoviesThatFeelLike', 'A disorienting psychological ride that twists the mind and emotions.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1287, '1vhz6xj', 'Movies that feel like this', 'Movies that feel like this', '', 'Fit-Chair-9848', 1786105489, '/r/MoviesThatFeelLike/comments/1vhz6xj/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vhz6xj', 'MoviesThatFeelLike', 'Nostalgic and dreamy feminine melancholy with an undercurrent of unease.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1288, '1vi45wm', 'Looking for movies/shows that feel like this!', '', '', 'Peraltasilie', 1786117402, '/r/MoviesThatFeelLike/comments/1vi45wm/looking_for_moviesshows_that_feel_like_this/', 'https://i.redd.it/bw3jdb124zhh1.jpeg', 'MoviesThatFeelLike', 'Eerie, mist-laden forests and small-town dread with supernatural undercurrents.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1289, '1vi6rwf', 'Movies with this vibe?', 'Movies with this vibe?', 'Recently rewatched season two of YOU (Netflix) and absolutely love the vibes of that season. Any movies that capture LA in a similar light? ', 'shannon_m17', 1786123170, '/r/MoviesThatFeelLike/comments/1vi6rwf/movies_with_this_vibe/', 'https://www.reddit.com/gallery/1vi6rwf', 'MoviesThatFeelLike', 'Glamorous yet unsettling Los Angeles, reminiscent of YOU season two.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1290, '1vi73kw', 'Movies that feel like this', '', '', 'Male-2003', 1786123901, '/r/MoviesThatFeelLike/comments/1vi73kw/movies_that_feel_like_this/', 'https://i.redd.it/4yy1ryjdnzhh1.jpeg', 'MoviesThatFeelLike', 'Nightmarish, bloody, and surreal horror with intense psychological torment.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1291, '1vi7ije', 'Other titles like Years and Years (2019)', 'Other titles like Years and Years', 'Hi, I recently rewatched Years and Years (2019) and I''m looking for more movies or series that would pursue a similar matter - a take on how our future could (or will?) look like, economic situation, societies, climate etc. - can be all topics at once, but can also focus on one at a time.

When rewatching, I got again hooked by the first episode and I personally think the show peaked there and then steadily took a turn to worse >!with a really unearned hopecore-ish finale!< (masking for spoilers just in case). I look for something that would hit a similar cord. 

I''ve watched original Utopia, Devs and Black Mirror. I heard The Expanse could have some of the vibe I described, could somebody confirm?

Thanks in advance!', 'epi_premnum', 1786124837, '/r/MoviesThatFeelLike/comments/1vi7ije/other_titles_like_years_and_years_2019/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vi7ije/other_titles_like_years_and_years_2019/', 'MoviesThatFeelLike', 'Near-future societal and climate dystopia', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1292, '1vi7n65', 'Other titles like Years and Years (2019)', '', 'Hi, I recently rewatched Years and Years (2019) and I''m looking for more movies or series that would pursue a similar matter - a take on how our future could (or will?) look like, economic situation, societies, climate etc. - can be all topics at once, but can also focus on one at a time.

When rewatching, I got again hooked by the first episode and I personally think the show peaked there and then steadily took a turn to worse >!with a really unearned hopecore-ish finale!< (masking for spoilers just in case). I look for something that would hit a similar cord. 

I''ve watched original Utopia, Devs and Black Mirror. I heard The Expanse could have some of the vibe I described, could somebody confirm?

Thanks in advance!', 'epi_premnum', 1786125118, '/r/MoviesThatFeelLike/comments/1vi7n65/other_titles_like_years_and_years_2019/', 'https://i.redd.it/7taru610rzhh1.jpeg', 'MoviesThatFeelLike', 'Speculative dystopian drama exploring societal breakdown.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1293, '1vi7oeu', 'Movies that look/feel like this', 'Movies that look/feel like this', '', 'StopTalking3005', 1786125189, '/r/MoviesThatFeelLike/comments/1vi7oeu/movies_that_lookfeel_like_this/', 'https://www.reddit.com/gallery/1vi7oeu', 'MoviesThatFeelLike', 'Whimsical and nostalgic animated pastoral fantasy with a hint of eerie storybook magic.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1294, '1vi81mc', 'Movies that give this kind of vibe', 'movies that give this kind of vibe', '', 'chaiegai', 1786125970, '/r/MoviesThatFeelLike/comments/1vi81mc/movies_that_give_this_kind_of_vibe/', 'https://www.reddit.com/gallery/1vi81mc', 'MoviesThatFeelLike', 'A rugged, remote wilderness filled with towering trees, crackling campfires, and lurking danger.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1295, '1vi96ts', 'Movies with this vibe? preferably thrillers or horrors', '', 'any movies with this vibe that are horror or thrillers? or whatever that genre “palo alto” is? (also i snuck in a pic of my own, is this the start of my photography career?)', 'Extension-Pretniss', 1786128502, '/r/MoviesThatFeelLike/comments/1vi96ts/movies_with_this_vibe_preferably_thrillers_or/', 'https://www.reddit.com/gallery/1vi96ts', 'MoviesThatFeelLike', 'Lonely, paranoid, neon-drenched urban nightmare.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1296, '1vi98b8', 'szukam niezależnego/psychologicznego dramatu filmowego, który widziałem lata temu z emo/goth żeńskim bohaterem', 'Looking for independent/psychological drama with emo/goth female lead', '[removed]', 'Bubbly_Internal_3190', 1786128593, '/r/MoviesThatFeelLike/comments/1vi98b8/szukam_niezależnegopsychologicznego_dramatu/', '/r/whatsthemoviecalled/comments/1vi8sdc/looking_for_an_indiepsychological_drama_movie_ive/', 'MoviesThatFeelLike', 'A brooding, introspective atmosphere of psychological darkness and somber artistic expression.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1297, '1vi9dtz', 'Recommend sharp showbiz satires', 'Recommend sharp showbiz satires', 'Preferably with a tone similar to The Player or Network. ', 'AmbitionTechnical274', 1786128934, '/r/MoviesThatFeelLike/comments/1vi9dtz/recommend_sharp_showbiz_satires/', 'https://www.reddit.com/gallery/1vi9dtz', 'MoviesThatFeelLike', 'A sharp, satirical look at the entertainment industry.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1298, '1vi9dzz', 'Any movies that give off this vibe?', 'Any movies that give off this vibe?', '', 'Bobbymom078', 1786128945, '/r/MoviesThatFeelLike/comments/1vi9dzz/any_movies_that_give_off_this_vibe/', 'https://www.reddit.com/gallery/1vi9dzz', 'MoviesThatFeelLike', 'A bleak, gritty Eastern European warzone atmosphere, evoking post-Soviet conflicts and the chaos of the Yugoslav Wars.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1299, '1vi9e0p', 'Looking for movies similar to Girl in the Basement (2021)', 'Looking for movies similar to Girl in the Basement (2021)', '', 'poo_smudge', 1786128947, '/r/MoviesThatFeelLike/comments/1vi9e0p/looking_for_movies_similar_to_girl_in_the/', '/r/findsimilarmovies/comments/1vi6iqs/looking_for_movies_similar_to_girl_in_the/', 'MoviesThatFeelLike', 'disturbing confinement dread', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1300, '1vi9fhk', 'Sharp Showbiz Satires', 'Sharp Showbiz Satires', 'Similar to The Player or Network', 'AmbitionTechnical274', 1786129040, '/r/MoviesThatFeelLike/comments/1vi9fhk/sharp_showbiz_satires/', 'https://www.reddit.com/gallery/1vi9fhk', 'MoviesThatFeelLike', 'Biting satires of the entertainment industry that expose its absurdities and dark humor.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1301, '1vi9usn', 'Borrowing from Songs!', 'Borrowing from Songs!', 'Who’s got some cool Y2K futurism for me?', 'GreenChiliGronk', 1786129977, '/r/MoviesThatFeelLike/comments/1vi9usn/borrowing_from_songs/', 'https://www.reddit.com/gallery/1vhefm0', 'MoviesThatFeelLike', 'Slick, high-tech late-90s/early-2000s cyberpunk and sci-fi aesthetic.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1302, '1viat6k', 'Movies that feel like playing Assassin''s Creed Black Flag (pirates)', 'Movies that feel like playing Assassin''s Creed Black Flag (pirates)', 'I''m playing Black Flag at the moment and I''d like to know if there are any other good pirate movies besides Pirates of the Caribbean ?', 'Special-Bad2404', 1786132148, '/r/MoviesThatFeelLike/comments/1viat6k/movies_that_feel_like_playing_assassins_creed/', 'https://i.redd.it/g4jmi25wb0ih1.jpeg', 'MoviesThatFeelLike', 'Swashbuckling pirate adventure with a gritty historical feel, ship battles, and treasure hunting.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1303, '1vib105', 'Can anyone recommend me something similar?', 'Can anyone recommend me something similar?', '[removed]', 'misscarmenortiz', 1786132649, '/r/MoviesThatFeelLike/comments/1vib105/can_anyone_recommend_me_something_similar/', 'https://www.reddit.com/gallery/1vib105', 'MoviesThatFeelLike', 'No specific vibe described', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1304, '1vib4x9', 'Can anyone recommend me something similar?', 'Can anyone recommend me something similar?', '[removed]', 'misscarmenortiz', 1786132874, '/r/MoviesThatFeelLike/comments/1vib4x9/can_anyone_recommend_me_something_similar/', 'https://i.redd.it/3wd5g8a2e0ih1.jpeg', 'MoviesThatFeelLike', 'Unknown', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1305, '1viga5a', 'Movies with this type of alien design?', 'Movies with this type of alien design?', 'My favorite type of alien design with an emphasis on certain body parts that stick out like eyes, lips, antennas, looking gross and cool at the same time. ', 'Jellypathicdream', 1786145590, '/r/MoviesThatFeelLike/comments/1viga5a/movies_with_this_type_of_alien_design/', 'https://www.reddit.com/gallery/1viga5a', 'MoviesThatFeelLike', 'Gross yet cool alien designs that emphasize bulging eyes, lips, and antennas, blending the repulsive with the fascinating.', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1306, '1vigaf4', 'Hard to describe but movies or songs that feel like these snippets.', 'Hard to describe but movies or songs that feel like these snippets.', 'https://reddit.com/link/1vigaf4/video/gymy3t5xe1ih1/player

https://reddit.com/link/1vigaf4/video/adj3ilawf1ih1/player

', 'Illustrious_Bowl_960', 1786145610, '/r/MoviesThatFeelLike/comments/1vigaf4/hard_to_describe_but_movies_or_songs_that_feel/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vigaf4/hard_to_describe_but_movies_or_songs_that_feel/', 'MoviesThatFeelLike', 'An indescribable, elusive vibe from personal snippets.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1307, '1vigoka', 'Can you find any movies that look like this?', 'Can you find any movies that look like this?', '', 'Ultrakirby78', 1786146694, '/r/MoviesThatFeelLike/comments/1vigoka/can_you_find_any_movies_that_look_like_this/', 'https://www.reddit.com/gallery/1vigoka', 'MoviesThatFeelLike', 'Retro-futuristic sci-fi with vibrant, campy aesthetics', 'publishable', NULL, NULL, '2026-08-08 02:23:49', '2026-08-08 02:23:49');
