-- 0086_seed_20260809T022843Z_01_posts.sql: data seed from pipeline:load run.
-- Generated:  2026-08-09T02:29:31.758484+00:00
-- Run started: 2026-08-09T02:28:43.172940+00:00
-- Source: data/working/load manifest from this run.
--
-- Idempotent: every INSERT is INSERT OR IGNORE, keyed by the
-- table's natural unique constraint.  Wrangler's migration
-- tracking normally prevents re-apply; the OR IGNORE is
-- defense in depth for partial / interrupted re-runs.
--
-- Chunk: 01_posts (1/5)
-- Tables: imported_vibe_posts.
-- Pipeline-state tables (processing_runs, pipeline_artifacts)
-- are intentionally excluded — they're per-run bookkeeping.

INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1308, '1ulqlno', 'Movies that have the vibe of Tangerine, but not other Sean Baker films.', 'Movies that have the vibe of Tangerine, but not other Sean Baker films.', 'https://preview.redd.it/3d219oy22vah1.png?width=709&format=png&auto=webp&s=37dadaba28e3b63e9e2b4db4d5b710961586a526

', 'LongjumpingHorse3050', 1783017388, '/r/MoviesThatFeelLike/comments/1ulqlno/movies_that_have_the_vibe_of_tangerine_but_not/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1ulqlno/movies_that_have_the_vibe_of_tangerine_but_not/', 'MoviesThatFeelLike', 'Gritty, vibrant street-level stories with darkly comedic undertones, following marginalized characters or reckless youth through chaotic, neon-lit adventures.', 'skipped', 'no usable images', NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1309, '1ulsrzx', 'Hangout movies by decade', 'Hangout movies by decade', 'Hi all, looking to have some blanks filled out.  
Prime examples:  
Set in 1960s: American Graffiti  
Set in 1970s: Dazed and Confused  
Set in 1980s: Fast Times at Ridgemont High  
Set in 1990s: Empire Records  
Set in 2000s:?  
Set in 2010s:?  
Set in 2020s:?

So as you can see from the first 4 examples these are teen hangout movies that largely take place over 1 day/night that really represent there time.

Can anyone suggest any movies for the other 3 decades? Any additional examples for the other decades would be cool too.

I can also think of Superbad, breakfast club,

Let’s see what you guys come up with', 'Miserable-Sea-4160', 1783022257, '/r/MoviesThatFeelLike/comments/1ulsrzx/hangout_movies_by_decade/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1ulsrzx/hangout_movies_by_decade/', 'MoviesThatFeelLike', 'Carefree teen hangout movies that bottle the spirit of their decade through a single day or night of youthful mischief and connection.', 'skipped', 'no usable images', NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1310, '1ultuyl', 'Non period movies that feel like this', 'Non period movies that feel like this', '', 'Male-2003', 1783024726, '/r/MoviesThatFeelLike/comments/1ultuyl/non_period_movies_that_feel_like_this/', 'https://i.redd.it/6qalmutxnvah1.jpeg', 'MoviesThatFeelLike', 'Tense, candlelit dinner parties with an undercurrent of psychological dread.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1311, '1uluvst', 'This', 'Arisu', 'Arisu ', 'Jellypathicdream', 1783027086, '/r/MoviesThatFeelLike/comments/1uluvst/this/', 'https://i.redd.it/b7bpsdhyuvah1.jpeg', 'MoviesThatFeelLike', 'A surreal androgynous punk aesthetic with cyberpunk and kabuki flair.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1312, '1ulw1di', 'Looking for more movies that are based or from the 60s/70s vibes! ☮️', '', '', 'codependencytapes', 1783029778, '/r/MoviesThatFeelLike/comments/1ulw1di/looking_for_more_movies_that_are_based_or_from/', 'https://i.redd.it/bpxonpjy2wah1.jpeg', 'MoviesThatFeelLike', 'Nostalgic, free-spirited 1960s and 1970s counterculture vibes.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1313, '1ulwp1i', 'movies that remind you everything is going to be okay', '', '', 'prince-vvv', 1783031348, '/r/MoviesThatFeelLike/comments/1ulwp1i/movies_that_remind_you_everything_is_going_to_be/', 'https://i.redd.it/ppafuium7wah1.jpeg', 'MoviesThatFeelLike', 'A cozy, quirky blend of indie warmth and darkly whimsical reassurance.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1314, '1um0afd', 'Movies like Southland Tales (2006).', 'Movies like Southland Tales', '[deleted]', '[deleted]', 1783041093, '/r/MoviesThatFeelLike/comments/1um0afd/movies_like_southland_tales_2006/', '', 'MoviesThatFeelLike', 'Surreal dystopian satire', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1315, '1um0b4d', 'Movies like Southland Tales (2006)', 'Movies like Southland Tales', 'I watched it a while back, and I just cannot get it out of my head! I need more stuff like it!', 'MaineGameBoy', 1783041149, '/r/MoviesThatFeelLike/comments/1um0b4d/movies_like_southland_tales_2006/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1um0b4d/movies_like_southland_tales_2006/', 'MoviesThatFeelLike', 'mind-bending and surreal dystopian sci-fi with satirical undertones', 'skipped', 'no usable images', NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1316, '1um1e5o', 'Movies that appear to be gory, violent and hectic, then it becomes apparent it''s also a love story', 'Movies that appear to be gory, violent and hectic, then it becomes apparent it''s also a love story', '', 'XipeTotecwithGlitter', 1783044211, '/r/MoviesThatFeelLike/comments/1um1e5o/movies_that_appear_to_be_gory_violent_and_hectic/', 'https://www.reddit.com/gallery/1um1e5o', 'MoviesThatFeelLike', 'Brutal, chaotic violence that slowly reveals an unexpected romantic core.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1317, '1um235n', 'Movies that feel like this?', 'Movies that feel like this?', '', 'No-Ear3313', 1783046217, '/r/MoviesThatFeelLike/comments/1um235n/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1um235n', 'MoviesThatFeelLike', 'Retro underwater pulp adventure with sharks, divers, and sea monsters.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1318, '1um24si', 'Something like this', 'Something like this', 'A film that has vast open spaces in the us with storms and light. Some that I’ve seen, Take Shelter, MUD, Joe, Hell or high water, no country for old men. Anything else you guys recommend? The image is more for the light a the sky then the storyline. ', 'Sturdypigeonz', 1783046353, '/r/MoviesThatFeelLike/comments/1um24si/something_like_this/', 'https://i.redd.it/hfn1a4w8gxah1.jpeg', 'MoviesThatFeelLike', 'A mood of vast, storm-swept American landscapes illuminated by dramatic, ethereal light.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1319, '1um2606', 'Movies that feel like living in an eternal sunset in a small Latin town', 'Eternal sunset in a small Latin town', '', 'emifetishh', 1783046455, '/r/MoviesThatFeelLike/comments/1um2606/movies_that_feel_like_living_in_an_eternal_sunset/', 'https://www.reddit.com/gallery/1um2606', 'MoviesThatFeelLike', 'A perpetual golden-hour glow wrapping a quiet Latin town in warmth and nostalgia.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1320, '1um3ef4', 'Movies featuring a character with those kinds of vibes. A strong character with a terrifying presence', 'Movies featuring a strong, terrifying character', '&#x200B;

Movies with an immensely Strong character,

Physically imposing, menacing, fast, brutal and terrifying

Yet set with "realistic" /grounded vibe with a dark and serious atmosphere.

The kind of movie character that makes you say:

■Damn, i definitely don''t want to meet this guy in a dark alley■

1&2 pics: The Brute from The Killer

3,4,5, pics: The Beast from Eastrail 177 Trilogy', 'espertempX2', 1783050094, '/r/MoviesThatFeelLike/comments/1um3ef4/movies_featuring_a_character_with_those_kinds_of/', 'https://www.reddit.com/gallery/1um3ef4', 'MoviesThatFeelLike', 'Dark, grounded intensity with terrifyingly imposing characters that evoke dread and raw power.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1321, '1um3en6', 'Movies that feel like this…', 'Movies that feel like this', '', 'LessLavishness7040', 1783050111, '/r/MoviesThatFeelLike/comments/1um3en6/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1um3en6', 'MoviesThatFeelLike', 'Gritty, neon-lit nights and restless romantic longing', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1322, '1um4f9d', 'Movies that feel like Emily Wants To Play (2015, horror videogame).', 'Movies that feel like Emily Wants To Play', '', 'SmallEconomics6173', 1783053148, '/r/MoviesThatFeelLike/comments/1um4f9d/movies_that_feel_like_emily_wants_to_play_2015/', 'https://www.reddit.com/gallery/1um4f9d', 'MoviesThatFeelLike', 'A tense, claustrophobic horror atmosphere with animatronic terrors and sudden frights.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1323, '1um4y0g', 'More CyberPunk Dystopia!', 'CyberPunk Dystopia!', 'Looking for more Blade Runner-adjacent films. I just read The Windup Girl last summer which gave me a taste of the whole, Thailand street market, tight/windy alley streets vibe. Looking for movies that paint a similar picture. More Dystopia! Think', 'KaseyJrCookies', 1783054785, '/r/MoviesThatFeelLike/comments/1um4y0g/more_cyberpunk_dystopia/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1um4y0g/more_cyberpunk_dystopia/', 'MoviesThatFeelLike', 'A neon-drenched, rain-slicked cyberpunk dystopia filled with crowded market alleys, oppressive surveillance, and decaying future-noir.', 'skipped', 'no usable images', NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1324, '1um4z8w', 'Shows (Mystery, horror, or thriller)that feel like this?', 'Shows (Mystery, horror, or thriller)that feel like this?', '', 'OkPomegranate9078', 1783054876, '/r/MoviesThatFeelLike/comments/1um4z8w/shows_mystery_horror_or_thrillerthat_feel_like/', 'https://i.redd.it/se6nwval5yah1.jpeg', 'MoviesThatFeelLike', 'Eerie, misty small towns and dark forest roads where supernatural secrets and impending dread lurk.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1325, '1um6ipd', 'Movies that feel like this?', '', '', 'SarahPleco', 1783059779, '/r/MoviesThatFeelLike/comments/1um6ipd/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1um6ipd', 'MoviesThatFeelLike', 'Grimy, sadomasochistic, and profoundly disturbing.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1326, '1um7ilg', 'Movies that feel like David Dees''s artworks?', 'Movies that feel like David Dees''s artworks?', 'Are there movies that captures the chaotic and insane vibe of this conspiracy theorist''s art pieces', 'Grainrain19', 1783063167, '/r/MoviesThatFeelLike/comments/1um7ilg/movies_that_feel_like_david_deess_artworks/', 'https://www.reddit.com/gallery/1um7ilg', 'MoviesThatFeelLike', 'Paranoid, chaotic, and hallucinatory conspiracy-drenched imagery.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1327, '1um7mkh', 'Loved the "shimmering" mescaline sequence in Images du monde visionnaire (1963) – Seeking similar visual experiences', 'Loved the "shimmering" mescaline sequence in Images du monde visionnaire – Seeking similar visual experiences', 'Hi everyone,

I recently watched Images du monde visionnaire (1963) by Éric Duvivier, featuring the mescaline experiences of Henri Michaux. While I share Michaux’s own reservations about the film’s overall execution, I was absolutely struck by the first part (the mescaline section).

Specifically, I’m looking for other films (experimental or otherwise) that capture those rapid, "shimmering" (miroitant) visual qualities: intense light streaks, frantically cut geometric patterns, vibrating optics, and a sense of pure luminous agitation. The way the film uses fast editing and optical tricks to simulate visual hallucinations really resonated with me.

Could you recommend other works that explore this specific aesthetic of light-based abstraction and flicker/scintillation? I’m interested in both classic experimental cinema and narrative films that might have sequences with a similar visual impact.

Thanks in advance for your suggestions!', 'Objective_Read_3603', 1783063554, '/r/MoviesThatFeelLike/comments/1um7mkh/loved_the_shimmering_mescaline_sequence_in_images/', 'https://youtu.be/GplnLRYhjWY?is=GJOgSqU6nYJaHNeG', 'MoviesThatFeelLike', 'Overstimulating psychedelic visuals with shimmering light streaks and frantically cut geometric patterns.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1328, '1um9mxw', 'Suggest some movies like this please.', 'Suggest some movies like this please.', '', 'Educational_Two9007', 1783070752, '/r/MoviesThatFeelLike/comments/1um9mxw/suggest_some_movies_like_this_please/', 'https://i.redd.it/9pe7jhqrgzah1.png', 'MoviesThatFeelLike', 'Eerie and surreal folk horror with dreamlike landscapes.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1329, '1umbdr4', 'Watched "The sheep detective"', 'Watched "The sheep detective"', 'I recently watched The sheep detective and i found it a very beautifully filmed movie. I mean i didn''t expect the movie to be this good when I watched the trailer but as I said it was so beautiful.

Can u guys give suggestions of this kind of movies for me to watch.', 'Gullible-Card7184', 1783076512, '/r/MoviesThatFeelLike/comments/1umbdr4/watched_the_sheep_detective/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1umbdr4/watched_the_sheep_detective/', 'MoviesThatFeelLike', 'Heartwarming, whimsical animal tales with beautiful countryside and farm settings.', 'skipped', 'no usable images', NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1330, '1umbzq4', 'Movies that feel like this??', 'Movies that feel like this??', '', 'hdhdhdhhddhhdhdhjdjd', 1783078389, '/r/MoviesThatFeelLike/comments/1umbzq4/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1umbzq4', 'MoviesThatFeelLike', 'Moody, surreal 90s therapy room with sickly yellow lighting.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1331, '1umc8sh', 'Guys question are there any movies like pulp ficition that are good', 'Guys question are there any movies like pulp ficition that are good', '', 'Frosty_Escape5793', 1783079153, '/r/MoviesThatFeelLike/comments/1umc8sh/guys_question_are_there_any_movies_like_pulp/', '/r/pulpfiction/comments/1umc8ei/guys_question_are_there_any_movies_like_pulp/', 'MoviesThatFeelLike', 'Self-aware, nonlinear, and stylized crime saga with a meta twist.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1332, '1umf2m5', 'Movies that feel like this?', 'Movies that feel like this?', '', 'Mean_Engineering7587', 1783086753, '/r/MoviesThatFeelLike/comments/1umf2m5/movies_that_feel_like_this/', 'https://v.redd.it/okb3tajds0bh1', 'MoviesThatFeelLike', 'Cyberpunk dystopia with neon-drenched cityscapes and futuristic technology.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1333, '1umfjal', 'Something''s wrong with the ENVIRONMENT', 'Something''s wrong with the environment', 'Looking for a film where something is inherently wrong, off and malevolent in a natural environment. ***Not*** looking for witch stuff. More like a twisted mother nature coming to life, or something related to the ecosystem surrounding the characters. 

I have already seen:

\-Annihilation  
\-YellowBrickRoad  
\-The Ruins  
\-The Happening

Thanks!', 'Fout99', 1783087870, '/r/MoviesThatFeelLike/comments/1umfjal/somethings_wrong_with_the_environment/', 'https://www.reddit.com/gallery/1umfjal', 'MoviesThatFeelLike', 'Eerie, malevolent natural environments where something is inherently wrong with the ecosystem.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1334, '1umgf9z', 'Looking for a French (or possibly Belgian) crime dark comedy from around 2005–2024. It takes place mostly around an empty seaside villa (Mediterranean coast). About 5–10 criminals independently try to get a briefcase full of cash. The tone is very Tarantino, all characters die.', 'Looking for a French (or possibly Belgian) crime dark comedy from around 2005–2024. It takes place mostly around an empty seaside villa (Mediterranean coast). About 5–10 criminals independently try to get a briefcase full of cash. The tone is very Tarantino, all characters die.', '', 'AcceptableLeek606', 1783089966, '/r/MoviesThatFeelLike/comments/1umgf9z/looking_for_a_french_or_possibly_belgian_crime/', '/r/MovieSuggestions/comments/1umgevb/looking_for_a_french_or_possibly_belgian_crime/', 'MoviesThatFeelLike', 'A darkly comedic, Tarantino-style crime caper set in a seaside villa where competing criminals meet their demise.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1335, '1umgiud', 'Eerie, psychological horror with NO gore', 'Eerie, psychological horror with NO gore', 'Blood and minor wounds are fine but I''d like to enjoy a good horror movie without the inevitable face smashing scene of anything of the sort, thank you ', 'opalrum', 1783090202, '/r/MoviesThatFeelLike/comments/1umgiud/eerie_psychological_horror_with_no_gore/', 'https://www.reddit.com/gallery/1umgiud', 'MoviesThatFeelLike', 'Eerie psychological dread without graphic violence.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1336, '1umgm4o', 'City melancholy but comforting', 'City melancholy but comforting', 'I fell IN LOVE with the batman animated series for this noir aesthetic. I''ve played chungkai express and american psycho on repeat, and now I need a new movie with this ambiance. ', 'hyeloop', 1783090410, '/r/MoviesThatFeelLike/comments/1umgm4o/city_melancholy_but_comforting/', 'https://www.reddit.com/gallery/1umgm4o', 'MoviesThatFeelLike', 'A moody, neon-lit urban melancholy that wraps you in a comforting noir embrace.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1337, '1umiqnl', 'Movies/Shows that feel like Emily Wants To Play (2015, horror videogame).', 'Movies/Shows that feel like Emily Wants To Play (2015, horror videogame).', 'I modified the screenshots because they were mismatched.

Have a great day guys 🫂👍', 'SmallEconomics6173', 1783095308, '/r/MoviesThatFeelLike/comments/1umiqnl/moviesshows_that_feel_like_emily_wants_to_play/', 'https://www.reddit.com/gallery/1umiqnl', 'MoviesThatFeelLike', 'Low-poly doll horror with terrifying children''s games.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1338, '1umiv2o', 'creepy anthropomorphic animals', '', '', 'OkComedian3786', 1783095590, '/r/MoviesThatFeelLike/comments/1umiv2o/creepy_anthropomorphic_animals/', 'https://www.reddit.com/gallery/1umiv2o', 'MoviesThatFeelLike', 'A disturbing menagerie of uncanny animal-human hybrids that burrow into your nightmares.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1339, '1umjanu', 'Newer movies(80s-present) that feel like 50s monster/b movies.', 'Newer movies(80s-present) that feel like 50s monster/b movies.', '', 'asapsharkyfrfr', 1783096567, '/r/MoviesThatFeelLike/comments/1umjanu/newer_movies80spresent_that_feel_like_50s/', 'https://www.reddit.com/gallery/1umjanu', 'MoviesThatFeelLike', 'A nostalgic journey into modern campy creature-features and retro sci-fi homages that channel the spirit of 1950s monster and B-movies.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1340, '1umjyft', 'Anyone know something with this type of vibe', 'Anyone know something with this type of vibe', '', 'Inevitable_Key_8889', 1783098087, '/r/MoviesThatFeelLike/comments/1umjyft/anyone_know_something_with_this_type_of_vibe/', 'https://www.reddit.com/gallery/1umjyft', 'MoviesThatFeelLike', 'Classic and introspective, with an elegant, melancholy undercurrent.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1341, '1umks84', 'Classic summer camp slasher vibes', 'Classic summer camp slasher vibes', '', 'David-SantaCarla235', 1783099983, '/r/MoviesThatFeelLike/comments/1umks84/classic_summer_camp_slasher_vibes/', 'https://www.reddit.com/gallery/1umks84', 'MoviesThatFeelLike', 'A nostalgic trip back to the golden age of summer camp slashers, filled with masked killers, teenage victims, and blood-soaked fun.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1342, '1umlgrd', 'trailer park age gap', 'trailer park age gap', 'I''m looking for a movie that''s extremely passionate and smutty but not in a 50 shades of gray way- in like a lifes-fucked-up-and-im-hopelessly-inlove-with-a-man-my-dads-age sorta way set in a trailer park with an age gap relationship being the focus. I dont care if its taboo. The more taboo the better.', 'wow_awesomesauce', 1783101577, '/r/MoviesThatFeelLike/comments/1umlgrd/trailer_park_age_gap/', 'https://www.reddit.com/gallery/1umlgrd', 'MoviesThatFeelLike', 'A fever dream of trailer-park sleaze, forbidden age-gap obsession, and heartbreak-fueled passion.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1343, '1ummm1h', 'Movies/Series that feels like this The Beach Boys MV', 'The Beach Boys MV', '', 'Lambert1551', 1783104253, '/r/MoviesThatFeelLike/comments/1ummm1h/moviesseries_that_feels_like_this_the_beach_boys/', 'https://v.redd.it/jesm2ora82bh1', 'MoviesThatFeelLike', 'Nostalgic, sun-drenched coming-of-age stories with a retro soundtrack and a touch of wistful melancholy.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1344, '1umnlsb', 'looking for stuff that feels like full blown absurd and camp 90s country music videos', '', '', 'smoothpaving', 1783106596, '/r/MoviesThatFeelLike/comments/1umnlsb/looking_for_stuff_that_feels_like_full_blown/', 'https://v.redd.it/3rlgniwne2bh1', 'MoviesThatFeelLike', 'Full blown absurd and campy 90s country music video aesthetic.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1345, '1ums3ee', 'Movies that feels like stepping on a wet dirty washcloth', 'Movies that feels like stepping on a wet dirty washcloth', 'I suddenly came to conclusion that it''s my favorite genre of cinema lol. I love movies that capture loneliness and realistic "slice of life" of troubled people. Something that feels real and leaves you with an unbearable need for a shower. 

There''s many movies that makes me feel dirty, but I don''t really like too gore-y/shock factor stuff, more like a bad life overall but not without hope and wholesome moments. Some stuff I already watched that meets the description: Midnight Cowboy (1969), Withnail and I (1987), Drugstore Cowboy (1989), Trainspotting (1996) and Fear & loathing in Las Vegas (1998) ', 'Sweaty_Ad4829', 1783117755, '/r/MoviesThatFeelLike/comments/1ums3ee/movies_that_feels_like_stepping_on_a_wet_dirty/', 'https://www.reddit.com/gallery/1ums3ee', 'MoviesThatFeelLike', 'A suffocating, grimy descent into loneliness and decay, punctuated by fleeting glimpses of humanity.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1346, '1umt325', 'Movies that feel like panic attacks', 'Movies that feel like panic attacks', 'I suffer from a LOT of anxiety and often experience feeling of impending, imminent death during my attacks.

I want a movie that feels exactly like it, bonus point if it has a happy end. Might seem like a weird request, but I think it would comfort me and make me feel less alone.', 'No_Barnacle_360', 1783120403, '/r/MoviesThatFeelLike/comments/1umt325/movies_that_feel_like_panic_attacks/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1umt325/movies_that_feel_like_panic_attacks/', 'MoviesThatFeelLike', 'Anxiety-inducing, suffocating films that replicate the visceral intensity of a panic attack.', 'skipped', 'no usable images', NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1347, '1umt9o2', 'A girl goes into a dream world', '', 'Alice in wonderland (any version)

Mirrormask

Labrynth

Pan''s labrynth 

Wizard of Oz

Coraline', 'pavi-caligula', 1783120911, '/r/MoviesThatFeelLike/comments/1umt9o2/a_girl_goes_into_a_dream_world/', 'https://www.reddit.com/gallery/1umt9o2', 'MoviesThatFeelLike', 'A girl slips into a surreal, dreamlike realm filled with wonder, danger, and visual splendor.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1348, '1umv1j7', 'Movies that have the Tell-Tale Heart feel to it', 'Movies that have the Tell-Tale Heart feel to it', '', 'Radiant-Boat-5149', 1783126099, '/r/MoviesThatFeelLike/comments/1umv1j7/movies_that_have_the_telltale_heart_feel_to_it/', 'https://i.redd.it/njbr1qkd14bh1.jpeg', 'MoviesThatFeelLike', 'Psychological tension and creeping dread with a focus on guilt.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1349, '1umv8t2', 'Horror movies that feel like this…', 'Horror movies that feel like this', 'Looking for horror movies that have a very moody atmospheric look that feels like an indie drama shot on film. ', 'sgwolfe', 1783126677, '/r/MoviesThatFeelLike/comments/1umv8t2/horror_movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1umv8t2', 'MoviesThatFeelLike', 'Moody, atmospheric horror with an indie drama aesthetic, shot on film.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1350, '1umwwfl', 'Horror/sci-fi movies perfect for the drive-in?', 'Horror/sci-fi movies perfect for the drive-in?', 'Preferably movies from the 70s and onwards but ones before that are also welcome!', 'FreakyFreak2005', 1783131500, '/r/MoviesThatFeelLike/comments/1umwwfl/horrorscifi_movies_perfect_for_the_drivein/', 'https://www.reddit.com/gallery/1umwwfl', 'MoviesThatFeelLike', 'Nostalgic retro drive-in horror and sci-fi fun with a campy, crowd-pleasing energy.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1351, '1umxn4o', 'Movies with long, epic, realistic, gritty action sequences.', '', '', 'WildCartographer5027', 1783133752, '/r/MoviesThatFeelLike/comments/1umxn4o/movies_with_long_epic_realistic_gritty_action/', 'https://www.reddit.com/gallery/1umxn4o', 'MoviesThatFeelLike', 'Relentless, gritty action with a visceral realistic edge.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1352, '1umxtzx', 'blue collar shenanigans', 'blue collar shenanigans', '', 'smoothpaving', 1783134321, '/r/MoviesThatFeelLike/comments/1umxtzx/blue_collar_shenanigans/', 'https://www.reddit.com/gallery/1umxtzx', 'MoviesThatFeelLike', 'A humorous, gritty look at working-class camaraderie and on-the-job antics.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1353, '1umypfa', 'Movies with the vibe of Arkham Asylum (1989) that are not Batman movies', '', 'It can have the vibe of any of these images, does not need to be all.', 'ThunderbirdFan75', 1783137053, '/r/MoviesThatFeelLike/comments/1umypfa/movies_with_the_vibe_of_arkham_asylum_1989_that/', 'https://www.reddit.com/gallery/1umypfa', 'MoviesThatFeelLike', 'A descent into gothic madness and surreal psychological horror.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1354, '1umzhjh', 'Movies that have gamelan-based soundtracks or are focused around the instrument and its performances.', '', 'Had these photos saved from a project, and it occured to me that there may be movies out there that include this instrument.', 'SpaceTranquil', 1783139485, '/r/MoviesThatFeelLike/comments/1umzhjh/movies_that_have_gamelanbased_soundtracks_or_are/', 'https://www.reddit.com/gallery/1umzhjh', 'MoviesThatFeelLike', 'Hypnotic gamelan percussion underscoring fantastical imagery.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1355, '1umzomd', 'The Most Hellucionary Eurotrash and Giallo Films', 'The Most Hellucionary Eurotrash and Giallo Films', '', 'TexturesOfEther', 1783140118, '/r/MoviesThatFeelLike/comments/1umzomd/the_most_hellucionary_eurotrash_and_giallo_films/', '/r/MovieRecommendations/comments/1umznfh/the_most_hellucionary_eurotrash_and_giallo_films/', 'MoviesThatFeelLike', 'Surreal and hallucinatory Eurotrash and giallo horror.', 'skipped', 'no usable images', NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1356, '1un2qnq', 'Movies that feel like growing up in West Virginia (or Appalachia) poverty', 'Movies that feel like growing up in West Virginia (or Appalachia) poverty', '', 'throwaway19998777999', 1783150385, '/r/MoviesThatFeelLike/comments/1un2qnq/movies_that_feel_like_growing_up_in_west_virginia/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1un2qnq/movies_that_feel_like_growing_up_in_west_virginia/', 'MoviesThatFeelLike', 'The oppressive yet familiar weight of rural Appalachian poverty, with its coal-dusted towns, tight-knit families, and the resilience forged in hardship.', 'skipped', 'no usable images', NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1357, '1un3j5k', 'Slow agonizing urban warfare', 'Slow agonizing urban warfare', '', 'Callsign_Aztec', 1783153212, '/r/MoviesThatFeelLike/comments/1un3j5k/slow_agonizing_urban_warfare/', 'https://www.reddit.com/gallery/1un3j5k', 'MoviesThatFeelLike', 'A grim, tense, and agonizingly slow burn through crumbling urban battlefields.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1358, '1unqez3', 'Movies that feel like abandoned NYC urban decay', 'Movies that feel like abandoned NYC urban decay', '', 'Placebopaddywagon', 1783218048, '/r/MoviesThatFeelLike/comments/1unqez3/movies_that_feel_like_abandoned_nyc_urban_decay/', 'https://www.reddit.com/gallery/1unqez3', 'MoviesThatFeelLike', 'Gritty, decaying New York City streets filled with urban blight, danger, and a palpable sense of abandonment.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1359, '1utkqs3', 'Movies that feel like this?', 'Movies that feel like this?', 'Games are also fine', 'Limp-Secretary6608', 1783777992, '/r/MoviesThatFeelLike/comments/1utkqs3/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1utkqs3', 'MoviesThatFeelLike', 'Dark, gothic fantasy with Victorian-era horror and monster hunting.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1360, '1v3kqdp', 'Movies with a similar vibe to *Drive 2011*', 'Movies with a similar vibe to *Drive 2011*', 'I’ve watched the movie \*Drive\* countless times, as well as director Refn’s \*Only God Forgives\* and \*Pusher\*. I’ve always been captivated by the unique atmosphere of these films. Do you have any other movies with a similar vibe to recommend?', 'Reasonable-Meet-7923', 1784736829, '/r/MoviesThatFeelLike/comments/1v3kqdp/movies_with_a_similar_vibe_to_drive_2011/', 'https://www.reddit.com/gallery/1v3kqdp', 'MoviesThatFeelLike', 'Neon-drenched, brooding urban tension with a synth-laden, slow-burn atmosphere.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1361, '1viicws', 'Discover the name of that movie that I will describe', '', '', 'Remarkable-Work-5837', 1786151402, '/r/MoviesThatFeelLike/comments/1viicws/discover_the_name_of_that_movie_that_i_will/', '/r/tvshow/comments/1viicf9/discover_the_name_of_that_movie_that_i_will/', 'MoviesThatFeelLike', 'Curious search for an unnamed film.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1362, '1viit1e', 'this postal 1 fanart', '', '', 'cowgirl-electra', 1786152714, '/r/MoviesThatFeelLike/comments/1viit1e/this_postal_1_fanart/', 'https://i.redd.it/dtro44y112ih1.jpeg', 'MoviesThatFeelLike', 'Dark, gritty, violent atmosphere with supernatural anti-heroes.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1363, '1vij5w9', 'Can you find any movies that feel like this?', 'Can you find any movies that feel like this?', '', 'Ultrakirby78', 1786153770, '/r/MoviesThatFeelLike/comments/1vij5w9/can_you_find_any_movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vij5w9', 'MoviesThatFeelLike', 'A haunting, surreal blend of Gothic horror and psychedelic imagery, evoking vintage European genre cinema.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1364, '1vijkqc', 'internet gothic, MMORPG escapism, teenage doom', 'internet gothic, MMORPG escapism, teenage doom', 'i was mutuals with grimelords on tumblr years ago, and this is one of the best works of flash fiction i’ve ever read. (the other photos are from Serial Experiments Lain and All About Lily Chou-Chou)

copying the text here as it’s hard to read in the photo:

There''s six guys who live in this flat and all they do all day is play WoW and watch movies. Waking up at 2pm every day and there''s always just someone asleep on the bed near all the multimonitor computer setups. There''s always music playing and it feels like a recovery day every day, padding around blearily in pyjamas or underwear. Old hoodies from defunct school teams. They''ve got this system where they''re selling their excess computing power to companies and hosting all this warez, and they''re stealing the internet from the business next door anyway and getting welfare on top of all that. They''re self sufficient and never go outdoors except to buy more fast food, and even then only in the dark. But then one of them wakes up dead some heavy afternoon. He''s just dead and they don''t know why but maybe the floor covered in fast food wrappings is a clue. They don''t want to tell the cops because of the purgatory den they live in and the illegality that supports it, and as far as they know he never had any actual parents. So it''s trouble. It''s taking a long trip out to the forest and thinking about how stars are so far away for the first time in a long time. It''s sweating in the cold air and digging a hole all night with your brand new shovels to leave him alone in. And it''s a long few days cracking all his passwords to keep his identity and associated payments persisting. Until the rhythm of waking up every day at 2pm to play WoW for nine hours and half watch a movie on your other monitor takes over again. It''s the same as it ever was except now there''s a room no one ever goes in.', 'LegitimateMention158', 1786154995, '/r/MoviesThatFeelLike/comments/1vijkqc/internet_gothic_mmorpg_escapism_teenage_doom/', 'https://www.reddit.com/gallery/1vijkqc', 'MoviesThatFeelLike', 'internet gothic, MMORPG escapism, teenage doom', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1365, '1viju8n', 'Movies with the vibe or setting', '', '', 'Euphoric_Access_7508', 1786155778, '/r/MoviesThatFeelLike/comments/1viju8n/movies_with_the_vibe_or_setting/', 'https://www.reddit.com/gallery/1viju8n', 'MoviesThatFeelLike', 'Dark, misty forest atmosphere, blue-hued and moody.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1366, '1vik1bc', 'Movies with a dark, tropical theme that matches these images', 'Movies with a dark, tropical theme that matches these images', '', 'SpaceTranquil', 1786156354, '/r/MoviesThatFeelLike/comments/1vik1bc/movies_with_a_dark_tropical_theme_that_matches/', 'https://www.reddit.com/gallery/1vik1bc', 'MoviesThatFeelLike', 'A dark, tropical atmosphere with exotic, mysterious, and sometimes sinister undertones.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1367, '1vil37i', 'Movies that feel like these illustrations?', 'Movies that feel like these illustrations?', 'Looking for ultimate feeling of coziness, comfort, safety, nature etc etc.   
Have watched all studio ghibli movies, Peter Rabbit and Wes Anderson😭  
Can be cartoons, regular movies, shows, whatever!!', 'justlookinghello', 1786159475, '/r/MoviesThatFeelLike/comments/1vil37i/movies_that_feel_like_these_illustrations/', 'https://www.reddit.com/gallery/1vil37i', 'MoviesThatFeelLike', 'Cozy, comforting nature scenes that evoke a sense of safety and nostalgic childhood wonder.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1368, '1vilnb3', 'Movies that feel like this', '', 'I''m talking about a feeling of inhabitation and abandonment at the same time, kinda merged with nature and scenery

Not sure how to describe it ', 'Original_Danta', 1786161171, '/r/MoviesThatFeelLike/comments/1vilnb3/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vilnb3', 'MoviesThatFeelLike', 'A humid, tropical atmosphere of places simultaneously inhabited and abandoned, overgrown with lush vegetation.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1369, '1vim9v2', 'Could you recommend productions that are happy and bring peace, and make you feel a sense of teamwork and family?', 'Could you recommend productions that are happy and bring peace, and make you feel a sense of teamwork and family?', '', 'Realbirisi', 1786163080, '/r/MoviesThatFeelLike/comments/1vim9v2/could_you_recommend_productions_that_are_happy/', 'https://i.redd.it/pp2ksnbiv2ih1.jpeg', 'MoviesThatFeelLike', 'Uplifting and peaceful with a sense of family and teamwork.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1370, '1vinlc5', 'Dark souls 1', 'Dark souls 1', 'Dark fantasy that doesn’t over-explain itself', 'melody74u', 1786167322, '/r/MoviesThatFeelLike/comments/1vinlc5/dark_souls_1/', 'https://www.reddit.com/gallery/1vinlc5', 'MoviesThatFeelLike', 'A dark fantasy realm where lore is felt rather than told, steeped in melancholic grandeur and oppressive silence.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1371, '1visym7', 'please help me find films that have the same vibe as ''Here''s Where The Story Ends'' by The Sundays', 'Films with the same vibe as ''Here''s Where The Story Ends'' by The Sundays', 'this song gives me such bittersweet romance vibes. though anything will do for this song since I enjoy it a lot : )', 'LimpLicker47', 1786186530, '/r/MoviesThatFeelLike/comments/1visym7/please_help_me_find_films_that_have_the_same_vibe/', 'https://v.redd.it/a6mhgh5dt4ih1', 'MoviesThatFeelLike', 'Bittersweet romance, nostalgic and wistful.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1372, '1viuxkd', 'Movies that feel like this…', 'Movies that feel like this…', '', 'moon_burger', 1786192625, '/r/MoviesThatFeelLike/comments/1viuxkd/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1viuxkd', 'MoviesThatFeelLike', 'Sky-high Manhattan, glass and steel, a city of vertical ambition and sprawling views.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1373, '1vj0q12', 'What is the most dreamlike, oneiric film noirs?', 'What is the most dreamlike, oneiric film noirs?', '', 'wedreaminsideadream', 1786207451, '/r/MoviesThatFeelLike/comments/1vj0q12/what_is_the_most_dreamlike_oneiric_film_noirs/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vj0q12/what_is_the_most_dreamlike_oneiric_film_noirs/', 'MoviesThatFeelLike', 'A dreamlike, nightmarish noir atmosphere filled with surreal imagery and disorientation.', 'skipped', 'no usable images', NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1374, '1vj2c16', 'films that feel like this…', 'films that feel like this…', '', 'Intelligent_Split565', 1786211338, '/r/MoviesThatFeelLike/comments/1vj2c16/films_that_feel_like_this/', 'https://www.reddit.com/gallery/1vj2c16', 'MoviesThatFeelLike', 'Innocence, imagination, and fragility set in bucolic realism.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1375, '1vj38nk', 'Movies with that feels like this?', 'Movies with that feels like this?', '', 'chaiegai', 1786213484, '/r/MoviesThatFeelLike/comments/1vj38nk/movies_with_that_feels_like_this/', 'https://www.reddit.com/gallery/1vj38nk', 'MoviesThatFeelLike', 'unknown', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1376, '1vj3bw5', 'Movies that feel like or take place in Kowloon, the walled city?', 'Movies that feel like or take place in Kowloon, the walled city?', '', 'Jellypathicdream', 1786213703, '/r/MoviesThatFeelLike/comments/1vj3bw5/movies_that_feel_like_or_take_place_in_kowloon/', 'https://www.reddit.com/gallery/1vj3bw5', 'MoviesThatFeelLike', 'A neon-drenched, claustrophobic labyrinth of crumbling vertical slums pulsing with chaotic life and danger.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1377, '1vj3f4k', 'movies that feel like this?', 'movies that feel like this?', 'it doesn’t have to have that architecture like the first pic, but is there any films with this kind of lighting that are actually interesting? usually movies with this aesthetic are nearly silent majority of the time 💔', 'dobryoesty', 1786213921, '/r/MoviesThatFeelLike/comments/1vj3f4k/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vj3f4k', 'MoviesThatFeelLike', 'Gloomy, overcast suburban landscapes bathed in muted, cold light, evoking quiet isolation and lurking unease.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1378, '1vj3mku', 'Movies that feel like this?', 'Movies that feel like this?', '', 'Fair_Network6712', 1786214426, '/r/MoviesThatFeelLike/comments/1vj3mku/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vj3mku', 'MoviesThatFeelLike', 'A disorienting labyrinth of arrows and surreal architecture, evoking mind-bending twists and psychological entrapment.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1379, '1vj3zez', 'Movies that feel like this?', 'Movies that feel like this?', '', 'fourteen47', 1786215314, '/r/MoviesThatFeelLike/comments/1vj3zez/movies_that_feel_like_this/', 'https://i.redd.it/a4xhai4777ih1.jpeg', 'MoviesThatFeelLike', '', 'skipped', 'no vibe summary; no enriched recommendation matches', NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1380, '1vj4y2e', 'Most liminal movies/shows/scenes', 'Most liminal movies/shows/scenes', '', 'Rikoh_Suave', 1786217686, '/r/MoviesThatFeelLike/comments/1vj4y2e/most_liminal_moviesshowsscenes/', '/r/LiminalSpace/comments/1vj10dl/most_liminal_moviesshowssces/', 'MoviesThatFeelLike', 'A search for movies, shows, or scenes that evoke eerily transitional, in-between spaces.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1381, '1vj5gm8', 'Movies like a nightmare!', 'Movies like a nightmare', '', 'That_Firefly', 1786219026, '/r/MoviesThatFeelLike/comments/1vj5gm8/movies_like_a_nightmare/', 'https://www.reddit.com/gallery/1vj5gm8', 'MoviesThatFeelLike', 'A dark, gothic Halloween night filled with spectral figures and autumnal dread.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1382, '1vj8un4', 'Movies or shows that are like this', 'Movies or shows that are like this', 'I’m looking for crime film style, but it doesn’t have to be crime film', 'nyancat2013', 1786227855, '/r/MoviesThatFeelLike/comments/1vj8un4/movies_or_shows_that_are_like_this/', 'https://www.reddit.com/gallery/1vj8un4', 'MoviesThatFeelLike', 'A moody, vintage crime atmosphere with classic noir undertones.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1383, '1vj8xtr', 'Movies/TV shows that feel like a combination of Jack Sparrow with Vladimir and Estragon from Waiting for Godot, soundtracked by 80s Tom Waits...', '', 'I''m aware this is incredibly specific but if you know these things you''ll know exactly the vibe I''m looking for.', 'metaphysical-loser', 1786228093, '/r/MoviesThatFeelLike/comments/1vj8xtr/moviestv_shows_that_feel_like_a_combination_of/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vj8xtr/moviestv_shows_that_feel_like_a_combination_of/', 'MoviesThatFeelLike', 'Eccentric, drunken absurdism with a bohemian, gritty 80s Tom Waits soundtrack.', 'skipped', 'no usable images', NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1384, '1vj99ze', 'Late 1980s to early 1990s American harshness realism', 'Late 1980s to early 1990s American harshness realism', '', 'smoothpaving', 1786228995, '/r/MoviesThatFeelLike/comments/1vj99ze/late_1980s_to_early_1990s_american_harshness/', 'https://i.redd.it/8inlcsfvb8ih1.jpeg', 'MoviesThatFeelLike', 'Unflinching harsh American realism from the late 1980s to early 1990s.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1385, '1vja0bf', 'Movies that gives off older brother core?', '', '', 'wweking_08', 1786230984, '/r/MoviesThatFeelLike/comments/1vja0bf/movies_that_gives_off_older_brother_core/', 'https://www.reddit.com/gallery/1vja0bf', 'MoviesThatFeelLike', '1990s-2000s nostalgic male teen energy with video games, rebellion, and hangout vibes.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1386, '1vjaknb', 'You aren’t supposed to be here (Spoilers: Lake Mungo, Kane Pixels’ Backrooms, No Through Road)', 'You aren’t supposed to be here (Spoilers: Lake Mungo, Kane Pixels’ Backrooms, No Through Road)', 'Horror films where someone finds something that isn’t meant for them, or any human being, and probably don’t make it out. Bonus points if a character/the main character(s) die, and we get footage from before they died.', 'SwordfishSimple5472', 1786232591, '/r/MoviesThatFeelLike/comments/1vjaknb/you_arent_supposed_to_be_here_spoilers_lake_mungo/', 'https://www.reddit.com/gallery/1vjaknb', 'MoviesThatFeelLike', 'A palpable dread of uncovering something never meant to be seen, often leading to a grim fate captured on found footage.', 'publishable', NULL, NULL, '2026-08-09 02:29:31', '2026-08-09 02:29:31');
