-- 0091_seed_20260810T023351Z_01_posts.sql: data seed from pipeline:load run.
-- Generated:  2026-08-10T02:34:01.216047+00:00
-- Run started: 2026-08-10T02:33:51.492167+00:00
-- Source: data/working/load manifest from this run.
--
-- Idempotent: every INSERT is INSERT OR IGNORE, keyed by the
-- table's natural unique constraint.  Wrangler's migration
-- tracking normally prevents re-apply; the OR IGNORE is
-- defense in depth for partial / interrupted re-runs.
--
-- Chunk: 01_posts (1/5)
-- Tables: imported_vibe_posts.
-- Pipeline-state tables (processing_runs, pipeline_artifacts)
-- are intentionally excluded — they're per-run bookkeeping.

INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1387, '1ujz2rm', '"Movies that feel like a northwest small town with a myste.."', 'Movies that feel like a northwest small town with a myste..', '', 'CodGroundbreaking803', 1782847879, '/r/MoviesThatFeelLike/comments/1ujz2rm/movies_that_feel_like_a_northwest_small_town_with/', 'https://i.redd.it/nsv3r60qpwyg1.jpeg', 'MoviesThatFeelLike', 'Eerie Pacific Northwest small-town mystery with surreal undertones.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1388, '1uk0dnv', 'surviving the end of the world in a underground bunker', 'surviving the end of the world in a underground bunker', '', 'CodGroundbreaking803', 1782850782, '/r/MoviesThatFeelLike/comments/1uk0dnv/surviving_the_end_of_the_world_in_a_underground/', 'https://www.reddit.com/gallery/1uk0dnv', 'MoviesThatFeelLike', 'Claustrophobic survival in post-apocalyptic underground refuges', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1389, '1uk1cf0', 'I need a movie or a series or a turkish series with these vibes please', '', '', 'Consistent-Fox3396', 1782852917, '/r/MoviesThatFeelLike/comments/1uk1cf0/i_need_a_movie_or_a_series_or_a_turkish_series/', 'https://www.reddit.com/gallery/1uk1cf0', 'MoviesThatFeelLike', 'Eerie, rain-soaked atmosphere with a sense of mystery and lurking dread.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1390, '1uk3tis', 'The horrors have become mundane', 'The horrors have become mundane', 'I need something where cosmic horrors have just become a average every day thing for people, something mind altering and horrifying for us is just another workday for the people of this world', 'EmergencySpare7939', 1782858730, '/r/MoviesThatFeelLike/comments/1uk3tis/the_horrors_have_become_mundane/', 'https://www.reddit.com/gallery/1uk3tis', 'MoviesThatFeelLike', 'Cosmic horror as mundane routine', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1391, '1uk4jjd', 'The horrors have become mundane', 'The horrors have become mundane', 'Something where cosmic level horror has just become a average every day thing for people, something mind altering and horrifying for us is just another workday for the people of this world', 'EmergencySpare7939', 1782860537, '/r/MoviesThatFeelLike/comments/1uk4jjd/the_horrors_have_become_mundane/', 'https://www.reddit.com/gallery/1uk4jjd', 'MoviesThatFeelLike', 'Cosmic horror reduced to a daily grind, where eldritch anomalies are just part of the job.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1392, '1uk4s5u', 'Movies with a vibe similar to Widow''s Bay', '', 'Widow''s Bay captured the cosy, spooky vibe that I love to watch.

Hard to describe the vibe but you know it when you see it.

\-Spooky and mysterious but not in a way that is scary or disturbing

\- Picturesque, leafy and you feel the cosy sense of the weather

\- Nostalgic vibe, even the font evokes the feeling

\- Funny in a quirky way

\- Reminds me of something Stephen King would write

Would love to see if anyone has recommendations for movies that have a similar vibe that I may not have already seen.

Thank you for your recommendations!', 'Classic_Recover2114', 1782861124, '/r/MoviesThatFeelLike/comments/1uk4s5u/movies_with_a_vibe_similar_to_widows_bay/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uk4s5u/movies_with_a_vibe_similar_to_widows_bay/', 'MoviesThatFeelLike', 'Cozy, spooky, small-town atmosphere with picturesque settings, quirky humor, and a nostalgic Stephen King feel.', 'skipped', 'no usable images', NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1393, '1uk6bel', 'movies that feel like dinner in america', 'movies that feel like dinner in america', 'i want one million more dinner in americas but unfortunately there is only one so i will settle for movies that feel similar ', 'fignewtonenjoyer', 1782865076, '/r/MoviesThatFeelLike/comments/1uk6bel/movies_that_feel_like_dinner_in_america/', 'https://i.redd.it/tq9o0vv7hiah1.jpeg', 'MoviesThatFeelLike', 'A rebellious, anarchic love story blending deadpan humor, punk energy, and dark romance.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1394, '1uk8fde', 'Coming of age romance/tragedies that feel like British boarding school meets English countryside', '', 'Image listed:

* Never Let Me Go (2010)
* The Theory of Everything (2014)
* Burberry Fall/Winter 2006 ad campaign
* Goodbye Christopher Robin (2017)
* Christopher Robin (2018)', 'Lissandra_Freljord', 1782871010, '/r/MoviesThatFeelLike/comments/1uk8fde/coming_of_age_romancetragedies_that_feel_like/', 'https://www.reddit.com/gallery/1uk8fde', 'MoviesThatFeelLike', 'Melancholic young love unfolds against the backdrop of British boarding schools and idyllic countryside.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1395, '1ukbjpu', 'Stories with cosmic horror undertones', 'Stories with cosmic horror undertones', '[deleted]', '[deleted]', 1782880216, '/r/MoviesThatFeelLike/comments/1ukbjpu/stories_with_cosmic_horror_undertones/', '', 'MoviesThatFeelLike', 'Dread-inducing stories of cosmic insignificance and otherworldly terror.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1396, '1ukbkk7', 'Stories with cosmic horror undertones', 'Stories with cosmic horror undertones', '', 'LeonardoKlotzTomaz', 1782880285, '/r/MoviesThatFeelLike/comments/1ukbkk7/stories_with_cosmic_horror_undertones/', 'https://www.reddit.com/gallery/1ukbkk7', 'MoviesThatFeelLike', 'A pervasive sense of otherworldly dread and existential unease.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1397, '1ukbnet', 'Movies that use and abuse the red filter', 'Movies that use and abuse the red filter', '', 'LeonardoKlotzTomaz', 1782880523, '/r/MoviesThatFeelLike/comments/1ukbnet/movies_that_use_and_abuse_the_red_filter/', 'https://www.reddit.com/gallery/1ukbnet', 'MoviesThatFeelLike', 'A visceral, red-drenched nightmare of sensory overload and intense violence.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1398, '1ukbyc3', 'Nepal/himalayas kinda vibe?', 'Nepal/himalayas kinda vibe?', '', 'cheesiestboy', 1782881455, '/r/MoviesThatFeelLike/comments/1ukbyc3/nepalhimalayas_kinda_vibe/', 'https://www.reddit.com/gallery/1ukbyc3', 'MoviesThatFeelLike', 'Remote Himalayan mysticism and awe-inspiring peaks.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1399, '1ukc80k', 'Movies that feel like Blade Runner', 'Movies that feel like Blade Runner', 'Big Trouble in Little China is one of my favourites besides Blade Runner. I love moody rain combined with a dystopian feel, neon lights and synth music. ', 'angvlsp1t', 1782882288, '/r/MoviesThatFeelLike/comments/1ukc80k/movies_that_feel_like_blade_runner/', 'https://www.reddit.com/gallery/1ukc80k', 'MoviesThatFeelLike', 'Moody, rain-soaked dystopian cityscapes with neon lights and synth music.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1400, '1ukeap4', 'Movies where the title unexpectedly appears right after the screen turns black, in either the opening scene or the ending scene.', '', '', 'Garidur', 1782889140, '/r/MoviesThatFeelLike/comments/1ukeap4/movies_where_the_title_unexpectedly_appears_right/', 'https://www.reddit.com/gallery/1ukeap4', 'MoviesThatFeelLike', 'A dramatic title card drop after a black screen.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1401, '1ukejn0', 'Any other Combined genres films?', '', 'Loved this “part samurai, part cowboy and part ‘Mad Max’ all with a modern twist” film.   
Any others out there (not Anime)?', 'FootballAmbitious916', 1782889976, '/r/MoviesThatFeelLike/comments/1ukejn0/any_other_combined_genres_films/', 'https://i.redd.it/pe7rm4h9jkah1.jpeg', 'MoviesThatFeelLike', 'An adrenaline-fueled genre mash-up of samurai, western, and post-apocalyptic action with a modern, playful twist.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1402, '1ukhnlw', 'Movies that feel like this artwork', 'Movies that feel like this artwork', 'Any genre, but strongly prefer live-action. The lesser known, the better!', 'savvylee17', 1782901034, '/r/MoviesThatFeelLike/comments/1ukhnlw/movies_that_feel_like_this_artwork/', 'https://i.redd.it/tjs6wx9jflah1.jpeg', 'MoviesThatFeelLike', 'A dreamy, autumnal folk-horror atmosphere with an ethereal, surreal edge.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1403, '1uki6bz', 'Movies that feel like "I Believe In Unicorns"', 'Movies that feel like "I Believe In Unicorns"', 'What I really liked in this movie and would like to see again: theme of losing innocence, visuals, landscapes, kinda unsettling, stressful vibe', 'No_Barnacle_360', 1782902779, '/r/MoviesThatFeelLike/comments/1uki6bz/movies_that_feel_like_i_believe_in_unicorns/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uki6bz/movies_that_feel_like_i_believe_in_unicorns/', 'MoviesThatFeelLike', 'A dreamy yet unsettling exploration of lost innocence amidst haunting landscapes.', 'skipped', 'no usable images', NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1404, '1ukpsin', 'Movies that feel like these pics!', 'Movies that feel like these pics!', 'Don’t say aquamarine or h2o or mako mermaids please! I’ve already watched those like a million times😭', 'moon_rain06', 1782921705, '/r/MoviesThatFeelLike/comments/1ukpsin/movies_that_feel_like_these_pics/', 'https://www.reddit.com/gallery/1ukpsin', 'MoviesThatFeelLike', 'Nostalgic beachy teen summer fantasy with mermaid dreams.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1405, '1ukpwji', 'Need a movie recommendation that feels like this.', 'Need a movie recommendation that feels like this.', '', 'aianneeee', 1782921938, '/r/MoviesThatFeelLike/comments/1ukpwji/need_a_movie_recommendation_that_feels_like_this/', 'https://www.reddit.com/gallery/1ukpwji', 'MoviesThatFeelLike', 'A portrait of isolation, emotional numbness, and urban desolation.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1406, '1ukqvkq', 'I’m thinking of ending things', 'I’m thinking of ending things', 'What is a movie like i’m thinking of ending things that isn’t the netflix movie they made? I loved the book with the unsettling vibe. Extra points if it also has a farmhouse in winter setting ', 'Plus_Ad1745', 1782924097, '/r/MoviesThatFeelLike/comments/1ukqvkq/im_thinking_of_ending_things/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1ukqvkq/im_thinking_of_ending_things/', 'MoviesThatFeelLike', 'Unsettling psychological surrealism with isolated wintry atmosphere.', 'skipped', 'no usable images', NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1407, '1uku2du', 'Movies that feel like the song, loose cannon by puzzle', 'Movies that feel like the song, loose cannon by puzzle', '[deleted]', '[deleted]', 1782931092, '/r/MoviesThatFeelLike/comments/1uku2du/movies_that_feel_like_the_song_loose_cannon_by/', '', 'MoviesThatFeelLike', 'Seeking movies that match the unpredictable, chaotic energy of a loose cannon.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1408, '1uku3lr', 'Movies that feel like the song: loose cannon by puzzle', '', 'The colorful, energetic, rebel and somehow nostagic feeling of being lost as a young', 'miqlo777', 1782931167, '/r/MoviesThatFeelLike/comments/1uku3lr/movies_that_feel_like_the_song_loose_cannon_by/', 'https://i.redd.it/94l3b6rqxnah1.jpeg', 'MoviesThatFeelLike', 'Colorful, energetic, rebellious nostalgia of youth lost.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1409, '1ukvfka', 'Movies with scenes like these', '', '', 'songedanslaniiut', 1782934031, '/r/MoviesThatFeelLike/comments/1ukvfka/movies_with_scenes_like_these/', 'https://www.reddit.com/gallery/1ukvfka', 'MoviesThatFeelLike', 'Surreal, melancholic existential wonder.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1410, '1ukw4rm', 'This', '', 'By Carlijn Jacobs ', 'Jellypathicdream', 1782935599, '/r/MoviesThatFeelLike/comments/1ukw4rm/this/', 'https://i.redd.it/8vtokz5xaoah1.jpeg', 'MoviesThatFeelLike', 'Eerie, theatrical, and dreamlike with a Japanese aesthetic.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1411, '1ukx31a', 'Movies and TV shows where language barriers are part of the plot', 'Movies and TV shows where language barriers are part of the plot', '', 'DreamerRealityArt', 1782937719, '/r/MoviesThatFeelLike/comments/1ukx31a/movies_and_tv_shows_where_language_barriers_are/', 'https://www.reddit.com/gallery/1ukx31a', 'MoviesThatFeelLike', 'Stories where linguistic and cultural divides drive both conflict and connection.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1412, '1ukygba', 'Movies and shows that feel like this.', 'Movies and shows that feel like Joe Pera Talks With You', 'Obviously i already know about Joe Pera Talks With You!', 'Krispytreat35', 1782940786, '/r/MoviesThatFeelLike/comments/1ukygba/movies_and_shows_that_feel_like_this/', 'https://www.reddit.com/gallery/1ukygba', 'MoviesThatFeelLike', 'Surreally sincere, calm comfort shows and films with gentle, earnest humor and heartfelt, mundane wonder.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1413, '1ukyjx0', 'Movies That feel like this.', 'Movies That feel like this', '', 'Shifa6612', 1782941022, '/r/MoviesThatFeelLike/comments/1ukyjx0/movies_that_feel_like_this/', 'https://i.redd.it/k1e1k2h1roah1.jpeg', 'MoviesThatFeelLike', 'Gothic suspense in an isolated, foreboding mansion with dark secrets.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1414, '1ul6vig', 'Organic Industrial Design', 'Organic Industrial Design', '', 'gustyaeroplane81', 1782962931, '/r/MoviesThatFeelLike/comments/1ul6vig/organic_industrial_design/', 'https://www.reddit.com/gallery/1ul6vig', 'MoviesThatFeelLike', 'Dark biomechanical industrial aesthetic', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1415, '1ul70f7', 'Movies that feel like this', '', '', 'SecondStarpilot', 1782963318, '/r/MoviesThatFeelLike/comments/1ul70f7/movies_that_feel_like_this/', 'https://i.redd.it/8l52oubclqah1.jpeg', 'MoviesThatFeelLike', 'Teenage nihilism etched in monochrome.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1416, '1ulbcja', 'Dumb question but is there any movies with this vibe', 'Dumb question but is there any movies with this vibe', '[removed]', 'LimpBlzkit', 1782977262, '/r/MoviesThatFeelLike/comments/1ulbcja/dumb_question_but_is_there_any_movies_with_this/', 'https://i.redd.it/pk4chx3tqrah1.jpeg', 'MoviesThatFeelLike', 'No explicit atmosphere described in the post.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1417, '1ulnjbb', 'Movies feels like this Neon grip mixed with some Action or Drama?', 'Movies feels like this Neon grip mixed with some Action or Drama?', 'courtesy: Revenge 2017', 'Bulky_Meet4528', 1783010762, '/r/MoviesThatFeelLike/comments/1ulnjbb/movies_feels_like_this_neon_grip_mixed_with_some/', 'https://www.reddit.com/gallery/1ulnjbb', 'MoviesThatFeelLike', 'Neon-drenched revenge thriller with gritty action and stylized drama.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1418, '1ulya68', '“I don’t know whether to laugh or be scared”', 'I don’t know whether to laugh or be scared', 'Looking for recommendations for horror movies where you don’t know whether you should laugh or hide under the covers.

I should say that I’m not looking for horror comedies, but instead movies that have a scary tone and use funny moments to make you uneasy and catch you off guard.', 'PomegranateRelative', 1783035477, '/r/MoviesThatFeelLike/comments/1ulya68/i_dont_know_whether_to_laugh_or_be_scared/', 'https://www.reddit.com/gallery/1ulya68', 'MoviesThatFeelLike', 'Horror that unnerves with abrupt humor, keeping you teetering between anxious laughter and genuine dread.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1419, '1utfugp', 'I want movies similar to this noir vibes', 'I want movies similar to this noir vibes', '', 'OBIWAN22334', 1783763557, '/r/MoviesThatFeelLike/comments/1utfugp/i_want_movies_similar_to_this_noir_vibes/', 'https://www.reddit.com/gallery/1utfugp', 'MoviesThatFeelLike', 'Dark, rainy cityscapes, neon-lit nights, and a moody noir ambiance filled with mystery and jazz.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1420, '1vjbatx', 'Movies that feel like', 'Movies that feel like', '', 'Apprehensive-Bar-359', 1786234612, '/r/MoviesThatFeelLike/comments/1vjbatx/movies_that_feel_like/', 'https://www.reddit.com/gallery/1vjbatx', 'MoviesThatFeelLike', 'A moody, neo-noir atmosphere with rain-slicked streets, shadows, and a sense of melancholy violence.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1421, '1vjbpah', 'Movies feel like that?', '', '', 'Serious-Pea8972', 1786235785, '/r/MoviesThatFeelLike/comments/1vjbpah/movies_feel_like_that/', 'https://i.redd.it/fw5ktl92w8ih1.jpeg', 'MoviesThatFeelLike', 'Dark, unsettling, and mysterious atmosphere.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1422, '1vjejhz', 'What are some films that look like this?', '', '', 'Ultrakirby78', 1786244390, '/r/MoviesThatFeelLike/comments/1vjejhz/what_are_some_films_that_look_like_this/', 'https://www.reddit.com/gallery/1vjejhz', 'MoviesThatFeelLike', 'Dark biomechanical horror-fantasy with grotesque organic-mechanical fusion, evoking Japanese tokusatsu and grim otherworldly aesthetics.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1423, '1vjfv0q', 'Movies/shows/animation that feel like richly decorated and surreal medieval fantasy?', 'Movies/shows/animation that feel like richly decorated and surreal medieval fantasy?', '', 'Mist156', 1786248501, '/r/MoviesThatFeelLike/comments/1vjfv0q/moviesshowsanimation_that_feel_like_richly/', 'https://www.reddit.com/gallery/1vjfv0q', 'MoviesThatFeelLike', 'Richly decorated and surreal medieval fantasy', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1424, '1vjgooo', 'Movies that feel like can''t afford it..', 'Movies that feel like can''t afford it..', '[removed]', '3amthoughts786', 1786251160, '/r/MoviesThatFeelLike/comments/1vjgooo/movies_that_feel_like_cant_afford_it/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vjgooo/movies_that_feel_like_cant_afford_it/', 'MoviesThatFeelLike', 'Low-budget movies with a cheap, scrappy atmosphere', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1425, '1vjii5x', 'Movies or TV shows with this vibe', '', '', 'No-Breakfast476', 1786257339, '/r/MoviesThatFeelLike/comments/1vjii5x/movies_or_tv_shows_with_this_vibe/', 'https://www.reddit.com/gallery/1vjii5x', 'MoviesThatFeelLike', 'A desolate, post-apocalyptic mood where abandoned urban ruins are slowly reclaimed by nature under an eerie, oppressive silence.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1426, '1vjj66l', 'Someone pls give me a movie that will ruin me and I sit in silence for 30 minutes afterward', 'Someone please give me a movie that will ruin me and I sit in silence for 30 minutes afterward', '', 'alienspinach', 1786259614, '/r/MoviesThatFeelLike/comments/1vjj66l/someone_pls_give_me_a_movie_that_will_ruin_me_and/', 'https://v.redd.it/x6m8xewx21ih1', 'MoviesThatFeelLike', 'Devastating films that leave you emotionally ruined and sitting in stunned silence.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1427, '1vjk381', 'Crazy, Colourful, Sci-Fi/Monster Pre-2000s Fun Like Hiruko The Goblin, Zeiram And School In The Crosshairs', 'Crazy, Colourful, Sci-Fi/Monster Pre-2000s Fun Like Hiruko The Goblin, Zeiram And School In The Crosshairs', 'Anybody got anymore films that are like these? I’ve watched others similar, but obviously I’m hungry for more and more haha. 

Thank you!', 'isopodsoup_', 1786262849, '/r/MoviesThatFeelLike/comments/1vjk381/crazy_colourful_scifimonster_pre2000s_fun_like/', 'https://i.redd.it/826qmhej4bih1.jpeg', 'MoviesThatFeelLike', 'Colorful and crazy sci-fi/monster mayhem from before the 2000s.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1428, '1vjnkhm', 'Cozy futuristic comedy that doesn’t take itself too seriously', 'Cozy futuristic comedy that doesn’t take itself too seriously', '', 'pinkdragapult', 1786275179, '/r/MoviesThatFeelLike/comments/1vjnkhm/cozy_futuristic_comedy_that_doesnt_take_itself/', 'https://www.reddit.com/gallery/1vjnkhm', 'MoviesThatFeelLike', 'Playful retro-futuristic coziness with a lighthearted, comedic, and campy charm.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1429, '1vjox2g', 'What’s an "end of the world" movie that actually feels terrifyinly realistic?', '', 'I’ve been on a huge apocalyptic and post-apocalyptic movie kick lately. I love seeing how different directors portray either the actual event of the world ending or just the gritty reality of life after the collapse.

But a lot of them rely on crazy sci-fi tropes or wild zombie outbreaks. Which movies have you watched that made you sit back and think, "Yeah, if society collapsed tomorrow, this is exactly how it would go down"? I need some recommendations that will actually keep me up at night', 'ThHeisenberg', 1786279341, '/r/MoviesThatFeelLike/comments/1vjox2g/whats_an_end_of_the_world_movie_that_actually/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vjox2g/whats_an_end_of_the_world_movie_that_actually/', 'MoviesThatFeelLike', 'Gritty and brutally realistic depictions of societal collapse that evoke a lingering sense of dread.', 'skipped', 'no usable images', NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1430, '1vjpo6j', 'Can you describe the nostalgia you have for movies?', 'Can you describe the nostalgia you have for movies?', 'In my early childhood movies, the nostalgia is more for feelings I had while I was watching. Plus, there''s a specific mystique to them, because these were the first movies I ever saw.

For later childhood movies, they remind me of my life at the time, not just memories of feelings while watching them. Even certain trailers/TV spots  ("My Life (1993)" is way up there.) Also, movie titles from the early/mid 90s give me strong nostalgic feelings. and many I haven''t even seen.

Nostalgia for movies during my teenage years as well, but not as strong.

Sorry if this post is really corny.', 'Socko82', 1786281448, '/r/MoviesThatFeelLike/comments/1vjpo6j/can_you_describe_the_nostalgia_you_have_for_movies/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vjpo6j/can_you_describe_the_nostalgia_you_have_for_movies/', 'MoviesThatFeelLike', 'A wistful nostalgia for the feelings and life associations of childhood movie-watching.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1431, '1vjpqxx', 'Let''s see if someone can suggest', '', '', 'SimpleDoughnut9131', 1786281658, '/r/MoviesThatFeelLike/comments/1vjpqxx/lets_see_if_someone_can_suggest/', 'https://i.redd.it/2xauyfygocih1.jpeg', 'MoviesThatFeelLike', 'Frustrated backlash against AI-generated content', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1432, '1vjpzjf', 'The Drama, The Invite, Materialists', 'The Drama, The Invite, Materialists', 'I dont really care about plot I just love the cinematography and indie music in these specific A24 movies. Specifically the first part of the drama and shots their apartment, the music and views of the city in Materialists, and the first few minutes of The Invite with the beautiful shots of San Francisco(I was so sad when I realized the whole movie was in their apartment lol).    
OH and the credits of Spiderman BND with the clips of NYC and Steve lacy in the background that''s exactly what I''m talking about.    
I don''t know what this style is called but I need more of it!!!', 'PastLavishness4692', 1786282310, '/r/MoviesThatFeelLike/comments/1vjpzjf/the_drama_the_invite_materialists/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vjpzjf/the_drama_the_invite_materialists/', 'MoviesThatFeelLike', 'Intimate, lived-in urban moments paired with indie soundtracks.', 'skipped', 'no usable images', NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1433, '1vjqt4g', 'Movies like this?', '', '[deleted]', '[deleted]', 1786284462, '/r/MoviesThatFeelLike/comments/1vjqt4g/movies_like_this/', '', 'MoviesThatFeelLike', '', 'skipped', 'no usable images; no vibe summary', NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1434, '1vjqtpz', 'Movies that are a combination of this?', '', '', 'Junior_Insurance7773', 1786284507, '/r/MoviesThatFeelLike/comments/1vjqtpz/movies_that_are_a_combination_of_this/', 'https://www.reddit.com/gallery/1vjqtpz', 'MoviesThatFeelLike', 'Epic historical and mythological action films and series featuring legendary warriors, brutal combat, and ancient worlds.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1435, '1vjrrja', 'films that feel like this (or make YOU feel like this)', '', '', 'Intelligent_Split565', 1786286893, '/r/MoviesThatFeelLike/comments/1vjrrja/films_that_feel_like_this_or_make_you_feel_like/', 'https://www.reddit.com/gallery/1vjrrja', 'MoviesThatFeelLike', 'dreamy sun-drenched summer nostalgia', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1436, '1vjsa0o', 'movies that feel like shameless (us)?', 'movies that feel like shameless (us)?', 'anything that finds the dark humor in life along the poverty line, substance abuse, mental illness, & dysfunctional but weirdly loving/comforting family  
dynamics. ', 'ThinKaleidoscope8600', 1786288143, '/r/MoviesThatFeelLike/comments/1vjsa0o/movies_that_feel_like_shameless_us/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vjsa0o/movies_that_feel_like_shameless_us/', 'MoviesThatFeelLike', 'Darkly humorous, gritty life on the poverty line with substance abuse and mental illness, yet anchored by dysfunctional but loving family bonds.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1437, '1vjsdv6', 'This Vibe', 'This Vibe', 'Barring Ripley (1st pic) what movies or series feel like this?', 'Unusual-Arrival-3425', 1786288399, '/r/MoviesThatFeelLike/comments/1vjsdv6/this_vibe/', 'https://www.reddit.com/gallery/1vjsdv6', 'MoviesThatFeelLike', 'A shadowy, black-and-white world of noir intrigue, melancholy romance, and stylish urban decay.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1438, '1vjsk53', 'Looking for something with a really bold and colorful animation style', '', 'I really like this sort of animation style that just fully embraces the medium and doesn’t care as much about realism as just making something bombastic and visually appealing

The game Zenless zone zero pulls this off in their cutscenes super well

It won’t let me attach more videos, but puss in boots the last wish and arcane are two other examples', 'Dreadsin', 1786288805, '/r/MoviesThatFeelLike/comments/1vjsk53/looking_for_something_with_a_really_bold_and/', 'https://v.redd.it/oi2f0kbg9dih1', 'MoviesThatFeelLike', 'A vibrant, bombastic visual feast that rejects realism for pure animated spectacle.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1439, '1vjtxpj', 'Movies that feels Jazzy', 'Movies that feels Jazzy', '', 'Radiant-Boat-5149', 1786292116, '/r/MoviesThatFeelLike/comments/1vjtxpj/movies_that_feels_jazzy/', 'https://www.reddit.com/gallery/1vjtxpj', 'MoviesThatFeelLike', 'Smoky jazz clubs and swinging soundtracks', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1440, '1vjuscm', 'Movies that feel like this', '', '', 'chaiegai', 1786294145, '/r/MoviesThatFeelLike/comments/1vjuscm/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vjuscm', 'MoviesThatFeelLike', '', 'skipped', 'no vibe summary; no enriched recommendation matches', NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1441, '1vjv1m0', 'Someone pls give me a movie that will ruin me and I sit in silence after watching', 'Someone pls give me a movie that will ruin me and I sit in silence after watching', 'Any suggestions?', 'Eastern-Part-6530', 1786294760, '/r/MoviesThatFeelLike/comments/1vjv1m0/someone_pls_give_me_a_movie_that_will_ruin_me_and/', 'https://v.redd.it/x6m8xewx21ih1', 'MoviesThatFeelLike', 'A desperate search for films that deliver such profound emotional devastation that one is left in stunned silence.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1442, '1vjv6go', 'Movies that feels like this', 'Movies that feels like this', '', 'chaiegai', 1786295068, '/r/MoviesThatFeelLike/comments/1vjv6go/movies_that_feels_like_this/', 'https://www.reddit.com/gallery/1vjv6go', 'MoviesThatFeelLike', 'Eerie rural isolation and creeping psychological dread', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1443, '1vjwjxz', 'Let''s see if you can find anything that looks like this.', 'Let''s see if you can find anything that looks like this.', '', 'Ultrakirby78', 1786298319, '/r/MoviesThatFeelLike/comments/1vjwjxz/lets_see_if_you_can_find_anything_that_looks_like/', 'https://www.reddit.com/gallery/1vjwjxz', 'MoviesThatFeelLike', 'A visual quest for something resembling an unseen image.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1444, '1vjx9ht', 'Found it on Instagram.any movie like this', '', '', 'AmanYadav19', 1786299933, '/r/MoviesThatFeelLike/comments/1vjx9ht/found_it_on_instagramany_movie_like_this/', 'https://v.redd.it/u2wnq7un6eih1', 'MoviesThatFeelLike', 'Eerie, isolated suburban liminality', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1445, '1vjy3th', 'ㅤ', '', '', 'FarPapaya2675', 1786301886, '/r/MoviesThatFeelLike/comments/1vjy3th/ㅤ/', 'https://www.reddit.com/gallery/1vjy3th', 'MoviesThatFeelLike', 'Introspective and melancholic with a dark undercurrent', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1446, '1vjy9fh', 'Movies that feel like the Evermore Album By Taylor Swift', 'Movies that feel like the Evermore Album By Taylor Swift', '[removed]', 'FantasticAct7424', 1786302233, '/r/MoviesThatFeelLike/comments/1vjy9fh/movies_that_feel_like_the_evermore_album_by/', 'https://www.reddit.com/gallery/1vjy9fh', 'MoviesThatFeelLike', 'Autumnal, storytelling, cozy melancholy like the Evermore album.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1447, '1vjyyej', 'Movies that could make me feel like this', 'Movies that could make me feel like this', 'I had watched a couple movies that were so good i kinda want More 

\- in this small corner of the world

\- remember me 

\- chemical hearts

\- perks of being a wall flower ', 'ifeelsammm', 1786303876, '/r/MoviesThatFeelLike/comments/1vjyyej/movies_that_could_make_me_feel_like_this/', 'https://www.reddit.com/gallery/1vjyyej', 'MoviesThatFeelLike', 'Bittersweet coming-of-age romance dramas with deep emotional impact.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1448, '1vjzgk7', 'Thisss', 'Thisss', '[deleted]', '[deleted]', 1786305091, '/r/MoviesThatFeelLike/comments/1vjzgk7/thisss/', '', 'MoviesThatFeelLike', 'No content to determine mood', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1449, '1vjzhgf', 'Thiss', 'Thiss', '', '24GLOCKS', 1786305149, '/r/MoviesThatFeelLike/comments/1vjzhgf/thiss/', 'https://www.reddit.com/gallery/1vjzhgf', 'MoviesThatFeelLike', 'Eerie, contemplative isolation', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1450, '1vjzhq4', 'Dr. Kashish Gupta on Instagram', 'Dr. Kashish Gupta on Instagram', '', 'gupta_kashish', 1786305167, '/r/MoviesThatFeelLike/comments/1vjzhq4/dr_kashish_gupta_on_instagram/', 'https://www.instagram.com/reel/Dbz8IoqosHi/?igsh%3DNzMyczI2bmllMjA4', 'MoviesThatFeelLike', '', 'skipped', 'no usable images; no vibe summary; no enriched recommendation matches', NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1451, '1vk0i68', 'Any movies that give off this euphoric vibe?', '', 'I''m struggling the most with finding movies of this genre, and the rest of the Internet doesn''t seem to be very helpful. I enjoy watching these kind of movies but they''re so hard to find! ', 'kittydhy', 1786307592, '/r/MoviesThatFeelLike/comments/1vk0i68/any_movies_that_give_off_this_euphoric_vibe/', 'https://www.reddit.com/gallery/1vk0i68', 'MoviesThatFeelLike', 'Neon-soaked euphoria and dreamlike disorientation, from wild parties to introspective comedown.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1452, '1vk18oj', 'The Weirdness of Space can be Cute, Considerate, and Chill', 'The Weirdness of Space can be Cute, Considerate, and Chill', '', 'grimoire-5_not_6', 1786309392, '/r/MoviesThatFeelLike/comments/1vk18oj/the_weirdness_of_space_can_be_cute_considerate/', 'https://www.reddit.com/gallery/1vk18oj', 'MoviesThatFeelLike', 'A whimsical and chill vibe where space is friendly and considerate.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1453, '1vk1eyp', 'Movies with this kinda atmosphere?', 'Movies with this kinda atmosphere?', '', 'LulaPoodle1', 1786309822, '/r/MoviesThatFeelLike/comments/1vk1eyp/movies_with_this_kinda_atmosphere/', 'https://www.reddit.com/gallery/1vk1eyp', 'MoviesThatFeelLike', 'A sleazy, neon-drenched Americana with a dark, surreal undercurrent.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1454, '1vk2nu9', 'Fucked up Americana neo-noir crime thriller', 'Fucked up Americana neo-noir crime thriller', '', 'smoothpaving', 1786312959, '/r/MoviesThatFeelLike/comments/1vk2nu9/fucked_up_americana_neonoir_crime_thriller/', 'https://i.redd.it/q9bzxvhj9fih1.jpeg', 'MoviesThatFeelLike', 'Dark and gritty American neo-noir crime thrillers with a rural, intense, and atmospheric mood.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1455, '1vk3enu', 'songs or albums that feel like this??', 'songs or albums that feel like this??', '', 'siento_1227', 1786314827, '/r/MoviesThatFeelLike/comments/1vk3enu/songs_or_albums_that_feel_like_this/', 'https://www.reddit.com/gallery/1vk26tw', 'MoviesThatFeelLike', 'Unidentified aesthetic from post', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1456, '1vk3fco', 'Movies that feel like this??', 'Movies that feel like this??', 'Preferably not horror?', 'siento_1227', 1786314877, '/r/MoviesThatFeelLike/comments/1vk3fco/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vk26tw', 'MoviesThatFeelLike', 'Moody, atmospheric tales of love and loss set against sweeping natural backdrops.', 'publishable', NULL, NULL, '2026-08-10 02:34:01', '2026-08-10 02:34:01');
