-- 0096_seed_20260811T024625Z_01_posts.sql: data seed from pipeline:load run.
-- Generated:  2026-08-11T02:46:38.598258+00:00
-- Run started: 2026-08-11T02:46:25.886314+00:00
-- Source: data/working/load manifest from this run.
--
-- Idempotent: every INSERT is INSERT OR IGNORE, keyed by the
-- table's natural unique constraint.  Wrangler's migration
-- tracking normally prevents re-apply; the OR IGNORE is
-- defense in depth for partial / interrupted re-runs.
--
-- Chunk: 01_posts (1/5)
-- Tables: imported_vibe_posts.
-- Pipeline-state tables (processing_runs, pipeline_artifacts)
-- are intentionally excluded — they're per-run bookkeeping.

INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1457, '1uhzc8d', 'Movies That Feel Like This Song', 'Movies That Feel Like This Song', 'Not necessarily the lyrics of the song, just the vibes. ', 'SvtJoshua', 1782658445, '/r/MoviesThatFeelLike/comments/1uhzc8d/movies_that_feel_like_this_song/', 'https://i.redd.it/4nh5dxsse1ah1.jpeg', 'MoviesThatFeelLike', 'Nostalgic, retro atmosphere reminiscent of 1950s-60s Americana, with rock and roll vibes and a lighthearted, coming-of-age feel.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1458, '1ui1nqw', 'Ego Clashes b/w two', 'Ego Clashes Between Two', 'exploring the destructive and entertaining results of two strong-willed individuals refusing to back down. These struggles often escalate into intense games of one-upmanship, pride, and ruined relationships. ', 'Adorable-Quarter2994', 1782663992, '/r/MoviesThatFeelLike/comments/1ui1nqw/ego_clashes_bw_two/', 'https://www.reddit.com/gallery/1ui1nqw', 'MoviesThatFeelLike', 'A tense and destructive clash of egos where pride and one-upmanship ruin relationships.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1459, '1ui485h', 'This', 'This', '', 'Jellypathicdream', 1782670042, '/r/MoviesThatFeelLike/comments/1ui485h/this/', 'https://i.redd.it/9eks9h5ad2ah1.jpeg', 'MoviesThatFeelLike', 'Dark and edgy cyberpunk noir with a rebellious punk aesthetic.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1460, '1ui4j5t', 'Movies or shows with a similar vibe to the life is strange /don''t nod games', 'Movies or shows with a similar vibe to Life is Strange / Don''t Nod games', 'Title says it all, I''m hoping the gamers here can help me out. If you don''t play video games and have no idea what I''m talking about, I want something to watch with a cozy vibe, acoustic songs, small town, could be any genre. It''s much more about the aesthetic.

Something that might help you narrow it down, I want something similar to gravity falls lol

I don''t know if this is dumb but I''m stuck and need help haha I have no movie or show to compare the vibe to.

Thank youuuu', 'Sea-Slide-4197', 1782670759, '/r/MoviesThatFeelLike/comments/1ui4j5t/movies_or_shows_with_a_similar_vibe_to_the_life/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1ui4j5t/movies_or_shows_with_a_similar_vibe_to_the_life/', 'MoviesThatFeelLike', 'Cozy small-town mystery with indie acoustic soundtrack and nostalgic coming-of-age atmosphere', 'skipped', 'no usable images', NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1461, '1ui4uuw', 'movie recs that are similar to project x ?', 'movie recs that are similar to project x ?', 'ive been looking for movies that are similar to project x and cant really find any that satisfy my need for teenage party movies. 

ive watched 21 & over and the f\*\*k it list as they were the closest i could get. didnt mond the f\*\*k it list, but wasnt huge on 21 & over. 

was just wondering if anyone has any recommendations similar to project x and even the other 2 i mentioned!!', 'feathersruffed', 1782671513, '/r/MoviesThatFeelLike/comments/1ui4uuw/movie_recs_that_are_similar_to_project_x/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1ui4uuw/movie_recs_that_are_similar_to_project_x/', 'MoviesThatFeelLike', 'An energetic, out-of-control teenage party with escalating chaos.', 'skipped', 'no usable images', NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1462, '1ui5b2e', 'William Blake', 'William Blake', 'Looking for movies that feel like the works of William Blake, both his writing(if you know it) and his artwork. ', 'Lost-Software9892', 1782672556, '/r/MoviesThatFeelLike/comments/1ui5b2e/william_blake/', 'https://www.reddit.com/gallery/1ui5b2e', 'MoviesThatFeelLike', 'Mystical and apocalyptic visions, stark chiaroscuro, cosmic confrontations, and spiritual allegories.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1463, '1ui617l', 'Any Russian war films that feel like this?', 'Any Russian war films that feel like this?', '[deleted]', '[deleted]', 1782674224, '/r/MoviesThatFeelLike/comments/1ui617l/any_russian_war_films_that_feel_like_this/', '', 'MoviesThatFeelLike', '', 'skipped', 'no usable images; no vibe summary; no enriched recommendation matches', NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1464, '1ui7y5g', 'brazil, hot summer, light, young and pure love story. (I’ve already watched the city of God btw)', 'Brazil, hot summer, light, young and pure love story', '', 'Horror-Egg-4509', 1782678714, '/r/MoviesThatFeelLike/comments/1ui7y5g/brazil_hot_summer_light_young_and_pure_love_story/', 'https://www.reddit.com/gallery/1ui7y5g', 'MoviesThatFeelLike', 'A light, youthful, and innocent love story unfolding under the hot Brazilian summer sun.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1465, '1uibhdc', 'movies or tv shows with this aesthetic', '', '', 'DingoTough5900', 1782687558, '/r/MoviesThatFeelLike/comments/1uibhdc/movies_or_tv_shows_with_this_aesthetic/', 'https://www.reddit.com/gallery/1uibhdc', 'MoviesThatFeelLike', 'Charming Alpine village surrounded by lush green meadows and storybook architecture, radiating peace and nostalgia.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1466, '1uidgn9', 'Movies with these vibes', '', '', 'El_Victor_XD', 1782692905, '/r/MoviesThatFeelLike/comments/1uidgn9/movies_with_these_vibes/', 'https://www.reddit.com/gallery/1uidgn9', 'MoviesThatFeelLike', 'A gritty, high-voltage rock-and-roll atmosphere full of electric guitars, leather jackets, and rebellious stage energy.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1467, '1uidskx', 'Romance movies, BUT there is NOT a Love at first sight', '', 'The pictures included are examples of what I''m not looking for.', 'XipeTotecwithGlitter', 1782693877, '/r/MoviesThatFeelLike/comments/1uidskx/romance_movies_but_there_is_not_a_love_at_first/', 'https://www.reddit.com/gallery/1uidskx', 'MoviesThatFeelLike', 'Slow-burn romantic narratives where love develops gradually, often from initial conflict or friendship, emphasizing depth over instant attraction.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1468, '1uidyh8', 'I’m looking for a scene from a classic movie—where should I ask?', 'Looking for a scene from a classic movie', '', 'Own-Smile7328', 1782694352, '/r/MoviesThatFeelLike/comments/1uidyh8/im_looking_for_a_scene_from_a_classic_moviewhere/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uidyh8/im_looking_for_a_scene_from_a_classic_moviewhere/', 'MoviesThatFeelLike', 'Nostalgic curiosity about classic cinema.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1469, '1uinld1', 'any movies with this aesthetic?', 'any movies with this aesthetic?', '', 'NotS0Odinary', 1782725199, '/r/MoviesThatFeelLike/comments/1uinld1/any_movies_with_this_aesthetic/', 'https://www.reddit.com/gallery/1uinld1', 'MoviesThatFeelLike', 'A dark, religious horror atmosphere filled with occult rituals, crumbling churches, and oppressive dread.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1470, '1uioh64', 'Neon city', '', 'This image is from the video game Cyberpunk 2077.

I also love the Bladerunner movies and the city scenes from Star Wars. I would love to watch more movies with that aesthetic. ', 'abraxasnl', 1782728230, '/r/MoviesThatFeelLike/comments/1uioh64/neon_city/', 'https://i.redd.it/bs3fv12b67ah1.jpeg', 'MoviesThatFeelLike', 'A dark, neon-drenched cityscape with a gritty futuristic noir atmosphere.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1471, '1uitfnx', 'Movie’s and/or Series’ that look or feel like this?', '', '(Preferably not Fargo)', 'Mathias-Pathias', 1782741842, '/r/MoviesThatFeelLike/comments/1uitfnx/movies_andor_series_that_look_or_feel_like_this/', 'https://www.reddit.com/gallery/1uitfnx', 'MoviesThatFeelLike', 'A moody small-town mystery with surreal and noir undertones, blending cozy diner ambiance with unsettling Pacific Northwest gothic.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1472, '1uiuqep', 'recommend a movie that will absolutely wrecked me emotionally…and maybe physically too?', 'recommend a movie that will absolutely wreck me emotionally…and maybe physically too?', '', 'sadgurlwithwifi', 1782744824, '/r/MoviesThatFeelLike/comments/1uiuqep/recommend_a_movie_that_will_absolutely_wrecked_me/', '/r/u_sadgurlwithwifi/comments/1uiupi5/recommend_a_movie_that_will_absolutely_wrecked_me/', 'MoviesThatFeelLike', 'Seeking emotionally devastating and perhaps physically intense cinematic experiences.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1473, '1uiy1bw', 'Movies that feel like my top 4', 'Movies that feel like my top 4', 'Movies that feel like my top 4 so a love story set in space with doomed lovers and horror elements? 😂 is anyone able too help with that ', 'somesithcookies', 1782751955, '/r/MoviesThatFeelLike/comments/1uiy1bw/movies_that_feel_like_my_top_4/', 'https://i.redd.it/s0ezu2uu49ah1.jpeg', 'MoviesThatFeelLike', 'A doomed love story in space with horror elements.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1474, '1uiy6xr', 'Movies/series that feel like this?', 'Movies/series that feel like this?', 'Fantasy with dark age vibes, mysteries, a bit of spook and horror here and there.', 'Adventurous_Mood1303', 1782752294, '/r/MoviesThatFeelLike/comments/1uiy6xr/moviesseries_that_feel_like_this/', 'https://www.reddit.com/gallery/1uiy6xr', 'MoviesThatFeelLike', 'Dark age fantasy blending mystery, spookiness, and horror in a medieval setting.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1475, '1uj1pl1', 'Movies like 2001 a space oddesey, on the silver globe, stalker and Solaris?', 'Movies like 2001 a space oddesey, on the silver globe, stalker and Solaris?', 'I need some sci fi movies that really feels cosmic rather than it just is about robots or takes place in space.', 'Melkertheprogfan', 1782760008, '/r/MoviesThatFeelLike/comments/1uj1pl1/movies_like_2001_a_space_oddesey_on_the_silver/', 'https://www.reddit.com/gallery/1uj1pl1', 'MoviesThatFeelLike', 'Philosophical, cosmic sci-fi with existential and atmospheric depth.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1476, '1uj2ltf', 'Movies that feel like this?', '', '', 'FormHead6677', 1782761922, '/r/MoviesThatFeelLike/comments/1uj2ltf/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1uj2ltf', 'MoviesThatFeelLike', 'Eerie folk-horror atmosphere with desolate rural landscapes, ancient dread, and isolation.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1477, '1uj2wqr', 'Movies that are like this', 'Movies that are like this', '', 'Idek163', 1782762577, '/r/MoviesThatFeelLike/comments/1uj2wqr/movies_that_are_like_this/', 'https://i.redd.it/erleqivf0aah1.jpeg', 'MoviesThatFeelLike', 'Seductive danger and dark comedic obsession', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1478, '1uj567s', 'Movies that feel like this painting I just finished.', 'Movies that feel like this painting I just finished.', '', 'YeahWellDesigns', 1782767652, '/r/MoviesThatFeelLike/comments/1uj567s/movies_that_feel_like_this_painting_i_just/', 'https://i.redd.it/r3iont2jfaah1.jpeg', 'MoviesThatFeelLike', 'A bizarre, uncanny portrait of a man radiating an unsettling yet comedic energy, akin to cult films and offbeat character studies.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1479, '1uj5p1b', 'Like Baker Street by Undercover (originally by Gerry Rafferty)', 'Baker Street by Undercover (originally by Gerry Rafferty)', 'I absolutely love this cover song, and the music video gives me a warm sense of nostalgia and old love. ', 'Jellypathicdream', 1782768849, '/r/MoviesThatFeelLike/comments/1uj5p1b/like_baker_street_by_undercover_originally_by/', 'https://www.reddit.com/gallery/1uj5p1b', 'MoviesThatFeelLike', 'Warm nostalgia and old love.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1480, '1ujatyb', 'My brother and I built a daily movie connection game over the past few years. We''d love some feedback from movie nerds.', 'My brother and I built a daily movie connection game over the past few years. We''d love some feedback from movie nerds.', '[removed]', 'Mediocre-Moose458', 1782781675, '/r/MoviesThatFeelLike/comments/1ujatyb/my_brother_and_i_built_a_daily_movie_connection/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1ujatyb/my_brother_and_i_built_a_daily_movie_connection/', 'MoviesThatFeelLike', 'collaborative movie nerd curiosity', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1481, '1ujfr97', 'Movies that feel like', '', 'Movies that have a deeper meaning that is bittersweet sad and all around just depressing but has a happier meaning stuff like half man , Bojack ,Manchester by the sea,or beautiful boy', 'Bojak_Vita', 1782795832, '/r/MoviesThatFeelLike/comments/1ujfr97/movies_that_feel_like/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1ujfr97/movies_that_feel_like/', 'MoviesThatFeelLike', 'Bittersweet and deeply sad, yet ultimately seeking a happier meaning.', 'skipped', 'no usable images', NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1482, '1ujg6n9', 'boho, chinese takeout, girl friend group, face masks, yoga, BODY DESCRIPTION', 'boho, chinese takeout, girl friend group, face masks, yoga, BODY DESCRIPTION', '', 'dontaskmeaboutmath', 1782797175, '/r/MoviesThatFeelLike/comments/1ujg6n9/boho_chinese_takeout_girl_friend_group_face_masks/', 'https://www.reddit.com/gallery/1ujg6n9', 'MoviesThatFeelLike', 'Bohemian and cozy friend group vibes with Chinese takeout, face masks, and yoga.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1483, '1ujg764', 'boho, chinese takeout, girl friend group, face masks, yoga', '', '', 'dontaskmeaboutmath', 1782797223, '/r/MoviesThatFeelLike/comments/1ujg764/boho_chinese_takeout_girl_friend_group_face_masks/', 'https://www.reddit.com/gallery/1ujg6n9', 'MoviesThatFeelLike', 'Cozy girls'' night in with yoga and face masks, enjoying Chinese takeout in a boho atmosphere.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1484, '1ujhexw', 'Movie that feels like this', 'Movie that feels like this', '', 'premegoodeats', 1782801270, '/r/MoviesThatFeelLike/comments/1ujhexw/movie_that_feels_like_this/', 'https://i.redd.it/jwo39qoh7dah1.jpeg', 'MoviesThatFeelLike', 'A haunting, retro-futuristic underwater world filled with mystery and eerie beauty.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1485, '1ujirgi', 'Need a movie with these vibes (not twilight)', 'Need a movie with these vibes (not twilight)', '', 'Consistent-Fox3396', 1782805922, '/r/MoviesThatFeelLike/comments/1ujirgi/need_a_movie_with_these_vibes_not_twilight/', 'https://www.reddit.com/gallery/1ujirgi', 'MoviesThatFeelLike', 'Dark, atmospheric, rain-soaked mystery with a blue-tinted, moody aesthetic.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1486, '1ujjf61', 'Horror/thriller with core song', 'Horror/thriller with core song', 'Hi, all - first time posting in this sub so hope I’m doing this right.

I’m looking for horror and thriller movie recommendations that have a core song associated with them that is played throughout or at least referenced more than once.   
Something that ties the movie’s dread together.

Some examples include (but are not limited to):

 “Time” in Fallen  
“Break on Through” in Deliver Us From Evil  
“Hurdy Gurdy” in Zodiac

The creepier the song inherently is or how it is delivered in the movie the better!

Thanks in advance! ', 'Doctor_NC', 1782808257, '/r/MoviesThatFeelLike/comments/1ujjf61/horrorthriller_with_core_song/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1ujjf61/horrorthriller_with_core_song/', 'MoviesThatFeelLike', 'A dark collection of horror and thriller films where a recurring song becomes a haunting motif, deepening the sense of dread.', 'skipped', 'no usable images', NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1487, '1ujkiqm', 'Movies that feel like this?', 'Movies that feel like this?', 'Shots from the video game "Inside (2016)"', 'Current-Topic6696', 1782812247, '/r/MoviesThatFeelLike/comments/1ujkiqm/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1ujkiqm', 'MoviesThatFeelLike', 'Haunting, oppressive atmosphere with a sense of dread and mystery, blending dystopian and surreal elements.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1488, '1ujnunz', 'Any movies or series similar to Interstellar?', 'Any movies or series similar to Interstellar?', '[deleted]', '[deleted]', 1782822561, '/r/MoviesThatFeelLike/comments/1ujnunz/any_movies_or_series_similar_to_interstellar/', '', 'MoviesThatFeelLike', 'Requesting films or series with cerebral, emotional space exploration like Interstellar.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1489, '1ujodvc', 'Scary movies with this vibe', 'Scary movies with this vibe', '', 'RewardCapable', 1782823934, '/r/MoviesThatFeelLike/comments/1ujodvc/scary_movies_with_this_vibe/', 'https://www.reddit.com/gallery/1ujodvc', 'MoviesThatFeelLike', 'Eerie supernatural dread in rural East Asian settings.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1490, '1ujog9q', 'Movies with "The night we met" vibes', '', 'So as the title suggests 

I''m looking for movies with "The night we met" song vibes

The Amazing trend that''s going on Insta with aesthetic couple good scenic views makes me wanna watch movies with such vibes

Also first 5 minutes of john wick feels the same btw 

Looking forward!', 'Ractzkindness', 1782824111, '/r/MoviesThatFeelLike/comments/1ujog9q/movies_with_the_night_we_met_vibes/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1ujog9q/movies_with_the_night_we_met_vibes/', 'MoviesThatFeelLike', 'yearning romantic nostalgia with beautiful scenic views', 'skipped', 'no usable images', NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1491, '1ujotw0', 'Its a painfully hot summer day, school just ended, youre glued to ur couch with your friends, while youre making your evening plans', 'Its a painfully hot summer day, school just ended, youre glued to ur couch with your friends, while youre making your evening plans', 'Basically, something like Mid90s, but not Mid90s.', 'Traditional_Site1770', 1782825042, '/r/MoviesThatFeelLike/comments/1ujotw0/its_a_painfully_hot_summer_day_school_just_ended/', 'https://www.reddit.com/gallery/1ujotw0', 'MoviesThatFeelLike', 'A hazy, languid summer day of youthful aimlessness and anticipation as evening plans form.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1492, '1ujpxtm', 'A movie which is emotionally devastating', '', '[removed]', 'Monstrousdihk', 1782827735, '/r/MoviesThatFeelLike/comments/1ujpxtm/a_movie_which_is_emotionally_devastating/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1ujpxtm/a_movie_which_is_emotionally_devastating/', 'MoviesThatFeelLike', 'Seeking films that leave you emotionally shattered.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1493, '1ujpyq7', 'Movies feel like this', 'Movies feel like this', '', 'Aggravating_Gas_3511', 1782827797, '/r/MoviesThatFeelLike/comments/1ujpyq7/movies_feel_like_this/', 'https://i.redd.it/jhnn4j0defah1.jpeg', 'MoviesThatFeelLike', 'Sunny surf and beach vibes', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1494, '1ujpz4v', 'Movies like this feel ?suggest', 'Movies like this feel ?suggest', '', 'Aggravating_Gas_3511', 1782827825, '/r/MoviesThatFeelLike/comments/1ujpz4v/movies_like_this_feel_suggest/', 'https://i.redd.it/d3qlwi6gefah1.jpeg', 'MoviesThatFeelLike', 'A carefree, sun-soaked vibe of endless summers, ocean adventures, and youthful freedom.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1495, '1ujsoz2', 'Movies That Feel Like Hiking and Wanderlust', 'Movies That Feel Like Hiking and Wanderlust', '', 'SongsForBats', 1782834004, '/r/MoviesThatFeelLike/comments/1ujsoz2/movies_that_feel_like_hiking_and_wanderlust/', 'https://www.reddit.com/gallery/1ujsoz2', 'MoviesThatFeelLike', 'The call of the wild, with expansive landscapes and the urge to wander.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1496, '1ujsp0l', 'Movies that feel like GTA VI', '', 'Or movies that may have inspired GTA VI. Some examples off the top of my head:

\-Spring Breakers

\-The Beach Bum

\-Miami Vice

\-the Bad Boys series

\-old Spring Break episodes of Cops', 'everydaywasnovember', 1782834007, '/r/MoviesThatFeelLike/comments/1ujsp0l/movies_that_feel_like_gta_vi/', 'https://www.reddit.com/gallery/1ujsp0l', 'MoviesThatFeelLike', 'A neon-drenched, adrenaline-fueled Miami crime spree with chaotic humor and over-the-top action.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1497, '1ujuan5', 'Movie/ series that gives off the same vibe as the song About you.', 'Movie/ series that gives off the same vibe as the song About you.', '', 'Common_Sherbert132', 1782837531, '/r/MoviesThatFeelLike/comments/1ujuan5/movie_series_that_gives_off_the_same_vibe_as_the/', '/r/u_Common_Sherbert132/comments/1rlkh7p/movie_series_that_gives_off_the_same_vibe_as_the/', 'MoviesThatFeelLike', 'Dreamy, nostalgic longing with an ethereal, romantic atmosphere.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1498, '1ujva83', 'Movies that feel like the movie Possession', '', '', 'loveandcaree', 1782839688, '/r/MoviesThatFeelLike/comments/1ujva83/movies_that_feel_like_the_movie_possession/', 'https://i.redd.it/avkinsbqdgah1.jpeg', 'MoviesThatFeelLike', 'Intense, surreal psychological horror with grotesque imagery and marital discord.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1499, '1ujyk0y', 'The Max Headroom incident', 'The Max Headroom incident', '', 'Jellypathicdream', 1782846761, '/r/MoviesThatFeelLike/comments/1ujyk0y/the_max_headroom_incident/', 'https://www.reddit.com/gallery/1ujyk0y', 'MoviesThatFeelLike', 'Creepy digital disruption and hijacked broadcast signals, blending reality with distorted media.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1500, '1ukrqkn', 'Movies With places like this', '', '', 'OkCase3935', 1782925969, '/r/MoviesThatFeelLike/comments/1ukrqkn/movies_with_places_like_this/', 'https://www.reddit.com/gallery/1ukrqkn', 'MoviesThatFeelLike', 'Haunting, lush, magical, and quiet.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1501, '1ukszun', 'Movies and shows! Preferably nothing sad', 'Movies and shows! Preferably nothing sad', '', 'moon_rain06', 1782928776, '/r/MoviesThatFeelLike/comments/1ukszun/movies_and_shows_preferably_nothing_sad/', 'https://www.reddit.com/gallery/1ukszun', 'MoviesThatFeelLike', 'Fun, light-hearted teenage party and hangout movies and shows with upbeat energy and humor, avoiding heavy drama.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1502, '1ul1u3v', 'Movies that feel like Smells Like Teen Spirit music video', 'Movies that feel like Smells Like Teen Spirit music video', '', 'Ted-Bundy-666', 1782949025, '/r/MoviesThatFeelLike/comments/1ul1u3v/movies_that_feel_like_smells_like_teen_spirit/', 'https://www.reddit.com/gallery/1ul1u3v', 'MoviesThatFeelLike', 'Anarchic teenage rebellion in a haze of grunge and disillusionment.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1503, '1ul2k3h', 'A world’s facade that is starting to fall apart.', 'A world’s facade that is starting to fall apart.', '', 'MisterSorrowCraft', 1782950885, '/r/MoviesThatFeelLike/comments/1ul2k3h/a_worlds_facade_that_is_starting_to_fall_apart/', 'https://www.reddit.com/gallery/1uksy17', 'MoviesThatFeelLike', 'The unsettling realization that reality is a fragile construct hiding dark secrets.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1504, '1ulkx6p', 'Movies that feel like this', 'Movies that feel like this', 'Some moments of michael mann movies come close maybe', 'Metaexe', 1783004994, '/r/MoviesThatFeelLike/comments/1ulkx6p/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1ulkx6p', 'MoviesThatFeelLike', 'A sleek, neon-drenched urban crime atmosphere with high-stakes action and moody cityscapes.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1505, '1ullo4q', 'Mundane Slice of Life/Coming of age (please read post for details)', 'Mundane Slice of Life/Coming of age', '**Looking for Dramedies that have a focus on characters/dialogue, minimal plot and mundane vibes. Ideally based in small towns/ tight knit communities; where people are just being people and trying to navigate life.** 

**Pictures are from Diggers, Beautiful Girls and Shit House. Note: I’ve made my way through the Noah Baumback, Greta Gerwig, Paul Thomas Anderson, Cooper Raiff, Jim Jarmusch and Richard Linklater collections so, looking for something else. Please no Woody Allen suggestions. Thank you!**', 'Wendelltheshell', 1783006663, '/r/MoviesThatFeelLike/comments/1ullo4q/mundane_slice_of_lifecoming_of_age_please_read/', 'https://www.reddit.com/gallery/1ullo4q', 'MoviesThatFeelLike', 'Mundane small-town coming-of-age dramedy with focus on dialogue and character.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1506, '1ulopge', 'Movies that feel like “Euphoria”?', 'Movies that feel like Euphoria?', '', 'KzKn_2020', 1783013301, '/r/MoviesThatFeelLike/comments/1ulopge/movies_that_feel_like_euphoria/', 'https://www.reddit.com/gallery/1ulopge', 'MoviesThatFeelLike', 'Gritty, neon-drenched tales of teen hedonism, addiction, and emotional turmoil.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1507, '1ulqb13', 'Movies that feel like Takashi Murakami artwork', '', '', 'reylee05', 1783016746, '/r/MoviesThatFeelLike/comments/1ulqb13/movies_that_feel_like_takashi_murakami_artwork/', 'https://www.reddit.com/gallery/1ulqb13', 'MoviesThatFeelLike', 'Surreal, colorful, psychedelic, and playfully dark Japanese pop-art fever dream.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1508, '1ulxrim', 'Movies with small town, California desert vibes.', 'Movies with small town, California desert vibes.', 'Any movies with these vibes. California, chill, even surfer vibes but small town, not big city. ', 'Talilala', 1783034067, '/r/MoviesThatFeelLike/comments/1ulxrim/movies_with_small_town_california_desert_vibes/', 'https://www.reddit.com/gallery/1ulxrim', 'MoviesThatFeelLike', 'Sun-baked small-town California desert allure, blending laid-back surfer cool with dusty, off-kilter isolation.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1509, '1undiyy', 'Movies that Feel like these still shots... Quest Adventures, Going on a Journey, Being Chased through Markets, Caves, Jungles, Islands etc...', 'Quest Adventures, Going on a Journey, Being Chased through Markets, Caves, Jungles, Islands etc.', '', 'SeaAd5168', 1783182873, '/r/MoviesThatFeelLike/comments/1undiyy/movies_that_feel_like_these_still_shots_quest/', 'https://www.reddit.com/gallery/1undiyy', 'MoviesThatFeelLike', 'A pulse-pounding expedition through bustling markets, treacherous caves, and uncharted jungles.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1510, '1unne2r', 'I''m looking for movies feels like or rathe have a globetrotting vibe liketraveling around the world, doing business in exotic places, and seeking fortune and adventure. They don''t HAVE to be set in vastly different countries; they could just be centered around a certain region, I guess', '', '', 'Throwawayforsaftyy', 1783208465, '/r/MoviesThatFeelLike/comments/1unne2r/im_looking_for_movies_feels_like_or_rathe_have_a/', 'https://www.reddit.com/gallery/1unne2r', 'MoviesThatFeelLike', 'High-stakes fortune-seeking and business ventures unfold across exotic global backdrops.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1511, '1usmsyt', 'folk horror/southern gothic/isolation in the woods', 'folk horror/southern gothic/isolation in the woods', '', 'sabrina_chanelx', 1783687887, '/r/MoviesThatFeelLike/comments/1usmsyt/folk_horrorsouthern_gothicisolation_in_the_woods/', 'https://www.reddit.com/gallery/1usmsyt', 'MoviesThatFeelLike', 'A chilling, atmospheric blend of folk horror and southern gothic set in isolated woodlands.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1512, '1vk5drv', 'Movies that feel like', 'Movies that feel like', '', 'One_Truck1871', 1786320130, '/r/MoviesThatFeelLike/comments/1vk5drv/movies_that_feel_like/', 'https://www.reddit.com/gallery/1vk5drv', 'MoviesThatFeelLike', 'Creepy, unsettling atmosphere with grinning figures', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1513, '1vk5hhs', 'Looking for genuinely disturbing psychological horror movies', 'Looking for genuinely disturbing psychological horror movies', '', 'Justin_420_', 1786320404, '/r/MoviesThatFeelLike/comments/1vk5hhs/looking_for_genuinely_disturbing_psychological/', '/r/MovieSuggestions/comments/1vjoy4o/looking_for_genuinely_disturbing_psychological/', 'MoviesThatFeelLike', 'A quest for deeply unsettling psychological horror films.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1514, '1vk5vdn', 'looking for a movie to heal after a breakup', 'looking for a movie to heal after a breakup', 'after a 2 year long rs i find my self lost after my partner broke up while we were in love. im going theough the toughest time and i just want something to help me and give me hope that i can find someone better', 'ForeignPoetry1083', 1786321446, '/r/MoviesThatFeelLike/comments/1vk5vdn/looking_for_a_movie_to_heal_after_a_breakup/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vk5vdn/looking_for_a_movie_to_heal_after_a_breakup/', 'MoviesThatFeelLike', 'A comforting cinematic embrace for broken hearts seeking hope and renewal.', 'skipped', 'no usable images', NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1515, '1vk8zr8', 'Movies that feel like: autumnal, emotional, can be a comedy or drama, maybe romance, that feels like this:', 'Movies that feel like: autumnal, emotional, can be a comedy or drama, maybe romance, that feels like this:', '', 'FantasticAct7424', 1786330377, '/r/MoviesThatFeelLike/comments/1vk8zr8/movies_that_feel_like_autumnal_emotional_can_be_a/', 'https://www.reddit.com/gallery/1vk8zr8', 'MoviesThatFeelLike', 'Warm, emotional, and autumnal atmosphere with romantic and humorous undertones.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1516, '1vkalkg', 'Free Google Drive link to watch any movie or show that you want please request if we don’t have it', 'Free Google Drive link to watch any movie or show that you want please request if we don’t have it', 'https://docs.google.com/presentation/d/1hsbu1uUSLTupiiKGwp7Jc4Ne\_C5gXIUqlMXM9pvZNc0/edit?usp=drivesdk', 'Upbeat-Bee9268', 1786335190, '/r/MoviesThatFeelLike/comments/1vkalkg/free_google_drive_link_to_watch_any_movie_or_show/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vkalkg/free_google_drive_link_to_watch_any_movie_or_show/', 'MoviesThatFeelLike', 'A communal, open-access media exchange.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1517, '1vkenu2', 'Movies that feel like the song "August" by Tailor Swift', 'Movies that feel like the song August by Taylor Swift', '', 'AdAdventurous2131', 1786349143, '/r/MoviesThatFeelLike/comments/1vkenu2/movies_that_feel_like_the_song_august_by_tailor/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vkenu2/movies_that_feel_like_the_song_august_by_tailor/', 'MoviesThatFeelLike', 'Wistful summer romance with bittersweet nostalgia', 'skipped', 'no usable images', NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1518, '1vkfxk1', 'Strong Irish landscapes and heritage', 'Strong Irish landscapes and heritage', '', 'Delicious_Domino', 1786353819, '/r/MoviesThatFeelLike/comments/1vkfxk1/strong_irish_landscapes_and_heritage/', 'https://www.reddit.com/gallery/1vkfxk1', 'MoviesThatFeelLike', 'Rugged Irish landscapes and rich heritage blending dark humor, folk horror, and historical drama.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1519, '1vkh5dy', 'Rejected from a job that i thought would be ticket away from misery. something with hope', 'Rejected from a job that I thought would be ticket away from misery. Something with hope', 'hi, i have been trying to get a job for past 4 months and i am at my limit. got a rejection after the last round and pinned all my hope to it. something comforting and that fills me up with hope', 'usuratonnkachii', 1786358000, '/r/MoviesThatFeelLike/comments/1vkh5dy/rejected_from_a_job_that_i_thought_would_be/', 'https://www.reddit.com/gallery/1vkh5dy', 'MoviesThatFeelLike', 'A gentle, hope-filled atmosphere of resilience and new beginnings after disappointment.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1520, '1vkj61n', 'Nature reclaiming the world', 'Nature reclaiming the world', '', 'uumamiii', 1786364134, '/r/MoviesThatFeelLike/comments/1vkj61n/nature_reclaiming_the_world/', 'https://www.reddit.com/gallery/1vkj61n', 'MoviesThatFeelLike', 'An eerie, overgrown world where nature reclaims civilization.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1521, '1vkk2gp', 'movies that feels like this?', 'movies that feels like this', 'except moonlight, already watched it multiple times (2nd fav movie)', 'Living_Advantage_803', 1786366528, '/r/MoviesThatFeelLike/comments/1vkk2gp/movies_that_feels_like_this/', 'https://i.redd.it/kwqmn70uojih1.jpeg', 'MoviesThatFeelLike', 'Melancholic and introspective atmosphere of memory and longing, often by the sea.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1522, '1vkldho', '...earning MONEY legally in casual different ways 💸', 'earning MONEY legally in casual different ways', 'for example: like grp of broke friends set out to explore (their talents) and earn real deal

cash cash cash

0 to millionaire kinda stuff

..that i cud learn frm and make notes uk 📝', 'arpitsrivstva', 1786369681, '/r/MoviesThatFeelLike/comments/1vkldho/earning_money_legally_in_casual_different_ways/', 'https://www.reddit.com/gallery/1vkldho', 'MoviesThatFeelLike', 'A lighthearted, aspirational fantasy of broke friends turning their talents into legal, casual cash and becoming millionaires.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1523, '1vkma9k', 'Like these some countryside', 'Like these some countryside', '', 'soyeahh_imthegawwd', 1786371791, '/r/MoviesThatFeelLike/comments/1vkma9k/like_these_some_countryside/', 'https://www.reddit.com/gallery/1vkma9k', 'MoviesThatFeelLike', 'Rural countryside charm and open landscapes.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1524, '1vkpg9g', 'Favorite movie with a sprawling, drive scene with dark cello type instrumentals bonus points for an ominous undertone…', 'Favorite movie with a sprawling, drive scene with dark cello type instrumentals bonus points for an ominous undertone…', '', 'Opposite-Squash-1055', 1786378777, '/r/MoviesThatFeelLike/comments/1vkpg9g/favorite_movie_with_a_sprawling_drive_scene_with/', 'https://i.redd.it/i6nwisnzr2gh1.jpeg', 'MoviesThatFeelLike', 'Ominous, dark atmospheric drivescapes with haunting cello undertones.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1525, '1vkrya0', 'What''s a movie simaler to Brave, that includes the keltic maybe supernatural, and woodsy elements?', '', '', 'paypallmehimbos', 1786384098, '/r/MoviesThatFeelLike/comments/1vkrya0/whats_a_movie_simaler_to_brave_that_includes_the/', '/r/askteddit/comments/1vkru5h/whats_a_movie_simaler_to_brave_that_includes_the/', 'MoviesThatFeelLike', 'Mythic Celtic woodland and folklore in stunning animated beauty.', 'skipped', 'no usable images', NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1526, '1vkv50s', 'Movies that feel like this? [OC]', 'Movies that feel like this? [OC]', 'I manually composited and edited this shot on my old PC. I''ve only been experimenting with digital art for a month now, and my background in ballet heavily influences the posing. I''m really looking for movies that match this exact mood. Feedback is always welcome! \[OC\]"', 'Tough-Skill4060', 1786391042, '/r/MoviesThatFeelLike/comments/1vkv50s/movies_that_feel_like_this_oc/', 'https://www.reddit.com/gallery/1vkv50s', 'MoviesThatFeelLike', 'A hauntingly surreal and gritty atmosphere blending avant-garde horror, ritualistic tension, and balletic grace.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1527, '1vkvuhk', 'movies that feel like this?', '', '', 'brenna_is_so_sad', 1786392569, '/r/MoviesThatFeelLike/comments/1vkvuhk/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vkvuhk', 'MoviesThatFeelLike', 'A nostalgic autumnal suburbia tinged with an eerie, underlying dread.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1528, '1vkzvh8', 'Movies that feel like this.', 'Movies that feel like this.', 'I want something that feels like your being watched, no privacy, a bit hypnotic and you feel like your losing your mind.', 'Evening-Crew2114', 1786401923, '/r/MoviesThatFeelLike/comments/1vkzvh8/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vkzvh8', 'MoviesThatFeelLike', 'Voyeuristic dread and psychological disintegration.', 'publishable', NULL, NULL, '2026-08-11 02:46:38', '2026-08-11 02:46:38');
