-- 0101_seed_20260811T220920Z_01_posts.sql: data seed from pipeline:load run.
-- Generated:  2026-08-11T22:09:33.771416+00:00
-- Run started: 2026-08-11T22:09:20.758968+00:00
-- Source: data/working/load manifest from this run.
--
-- Idempotent: every INSERT is INSERT OR IGNORE, keyed by the
-- table's natural unique constraint.  Wrangler's migration
-- tracking normally prevents re-apply; the OR IGNORE is
-- defense in depth for partial / interrupted re-runs.
--
-- Chunk: 01_posts (1/5)
-- Tables: imported_vibe_posts.
-- Pipeline-state tables (processing_runs, pipeline_artifacts)
-- are intentionally excluded — they're per-run bookkeeping.

INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1529, '1uf6tq3', 'Best Movie Suggestions', 'Best Movie Suggestions', 'I''m a movie lover. I watch movies a lot... 

I cannot find a good one 

Can you guys suggest me one?', 'Unusual-Squash129', 1782385252, '/r/MoviesThatFeelLike/comments/1uf6tq3/best_movie_suggestions/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uf6tq3/best_movie_suggestions/', 'MoviesThatFeelLike', 'A desperate cinephile seeking hidden gems across all genres, from uplifting dramas to surreal mind-benders.', 'skipped', 'no usable images', NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1530, '1uf73p7', 'Madonna''s latest shoot for Interview Magazine!', 'Madonna''s latest shoot for Interview Magazine!', '', 'lollirot69', 1782386117, '/r/MoviesThatFeelLike/comments/1uf73p7/madonnas_latest_shoot_for_interview_magazine/', 'https://www.reddit.com/gallery/1uf73p7', 'MoviesThatFeelLike', 'Deconstructed Americana with a surreal Lynchian edge and gritty crime ambiance.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1531, '1uf78mu', 'Searching for crime/investigative/psychological thrillers that feel like the given pics. Recommend the ones that you genuinely loved & enjoyed.', 'Searching for crime/investigative/psychological thrillers that feel like the given pics. Recommend the ones that you genuinely loved & enjoyed.', '', 'Wasique111', 1782386542, '/r/MoviesThatFeelLike/comments/1uf78mu/searching_for_crimeinvestigativepsychological/', 'https://www.reddit.com/gallery/1uf78mu', 'MoviesThatFeelLike', 'Moody, rain-soaked small-town mysteries and slow-burn thrillers set in foggy forests and damp, atmospheric landscapes.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1532, '1uf7how', 'What should I watch after the Dark?', 'What should I watch after the Dark?', '[removed]', 'mithie_daphne', 1782387322, '/r/MoviesThatFeelLike/comments/1uf7how/what_should_i_watch_after_the_dark/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uf7how/what_should_i_watch_after_the_dark/', 'MoviesThatFeelLike', 'Mind-bending, atmospheric sci‑fi mystery seeking a successor to Dark’s intricate time‑travel narrative.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1533, '1uf7ndl', 'Underrated High-stakes espionage, globe-trotting missions, and Set pieces!!', 'Underrated High-stakes espionage, globe-trotting missions, and Set pieces!!', 'check references. TIA❤️!', 'Adorable-Quarter2994', 1782387806, '/r/MoviesThatFeelLike/comments/1uf7ndl/underrated_highstakes_espionage_globetrotting/', 'https://www.reddit.com/gallery/1uf7ndl', 'MoviesThatFeelLike', 'High-stakes espionage with globe-trotting missions and thrilling set pieces.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1534, '1ufa7y6', 'Any movies that feel like this images?', 'Any movies that feel like this images?', '', 'koyunsuyubardaga', 1782394511, '/r/MoviesThatFeelLike/comments/1ufa7y6/any_movies_that_feel_like_this_images/', 'https://www.reddit.com/gallery/1ufa7y6', 'MoviesThatFeelLike', 'A wistful, golden-hour pastoral atmosphere with fields of wheat, warm sunsets, and quiet rural life.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1535, '1ufbizw', 'Great movie combo', 'Great movie combo', '', 'No_Ear_721', 1782397474, '/r/MoviesThatFeelLike/comments/1ufbizw/great_movie_combo/', 'https://i.redd.it/mziug00fuf9h1.jpeg', 'MoviesThatFeelLike', 'Epic historical drama double feature', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1536, '1ufd5am', 'Movies that feel like an Alaskan winter', 'Movies that feel like an Alaskan winter', 'Basically I just got back from an Alaska trip and I loved it. Looking for movies that take place in Alaska/have arctic vibes. Any genre is fine 👍', 'Successful_Cap150', 1782401026, '/r/MoviesThatFeelLike/comments/1ufd5am/movies_that_feel_like_an_alaskan_winter/', 'https://i.redd.it/vlzpx32d5g9h1.jpeg', 'MoviesThatFeelLike', 'Bleak snowy isolation and harsh Arctic wilderness.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1537, '1ufdgyd', 'Movies that feel like this painting I did', '', '', 'YeahWellDesigns', 1782401738, '/r/MoviesThatFeelLike/comments/1ufdgyd/movies_that_feel_like_this_painting_i_did/', 'https://i.redd.it/m4qpeq5h7g9h1.jpeg', 'MoviesThatFeelLike', 'A surreal, unsettling dreamscape with vibrant colors and distorted faces, evoking a sense of uncanny unease and hallucinatory panic.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1538, '1uffnf9', 'Your rainy day movies', 'Your rainy day movies', '', 'Eastern_Bad_922', 1782406458, '/r/MoviesThatFeelLike/comments/1uffnf9/your_rainy_day_movies/', 'https://i.redd.it/sihtwhi7bg9h1.jpeg', 'MoviesThatFeelLike', 'Cozy, rainy day aesthetic with comforting and nostalgic atmospheres.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1539, '1uflink', 'First movie that comes to mind when you see this image', 'First movie that comes to mind when you see this image', '', 'SpaceTranquil', 1782419187, '/r/MoviesThatFeelLike/comments/1uflink/first_movie_that_comes_to_mind_when_you_see_this/', 'https://i.redd.it/yyicurdanh9h1.jpeg', 'MoviesThatFeelLike', 'A sun-scorched, retro-fabulous crime thriller vibe drenched in 80s neon and palm tree shadows.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1540, '1ufm1e3', 'Crime/Miami', '', '', 'TheLetterBoxder', 1782420376, '/r/MoviesThatFeelLike/comments/1ufm1e3/crimemiami/', 'https://www.reddit.com/gallery/1ufm1e3', 'MoviesThatFeelLike', 'Stylish, neon-soaked Miami crime underworld.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1541, '1ufp6c5', 'Movies, Shows, or Games that feel like this:', 'Movies, Shows, or Games that feel like this:', '[removed]', 'ArBuck-ee', 1782427779, '/r/MoviesThatFeelLike/comments/1ufp6c5/movies_shows_or_games_that_feel_like_this/', 'https://www.reddit.com/gallery/1ufp6c5', 'MoviesThatFeelLike', 'No atmosphere described (post content removed).', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1542, '1ufqvme', 'Movies, Shows, or Games with this feel:', '', '[removed]', 'ArBuck-ee', 1782432194, '/r/MoviesThatFeelLike/comments/1ufqvme/movies_shows_or_games_with_this_feel/', 'https://www.reddit.com/gallery/1ufqvme', 'MoviesThatFeelLike', 'undefined vibe', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1543, '1ufqvwr', 'summer solitude', 'summer solitude', 'themes of seasonal depression, loneliness followed by solitude,  pushing through', 'wooabi', 1782432212, '/r/MoviesThatFeelLike/comments/1ufqvwr/summer_solitude/', 'https://www.reddit.com/gallery/1ufqvwr', 'MoviesThatFeelLike', 'Melancholic summer solitude and the slow journey from loneliness to peaceful introspection.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1544, '1ufrq5h', 'Movies that feel like agricultural Americana that isn''t The Straight Story or Jeff Nichols'' filmography', '', 'I want movies that feel like these pictures I took. ', 'stakes-lines-grades', 1782434463, '/r/MoviesThatFeelLike/comments/1ufrq5h/movies_that_feel_like_agricultural_americana_that/', 'https://www.reddit.com/gallery/1ufrq5h', 'MoviesThatFeelLike', 'Dreamy rural landscapes with golden fields, barns, and endless skies.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1545, '1ufum9a', 'Movies that feel like this', 'Movies that feel like this', '', 'Green_Speech_5796', 1782442511, '/r/MoviesThatFeelLike/comments/1ufum9a/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1ufum9a', 'MoviesThatFeelLike', 'A lush, eerie world where nature has reclaimed civilization under a haunting, quiet atmosphere.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1546, '1ufvf5t', 'what’s your favourite sci-fi movie’s', 'what’s your favourite sci-fi movies', '', 'izixhx', 1782444814, '/r/MoviesThatFeelLike/comments/1ufvf5t/whats_your_favourite_scifi_movies/', 'https://i.redd.it/a0nn39zbrj9h1.jpeg', 'MoviesThatFeelLike', 'Redditors share their all-time favorite sci-fi movies, ranging from psychological thrillers and dystopian futures to classic action and space operas.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1547, '1ufvfjb', 'what’s your favourite sci-fi movie’s', 'what’s your favourite sci-fi movie’s', '', 'izixhx', 1782444845, '/r/MoviesThatFeelLike/comments/1ufvfjb/whats_your_favourite_scifi_movies/', 'https://i.redd.it/a0nn39zbrj9h1.jpeg', 'MoviesThatFeelLike', 'Seeking sci-fi favorites', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1548, '1ufvnol', 'The mental block of movie recommendations', '', '', 'Lost_Masterpiece_577', 1782445513, '/r/MoviesThatFeelLike/comments/1ufvnol/the_mental_block_of_movie_recommendations/', '/r/movies/comments/1ufvmyj/the_mental_block_of_movie_recommendations/', 'MoviesThatFeelLike', 'A frustrating mental block when trying to choose what to watch.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1549, '1ufwktf', 'Like Gattaca and Dead Ringers', 'Gattaca and Dead Ringers', '', '42observer', 1782448204, '/r/MoviesThatFeelLike/comments/1ufwktf/like_gattaca_and_dead_ringers/', 'https://www.reddit.com/gallery/1ufwktf', 'MoviesThatFeelLike', 'Cold, clinical, and psychologically intense with a sterile aesthetic.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1550, '1ufzrx0', '80''s sexual crime drama?', '80s sexual crime drama', 'Recently watched the original American Gigelo and loved the plot and feel of the movie which was different than the dominating cartoonish action-comedy flicks of the 80''s.', 'velvet_champagneX', 1782458555, '/r/MoviesThatFeelLike/comments/1ufzrx0/80s_sexual_crime_drama/', 'https://i.redd.it/uz5j3q8fwk9h1.jpeg', 'MoviesThatFeelLike', 'Stylized 80s erotic crime noir', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1551, '1ufzvjh', 'Films that feel like "Christina''s World" by Andrew Wyeth', '', '*Christina''s World* is one of my favorite paintings. It evokes a profound sense of melancholy, nostalgia, longing, and existentialism in me. A few films that give me the same vibes as the painting include: 

*Days of Heaven* (1978)

*The Reflecting Skin* (1990)

*The Texas Chainsaw Massacre* (1974)

I''m open to any genre, but I''ve seen over 3,000 films, so there''s a good chance I''ve seen it if it''s well-known. Thanks in advance!

', 'savvylee17', 1782458893, '/r/MoviesThatFeelLike/comments/1ufzvjh/films_that_feel_like_christinas_world_by_andrew/', 'https://i.redd.it/yf00m9fywk9h1.jpeg', 'MoviesThatFeelLike', 'Melancholic, nostalgic rural liminality with existential longing.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1552, '1ufzztj', 'Modern Fantasy/Adventure Films (With Magic)', 'Modern Fantasy/Adventure Films (With Magic)', '[deleted]', '[deleted]', 1782459293, '/r/MoviesThatFeelLike/comments/1ufzztj/modern_fantasyadventure_films_with_magic/', '', 'MoviesThatFeelLike', 'Seeking modern fantasy and adventure films that incorporate magic.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1553, '1ug2ecq', 'Movies that feels like this song and clip (Benson Boone - The Time of my Life)', 'Movies that feels like this song and clip (Benson Boone - The Time of my Life)', '[https://youtu.be/ptlsli-QXXc?si=PrCHjVN2mDPFmrZ6](https://youtu.be/ptlsli-QXXc?si=PrCHjVN2mDPFmrZ6)', 'Special-Bad2404', 1782467748, '/r/MoviesThatFeelLike/comments/1ug2ecq/movies_that_feels_like_this_song_and_clip_benson/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1ug2ecq/movies_that_feels_like_this_song_and_clip_benson/', 'MoviesThatFeelLike', 'Euphoric, nostalgic coming-of-age energy', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1554, '1ug2end', 'Shows/movies that feel like this', 'Shows/movies that feel like this', 'Looking for a good coming of age romance/friend group movie', 'Zealousideal_Let_213', 1782467778, '/r/MoviesThatFeelLike/comments/1ug2end/showsmovies_that_feel_like_this/', 'https://www.reddit.com/gallery/1ug2end', 'MoviesThatFeelLike', 'Nostalgic, sun-soaked coming-of-age tales of friendship, romance, and restless summer days.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1555, '1ug2mu6', 'Movies that feels like the latest clip of Benson Boone', 'A doomed love story across centuries', 'A doomed love story across centuries

  
[https://www.youtube.com/watch?v=ptlsli-QXXc](https://www.youtube.com/watch?v=ptlsli-QXXc)', 'Special-Bad2404', 1782468516, '/r/MoviesThatFeelLike/comments/1ug2mu6/movies_that_feels_like_the_latest_clip_of_benson/', 'https://www.reddit.com/gallery/1ug2mu6', 'MoviesThatFeelLike', 'Doomed romance echoing across time', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1556, '1ug40gp', 'Lonley people in neon cities', 'Lonley people in neon cities', '', 'Lost-Purple-883', 1782472842, '/r/MoviesThatFeelLike/comments/1ug40gp/lonley_people_in_neon_cities/', 'https://www.reddit.com/gallery/1ug40gp', 'MoviesThatFeelLike', 'Lonely individuals wandering through glowing neon-drenched city streets at night.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1557, '1ug5fx2', 'About me I want opinions', 'About me I want opinions', '', 'Voltri_1305', 1782476895, '/r/MoviesThatFeelLike/comments/1ug5fx2/about_me_i_want_opinions/', 'https://www.reddit.com/gallery/1ug538r', 'MoviesThatFeelLike', 'The user''s list is perceived as standard and basic, aligning with popular Letterboxd trends.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1558, '1ug6w2i', 'Blood. Brotherhood. Betrayal', '', 'Cool or serious,(Underrated) atmospheric movies about / with mafia, organized crime, gangster,  rich family or crime family, betrayal and mob boss themes

Love (leave)  the Obvious Godfather, Goodfellas  Peaky Blinders, Sopranos etc. 

Go for other routes  like The Casino ', 'Adorable-Quarter2994', 1782480532, '/r/MoviesThatFeelLike/comments/1ug6w2i/blood_brotherhood_betrayal/', 'https://www.reddit.com/gallery/1ug6w2i', 'MoviesThatFeelLike', 'Brooding, atmospheric crime sagas of blood ties and stylish betrayal.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1559, '1ug766k', 'Fun Movies about shooting a movie with/about gangster', 'Fun Movies about shooting a movie with/about gangster', 'Yup. Such a weird meta sub-genre. But trust me, it is as fun as the last slide.

There are lot many examples in world cinema it seems. 

So fellow redditors, Enlighten us. TIA☺️', 'Adorable-Quarter2994', 1782481204, '/r/MoviesThatFeelLike/comments/1ug766k/fun_movies_about_shooting_a_movie_withabout/', 'https://www.reddit.com/gallery/1ug766k', 'MoviesThatFeelLike', 'A playful and meta dive into the chaotic world of gangster filmmaking, where criminals and cameras collide with darkly comedic results.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1560, '1uga3pr', 'This', 'The legend of the stardust brothers', 'The legend of the stardust brothers', 'Jellypathicdream', 1782487911, '/r/MoviesThatFeelLike/comments/1uga3pr/this/', 'https://i.redd.it/pnxwnuspbn9h1.jpeg', 'MoviesThatFeelLike', 'A surreal, bizarre collage of cult Japanese sci-fi and horror oddities.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1561, '1ugb5f7', 'Movies that looks like', 'Sleek, rainy, high-rise urban night aesthetic', '', 'Tricky_cielito00', 1782490239, '/r/MoviesThatFeelLike/comments/1ugb5f7/movies_that_looks_like/', 'https://www.reddit.com/gallery/1ugb5f7', 'MoviesThatFeelLike', 'Sleek, rainy, neon-lit high-rise urban atmosphere at night with an undercurrent of corporate luxury and isolation.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1562, '1ugclxc', 'Movies that give - father daughter bond', 'Movies that give - father daughter bond', 'Hello,

Please spare my heart, and warn me if there''s a sad ending. I have seen >!Aftersun!< already.

Single dad trope works, I loved  ''Hi Nanna'', comedy like ''Father of the Bride'', ''Hindi Medium'' works.. even drama like ''The Whale'' works. 

Any language works - All Indian, all International language works. 

I just want to watch good Films. 

Thanks', 'HeatedRivalryPaglu', 1782493412, '/r/MoviesThatFeelLike/comments/1ugclxc/movies_that_give_father_daughter_bond/', 'https://www.reddit.com/gallery/1ugclxc', 'MoviesThatFeelLike', 'Heartwarming and emotional stories of father-daughter bonding.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1563, '1ugcvjc', 'I got tired of wasting hours trying to figure out what movie to watch... so I built a free tool to match your exact vibe. Meet FlixPic.', '', '[removed]', 'FlixPic', 1782494008, '/r/MoviesThatFeelLike/comments/1ugcvjc/i_got_tired_of_wasting_hours_trying_to_figure_out/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1ugcvjc/i_got_tired_of_wasting_hours_trying_to_figure_out/', 'MoviesThatFeelLike', 'Effortless mood-based movie discovery', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1564, '1ugd026', 'Suggest me a movie like dear zindagi that''d change my perspective about life, about myself, about beauty.', '', '', 'lammbb', 1782494297, '/r/MoviesThatFeelLike/comments/1ugd026/suggest_me_a_movie_like_dear_zindagi_thatd_change/', '/r/Advice/comments/1ugczee/suggest_me_a_movie_like_dear_zindagi_thatd_change/', 'MoviesThatFeelLike', 'Introspective and philosophical exploration of life and self.', 'skipped', 'no usable images', NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1565, '1ugd4i0', 'Shows/Movies with romance that feel like this?', '', '', 'Zealousideal_Let_213', 1782494563, '/r/MoviesThatFeelLike/comments/1ugd4i0/showsmovies_with_romance_that_feel_like_this/', 'https://www.reddit.com/gallery/1ugd4i0', 'MoviesThatFeelLike', 'A vibrant, nostalgia-tinged coastal escape bathed in neon sunsets, capturing youthful romance and carefree summer nights.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1566, '1ugd5ds', 'Documentaries that feel the documentary was in the right place at the right time to capture gold', 'Documentaries that feel the documentary was in the right place at the right time to capture gold', '', 'Shivathewriter', 1782494620, '/r/MoviesThatFeelLike/comments/1ugd5ds/documentaries_that_feel_the_documentary_was_in/', 'https://www.reddit.com/gallery/1ugd5ds', 'MoviesThatFeelLike', 'Documentaries that serendipitously captured unexpected, dramatic, and often shocking real-life moments.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1567, '1ugea29', 'My watchlist is officially empty.', '', 'Recommend me a movie that’ll make me forget reality for the next 2-3 hours.', 'Maximum-Bit-3848', 1782497141, '/r/MoviesThatFeelLike/comments/1ugea29/my_watchlist_is_officially_empty/', 'https://i.redd.it/4stj7yo53o9h1.jpeg', 'MoviesThatFeelLike', 'An escapist yearning for films that entirely consume your attention and detach you from the everyday.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1568, '1ugeken', 'My country just experienced the hottest day in history, what are some sweaty summer films?', '', '', 'AssociationCorrect14', 1782497783, '/r/MoviesThatFeelLike/comments/1ugeken/my_country_just_experienced_the_hottest_day_in/', 'https://www.reddit.com/gallery/1ugeken', 'MoviesThatFeelLike', 'A scorching blend of heat-soaked tension, dripping sweat, and summertime unease.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1569, '1ugjrdm', 'suggest a movie about someone who''s sooo obsessed with his friendand he sees him as his best friend ever but on the other hand the other friend sees him as a regular friend similar to The Cable Guy(1996) and Single White Female(1992) &Thanks a lot.', '', '', 'Yu733', 1782509621, '/r/MoviesThatFeelLike/comments/1ugjrdm/suggest_a_movie_about_someone_whos_sooo_obsessed/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1ugjrdm/suggest_a_movie_about_someone_whos_sooo_obsessed/', 'MoviesThatFeelLike', 'An unsettling exploration of obsessive, one-sided friendships.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1570, '1ugjrwv', 'suggest a movie about someone who''s sooo obsessed with his friend and he sees him as his best friend ever but on the other hand the other friend sees him as a regular friend similar to The Cable Guy(1996) and Single White Female(1992) &Thanks a lot.', 'Suggest a movie about someone who is so obsessed with his friend and sees him as his best friend, but the other friend sees him as a regular friend, similar to The Cable Guy (1996) and Single White Female (1992).', '', 'Yu733', 1782509657, '/r/MoviesThatFeelLike/comments/1ugjrwv/suggest_a_movie_about_someone_whos_sooo_obsessed/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1ugjrwv/suggest_a_movie_about_someone_whos_sooo_obsessed/', 'MoviesThatFeelLike', 'Clingy, unbalanced friendships veer into psychological obsession and menace.', 'skipped', 'no usable images', NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1571, '1ugkoc7', 'movies that feel like this?', 'movies that feel like this?', 'these are all from charli xcx’s new mv btw', 'missIdior', 1782511795, '/r/MoviesThatFeelLike/comments/1ugkoc7/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1ugkoc7', 'MoviesThatFeelLike', 'A raw, sun-drenched Americana aesthetic with a rebellious, chaotic, and intensely romantic energy.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1572, '1ugllzc', 'If you ever feel like watching the obscure movie or jamming to cool music....', 'If you ever feel like watching the obscure movie or jamming to cool music....', '', 'Cav_01', 1782514108, '/r/MoviesThatFeelLike/comments/1ugllzc/if_you_ever_feel_like_watching_the_obscure_movie/', '/r/ArtHouse/comments/1uglctj/if_you_ever_feel_like_watching_the_obscure_movie/', 'MoviesThatFeelLike', 'Obscure movie watching and cool music vibes.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1573, '1ugmhzl', 'Movies that fit this vibe?', 'Movies that fit this vibe?', 'I''m thinking of ninth gate with Johnny Depp. Hereditary etc. What else you guys got? Oh I guess there''s Rosemary''s baby. Lol why even post? Gimme what you got?', 'comelyfrost', 1782516339, '/r/MoviesThatFeelLike/comments/1ugmhzl/movies_that_fit_this_vibe/', 'https://www.reddit.com/gallery/1uejuyv', 'MoviesThatFeelLike', 'Occult dread and psychedelic ritual horror.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1574, '1ugqtpk', 'Weird, soft, creepy, and cute', 'Weird, soft, creepy, and cute', '', 'BillythenotaKid', 1782528311, '/r/MoviesThatFeelLike/comments/1ugqtpk/weird_soft_creepy_and_cute/', 'https://www.reddit.com/gallery/1ugqtpk', 'MoviesThatFeelLike', 'A soft, eerie dreamscape blending the macabre with an almost childlike cuteness.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1575, '1ugqx5n', 'exploring a small town or the woods at night kinda horror, maybe found footage and following a group of teenage friends', 'exploring a small town or the woods at night kinda horror, maybe found footage and following a group of teenage friends', '', 'banana-127', 1782528595, '/r/MoviesThatFeelLike/comments/1ugqx5n/exploring_a_small_town_or_the_woods_at_night/', 'https://www.reddit.com/gallery/1ugqx5n', 'MoviesThatFeelLike', 'Eerie nighttime exploration of small towns and dark woods, often through found-footage and teenage perspectives.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1576, '1ugrt1y', 'Movies that feel like', 'Movies that feel like', '', 'santacondenada', 1782531198, '/r/MoviesThatFeelLike/comments/1ugrt1y/movies_that_feel_like/', 'https://www.reddit.com/gallery/1ugrt1y', 'MoviesThatFeelLike', 'A cold, concrete decay filled with gray skies and urban desolation.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1577, '1ugsf74', 'Movies that feel like this:', 'Movies that feel like this', 'British accents ….', 'HeavyAcademic', 1782533063, '/r/MoviesThatFeelLike/comments/1ugsf74/movies_that_feel_like_this/', 'https://i.redd.it/fo3exz5z1r9h1.jpeg', 'MoviesThatFeelLike', 'Lush British period drama with a gothic romantic mood.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1578, '1ugshec', 'Comedy actors or typecast actors in a really good horror or thriller movie', 'Comedy actors or typecast actors in a really good horror or thriller movie', 'Robin Williams in one hour photo

Jim Carrey in the number 23', 'DaintyCatBug', 1782533247, '/r/MoviesThatFeelLike/comments/1ugshec/comedy_actors_or_typecast_actors_in_a_really_good/', 'https://www.reddit.com/gallery/1ugshec', 'MoviesThatFeelLike', 'A jarring but fascinating exploration of comedic actors delivering dark, unsettling performances in horror-thriller settings.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1579, '1ugv4bq', 'Movies that feel like this?', 'Movies that feel like this?', '', 'Ancient_Win_2837', 1782541648, '/r/MoviesThatFeelLike/comments/1ugv4bq/movies_that_feel_like_this/', 'https://i.redd.it/mehtou2irr9h1.jpeg', 'MoviesThatFeelLike', 'An eerie, gothic atmosphere with haunting pastoral isolation.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1580, '1ugxi9s', 'movies that exude the feeling of wonderment and comfort like this painting, ''Half Moon'' by Tono?', 'movies that exude the feeling of wonderment and comfort like this painting, ''Half Moon'' by Tono?', 'https://preview.redd.it/lfgjcex7gs9h1.png?width=589&format=png&auto=webp&s=b2f19fcca5055601e1720b1ee327c46a823665bb

', 'Extension_Effect_983', 1782549968, '/r/MoviesThatFeelLike/comments/1ugxi9s/movies_that_exude_the_feeling_of_wonderment_and/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1ugxi9s/movies_that_exude_the_feeling_of_wonderment_and/', 'MoviesThatFeelLike', 'wonderment and comfort', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1581, '1ugxnw5', 'Movies with over the top, camp, chaotic, obnoxious villains', 'Movies with over the top, camp, chaotic, obnoxious villains', '', 'Samiad_In_The_Mist', 1782550531, '/r/MoviesThatFeelLike/comments/1ugxnw5/movies_with_over_the_top_camp_chaotic_obnoxious/', 'https://www.reddit.com/gallery/1ugxnw5', 'MoviesThatFeelLike', 'Campy, over-the-top, chaotic, and obnoxious villains chewing the scenery.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1582, '1uh0cez', 'movies or tv shows with these vibes', 'movies or tv shows with these vibes', 'With snowy landscapes and that takes place in winter ', 'DingoTough5900', 1782559737, '/r/MoviesThatFeelLike/comments/1uh0cez/movies_or_tv_shows_with_these_vibes/', 'https://www.reddit.com/gallery/1uh0cez', 'MoviesThatFeelLike', 'A crisp, snowy winter retreat with an undercurrent of isolation and mystery.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1583, '1uh5m1u', 'Irreversible', 'Irréversible', 'Irréversible

Irreversible is an intense and unforgettable cinematic experience. It''s a rollercoaster of emotions: vulgarity, brutality, darkness, and love, all presented in their purest form, with nothing held back. The film demands engagement and leaves a lasting impact.', 'SeriousBattle5750', 1782574066, '/r/MoviesThatFeelLike/comments/1uh5m1u/irreversible/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uh5m1u/irreversible/', 'MoviesThatFeelLike', 'An intense, brutal, and emotionally raw cinematic experience that leaves a lasting impact through its unflinching portrayal of darkness and love.', 'skipped', 'no usable images', NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1584, '1uh6jx3', 'Suggest me a movie based on my character crushes', 'Suggest me a movie based on my character crushes', 'Sidenote I actually met Christina Ricci at a convention!', 'Fun_Butterfly_420', 1782576342, '/r/MoviesThatFeelLike/comments/1uh6jx3/suggest_me_a_movie_based_on_my_character_crushes/', 'https://www.reddit.com/r/characters/comments/1otjt00/what_do_my_character_crushes_say_about_me/?share_id=26YroEIrjWeBunQHw85FT&utm_content=1&utm_medium=ios_app&utm_name=ioscss&utm_source=share&utm_term=1', 'MoviesThatFeelLike', 'A playful and nostalgic adoration for eccentric fictional characters.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1585, '1uh6ndt', 'movies that have this vibe', 'movies that have this vibe', 'movies that feel like a 2010''s garden party ', 'Ecstatic-Coconut-204', 1782576571, '/r/MoviesThatFeelLike/comments/1uh6ndt/movies_that_have_this_vibe/', 'https://www.reddit.com/gallery/1uh6ndt', 'MoviesThatFeelLike', 'A wistful, elegant garden party atmosphere with an undercurrent of dark secrets and melancholic beauty.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1586, '1uh7vet', 'This', 'This', 'Varov\_art on twitter ', 'Jellypathicdream', 1782579521, '/r/MoviesThatFeelLike/comments/1uh7vet/this/', 'https://i.redd.it/yn17yaa4wu9h1.jpeg', 'MoviesThatFeelLike', 'Anarchic, neon-drenched punk energy with a rebellious and chaotic spirit.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1587, '1uh8tfq', 'TLOZ The Wind Waker', 'The Legend of Zelda: The Wind Waker', '', 'TiredEyesGuy', 1782581801, '/r/MoviesThatFeelLike/comments/1uh8tfq/tloz_the_wind_waker/', 'https://www.reddit.com/gallery/1uh8tfq', 'MoviesThatFeelLike', 'A whimsical seafaring adventure with a vibrant, hand-drawn aesthetic.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1588, '1uh9lgu', 'Movies and series with this look/ feel?', 'Movies and series with this look/ feel?', 'British seaside town vibes. Similar to Doc Martin.   
Bonus points if it’s a detective/ crime drama series. Thanks in advance :)', 'flightofthemoth', 1782583694, '/r/MoviesThatFeelLike/comments/1uh9lgu/movies_and_series_with_this_look_feel/', 'https://www.reddit.com/gallery/1uh9lgu', 'MoviesThatFeelLike', 'Cozy British coastal village atmosphere with a mix of quirky charm and underlying mystery, reminiscent of Doc Martin.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1589, '1uhatwb', 'Need a movie with this aesthetic', 'Need a movie with this aesthetic', '', 'moonlightmissE', 1782586677, '/r/MoviesThatFeelLike/comments/1uhatwb/need_a_movie_with_this_aesthetic/', 'https://www.reddit.com/gallery/1uhatwb', 'MoviesThatFeelLike', 'Dark, foggy Victorian streets with an ominous gothic horror atmosphere.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1590, '1uhbiw3', 'Movies that feel like this', '', '', 'Sad_Philosopher_2083', 1782588355, '/r/MoviesThatFeelLike/comments/1uhbiw3/movies_that_feel_like_this/', 'https://i.redd.it/ascof5qdmv9h1.jpeg', 'MoviesThatFeelLike', 'A contemplative, nature-infused mood with journeys through rural and lonely landscapes.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1591, '1uhdk77', 'Need creepy horror movies with this aesthetic!', '', '', 'Rare-Cucumber4264', 1782593361, '/r/MoviesThatFeelLike/comments/1uhdk77/need_creepy_horror_movies_with_this_aesthetic/', 'https://www.reddit.com/gallery/1uhdk77', 'MoviesThatFeelLike', 'Unsettling found-footage horror with masked figures and analog distortion.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1592, '1uhf47p', 'MTFL All hope is gone / existentialism / meaningless existence?', 'All hope is gone / existentialism / meaningless existence?', '', 'siivenn', 1782597319, '/r/MoviesThatFeelLike/comments/1uhf47p/mtfl_all_hope_is_gone_existentialism_meaningless/', 'https://www.reddit.com/gallery/1uhf47p', 'MoviesThatFeelLike', 'A desolate and existential void where hope has vanished and life feels utterly meaningless.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1593, '1uhhdul', 'Bad Omens Specter MV', 'Bad Omens Specter MV', 'i get full body chills every time i watch this mv, any movie recs or even shows?? 🥹🥹', 'imenjoyingthis2much', 1782603176, '/r/MoviesThatFeelLike/comments/1uhhdul/bad_omens_specter_mv/', 'https://www.reddit.com/gallery/1uhhdul', 'MoviesThatFeelLike', 'Eerie and haunting atmospheric horror with surreal, skin-crawling dread.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1594, '1uhltg9', 'I need some movie recommendations pleaseeeee', 'Movies that make you fall in love with yourself', 'Movies that make you fall in love with yourself! I’m a big movie and show fan but I want something more niche ', 'whatthefluffbob', 1782615781, '/r/MoviesThatFeelLike/comments/1uhltg9/i_need_some_movie_recommendations_pleaseeeee/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uhltg9/i_need_some_movie_recommendations_pleaseeeee/', 'MoviesThatFeelLike', 'Films that inspire self-love and personal acceptance.', 'skipped', 'no usable images', NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1595, '1uhmv90', 'This theme song video (trigger warning)', 'This theme song video', 'Minimal blood and roadkill is in the video 😭', 'CampHead3748', 1782618971, '/r/MoviesThatFeelLike/comments/1uhmv90/this_theme_song_video_trigger_warning/', 'https://youtu.be/nlnb_Bnyxps?is=EVy6iq0bCi1-0f9m', 'MoviesThatFeelLike', 'Unsettling and dark video with minimal gore and a melancholic undertone.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1596, '1uhq3ij', 'Movies that feel like these', 'Movies that feel like these', 'Y''all cooked on my last post so here''s another one best movies based on a true story

Pic 1: prayer before dawn

Pic 2: unbroken

Pic 3: the pianist ', 'DaintyCatBug', 1782629371, '/r/MoviesThatFeelLike/comments/1uhq3ij/movies_that_feel_like_these/', 'https://www.reddit.com/gallery/1uhq3ij', 'MoviesThatFeelLike', 'Harrowing true stories of survival and endurance in the face of war and captivity.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1597, '1uhqep9', 'Irreversible', 'Irreversible', 'Recently I watched irreversible it''s a Rollercoaster of emotions vulgarity brutal dark and love, all of these in its purest form nothing held back.', 'SeriousBattle5750', 1782630429, '/r/MoviesThatFeelLike/comments/1uhqep9/irreversible/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uhqep9/irreversible/', 'MoviesThatFeelLike', 'Raw, brutal, and emotionally devastating cinema that holds nothing back.', 'skipped', 'no usable images', NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1598, '1uhqzn8', 'Looking for classic movies (1900-1940) featuring scenes of reading ticker tape or stock tickers.', 'Looking for classic movies (1900-1940) featuring scenes of reading ticker tape or stock tickers.', '[removed]', 'Own-Smile7328', 1782632434, '/r/MoviesThatFeelLike/comments/1uhqzn8/looking_for_classic_movies_19001940_featuring/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1uhqzn8/looking_for_classic_movies_19001940_featuring/', 'MoviesThatFeelLike', 'Vintage black-and-white stock market tension', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1599, '1uhsoyu', 'Movies that feel like this', 'Movies that feel like this', 'This exact set design, please.', 'No_Economics8681', 1782638587, '/r/MoviesThatFeelLike/comments/1uhsoyu/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1uhsoyu', 'MoviesThatFeelLike', 'A nostalgic plunge into the bold, colorful, and slightly surreal interior design of the 1960s and 1970s.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1600, '1uhw8nj', 'Smooth Jazz and cigarettes', 'Smooth Jazz and cigarettes', '', 'llttww83', 1782650246, '/r/MoviesThatFeelLike/comments/1uhw8nj/smooth_jazz_and_cigarettes/', 'https://www.reddit.com/gallery/1uhw8nj', 'MoviesThatFeelLike', 'Late-night urban ennui with smooth jazz, cigarette smoke, and neon-lit cityscapes, evoking a cool, detached 80s/90s noir aesthetic.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1601, '1uhyzwb', 'Any movies or shows that feel like this?', 'Any movies or shows that feel like this?', '', 'CustardSimilar9285', 1782657598, '/r/MoviesThatFeelLike/comments/1uhyzwb/any_movies_or_shows_that_feel_like_this/', 'https://www.reddit.com/gallery/1uhyzwb', 'MoviesThatFeelLike', 'A dark, surreal, and apocalyptic atmosphere with cosmic horror, body horror, religious iconography, and biomechanical imagery.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1602, '1ui4s0s', 'Movies with a Spooky Southern Horror Mystery Feel that Aren’t Slashers', 'Movies with a Spooky Southern Horror Mystery Feel that Aren’t Slashers', 'Looking for movies with a southern mystery horror setting in the visual vein of the movie and game screenshots above. I have already seen Sinners, Is God Is, and some other slashers set in the Louisiana area. Alan Wake 2 or True Detective s1 are another good example of the sort of aesthetic I’m going for I think. Bonus points if it’s witchy', 'TheMightyEmu1466', 1782671338, '/r/MoviesThatFeelLike/comments/1ui4s0s/movies_with_a_spooky_southern_horror_mystery_feel/', 'https://www.reddit.com/gallery/1ui4s0s', 'MoviesThatFeelLike', 'Eerie Southern Gothic mystery shrouded in swamp mist, with witchy undertones and a haunting, atmospheric dread.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1603, '1ul66r7', 'That Y2K blue aesthetic', '', 'What movies have this?', 'neonblakk', 1782960951, '/r/MoviesThatFeelLike/comments/1ul66r7/that_y2k_blue_aesthetic/', 'https://www.reddit.com/gallery/1ul66r7', 'MoviesThatFeelLike', 'A cold, futuristic blue-tinted aesthetic from the Y2K era with a clinical, cybernetic edge.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1604, '1v9r6a3', 'Recommend Films Based on My Top 10 Favorites', '', '(note: these are not objectively the *best* movies but rather, of course, my personal *favorite* movies)

A Ghost Story, I Saw the TV Glow, Coraline, The Lighthouse, Scott Pilgrim vs. the World, The Matrix, Pan’s Labyrinth, Apocalypse Now, Barton Fink, The Last Black Man in San Francisco

subjects of interest include  
\-poststructuralism/postmodernism  
\-nihilism/existentialism  
\-magical realism  
\-folkloric or children’s lit influence  
\-the queer experience  
\-colonization & war  
\-metafiction  
\-alienation  
\-alternate or distorted realities  
\-heavy focus on intertextuality, especially music, philosophy, and literature', 'han___banan', 1785317426, '/r/MoviesThatFeelLike/comments/1v9r6a3/recommend_films_based_on_my_top_10_favorites/', 'https://i.redd.it/4qm5o2fb15gh1.jpeg', 'MoviesThatFeelLike', 'A brooding, introspective labyrinth of fractured realities and poetic dread.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1605, '1vg1jyi', 'Horror movies where a group of survivors are trapped somewhere', 'Horror movies where a group of survivors are trapped somewhere', 'Examples: Dawn of the Dead, Cube, The Mist, Saw II, TWD S1E2 when they’re trapped in Atlanta', 'Raliadose', 1785919000, '/r/MoviesThatFeelLike/comments/1vg1jyi/horror_movies_where_a_group_of_survivors_are/', 'https://www.reddit.com/gallery/1vg1jyi', 'MoviesThatFeelLike', 'Claustrophobic dread and tense survival dynamics as strangers are trapped together in confined, inescapable spaces.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1606, '1vhq6cs', 'Movies that feel psychologically manipulative 🎬', 'Movies that feel psychologically manipulative 🎬', '', 'Ancient_Win_2837', 1786075597, '/r/MoviesThatFeelLike/comments/1vhq6cs/movies_that_feel_psychologically_manipulative/', 'https://i.redd.it/ssttxtxqnvhh1.jpeg', 'MoviesThatFeelLike', 'A collection of unsettling, mind-bending films that psychologically manipulate the audience.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1607, '1vit0h6', 'Cursed movies', 'Cursed movies', 'Dear friends,

For months now, I’ve been looking for films that can recreate the same effect that 3–4 particular movies had on me — movies I like to call “cursed films”: *The Shining*, *Eyes Wide Shut*, *Rosemary’s Baby*, and, to a lesser extent, *Possession*.

Let me explain what I mean. By “cursed films,” I don’t mean movies that are literally associated with a curse (actors dying, accidents on set, and so on), but rather films that evoke a strange feeling in me. They’re movies that, in a way, seem “wrong” — as if they weren’t meant for mass consumption, something you might find hidden away in the Vatican archives. Something people normally aren’t supposed to see.  
Films that show evil creeping into everyday life and the mundane; not necessarily horror films, but movies saturated with a heavy, oppressive atmosphere.

A kiss to anyone who can recommend me more films like these.

Here’s a list of films I’ve tried watching, but that didn’t have quite the same effect on me:  
*The Ninth Gate, The Others, The Wicker Man, Cure, Carrie, Under the Silver Lake, Jacob’s Ladder*', 'EntertainerSmooth920', 1786186710, '/r/MoviesThatFeelLike/comments/1vit0h6/cursed_movies/', 'https://www.reddit.com/gallery/1vit0h6', 'MoviesThatFeelLike', 'Heavy, forbidden dread with evil seeping into the mundane, like unearthed secrets never meant for public view.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1608, '1vk8qk1', 'Movies like Mid90s and/or SLC Punk', '', '', 'Flaky_Occasion_604', 1786329616, '/r/MoviesThatFeelLike/comments/1vk8qk1/movies_like_mid90s_andor_slc_punk/', 'https://www.reddit.com/gallery/1vk8qk1', 'MoviesThatFeelLike', 'Gritty coming-of-age tales immersed in skateboarding, punk, and rebellious youth subcultures of the 80s and 90s.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1609, '1vkavkn', 'Movies with a heavy sickly-green color grade, security-cam visuals, and overwhelming paranoia?', '', '', 'DustyGlass_20', 1786336084, '/r/MoviesThatFeelLike/comments/1vkavkn/movies_with_a_heavy_sicklygreen_color_grade/', 'https://www.reddit.com/gallery/1vkavkn', 'MoviesThatFeelLike', 'A claustrophobic, paranoia-filled atmosphere with a sickly green tint and pervasive surveillance-camera aesthetic.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1610, '1vkbalh', 'Suggest me a underrated movie', '', 'Help me!', 'Character-Bat-7397', 1786337439, '/r/MoviesThatFeelLike/comments/1vkbalh/suggest_me_a_underrated_movie/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vkbalh/suggest_me_a_underrated_movie/', 'MoviesThatFeelLike', 'Passionate cinephiles debate the definition of ''underrated'' while enthusiastically sharing a diverse list of lesser-known film gems.', 'skipped', 'no usable images', NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1611, '1vkeqqe', 'Are there any movies or shows that match or feel like these pictures?', 'Are there any movies or shows that match or feel like these pictures?', '', 'Ultrakirby78', 1786349451, '/r/MoviesThatFeelLike/comments/1vkeqqe/are_there_any_movies_or_shows_that_match_or_feel/', 'https://www.reddit.com/gallery/1vkeqqe', 'MoviesThatFeelLike', 'Retro-futuristic and surreal sci-fi with dystopian, cyberpunk, and AI themes.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1612, '1vksilg', 'Movies that feel like video games', 'Movies that feel like video games', 'The protagonist (player) moves through different areas (stages), grabs new gear or learns skills along the way and fights scores of baddies and "bosses". The "game" doesn''t have to be an explicit plot point like in 13 sins. It can be like rambo or phantom where it just feels that way.', 'SilverSpaceRobot10', 1786385311, '/r/MoviesThatFeelLike/comments/1vksilg/movies_that_feel_like_video_games/', 'https://www.reddit.com/gallery/1vksilg', 'MoviesThatFeelLike', 'Action-driven stage-by-stage journey with gear upgrades and boss encounters.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (1613, '1vl1j2a', 'Cold, lonely and depressive movies', 'Cold, lonely and depressive movies', 'Just very bleak ', 'Ok_Reveal1999', 1786406139, '/r/MoviesThatFeelLike/comments/1vl1j2a/cold_lonely_and_depressive_movies/', 'https://www.reddit.com/gallery/1vl1j2a', 'MoviesThatFeelLike', 'Bleak, cold, and deeply lonely mood.', 'publishable', NULL, NULL, '2026-08-11 22:09:33', '2026-08-11 22:09:33');
