-- 0141_seed_20260823T014200Z_01_posts.sql: data seed from pipeline:load run.
-- Generated:  2026-08-23T01:42:21.405386+00:00
-- Run started: 2026-08-23T01:42:00.270170+00:00
-- Source: data/working/load manifest from this run.
--
-- Idempotent: every INSERT is INSERT OR IGNORE, keyed by the
-- table's natural unique constraint.  Wrangler's migration
-- tracking normally prevents re-apply; the OR IGNORE is
-- defense in depth for partial / interrupted re-runs.
--
-- Chunk: 01_posts (1/5)
-- Tables: imported_vibe_posts.
-- Pipeline-state tables (processing_runs, pipeline_artifacts)
-- are intentionally excluded — they're per-run bookkeeping.

INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2276, '1u38nei', 'Flower, sun, and rain (A paradise that isn''t paradise, despite its looks. It''s like a purgatory).', 'Flower, Sun, and Rain', 'This PS2 and DS game is definitely a trip. There''s alot more to the story of FSR I''m ommiting here, but the theme of isolation on an island is very fascinating to me.', 'Jellypathicdream', 1781205587, '/r/MoviesThatFeelLike/comments/1u38nei/flower_sun_and_rain_a_paradise_that_isnt_paradise/', 'https://www.reddit.com/gallery/1u38nei', 'MoviesThatFeelLike', 'A deceptively beautiful island paradise that masks a surreal, isolating purgatory — a dreamlike trip where nothing is quite what it seems.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2277, '1u38w3b', 'Movies that feel like the Steppe/Haruspex route in Pathologic?', 'Movies that feel like the Steppe/Haruspex route in Pathologic?', '[removed]', 'Purple_Wolverine_183', 1781206128, '/r/MoviesThatFeelLike/comments/1u38w3b/movies_that_feel_like_the_steppeharuspex_route_in/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1u38w3b/movies_that_feel_like_the_steppeharuspex_route_in/', 'MoviesThatFeelLike', 'A request for movies capturing the bleak, atmospheric survival horror of Pathologic''s Steppe/Haruspex route.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2278, '1u3a6zx', 'Movies that feel like the game No I''m not a human', 'Movies that feel like the game No I''m not a human', '', 'No-Consideration3053', 1781209035, '/r/MoviesThatFeelLike/comments/1u3a6zx/movies_that_feel_like_the_game_no_im_not_a_human/', 'https://www.reddit.com/gallery/1u3a6zx', 'MoviesThatFeelLike', 'The atmosphere is eerie and unsettling, with recommendations focusing on horror and thriller movies that evoke a sense of dread and paranoia.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2279, '1u3aov7', 'Something like this?', '', '', 'cheesiestboy', 1781210158, '/r/MoviesThatFeelLike/comments/1u3aov7/something_like_this/', 'https://www.reddit.com/gallery/1u3aov7', 'MoviesThatFeelLike', 'Gritty urban action and dystopian adventure.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2280, '1u3c0ke', 'I mean...', 'I mean...', '', 'Mediocre_Rip_7692', 1781213212, '/r/MoviesThatFeelLike/comments/1u3c0ke/i_mean/', 'https://i.redd.it/o17jbwpd1q6h1.jpeg', 'MoviesThatFeelLike', 'Playful and humorous discussion about movie feels and comparisons.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2281, '1u3cgtk', 'Movies that feel like this?', 'Movies that feel like this?', '', 'Harddisksson69', 1781214281, '/r/MoviesThatFeelLike/comments/1u3cgtk/movies_that_feel_like_this/', 'https://i.redd.it/7r0jw6ri4q6h1.png', 'MoviesThatFeelLike', 'Adventurous and enchanting with a pirate-themed, nostalgic feel.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2282, '1u3cz0p', 'Something like this please', 'Something like this please', '', 'cheesiestboy', 1781215463, '/r/MoviesThatFeelLike/comments/1u3cz0p/something_like_this_please/', 'https://www.reddit.com/gallery/1u3cz0p', 'MoviesThatFeelLike', 'Claustrophobic sci-fi horror set in sterile high-tech facilities where humans lose control to experimental or extraterrestrial threats, blending body horror with dystopian unease.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2283, '1u3d0kp', 'need to cry tonight, recommend me something that will wreck me', 'need to cry tonight recommend me something that will wreck me', 'i don''t even know how to start this. i''ve been holding everything in for so long that i genuinely don''t remember the last time i felt okay.

failed relationships, academic pressure i can''t seem to escape, and constantly feeling like i''m disappointing everyone around me bcz of that. i smile and act fine bcz what else do u do right? u just keep going.

but tonight i just need to cry like really cry. not the fucking kind where a few tears fall and you just wipe them away. the kind where u just break open and let everything out that you have been carrying

does anyone have movie recommendations that will genuinely wreck me? i want to feel something completely', 'studiosooo', 1781215562, '/r/MoviesThatFeelLike/comments/1u3d0kp/need_to_cry_tonight_recommend_me_something_that/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1u3d0kp/need_to_cry_tonight_recommend_me_something_that/', 'MoviesThatFeelLike', 'Raw, desperate need for emotional catharsis—someone who has been suppressing pain and is begging for something to finally break them open.', 'skipped', 'no usable images', NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2284, '1u3d64f', 'I hat Marty Supreme’s original ending', 'Movies that rapidly shift their entire genre at or towards the end', 'To further elaborate: I’m looking for films that rapidly and randomly shift their entire genre towards or at the very end. 

I’m not even looking for good examples. Give me examples where it did NOT work. Those are just as valuable! Thank you all! :)', 'SupremacySinema', 1781215943, '/r/MoviesThatFeelLike/comments/1u3d64f/i_hat_marty_supremes_original_ending/', 'https://i.redd.it/odan6r3i9q6h1.jpeg', 'MoviesThatFeelLike', 'A playful, curious deep-dive into wild genre-flip movies where the discussion itself spirals with enthusiastic, unpolished recommendations.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2285, '1u3dn3a', 'I need a film that feels like', 'I need a film that feels like', '', 'Ok_Push_2665', 1781217129, '/r/MoviesThatFeelLike/comments/1u3dn3a/i_need_a_film_that_feels_like/', 'https://www.reddit.com/gallery/1u3dn3a', 'MoviesThatFeelLike', 'Neon-soaked Miami heat, pastel Art Deco hotels, synthwave sunset drives, and the sweaty glamour of 80s/90s tropical crime — sun-bleached excess with a hint of danger.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2286, '1u3dz1d', 'Movie with this aesthetic', 'Movie with this aesthetic', 'I’m looking for a movie with a creepy cult aesthetic ', 'Lukotheduko', 1781217988, '/r/MoviesThatFeelLike/comments/1u3dz1d/movie_with_this_aesthetic/', 'https://www.reddit.com/gallery/1u3dz1d', 'MoviesThatFeelLike', 'Eerie and cultish atmosphere with a focus on unsettling, mysterious aesthetics.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2287, '1u3em4o', 'Horror films with this aesthetic.', 'Horror Aesthetic: Pacific Northwest Cryptids', 'Sort of American pacific northwest state park with fire watchtowers and woodland cryptids like the goatman or wendigo. Photos are from the video games *Do You Copy?* and *Fears to Fathom:Ironbark Lookout*.', 'Colonel1916', 1781219672, '/r/MoviesThatFeelLike/comments/1u3em4o/horror_films_with_this_aesthetic/', 'https://www.reddit.com/gallery/1u3em4o', 'MoviesThatFeelLike', 'An eerie forest horror aesthetic featuring woodland cryptids and isolation.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2288, '1u3ghbz', 'movies or shows that feel like this?', 'movies or shows that feel like this?', '', 'HighQualityGifs', 1781224731, '/r/MoviesThatFeelLike/comments/1u3ghbz/movies_or_shows_that_feel_like_this/', 'https://www.reddit.com/gallery/1u2x744', 'MoviesThatFeelLike', 'Grotesque biomechanical body horror and cosmic surrealism—organic machinery, mutated flesh, and nightmarish industrial landscapes.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2289, '1u3gkmb', 'This vibe', '', 'Preferably a horror movie but I don''t really mind

The only movies I''ve watched with an aesthetic similar to this are Suspiria(1977) and Inferno, but even those two aren''t exactly like this', 'doodledli', 1781224985, '/r/MoviesThatFeelLike/comments/1u3gkmb/this_vibe/', 'https://www.reddit.com/gallery/1u3gkmb', 'MoviesThatFeelLike', 'Opulent, saturated-hued 80s excess with psychological unease — grand decaying estates and stylized visuals radiating sinister, decadent glamour.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2290, '1u3ivir', 'Ships, Harbors, wharfs, old salts. I’m re reading Moby Dick and want to really capture the spirit of old timey maritime life. (Already love The Lighthouse)', 'Ships harbors wharfs old salts Moby Dick maritime life', '', 'Spare-Department-765', 1781231550, '/r/MoviesThatFeelLike/comments/1u3ivir/ships_harbors_wharfs_old_salts_im_re_reading_moby/', 'https://www.reddit.com/gallery/1u3ivir', 'MoviesThatFeelLike', 'Nostalgic and adventurous, evoking the rugged, isolated life of old-time sailors and maritime exploration.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2291, '1u3j5e2', 'Movies that feel like this painting I did', '', '', 'YeahWellDesigns', 1781232336, '/r/MoviesThatFeelLike/comments/1u3j5e2/movies_that_feel_like_this_painting_i_did/', 'https://i.redd.it/sh421fv8mr6h1.jpeg', 'MoviesThatFeelLike', 'A festive and whimsical atmosphere with nostalgic, quirky charm.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2292, '1u3ks50', 'Movies that give the vibe of these pics of these characters', 'Movies that give the vibe of these pics of these characters', '', 'Fun_Butterfly_420', 1781237261, '/r/MoviesThatFeelLike/comments/1u3ks50/movies_that_give_the_vibe_of_these_pics_of_these/', 'https://www.reddit.com/r/characters/comments/1s3u117/id_like_to_see_these_characters_play_the_weakest/?share_id=uHGkhIteJTSf8Aowuvwtu&utm_content=1&utm_medium=ios_app&utm_name=iossmf&utm_source=share&utm_term=22', 'MoviesThatFeelLike', 'A user seeks movie recommendations that capture a specific, visually referenced character-driven aesthetic or mood.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2293, '1u3l3xx', 'Movies that give off this vibe', 'Movies that give off this vibe', '', 'Fun_Butterfly_420', 1781238294, '/r/MoviesThatFeelLike/comments/1u3l3xx/movies_that_give_off_this_vibe/', 'https://www.reddit.com/gallery/1u3l3xx', 'MoviesThatFeelLike', 'Chaotic, absurd humor-driven post where a random collage of images provokes confusion, shitposting, and a wave of comedic recommendations blending monster movies, jungle adventure films, and bizarre cult classics.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2294, '1u3ltj1', 'Movies that feel like this', 'Movies that feel like this', 'Creepy dolls + amusement parks', 'ExtensionFuture654', 1781240529, '/r/MoviesThatFeelLike/comments/1u3ltj1/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1u3ltj1', 'MoviesThatFeelLike', 'A quirky and creepy vibe blending horror elements with whimsical amusement park settings.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2295, '1u3mgog', 'Any movie suggestion with this type of weather or setting?', 'Any movie suggestion with this type of weather or setting?', '', 'Lolitsmekonichiwa', 1781242588, '/r/MoviesThatFeelLike/comments/1u3mgog/any_movie_suggestion_with_this_type_of_weather_or/', 'https://i.redd.it/3khz7a5qgs6h1.jpeg', 'MoviesThatFeelLike', 'A cozy yet mysterious atmosphere evoking foggy, northern harbor settings with a touch of historical intrigue.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2296, '1u3n4t1', 'Movies that feel like some of these albums', 'Movies that feel like some of these albums', '', 'Alert_Doughnut_4619', 1781244803, '/r/MoviesThatFeelLike/comments/1u3n4t1/movies_that_feel_like_some_of_these_albums/', 'https://i.redd.it/q20szzgbns6h1.jpeg', 'MoviesThatFeelLike', 'A contemplative search for cinematic counterparts to musical moods.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2297, '1u3n5n2', 'Movies that feel like some of these albums', 'Movies that feel like some of these albums', '', 'Alert_Doughnut_4619', 1781244881, '/r/MoviesThatFeelLike/comments/1u3n5n2/movies_that_feel_like_some_of_these_albums/', 'https://i.redd.it/rj5v0ivjns6h1.jpeg', 'MoviesThatFeelLike', 'Seeking cinematic parallels to musical atmospheres.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2298, '1u3nlot', 'Movies that feel like this (fuck JKR, that''s why I''m looking for alternatives) (scary images)', 'Movies that feel like this (scary images) (anti-JKR alternatives)', '', 'TriggerHappyGremlin', 1781246415, '/r/MoviesThatFeelLike/comments/1u3nlot/movies_that_feel_like_this_fuck_jkr_thats_why_im/', 'https://www.reddit.com/gallery/1u3nlot', 'MoviesThatFeelLike', 'A demand for intense, scary movie alternatives with a rebellious edge against mainstream influences.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2299, '1u3op70', 'Movies that give this vibe', '', '', 'real_realist_opt', 1781250268, '/r/MoviesThatFeelLike/comments/1u3op70/movies_that_give_this_vibe/', 'https://www.reddit.com/gallery/1u3op70', 'MoviesThatFeelLike', 'A contemplative and melancholic atmosphere, often capturing the quiet beauty of everyday life and introspective moments.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2300, '1u3s71a', 'Movies with this vibe', 'Movies with this vibe', '', 'Ill-Run8036', 1781262397, '/r/MoviesThatFeelLike/comments/1u3s71a/movies_with_this_vibe/', 'https://i.redd.it/il3hofc23u6h1.png', 'MoviesThatFeelLike', 'A gritty, claustrophobic horror atmosphere of a grim, inescapable room that evokes confinement, dread, and psychological torment.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2301, '1u3w6vi', 'Movies with this vibe', 'Movies with this vibe', '', 'Ambitious-Eagle-1525', 1781272998, '/r/MoviesThatFeelLike/comments/1u3w6vi/movies_with_this_vibe/', 'https://www.reddit.com/gallery/1u3w6vi', 'MoviesThatFeelLike', 'A nocturnal urban vibe characterized by melancholic solitude and neon-lit streets, often in Japanese settings.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2302, '1u3z6z0', 'End of the world/Survival', '', '', 'SlySang', 1781279603, '/r/MoviesThatFeelLike/comments/1u3z6z0/end_of_the_worldsurvival/', 'https://i.redd.it/ta1uegyriv6h1.jpeg', 'MoviesThatFeelLike', 'Grim and tense post-apocalyptic survival atmosphere.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2303, '1u40oa3', 'Movies that feel like Eyes Wide Shut (1999)?', 'Movies that feel like Eyes Wide Shut (1999)?', '', 'Spiritual-Orange692', 1781282715, '/r/MoviesThatFeelLike/comments/1u40oa3/movies_that_feel_like_eyes_wide_shut_1999/', 'https://www.reddit.com/gallery/1tzsl71', 'MoviesThatFeelLike', 'A search for films that evoke the mysterious, surreal, and psychologically tense atmosphere of Eyes Wide Shut.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2304, '1u41xyz', 'Movies that feel like the indomitable expanse of mother nature?', 'Movies that feel like the indomitable expanse of mother nature', '', 'HungryOpportunity322', 1781285443, '/r/MoviesThatFeelLike/comments/1u41xyz/movies_that_feel_like_the_indomitable_expanse_of/', 'https://i.redd.it/xfragys50w6h1.jpeg', 'MoviesThatFeelLike', 'Awe-struck reverence for nature''s overwhelming, indifferent power — vast landscapes that dwarf humanity and nature reclaiming what humans thought was theirs.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2305, '1u42ox0', 'Any movies with this type of setting?', 'Any movies with this type of setting?', '', 'Current-Topic6696', 1781287090, '/r/MoviesThatFeelLike/comments/1u42ox0/any_movies_with_this_type_of_setting/', 'https://i.redd.it/gxn5hgl05w6h1.jpeg', 'MoviesThatFeelLike', 'A cold, gothic, snow-shrouded medieval castle atmosphere evoking dark fantasy and vampire lore.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2306, '1u432lv', 'Looking for movies', 'Looking for movies', 'Does anyone know any movies that feel like any of these

 

2001:a space Odyssey 

Half Man

Labyrinth 

The Twilight zone 

Bojack Horseman 

Rocky

Project hail mary', 'Bojak_Vita', 1781287892, '/r/MoviesThatFeelLike/comments/1u432lv/looking_for_movies/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1u432lv/looking_for_movies/', 'MoviesThatFeelLike', 'A user seeks movie recommendations spanning wide tastes, with commenters enthusiastically suggesting sci-fi, dystopian, and mind-bending films with deeper meanings.', 'skipped', 'no usable images', NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2307, '1u447ds', 'movies that give off the same vibes/feel like hotel california by the eagles', 'movies that give off the same vibes/feel like hotel california by the eagles', '', 'jesselvr', 1781290431, '/r/MoviesThatFeelLike/comments/1u447ds/movies_that_give_off_the_same_vibesfeel_like/', 'https://i.redd.it/yi99firzew6h1.jpeg', 'MoviesThatFeelLike', 'Desert noir with creeping dread beneath sun-soaked California decadence—a golden-hour nightmare you can never leave.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2308, '1u47h5j', 'Gta loading screen vibes', 'Gta loading screen vibes', '', 'Glad-Guarantee1587', 1781297999, '/r/MoviesThatFeelLike/comments/1u47h5j/gta_loading_screen_vibes/', 'https://www.reddit.com/gallery/1u47h5j', 'MoviesThatFeelLike', 'The vibe evokes the gritty, urban, and high-stakes atmosphere of GTA loading screens, with a focus on crime dramas and action.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2309, '1u47tjv', 'Comedies about eccentric children facing everyday and emotional problems?', 'Comedies about eccentric children facing everyday and emotional problems', '', 'm_alcofribas', 1781298790, '/r/MoviesThatFeelLike/comments/1u47tjv/comedies_about_eccentric_children_facing_everyday/', 'https://www.reddit.com/gallery/1u47tjv', 'MoviesThatFeelLike', 'Warm, quirky, and heartfelt nostalgia for coming-of-age stories where oddball kids navigate family dysfunction and growing up with humor and tenderness.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2310, '1u49cew', 'i want to watch like this vibe films', 'i want to watch like this vibe films', '', 'duskyie', 1781302445, '/r/MoviesThatFeelLike/comments/1u49cew/i_want_to_watch_like_this_vibe_films/', 'https://v.redd.it/agj41xopex6h1', 'MoviesThatFeelLike', 'A user shares a visually cinematic image seeking atmospheric, mood-driven films with striking camera work and intimate, contemplative moments.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2311, '1u49h13', 'Any movie with this vibe?', '', '', 'Harddisksson69', 1781302761, '/r/MoviesThatFeelLike/comments/1u49h13/any_movie_with_this_vibe/', 'https://i.redd.it/2l6cgblmfx6h1.png', 'MoviesThatFeelLike', 'A feeling of surreal, paranoid absurdity where mundane tasks become deeply unsettling and otherworldly.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2312, '1u4azdf', 'Something like this', 'Something like this', '', 'cheesiestboy', 1781306660, '/r/MoviesThatFeelLike/comments/1u4azdf/something_like_this/', 'https://www.reddit.com/gallery/1u4azdf', 'MoviesThatFeelLike', 'A tense and clinical atmosphere evoking pandemic containment and scientific dread.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2313, '1u4gs8p', 'I built a movie app that recommends films by emotion instead of genre', 'I built a movie app that recommends films by emotion instead of genre', '', 'depointless', 1781323507, '/r/MoviesThatFeelLike/comments/1u4gs8p/i_built_a_movie_app_that_recommends_films_by/', 'https://www.reddit.com/gallery/1u4gew2', 'MoviesThatFeelLike', 'Hopeful excitement and curiosity about a new tool that personalizes movie discovery through emotional resonance.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2314, '1u4j979', 'What movie emotionally destroyed you and made you question your existence BUT ALSO brought you back to life?', 'Movies that emotionally destroy and revive you', '', 'Tight-Warning-7813', 1781331519, '/r/MoviesThatFeelLike/comments/1u4j979/what_movie_emotionally_destroyed_you_and_made_you/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1u4j979/what_movie_emotionally_destroyed_you_and_made_you/', 'MoviesThatFeelLike', 'Emotionally devastating yet ultimately life-affirming and introspective.', 'skipped', 'no usable images', NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2315, '1u4jj2y', 'Movies which a bunch of shit going on that all add up/are connected.', 'Movies with interconnected plots and multiple storylines.', '', 'Glad-Guarantee1587', 1781332461, '/r/MoviesThatFeelLike/comments/1u4jj2y/movies_which_a_bunch_of_shit_going_on_that_all/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1u4jj2y/movies_which_a_bunch_of_shit_going_on_that_all/', 'MoviesThatFeelLike', 'Intricate, chaotic narratives with multiple intertwined storylines.', 'skipped', 'no usable images', NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2316, '1u4jqyr', 'Movies that have this strange vibe', 'Movies that have this strange vibe', '', 'vladkudas', 1781333230, '/r/MoviesThatFeelLike/comments/1u4jqyr/movies_that_have_this_strange_vibe/', 'https://www.reddit.com/gallery/1u4jqyr', 'MoviesThatFeelLike', 'A dark, surreal, and unsettling avant-garde atmosphere blending industrial decay, existential dread, and cosmic horror through grainy monochrome imagery.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2317, '1u4lxwq', 'Movies that give off the vibe and atmosphere of Waves', 'Movies with atmosphere like Waves', '', 'ButtercupPPG', 1781341082, '/r/MoviesThatFeelLike/comments/1u4lxwq/movies_that_give_off_the_vibe_and_atmosphere_of/', 'https://i.redd.it/l3ifpipll07h1.jpeg', 'MoviesThatFeelLike', 'The post seeks movies with an intimate, emotionally charged atmosphere similar to Waves, emphasizing slow pacing and striking cinematography.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2318, '1u4rp4y', 'Movies that feel both chill and intense', 'Movies that feel both chill and intense', '', 'Male-2003', 1781359134, '/r/MoviesThatFeelLike/comments/1u4rp4y/movies_that_feel_both_chill_and_intense/', 'https://i.redd.it/14bppny9327h1.jpeg', 'MoviesThatFeelLike', 'A blend of relaxed atmospheres with high-stakes tension in cinematic experiences.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2319, '1u4tbl1', 'Movies with this vibe', 'Movies with this vibe', '', 'WhiskeyLothbrok', 1781363206, '/r/MoviesThatFeelLike/comments/1u4tbl1/movies_with_this_vibe/', 'https://www.reddit.com/gallery/1u4tbl1', 'MoviesThatFeelLike', 'Dark, surreal, and atmospheric with a mix of horror, psychological thriller, and cyberpunk elements.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2320, '1u4vdx7', 'A movie, TV series, or cartoon with a similar vibe', '', '', 'Conscious_Loss_3279', 1781368245, '/r/MoviesThatFeelLike/comments/1u4vdx7/a_movie_tv_series_or_cartoon_with_a_similar_vibe/', 'https://www.reddit.com/gallery/1u4vdx7', 'MoviesThatFeelLike', 'A dark, ominous, and surreal atmosphere with industrial and retro-futuristic elements, evoking a sense of mystery and dread.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2321, '1u4wi8g', 'Movies that feel like this painting I did', 'Movies that feel like this painting', '', 'YeahWellDesigns', 1781370919, '/r/MoviesThatFeelLike/comments/1u4wi8g/movies_that_feel_like_this_painting_i_did/', 'https://i.redd.it/sqqs56rb237h1.jpeg', 'MoviesThatFeelLike', 'Quirky, surreal movies with cult absurdity.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2322, '1u4wmwu', 'Movies that show people secretly working against the Nazis. One false move or sound and the whole thing is ruined', 'Movies that show people secretly working against the Nazis. One false move or sound and the whole thing is ruined', 'I love WWII movies but not so much battles, more humans working against the Axis (Nazis) secretly. I love the tension created in movies like Inglorious Basterds, Operation Valkyrie or even the scene in Twilight Zone The Movie when Vic Murrow (RIP) is hiding from the Nazis. Any other suggestions?', 'tinglep', 1781371226, '/r/MoviesThatFeelLike/comments/1u4wmwu/movies_that_show_people_secretly_working_against/', 'https://www.reddit.com/gallery/1u4wmwu', 'MoviesThatFeelLike', 'A tense and suspenseful atmosphere centered on secret resistance during World War II, where every move could lead to disaster.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2323, '1u4wp83', 'Movies with Exciting, Anxiety-Inducing Action Sequences?', 'Movies with Exciting, Anxiety-Inducing Action Sequences?', '', 'BelovedGoat97', 1781371379, '/r/MoviesThatFeelLike/comments/1u4wp83/movies_with_exciting_anxietyinducing_action/', '/r/MovieSuggestions/comments/1u4wkxn/movies_with_exciting_anxietyinducing_action/', 'MoviesThatFeelLike', 'A query seeking the adrenaline rush and tense excitement of high-stakes, suspenseful action cinema.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2324, '1u5g14v', 'Movies that feel like this?', 'Movies that feel like this?', 'OTHERRR then Texas Chainsaw.. I want something that feels like accidentally swallowing someone else’s tobacco in a bottle of Pepsi.', 'Personal-Crazy6179', 1781427193, '/r/MoviesThatFeelLike/comments/1u5g14v/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1u5g14v', 'MoviesThatFeelLike', 'Sun-bleached, grimy 70s Americana exploitation aesthetic—grease-stained roadhouse culture, tobacco-stained nostalgia for a sweaty, morally ambiguous era of trucker films and counter-culture cinema.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2325, '1u5lk3q', 'I just love these specific genres of movies and want to see if anyone knows any good ones ?', '', ' Hello I’m high and I do not really know how reddit works, but I am wondering if any humans out there on this earth we are bound to know of any good movies, documentary’s too Even. Preferably relating to the following genres,   
dystopian / adventure / zombies / plane crash / natural  disasters / caving / survival but not cringe / cannibals /  
\-  
I really enjoyed watching and learning about the Andes mountains plane crash and story through the movie, so I’d like to find more documentary’s, and/or movies with people reenacting non fictional, disastrous events. Whether they are success stories or not. 

I don’t know if this will reach anyone 🦭🐾 ', 'Spiritual_Love6041', 1781444648, '/r/MoviesThatFeelLike/comments/1u5lk3q/i_just_love_these_specific_genres_of_movies_and/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1u5lk3q/i_just_love_these_specific_genres_of_movies_and/', 'MoviesThatFeelLike', 'A high-curious poster earnestly seeking intense survival, disaster, and dystopian movies and documentaries.', 'skipped', 'no usable images', NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2326, '1u6t5ii', 'Movies that feel like this', '', '', 'pesetmememaxxing', 1781557066, '/r/MoviesThatFeelLike/comments/1u6t5ii/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1u6t5ii', 'MoviesThatFeelLike', 'Dystopian and surreal with existential undertones.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2327, '1u773li', 'Recommend movies with the best 1v1 duels, fights etc', 'Recommend movies with the best 1v1 duels, fights etc', 'Guns, swords, hand-to-hand combat... it doesn''t matter 👍🏻', 'elementtwisting', 1781596567, '/r/MoviesThatFeelLike/comments/1u773li/recommend_movies_with_the_best_1v1_duels_fights/', 'https://www.reddit.com/gallery/1u773li', 'MoviesThatFeelLike', 'The atmosphere is intense and adrenaline-fueled, centered around thrilling one-on-one duels and fights across various genres.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2328, '1vubtyw', 'Dark, shiny, sci-fi conspiracy thriller with a touch of dread', 'Dark, shiny, sci-fi conspiracy thriller with a touch of dread', 'The newer Deus Ex games and especially certain parts of Cyberpunk 2077 are exactly what I''m looking for ', 'PatrickHardcastle', 1787305918, '/r/MoviesThatFeelLike/comments/1vubtyw/dark_shiny_scifi_conspiracy_thriller_with_a_touch/', 'https://www.reddit.com/gallery/1vubtyw', 'MoviesThatFeelLike', 'A sleek, dystopian cyberpunk atmosphere blending corporate conspiracy with existential dread.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2329, '1vue64i', 'crime/thriller films that feels like this?', 'crime/thriller films that feels like this?', '', 'Few-Advertising-5164', 1787313052, '/r/MoviesThatFeelLike/comments/1vue64i/crimethriller_films_that_feels_like_this/', 'https://www.reddit.com/gallery/1vue64i', 'MoviesThatFeelLike', 'A gritty, intense atmosphere of urban crime and thriller elements.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2330, '1vuqlj6', 'Divine machinery movies?', 'Divine Machinery Movies', '', 'nishichou27', 1787341600, '/r/MoviesThatFeelLike/comments/1vuqlj6/divine_machinery_movies/', 'https://www.reddit.com/gallery/1vuqlj6', 'MoviesThatFeelLike', 'A search for films that blend divine or cosmic themes with mechanical and technological horror, creating an eerie, surreal atmosphere.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2331, '1vurd7x', 'Slowpaced atmospheric ghost films', 'Slowpaced atmospheric ghost films', 'I''m looking for slowpaced atmospheric ghost films. Stuff like BBC''s Ghost story for christmas series or The Haunting (1963).

There is something weirdly cozy about those old school ghost stories i think.', 'Birger000', 1787343352, '/r/MoviesThatFeelLike/comments/1vurd7x/slowpaced_atmospheric_ghost_films/', 'https://www.reddit.com/gallery/1vurd7x', 'MoviesThatFeelLike', 'Cozy and atmospheric old-school ghost stories with a slow pace.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2332, '1vureqc', 'Movies that feels like an endless night..', '', '', 'That_Firefly', 1787343449, '/r/MoviesThatFeelLike/comments/1vureqc/movies_that_feels_like_an_endless_night/', 'https://www.reddit.com/gallery/1vureqc', 'MoviesThatFeelLike', 'A dark, gothic atmosphere of perpetual night and eerie mystery.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2333, '1vutgi7', 'Movies that feel like Criminals on the Road vibe?', 'Movies that feel like Criminals on the Road vibe', 'I’m looking for movies with that same feeling of being on the run, committing crimes and forming a bond along the way but also with that sense of freedom that comes with being on the road and outside the rules

Bonnie and Clyde (1967)  
Thelma & Louise (1991)  
The End of the F\*\*\*ing world (2017) 

What other movies or shows would you recommend?', 'Ordinary-Gal', 1787348262, '/r/MoviesThatFeelLike/comments/1vutgi7/movies_that_feel_like_criminals_on_the_road_vibe/', 'https://www.reddit.com/gallery/1vutgi7', 'MoviesThatFeelLike', 'Outlaw romanticism—fugitives on the open road bonding over crime and freedom, equal parts dangerous and liberating.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2334, '1vuyl5t', 'Movies that have asthetics like these', 'Movies that have asthetics like these', '', 'EbonyInk95', 1787361506, '/r/MoviesThatFeelLike/comments/1vuyl5t/movies_that_have_asthetics_like_these/', 'https://www.reddit.com/gallery/1vuyl5t', 'MoviesThatFeelLike', 'Cozy autumn nostalgia with a gentle undercurrent of melancholy, evoking crisp leaves, warm sweaters, and the bittersweet ache of fleeting seasons.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2335, '1vuzfep', 'Please suggest movies that feel like this for my tonight’s watch :)', 'Please suggest movies that feel like this for my tonight''s watch', '', 'Fair_Bag_3402', 1787363896, '/r/MoviesThatFeelLike/comments/1vuzfep/please_suggest_movies_that_feel_like_this_for_my/', 'https://www.reddit.com/gallery/1vuzfep', 'MoviesThatFeelLike', 'Dark, atmospheric, and introspective with elements of urban decay and melancholy.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2336, '1vuzh5v', 'Movies like these?', '', 'Eternal Sunshine Of The Spotless Mind

Enemy

Donnie Darko

Lost In Translation

Night Owls

Liminal types', 'Sunflower_Cow_1997', 1787364034, '/r/MoviesThatFeelLike/comments/1vuzh5v/movies_like_these/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vuzh5v/movies_like_these/', 'MoviesThatFeelLike', 'A thread seeking introspective and surreal movies that evoke melancholy and existential themes.', 'skipped', 'no usable images', NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2337, '1vuzvog', 'movie that feel like chainsawman', '', 'yes i saw the chainsaw man movie', 'daddylongjohnsliver', 1787365186, '/r/MoviesThatFeelLike/comments/1vuzvog/movie_that_feel_like_chainsawman/', 'https://www.reddit.com/gallery/1vuzvog', 'MoviesThatFeelLike', 'Seeking dark, surreal, and bizarre films with intense, chaotic energy similar to Chainsaw Man.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2338, '1vv08nb', 'Monster control by mind', '', 'Like love death and robot karnivore', 'AmanYadav19', 1787366253, '/r/MoviesThatFeelLike/comments/1vv08nb/monster_control_by_mind/', 'https://www.reddit.com/gallery/1vv08nb', 'MoviesThatFeelLike', 'The post expresses a desire for sci-fi films featuring mind control over monsters or giant entities, with a tone of casual exploration.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2339, '1vv0tgr', 'Movies That feel like a Greek Goddess', 'Movies That Feel Like a Greek Goddess', '', 'Amazing_Blonde9890', 1787367951, '/r/MoviesThatFeelLike/comments/1vv0tgr/movies_that_feel_like_a_greek_goddess/', 'https://www.reddit.com/gallery/1vv0tgr', 'MoviesThatFeelLike', 'A request for films evoking divine feminine power and mythological grandeur.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2340, '1vv1fp4', 'Movies like these', 'Movies like these', '', 'Fantastic-Tooth-7597', 1787369795, '/r/MoviesThatFeelLike/comments/1vv1fp4/movies_like_these/', 'https://www.reddit.com/gallery/1vv1fp4', 'MoviesThatFeelLike', 'Dark, gritty, and emotionally intense films exploring addiction, coming-of-age struggles, and disturbing themes.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2341, '1vv1g1g', 'Lili Reinhart at The 16th Governors Awards (11/17/2025)', 'Lili Reinhart at The 16th Governors Awards', '', 'EasyFun2704', 1787369825, '/r/MoviesThatFeelLike/comments/1vv1g1g/lili_reinhart_at_the_16th_governors_awards/', 'https://www.reddit.com/gallery/1vv1g1g', 'MoviesThatFeelLike', 'Glamorous red carpet formality at a prestigious Hollywood awards ceremony, though clearly misplaced in this subreddit.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2342, '1vv1nrf', 'Movies that feel like a Japanese Dark Romance', '', '', 'Dear_Babe4314', 1787370492, '/r/MoviesThatFeelLike/comments/1vv1nrf/movies_that_feel_like_a_japanese_dark_romance/', 'https://www.reddit.com/gallery/1vv1nrf', 'MoviesThatFeelLike', 'A dark, intense, and romantic atmosphere blending Japanese aesthetics with themes of passion and violence.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2343, '1vv2zjf', 'Must watch movie funny thriller and action best combination', '', '', 'HairyGiraffe4193', 1787374588, '/r/MoviesThatFeelLike/comments/1vv2zjf/must_watch_movie_funny_thriller_and_action_best/', 'https://i.redd.it/5osgqi7byukh1.jpeg', 'MoviesThatFeelLike', 'Craving for action-packed thrillers with humorous elements.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2344, '1vv2zm0', 'A movie that feels like this image', 'A movie that feels like this image', '[removed]', 'worlds_away00', 1787374593, '/r/MoviesThatFeelLike/comments/1vv2zm0/a_movie_that_feels_like_this_image/', 'https://i.redd.it/4dx280xbyukh1.jpeg', 'MoviesThatFeelLike', 'Seeking a movie that matches a visual or emotional image while avoiding gratuitous gore.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2345, '1vv41d4', 'Films/movies with this vibe', 'Films/movies with this vibe', 'i dont know what kinda plot im looking for, but something that has this kind of cinematography or vibe and feels like this. i''ve watcged friday the 13th which has this kind of cinematography, but probably nit what im looking for. It can be feel good, about friendship, relationship, angst, mental health issues, smmer camp, nostalgic and all. But i prefer teen characters tho. better if it''s in english and also available in youtube but not mandatory. I''ve liked stabd by me and goth (2008) with similar cinematography ', 'Soggy_Strike9338', 1787377907, '/r/MoviesThatFeelLike/comments/1vv41d4/filmsmovies_with_this_vibe/', 'https://www.reddit.com/gallery/1vv41d4', 'MoviesThatFeelLike', 'Nostalgic and cinematic atmosphere with a focus on teen coming-of-age experiences, blending warmth and melancholy.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2346, '1vv4rff', 'Which One Is Better? 300 or Rise of an Empire?', '300 vs Rise of an Empire', '', 'anonymous_0567', 1787380313, '/r/MoviesThatFeelLike/comments/1vv4rff/which_one_is_better_300_or_rise_of_an_empire/', 'https://www.reddit.com/gallery/1vv3dxa', 'MoviesThatFeelLike', 'The discussion reflects a negative and critical atmosphere, with users expressing dislike and making unfavorable comparisons between the movies.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2347, '1vv5hct', 'Movies with this vibe:', '', 'What movies give off a vibe that resembles these ponds, palaces, castles, or even kingdoms with surrounding water?', 'ZElves100', 1787382733, '/r/MoviesThatFeelLike/comments/1vv5hct/movies_with_this_vibe/', 'https://www.reddit.com/gallery/1vv5hct', 'MoviesThatFeelLike', 'Movies evoking medieval grandeur and serene water-bound settings like castles and palaces surrounded by ponds or moats.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2348, '1vv6r9t', 'Petty incident uncovering a massive reality.', 'Movies where a small incident spirals into a massive conspiracy or reality', 'Movies where a small, isolated event spirals into a massive scenario , complex conspiracy or a major plot twist something like 

Chinatown, Rear Window, Fargo, Blow-Out, and The Conversation. These films start with a minor crime or a simple observation before uncovering a much darker reality.

ANY language is welcome.', 'Adorable-Quarter2994', 1787387314, '/r/MoviesThatFeelLike/comments/1vv6r9t/petty_incident_uncovering_a_massive_reality/', 'https://www.reddit.com/gallery/1vv6r9t', 'MoviesThatFeelLike', 'A simmering, paranoid atmosphere of obsessive discovery where mundane observations peel back layers to reveal dark conspiracies lurking beneath the surface.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2349, '1vv8k81', 'secret society movies/shows', 'secret society movies/shows', 'something with vibe/aesthetic from the pics but also a good story that keeps u watching ', 'Acrobatic_Soup9393', 1787393653, '/r/MoviesThatFeelLike/comments/1vv8k81/secret_society_moviesshows/', 'https://www.reddit.com/gallery/1vv8k81', 'MoviesThatFeelLike', 'A tense and enigmatic atmosphere focused on secret societies and hidden conspiracies.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2350, '1vv9d3i', 'Movie feels like this portrayal of people who make their living at the strip clubs', '', '', 'Bulky_Meet4528', 1787396319, '/r/MoviesThatFeelLike/comments/1vv9d3i/movie_feels_like_this_portrayal_of_people_who/', 'https://www.reddit.com/gallery/1vv9d3i', 'MoviesThatFeelLike', 'A gritty and immersive exploration of strip club culture and the lives of those within it.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2351, '1vvabhc', 'Movies that feel like English autumn in luxury Barn', 'Movies that feel like English autumn in luxury Barn', '', 'AdoptedDog69', 1787399253, '/r/MoviesThatFeelLike/comments/1vvabhc/movies_that_feel_like_english_autumn_in_luxury/', 'https://www.reddit.com/gallery/1vvabhc', 'MoviesThatFeelLike', 'Evokes a cozy, nostalgic atmosphere with a luxurious and rustic English autumn vibe.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2352, '1vvb1j2', 'Movies that feel like Cuba-island living', 'Movies that feel like Cuba-island living', '', 'NegotiationMean3042', 1787401369, '/r/MoviesThatFeelLike/comments/1vvb1j2/movies_that_feel_like_cubaisland_living/', 'https://www.reddit.com/gallery/1vvb1j2', 'MoviesThatFeelLike', 'A nostalgic and vibrant collection of films that evoke the tropical atmosphere and daily life of Cuban island living.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2353, '1vvbgml', 'Movies that gives vibes of wuthering heights', '', '', 'chaiegai', 1787402589, '/r/MoviesThatFeelLike/comments/1vvbgml/movies_that_gives_vibes_of_wuthering_heights/', 'https://www.reddit.com/gallery/1vvbgml', 'MoviesThatFeelLike', 'A literal and acrophobic misinterpretation of the classic title Wuthering Heights, leading to discussions and recommendations focused on height-related anxiety rather than the original gothic romance.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2354, '1vvc9s4', 'Am I the only one that can''t play any streaming sites?', 'Am I the only one that can''t play any streaming sites?', 'Pls', 'Mikan_Divzee', 1787404781, '/r/MoviesThatFeelLike/comments/1vvc9s4/am_i_the_only_one_that_cant_play_any_streaming/', '/r/Piracy/comments/1g26hzr/am_i_the_only_one_that_cant_play_any_streaming/', 'MoviesThatFeelLike', 'Frustrated tech troubleshooting in a movie subreddit, met with deadpan humor.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2355, '1vvf66z', 'Looking for something cozy but a little bittersweet', '', '[removed]', 'biscoot-', 1787412032, '/r/MoviesThatFeelLike/comments/1vvf66z/looking_for_something_cozy_but_a_little/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vvf66z/looking_for_something_cozy_but_a_little/', 'MoviesThatFeelLike', 'A longing for comforting media with a touch of melancholy.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2356, '1vvfxea', 'these edits (camera quality, colors and vibe)', '', '', 'CampHead3748', 1787413868, '/r/MoviesThatFeelLike/comments/1vvfxea/these_edits_camera_quality_colors_and_vibe/', 'https://v.redd.it/hy6ox08w6ykh1', 'MoviesThatFeelLike', 'A cinematic atmosphere emphasizing visual edits and color grading.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2357, '1vvg3vn', 'Movies to watch after a concert that captures the feelings of post-concert blues', 'Movies to watch after a concert that captures the feelings of post-concert blues', 'It''s a mix of gratitude, feeling connected, and immensely sad that it''s over but hopefully that these experiences make me human. ', 'Interesting_Ice_9649', 1787414303, '/r/MoviesThatFeelLike/comments/1vvg3vn/movies_to_watch_after_a_concert_that_captures_the/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vvg3vn/movies_to_watch_after_a_concert_that_captures_the/', 'MoviesThatFeelLike', 'A bittersweet afterglow of connection and melancholy after a concert ends.', 'skipped', 'no usable images', NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2358, '1vvgj8l', 'Movies with synthwave/city lights vibe', 'Synthwave City Lights Vibe Movies', '', 'Ok-Patience-8277', 1787415292, '/r/MoviesThatFeelLike/comments/1vvgj8l/movies_with_synthwavecity_lights_vibe/', 'https://www.reddit.com/gallery/1vvgj8l', 'MoviesThatFeelLike', 'Neon-lit cyberpunk nights with a synthwave atmosphere.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2359, '1vvk666', 'Movie that feel like New York in the Summer...', 'Movie that feel like New York in the Summer...', '[deleted]', '[deleted]', 1787423792, '/r/MoviesThatFeelLike/comments/1vvk666/movie_that_feel_like_new_york_in_the_summer/', '', 'MoviesThatFeelLike', 'Nostalgic summer atmosphere in New York City.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2360, '1vvk6xm', 'Movies that feel like New York in the Summer', 'Movies that feel like New York in the Summer', '', 'MaterialRow3769', 1787423842, '/r/MoviesThatFeelLike/comments/1vvk6xm/movies_that_feel_like_new_york_in_the_summer/', 'https://www.reddit.com/gallery/1vvk6xm', 'MoviesThatFeelLike', 'Sweltering, sweat-drenched New York City summers on sun-baked Brooklyn stoops and humid city streets — gritty, nostalgic, and unmistakably urban.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2361, '1vvk93m', '🐱✨ Real Cats React to Pixar’s GATTO Trailer! 😱🌙 | Nero’s Incredible Adve...', 'Real Cats React to Pixar''s GATTO Trailer - Nero''s Incredible Adventure', '', 'Appropriate_Day9274', 1787423982, '/r/MoviesThatFeelLike/comments/1vvk93m/real_cats_react_to_pixars_gatto_trailer_neros/', 'https://youtube.com/watch?v=Nicv4Vj3c2E&si=I4KXMJ7x6-CMdi0H', 'MoviesThatFeelLike', 'Playful and enthusiastic cat-lover energy centered on cute animals and animated entertainment.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2362, '1vvlvsb', 'Government Agent(s) vs. The Horrors', 'Government Agents vs. The Horrors', 'Movies?', 'gunell_', 1787427779, '/r/MoviesThatFeelLike/comments/1vvlvsb/government_agents_vs_the_horrors/', 'https://www.reddit.com/gallery/1vqabnk', 'MoviesThatFeelLike', 'A request for movies where government agents confront supernatural or extraterrestrial horrors, creating an atmosphere of tense suspense and eerie mystery.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2363, '1vvm8no', 'Movies that feel like', 'Movies That Feel Like Pinterest Autumn Aesthetic', 'I hope none of these pictures are ai, but I got them from Pinterest so idk anymore', 'ziziJ123', 1787428633, '/r/MoviesThatFeelLike/comments/1vvm8no/movies_that_feel_like/', 'https://www.reddit.com/gallery/1vvm8no', 'MoviesThatFeelLike', 'Golden autumnal nostalgia for campus life, prep school corridors, and crisp New England fall — yearning for a romanticized intellectual twilight between youth and adulthood.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2364, '1vvmwjq', 'Movies that feel like being a poor and lonely woman coping with living in a big city', 'Movies that feel like being a poor and lonely woman coping with living in a big city', '', 'Key-Practice-8389', 1787430186, '/r/MoviesThatFeelLike/comments/1vvmwjq/movies_that_feel_like_being_a_poor_and_lonely/', 'https://www.reddit.com/gallery/1vvmwjq', 'MoviesThatFeelLike', 'A melancholic, gritty atmosphere of urban poverty, isolation, and the struggle to survive in a big city.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2365, '1vvncwy', 'Movies that feel like this song/music video', 'Movies that feel like this song/music video', '', 'BloodhoundSupervisor', 1787431292, '/r/MoviesThatFeelLike/comments/1vvncwy/movies_that_feel_like_this_songmusic_video/', 'https://youtu.be/0XlO39kCQ-8?is=8MQNZtNkfWMzk0J9', 'MoviesThatFeelLike', 'A request for mood-matching cinema that captures the evocative atmosphere of a specific song or music video.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2366, '1vvndii', 'This song/music video', 'This song/music video', '', 'BloodhoundSupervisor', 1787431334, '/r/MoviesThatFeelLike/comments/1vvndii/this_songmusic_video/', 'https://youtu.be/0XlO39kCQ-8?is=8MQNZtNkfWMzk0J9', 'MoviesThatFeelLike', 'A straightforward media share seeking identification or discussion.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2367, '1vvne4n', 'Movies that feel like this song/music video', 'Movies that feel like this song/music video', '', 'BloodhoundSupervisor', 1787431373, '/r/MoviesThatFeelLike/comments/1vvne4n/movies_that_feel_like_this_songmusic_video/', 'https://youtu.be/0XlO39kCQ-8?is=8MQNZtNkfWMzk0J9', 'MoviesThatFeelLike', 'A whimsical and eclectic discussion of films that match a creative music video''s vibe.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2368, '1vvpap0', 'i NEED a link to download Hereditary', 'Hereditary', '', 'Inside_Victory_2911', 1787436183, '/r/MoviesThatFeelLike/comments/1vvpap0/i_need_a_link_to_download_hereditary/', '/r/Hereditary/comments/1vvpa7e/i_need_a_link_to_download_hereditary/', 'MoviesThatFeelLike', 'An urgent and eager request for the horror film Hereditary.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2369, '1vvpskq', 'Movies that feel like old, mystic romance', 'Movies that feel like old, mystic romance', '', 'gallant_embrace', 1787437479, '/r/MoviesThatFeelLike/comments/1vvpskq/movies_that_feel_like_old_mystic_romance/', 'https://www.reddit.com/gallery/1vvpskq', 'MoviesThatFeelLike', 'A nostalgic yearning for romantic films with a timeless, ethereal, and slightly mystical quality.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2370, '1vvqyq0', 'Are there similar movies to The Wolf of Wall Street', 'Are there similar movies to The Wolf of Wall Street', '', 'cutie_pri', 1787440605, '/r/MoviesThatFeelLike/comments/1vvqyq0/are_there_similar_movies_to_the_wolf_of_wall/', 'https://www.reddit.com/gallery/1vvqyq0', 'MoviesThatFeelLike', 'Seeking recommendations for films with similar high-energy, financial-industry narratives and satirical tone.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2371, '1vvqyz4', 'Movies that feel like these, with giant surreal set pieces', 'Movies that feel like these with giant surreal set pieces', 'The Devils, Metropolis, Fellini Satyricon, Dark City, Holy Mountain, City of Lost Children.', 'Slight_Edge3788', 1787440623, '/r/MoviesThatFeelLike/comments/1vvqyz4/movies_that_feel_like_these_with_giant_surreal/', 'https://www.reddit.com/gallery/1vvqyz4', 'MoviesThatFeelLike', 'A yearning for movies with grandiose, dreamlike production design — towering surreal architecture and ornate, fantastical worlds that overwhelm the senses.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2372, '1vvrck0', 'Movies that feel like Narcos', 'Movies that feel like Narcos', '', 'PriandTiti', 1787441657, '/r/MoviesThatFeelLike/comments/1vvrck0/movies_that_feel_like_narcos/', 'https://www.reddit.com/gallery/1vvrck0', 'MoviesThatFeelLike', 'A gritty, crime-focused discussion seeking intense, realistic portrayals of the drug trade.', 'publishable', NULL, NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2373, '1vvruze', 'The Empty Man', 'The Empty Man', 'I was blown away by this underrated gem.

I also recently watched Archive 81 which gave off similar cosmic horror vibes

Any recommendations for similar types of films or dramas?', 'SkirtEuphoric7456', 1787443066, '/r/MoviesThatFeelLike/comments/1vvruze/the_empty_man/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vvruze/the_empty_man/', 'MoviesThatFeelLike', 'A deeply engaging cosmic horror experience with an aura of mystery and awe.', 'skipped', 'no usable images', NULL, '2026-08-23 01:42:21', '2026-08-23 01:42:21');
