-- 0151_seed_20260825T013805Z_01_posts.sql: data seed from pipeline:load run.
-- Generated:  2026-08-25T01:38:26.748026+00:00
-- Run started: 2026-08-25T01:38:05.306559+00:00
-- Source: data/working/load manifest from this run.
--
-- Idempotent: every INSERT is INSERT OR IGNORE, keyed by the
-- table's natural unique constraint.  Wrangler's migration
-- tracking normally prevents re-apply; the OR IGNORE is
-- defense in depth for partial / interrupted re-runs.
--
-- Chunk: 01_posts (1/5)
-- Tables: imported_vibe_posts.
-- Pipeline-state tables (processing_runs, pipeline_artifacts)
-- are intentionally excluded — they're per-run bookkeeping.

INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2469, '1tz6d4e', 'Southwestern Gothic?', 'Southwestern Gothic', '', 'cookingmama4', 1780820453, '/r/MoviesThatFeelLike/comments/1tz6d4e/southwestern_gothic/', 'https://www.reddit.com/gallery/1tz6d4e', 'MoviesThatFeelLike', 'Sun-baked dread and dusty desolation where desert highways breed paranoia, violence, and lurking supernatural menace.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2470, '1tz7jgy', 'Movies that feel like Season 1 of True Detective?', 'Movies that feel like Season 1 of True Detective', 'I''ve already seen Zodiac, Se7en, and Prisoners. Are there many more like this? ', 'LandWide1362', 1780824697, '/r/MoviesThatFeelLike/comments/1tz7jgy/movies_that_feel_like_season_1_of_true_detective/', 'https://i.redd.it/9p5pu3rwxt5h1.jpeg', 'MoviesThatFeelLike', 'Dark Southern Gothic detectives unraveling ancient evil, steeped in oppressive atmosphere, regional grit, and existential dread.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2471, '1tzctyx', 'Gloomy Midwest vibes', 'Gloomy Midwest vibes', '', 'Present_Friend_6467', 1780840598, '/r/MoviesThatFeelLike/comments/1tzctyx/gloomy_midwest_vibes/', 'https://www.reddit.com/gallery/1tzctyx', 'MoviesThatFeelLike', 'A dark, oppressive atmosphere capturing the gloomy essence of the Midwest.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2472, '1tzedie', 'Movies with this lever of creepiness', 'Movies with this level of creepiness', '', 'Working_Welder_1751', 1780844301, '/r/MoviesThatFeelLike/comments/1tzedie/movies_with_this_lever_of_creepiness/', 'https://www.reddit.com/gallery/1tzedie', 'MoviesThatFeelLike', 'Seeking films that hit a specific sweet spot of unsettling creepiness.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2473, '1tzftf8', 'Movies that feel like a black metal album cover', 'Movies that feel like a black metal album cover', '', 'Haghiri75', 1780847660, '/r/MoviesThatFeelLike/comments/1tzftf8/movies_that_feel_like_a_black_metal_album_cover/', 'https://www.reddit.com/gallery/1tzftf8', 'MoviesThatFeelLike', 'Dark and eerie atmosphere with themes of occultism, grim landscapes, and historical horror, reminiscent of black metal aesthetics.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2474, '1tzg0p4', 'Movies that feel like the series Chernobyl...', 'Movies that feel like the series Chernobyl', '', 'Square-Ad-8911', 1780848110, '/r/MoviesThatFeelLike/comments/1tzg0p4/movies_that_feel_like_the_series_chernobyl/', 'https://i.redd.it/flw4fntqvv5h1.jpeg', 'MoviesThatFeelLike', 'A grim and suspenseful atmosphere seeking intense, atmospheric media similar to Chernobyl.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2475, '1tzgp48', 'Movies that feel like this (besides Paris, Texas)', 'Movies that feel like this (besides Paris, Texas)', '', 'chimpaman', 1780849645, '/r/MoviesThatFeelLike/comments/1tzgp48/movies_that_feel_like_this_besides_paris_texas/', 'https://www.reddit.com/gallery/1tzgp48', 'MoviesThatFeelLike', 'Desolate roadside Americana with existential undertones.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2476, '1tzgylv', 'Movies that feel like the "soda testing" story from VHS Halloween', 'Movies that feel like the "soda testing" story from VHS Halloween', 'I love the idea of watching test tapes for some experiment. But looking in on a bigger project that is not fully explained. ', 'Fit-Adhesiveness2481', 1780850266, '/r/MoviesThatFeelLike/comments/1tzgylv/movies_that_feel_like_the_soda_testing_story_from/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tzgylv/movies_that_feel_like_the_soda_testing_story_from/', 'MoviesThatFeelLike', 'An atmosphere of experimental curiosity and hidden narratives, centered on watching test tapes within a mysterious, larger unexplained project.', 'skipped', 'no usable images', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2477, '1tzhmo3', 'I’m looking for orange-ish movies for a rainbow movie rec social media thingy!! I’ve done red, now I’m looking for orange cinematography, colours etc.', 'Looking for orange-ish movies for a rainbow movie recommendation social media project', '', 'Peraltasilie', 1780851803, '/r/MoviesThatFeelLike/comments/1tzhmo3/im_looking_for_orangeish_movies_for_a_rainbow/', 'https://www.reddit.com/gallery/1tzhmo3', 'MoviesThatFeelLike', 'A playful, collaborative community brainstorming visually warm, orange-hued films for a rainbow-themed creative project.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2478, '1tzi9l0', 'Movies that feel like Jo I hi', 'Movies that feel like Jo I hi', '[deleted]', '[deleted]', 1780853256, '/r/MoviesThatFeelLike/comments/1tzi9l0/movies_that_feel_like_jo_i_hi/', '', 'MoviesThatFeelLike', 'A search for movies that capture a specific, possibly typo-induced, atmospheric feeling.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2479, '1tzib8n', 'Movies that feel like this', 'Movies that feel like this', '1980s teens, high school and bright neighbourhoods. Think back to the future, can’t buy me love. ', 'inyourbooksandmaps', 1780853363, '/r/MoviesThatFeelLike/comments/1tzib8n/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1tzib8n', 'MoviesThatFeelLike', 'Sun-drenched 1980s suburban teenage nostalgia with bright neighborhoods, high school drama, and carefree youthful adventures.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2480, '1tzirzt', 'So what''s your comfort movie?', 'So what''s your comfort movie?', '', 'Internetdidi', 1780854411, '/r/MoviesThatFeelLike/comments/1tzirzt/so_whats_your_comfort_movie/', '/r/TheGirlSurvivalGuide/comments/1tzirrr/so_whats_your_comfort_movie/', 'MoviesThatFeelLike', 'Warm, cozy invitation to share emotionally safe films that provide comfort and familiarity.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2481, '1tzisvf', 'Movies that feel like', 'Movies that feel like', '[removed]', '[deleted]', 1780854466, '/r/MoviesThatFeelLike/comments/1tzisvf/movies_that_feel_like/', '', 'MoviesThatFeelLike', 'A request for movies that evoke a specific feeling, but the feeling is not specified in the available text.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2482, '1tzit4j', 'looking for captivating and surreal movies', 'Looking for Captivating and Surreal Movies', 'ive seen films like fear and loathing in las vegas and i really like this type of movie, please leave suggestions :)', 'diablo567865333', 1780854482, '/r/MoviesThatFeelLike/comments/1tzit4j/looking_for_captivating_and_surreal_movies/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tzit4j/looking_for_captivating_and_surreal_movies/', 'MoviesThatFeelLike', 'Seeking surreal and captivating cinematic experiences with a trippy, mind-bending atmosphere.', 'skipped', 'no usable images', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2483, '1tzitkv', 'Movies that feel like Severance', '', '[removed]', 'laudrupszn11', 1780854510, '/r/MoviesThatFeelLike/comments/1tzitkv/movies_that_feel_like_severance/', 'https://i.redd.it/r9z6l4n11w5h1.jpeg', 'MoviesThatFeelLike', 'A craving for surreal, dystopian corporate thrillers that evoke psychological tension and mystery.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2484, '1tzklct', 'So what''s your comfort movie?', 'So what''s your comfort movie?', '', 'Internetdidi', 1780858375, '/r/MoviesThatFeelLike/comments/1tzklct/so_whats_your_comfort_movie/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tzklct/so_whats_your_comfort_movie/', 'MoviesThatFeelLike', 'A warm, nostalgic celebration of repeat-watch comfort films that feel like a cozy blanket — from whimsical animation to beloved classics people return to again and again.', 'skipped', 'no usable images', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2485, '1tzkmlr', 'So what''s your comfort movie?', 'So what''s your comfort movie?', '', 'Internetdidi', 1780858450, '/r/MoviesThatFeelLike/comments/1tzkmlr/so_whats_your_comfort_movie/', '/r/MoviesThatFeelLike/comments/1tzklct/so_whats_your_comfort_movie/', 'MoviesThatFeelLike', 'A warm, inviting prompt seeking personal comfort food cinema favorites.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2486, '1tzknca', 'So what''s your comfort movie?', 'So what''s your comfort movie?', '', 'Internetdidi', 1780858491, '/r/MoviesThatFeelLike/comments/1tzknca/so_whats_your_comfort_movie/', '/r/MoviesThatFeelLike/comments/1tzklct/so_whats_your_comfort_movie/', 'MoviesThatFeelLike', 'A cozy, nostalgic search for movies that provide emotional comfort and relaxation.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2487, '1tzmaim', 'Movies with this vibe', 'Movies with this vibe', 'Preferably a woman protagonist.', 'UkuleleSugar', 1780862231, '/r/MoviesThatFeelLike/comments/1tzmaim/movies_with_this_vibe/', 'https://i.redd.it/p3dlk0fq1x5h1.jpeg', 'MoviesThatFeelLike', 'Melancholic, introspective atmosphere of a depressed young woman drifting through life — numb, disaffected, and searching for meaning in a haze of exhaustion.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2488, '1tzntul', 'This vibe, but not a gangster movie (if possible)', 'This vibe, but not a gangster movie (if possible)', '', 'Spare-Department-765', 1780865802, '/r/MoviesThatFeelLike/comments/1tzntul/this_vibe_but_not_a_gangster_movie_if_possible/', 'https://www.reddit.com/gallery/1tzntul', 'MoviesThatFeelLike', 'Nostalgic, old-timey urban atmosphere with a sense of longing, often set in mid-20th century New York.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2489, '1tzqbfx', 'Movies that feel like ‘Cherry-coloured funk’ by The Cocteau Twins', 'Movies that feel like ‘Cherry-coloured funk’ by The Cocteau Twins', '', 'zeke-002', 1780871967, '/r/MoviesThatFeelLike/comments/1tzqbfx/movies_that_feel_like_cherrycoloured_funk_by_the/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tzqbfx/movies_that_feel_like_cherrycoloured_funk_by_the/', 'MoviesThatFeelLike', 'Enthusiastic and collaborative sharing of films that evoke the ethereal, melancholic, and dreamlike atmosphere of Cocteau Twins'' music.', 'skipped', 'no usable images', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2490, '1tzr083', 'Movies and shows like this', '', 'It doesn’t have the be the pacific northwest but like this kinda misty/rainy woodsy dark feel

Things ive seen like this already are goonies,twilight and gravity falls

  ', 'NearlyHeadless-Brick', 1780873780, '/r/MoviesThatFeelLike/comments/1tzr083/movies_and_shows_like_this/', 'https://www.reddit.com/gallery/1tzr083', 'MoviesThatFeelLike', 'A request for content with a misty, rainy, and dark wooded atmosphere, evoking a moody Pacific Northwest vibe.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2491, '1tzsl71', 'Movies that feel like Eyes Wide Shut (1999)?', 'Movies that feel like Eyes Wide Shut (1999)?', 'Looking for any movies that feel like Stanley Kubrick’s Eyes Wide Shut. I love the dreamy and bright light or vibrant color feel in the movie. Kubrick is probably one of my favorite filmmakers and this is also one of my favorite movies, I rewatch it every year, and I also got a little deep into the conspiracies behind the movie. I listed some SFW screenshots and two gifs above if that helps.

If any of y’all know something like this, I would appreciate your help. Thanks.', 'Diligent-Educator612', 1780878060, '/r/MoviesThatFeelLike/comments/1tzsl71/movies_that_feel_like_eyes_wide_shut_1999/', 'https://www.reddit.com/gallery/1tzsl71', 'MoviesThatFeelLike', 'A dreamy, surreal quest for films with vibrant visuals and underlying paranoia.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2492, '1tztyao', 'Movies that feel like Marty Robbins’ music', 'Movies that feel like Marty Robbins’ music', 'I was building a list of movies to watch from a previous post i made, and decided why not look for movies that feel like songs too. I love Marty Robbins’ music, I listed 3 of his songs in the images. The suggestions will probably be westerns, something like The Dollars Trilogy.

If you have any recommendations, let me know. Thank y’all 🙏.', 'Diligent-Educator612', 1780881893, '/r/MoviesThatFeelLike/comments/1tztyao/movies_that_feel_like_marty_robbins_music/', 'https://www.reddit.com/gallery/1tztyao', 'MoviesThatFeelLike', 'Nostalgic western ballads meet classic cinematic storytelling in a dusty, evocative atmosphere.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2493, '1tzu353', 'Movies about letting go?', 'Movies about letting go', 'I really like the feeling in certain movies of just letting go and not caring anymore. 

Giving up on societal norms, on living a normal, decent life and letting yourself fall into self-destructive habits.

Also this but in a non-destructive / healing / cathartic way if you know any. 

I think the images explain it better than me :)

Fight Club (1999)

Y Tu Mamá También (2001)

Taxi Driver (1976)

Thirteen (2003)

Climax (2018)

Die My Love (2025)

Mommy (2014)

The Darjeeling Limited (2007)

Thanks!', 'Zkadush', 1780882278, '/r/MoviesThatFeelLike/comments/1tzu353/movies_about_letting_go/', 'https://www.reddit.com/gallery/1tzu353', 'MoviesThatFeelLike', 'A restless longing to shed societal constraints and either spiral into beautiful chaos or find cathartic release.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2494, '1tzu6w7', 'Movies with scenes like these?', '', '', 'aweiner99', 1780882583, '/r/MoviesThatFeelLike/comments/1tzu6w7/movies_with_scenes_like_these/', 'https://www.reddit.com/gallery/1tzu6w7', 'MoviesThatFeelLike', 'A nostalgic and artistic pursuit of visually evocative and emotionally resonant cinema.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2495, '1tzuep7', 'Loved everything about this movie!! More similar suggestions?', 'Loved everything about this movie!! More similar suggestions?', '', 'Level-Finance631', 1780883204, '/r/MoviesThatFeelLike/comments/1tzuep7/loved_everything_about_this_movie_more_similar/', 'https://www.reddit.com/gallery/1tzuegg', 'MoviesThatFeelLike', 'The discussion radiates a cozy, classic period drama atmosphere centered on beloved literary adaptations and romantic, character-driven stories.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2496, '1tzuiw7', 'Movie where there''s a competition show to save a loved one', 'Movie where there''s a competition show to save a loved one', '', 'Limp-Guitar-197', 1780883530, '/r/MoviesThatFeelLike/comments/1tzuiw7/movie_where_theres_a_competition_show_to_save_a/', '/r/tipofmytongue/comments/1tzu1rp/tomt_competition_show_to_save_a_loved_one/', 'MoviesThatFeelLike', 'Anxious searching for a specific movie with a desperate, high-stakes competition premise.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2497, '1tzvczl', 'Mayor of Kingstown-ish Movies?', 'Movies Similar to Mayor of Kingstown', 'Just like the title says! My husband and I have been loving this show and I want to watch movies similar to it after he goes to bed so I’m not tempted to continue watching hahaha ', 'namaste_you_guys', 1780885969, '/r/MoviesThatFeelLike/comments/1tzvczl/mayor_of_kingstownish_movies/', 'https://i.redd.it/xc26fa5b0z5h1.jpeg', 'MoviesThatFeelLike', 'The user seeks movies that mirror the gritty, crime-focused tension of ''Mayor of Kingstown.''', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2498, '1tzw9xx', 'Movies that are actually scary?', 'Movies that are actually scared', 'I dont mean jump scares. I just saw the b@ckrooms and everyone is talking about how scary it is. Sorry I just thought the monster was goofy. Jump scares are cheap. I can be startled for a second then go home and sleep just fine. Ive seen all the classics lime John carpenters the thing and the exorcist. They aren''t all that frightening. I dont think blood and guts scare me. Its more the feeling of being alone with the unknown if that makes sense.', 'crazyguy28', 1780888658, '/r/MoviesThatFeelLike/comments/1tzw9xx/movies_that_are_actually_scary/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tzw9xx/movies_that_are_actually_scary/', 'MoviesThatFeelLike', 'A tense and atmospheric search for horror films that evoke deep psychological dread and fear of the unknown.', 'skipped', 'no usable images', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2499, '1tzy55q', 'Late night movies…', '', '', 'mikehunt7337', 1780894420, '/r/MoviesThatFeelLike/comments/1tzy55q/late_night_movies/', 'https://i.redd.it/bbciglbepz5h1.jpeg', 'MoviesThatFeelLike', 'A nocturnal vibe with intense late-night movie discussions focusing on memorable and provocative scenes.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2500, '1tzysl6', 'Culture is everything (literally everything)', 'Culture is everything (literally everything)', '[deleted]', '[deleted]', 1780896487, '/r/MoviesThatFeelLike/comments/1tzysl6/culture_is_everything_literally_everything/', '', 'MoviesThatFeelLike', 'A sweeping, almost philosophical declaration about the omnipresence of culture.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2501, '1tzzyaq', 'Movies that feel like The Stranglers “Golden Brown”? (either Song or Music video', 'Movies that feel like The Stranglers Golden Brown', 'I really like the song and the music video. If yall have any movie recommendations that match either the feel of music video or the feel of the song, let me know. Thanks 🙏', 'Diligent-Educator612', 1780900404, '/r/MoviesThatFeelLike/comments/1tzzyaq/movies_that_feel_like_the_stranglers_golden_brown/', 'https://www.youtube.com/watch?v=z-GUjA67mdc', 'MoviesThatFeelLike', 'Seeking atmospheric films that evoke the baroque, nostalgic, and exotic mood of a distinctive harpsichord-driven post-punk song.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2502, '1u04mwl', 'Movie that feels like', 'Movie that feels like', '', 'Gotivnn', 1780916530, '/r/MoviesThatFeelLike/comments/1u04mwl/movie_that_feels_like/', 'https://www.reddit.com/gallery/1u04mwl', 'MoviesThatFeelLike', 'A request for a movie that evokes a specific, unspecified feeling.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2503, '1u04ujj', 'Movies that feel like the farm', 'Movies that feel like the farm', 'I''m gonna work back on the farm in a few weeks. And i just finished watching The Wrong Paris (2025), which has me romanticizing farm life way more than i probably should. 

I''m also dating this woman right now, so i might be leaning extra hard into the whole "cozy countryside romance vibe"

What other movies have that kind of farm, rural, small town, country life feeling? The Hannah Montana movie (2009) is on my watch list too.

And yes, before anyone says it, Brokeback Mountain is already on the list.', 'Lazy_Panda77', 1780917174, '/r/MoviesThatFeelLike/comments/1u04ujj/movies_that_feel_like_the_farm/', 'https://www.reddit.com/gallery/1u04ujj', 'MoviesThatFeelLike', 'Romanticizing farm life with a cozy countryside romance vibe.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2504, '1u07dwf', 'From where I can download all season of all Lost or if any one has gdrive link?', '', '', 'Pure-Complex6988', 1780924032, '/r/MoviesThatFeelLike/comments/1u07dwf/from_where_i_can_download_all_season_of_all_lost/', 'https://i.redd.it/k2qraczh526h1.jpeg', 'MoviesThatFeelLike', 'A poster searching for pirated episodes of Lost, met with deflections and one cryptic alternative recommendation.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2505, '1u08q87', 'Recommend me movies based on my favorites', 'Recommend me movies based on my favorites', 'Recommend me movies based on my favorites

A woman under the influence

My own private Idaho

The worst person in the world

Turtles can fly

Ema 2019

Bad timing 1980

Heartbeats 2010

Midsommar 

Another round

A star is born

The piano teacher

Call me by your name

Youth', 'lost-witch', 1780927113, '/r/MoviesThatFeelLike/comments/1u08q87/recommend_me_movies_based_on_my_favorites/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1u08q87/recommend_me_movies_based_on_my_favorites/', 'MoviesThatFeelLike', 'Introspective longing for emotionally raw, intimate, and visually artful cinema exploring complex relationships, desire, and personal upheaval.', 'skipped', 'no usable images', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2506, '1u08r4v', 'What movies feel like Season 1 to you ?', 'What movies feel like Season 1 to you', 'Added NSFW tag since it is kind of horror.', 'CaptainShaboigen', 1780927169, '/r/MoviesThatFeelLike/comments/1u08r4v/what_movies_feel_like_season_1_to_you/', 'https://i.redd.it/v390ohnrvx5h1.jpeg', 'MoviesThatFeelLike', 'A casual horror-tinged discussion where users share atmospheric, unsettling film recommendations that evoke a specific seasonal mood.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2507, '1u09fpn', 'Movies that capture this vibe?', 'Movies that capture this vibe', '', 'SantaHasTrueGrit', 1780928652, '/r/MoviesThatFeelLike/comments/1u09fpn/movies_that_capture_this_vibe/', 'https://i.redd.it/nmkvbwp3j26h1.png', 'MoviesThatFeelLike', 'Neon-drenched, maximalist, chaotic energy — stylized excess with a hazy, dreamlike quality.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2508, '1u09vem', 'Movies that feel like the painting Garden of Earthly Delights by Bosch', '', '', 'SecondStarpilot', 1780929641, '/r/MoviesThatFeelLike/comments/1u09vem/movies_that_feel_like_the_painting_garden_of/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1u09vem/movies_that_feel_like_the_painting_garden_of/', 'MoviesThatFeelLike', 'Surreal and fantastical, evoking a chaotic yet intricate dreamscape.', 'skipped', 'no usable images', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2509, '1u0aq2v', 'Recommendations for movies', 'Recommendations for movies', 'So I need a bit of help    
I want to binge watch movies but I’m not sure what to watch     
I’m interested in a bit of country/cowboy, a bit of romance(but not to the extreme), supernatural and fantasy. There are more but I can’t think of any more at the moment     
Just as a guide I have watched, Yellowstone, vampire diaries and their spinoffs, the Witchers and those are just some. I don’t mind tv series but I do find that I can watch more movies in a day. I also don’t mind animated films. 

I have Stan, Netflix, paramount, Disney + and prime ', 'Traditional_Cow1537', 1780931477, '/r/MoviesThatFeelLike/comments/1u0aq2v/recommendations_for_movies/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1u0aq2v/recommendations_for_movies/', 'MoviesThatFeelLike', 'A viewer seeking immersive, genre-blending movie recommendations for a cozy binge-watch session.', 'skipped', 'no usable images', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2510, '1u0ba0e', 'Neo-Noir ???', 'Neo-Noir Films Discussion', 'Like the vibe of 70s neo-noir films, heres some examples

Taxi Driver  
Chinatown  
The Long Goodbye  
The French Connection  
The American Friend  
Klute

Honorable mention to the bladerunner films, ill tale cyber-noirs too if they exist.', 'melody74u', 1780932662, '/r/MoviesThatFeelLike/comments/1u0ba0e/neonoir/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1u0ba0e/neonoir/', 'MoviesThatFeelLike', 'A collection of dark, suspenseful neo-noir films characterized by moral ambiguity and gritty aesthetics.', 'skipped', 'no usable images', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2511, '1u0eikb', 'Movies that feel like this?', '', '', 'Zealousideal_Cry2970', 1780939525, '/r/MoviesThatFeelLike/comments/1u0eikb/movies_that_feel_like_this/', 'https://i.redd.it/itzmsugkf36h1.jpeg', 'MoviesThatFeelLike', 'A serene, introspective, and earthy atmosphere evoking solitude and connection with nature.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2512, '1u0h0yn', 'i want a movie with the same vibe of the movie "let go"', '', '', 'Cvxbro', 1780944684, '/r/MoviesThatFeelLike/comments/1u0h0yn/i_want_a_movie_with_the_same_vibe_of_the_movie/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1u0h0yn/i_want_a_movie_with_the_same_vibe_of_the_movie/', 'MoviesThatFeelLike', 'A user seeking a film that evokes the same atmospheric mood as ''Let Go''.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2513, '1u0h2hn', 'i want a movie with the same vibe of the song "let go"', 'i want a movie with the same vibe of the song "let go"', '', 'Cvxbro', 1780944771, '/r/MoviesThatFeelLike/comments/1u0h2hn/i_want_a_movie_with_the_same_vibe_of_the_song_let/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1u0h2hn/i_want_a_movie_with_the_same_vibe_of_the_song_let/', 'MoviesThatFeelLike', 'A dreamy, melancholic longing for emotional release and bittersweet beauty, evoked by the ethereal tones of Ark Patrol''s ''Let Go''.', 'skipped', 'no usable images', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2514, '1u0h8bp', 'Movies like taxi driver and joker', 'Movies like Taxi Driver and Joker', '', 'Glad-Guarantee1587', 1780945097, '/r/MoviesThatFeelLike/comments/1u0h8bp/movies_like_taxi_driver_and_joker/', 'https://www.reddit.com/gallery/1u0h8bp', 'MoviesThatFeelLike', 'Dark, gritty, and brooding atmosphere of alienated men spiraling into obsessive madness against grimy urban backdrops.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2515, '1u0hfu4', 'Movies that have this type of setting.', 'Movies that have this type of setting', 'Of any genre, but preferably post-apocalyptic.', 'BlueSM-012', 1780945502, '/r/MoviesThatFeelLike/comments/1u0hfu4/movies_that_have_this_type_of_setting/', 'https://www.reddit.com/gallery/1u0hfu4', 'MoviesThatFeelLike', 'Craving gritty, war-ravaged and post-apocalyptic urban landscapes filled with rubble, collapse, and societal decay.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2516, '1u0i51y', 'Discovering America, pioneering, early colonization', '', 'Movies that feel like The Revenant, The New World, 1883 tv series.   
TV shows similar to Deadwood or The Ballad or Buster Scruggs.   
Movies or TB shows about early American discovery or colonies.   
Any ideas? ', 'Peachachu', 1780946960, '/r/MoviesThatFeelLike/comments/1u0i51y/discovering_america_pioneering_early_colonization/', 'https://www.reddit.com/gallery/1u0i51y', 'MoviesThatFeelLike', 'A request for media capturing the gritty, adventurous spirit of early American frontier life and colonization.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2517, '1u0its1', 'Movies that feel like thursday murder club or knives out?', 'Movies that feel like Thursday Murder Club or Knives Out?', '', 'zsoff13', 1780948431, '/r/MoviesThatFeelLike/comments/1u0its1/movies_that_feel_like_thursday_murder_club_or/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1u0its1/movies_that_feel_like_thursday_murder_club_or/', 'MoviesThatFeelLike', 'A cozy, lighthearted hunt for clever whodunnits and mystery stories with charm, wit, and a puzzle-solving spirit.', 'skipped', 'no usable images', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2518, '1u0iybc', 'Movies that feel like the female version of Fight Club', 'Movies that feel like the female version of Fight Club', '', 'SecondStarpilot', 1780948695, '/r/MoviesThatFeelLike/comments/1u0iybc/movies_that_feel_like_the_female_version_of_fight/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1u0iybc/movies_that_feel_like_the_female_version_of_fight/', 'MoviesThatFeelLike', 'A hungry search for dark, subversive stories where women snap, rebel, and dismantle societal expectations—seeking cathartic rage and identity-crisis narratives filtered through a feminine lens.', 'skipped', 'no usable images', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2519, '1u0j0lp', 'Movies that would get laid the most if it were a person?', 'Movies that would get laid the most if it were a person', '[deleted]', '[deleted]', 1780948827, '/r/MoviesThatFeelLike/comments/1u0j0lp/movies_that_would_get_laid_the_most_if_it_were_a/', '', 'MoviesThatFeelLike', 'A humorous and playful inquiry into anthropomorphized movies with a suggestive twist.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2520, '1u0j1bt', 'Movies that would get laid the most if it were a person?', 'Movies that would get laid the most if it were a person?', '', 'josh_park189', 1780948866, '/r/MoviesThatFeelLike/comments/1u0j1bt/movies_that_would_get_laid_the_most_if_it_were_a/', 'https://www.reddit.com/gallery/1u0j1bt', 'MoviesThatFeelLike', 'A humorous and flirty discussion where users personify movies as sexually attractive characters.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2521, '1u0nlsy', 'Movies where you root for the evil protagonist who wins at the end.', 'Movies where you root for the evil protagonist who wins at the end.', '', 'SecondStarpilot', 1780959344, '/r/MoviesThatFeelLike/comments/1u0nlsy/movies_where_you_root_for_the_evil_protagonist/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1u0nlsy/movies_where_you_root_for_the_evil_protagonist/', 'MoviesThatFeelLike', 'A dark, morally ambiguous thrill where anti-heroes triumph against societal norms.', 'skipped', 'no usable images', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2522, '1u0pd44', 'Anything like this?', '', 'something with this ominous, mysterious and strange feeling. Kinda tedious, silent and sublime too. Anything that has the same vibe as \[this song\](https://youtu.be/S1-A9m4c0mk?si=PxcAWjRcGhVv-9Lg). At least somewhat urban

I''ve already watched the original suspiria, and it feels like this.

Funger 2 has this feeling too.

That doctor who episode with the angel statues that can only move when not beeing seen also has this feeling', 'KRTSHK_Cazzo', 1780963789, '/r/MoviesThatFeelLike/comments/1u0pd44/anything_like_this/', 'https://www.reddit.com/gallery/1u0pd44', 'MoviesThatFeelLike', 'An ominous, mysterious, and strange atmosphere with a silent, sublime quality, often set in urban or eerie environments.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2523, '1u0qbxm', 'Something that feels like the magic of old Hollywood movies (read desc.)', 'Something that feels like the magic of old Hollywood movies', 'The movies included in the photos (so don’t recommend) are

The Red Shoes

Singin in the Rain

Down to Earth

The Tales of Hoffmann 

  
Also, they don’t have to be classic hollywood movies - just feel like them. If it’s a movie from 5 years ago or another country that’s great.', 'blink_twice_9465', 1780966441, '/r/MoviesThatFeelLike/comments/1u0qbxm/something_that_feels_like_the_magic_of_old/', 'https://www.reddit.com/gallery/1u0qbxm', 'MoviesThatFeelLike', 'A yearning for the enchanting and theatrical allure of vintage Hollywood cinema, seeking modern films that evoke similar magic.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2524, '1u0qpso', 'Movies that feel like these pictures...', '', 'Besides anything *Hellraiser*, *Alien*, *It*, *Doctor Who* or *Halloween.* I''m also intimately familiar with Monster''s Inc, so I''m trying to explore other options.', 'XipeTotecwithGlitter', 1780967481, '/r/MoviesThatFeelLike/comments/1u0qpso/movies_that_feel_like_these_pictures/', 'https://www.reddit.com/gallery/1u0qpso', 'MoviesThatFeelLike', 'A campy, horror-comedy atmosphere where monsters and slashers navigate mundane situations with creative flair.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2525, '1u0r90y', 'summer movies/shows with a girl who gives this vibe', 'summer movies shows with a girl who gives this vibe', 'I’m also a girl not trying to be weird lol, just want something nostalgic and summer-y with an effortlessly cool/stunning protagonist ', 'Glass-Room-2138', 1780968954, '/r/MoviesThatFeelLike/comments/1u0r90y/summer_moviesshows_with_a_girl_who_gives_this_vibe/', 'https://i.redd.it/tz8mg9s2v56h1.jpeg', 'MoviesThatFeelLike', 'Nostalgic summer longing for effortlessly cool, sun-drenched femininity — equal parts envy, admiration, and hazy golden-hour daydreaming.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2526, '1u0tjln', 'Specific movies?', 'Specific movies that feel targeted to a particular person or moment in time', 'As in movies that feel like they were made to reach a specific person or type of person at a specific time.

It doesn’t necessarily have to be an art house movie, but it should feel very targeted, like office space or especially I saw the tv glow', 'Phi_1618033988749894', 1780975434, '/r/MoviesThatFeelLike/comments/1u0tjln/specific_movies/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1u0tjln/specific_movies/', 'MoviesThatFeelLike', 'A search for movies that feel laser-targeted to a specific person, subculture, or cultural moment—films that feel like they were made *for you* at exactly the right time.', 'skipped', 'no usable images', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2527, '1u0uo6u', 'movies or tv series with a depressing/realistic atmosphere throughout', 'movies or tv series with depressive realistic atmosphere', 'id like to watch something truly soul-crushing and disturbing, but not in a gorey way. gore is fine, but i want something that will make me feel like life isnt worth living. i know that’s a very vague description, but i recently watched the second episode of that hulu monsterland series. the second half was pretty terrible and made me laugh at how bad some of it was, but the first 30mins or so just follow this kid’s awful life and it made me feel pretty uncomfortable, which is what im looking for.    
if anyone can recommend something like that, id be very grateful, thanks.', 'yelsgup', 1780978765, '/r/MoviesThatFeelLike/comments/1u0uo6u/movies_or_tv_series_with_a_depressingrealistic/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1u0uo6u/movies_or_tv_series_with_a_depressingrealistic/', 'MoviesThatFeelLike', 'Soul-crushing and disturbing, evoking a bleak, nihilistic atmosphere of uncomfortable realism.', 'skipped', 'no usable images', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2528, '1u0ur37', 'Anything that looks like this (grungy/industrial scifi + early 2000s CGI)', 'Anything that looks like this (grungy/industrial scifi + early 2000s CGI)', 'These are from *Garage: Bad Dream Adventure* and *Tamala 2010: A Punk Cat in Outer Space*. If *Tetsuo the Iron Man* and *Eraserhead* were cgi they would for sure fit lol', 'FundaysWithFox', 1780979014, '/r/MoviesThatFeelLike/comments/1u0ur37/anything_that_looks_like_this_grungyindustrial/', 'https://www.reddit.com/gallery/1u0ur37', 'MoviesThatFeelLike', 'A nostalgic craving for dark, industrial cyberpunk aesthetics with early 2000s CGI vibes.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2529, '1u0w4u0', 'Movies and shows that feel like Megahex/Megg and Mogg', 'Movies and shows that feel like Megahex Megg and Mogg', '', 'maz323bf', 1780983391, '/r/MoviesThatFeelLike/comments/1u0w4u0/movies_and_shows_that_feel_like_megahexmegg_and/', 'https://www.reddit.com/gallery/1u0w4u0', 'MoviesThatFeelLike', 'A grimy, surreal, darkly humorous search for counterculture media populated by degenerate stoners and morally bankrupt misfits.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2530, '1u0ywde', 'suggest a movie or TV series with a similar aesthetic', 'suggest a movie or TV series with a similar aesthetic', '', 'Conscious_Loss_3279', 1780992986, '/r/MoviesThatFeelLike/comments/1u0ywde/suggest_a_movie_or_tv_series_with_a_similar/', 'https://www.reddit.com/gallery/1u0ywde', 'MoviesThatFeelLike', 'A dark, surreal atmosphere blending psychological horror, sci-fi, and supernatural elements.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2531, '1u0z8sw', 'movies or TV series with this vibe', '', '', 'Conscious_Loss_3279', 1780994259, '/r/MoviesThatFeelLike/comments/1u0z8sw/movies_or_tv_series_with_this_vibe/', 'https://www.reddit.com/gallery/1u0z8sw', 'MoviesThatFeelLike', 'Pastoral tranquility laced with creeping dread and isolation.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2532, '1u101a4', 'Movies that feel like this', 'Movies that feel like this', '', 'Ted-Bundy-666', 1780997134, '/r/MoviesThatFeelLike/comments/1u101a4/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1u101a4', 'MoviesThatFeelLike', 'Deeply unsettling dystopian unease with themes of surveillance, entrapment, and twisted societal punishment.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2533, '1u10nhx', 'Suggest me movies that feel like tranquil & serene, sunset tender vibe and historic mughal architectural beauty.', 'Suggest me movies that feel like tranquil & serene, sunset tender vibe and historic mughal architectural beauty.', '', 'mehdibaritenei', 1780999341, '/r/MoviesThatFeelLike/comments/1u10nhx/suggest_me_movies_that_feel_like_tranquil_serene/', 'https://i.redd.it/uo1jbtgfd86h1.jpeg', 'MoviesThatFeelLike', 'A yearning for serene, tender sunset atmospheres blended with historical Mughal architectural grandeur.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2534, '1u15i6h', 'Looking for movies and tv shows with this vibe! I have a few already thought out but I’d like more', '', '', 'Peraltasilie', 1781012885, '/r/MoviesThatFeelLike/comments/1u15i6h/looking_for_movies_and_tv_shows_with_this_vibe_i/', 'https://i.redd.it/txzk3pcph96h1.jpeg', 'MoviesThatFeelLike', 'A dark and eerie atmosphere with supernatural and horror elements, evoking mystery and suspense.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2535, '1u17pjt', 'Selene''s story was never really about vampires 🧛‍♀️🩸', 'Selene''s story was never really about vampires', '', 'EmberfallsAmbience', 1781017707, '/r/MoviesThatFeelLike/comments/1u17pjt/selenes_story_was_never_really_about_vampires/', 'https://youtu.be/GPy0Li7ps1A?si=n6X3VfsRc8JO8lvZ', 'MoviesThatFeelLike', 'A reflective, thematic interpretation of Underworld''s Selene arc, hinting at deeper meaning beneath the vampire genre.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2536, '1u1956c', 'Movies and TV shows like this?', 'Movies and TV shows like this?', '[deleted]', '[deleted]', 1781020667, '/r/MoviesThatFeelLike/comments/1u1956c/movies_and_tv_shows_like_this/', '', 'MoviesThatFeelLike', 'A vague request for media recommendations with no context, as the original post content has been deleted.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2537, '1u196bu', 'Movies and TV shows like this?', '', '', 'lanx____', 1781020738, '/r/MoviesThatFeelLike/comments/1u196bu/movies_and_tv_shows_like_this/', 'https://www.reddit.com/gallery/1u196bu', 'MoviesThatFeelLike', 'Curiously seeking movie and TV show recommendations.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2538, '1u199ta', 'Movies and shows that feel like this?', 'Movies and shows that feel like this', '', 'lanx____', 1781020933, '/r/MoviesThatFeelLike/comments/1u199ta/movies_and_shows_that_feel_like_this/', 'https://www.reddit.com/gallery/1u199ta', 'MoviesThatFeelLike', 'The post seeks movies and shows with a mysterious, atmospheric, and often sci-fi or fantasy aesthetic, evoking a sense of wonder and unease.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2539, '1u19jks', 'Any movie', 'Any movie', '', 'ducky3686', 1781021492, '/r/MoviesThatFeelLike/comments/1u19jks/any_movie/', 'https://i.redd.it/ejquxlma7a6h1.jpeg', 'MoviesThatFeelLike', 'A nostalgic and cinematic atmosphere where a visual scene evokes memories of classic action and thriller movies.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2540, '1u19q8g', 'Looking for a movie with a similar vibe to a nightmare I had', 'Looking for a movie with a similar vibe to a nightmare I had', 'A couple of nights ago, I had a very vivid dream that I was driving through stunning desert landscapes, feeling completely free. Then the road climbed into the mountains, becoming steep, winding, and dangerous, and I was overcome with anxiety that I might drive off the cliff. Eventually, I had to stop because I couldn’t go any farther. That’s when I saw a group of human traffickers approaching my car, and I ran to hide, but there was nowhere to hide. I can’t even begin to describe the amount of anxiety I felt, I’m still thinking about it. 

Is there a film about people getting lost in the desert, going through a treacherous terrain, things going badly (it doesn’t have to be human trafficking lol). I realize that I’m probably asking for too much. ', 'black-chaos-void', 1781021872, '/r/MoviesThatFeelLike/comments/1u19q8g/looking_for_a_movie_with_a_similar_vibe_to_a/', 'https://i.redd.it/axecwc6f8a6h1.jpeg', 'MoviesThatFeelLike', 'A spiraling nightmare of desert highways turning into treacherous mountain roads, suffused with escalating anxiety, isolation, and dread.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2541, '1u1ctgo', 'Movies that feel Cerebral?', 'Movies that feel Cerebral', '', 'Southern_Check_6827', 1781028328, '/r/MoviesThatFeelLike/comments/1u1ctgo/movies_that_feel_cerebral/', 'https://v.redd.it/uqva1d9pka6h1', 'MoviesThatFeelLike', 'A community discussion sharing intellectual and thought-provoking science fiction films that engage the mind.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2542, '1u29r01', 'Movies or Shows that feel like this?', 'Movies or Shows that feel like this?', 'Moody, Misty atmosphere, like dark (Netflix)', 'ItsNiranjanWaffles', 1781114332, '/r/MoviesThatFeelLike/comments/1u29r01/movies_or_shows_that_feel_like_this/', 'https://www.reddit.com/gallery/1u29r01', 'MoviesThatFeelLike', 'Moody and misty with a dark, atmospheric tension reminiscent of Netflix''s Dark.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2543, '1vwitlc', 'Any movies that bring back 90s or early 2000s nostalgia? 33 year old millennial', 'Movies that bring back 90s or early 2000s nostalgia', '', 'Obvious-Physics1286', 1787518732, '/r/MoviesThatFeelLike/comments/1vwitlc/any_movies_that_bring_back_90s_or_early_2000s/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vwitlc/any_movies_that_bring_back_90s_or_early_2000s/', 'MoviesThatFeelLike', 'A cozy, nostalgic community of millennials sharing warm memories of the movies that defined their childhood and teen years.', 'skipped', 'no usable images', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2544, '1vwoy0d', 'A movie that feel like Def Jam for Ny', 'A movie that feels like Def Jam for NY', '', 'daddylongjohnsliver', 1787534660, '/r/MoviesThatFeelLike/comments/1vwoy0d/a_movie_that_feel_like_def_jam_for_ny/', 'https://www.reddit.com/gallery/1vwoy0d', 'MoviesThatFeelLike', 'Gritty urban action films infused with hip-hop culture and street-level intensity.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2545, '1vwpv4u', 'Movies that feel like the desert sun', 'Movies that feel like the desert sun', 'These are generic photos I found', 'LoudKitty-2401', 1787537273, '/r/MoviesThatFeelLike/comments/1vwpv4u/movies_that_feel_like_the_desert_sun/', 'https://www.reddit.com/gallery/1vwpv4u', 'MoviesThatFeelLike', 'A scorching, arid atmosphere evoking vast desert landscapes and intense cinematic adventures under the blazing sun.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2546, '1vwqb80', 'Movies that feel like this Teen Titans arc I was obsessed with as a teenager', 'Movies that feel like this Teen Titans arc I was obsessed with as a teenager', '[deleted]', '[deleted]', 1787538555, '/r/MoviesThatFeelLike/comments/1vwqb80/movies_that_feel_like_this_teen_titans_arc_i_was/', '', 'MoviesThatFeelLike', '', 'skipped', 'no usable images; no vibe summary; no enriched recommendation matches', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2547, '1vwqcac', 'Movies that feel like this Teen Titans arc. Good guys forced to go bad with psychological elements ', 'Movies that feel like this Teen Titans arc. Good guys forced to go bad with psychological elements', '', 'falling-waters', 1787538641, '/r/MoviesThatFeelLike/comments/1vwqcac/movies_that_feel_like_this_teen_titans_arc_good/', 'https://i.redd.it/poh4d1z1i8lh1.jpeg', 'MoviesThatFeelLike', 'A search for dark, psychologically complex stories where heroes are corrupted or turned against their will.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2548, '1vwrq1t', 'Alone woman, city night, hookups', 'Alone woman, city night, hookups', 'And this song vibe ... (Still don''t know my name)', 'loopyluvv', 1787542704, '/r/MoviesThatFeelLike/comments/1vwrq1t/alone_woman_city_night_hookups/', 'https://v.redd.it/9fe0qq77u8lh1', 'MoviesThatFeelLike', 'Melancholic urban solitude with intimate late-night encounters.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2549, '1vww1pt', 'Посоветуйте фильм', '', '', 'embremo', 1787557176, '/r/MoviesThatFeelLike/comments/1vww1pt/посоветуйте_фильм/', '/r/kinoman/comments/1vww1ad/посоветуйте_фильм/', 'MoviesThatFeelLike', 'A direct, inquisitive request for movie recommendations.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2550, '1vwxs8o', 'Movies about the illusion of love', 'Movies about the illusion of love', 'Silent romance/misinterpreted silence, no dialogue or unnecessary dialogue, confusion, unreciprocated feelings, open ending, but nothing too mushy or passionate. And nice austere cinematography. I''m looking for a movie where nothing actually happens. Infatuation is the key word. 

Thanks!', 'Miri_001freak', 1787563407, '/r/MoviesThatFeelLike/comments/1vwxs8o/movies_about_the_illusion_of_love/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vwxs8o/movies_about_the_illusion_of_love/', 'MoviesThatFeelLike', 'A longing for restrained, almost hollow romance—love as something felt but never fully inhabited, filtered through silence and gorgeous still frames.', 'skipped', 'no usable images', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2551, '1vx08pa', 'Movies that vibes like this', '', '[deleted]', '[deleted]', 1787571216, '/r/MoviesThatFeelLike/comments/1vx08pa/movies_that_vibes_like_this/', '', 'MoviesThatFeelLike', 'A vague request for movies that evoke an unspecified atmospheric mood.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2552, '1vx09c8', 'Movies that vibes like this', 'Movies that vibes like this', '', 'chaiegai', 1787571265, '/r/MoviesThatFeelLike/comments/1vx09c8/movies_that_vibes_like_this/', 'https://www.reddit.com/gallery/1vx09c8', 'MoviesThatFeelLike', 'User seeking atmospheric, mood-driven films with a particular aesthetic feeling.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2553, '1vx0b0e', 'Ship Ahoy! Movies that gives vibes like this.', 'Ship Ahoy! Movies that gives vibes like this.', '', 'chaiegai', 1787571407, '/r/MoviesThatFeelLike/comments/1vx0b0e/ship_ahoy_movies_that_gives_vibes_like_this/', 'https://www.reddit.com/gallery/1vx0b0e', 'MoviesThatFeelLike', 'A dreamlike, nostalgic maritime atmosphere with twinkling lights on ships evoking a sense of wonder and melancholy ocean-bound longing.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2554, '1vx5eqt', 'Movies that really make you cry', 'Movies that really make you cry', '', 'BipolarsReality', 1787583962, '/r/MoviesThatFeelLike/comments/1vx5eqt/movies_that_really_make_you_cry/', '/r/whattowatch/comments/1vx5eae/movies_that_really_make_you_cry/', 'MoviesThatFeelLike', 'A somber collection of emotionally devastating films designed to evoke tears and deep sadness.', 'skipped', 'no usable images', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2555, '1vx5ma4', 'Movies that feel like this pics', 'Movies that feel like this pics', 'Any genre', 'TravelDelicious8934', 1787584441, '/r/MoviesThatFeelLike/comments/1vx5ma4/movies_that_feel_like_this_pics/', 'https://www.reddit.com/gallery/1vx5ma4', 'MoviesThatFeelLike', 'An open-ended request for atmospheric, mood-driven movie recommendations based on visual inspiration.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2556, '1vx5nki', 'Movies that feel like this?', 'Movies that feel like this?', 'Any genre', 'TravelDelicious8934', 1787584521, '/r/MoviesThatFeelLike/comments/1vx5nki/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vx5nki', 'MoviesThatFeelLike', 'Dark, atmospheric, and eerie with Southern Gothic, cosmic horror, and psychological thriller elements.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2557, '1vx74nh', '''90s country', '90s country', '', 'smoothpaving', 1787587752, '/r/MoviesThatFeelLike/comments/1vx74nh/90s_country/', 'https://www.reddit.com/gallery/1vx74nh', 'MoviesThatFeelLike', 'A nostalgic longing for the dusty, sun-scorched heartland aesthetic of 1990s country music—where honky-tonks, open plains, cowboy culture, and small-town warmth define the mood.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2558, '1vxad99', 'Vintage/Epic warrior/fantasy/scifi?', 'Vintage Epic Warrior Fantasy Sci-Fi', 'Looking for that retro epic aesthetic with epic battles, swords, magic, in a fantasy world. Can be animated even. Doesn''t have to be from that time, can also be an homage to it.

Yes I love 80s metal lol

I''ve seen: Lord of the Rings, Heavy Metal/Heavy Metal 2000, Conan the Barbarian, Berserk', 'Faloodeh123', 1787594591, '/r/MoviesThatFeelLike/comments/1vxad99/vintageepic_warriorfantasyscifi/', 'https://www.reddit.com/gallery/1vxad99', 'MoviesThatFeelLike', 'A nostalgic craving for over-the-top 80s sword-and-sorcery pulp fantasy dripping with heavy metal album cover energy.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2559, '1vxagbn', 'movies that feel like this song', '', '', 'Aware_Session_5038', 1787594771, '/r/MoviesThatFeelLike/comments/1vxagbn/movies_that_feel_like_this_song/', 'https://youtu.be/pjPA7CXutDw', 'MoviesThatFeelLike', 'Searching for cinematic echoes of musical emotion', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2560, '1vxalxy', 'Halloween', '', 'I love Halloween and can’t get enough of it lmao Looking for movies (tv episodes are welcomed as well!) that are Halloween AF. ', 'melloncollie11', 1787595104, '/r/MoviesThatFeelLike/comments/1vxalxy/halloween/', 'https://www.reddit.com/gallery/1vxalxy', 'MoviesThatFeelLike', 'Enthusiastic search for Halloween-themed movies and TV episodes, filled with nostalgia and spooky fun.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2561, '1vxc6fj', 'Films that have a midwestern/plains landscape', 'Films that have a midwestern/plains landscape', 'Bones And All (2022) is one of my favs and I feel nostalgic for this kind of setting x', 'p0ttymouth', 1787598337, '/r/MoviesThatFeelLike/comments/1vxc6fj/films_that_have_a_midwesternplains_landscape/', 'https://www.reddit.com/gallery/1vxc6fj', 'MoviesThatFeelLike', 'A nostalgic yearning for the vast, open emptiness of the American heartland — wide skies, flat horizons, and lonely roads through the plains.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2562, '1vxckye', 'Movies that feel like this?', 'Movies that feel like this?', '', 'NeneaMuddle', 1787599156, '/r/MoviesThatFeelLike/comments/1vxckye/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vxckye', 'MoviesThatFeelLike', 'Gloomy, atmospheric, and unsettling folk horror with elements of slow-burn dread and supernatural tension.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2563, '1vxf79q', 'Movies that feel like this', '', 'These stills are from *Paris, Texas*. This movie has more of a Wild West vibe at the start, but it ends like this. I want to see more stuff like this.', 'MixtureBubbly2587', 1787604878, '/r/MoviesThatFeelLike/comments/1vxf79q/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vxf79q', 'MoviesThatFeelLike', 'Moody urban nocturne with neon-lit streets and cinematic tension.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2564, '1vxibsb', '2000’s tuscan', '2000''s tuscan', '', 'the_secret_mermaid_', 1787612143, '/r/MoviesThatFeelLike/comments/1vxibsb/2000s_tuscan/', 'https://www.reddit.com/gallery/1vxibsb', 'MoviesThatFeelLike', 'A nostalgic early 2000s vibe blending luxury, drama, and reality TV influences.', 'publishable', NULL, NULL, '2026-08-25 01:38:26', '2026-08-25 01:38:26');
