-- 0156_seed_20260826T014324Z_01_posts.sql: data seed from pipeline:load run.
-- Generated:  2026-08-26T01:43:46.753378+00:00
-- Run started: 2026-08-26T01:43:24.717268+00:00
-- Source: data/working/load manifest from this run.
--
-- Idempotent: every INSERT is INSERT OR IGNORE, keyed by the
-- table's natural unique constraint.  Wrangler's migration
-- tracking normally prevents re-apply; the OR IGNORE is
-- defense in depth for partial / interrupted re-runs.
--
-- Chunk: 01_posts (1/5)
-- Tables: imported_vibe_posts.
-- Pipeline-state tables (processing_runs, pipeline_artifacts)
-- are intentionally excluded — they're per-run bookkeeping.

INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2565, '1txyh67', 'Is this whole subreddit for AI training?', 'Is this whole subreddit for AI training?', 'Because it feels like it.', 'InnsmouthFashionWeek', 1780695906, '/r/MoviesThatFeelLike/comments/1txyh67/is_this_whole_subreddit_for_ai_training/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1txyh67/is_this_whole_subreddit_for_ai_training/', 'MoviesThatFeelLike', 'The atmosphere is skeptical and frustrated with concerns about AI training and bot activity diluting genuine recommendations.', 'skipped', 'no usable images', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2566, '1txynmd', 'Movie recommendations needed', 'Movie recommendations needed', '[removed]', 'TheManBetweenStories', 1780696355, '/r/MoviesThatFeelLike/comments/1txynmd/movie_recommendations_needed/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1txynmd/movie_recommendations_needed/', 'MoviesThatFeelLike', 'An open, anticipatory request for movie suggestions.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2567, '1txytoc', 'I want movies/tv series that feels like this playlist', '', 'https://music.youtube.com/playlist?list=PLnoVKgjl5k3kh1JsKHvx7WuF1L-dKoCV4&si=OFP1EjYLCowoB6Nf  
 

So like a forest story/adventure. Like “Untamed”( tv series). Like winter,forest,family,adventure. Idk maybe suburban story or a person/family who lives in the forest. You understand what I’m saying?', 'Realbirisi', 1780696755, '/r/MoviesThatFeelLike/comments/1txytoc/i_want_moviestv_series_that_feels_like_this/', 'https://www.reddit.com/gallery/1txytoc', 'MoviesThatFeelLike', 'A wintry forest adventure with family themes.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2568, '1txzx97', 'Movies that give off these vibes', 'Movies that give off these vibes', '', 'josh_park189', 1780699449, '/r/MoviesThatFeelLike/comments/1txzx97/movies_that_give_off_these_vibes/', 'https://www.reddit.com/gallery/1txzx97', 'MoviesThatFeelLike', 'Sleek cosmopolitan travel energy—airports, airplanes, frequent-flyer lounges, and polished professional worlds with an undercurrent of tension and glamour.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2569, '1ty1umk', 'Movies with constant movement/motion', '', 'I can’t think of any specific image to represent this but I’m talking about movies that are constantly moving forward, where you can feel the momentum in every scene. ', 'Glad-Guarantee1587', 1780704360, '/r/MoviesThatFeelLike/comments/1ty1umk/movies_with_constant_movementmotion/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1ty1umk/movies_with_constant_movementmotion/', 'MoviesThatFeelLike', 'A sense of relentless forward momentum and dynamic motion in cinema.', 'skipped', 'no usable images', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2570, '1ty20wi', 'Villain protagonists who aren’t serial killers', 'Villain protagonists who aren''t serial killers', '', 'Glad-Guarantee1587', 1780704839, '/r/MoviesThatFeelLike/comments/1ty20wi/villain_protagonists_who_arent_serial_killers/', 'https://www.reddit.com/gallery/1ty20wi', 'MoviesThatFeelLike', 'Seeking morally complex anti-heroes beyond serial killer narratives.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2571, '1ty2mmt', 'Looking for film recommendations based on Interstellar, The Virgin Suicides, Apocalypse Now, and other favorites', 'Looking for film recommendations based on Interstellar, The Virgin Suicides, Apocalypse Now, and other favorites', 'Hey everyone, I’d love to get some film recs based on my all time favorites (English preferably). I’m consistently drawn to films with dramatic storytelling, social or societal commentary, complex character dynamics, and beautifully crafted atmospheres.

If I had to pick the three films that have stuck with me the most, it’d probably be Interstellar, The Virgin Suicides, and Apocalypse Now.

More favorites include:  
Epics: Interstellar, Gladiator, Apocalypse Now, Inglourious Basterds, Pulp Fiction, The Godfather

Character-driven / thematic: Good Will Hunting, The Shawshank Redemption, Green Book

Emotional / devastating: Beautiful Boy, 12 Years a Slave, The Pianist

Melancholic / nostalgic: The Virgin Suicides, Call Me by Your Name, Little Women (2019)

Any recs or advice would be greatly appreciated! Thanks in advance!', 'Affectionate-File777', 1780706510, '/r/MoviesThatFeelLike/comments/1ty2mmt/looking_for_film_recommendations_based_on/', '/r/MovieSuggestions/comments/1ty2lvb/looking_for_film_recommendations_based_on/', 'MoviesThatFeelLike', 'A nostalgic and dramatic quest for cinematic depth and emotional resonance.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2572, '1ty2q82', 'MTFL this specific genre of early 2010s hipster music', 'MTFL this specific genre of early 2010s hipster music', '', 'Brianna-Imagination', 1780706782, '/r/MoviesThatFeelLike/comments/1ty2q82/mtfl_this_specific_genre_of_early_2010s_hipster/', 'https://www.reddit.com/gallery/1ty2q82', 'MoviesThatFeelLike', 'A nostalgic and indie atmosphere reminiscent of early 2010s hipster music scenes.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2573, '1ty39r0', 'Movies that feel like these old beer ads?', 'Movies that feel like these old beer ads?', '', 'Bonchez', 1780708293, '/r/MoviesThatFeelLike/comments/1ty39r0/movies_that_feel_like_these_old_beer_ads/', 'https://www.reddit.com/gallery/1ty39r0', 'MoviesThatFeelLike', 'Nostalgic yearning for a wholesome, idealized mid-century American small-town Americana of cookouts, camaraderie, and golden-hour warmth.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2574, '1ty3vyg', 'Horror movies or series with this atmosphere.', 'Horror movies or series with this atmosphere.', '', 'BlueSM-012', 1780710056, '/r/MoviesThatFeelLike/comments/1ty3vyg/horror_movies_or_series_with_this_atmosphere/', 'https://www.reddit.com/gallery/1ty3vyg', 'MoviesThatFeelLike', 'A request for dark, atmospheric horror content evoking classic and modern supernatural dread and gothic terror.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2575, '1ty43bw', 'Give me your best sci-fi thriller movies', 'Give me your best sci-fi thriller movies', 'What are the best sci-fi thriller movies that you have watched that would keep you hooked? I need a good TV show to watch tonight.

Movies I really like: Arrival - The Invisible Guest - Get Out - Escape Room', 'Thin-Celebration7605', 1780710649, '/r/MoviesThatFeelLike/comments/1ty43bw/give_me_your_best_scifi_thriller_movies/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1ty43bw/give_me_your_best_scifi_thriller_movies/', 'MoviesThatFeelLike', 'Engaging and suspenseful sci-fi thrillers recommended for a hooked watch.', 'skipped', 'no usable images', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2576, '1ty48xh', 'Movies that feel like this??', 'Movies that feel like this??', '', 'Personal-Crazy6179', 1780711092, '/r/MoviesThatFeelLike/comments/1ty48xh/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1ty48xh', 'MoviesThatFeelLike', 'Surreal and unsettling atmosphere blending body horror with natural and psychological terror.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2577, '1ty4ax5', 'Movies that give off this vibe', 'Movies that give off this vibe', 'Anything goes icl', 'Jimboseth', 1780711243, '/r/MoviesThatFeelLike/comments/1ty4ax5/movies_that_give_off_this_vibe/', 'https://www.reddit.com/gallery/1ty4ax5', 'MoviesThatFeelLike', 'Dark and surreal horror atmosphere with grotesque and unsettling imagery.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2578, '1ty4cb3', 'What movie have this vibe?', 'What movie have this vibe?', '', 'Animememeboi96', 1780711351, '/r/MoviesThatFeelLike/comments/1ty4cb3/what_movie_have_this_vibe/', 'https://i.redd.it/zh1udn83lk5h1.jpeg', 'MoviesThatFeelLike', 'An atmospheric mood characterized by urban tension and nocturnal settings.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2579, '1ty5aua', 'Movies or TV shows that feel like this?', 'Movies or TV shows that feel like this?', '', 'Decent-Journalist996', 1780714129, '/r/MoviesThatFeelLike/comments/1ty5aua/movies_or_tv_shows_that_feel_like_this/', 'https://www.reddit.com/gallery/1ty5aua', 'MoviesThatFeelLike', 'A post seeking movies or TV shows with an unsettling, psychological atmosphere, likely involving themes of control and societal pressure.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2580, '1ty60c5', 'Movies that feel like the streets of Japan?', 'Movies that feel like the streets of Japan?', '', 'LiteFennec', 1780716226, '/r/MoviesThatFeelLike/comments/1ty60c5/movies_that_feel_like_the_streets_of_japan/', 'https://www.reddit.com/gallery/1ty60c5', 'MoviesThatFeelLike', 'Urban neon-soaked Japanese streets at night — restless, atmospheric, and cinematic.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2581, '1ty65hs', 'Movies that have this vibe?', 'Movies that have this vibe?', '', 'ThatBenGuy23', 1780716653, '/r/MoviesThatFeelLike/comments/1ty65hs/movies_that_have_this_vibe/', 'https://www.reddit.com/gallery/1ty65hs', 'MoviesThatFeelLike', 'A dark and eerie supernatural horror atmosphere with unsettling vibes.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2582, '1ty66bo', 'movies that are entirely about aura farming', 'movies that are entirely about aura farming', '', 'thrillerparker', 1780716721, '/r/MoviesThatFeelLike/comments/1ty66bo/movies_that_are_entirely_about_aura_farming/', 'https://i.redd.it/kcmtxj611l5h1.jpeg', 'MoviesThatFeelLike', 'A request for films entirely focused on cultivating a distinct, powerful atmosphere or persona.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2583, '1ty6bvy', 'movies: psychosexual, dramatic, emotional tension releasing, slightly religious', 'movies: psychosexual, dramatic, emotional tension releasing, slightly religious', 'something that’s intense, mindfuck, relationships, David Lynch esque, messy, sad endings ', 'TwoStreet5049', 1780717172, '/r/MoviesThatFeelLike/comments/1ty6bvy/movies_psychosexual_dramatic_emotional_tension/', 'https://www.reddit.com/gallery/1ty6bvy', 'MoviesThatFeelLike', 'A craving for visceral, psychologically unhinged cinema where psychosexual desire, religious ecstasy, and emotional devastation collide in Lynchian fog.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2584, '1ty6n6k', 'No horror movie has made me feel genuine terror. This is the kind of thing that does it for me. Any recommendations?', 'No horror movie has made me feel genuine terror. This is the kind of thing that does it for me. Any recommendations?', 'I have seen Gonjiam. ', 'Jimboseth', 1780718107, '/r/MoviesThatFeelLike/comments/1ty6n6k/no_horror_movie_has_made_me_feel_genuine_terror/', 'https://www.reddit.com/gallery/1ty6n6k', 'MoviesThatFeelLike', 'A hunger for genuine dread—the OP and community chase the rare, lingering terror that burrows under skin rather than relying on jump scares, sparking passionate debate about what truly unsettles.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2585, '1tyap2h', 'Create a cinematic action scene with dynamic shots 🎥', 'Create a cinematic action scene with dynamic shots', 'Innovative sound design meets creative thinking, crafting immersive experiences through collaboration, imagination, and dynamic audio storytelling techniques 🥷🏻', 'Aakashh0408', 1780731189, '/r/MoviesThatFeelLike/comments/1tyap2h/create_a_cinematic_action_scene_with_dynamic_shots/', 'https://v.redd.it/h0ux70118m5h1', 'MoviesThatFeelLike', 'A creative proposal for dynamic action scenes is dismissed as off-topic, evoking a sense of thwarted enthusiasm.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2586, '1tyc7nc', 'movie websites', 'movie websites', 'yall i don’t have no more movie websites  help ME OUTT , does anyone have a goood movie website thats js like Netflix and good quality and lil yk LOOKS LIKE NETFLIX TOO like something like cineby cuz its down unfortunately so pls help ommhh', 'mvculll', 1780736581, '/r/MoviesThatFeelLike/comments/1tyc7nc/movie_websites/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tyc7nc/movie_websites/', 'MoviesThatFeelLike', 'A streaming enthusiast desperately hunting for free Netflix-like alternatives after their go-to site went down, leaning on community help to fill the gap.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2587, '1tydr0z', 'I want movies/tv series that feels like this playlist', '', ' https://music.youtube.com/playlist?list=PLnoVKgjl5k3kh1JsKHvx7WuF1L-dKoCV4&si=OFP1EjYLCowoB6Nf      

So like a forest story/adventure. Like “Untamed”( tv series). Like winter,forest,family,adventure. Idk maybe suburban story or a person/family who lives in the forest. You understand what I’m saying?', 'Realbirisi', 1780742038, '/r/MoviesThatFeelLike/comments/1tydr0z/i_want_moviestv_series_that_feels_like_this/', 'https://www.reddit.com/gallery/1tydr0z', 'MoviesThatFeelLike', 'A cozy and adventurous forest setting with family and winter elements.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2588, '1tyecpm', 'A dreamlike, nostalgic, and empty world.', 'A dreamlike, nostalgic, and empty world.', '', 'Cold-Bed498', 1780744063, '/r/MoviesThatFeelLike/comments/1tyecpm/a_dreamlike_nostalgic_and_empty_world/', 'https://www.reddit.com/gallery/1tyecpm', 'MoviesThatFeelLike', 'A wistful, surreal yearning for empty dreamscapes and nostalgic absurdity, where the world feels half-remembered and eerily still.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2589, '1tygs66', 'What is a movie that feels like a lunchble''s pizza', 'What is a movie that feels like a lunchble''s pizza', '', 'Lanky-Impact-4747', 1780751107, '/r/MoviesThatFeelLike/comments/1tygs66/what_is_a_movie_that_feels_like_a_lunchbles_pizza/', 'https://i.redd.it/aiqyq5g2vn5h1.jpeg', 'MoviesThatFeelLike', 'A humorous and nostalgic comparison evoking childhood memories of Lunchable''s pizza.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2590, '1tyhkxq', 'Movies like the hidden figures....', 'Movies like the hidden figures....', 'I found clips of hidden figures on tiktok and decided to give it a try. To be honest, biographical movies usually aren’t my thing, but this one completely pulled me in. I genuinely forgot I was watching a biography. The performances were incredible, and the way the film portrayed racism, resilience, and the courage to stand up for what’s right was both powerful and chilling. By the end, I was fully invested in the story and the characters. It turned out to be one of those movies that stays with you after the credits roll.    
Since I enjoyed this so much, what are some other movies you’d recommend that have a similar impact? They don’t necessarily have to be biographies just great films that leave a lasting impression.', 'Fiery_Candy', 1780753232, '/r/MoviesThatFeelLike/comments/1tyhkxq/movies_like_the_hidden_figures/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tyhkxq/movies_like_the_hidden_figures/', 'MoviesThatFeelLike', 'Seeking emotionally powerful and thought-provoking films with lasting impact.', 'skipped', 'no usable images', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2591, '1tyhkxv', 'Is there a movie you ''hate'' that you’ve watched more than five times just because it’s a comfort watch?', 'Comfort watches you hate', '', 'Low_Moose_2765', 1780753233, '/r/MoviesThatFeelLike/comments/1tyhkxv/is_there_a_movie_you_hate_that_youve_watched_more/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tyhkxv/is_there_a_movie_you_hate_that_youve_watched_more/', 'MoviesThatFeelLike', 'A cozy, contradictory nostalgia for flawed movies you can''t stop rewatching — comfort through repetition even when the film itself falls short.', 'skipped', 'no usable images', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2592, '1tyiau4', 'films that feel like Dark Souls', '', 'more than just medieval fantasy, can you think about some films with a lonely knight which might be similar to Dark Souls trilogy mood? preferably niche', 'Due-Abbreviations180', 1780755058, '/r/MoviesThatFeelLike/comments/1tyiau4/films_that_feel_like_dark_souls/', 'https://www.reddit.com/gallery/1tyiau4', 'MoviesThatFeelLike', 'A desolate and oppressive atmosphere evoking lonely knights wandering through dark, mythic landscapes.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2593, '1tyitd8', 'Crime b-movies', 'Crime B-Movies', '&#x200B;

Please help me find this movie, or something like it...

It starts with a woman going to her drug dealers apartment and being invited inside. The dealer snatches her rent/bail(?) money and she wants it back, in the struggle the Dealer is hit in the head with a piece of the Berlin Wall. Before she can leave the scene of the crime a druggie knocks on the door asking for a fix. The next half or so of the movie is her serving the dealers customers as she waits for her best friend to arrive to help her. A hooker/prostitute that was in the apartment bedroom wakes up from her drug induced coma and goes to the bathroom to get a fix when she discovers the body, and the 2 women who did it.  The hooker is happy that the dealer is dead as she had been planning to murder him anyways, she offers to help them cover-up the murder. They roll the guy up in a huge rug and seduce some skater boys into carrying it down the stairs, a shoe falls off the corpse.

With the rug-roll secured to the roof of a car with christmas lights as rope the main protagonist girl gets a call from her brother who is in jail and needs her to come pick him up (and pay bail?) She zooms over to the police station concealed body and all and heads inside to get her brother. While absent her best friend and the stripper are approached by a police officer who inspects the rug and determines (after a tense moment) that it is improperly secured, luckily he has rope in his truck/car. They re-tie the corpse sushi to the roof of the car with rope this time and thank the officer for his help. By then the sibilings had returned and got in the car.

Upon arriving at her own house to drop off her brother her mom expresses an obsessive interest in purchasing/taking the vintage rug the body is wrapped in. After several minutes of dissuading her and lying they part ways and head to the city dump. There they drop off the "package" and before they separate the stripper tells the two best friends that she can tell they''re totally gay for each other and should get together. Protag decides to leave her abusive boyfriend for kind supportive girlfriend who helped her quit cocaine. at the end it''s revealed the guy in the rug was just unconscious the entire time, he wakes up very confused.', 'SecretarySouthern160', 1780756271, '/r/MoviesThatFeelLike/comments/1tyitd8/crime_bmovies/', 'https://www.reddit.com/gallery/1tyitd8', 'MoviesThatFeelLike', 'Gritty, darkly comic crime sleuthing with pulpy low-budget energy and collaborative internet detective work.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2594, '1tyl8d3', 'Like…', 'Like', 'Art by Coby Whitmore, James Williamson, Robert Jones, Joe Bowler, Al Parker, Lucia Lerner, Mike Ludlow', 'Formal_Woodpecker450', 1780762007, '/r/MoviesThatFeelLike/comments/1tyl8d3/like/', 'https://www.reddit.com/gallery/1tyl8d3', 'MoviesThatFeelLike', 'Sophisticated mid-century glamour evoking cocktail lounges, European chic, and romantic Hollywood elegance with vivid retro color palettes.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2595, '1tyn703', 'Movies, please', 'Movies please', '\*\*\*Guys, pls suggest some movies its getting so boring\*\*\*', 'OpportunityAdept9947', 1780766578, '/r/MoviesThatFeelLike/comments/1tyn703/movies_please/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tyn703/movies_please/', 'MoviesThatFeelLike', 'A bored poster seeking casual movie suggestions in a low-effort, somewhat unhelpful thread.', 'skipped', 'no usable images', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2596, '1tyndev', 'Finally Found The Best IPTV Service Provider That Actually Works in 2026 – Ultimate Best IPTV Review', 'Best IPTV Service Provider That Works', '[removed]', 'RundomUser', 1780766980, '/r/MoviesThatFeelLike/comments/1tyndev/finally_found_the_best_iptv_service_provider_that/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tyndev/finally_found_the_best_iptv_service_provider_that/', 'MoviesThatFeelLike', 'Triumphant relief at discovering a reliable IPTV service after struggles.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2597, '1tyngrs', 'Movies that feel like', 'Snowy adventure and mystery movies', 'Mystery or adventure movies based in the snow! Don''t really love the everest/mountaineering centred films, really looking more of cowboys/detectives/fur trappers in a snow storm setting!! Snow doesn''t have to be present all the time but needs to be the back drop! Very Thankful for any recommendations!!!', 'No_Anxiety_9747', 1780767192, '/r/MoviesThatFeelLike/comments/1tyngrs/movies_that_feel_like/', 'https://www.reddit.com/gallery/1tyngrs', 'MoviesThatFeelLike', 'Rugged snowy adventure with mystery elements.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2598, '1tynxim', 'Great English language films for this?', 'Great English language films for this?', '', 'NeighborhoodLoud2076', 1780768260, '/r/MoviesThatFeelLike/comments/1tynxim/great_english_language_films_for_this/', '/r/moviecritic/comments/1tynwrp/great_english_language_films_for_this/', 'MoviesThatFeelLike', 'A user seeking English-language film recommendations, though the context of ''this'' is unclear.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2599, '1typgna', 'What is a movie from your childhood that you still put on as background noise when you''re feeling stressed or sick?', 'Childhood comfort movie for background noise when stressed or sick', '[removed]', 'Bottom_Taxs', 1780771804, '/r/MoviesThatFeelLike/comments/1typgna/what_is_a_movie_from_your_childhood_that_you/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1typgna/what_is_a_movie_from_your_childhood_that_you/', 'MoviesThatFeelLike', 'A nostalgic, cozy invitation to share beloved childhood comfort watches used as soothing background noise during vulnerable moments.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2600, '1tyq3xz', 'Released my Short Film today!', '', '', 'lumdog05', 1780773305, '/r/MoviesThatFeelLike/comments/1tyq3xz/released_my_short_film_today/', 'https://youtu.be/d4ROy0MHoHQ?si=VrySGwsI50WqjBRA', 'MoviesThatFeelLike', 'Personal film release evoking enthusiasm and criticism in a casual community setting.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2601, '1tyq90z', 'Movies that feel like white trash absurdism', 'Movies that feel like white trash absurdism', '', 'smoothpaving', 1780773647, '/r/MoviesThatFeelLike/comments/1tyq90z/movies_that_feel_like_white_trash_absurdism/', 'https://www.reddit.com/gallery/1tyq90z', 'MoviesThatFeelLike', 'Absurd and gritty rural humor depicting white trash culture with a mix of comedy and discomfort.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2602, '1tyr10t', 'Movies that feel like misty woods', 'Movies that feel like misty woods', 'Missing people, unknown creatures, alone in the woods. Similar vibe to that one x-files episode about the human eating bugs', 'ExistentialDeception', 1780775499, '/r/MoviesThatFeelLike/comments/1tyr10t/movies_that_feel_like_misty_woods/', 'https://i.redd.it/zvmvn42uvp5h1.jpeg', 'MoviesThatFeelLike', 'Eerie isolation in dense, fog-choked forests where unknown creatures lurk and people vanish without a trace.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2603, '1tys47i', 'An unreal world where the creation of all things was born.', 'An unreal world where the creation of all things was born.', '', 'Cold-Bed498', 1780778130, '/r/MoviesThatFeelLike/comments/1tys47i/an_unreal_world_where_the_creation_of_all_things/', 'https://www.reddit.com/gallery/1tys47i', 'MoviesThatFeelLike', 'A mystical and epic atmosphere centered on the origins of existence.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2604, '1tysxg3', 'Movies set in the past were a European/American travels to distant countries and witnesses historical events', 'Movies set in the past where a European/American travels to distant countries and witnesses historical events', '', 'AssociationCorrect14', 1780780195, '/r/MoviesThatFeelLike/comments/1tysxg3/movies_set_in_the_past_were_a_europeanamerican/', 'https://www.reddit.com/gallery/1tysxg3', 'MoviesThatFeelLike', 'Seeking epic historical dramas featuring Western protagonists in distant lands during pivotal events.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2605, '1tytjfi', 'Like ....', '', '', 'Physics_hacker', 1780781743, '/r/MoviesThatFeelLike/comments/1tytjfi/like/', 'https://www.reddit.com/gallery/1tytjfi', 'MoviesThatFeelLike', 'Awe-inspiring futuristic cityscapes blending cyberpunk grit with techno-utopian grandeur.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2606, '1tytjoj', 'A visually stunning acid trip', 'A visually stunning acid trip', 'Looking for stunning visual and a story that is fantastical/magical realism. Like The Fall, tale of tales, the cell, big fish. ', 'Miserable_Profile692', 1780781761, '/r/MoviesThatFeelLike/comments/1tytjoj/a_visually_stunning_acid_trip/', 'https://www.reddit.com/gallery/1tytjoj', 'MoviesThatFeelLike', 'A quest for visually intoxicating, fantastical films that deliver the hallucinatory grandeur and surreal beauty of a psychedelic experience.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2607, '1tyv09v', 'Suggest a movie that is feel good, but offbeat and different from the usual formulaic Bollywood love stories.', 'Suggest a movie that is feel good, but offbeat and different from the usual formulaic Bollywood love stories.', 'I want to watch a movie worth spending time on and which can grab my attention.', 'youarethat4', 1780785534, '/r/MoviesThatFeelLike/comments/1tyv09v/suggest_a_movie_that_is_feel_good_but_offbeat_and/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tyv09v/suggest_a_movie_that_is_feel_good_but_offbeat_and/', 'MoviesThatFeelLike', 'A yearning for a distinctive and enjoyable film that breaks away from conventional romantic storylines.', 'skipped', 'no usable images', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2608, '1tyvgsx', 'Movies with this vibe', '', '[removed]', '[deleted]', 1780786768, '/r/MoviesThatFeelLike/comments/1tyvgsx/movies_with_this_vibe/', '', 'MoviesThatFeelLike', 'A request for movies that match an unspecified, atmospheric mood.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2609, '1tyvjv5', 'Movies that feel like this?', '', '', 'Affectionate_Log1743', 1780786984, '/r/MoviesThatFeelLike/comments/1tyvjv5/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1tyvjv5', 'MoviesThatFeelLike', 'A nostalgic yearning for visually striking, stylized cinema from the early 2000s, contrasted with frustration over AI-generated aesthetics.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2610, '1tyvl9o', 'Movies with this vibe', 'Movies with this vibe', '', 'Neat_Ostrich9966', 1780787092, '/r/MoviesThatFeelLike/comments/1tyvl9o/movies_with_this_vibe/', 'https://www.reddit.com/gallery/1tyvl9o', 'MoviesThatFeelLike', 'A dark, atmospheric, and surreal discussion centered on horror, existential dread, and supernatural elements.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2611, '1tywbgi', 'Movies That Feel Like Immortality: The Game', 'Movies That Feel Like Immortality The Game', 'Something about this game has haunted me, aesthetically. Specifically the segments focusing on the movie, "Ambrosio." The art style looks like something out of a medieval painting. Is there a real movie out there that captures this same type of vibe? Preferably something that''s also creepy. ', 'SchroedingersSphere', 1780789052, '/r/MoviesThatFeelLike/comments/1tywbgi/movies_that_feel_like_immortality_the_game/', 'https://www.reddit.com/gallery/1tywbgi', 'MoviesThatFeelLike', 'A haunting and creepy aesthetic reminiscent of medieval paintings.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2612, '1tywdwf', 'Movie that feel like..', '', '', 'Gotivnn', 1780789243, '/r/MoviesThatFeelLike/comments/1tywdwf/movie_that_feel_like/', 'https://www.reddit.com/gallery/1tywdwf', 'MoviesThatFeelLike', 'A gothic and eerie atmosphere with historical elegance and melancholic undertones.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2613, '1tyyj0p', 'Movies that feel like this', '', '', 'xaroanon', 1780795381, '/r/MoviesThatFeelLike/comments/1tyyj0p/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1tyyj0p', 'MoviesThatFeelLike', 'A gritty, industrial atmosphere with surreal and dystopian elements, evoking machinery and urban decay.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2614, '1tyzfoh', 'Movies that feel like this? (Grind fiction/Shibuya punk)', 'movies that feel like this? (grind fiction/shibuya punk)', '[deleted]', '[deleted]', 1780798051, '/r/MoviesThatFeelLike/comments/1tyzfoh/movies_that_feel_like_this_grind_fictionshibuya/', '', 'MoviesThatFeelLike', 'A gritty, rebellious urban atmosphere with elements of Shibuya punk and grindhouse fiction.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2615, '1tyzfq9', 'Movies that feel like this? (Grind fiction/Shibuya punk)', 'Movies that feel like Grind fiction / Shibuya punk', 'I almost always see this in any media that isn’t movies, Jet Set Radio, Splatoon, TWEWY, Persona, No More Heroes, those are games. FLCL is an anime, Scott Pilgrim is a comic, I need MORE of this urban feel with heavy emphasis on style, swag, and overall coolness while fighting a general higher power ', 'FaZe_poopy', 1780798055, '/r/MoviesThatFeelLike/comments/1tyzfq9/movies_that_feel_like_this_grind_fictionshibuya/', 'https://www.reddit.com/gallery/1tyzfq9', 'MoviesThatFeelLike', 'A craving for rebellious, hyper-stylized urban anti-authority media drenched in street culture, graffiti aesthetics, and punk energy.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2616, '1tyzmhm', 'Movies that feel like this?', 'Movies that feel like this?', '', 'philosareantichrist', 1780798610, '/r/MoviesThatFeelLike/comments/1tyzmhm/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1tyzmhm', 'MoviesThatFeelLike', 'Campy, satirical, and absurdist religious imagery blending the sacred with the profane in a fever-dream aesthetic.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2617, '1tz0hkk', 'Movies that feel like this', 'Movies that feel like this', '', 'xaroanon', 1780801199, '/r/MoviesThatFeelLike/comments/1tz0hkk/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1tz0hkk', 'MoviesThatFeelLike', 'A vague request for movies evoking an unspecified atmospheric feeling.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2618, '1tz0mnv', 'Movies that feel like this', '', '', 'xaroanon', 1780801591, '/r/MoviesThatFeelLike/comments/1tz0mnv/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1tz0mnv', 'MoviesThatFeelLike', 'A nostalgic quest for films that capture retro-futuristic scientific aesthetics and mid-century innovation.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2619, '1tz1ebq', 'Movies with this vibe.', 'Movies with this vibe.', '', 'BlueSM-012', 1780803853, '/r/MoviesThatFeelLike/comments/1tz1ebq/movies_with_this_vibe/', 'https://www.reddit.com/gallery/1tz1ebq', 'MoviesThatFeelLike', 'A somber, haunting atmosphere with war themes and beautiful, melancholic skies.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2620, '1tz1suu', 'Like rdr2', 'Like Red Dead Redemption 2', '', 'Sm0kythebandit', 1780805077, '/r/MoviesThatFeelLike/comments/1tz1suu/like_rdr2/', 'https://www.reddit.com/gallery/1tz1suu', 'MoviesThatFeelLike', 'A community of fans seeking that same atmospheric, sweeping western frontier feeling of Red Dead Redemption 2 through classic and modern western films.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2621, '1tz2zhl', 'Movies with this aesthetic', '', '', 'Proof_Caregiver_4234', 1780808808, '/r/MoviesThatFeelLike/comments/1tz2zhl/movies_with_this_aesthetic/', 'https://www.reddit.com/gallery/1tz2zhl', 'MoviesThatFeelLike', 'Neon-soaked cyberpunk world with a moody, introspective dystopian feel.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2622, '1tz4m05', 'Recommendations for movies to relax/fall asleep to', 'Recommendations for movies to relax/fall asleep to', '', 'Cryptlofi', 1780814243, '/r/MoviesThatFeelLike/comments/1tz4m05/recommendations_for_movies_to_relaxfall_asleep_to/', '/r/movies/comments/1tz4l7g/recommendations_for_movies_to_relaxfall_asleep_to/', 'MoviesThatFeelLike', 'Seeking slow, dreamy, and comforting films that are soothing enough to drift off to sleep.', 'skipped', 'no usable images', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2623, '1tz4nhm', 'Rural set horror films that feel like this:', 'Rural set horror films that feel like this', '', 'throwing-stones-', 1780814380, '/r/MoviesThatFeelLike/comments/1tz4nhm/rural_set_horror_films_that_feel_like_this/', 'https://www.reddit.com/gallery/1tz4nhm', 'MoviesThatFeelLike', 'Seeking rural horror films with a specific unsettling, atmospheric, and isolated feeling.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2624, '1tz5023', 'Narrated Movies', '', 'I love narrated movies, but cannot recall many, and would love recommendations. 

For instance, my favorite movie is Apocalypse Now, mostly because of Martin Sheen’s narrating. Another example is Stranger than Fiction. I also like how the Grand Budapest is a man sharing his experience with someone else, though his narration is limited.. 

But what other movies go heavy on narration?', 'lemmeatem6969', 1780815583, '/r/MoviesThatFeelLike/comments/1tz5023/narrated_movies/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tz5023/narrated_movies/', 'MoviesThatFeelLike', 'A nostalgic and enthusiastic discussion about narrated films, evoking a love for storytelling through voice-over and first-person perspectives.', 'skipped', 'no usable images', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2625, '1tz5pvy', 'An unreal world populated by divine entities.', 'An unreal world populated by divine entities.', '', 'Cold-Bed498', 1780818123, '/r/MoviesThatFeelLike/comments/1tz5pvy/an_unreal_world_populated_by_divine_entities/', 'https://www.reddit.com/gallery/1tz5pvy', 'MoviesThatFeelLike', 'Awe-struck encounter with towering, alien divinities in a luminous, unsettling cosmos where beauty and cosmic dread coexist.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2626, '1u01ivl', 'movies that feel like this', 'movies that feel like this', 'movies that feels like a melancholic young girl / girlhood wearing cotton, linen, and lace dresses wandering through the airy morning

movies ive already watched: the virgin suicides (1999), picnic at the hanging rock (1975), 3 women (1977), mustang (2015), white oleander (2002), and valerie and her week of wonders (1970)', 'aihyelle', 1780905898, '/r/MoviesThatFeelLike/comments/1u01ivl/movies_that_feel_like_this/', 'https://i.redd.it/j85lf6ekn06h1.jpeg', 'MoviesThatFeelLike', 'A dreamy, melancholic haze of girlhood innocence — airy mornings, soft fabrics, and the quiet weight of being young and adrift in a sunlit, ethereal world.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2627, '1u1vgek', 'Looking for obscure, old (1930s-early 60s) that have the same vibe as this', '', '', 'ingridnightshade', 1781077391, '/r/MoviesThatFeelLike/comments/1u1vgek/looking_for_obscure_old_1930searly_60s_that_have/', 'https://www.reddit.com/gallery/1u1vgek', 'MoviesThatFeelLike', 'A quest for eerie, obscure old horror films with unsettling visuals.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2628, '1vw2ywo', 'Movies that feel like this', '', 'Hi  
I’m looking for some movies filmed in locations like Iceland, the Faroe Islands, Scandinavia... The genre isn’t that important to me, what’s more important is this kind of location and atmosphere', 'lotringer', 1787478588, '/r/MoviesThatFeelLike/comments/1vw2ywo/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vw2ywo', 'MoviesThatFeelLike', 'A moody, atmospheric feel of cold, remote northern landscapes with a sense of isolation and beauty.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2629, '1vxjzsu', 'Movies that feel like this?', 'Movies that feel like this', '', 'SmartBaeby', 1787616296, '/r/MoviesThatFeelLike/comments/1vxjzsu/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vxjzsu', 'MoviesThatFeelLike', 'Dark, religious atmosphere with sacred architecture and gothic horror undertones, evoking tension between faith and menace.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2630, '1vxk60x', 'Movies that feel like this', 'Movies that feel like this', '', 'X-_Grimrian_-X', 1787616737, '/r/MoviesThatFeelLike/comments/1vxk60x/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vxk60x', 'MoviesThatFeelLike', 'Nostalgic suburban childhood with a cozy, retro tech feel.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2631, '1vxkk8e', 'Any movie that feels like those four together?', 'Any movie that feels like those four together?', '', 'Difficult-Second3315', 1787617745, '/r/MoviesThatFeelLike/comments/1vxkk8e/any_movie_that_feels_like_those_four_together/', 'https://www.reddit.com/gallery/1vxkk8e', 'MoviesThatFeelLike', 'A humorous and eclectic mix of sci-fi and cult film recommendations, embodying a chaotic and unhinged search for cinematic vibes.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2632, '1vxkqyc', 'Movies that mirror this vibe', 'Movies that mirror this vibe', '', 'SnailCooper_', 1787618231, '/r/MoviesThatFeelLike/comments/1vxkqyc/movies_that_mirror_this_vibe/', 'https://www.reddit.com/gallery/1vxkqyc', 'MoviesThatFeelLike', 'Surreal, melancholic, and deeply atmospheric — a dreamlike unease mixing beauty with dread, evoking lonely figures in luminous, painterly landscapes.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2633, '1vxl762', 'Looking for some movies to get into the spooky time vibes. Doesn''t necessarily have to be a horror movie. (Dark Crystal, labyrinth, Coraline)', 'Looking for some movies to get into the spooky time vibes. Doesn''t necessarily have to be a horror movie. (Dark Crystal, labyrinth, Coraline)', 'Honestly I''m not exactly sure how to describe the vibe I''m looking for. I know about horror movies obviously, and those are welcome, but I''m more looking for a different vibe at the moment. Movies that aren''t necessarily meant to be horror movies but more maybe Halloween time movies or unsettling movies or even fever dream movies. I have a few examples below but I can''t quite put my finger on what I would call the vibe other than spooky season or October vibe Halloween vibe whatever. 

And as stated above they don''t even have to be horror movies or scary at all. They could just have a weird Halloween spooky vibe about them like that one episode of the claymation Mark Twain show where they ran into Satan who was just like a mask and it kind of had like a spooky vibe to it but it wasn''t necessarily scary but it was unsettling and kind of a fever dream. Same way with return to Oz. It''s not scary, but it has some elements to it that are maybe slightly off putting or just have a fever dream vibe to it. Honestly the way I describe it is like movies that a kid would like that wears orange and black stripes sweaters and scarves and maybe has black dyed hair. Not necessarily goth because I think they had more into the metal hard Rock blood and gore guts stuff, but more so weird kid that like to listen to scary stories and creepy pastas and plays weird fever dream indie games. Someone who just likes the entire vibe of autumn and Halloween. Maybe something that even feels like a creepypasta.

Also a huge plus if there are practical effects, puppets, or stop motion. Also just fever dream movies that make you feel like you''re going crazy or they don''t quite make sense. Those are usually at least a little scary like the shining or Jacob''s ladder. 

Without further Ado here are some examples I''m sure some of them will be obvious, but I''m more looking for ones that I may have forgotten or never looked into. Return to Oz was one that I had never even thought of but it does kind of have a little bit of that quality in it here and there. 

\\\* That one Mark Twain adventures episode that had Satan in it. Very much kind of the vibe I would love 

\\\* Return to Oz kind of has it with some of the creatures in the mountain faces and stuff. 

\\\* I would definitely say neverending story has some of that in it. 

\\\* Dark Crystal fits the vibe too. One of my favorite movies of all time. 

\\\* One of the obvious ones, nightmare before Christmas. 

\\\* Another obvious one, but one of my favorites, Coraline. 

\\\* Corpse Bride works as well, but it''s a bit too light-hearted and comedic for me. Still good though. 

\\\* I think I would put labyrinth in there. Another favorite of mine. 

\\\* Edward scissorhands again a little bit comedic but it fits 

\\\* Beetlejuice fits, but again a bit comedic. But I really love the claymation scenes.

\\\* Same way with the Addams family. Movie or show. I like the vibe of it, but a bit too comedic. 

\\\* See about the reason for wednesday. I kind of torn about that one. It''s like half of the things featured in the show I really liked and then half I hate. 

\\\* Stranger things fits for sure. 

\\\* Pans labyrinth for sure

\\\* Sleepy hollow is another great one.

I''m sure there are a ton that have never heard of or even just that I forgot to put. Still not sure how to describe the vibe or what to call it, but I definitely encourage anyone who knows what I''m talking about to recommend anything and everything that they can think of.', 'Captain_Fach', 1787619425, '/r/MoviesThatFeelLike/comments/1vxl762/looking_for_some_movies_to_get_into_the_spooky/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vxl762/looking_for_some_movies_to_get_into_the_spooky/', 'MoviesThatFeelLike', 'A cozy autumnal craving for fever-dream, off-kilter, and eerily whimsical films that unsettle without necessarily frightening — the dark enchantment of stop-motion gothic fairy tales and surreal imagery.', 'skipped', 'no usable images', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2634, '1vxmpxm', 'Movies that feel like an Old Rich Man struggling with aging and some sketchy business', 'Movies that feel like an Old Rich Man struggling with aging and some sketchy business', '', 'Pretty-Girl3875', 1787623477, '/r/MoviesThatFeelLike/comments/1vxmpxm/movies_that_feel_like_an_old_rich_man_struggling/', 'https://www.reddit.com/gallery/1vxmpxm', 'MoviesThatFeelLike', 'A mood of decaying wealth, moral compromise, and the unsettling tension between privilege and personal ruin.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2635, '1vxorxi', '60s-70s Southwestern/West Coast Americana', '60s-70s Southwestern West Coast Americana', 'I was wondering if anyone knew of any films with a vintage Americana visual style. I have seen a handful of films with this vibe (ex: Paris, Texas , Thelma and Louise , Alice Doesn’t Live Here Anymore , etc) but I wanted to know if anyone had some recommendations that I haven’t seen or haven’t heard of. ', 'cosmocamp', 1787629282, '/r/MoviesThatFeelLike/comments/1vxorxi/60s70s_southwesternwest_coast_americana/', 'https://www.reddit.com/gallery/1vxorxi', 'MoviesThatFeelLike', 'A nostalgic search for films capturing the rugged, vintage Americana visual style of the 1960s and 1970s, focusing on Southwestern and West Coast settings.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2636, '1vxp5re', 'Movies that feel like a pure adrenaline', 'Movies that feel like a pure adrenaline', '', 'Infinite-Pleasure255', 1787630441, '/r/MoviesThatFeelLike/comments/1vxp5re/movies_that_feel_like_a_pure_adrenaline/', 'https://www.reddit.com/gallery/1vxp5re', 'MoviesThatFeelLike', 'Relentless, high-octane action where the heart never stops pounding and the pace never lets up.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2637, '1vxpx48', 'Movies that give me the highbrow, artsy feeling of Call Me By Your Name / Miroirs 3 Un barque sur l''ocean?', 'Movies that give me the highbrow artsy feeling of Call Me By Your Name', 'Yea I know Armie Hammer is... well Armie Hammer now, and this is my first post in this sub but I was listening to Maurice Ravel''s Miroirs 3: Un barque sur l''ocean and I''m almost *certain* that song comes up in Call me by your name, or at least in the marketing. I was taken aback by how much the song struck me; suddenly I was seeing visions of Europe, the ocean, the Italian hills, everything, and of all that artsy highbrow stuff that I don''t get too much of. 

I realized that I spend my time watching franchise slop (not that there''s anything inherently wrong with that though) and playing old nostalgia videogames yet I don''t interest my brain in anything new or intellectually stimulating media or films - as much as a film can be intellectually stimulating lol.

Me and some other people loved this film years ago but I wanna catch up on the essential, brainy and cerebral films that people love and glaze and hold dear to this day. The only other one I can think of is Triangle of Sadness, which I love but is more of a dark comedy satire, whereas CMBYN takes itself and the story much more seriously. 

Are there any examples of what I''m looking for? Thanks in advance !', 'tecrush', 1787632835, '/r/MoviesThatFeelLike/comments/1vxpx48/movies_that_give_me_the_highbrow_artsy_feeling_of/', 'https://www.reddit.com/gallery/1vxpx48', 'MoviesThatFeelLike', 'A contemplative yearning for sophisticated, European-inspired artsy cinema that stimulates the intellect.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2638, '1vxq0oq', 'What movies feel like reality is slowly becoming “wrong” without anyone else noticing?', 'What movies feel like reality is slowly becoming “wrong” without anyone else noticing?', '', 'Ancient_Win_2837', 1787633154, '/r/MoviesThatFeelLike/comments/1vxq0oq/what_movies_feel_like_reality_is_slowly_becoming/', 'https://i.redd.it/xc1txcy5bglh1.jpeg', 'MoviesThatFeelLike', 'An atmosphere of creeping paranoia and unsettling distortion, where ordinary reality slowly reveals itself to be deeply wrong.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2639, '1vxq5ic', 'Movies that give me the same highbrow, artsy feeling as Call Me By Your Name / Miroirs 3: Un baraue sur l''ocean?', 'Movies that give me the same highbrow, artsy feeling as Call Me By Your Name', 'Yea I know Armie Hammer is... well Armie Hammer now, and this is my first post in this sub but I  
was listening to Maurice Ravel''s Miroirs 3: Un barque sur l''ocean and I''m almost certain that  
song comes up in Call me by your name, or at least in the marketing. I was taken aback by how  
much the song struck me; suddenly I was seeing visions of Europe, the ocean, the Italian hills,  
everything, and of all that artsy highbrow stuff that I don''t get too much of.

I realized that I spend my time watching franchise slop (not that there''s anything inherently  
wrong with that though) and playing old nostalgia videogames yet I don''t interest my brain in  
anything new or intellectually stimulating media or films.

Me and some other people loved this film years ago but I wanna catch up on the essential, brainy and cerebral films that people love and glaze and hold dear to this day, and with good reason! The only other one I can think of is Triangle of Sadness, which I love but is more of a dark comedy satire,  
whereas CMBYN takes itself and the story much more seriously imo.

Are there any examples of what I''m looking for? Thanks in advance !', 'tecrush', 1787633590, '/r/MoviesThatFeelLike/comments/1vxq5ic/movies_that_give_me_the_same_highbrow_artsy/', 'https://www.reddit.com/gallery/1vxq5ic', 'MoviesThatFeelLike', 'A yearning for intellectually stimulating and aesthetically rich films with classical music and European sensibilities.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2640, '1vxtsc6', 'Movies with monstrous women', 'Movies with monstrous women', '', 'TravelDelicious8934', 1787646119, '/r/MoviesThatFeelLike/comments/1vxtsc6/movies_with_monstrous_women/', 'https://www.reddit.com/gallery/1vxtsc6', 'MoviesThatFeelLike', 'A rowdy, playful horror community thread brimming with enthusiasm for monstrous women across genres—from slasher to art-house—with a mix of genuine recs and cheeky jokes.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2641, '1vxtz0m', 'This scene from "The Elephant Man"', 'This scene from The Elephant Man', 'Nothing heals like kind words.

What a movie by David lynch.', 'Disco-Zero', 1787646814, '/r/MoviesThatFeelLike/comments/1vxtz0m/this_scene_from_the_elephant_man/', 'https://v.redd.it/hqwp0s3sfhlh1', 'MoviesThatFeelLike', 'A heartfelt discussion about healing through kindness, inspired by a touching scene from David Lynch''s ''The Elephant Man''.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2642, '1vxukh7', 'You are the only sane person', 'You are the only sane person', 'Trapped, suffocating ', 'Lindy_dy', 1787648950, '/r/MoviesThatFeelLike/comments/1vxukh7/you_are_the_only_sane_person/', 'https://www.reddit.com/gallery/1vxukh7', 'MoviesThatFeelLike', 'A suffocating sense of paranoia and isolation where the protagonist feels like the only rational person in an insane world.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2643, '1vxv0un', 'movies that feel like this?', '', '', 'Few-Advertising-5164', 1787650533, '/r/MoviesThatFeelLike/comments/1vxv0un/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vxv0un', 'MoviesThatFeelLike', 'Clinical, unsettling atmosphere with medical horror and psychological unease.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2644, '1vxv8ao', 'Movies or shows that feel like Prime Drake era/aesthetic', 'Movies or shows that feel like Prime Drake era/aesthetic', '', 'Magikarpcopiesdunkey', 1787651269, '/r/MoviesThatFeelLike/comments/1vxv8ao/movies_or_shows_that_feel_like_prime_drake/', 'https://www.reddit.com/gallery/1vxv8ao', 'MoviesThatFeelLike', 'Seeking mid-2000s urban dramatic cinema with that slick, moody, slightly edgy Drake aesthetic — a mix of action, thriller, and hip-hop-era cool.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2645, '1vxvwbs', 'Movies that feel like your entering mid twenties, don’t have it all together but are slowly getting there', 'Movies that feel like you''re entering mid twenties, don''t have it all together but are slowly getting there', '', 'givemespaceplease', 1787653532, '/r/MoviesThatFeelLike/comments/1vxvwbs/movies_that_feel_like_your_entering_mid_twenties/', 'https://i.redd.it/gxexstarzhlh1.jpeg', 'MoviesThatFeelLike', 'A nostalgic, slightly uncertain feeling of navigating early adulthood — figuring yourself out while everyone else seems to have it handled.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2646, '1vxxffr', 'Shows that feel like a medieval peasant woman living a romance with a warrior', 'Shows that feel like a medieval peasant woman living a romance with a warrior', 'Non-related but have seen: Outlander, My Lady Jane, Poldark, Bridgerton, The Spanish Princess

I''d like if the FL was also a warrior in some way  
It can be spicy  
Not the best images but will work', 'Maleficent_Pen_940', 1787658160, '/r/MoviesThatFeelLike/comments/1vxxffr/shows_that_feel_like_a_medieval_peasant_woman/', 'https://www.reddit.com/gallery/1vxxffr', 'MoviesThatFeelLike', 'A longing for romantic medieval narratives centered on peasant women and warrior romances.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2647, '1vxyuby', 'Movies that feel like confessing your guilt, especially for something you did to a past lover', 'Movies that feel like confessing your guilt, especially for something you did to a past lover', 'like *Paris, Texas*, maybe? or *Anatomy of a Fall*, where there’s literally a trial?', 'Agreeable-Gain-1552', 1787661935, '/r/MoviesThatFeelLike/comments/1vxyuby/movies_that_feel_like_confessing_your_guilt/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vxyuby/movies_that_feel_like_confessing_your_guilt/', 'MoviesThatFeelLike', 'A confessional and remorseful atmosphere centered on guilt and atonement towards past lovers.', 'skipped', 'no usable images', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2648, '1vy0t95', 'Mtfl Mexico in the 90s', 'Mexico in the 90s', '', 'Blabsalot', 1787666695, '/r/MoviesThatFeelLike/comments/1vy0t95/mtfl_mexico_in_the_90s/', 'https://www.reddit.com/gallery/1vy0t95', 'MoviesThatFeelLike', 'Nostalgic longing for the cinematic atmosphere of 1990s Mexico.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2649, '1vy2ltr', 'Movies about riding but NOT about racing', '', 'Astonished how few movies there are about riding motorcycles that arent racing-centered', 'Slice_lice', 1787670773, '/r/MoviesThatFeelLike/comments/1vy2ltr/movies_about_riding_but_not_about_racing/', 'https://www.reddit.com/gallery/1vy2ltr', 'MoviesThatFeelLike', 'A nostalgic and adventurous quest for motorcycle films that celebrate the ride over the race, with a touch of counter-cultural spirit.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2650, '1vy4jxx', 'Movies that feel like Jamel Campbell''s 2025 Zatanna run?', 'Movies like Jamel Campbell''s 2025 Zatanna run', '', 'Supersmashbrosfan', 1787674987, '/r/MoviesThatFeelLike/comments/1vy4jxx/movies_that_feel_like_jamel_campbells_2025/', 'https://www.reddit.com/gallery/1vy4jxx', 'MoviesThatFeelLike', 'Magical, fantastical quest for cinema matching a comic book run.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2651, '1vy4o6c', 'Movies that feel like Jamel Campbell''s 2025 Zatanna run?', 'Movies that feel like Jamel Campbell''s 2025 Zatanna run?', '', 'Supersmashbrosfan', 1787675239, '/r/MoviesThatFeelLike/comments/1vy4o6c/movies_that_feel_like_jamel_campbells_2025/', 'https://www.reddit.com/gallery/1vy4o6c', 'MoviesThatFeelLike', 'A request for films matching the magical, theatrical, and character-driven style of a specific comic book run.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2652, '1vy54tq', 'Red State tribute poster by Koblovtattoo. I recommend this one :)', '', '', 'koblovtattoo', 1787676255, '/r/MoviesThatFeelLike/comments/1vy54tq/red_state_tribute_poster_by_koblovtattoo_i/', 'https://i.redd.it/5y5ykujxjjlh1.jpeg', 'MoviesThatFeelLike', 'Enthusiastic recommendation of a specific movie''s fan art.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2653, '1vy58f9', 'Movies that feel dreamy, haunting, heart wrenching, leave you empty, female friendship, destructive, mental illness', '', 'TIA! ', 'wickedlittle____', 1787676467, '/r/MoviesThatFeelLike/comments/1vy58f9/movies_that_feel_dreamy_haunting_heart_wrenching/', 'https://www.reddit.com/gallery/1vy58f9', 'MoviesThatFeelLike', 'The post seeks films that evoke a dreamy, haunting, and emotionally heavy atmosphere, often centered on female friendships and mental illness, leaving the viewer with a sense of emptiness and destruction.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2654, '1vy59gw', 'dark mystical and feminine', 'Dark, Mystical, and Feminine', 'looking for films that are dark, mystical, and feminine centring women of colour ', 'ZestycloseEconomy858', 1787676529, '/r/MoviesThatFeelLike/comments/1vy59gw/dark_mystical_and_feminine/', 'https://www.reddit.com/gallery/1vy59gw', 'MoviesThatFeelLike', 'Dark, mystical, and feminine atmosphere centered on women of colour.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2655, '1vy5puf', 'I need 80s-90s lesser known movies Sci fi/action/adventure/fantasy all accepted that I haven’t seen', '80s-90s lesser known sci-fi/action/adventure/fantasy movies', '', 'Bitter-Pattern-573', 1787677481, '/r/MoviesThatFeelLike/comments/1vy5puf/i_need_80s90s_lesser_known_movies_sci/', '/r/MovieSuggestions/comments/1vy5p9h/i_need_80s90s_lesser_known_movies_sci/', 'MoviesThatFeelLike', 'A nostalgic search for hidden cinematic gems from the 80s and 90s in sci-fi, action, adventure, and fantasy genres.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2656, '1vy780b', 'What’s the best movie to watch after a breakup?', 'What’s the best movie to watch after a breakup?', '', 'Secret-Win1999', 1787680690, '/r/MoviesThatFeelLike/comments/1vy780b/whats_the_best_movie_to_watch_after_a_breakup/', 'https://i.redd.it/m8o5acpuijlh1.jpeg', 'MoviesThatFeelLike', 'Cathartic and supportive movie suggestions for navigating post-breakup emotions.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2657, '1vy9g98', 'Movies with this type of vibe/aesthetic', 'Movies with this type of vibe/aesthetic', '', 'Sea-Conclusion959', 1787685334, '/r/MoviesThatFeelLike/comments/1vy9g98/movies_with_this_type_of_vibeaesthetic/', 'https://i.redd.it/jpwxkxmbmklh1.jpeg', 'MoviesThatFeelLike', 'A yearning for rustic, historical Americana and period dramas set in rural, expansive landscapes with melancholic undertones.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2658, '1vya28w', 'Movies that feel like I’ve been living in a box, then I befriended a rich person and have discovered a whole new world?', 'Movies that feel like I’ve been living in a box, then I befriended a rich person and have discovered a whole new world?', '', 'Hot_Composer_9351', 1787686624, '/r/MoviesThatFeelLike/comments/1vya28w/movies_that_feel_like_ive_been_living_in_a_box/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vya28w/movies_that_feel_like_ive_been_living_in_a_box/', 'MoviesThatFeelLike', 'A transformative experience of discovering luxury and new social horizons through unexpected connections.', 'skipped', 'no usable images', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2659, '1vybydv', 'What’s a movie you went into with zero expectations and came out obsessed with?', '', 'I swear some of the best movies are the ones you watch with absolutely **no expectations**.

No trailer. No hype. No Rotten Tomatoes score. Just randomly watching it because you’re bored… and 2 hours later you’re sitting there like:

**“Why did nobody tell me about this?”** 😭

For me, the underrated part is when a movie actually stays in your head for days after watching it.

What’s that one movie for you?

**No obvious blockbuster answers — give me the movie that genuinely surprised you.** 👀', 'Parking-Attitude-971', 1787690626, '/r/MoviesThatFeelLike/comments/1vybydv/whats_a_movie_you_went_into_with_zero/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vybydv/whats_a_movie_you_went_into_with_zero/', 'MoviesThatFeelLike', 'Serendipitous discovery of hidden cinematic gems that linger in the mind, celebrating unexpected obsessions without hype.', 'skipped', 'no usable images', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2660, '1vydpna', 'Recommend me any movie that fits the description', 'Recommend me any movie that fits the description', '', 'Disco-Zero', 1787694550, '/r/MoviesThatFeelLike/comments/1vydpna/recommend_me_any_movie_that_fits_the_description/', 'https://i.redd.it/ysb3v17h7llh1.jpeg', 'MoviesThatFeelLike', 'A straightforward request for movie recommendations.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2661, '1vye2aa', 'Movies that feel like this', 'Movies that feel like this', 'Cossie was legendary in 80s/90s Britain for being a stolen getaway car, but are there british crime films that feature Ford Sierra Cosworth used for this purpose?', 'peerkons1985', 1787695383, '/r/MoviesThatFeelLike/comments/1vye2aa/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vye2aa', 'MoviesThatFeelLike', 'Craving gritty British crime films with high-speed getaway car chases featuring iconic vehicles of the era.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2662, '1vyfrmo', 'Movies that feel like hidden underwater sea life', 'Movies that feel like hidden underwater sea life', '', 'NegotiationMean3042', 1787699531, '/r/MoviesThatFeelLike/comments/1vyfrmo/movies_that_feel_like_hidden_underwater_sea_life/', 'https://www.reddit.com/gallery/1vyfrmo', 'MoviesThatFeelLike', 'A mysterious and aquatic vibe evoking hidden underwater realms and sea life.', 'publishable', NULL, NULL, '2026-08-26 01:43:46', '2026-08-26 01:43:46');
