-- 0166_seed_20260828T091438Z_01_posts.sql: data seed from pipeline:load run.
-- Generated:  2026-08-28T09:15:02.194680+00:00
-- Run started: 2026-08-28T09:14:38.744584+00:00
-- Source: data/working/load manifest from this run.
--
-- Idempotent: every INSERT is INSERT OR IGNORE, keyed by the
-- table's natural unique constraint.  Wrangler's migration
-- tracking normally prevents re-apply; the OR IGNORE is
-- defense in depth for partial / interrupted re-runs.
--
-- Chunk: 01_posts (1/5)
-- Tables: imported_vibe_posts.
-- Pipeline-state tables (processing_runs, pipeline_artifacts)
-- are intentionally excluded — they're per-run bookkeeping.

INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2760, '1tu96ke', 'Any emo clown musicals?', 'Any emo clown musicals?', 'Sorry for the weird title but it really is what im looking for. Im interested in anything with clown elements, circus or carnival elements, alternative fashion, strange and whimsical characters and almost no real plot. Im thinking the rocky horror picture show, repo: the genetic opera, forbiden zone, the devil''s carnival, and killer klowns from outer space! (And, if you couldnt tell, i like musicals.)', 'obsidian_nightmare6', 1780355532, '/r/MoviesThatFeelLike/comments/1tu96ke/any_emo_clown_musicals/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tu96ke/any_emo_clown_musicals/', 'MoviesThatFeelLike', 'Seeking darkly whimsical, carnival-themed musicals with clown elements and alternative aesthetics.', 'skipped', 'no usable images', NULL, '2026-08-28 09:15:01', '2026-08-28 09:15:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2761, '1tuarrj', 'I’m looking for films that evoke a quiet, pervasive sense of wrongness—like Cure or Chime by Kiyoshi Kurosawa. Not necessarily horror, but deeply unsettling, eerie, and psychologically disturbing.', '', '', '-marebito-', 1780359531, '/r/MoviesThatFeelLike/comments/1tuarrj/im_looking_for_films_that_evoke_a_quiet_pervasive/', 'https://i.redd.it/15vu6zzxir4h1.jpeg', 'MoviesThatFeelLike', 'A deeply unsettling and psychologically eerie atmosphere with a quiet sense of pervasive wrongness.', 'publishable', NULL, NULL, '2026-08-28 09:15:01', '2026-08-28 09:15:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2762, '1tub6j9', 'Movies with multiple interpretations/intricate details', 'Movies with multiple interpretations and intricate details', 'Pictured films: The Shining, Beau is Afraid, Backrooms (2026), Get Out', 'MaskGas44', 1780360603, '/r/MoviesThatFeelLike/comments/1tub6j9/movies_with_multiple_interpretationsintricate/', 'https://www.reddit.com/gallery/1tub6j9', 'MoviesThatFeelLike', 'A cerebral, puzzle-box craving atmosphere where viewers seek layered narratives that unravel differently with each viewing.', 'publishable', NULL, NULL, '2026-08-28 09:15:01', '2026-08-28 09:15:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2763, '1tuczo5', 'Hawaii, 1940s and shortly after.', 'Hawaii, 1940s and shortly after', '', 'Spare-Department-765', 1780365397, '/r/MoviesThatFeelLike/comments/1tuczo5/hawaii_1940s_and_shortly_after/', 'https://www.reddit.com/gallery/1tuczo5', 'MoviesThatFeelLike', 'A nostalgic historical wartime atmosphere evoking 1940s Hawaii and the era following Pearl Harbor.', 'publishable', NULL, NULL, '2026-08-28 09:15:01', '2026-08-28 09:15:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2764, '1tuf2jk', 'Movies with characters that have this vibes.', 'Movies with characters that have this vibes.', '', 'BlueSM-012', 1780371107, '/r/MoviesThatFeelLike/comments/1tuf2jk/movies_with_characters_that_have_this_vibes/', 'https://www.reddit.com/gallery/1tuf2jk', 'MoviesThatFeelLike', 'A gritty, dystopian atmosphere with heavily armed, rebellious characters in chaotic, post-apocalyptic settings.', 'publishable', NULL, NULL, '2026-08-28 09:15:01', '2026-08-28 09:15:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2765, '1tufu0h', 'movies that feel like queer toric relationships', 'movies that feel like queer toric relationships', '', 'ScientificPianist', 1780373299, '/r/MoviesThatFeelLike/comments/1tufu0h/movies_that_feel_like_queer_toric_relationships/', 'https://www.reddit.com/gallery/1tufu0h', 'MoviesThatFeelLike', 'A community discusses and recommends movies that resonate with queer toric relationships, sharing titles that explore gender and sexuality.', 'publishable', NULL, NULL, '2026-08-28 09:15:01', '2026-08-28 09:15:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2766, '1tugsnu', 'What’s a movie or TV show that perfectly captures the vibe of a specific decade without being a period piece?', 'What’s a movie or TV show that perfectly captures the vibe of a specific decade without being a period piece?', '', 'Low_Moose_2765', 1780376157, '/r/MoviesThatFeelLike/comments/1tugsnu/whats_a_movie_or_tv_show_that_perfectly_captures/', '/r/NoStupidQuestions/comments/1tuglie/whats_a_movie_or_tv_show_that_perfectly_captures/', 'MoviesThatFeelLike', 'A nostalgic query seeking media that encapsulates the atmosphere of specific decades without literal period settings.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-28 09:15:01', '2026-08-28 09:15:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2767, '1tuguh0', 'What’s a movie that perfectly captures the vibe of a specific decade without being a period piece and why ?', 'Movies that capture the vibe of a specific decade', '', 'Low_Moose_2765', 1780376316, '/r/MoviesThatFeelLike/comments/1tuguh0/whats_a_movie_that_perfectly_captures_the_vibe_of/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tuguh0/whats_a_movie_that_perfectly_captures_the_vibe_of/', 'MoviesThatFeelLike', 'A nostalgic discussion reflecting on movies that authentically capture the cultural essence of past decades.', 'skipped', 'no usable images', NULL, '2026-08-28 09:15:01', '2026-08-28 09:15:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2768, '1tukvot', 'Horror movies set in a haunted asylum', 'Horror movies set in a haunted asylum', '', 'CollarOrdinary4284', 1780389547, '/r/MoviesThatFeelLike/comments/1tukvot/horror_movies_set_in_a_haunted_asylum/', 'https://www.reddit.com/gallery/1tukvot', 'MoviesThatFeelLike', 'Eerie and suspenseful, focused on haunted asylum horrors.', 'publishable', NULL, NULL, '2026-08-28 09:15:01', '2026-08-28 09:15:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2769, '1tulcxg', 'kindly suggest movies', 'kindly suggest movies', '', 'qasiw', 1780391167, '/r/MoviesThatFeelLike/comments/1tulcxg/kindly_suggest_movies/', 'https://www.reddit.com/gallery/1tulcxg', 'MoviesThatFeelLike', 'Fierce female rage and revenge — women fighting back against injustice with cathartic, violent, unapologetic energy.', 'publishable', NULL, NULL, '2026-08-28 09:15:01', '2026-08-28 09:15:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2770, '1tumuip', 'Movie that feels like this', '', 'Or shows', 'WerewolfWild1323', 1780396016, '/r/MoviesThatFeelLike/comments/1tumuip/movie_that_feels_like_this/', 'https://www.reddit.com/gallery/1tumuip', 'MoviesThatFeelLike', 'Nostalgic and sentimental coming-of-age vibe with a focus on female friendships and summer memories.', 'publishable', NULL, NULL, '2026-08-28 09:15:01', '2026-08-28 09:15:01');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2771, '1tupxpd', 'Movies or shows that feel other worldly', 'Movies or shows that feel otherworldly', 'Subbed/Dubbed is totally fine ', 'NoShow95', 1780404465, '/r/MoviesThatFeelLike/comments/1tupxpd/movies_or_shows_that_feel_other_worldly/', 'https://www.reddit.com/gallery/1tupxpd', 'MoviesThatFeelLike', 'A curiosity-driven search for content that transcends the ordinary — seeking alien landscapes, surreal worlds, and stories that feel like they come from somewhere beyond human reality.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2772, '1tus5nn', 'Long and awkward interactions', '', '', 'Male-2003', 1780409502, '/r/MoviesThatFeelLike/comments/1tus5nn/long_and_awkward_interactions/', 'https://www.reddit.com/gallery/1tus5nn', 'MoviesThatFeelLike', 'A mood of uncomfortable, prolonged social encounters filled with tension and awkwardness.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2773, '1tut77u', 'Hi guys, I''m looking for media with this dark sci fi vibe mixed with lovecraftian horror', 'Dark sci-fi with Lovecraftian horror vibe', 'I''m really into this kind of atmosphere, what I''m looking for is;
-people in space encountering incomprehensible threats
-abandoned industrial-style space stations
-slow and enigmatic stories with substantial premise; take Iron Lung for example. In a world where all the stars and planets dissapeared, a convict is sent to a moon covered with a blood ocean to examine gargantuan monsters. That sounds AWESOME to me, it''s very specific and imaginative
Thanks for all the responses in advance 🤙', 'Able_Revolution9977', 1780411712, '/r/MoviesThatFeelLike/comments/1tut77u/hi_guys_im_looking_for_media_with_this_dark_sci/', 'https://i.redd.it/43c57dx3uv4h1.jpeg', 'MoviesThatFeelLike', 'A craving for slow-burn, oppressive sci-fi dread where humans confront incomprehensible cosmic threats in derelict, industrial corridors—Lovecraftian horror filtered through abandoned space stations and enigmatic worlds.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2774, '1tutmte', 'Am I the only one who thinks this scene is better than jersey', 'Am I the only one who thinks this scene is better than jersey', 'The above scene from Ms dhoni the untold story is still better than jersey scene ', 'Western-Cry-9196', 1780412611, '/r/MoviesThatFeelLike/comments/1tutmte/am_i_the_only_one_who_thinks_this_scene_is_better/', 'https://v.redd.it/2o6uslvqwv4h1', 'MoviesThatFeelLike', 'Nostalgic appreciation for emotionally powerful cricket biopic scenes, sparking debate over which film delivers greater impact.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2775, '1tuuekd', 'Movies that feel like the Joel Schumacher Batman Films', 'Movies that feel like the Joel Schumacher Batman Films', '', 'Thabrianking', 1780414191, '/r/MoviesThatFeelLike/comments/1tuuekd/movies_that_feel_like_the_joel_schumacher_batman/', 'https://www.reddit.com/gallery/1tuuekd', 'MoviesThatFeelLike', 'A vibrant, neon-drenched urban fantasy with a campy yet gritty art-deco aesthetic.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2776, '1tuw2gy', 'Dark comedies with manipulation', 'Dark comedies with manipulation', '', 'Male-2003', 1780417585, '/r/MoviesThatFeelLike/comments/1tuw2gy/dark_comedies_with_manipulation/', 'https://www.reddit.com/gallery/1tuw2gy', 'MoviesThatFeelLike', 'A thread for darkly humorous films centered on manipulation and deceit, with users sharing personal recommendations.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2777, '1tuw762', 'anyone?', 'Live-Action Cyberpunk Recommendations with Futuristic Drugs', 'preferably live action. i love animation, just trying to expand my horizons a little. shown are altered carbon, bladerunner 2047, cyberpunk, and some art i found off google. bonus points if it has futuristic drugs, that was one of my favorite pieces of worldbuilding from altered carbon!', 'Fantastic_Ad4438', 1780417853, '/r/MoviesThatFeelLike/comments/1tuw762/anyone/', 'https://www.reddit.com/gallery/1tuw762', 'MoviesThatFeelLike', 'The user is seeking immersive live-action cyberpunk worlds with neon aesthetics and futuristic elements like drugs, inspired by Altered Carbon and Blade Runner.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2778, '1tuxlrx', 'Any movies that feel like this one?', 'Any movies that feel like this one?', '', 'ProfessionalLevel908', 1780420690, '/r/MoviesThatFeelLike/comments/1tuxlrx/any_movies_that_feel_like_this_one/', 'https://www.reddit.com/gallery/1tutg34', 'MoviesThatFeelLike', 'A user requests movie recommendations without specifying a reference, creating an open-ended, community-focused atmosphere of casual suggestion and shared cinematic tastes.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2779, '1tuxmge', 'Any movies that feel like this?', 'Any movies that feel like this?', '', 'No_Dress_2107', 1780420729, '/r/MoviesThatFeelLike/comments/1tuxmge/any_movies_that_feel_like_this/', 'https://v.redd.it/4jbf5l39kw4h1', 'MoviesThatFeelLike', 'A dark, unsettling atmosphere of psychological dread and eerie menace — grainy Southern Gothic imagery paired with sinister voiceovers evoking True Detective''s first season.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2780, '1tuym2d', 'Movies that feel like', 'Movies that feel like', '', 'The_Fat_Tony_', 1780422701, '/r/MoviesThatFeelLike/comments/1tuym2d/movies_that_feel_like/', 'https://i.redd.it/n6o76d9sqw4h1.jpeg', 'MoviesThatFeelLike', 'A chaotic and humorous thread with absurd movie suggestions and repetitive image replies.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2781, '1tv0pke', 'Something soft, tender, and about friendship', 'Something soft, tender, and about friendship', '', 'Vinilla_Icecream', 1780426955, '/r/MoviesThatFeelLike/comments/1tv0pke/something_soft_tender_and_about_friendship/', 'https://i.redd.it/nxl8nllf3x4h1.jpeg', 'MoviesThatFeelLike', 'A warm, gentle yearning for tender stories about the quiet beauty of friendship, evoking nostalgic comfort and heartfelt emotional warmth.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2782, '1tv1kci', 'Bros', 'Bros', '', 'TheLetterBoxder', 1780428737, '/r/MoviesThatFeelLike/comments/1tv1kci/bros/', 'https://www.reddit.com/gallery/1tv1kci', 'MoviesThatFeelLike', 'Movies that capture the essence of brotherhood and loyal camaraderie, often with action or emotional depth.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2783, '1tv1twk', 'Movies that feel liminal/webcore?', '', 'https://preview.redd.it/nnc6op13ax4h1.png?width=640&format=png&auto=webp&s=c2ebf4dad5eb3602228da59f0eae7f55515fdf6a

https://preview.redd.it/c5e4ygw4ax4h1.png?width=996&format=png&auto=webp&s=ba2d8969ea3706e04b6ce673615831b85d5ebf30

https://preview.redd.it/rzajothdax4h1.png?width=1280&format=png&auto=webp&s=c750d62297584a8a01d4fad462ebefe09ac0fd29

', 'NineJuanon', 1780429297, '/r/MoviesThatFeelLike/comments/1tv1twk/movies_that_feel_liminalwebcore/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tv1twk/movies_that_feel_liminalwebcore/', 'MoviesThatFeelLike', 'A mood of eerie nostalgia and transitional emptiness, evoking liminal spaces and early internet aesthetics.', 'skipped', 'no usable images', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2784, '1tv2ls2', 'A widow preparing herself for her husband''s funeral', 'A widow preparing for her husband''s funeral', 'Any movies came to mind? Or any form of media.', 'Legal-Ad7016', 1780430924, '/r/MoviesThatFeelLike/comments/1tv2ls2/a_widow_preparing_herself_for_her_husbands_funeral/', 'https://i.redd.it/8ytdfih8fx4h1.png', 'MoviesThatFeelLike', 'A somber and reflective mood centered on grief and the duality of love and loss.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2785, '1tvblmr', 'Horror/suspense movies with this vibe.', 'Horror/suspense movies with this vibe.', '', 'BlueSM-012', 1780452569, '/r/MoviesThatFeelLike/comments/1tvblmr/horrorsuspense_movies_with_this_vibe/', 'https://www.reddit.com/gallery/1tvblmr', 'MoviesThatFeelLike', 'Intense, war-torn psychological horror with gritty suspense and supernatural elements.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2786, '1tvc2lz', 'vintage, campy, and gay', 'vintage, campy, and gay', 'want to make a collection of movies to watch this month (:', 'UsedWatercress3700', 1780453753, '/r/MoviesThatFeelLike/comments/1tvc2lz/vintage_campy_and_gay/', 'https://www.reddit.com/gallery/1tvc2lz', 'MoviesThatFeelLike', 'A flamboyant and nostalgic celebration of campy queer cinema.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2787, '1tvd5t1', 'A thrill/action movie with gloomy environment', 'A thrill/action movie with gloomy environment', 'I''m looking for a movie where the environment is mostly gloomy and rainy. It must be action/thrill. I really loved the old boy and the chaser. 

Please recommend based on the above characteristics.

The feeling of anxiety and eerieness.. ', 'Ok-Worry-9313', 1780456631, '/r/MoviesThatFeelLike/comments/1tvd5t1/a_thrillaction_movie_with_gloomy_environment/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tvd5t1/a_thrillaction_movie_with_gloomy_environment/', 'MoviesThatFeelLike', 'A dark and tense atmosphere with feelings of anxiety and eeriness in gloomy, rainy settings.', 'skipped', 'no usable images', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2788, '1tvdxcl', 'One Last Adventure / Final Day of High School Vibe', 'One Last Adventure Final Day of High School Vibe', 'Feeling a little nostalgic lately, it''s been ten years since I graduated high school, and this warm weather keeps pulling me back to those days. Looking for movie recommendations that capture that vibe. Bonus points if there''s just a touch of magical realism or sci-fi woven in.', 'Monstro552', 1780458782, '/r/MoviesThatFeelLike/comments/1tvdxcl/one_last_adventure_final_day_of_high_school_vibe/', 'https://www.reddit.com/gallery/1tvdxcl', 'MoviesThatFeelLike', 'Nostalgic, warm-weather haze of high school''s final days—bittersweet yearning for carefree adolescence, captured in golden-hour light and the ache of looking back a decade later.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2789, '1tveyo4', 'Romance with a dream-like vibe', 'Romance with a dream-like vibe', '', 'EmergencySpare7939', 1780461789, '/r/MoviesThatFeelLike/comments/1tveyo4/romance_with_a_dreamlike_vibe/', 'https://www.reddit.com/gallery/1tveyo4', 'MoviesThatFeelLike', 'A yearning for surreal, ethereal romance wrapped in dreamlike aesthetics — melancholy, tender, and visually intoxicating.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2790, '1tvgabb', 'Comedy movies with similar type of humor to this', 'Comedy movies with similar humor', '', 'josh_park189', 1780465859, '/r/MoviesThatFeelLike/comments/1tvgabb/comedy_movies_with_similar_type_of_humor_to_this/', 'https://v.redd.it/ec7uhz54b05h1', 'MoviesThatFeelLike', 'Casual search for buddy comedy with male-centric humor.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2791, '1tvhsc9', 'Movies that feel like THIS', 'Movies that feel like THIS', '', 'Material_Comfort_259', 1780470788, '/r/MoviesThatFeelLike/comments/1tvhsc9/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1tuv48l', 'MoviesThatFeelLike', 'Chaotic and gritty urban Americana with a touch of absurd humor.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2792, '1tvhtq2', 'I want a movie that feels like it was made by jack Stauber', 'I want a movie that feels like it was made by jack Stauber', 'All the shorts and mv make me feel welcomed.', 'Remarkable-Slide5376', 1780470915, '/r/MoviesThatFeelLike/comments/1tvhtq2/i_want_a_movie_that_feels_like_it_was_made_by/', 'https://www.reddit.com/gallery/1tvhtq2', 'MoviesThatFeelLike', 'A surreal and quirky atmosphere seeking whimsically eerie animation that feels both welcoming and uncanny.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2793, '1tviuxh', 'Noirish Romance with Musical Elements', 'Noirish Romance with Musical Elements', '', 'Lady-Columbo', 1780474485, '/r/MoviesThatFeelLike/comments/1tviuxh/noirish_romance_with_musical_elements/', 'https://www.reddit.com/gallery/1tviuxh', 'MoviesThatFeelLike', 'Dark romantic atmosphere with musical undertones.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2794, '1tvk94e', 'What are some movies that feel like this?', 'What are some movies that feel like this?', 'Can’t seem to find any movies that are like this', 'CatsRcut3', 1780479289, '/r/MoviesThatFeelLike/comments/1tvk94e/what_are_some_movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1tvk94e', 'MoviesThatFeelLike', 'A nostalgic yearning for a blend of wholesome comedy and poignant life lessons, often with a fantastical or moral twist.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2795, '1tvl7f0', 'What''s a movie scene that lives in your head rent free?', 'What''s a movie scene that lives in your head rent free?', '', 'MovieRushZone', 1780482306, '/r/MoviesThatFeelLike/comments/1tvl7f0/whats_a_movie_scene_that_lives_in_your_head_rent/', '/r/AskReddit/comments/1tvl5is/whats_a_movie_scene_that_lives_in_your_head_rent/', 'MoviesThatFeelLike', 'Nostalgic and reflective, pondering over iconic movie moments that linger in memory.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2796, '1tvl9uo', 'Besides the great gatsby, what do you think feels like this?', 'Besides the great gatsby, what do you think feels like this?', '', 'Collt092', 1780482521, '/r/MoviesThatFeelLike/comments/1tvl9uo/besides_the_great_gatsby_what_do_you_think_feels/', 'https://www.reddit.com/gallery/1tvl9uo', 'MoviesThatFeelLike', 'Glamorous Art Deco grandeur blending retro-futuristic opulence with noir undertones—ornate skylines, gilded excess, and a melancholy sense of lost grandeur.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2797, '1tvqmjs', 'movies or tv shows that feel like this', '', '2000s tuscan aesthetic', 'DingoTough5900', 1780496061, '/r/MoviesThatFeelLike/comments/1tvqmjs/movies_or_tv_shows_that_feel_like_this/', 'https://www.reddit.com/gallery/1tvqmjs', 'MoviesThatFeelLike', 'Luxurious 2000s Tuscan-inspired aesthetics with a touch of suburban opulence and reality TV flair.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2798, '1tvstws', 'Any movies that are visually similar to the game Heavy Rain?', 'Any movies that are visually similar to the game Heavy Rain?', 'I absolutely love how this game looks', 'Arc_Havoc', 1780500584, '/r/MoviesThatFeelLike/comments/1tvstws/any_movies_that_are_visually_similar_to_the_game/', 'https://www.reddit.com/gallery/1tvstws', 'MoviesThatFeelLike', 'The discussion evokes a dark, atmospheric, and rain-soaked aesthetic, seeking movies with a similar visual and tonal feel to the heavy rain-drenched game.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2799, '1tvsw5t', 'Non war movies that feel like this', 'Non war movies that feel like this', '', 'Male-2003', 1780500706, '/r/MoviesThatFeelLike/comments/1tvsw5t/non_war_movies_that_feel_like_this/', 'https://i.redd.it/5unry4gq635h1.jpeg', 'MoviesThatFeelLike', 'Gritty, dingy, and visceral atmosphere evoking jungles, urban decay, and intense action with a neo-noir or exploitation edge.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2800, '1tvuah4', 'All of these are separate', 'All of these are separate', 'No nudity btw ', 'ducky3686', 1780503517, '/r/MoviesThatFeelLike/comments/1tvuah4/all_of_these_are_separate/', 'https://www.reddit.com/gallery/1tvuah4', 'MoviesThatFeelLike', 'Nostalgic coming-of-age warmth — sunlit frames of youth, small-town summers, and the bittersweet beauty of growing up.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2801, '1tvv0wg', 'What Psychological Horror Movie Best Fits the Deadly Sin of Pride?', 'What Psychological Horror Movie Best Fits the Deadly Sin of Pride?', '[deleted]', '[deleted]', 1780505014, '/r/MoviesThatFeelLike/comments/1tvv0wg/what_psychological_horror_movie_best_fits_the/', '', 'MoviesThatFeelLike', 'A dark, introspective inquiry into pride within the realm of psychological horror.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2802, '1tvv84d', 'This classic style of adventure.', 'This classic style of adventure.', '', 'DreadCaptainE0', 1780505414, '/r/MoviesThatFeelLike/comments/1tvv84d/this_classic_style_of_adventure/', 'https://www.reddit.com/gallery/1tvv84d', 'MoviesThatFeelLike', 'A nostalgic and adventurous atmosphere reminiscent of classic pulp adventures and exploration tales.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2803, '1tvwflx', 'Which films best represent US East coast way of life?', 'films representing US East coast way of life', '[removed]', 'deepiez', 1780507843, '/r/MoviesThatFeelLike/comments/1tvwflx/which_films_best_represent_us_east_coast_way_of/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tvwflx/which_films_best_represent_us_east_coast_way_of/', 'MoviesThatFeelLike', 'A contemplative inquiry into regional identity and lifestyle through cinematic representation.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2804, '1tvxwjv', 'movies or series with things hidden in the background?', 'movies or series with things hidden in the background', '', '2Jads1Cup', 1780510744, '/r/MoviesThatFeelLike/comments/1tvxwjv/movies_or_series_with_things_hidden_in_the/', 'https://i.redd.it/fx8b3rmk045h1.jpeg', 'MoviesThatFeelLike', 'A collective fascination with spotting hidden details and Easter eggs woven into horror and thriller backgrounds, rewarding careful rewatching.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2805, '1tvz0za', 'epic in scale yet touching at human level ?', 'epic in scale yet touching at human level ?', '', 'lit_readit', 1780512997, '/r/MoviesThatFeelLike/comments/1tvz0za/epic_in_scale_yet_touching_at_human_level/', 'https://v.redd.it/shcihjy1kw4h1', 'MoviesThatFeelLike', 'A yearning for epic, sweeping narratives that remain deeply intimate and emotionally resonant.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2806, '1tvz7dk', 'Pure loneliness + Depression', 'Pure loneliness + Depression', 'So what’s your list of isolation/depression movies? Here’s my top 5—curious to see yours.

1. The Turin Horse
2. Skinamarink
3. Sleep Has Her House
4. Jeanne Dielman, 23 quai du Commerce, 1080 Bruxelles
5. The Outwaters

https://preview.redd.it/re2ekskdww4h1.jpg?width=632&format=pjpg&auto=webp&s=7e2cc4f10ae217474268e8d8611d11706d150b65', 'u9762552', 1780513356, '/r/MoviesThatFeelLike/comments/1tvz7dk/pure_loneliness_depression/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tvz7dk/pure_loneliness_depression/', 'MoviesThatFeelLike', 'A deeply melancholic and isolating atmosphere, evoking pure loneliness and depressive states.', 'skipped', 'no usable images', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2807, '1tw0ejp', 'Movies that feel like taking a poop at a gas station', 'Movies that feel like taking a poop at a gas station', '', 'KickedIntoOrbit', 1780515857, '/r/MoviesThatFeelLike/comments/1tw0ejp/movies_that_feel_like_taking_a_poop_at_a_gas/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tw0ejp/movies_that_feel_like_taking_a_poop_at_a_gas/', 'MoviesThatFeelLike', 'A gritty, uncomfortable, and darkly humorous atmosphere evoking dirty, chaotic spaces and visceral experiences.', 'skipped', 'no usable images', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2808, '1tw237t', 'Movies or animations like this video', 'Movies or animations like this video', 'Nature, animals in harsh realities of nature, not upbeat or overly joyful environment.', 'melekin', 1780519432, '/r/MoviesThatFeelLike/comments/1tw237t/movies_or_animations_like_this_video/', 'https://youtu.be/gNec4uzpRks?si=7RPMwttXpeK9Q3qb', 'MoviesThatFeelLike', 'A somber exploration of animal life in harsh natural environments.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2809, '1tw3wkh', 'Suggest me a film about a wild wild wild adventure. I wanna see a journey around the world of somebody looking for their identity, something deep that will make me cry. I loved into the wild', 'Suggest me a film about a wild wild wild adventure. I wanna see a journey around the world of somebody looking for their identity, something deep that will make me cry. I loved into the wild', '', 'Horror-Egg-4509', 1780523473, '/r/MoviesThatFeelLike/comments/1tw3wkh/suggest_me_a_film_about_a_wild_wild_wild/', 'https://www.reddit.com/gallery/1tw3wkh', 'MoviesThatFeelLike', 'Yearning for transformative wilderness journeys and soul-searching adventures that shake you out of routine and make you feel alive.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2810, '1tw4mbx', 'Eyes Without a Face', 'Eyes Without a Face', 'Movies that feel/look like the song Eyes Without a Face - Billy Idol ', 'Alone-Explanation246', 1780525071, '/r/MoviesThatFeelLike/comments/1tw4mbx/eyes_without_a_face/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tw4mbx/eyes_without_a_face/', 'MoviesThatFeelLike', 'Eerie and haunting cinematic atmosphere evocative of 80s synth-pop darkness.', 'skipped', 'no usable images', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2811, '1tw5f6t', 'American movies with strong giallo (Italian pulp horror) vibes?', 'American movies with giallo vibes', '*Giallo* is an Italian film genre that incorporates some or all of these elements: crime drama, psychological thriller, supernatural horror, and surrealism. It''s a little tricky to explain the vibe without seeing it for yourself. Pictures don''t quite do it justice. Think of a movie that feels like a dream state with heightened reality and unexplained moments. The movies typically end with a big reveal: the character you least suspected was the killer, probably because they were horribly abused as a child, or they absorbed an evil twin in the womb, or they are secretly in a coven of witches, or their child was born a monster (and they have to kill people to feed it). 

The genre has influenced countless filmmakers, but it remains fairly inaccessible to American audiences and the genre is not typically attempted here. 

There are some exceptions, of course. Eyes of Laura Mars (1978) and Alice, Sweet Alice (1976) are great examples of American giallo. Castle Freak (1995) was an American-Italian joint production and direct-to-video, so it gets an honorable mention. 

I''m eager to hear your recommendations! 

', 'randombydesign', 1780526968, '/r/MoviesThatFeelLike/comments/1tw5f6t/american_movies_with_strong_giallo_italian_pulp/', 'https://www.reddit.com/gallery/1tw5f6t', 'MoviesThatFeelLike', 'A surreal, dreamlike atmosphere with psychological tension and unexpected revelations, characteristic of giallo''s blend of crime, thriller, and horror elements.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2812, '1tw6my5', 'Looking for horror films set in rural swamp lands that give off this vibe:', 'Looking for horror films set in rural swamp lands that give off this vibe:', 'https://preview.redd.it/1xvdxkdci55h1.png?width=736&format=png&auto=webp&s=8b6680ebd4d3d5bb183c65627fd4f0e6df71003d

https://preview.redd.it/4ad9qgqei55h1.png?width=244&format=png&auto=webp&s=8eca4eb16fa336a3a62eb4b323ad2de06b370339

https://preview.redd.it/7cdnvhvqj55h1.png?width=600&format=png&auto=webp&s=335380771227f523b80fa87ae423af1be10be98a

https://preview.redd.it/1y8yq6jtj55h1.png?width=500&format=png&auto=webp&s=6855d0a57a614e7b7c1cbeeb2fa0957e14fcd7a7

https://preview.redd.it/rttuixxwj55h1.png?width=736&format=png&auto=webp&s=8f2a0423cdeecb661695d7b5d36ef529c05e3984

https://preview.redd.it/a5nfmaa0k55h1.png?width=736&format=png&auto=webp&s=f04458a1ea45285fec44aa069b1aefec1d71d822

https://preview.redd.it/xjg9uhr8k55h1.png?width=1155&format=png&auto=webp&s=ccd3ec41a99e9ba827e46965a2f897c7f1c00427

https://preview.redd.it/etebk7aak55h1.png?width=1170&format=png&auto=webp&s=4f25777065b702589d5ea295586dbf575889e302

https://preview.redd.it/j4m3nysfk55h1.png?width=608&format=png&auto=webp&s=ba2cab61f00321789f2f237514e864e71f6b06f2

https://preview.redd.it/drff7k5cl55h1.png?width=540&format=png&auto=webp&s=74a74b2cfd23582b6f40d6dc6033b8e49f2a6ce6

', 'throwing-stones-', 1780529903, '/r/MoviesThatFeelLike/comments/1tw6my5/looking_for_horror_films_set_in_rural_swamp_lands/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tw6my5/looking_for_horror_films_set_in_rural_swamp_lands/', 'MoviesThatFeelLike', 'Eerie, isolated swamp horror atmosphere.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2813, '1tw7ubc', 'Michael Jackson''s Who Is It music video', 'Michael Jackson''s Who Is It Music Video', '80S-2000s vibes, dark, mystery, erotic, New York/Chicago, female lead, femme fatale, money. Maybe supernatural/futuristic elements as well.', 'Long_Reflection_4202', 1780532954, '/r/MoviesThatFeelLike/comments/1tw7ubc/michael_jacksons_who_is_it_music_video/', 'https://www.reddit.com/gallery/1tw7ubc', 'MoviesThatFeelLike', 'Dark, mysterious, and erotic with 80s-2000s urban noir, femme fatale, and supernatural or futuristic elements.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2814, '1twafx5', 'Movies where the villains are like this.', 'Movies where the villains are like this.', '', 'BlueSM-012', 1780539844, '/r/MoviesThatFeelLike/comments/1twafx5/movies_where_the_villains_are_like_this/', 'https://www.reddit.com/gallery/1twafx5', 'MoviesThatFeelLike', 'An unsettling and eerie atmosphere featuring supernatural villains that create a sense of dread.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2815, '1twc548', 'Disturbing medieval horror with creepy bugs', '', '', 'capybarnia', 1780544579, '/r/MoviesThatFeelLike/comments/1twc548/disturbing_medieval_horror_with_creepy_bugs/', 'https://www.reddit.com/gallery/1twc548', 'MoviesThatFeelLike', 'A dark and eerie atmosphere blending medieval horror with unsettling bug-centric dread.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2816, '1twc7px', 'Disturbing medieval horror with creepy bugs', 'Disturbing medieval horror with creepy bugs', '', 'capybarnia', 1780544774, '/r/MoviesThatFeelLike/comments/1twc7px/disturbing_medieval_horror_with_creepy_bugs/', 'https://www.reddit.com/gallery/1twc7px', 'MoviesThatFeelLike', 'A request seeking dark, unsettling horror set in a medieval world with insectoid elements.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2817, '1twcca6', 'Disturbing medieval horror', 'Disturbing medieval horror', '', 'capybarnia', 1780545130, '/r/MoviesThatFeelLike/comments/1twcca6/disturbing_medieval_horror/', 'https://www.reddit.com/gallery/1twcca6', 'MoviesThatFeelLike', 'A dark and unsettling exploration of historical terror.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2818, '1twcejl', 'Disturbing medieval horror', '', '', 'capybarnia', 1780545304, '/r/MoviesThatFeelLike/comments/1twcejl/disturbing_medieval_horror/', 'https://www.reddit.com/gallery/1twcejl', 'MoviesThatFeelLike', 'The post evokes a disturbing and eerie medieval horror atmosphere, suggesting fear and darkness.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2819, '1twcgvu', 'Movies that feel like sunshine and rainbows', 'Movies that feel like sunshine and rainbows', '', 'capybarnia', 1780545487, '/r/MoviesThatFeelLike/comments/1twcgvu/movies_that_feel_like_sunshine_and_rainbows/', 'https://i.redd.it/a7pl6rxvv65h1.jpeg', 'MoviesThatFeelLike', 'A bright, cheerful, and uplifting atmosphere seeking films that evoke joy and positivity.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2820, '1twg3nb', 'Looking for this! (Romance, Horror, Etc)', 'Looking for this! (Romance, Horror, Etc)', '', 'TouristKeyy', 1780556871, '/r/MoviesThatFeelLike/comments/1twg3nb/looking_for_this_romance_horror_etc/', 'https://www.reddit.com/gallery/1tw8tlv', 'MoviesThatFeelLike', 'A dark and mysterious vibe seeking horror and romance with eerie and suspenseful atmospheres.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2821, '1twmfpu', 'Any movies with this kind of vibe?', '', '', 'Pale_Bike_7288', 1780576698, '/r/MoviesThatFeelLike/comments/1twmfpu/any_movies_with_this_kind_of_vibe/', 'https://www.reddit.com/gallery/1twmfpu', 'MoviesThatFeelLike', 'Tropical vacation vibes with humor and adventure.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2822, '1vz995b', 'movies that feel like this kind of fall (any genre welcome)', 'movies that feel like this kind of fall', 'photos taken in my natural habitat. how do these pics make you feel? what movie or show comes to mind?   
super curious to know what people think of. ', 'Safcet', 1787777112, '/r/MoviesThatFeelLike/comments/1vz995b/movies_that_feel_like_this_kind_of_fall_any_genre/', 'https://www.reddit.com/gallery/1vz995b', 'MoviesThatFeelLike', 'A nostalgic and eerie autumn atmosphere evoking small-town mystery and cozy fall vibes.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2823, '1vzem5q', 'What are your Favorite Coming of Age Films?', 'What are your Favorite Coming of Age Films?', '[removed]', '5oclockgoldenhour', 1787790107, '/r/MoviesThatFeelLike/comments/1vzem5q/what_are_your_favorite_coming_of_age_films/', 'https://www.reddit.com/gallery/1vzem5q', 'MoviesThatFeelLike', 'Nostalgic and reflective mood centered on personal growth, memory, and cinematic nostalgia.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2824, '1vzf2s4', 'Movies that feel like warm, suburban summer nights', 'Movies that feel like warm suburban summer nights', 'Looking for suburban, August end-of-summer vibes. Hum of crickets, kids biking, quiet town, that sort of thing.', 'wueopp', 1787791327, '/r/MoviesThatFeelLike/comments/1vzf2s4/movies_that_feel_like_warm_suburban_summer_nights/', 'https://www.reddit.com/gallery/1vzf2s4', 'MoviesThatFeelLike', 'Nostalgic and serene suburban summer nights with crickets, biking kids, and a quiet town atmosphere.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2825, '1vzfs4h', 'What is a good sad movie/ series that involves romance or depression?', 'What is a good sad movie/ series that involves romance or depression?', '', 'Impossible-Fix4144', 1787793226, '/r/MoviesThatFeelLike/comments/1vzfs4h/what_is_a_good_sad_movie_series_that_involves/', '/r/helpme/comments/1vzfr6v/what_is_a_good_sad_movie_series_that_involves/', 'MoviesThatFeelLike', 'A somber search for emotionally heavy romance or depression-themed media.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2826, '1vzg2dm', 'Movies You Relax/Sleep To', 'Movies You Relax/Sleep To', 'This isn’t to indicate that a movie is boring or doesn’t hold your interest, but rather a movie that relaxes you, or that you find relaxing, soothing, calming, comforting, or otherwise familiar enough to fall asleep to or relax with. Doesn’t have to make logical sense to anyone but you. 

I’ll start: Star Trek IV, Grumpier Old Men, Dennis the Menace (93), Bon Voyage Charlie Brown, Pee Wee’s Big Adventure, Mr. Baseball, and The Englishman Who Went Up a Hill But Came Down a Mountain. ', 'BishopSaturn', 1787794004, '/r/MoviesThatFeelLike/comments/1vzg2dm/movies_you_relaxsleep_to/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vzg2dm/movies_you_relaxsleep_to/', 'MoviesThatFeelLike', 'A warm, drowsy gathering of people sharing deeply personal comfort movies — familiar, cozy, and safe enough to drift off to.', 'skipped', 'no usable images', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2827, '1vzhmpv', 'Movies that feel like Prince of Persia', 'Movies that feel like Prince of Persia', '[removed]', 'HeavyCurves03', 1787798222, '/r/MoviesThatFeelLike/comments/1vzhmpv/movies_that_feel_like_prince_of_persia/', 'https://i.redd.it/4mpyn4pgxtlh1.jpeg', 'MoviesThatFeelLike', 'Seeking adventurous, swashbuckling films with desert landscapes, ancient Middle Eastern settings, parkour action, and romantic escapism.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2828, '1vzhz3t', 'Movies (Or documentaries) that feel like this', 'Ballroom and LGBT community movies and documentaries', '', 'Amazing_Blonde9890', 1787799176, '/r/MoviesThatFeelLike/comments/1vzhz3t/movies_or_documentaries_that_feel_like_this/', 'https://www.reddit.com/gallery/1vzhz3t', 'MoviesThatFeelLike', 'A nostalgic and gritty dive into ballroom culture and LGBT communities of the 80s and 90s.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2829, '1vzjhhz', 'Is Toxic worse than Ligar? Why would Yash do this to himself, Why Yash! Why?', 'Is Toxic worse than Liger? Why would Yash do this to himself, Why Yash! Why?', '', 'onlybizninja', 1787803577, '/r/MoviesThatFeelLike/comments/1vzjhhz/is_toxic_worse_than_ligar_why_would_yash_do_this/', '/r/KannadaCinemaClub/comments/1vzj9ok/is_toxic_worse_than_ligar_why_would_yash_do_this/', 'MoviesThatFeelLike', 'Exasperated disappointment and frustration over a filmmaker''s questionable creative choices.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2830, '1vzjo8d', 'Movies that feel like this?', 'Movies that feel like this?', '', 'Lazy_One99', 1787804151, '/r/MoviesThatFeelLike/comments/1vzjo8d/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1vzjo8d', 'MoviesThatFeelLike', 'An adventurous and reflective mood evoking wanderlust and scenic journeys.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2831, '1vzkeja', 'Non mysicals', 'Non mysicals', '[removed]', '[deleted]', 1787806512, '/r/MoviesThatFeelLike/comments/1vzkeja/non_mysicals/', '', 'MoviesThatFeelLike', 'A mood focused on non-mythical, real-world elements without fantasy.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2832, '1vzlk1c', 'Movies that feel like medieval Europe', 'Movies that feel like medieval Europe', '[removed]', '[deleted]', 1787810329, '/r/MoviesThatFeelLike/comments/1vzlk1c/movies_that_feel_like_medieval_europe/', '', 'MoviesThatFeelLike', 'The post seeks movies that evoke the atmosphere of medieval Europe, suggesting a desire for historical authenticity and immersive settings.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2833, '1vzmy1e', 'i wanna know what stories take place in places like this.', 'i wanna know what stories take place in places like this.', '', 'dane_the_great', 1787815135, '/r/MoviesThatFeelLike/comments/1vzmy1e/i_wanna_know_what_stories_take_place_in_places/', 'https://www.reddit.com/gallery/1vzmy1e', 'MoviesThatFeelLike', 'Nostalgic curiosity for surreal digital landscapes.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2834, '1vzo1ex', 'Movies that feels like Doctor Who Series 3, Episode 10 ', '', '', 'Itchy-Dig1610', 1787819070, '/r/MoviesThatFeelLike/comments/1vzo1ex/movies_that_feels_like_doctor_who_series_3/', 'https://v.redd.it/fjsa288unvlh1', 'MoviesThatFeelLike', 'The atmosphere is one of eerie suspense and psychological horror, as users seek films that replicate the chilling and mind-bending tension of Doctor Who''s ''Blink''.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2835, '1vzoauf', 'Films that gve off this vibe.', 'Films that give off this vibe.', '', 'wormword46', 1787820032, '/r/MoviesThatFeelLike/comments/1vzoauf/films_that_gve_off_this_vibe/', 'https://i.redd.it/40vv4fbrqvlh1.jpeg', 'MoviesThatFeelLike', 'A blend of childhood whimsy with underlying horror and unsettling atmospheres.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2836, '1vzp7m3', 'The LA of the 90s', 'The LA of the 90s', 'The vibes from Pulp Fiction / Falling Down ', 'scala84', 1787823250, '/r/MoviesThatFeelLike/comments/1vzp7m3/the_la_of_the_90s/', 'https://i.redd.it/6cmecb1f0wlh1.jpeg', 'MoviesThatFeelLike', 'A gritty, nostalgic urban atmosphere capturing the essence of 90s Los Angeles, with a mix of action, crime, and drama.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2837, '1vzrw7a', 'Movies that Feel Like Violent Chick Flicks?', 'Movies that Feel Like Violent Chick Flicks', 'May seem contradictory, I know. Do any titles fit?', 'Kindly-Reception1108', 1787831899, '/r/MoviesThatFeelLike/comments/1vzrw7a/movies_that_feel_like_violent_chick_flicks/', 'https://i.redd.it/196ga921qwlh1.jpeg', 'MoviesThatFeelLike', 'Empowering and violent films centered on fierce female protagonists, blending action with chick-flick aesthetics.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2838, '1vzrzjw', 'Movies that give vibes of vertigo or have scenes from heights', 'Movies that give vibes of vertigo or have scenes from heights', '', 'chaiegai', 1787832107, '/r/MoviesThatFeelLike/comments/1vzrzjw/movies_that_give_vibes_of_vertigo_or_have_scenes/', 'https://www.reddit.com/gallery/1vzrzjw', 'MoviesThatFeelLike', 'Heart-pounding fear of heights with vertigo-inducing tension from towering skyscrapers, treacherous cliffs, and death-defying stunts.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2839, '1vztzeu', 'I built a movie discovery app because I was tired of deciding what to watch', 'I built a movie discovery app because I was tired of deciding what to watch', '', 'Swabhimanc', 1787837269, '/r/MoviesThatFeelLike/comments/1vztzeu/i_built_a_movie_discovery_app_because_i_was_tired/', 'https://www.reddit.com/gallery/1vztvhh', 'MoviesThatFeelLike', 'Practical frustration turned into a DIY solution for the endless scroll of indecision.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2840, '1vzucxs', 'Grim fantasy sense of uncertainty', 'Grim fantasy sense of uncertainty', '', 'Mattvieyy6', 1787838190, '/r/MoviesThatFeelLike/comments/1vzucxs/grim_fantasy_sense_of_uncertainty/', 'https://www.reddit.com/gallery/1vzucxs', 'MoviesThatFeelLike', 'Dark, brooding fantasy atmosphere with an undercurrent of dread and moral ambiguity.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2841, '1vzus0o', 'post apocalyptic solitary survival', 'post apocalyptic solitary survival', '', 'Mattvieyy6', 1787839159, '/r/MoviesThatFeelLike/comments/1vzus0o/post_apocalyptic_solitary_survival/', 'https://www.reddit.com/gallery/1vzus0o', 'MoviesThatFeelLike', 'Bleak and isolated survival in a post-apocalyptic world.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2842, '1vzvibu', 'How to Make Millions Before Grandma Dies — one of the saddest films I''ve seen', 'How to Make Millions Before Grandma Dies', '[removed]', 'nurra2', 1787840821, '/r/MoviesThatFeelLike/comments/1vzvibu/how_to_make_millions_before_grandma_dies_one_of/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1vzvibu/how_to_make_millions_before_grandma_dies_one_of/', 'MoviesThatFeelLike', 'A deeply sad and emotional cinematic experience.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2843, '1w005c3', 'PRISONERS 2013', 'PRISONERS 2013', '', 'raj722', 1787851028, '/r/MoviesThatFeelLike/comments/1w005c3/prisoners_2013/', 'https://v.redd.it/vmj3ydctaylh1', 'MoviesThatFeelLike', 'A direct reference to the 2013 film Prisoners, evoking a tense and dramatic atmosphere.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2844, '1w00i8v', 'HEAT 1995', 'Heat 1995', '', 'raj722', 1787851806, '/r/MoviesThatFeelLike/comments/1w00i8v/heat_1995/', 'https://v.redd.it/7q3zl9pbdylh1', 'MoviesThatFeelLike', 'Enthusiastic discussion and recommendation for a gritty, complex crime film.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2845, '1w01j1i', 'Movies with weird alternate universes that have just enough changes to feel different and similar at the same time? While also being oddly comforting.', 'Movies with weird alternate universes that have just enough changes to feel different and similar at the same time? While also being oddly comforting.', '', 'Jellypathicdream', 1787853964, '/r/MoviesThatFeelLike/comments/1w01j1i/movies_with_weird_alternate_universes_that_have/', 'https://www.reddit.com/gallery/1w01j1i', 'MoviesThatFeelLike', 'A longing for familiar worlds that are just slightly off, blending nostalgia with gentle surrealism and a touch of unsettling comfort.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2846, '1w033ok', '2010s nostalgia?', '2010s nostalgia', 'something from the 2010s w this vibe and feels like blonde by frank ocean? ', 'Few-Advertising-5164', 1787857344, '/r/MoviesThatFeelLike/comments/1w033ok/2010s_nostalgia/', 'https://www.reddit.com/gallery/1w033ok', 'MoviesThatFeelLike', 'Hazy, melancholic 2010s youth nostalgia — aimless walks, house parties, and the bittersweet feeling that life was huge even when you were broke.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2847, '1w03f43', 'Movies that feel like Crazy Taxi?', 'Movies that feel like Crazy Taxi?', 'Before anyone asks, yes, I know about the Taxi series of films, including the American one that no one liked.', 'Supersmashbrosfan', 1787858026, '/r/MoviesThatFeelLike/comments/1w03f43/movies_that_feel_like_crazy_taxi/', 'https://www.reddit.com/gallery/1w03f43', 'MoviesThatFeelLike', 'Nostalgic and high-energy search for the chaotic, arcade-driving rush of a 90s video game, with a focus on fast chases, quirky humor, and iconic soundtracks.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2848, '1w04jt0', 'Movies that feel like YOU ARE IN YOUR FLOW STATE.', 'Movies that feel like you are in your flow state', '', 'Barath_HBK_', 1787860470, '/r/MoviesThatFeelLike/comments/1w04jt0/movies_that_feel_like_you_are_in_your_flow_state/', '/r/Letterboxd/comments/1w049of/movies_that_best_fits_the_films_that_put_you_in/', 'MoviesThatFeelLike', 'Movies that immerse you completely, creating a sense of effortless focus and engagement.', 'skipped', 'no usable images', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2849, '1w04lid', 'How about it?', 'How about it?', '[deleted]', '[deleted]', 1787860574, '/r/MoviesThatFeelLike/comments/1w04lid/how_about_it/', '', 'MoviesThatFeelLike', 'The post is deleted with no content, creating an empty and inactive atmosphere.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2850, '1w04u4r', 'Movies that feel like heroic fiction drama, which is framed in ancient time!', 'Movies that feel like heroic fiction drama, which is framed in ancient time!', '', 'The_NonDualistic', 1787861067, '/r/MoviesThatFeelLike/comments/1w04u4r/movies_that_feel_like_heroic_fiction_drama_which/', 'https://www.reddit.com/gallery/1w04u4r', 'MoviesThatFeelLike', 'A request seeking movies that combine heroic fiction drama with ancient historical or mythological settings, suggesting a craving for epic, timeless tales of heroism.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2851, '1w05nd1', 'A film that feels like one of those romantic tragedies where you know they love each other, but you also know it’s not going to end well', '', '***Braveheart*** **(1995)**', 'f-california', 1787862810, '/r/MoviesThatFeelLike/comments/1w05nd1/a_film_that_feels_like_one_of_those_romantic/', 'https://i.redd.it/z72ty3r1azlh1.jpeg', 'MoviesThatFeelLike', 'A bittersweet craving for romantic tragedies where love is mutual but inevitably doomed.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2852, '1w07jy7', 'The American college football experience in all of its bonkers and glory', 'The American college football experience in all of its bonkers and glory', '', 'smoothpaving', 1787867123, '/r/MoviesThatFeelLike/comments/1w07jy7/the_american_college_football_experience_in_all/', 'https://www.reddit.com/gallery/1w07jy7', 'MoviesThatFeelLike', 'A chaotic and glorious celebration of American college football, blending drama, comedy, and high energy.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2853, '1w08fxw', '8 women', '8 women', 'I love this movie so much, i felt like i was invited in a difficult family and watched them gossip and squabble. 

Bonus point if they are cheeky lesbians.', 'kannniballs', 1787869218, '/r/MoviesThatFeelLike/comments/1w08fxw/8_women/', 'https://i.redd.it/3ointzp3tzlh1.jpeg', 'MoviesThatFeelLike', 'Intimate, gossipy family drama with a sense of inclusion and conflict, seeking similar movies with cheeky lesbian elements.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2854, '1w08l3v', 'unpredictable comedys with a deliring plot', 'Unpredictable comedies with a delirious plot', '', 'kannniballs', 1787869562, '/r/MoviesThatFeelLike/comments/1w08l3v/unpredictable_comedys_with_a_deliring_plot/', 'https://www.reddit.com/gallery/1w08l3v', 'MoviesThatFeelLike', 'A playful quest for comedies with wild, unpredictable plots and delirious humor.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2855, '1w0a526', 'Unsettling creepiness covered by idyllic, soft, feminity', 'Unsettling creepiness covered by idyllic, soft femininity', 'I loooove this subgenre of small town horror because it often transforms mothers, the figures of supreme affection, into the villainous monsters, and turns the most feminine aesthetic into something macabre. TV recs are also welcomed! TIA!

Southern gothic, religious horror, boarding schools, female relationships, cults, small towns, picture perfect housewives, complicated family relationships', 'strawberryc0w_', 1787873406, '/r/MoviesThatFeelLike/comments/1w0a526/unsettling_creepiness_covered_by_idyllic_soft/', 'https://www.reddit.com/gallery/1w0a526', 'MoviesThatFeelLike', 'A macabre yet idyllic atmosphere where unsettling horror is wrapped in soft, feminine aesthetics, evoking small-town dread and motherhood gone wrong.', 'publishable', NULL, NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2856, '1w0a8yj', 'Need a movie that feels like how “The only time I prayed” - Dermot Kennedy sounds', 'Need a movie that feels like how “The only time I prayed” - Dermot Kennedy sounds', 'Title pretty much sums it up. I would like you to listen to that song and think of some movies that feel how that song sounds, if that makes sense? I already have a couple on the list, like What Dreams May Come. Please add more 😁', 'Both_Group_1512', 1787873691, '/r/MoviesThatFeelLike/comments/1w0a8yj/need_a_movie_that_feels_like_how_the_only_time_i/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1w0a8yj/need_a_movie_that_feels_like_how_the_only_time_i/', 'MoviesThatFeelLike', 'Melancholic and emotionally charged atmosphere focusing on painful relationship endings.', 'skipped', 'no usable images', NULL, '2026-08-28 09:15:02', '2026-08-28 09:15:02');
