-- 0171_seed_20260830T033819Z_01_posts.sql: data seed from pipeline:load run.
-- Generated:  2026-08-30T03:38:44.218962+00:00
-- Run started: 2026-08-30T03:38:19.542440+00:00
-- Source: data/working/load manifest from this run.
--
-- Idempotent: every INSERT is INSERT OR IGNORE, keyed by the
-- table's natural unique constraint.  Wrangler's migration
-- tracking normally prevents re-apply; the OR IGNORE is
-- defense in depth for partial / interrupted re-runs.
--
-- Chunk: 01_posts (1/5)
-- Tables: imported_vibe_posts.
-- Pipeline-state tables (processing_runs, pipeline_artifacts)
-- are intentionally excluded — they're per-run bookkeeping.

INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2857, '1tsyuea', 'Movies that have that classic fantasy RPG feeling', 'Movies that have that classic fantasy RPG feeling', 'Like Legend of Zelda or Final Fantasy ', 'ExtensionFuture654', 1780242292, '/r/MoviesThatFeelLike/comments/1tsyuea/movies_that_have_that_classic_fantasy_rpg_feeling/', 'https://www.reddit.com/gallery/1tsyuea', 'MoviesThatFeelLike', 'A nostalgic quest for epic fantasy adventures reminiscent of classic video games.', 'publishable', NULL, NULL, '2026-08-30 03:38:43', '2026-08-30 03:38:43');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2858, '1tsyy00', 'Movies like Paul (2011)', 'Movies like Paul (2011)', 'Little green men, flying saucers, cows/people getting abducted, Roswell/Area 51; that kind of cultural canon.', 'QuantumOfSilence', 1780242523, '/r/MoviesThatFeelLike/comments/1tsyy00/movies_like_paul_2011/', 'https://www.reddit.com/gallery/1tsyy00', 'MoviesThatFeelLike', 'A playful quest for sci-fi comedies centered on quirky alien encounters and suburban adventures.', 'publishable', NULL, NULL, '2026-08-30 03:38:43', '2026-08-30 03:38:43');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2859, '1tsze32', 'Movies that feel like this Thesis ad', 'Movies that feel like this Thesis ad', 'It doesnt have to be Monkeys', 'RifleTower', 1780243522, '/r/MoviesThatFeelLike/comments/1tsze32/movies_that_feel_like_this_thesis_ad/', 'https://www.reddit.com/gallery/1tsze32', 'MoviesThatFeelLike', 'Surreal and eclectic cinematic experiences with bizarre, animal-themed or outlandish elements.', 'publishable', NULL, NULL, '2026-08-30 03:38:43', '2026-08-30 03:38:43');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2860, '1tt0o8o', 'Finally! You can now watch the official Backrooms Movie online! 🚪🦺🪞', 'Backrooms Movie online', '[removed]', 'CicadaDistinct6004', 1780246434, '/r/MoviesThatFeelLike/comments/1tt0o8o/finally_you_can_now_watch_the_official_backrooms/', 'https://sites.google.com/view/backrooms-movie-watch-online/home', 'MoviesThatFeelLike', 'Excited relief and celebration about finally being able to access a long-awaited horror media release.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-30 03:38:43', '2026-08-30 03:38:43');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2861, '1tt15xt', 'Movies that feel....', 'Movies that feel....', '', 'capibarawithsocks', 1780247538, '/r/MoviesThatFeelLike/comments/1tt15xt/movies_that_feel/', 'https://v.redd.it/xsvsm6ox9i4h1', 'MoviesThatFeelLike', 'A hazy, nostalgic longing for the electric pulse of New York City — lonely skyscrapers, late-night wandering, and the bittersweet ache of urban life.', 'publishable', NULL, NULL, '2026-08-30 03:38:43', '2026-08-30 03:38:43');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2862, '1tt166x', 'Movies that feel like this album/project', 'Movies that feel like this album/project', '(Stages 1-6, not just stage 6)

The feeling of losing yourself, but not through some sort of violent outburst. I''m looking for kind of that gradual decline. Doesn''t necessarily have to be slow cinema. Bleak, hopeless worldview.', 'throu1away', 1780247553, '/r/MoviesThatFeelLike/comments/1tt166x/movies_that_feel_like_this_albumproject/', 'https://i.redd.it/89m292ez9i4h1.jpeg', 'MoviesThatFeelLike', 'A gradual, bleak descent into memory loss and existential dread.', 'publishable', NULL, NULL, '2026-08-30 03:38:43', '2026-08-30 03:38:43');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2863, '1tt2c3o', 'Movies that deal with depression and melancholy? Kinda like these album coers', 'Movies that deal with depression and melancholy', 'Source, pic 1, 2, 3: Sadness. pic 4: Make a change kill yourself. pic 5: Forgotten tomb', 'dvdh_03', 1780250168, '/r/MoviesThatFeelLike/comments/1tt2c3o/movies_that_deal_with_depression_and_melancholy/', 'https://www.reddit.com/gallery/1tt2c3o', 'MoviesThatFeelLike', 'Somber, introspective exploration of depression and melancholy through cinema.', 'publishable', NULL, NULL, '2026-08-30 03:38:43', '2026-08-30 03:38:43');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2864, '1tt5ki8', 'Movies that feel like this tiktok edit on my fyp', 'Movies that feel like this tiktok edit on my fyp', '', 'josh_park189', 1780257245, '/r/MoviesThatFeelLike/comments/1tt5ki8/movies_that_feel_like_this_tiktok_edit_on_my_fyp/', 'https://v.redd.it/psp8lcss2j4h1', 'MoviesThatFeelLike', 'A slick, high-stakes atmosphere of crime, excess, and fast-paced criminal energy.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2865, '1tt6kz6', 'Any movies that give this vibe?', 'Movies that give this vibe', '', 'randomaccount2357', 1780259525, '/r/MoviesThatFeelLike/comments/1tt6kz6/any_movies_that_give_this_vibe/', 'https://www.reddit.com/gallery/1tt6kz6', 'MoviesThatFeelLike', 'Confusing and eerie mundane absurdity.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2866, '1tt6vml', 'Overcast weather with dark clouds', '', '', 'Current-Topic6696', 1780260193, '/r/MoviesThatFeelLike/comments/1tt6vml/overcast_weather_with_dark_clouds/', 'https://www.reddit.com/gallery/1tt6vml', 'MoviesThatFeelLike', 'Gloomy and atmospheric with a sense of impending doom or melancholy under dark clouds.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2867, '1tt7ta6', 'Scary movies/tv shows that have creepy scary insane asylum/hospitals settings', 'Scary movies/tv shows with creepy asylum/hospital settings', '', 'Wooden_Big_2853', 1780262356, '/r/MoviesThatFeelLike/comments/1tt7ta6/scary_moviestv_shows_that_have_creepy_scary/', 'https://www.reddit.com/gallery/1tt7ta6', 'MoviesThatFeelLike', 'A community exchange seeking chilling horror media set in creepy asylum and hospital environments, filled with recommendations ranging from psychological thrillers to found footage films.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2868, '1tt9lpt', 'Movies that feel like...', 'Movies that feel like Krystal Bick Instagram photos', 'Photos from Krystal Bick on Insta', 'MotelleCodeenDragon', 1780266708, '/r/MoviesThatFeelLike/comments/1tt9lpt/movies_that_feel_like/', 'https://www.reddit.com/gallery/1tt9lpt', 'MoviesThatFeelLike', 'Sophisticated, glamorous European and retro aesthetic with an air of high-fashion romanticism and cinematic longing.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2869, '1ttafe8', 'Film about the circus? Horror or not, doesn’t matter', 'Film about the circus? Horror or not, doesn''t matter', '', 'Horror-Egg-4509', 1780268799, '/r/MoviesThatFeelLike/comments/1ttafe8/film_about_the_circus_horror_or_not_doesnt_matter/', 'https://www.reddit.com/gallery/1ttafe8', 'MoviesThatFeelLike', 'A nostalgic, eerie craving for circus-themed stories that blend wonder, darkness, and the strange beauty of sideshow life.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2870, '1ttaurx', 'dreamy, fun, and cute preppy pastel outfits', 'dreamy, fun, and cute preppy pastel outfits', '', 'Expensive_Week8151', 1780269905, '/r/MoviesThatFeelLike/comments/1ttaurx/dreamy_fun_and_cute_preppy_pastel_outfits/', 'https://www.reddit.com/gallery/1ttaurx', 'MoviesThatFeelLike', 'A whimsical and nostalgic atmosphere with playful, pastel-colored preppy fashion.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2871, '1ttbcc0', 'Any suggestions? Horror type please. Middle of nowhere houses, farms ect..', '', '', 'Responsible-Sea5776', 1780271205, '/r/MoviesThatFeelLike/comments/1ttbcc0/any_suggestions_horror_type_please_middle_of/', 'https://www.reddit.com/gallery/1ttbcc0', 'MoviesThatFeelLike', 'Eerie isolation in rural and farmhouse settings, evoking dread and vulnerability in the face of unknown threats.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2872, '1ttc0bp', 'What yall got?', 'What yall got?', '', 'KzKn_2020', 1780272931, '/r/MoviesThatFeelLike/comments/1ttc0bp/what_yall_got/', 'https://www.reddit.com/gallery/1ttc0bp', 'MoviesThatFeelLike', 'Sleek excess and decadent style—luxury cars, fashion, nightlife, and the intoxicating allure of wealth with an underlying edge.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2873, '1ttc4bc', 'Movies that feel like this song?', 'Movies that feel like this song?', 'Avant-garde, glitchy, upbeat and sweet but almost kind of in an artificial sweetener way.', 'throu1away', 1780273213, '/r/MoviesThatFeelLike/comments/1ttc4bc/movies_that_feel_like_this_song/', 'https://v.redd.it/r6usmn0aek4h1', 'MoviesThatFeelLike', 'Avant-garde and glitchy with an artificially sweet, upbeat feel.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2874, '1ttczh1', 'Horror movies with this kind of ambience.', 'Horror movies with this kind of ambience.', '', 'BlueSM-012', 1780275592, '/r/MoviesThatFeelLike/comments/1ttczh1/horror_movies_with_this_kind_of_ambience/', 'https://www.reddit.com/gallery/1ttczh1', 'MoviesThatFeelLike', 'Eerie and atmospheric horror evoking rural dread and psychological unease.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2875, '1ttdjod', 'One Last Adventure / Final Day of High School Vibe', 'One Last Adventure / Final Day of High School Vibe', '[deleted]', '[deleted]', 1780277096, '/r/MoviesThatFeelLike/comments/1ttdjod/one_last_adventure_final_day_of_high_school_vibe/', '', 'MoviesThatFeelLike', 'A bittersweet, nostalgic end-of-an-era feeling — the kind of sunny, wistful last day where everything feels both like a beginning and a goodbye.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2876, '1ttdkdi', 'Movies that feel like:', 'Movies that feel like:', '', 'Benjamin5431', 1780277146, '/r/MoviesThatFeelLike/comments/1ttdkdi/movies_that_feel_like/', 'https://www.reddit.com/gallery/1ttdkdi', 'MoviesThatFeelLike', 'A casual, collaborative thread where users share and celebrate movies featuring interracial romance, with a mix of heartfelt recommendations and lighthearted banter.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2877, '1tthdjd', 'Movies that feel like', 'Movies that feel like', '', 'CutterChoper', 1780287894, '/r/MoviesThatFeelLike/comments/1tthdjd/movies_that_feel_like/', 'https://www.reddit.com/gallery/1tthdjd', 'MoviesThatFeelLike', 'A dreamy, introspective atmosphere blending ethereal Japanese art cinema with melancholic coming-of-age stories and surreal, emotionally resonant visuals.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2878, '1ttihuv', 'Any movies that feel like Sandra Bernhard''s Excuses for Bad Behavior, Part 1', '', 'This is a wild shot in the dark and probably very niche, but hell why not try? If you''ve listened to this gem, what movies did it remind you of? I''d be incredibly fascinated.', 'XipeTotecwithGlitter', 1780291250, '/r/MoviesThatFeelLike/comments/1ttihuv/any_movies_that_feel_like_sandra_bernhards/', 'https://i.redd.it/6vq4ugxvvl4h1.jpeg', 'MoviesThatFeelLike', 'A hesitant yet fascinated inquiry into obscure movie parallels for a niche audio performance.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2879, '1ttjtg8', 'Movies like nimona', 'Movies like Nimona', '', 'Impossible-Car-1880', 1780295488, '/r/MoviesThatFeelLike/comments/1ttjtg8/movies_like_nimona/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1ttjtg8/movies_like_nimona/', 'MoviesThatFeelLike', 'A search for animated films with heartfelt, identity-driven narratives similar to Nimona.', 'skipped', 'no usable images', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2880, '1ttldxd', 'What movies come to mind that are similar to Silent Hill f - story OR atmosphere (or both)', 'Movies similar to Silent Hill f in story or atmosphere', '', 'ECHOSTIK', 1780300798, '/r/MoviesThatFeelLike/comments/1ttldxd/what_movies_come_to_mind_that_are_similar_to/', '/r/horror/comments/1ttldh0/what_movies_come_to_mind_that_are_similar_to/', 'MoviesThatFeelLike', 'Seeking eerie, psychological horror experiences similar to Silent Hill.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2881, '1ttp2m3', 'Can Any one pay with there SBI Debit card for me?', 'Can anyone pay with their SBI debit card for me?', '', 'have_we_met_earlier', 1780312619, '/r/MoviesThatFeelLike/comments/1ttp2m3/can_any_one_pay_with_there_sbi_debit_card_for_me/', '/r/DebitCardLifestyle/comments/1ttp1tn/can_any_one_pay_with_there_sbi_debit_card_for_me/', 'MoviesThatFeelLike', 'Desperate plea for financial assistance.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2882, '1ttqm1r', 'Movies that feel like:', 'Movies that feel like:', '', 'Pure-Dragonfruit1899', 1780316683, '/r/MoviesThatFeelLike/comments/1ttqm1r/movies_that_feel_like/', 'https://i.redd.it/lsbwwihjzn4h1.jpeg', 'MoviesThatFeelLike', 'Gritty urban suspense and train-centric thrillers.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2883, '1ttrdhq', 'Dark and Artistic movies', 'Dark and Artistic movies', 'The only movie and TV''s show I can think of are The House that Jack Built and Hannibal the tv show and I''m wondering if there''s anything similar to them. Visually the only comparison I can think of are paintings made by Carravagio and the sculptures made by Emil Melmoth. I''m not too big on romance movies but I don''t mind a horror, sci-fi, action,or comedy movie with romantic elements I''m just not big on pure romance movies. Please let me know if there are any more examples of these types of movies.', 'reylee05', 1780318563, '/r/MoviesThatFeelLike/comments/1ttrdhq/dark_and_artistic_movies/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1ttrdhq/dark_and_artistic_movies/', 'MoviesThatFeelLike', 'Fascination with dark, visually striking, and artistically intense media.', 'skipped', 'no usable images', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2884, '1ttsa6l', 'movies that feel like this?', 'movies that feel like this?', 'random bs for adhd ig', 'Massive_Ad_2870', 1780320581, '/r/MoviesThatFeelLike/comments/1ttsa6l/movies_that_feel_like_this/', 'https://i.redd.it/wdtmbzp4bo4h1.jpeg', 'MoviesThatFeelLike', 'A chaotic and visually overwhelming collection of media that captures the sensory overload and excess often associated with ADHD.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2885, '1tttisu', 'Retro Romance Dynamics Like Leia and Han (Star Wars) or Rick and Evelyn (The Mummy)?', 'Retro Romance Dynamics Like Leia and Han or Rick and Evelyn', 'Love me a good snobbier/fancier/posher person who loves a total smartass with a reckless streak. It doesn’t go too far to the point where it kinda just becomes bullying and it always feels like they choose to come back to talk more. Y’know? 

Preferably something released between 1960-1990 but if you think it fits well enough. ', 'isopodsoup_', 1780323255, '/r/MoviesThatFeelLike/comments/1tttisu/retro_romance_dynamics_like_leia_and_han_star/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tttisu/retro_romance_dynamics_like_leia_and_han_star/', 'MoviesThatFeelLike', 'A nostalgic craving for witty, tension-filled romances with opposing social classes or personalities.', 'skipped', 'no usable images', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2886, '1ttvzcl', 'Retro Horror/Thriller, etc Movies With The Teen Girl Dread, Insanity and Emotional Drama Of Doki Doki Literature Club?', 'Retro Horror/Thriller Movies With Teen Girl Dread and Emotional Drama Like DDLC', 'Can include graphic violence like DDLC did, of course. Preferably released between the 70s to early 90s. 

Looking for something the captures a similar feeling of “something is going terribly wrong with these girls” that gets more complex and sad as the story goes on. Probably the closest I can think of would be the Higurashi series but ofc that doesn’t have a movie yet. 

Any suggestions? Thank you! ', 'isopodsoup_', 1780328276, '/r/MoviesThatFeelLike/comments/1ttvzcl/retro_horrorthriller_etc_movies_with_the_teen/', 'https://i.redd.it/u8ejlpb0yo4h1.jpeg', 'MoviesThatFeelLike', 'A tense, melancholic search for retro horror capturing teenage dread and psychological unraveling.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2887, '1ttx113', 'Movies that feel like this', 'Movies that feel like this', '[removed]', '[deleted]', 1780330368, '/r/MoviesThatFeelLike/comments/1ttx113/movies_that_feel_like_this/', '', 'MoviesThatFeelLike', 'A request for mood-matching film recommendations based on a removed visual reference, leaving the desired aesthetic ambiguous.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2888, '1ttx1pn', 'Movies that feel like this', 'Movies that feel like this', '[removed]', 'dzefdekiler', 1780330408, '/r/MoviesThatFeelLike/comments/1ttx1pn/movies_that_feel_like_this/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1ttx1pn/movies_that_feel_like_this/', 'MoviesThatFeelLike', 'A request for mood-matched film recommendations with no context provided.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2889, '1tu04l4', 'Hii, anyone up for joining a online movie community?', 'Hii, anyone up for joining a online movie community?', '[deleted]', '[deleted]', 1780336517, '/r/MoviesThatFeelLike/comments/1tu04l4/hii_anyone_up_for_joining_a_online_movie_community/', '', 'MoviesThatFeelLike', 'Communal and inviting, centered around movie discussions.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2890, '1tu05ey', 'Hii, anyone up for joining a online movie community?', '', 'Hey if anyone up for joining a movie community let me know where people watch movies together and have fun 3-4 movies per week depends on genre polls and many more, respectful debates and cinematic watching experience with others', 'Busy_Habit_8333', 1780336560, '/r/MoviesThatFeelLike/comments/1tu05ey/hii_anyone_up_for_joining_a_online_movie_community/', 'https://i.redd.it/itdthd2nmp4h1.jpeg', 'MoviesThatFeelLike', 'Friendly invitation to join a movie-watching community for shared enjoyment and respectful discussions.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2891, '1tu2pm5', 'Crime Movies with this kind of story', 'Crime Movies with this kind of story', '', 'CodGroundbreaking803', 1780341544, '/r/MoviesThatFeelLike/comments/1tu2pm5/crime_movies_with_this_kind_of_story/', 'https://www.reddit.com/gallery/1tu2pm5', 'MoviesThatFeelLike', 'Gritty, dark crime narratives set in rural American landscapes with themes of moral ambiguity and decay.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2892, '1tu2u54', 'Could you recommend something as crazy as the True Blood show', '', 'Recently, my friends and I were watching the True Blood show, and that was amazing. The plot was a bit silly, and we were just screaming in the screen and laughing. Don''t get me wrong, I liked it.

Could you recommend anything similar, please? Where the atmosphere is nice, the characters are interesting, but something silly without trying being silly 

I''m sorry if it sounds strange ', 'Flimsy_Plum6669', 1780341800, '/r/MoviesThatFeelLike/comments/1tu2u54/could_you_recommend_something_as_crazy_as_the/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tu2u54/could_you_recommend_something_as_crazy_as_the/', 'MoviesThatFeelLike', 'A quirky, fun atmosphere with engaging characters and absurd yet enjoyable plotlines.', 'skipped', 'no usable images', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2893, '1tu5e3n', 'Movies that feel like the French countryside in the summer', 'Movies that feel like the French countryside in the summer', 'https://preview.redd.it/qi97i91xhq4h1.jpg?width=1200&format=pjpg&auto=webp&s=ea3b70ce09d0be46bb8b1789d717f9b81ce48662

https://preview.redd.it/xyp00a1xhq4h1.jpg?width=1024&format=pjpg&auto=webp&s=79b6077d29dbf248f6d8aff8278ac2b73a7b1240

https://preview.redd.it/yy3n2a1xhq4h1.jpg?width=1080&format=pjpg&auto=webp&s=e3b245243d155c1eda08a6624c8df74ed97a6591

https://preview.redd.it/noztt91xhq4h1.jpg?width=736&format=pjpg&auto=webp&s=43ef3e94062c0d92f6e56e21ab7ba5ba98b2ebac

https://preview.redd.it/v3ccza1xhq4h1.jpg?width=736&format=pjpg&auto=webp&s=932396602a4f45d334ccd9f1ec485e96458bdb24

', 'Candid-Panda2737', 1780347093, '/r/MoviesThatFeelLike/comments/1tu5e3n/movies_that_feel_like_the_french_countryside_in/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tu5e3n/movies_that_feel_like_the_french_countryside_in/', 'MoviesThatFeelLike', 'Evokes a tranquil and sunny pastoral atmosphere reminiscent of the French countryside in summer.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2894, '1tu5o5e', 'Movies That Feel Like European Summer', 'Movies That Feel Like European Summer', 'I want that French summer feel. Can be any films at all, any time period, any genre. I just want to feel summer', 'Candid-Panda2737', 1780347691, '/r/MoviesThatFeelLike/comments/1tu5o5e/movies_that_feel_like_european_summer/', 'https://www.reddit.com/gallery/1tu5o5e', 'MoviesThatFeelLike', 'Evokes the warm, nostalgic, and leisurely atmosphere of a European summer.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2895, '1tu73ym', 'I need movies like "emotion 1966"', 'Movies like Emotion 1966', '', 'Dlokun', 1780350810, '/r/MoviesThatFeelLike/comments/1tu73ym/i_need_movies_like_emotion_1966/', 'https://www.reddit.com/gallery/1tu73ym', 'MoviesThatFeelLike', 'A yearning for surreal, dreamlike art cinema that blends ethereal beauty with unsettling, emotionally intense atmospheres.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2896, '1tu7nbx', 'Movies that feel like this? (post apocalyptic city/town eaten by the nature)', 'Movies that feel like post apocalyptic city town eaten by nature', '', 'Tenebrae_Hunter', 1780351995, '/r/MoviesThatFeelLike/comments/1tu7nbx/movies_that_feel_like_this_post_apocalyptic/', 'https://i.redd.it/3ehv216iwq4h1.jpeg', 'MoviesThatFeelLike', 'Post-apocalyptic atmosphere with nature reclaiming urban spaces, evoking desolation and eerie beauty.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2897, '1tu8dk1', 'Need help finding similar movies to i saw the tv glow', 'Need help finding similar movies to I Saw the TV Glow', 'Hi! Im looking for movies that most people find slow and boring. Im looking for a horror element, a pshychological element, and a whimsy element! Here are some examples of what i mean: were all going to the worlds fair, skinamarink, im thinking of ending things, caveat, possum, men, and i saw the tv glow! i hope i finally found the right sub reddit to post this in, i keep getting my posts removed and i dont know why😅anyway, thank you to anyone who helps!', 'obsidian_nightmare6', 1780353645, '/r/MoviesThatFeelLike/comments/1tu8dk1/need_help_finding_similar_movies_to_i_saw_the_tv/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tu8dk1/need_help_finding_similar_movies_to_i_saw_the_tv/', 'MoviesThatFeelLike', 'A craving for slow-burn, psychologically disorienting films that feel like lucid nightmares wrapped in eerie whimsy — movies that unsettle you while beauty and dread blur together.', 'skipped', 'no usable images', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2898, '1tu8u4r', 'movies with this vibe', '', '', 'xsadgirll', 1780354737, '/r/MoviesThatFeelLike/comments/1tu8u4r/movies_with_this_vibe/', 'https://www.reddit.com/gallery/1tu8u4r', 'MoviesThatFeelLike', 'A gritty, adventurous motorcycle road trip vibe with a vintage 60s/70s rebellion aesthetic.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2899, '1tul5w7', 'Movies like feel like this board?', 'Movies like feel like this board?', '', 'Wild_Analysis_3345', 1780390521, '/r/MoviesThatFeelLike/comments/1tul5w7/movies_like_feel_like_this_board/', 'https://www.reddit.com/gallery/1tul5w7', 'MoviesThatFeelLike', 'Nostalgic and quirky coming-of-age indie film atmosphere.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2900, '1tuoiy4', 'Movies where you become so obsessed with a passion that it ultimately becomes your demise', 'Movies where you become so obsessed with a passion that it ultimately becomes your demise', '', 'Shivathewriter', 1780400908, '/r/MoviesThatFeelLike/comments/1tuoiy4/movies_where_you_become_so_obsessed_with_a/', 'https://www.reddit.com/gallery/1tuoiy4', 'MoviesThatFeelLike', 'Intense, dark fascination with consuming passion — stories of artists, athletes, and seekers who sacrifice everything including themselves for their all-consuming drive.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2901, '1u40fup', 'Looking for mind bending movies with reality distortion, survival mysteries, and unusual horror concepts (Any language is fine)', 'Looking for mind bending movies with reality distortion, survival mysteries, and unusual horror concepts', 'I am looking for Movies from any country and in any language. American, Korean, British, Indian, European, or anything else is fine.

I am mainly interested in:

• Thriller  
• Mystery  
• Supernatural  
• Horror  
• Psychological thriller  
• Survival stories  
• Time loops and reality distortion  
• Detectives and serial killers  
• Crime, mafia, and underworld stories  
• Fantasy and superpowers  
• Villain, antihero, or morally gray protagonists  
• Intelligent, pragmatic characters  
• Good action and suspense

I am open to almost any genre as long as the story is engaging and not heavily focused on romance.

What I am NOT looking for:

• Romance driven stories  
• Melodramas  
• Warm hearted slice of life movies  
• Stories where romance is the central plot

A little romance is completely fine, but I do not want it to be the main focus of the movies.

Some movies I enjoyed:

1. Arlington Road 1999
2. American Psycho
3. John Wick series
4. mechanic resurrection
5. nobody
6. Metro 2013 \[ A good disaster movie \]
7. mirage 2018
8. Don''t Breathe
9. Most Dangerous Game
10. law-abiding citizen
11. Malignant 2021
12. boss level
13. circle \[ Great movie imo \]
14. Orphan part 1 and 2
15. Oculus
16. Mirror 2008
17. Amityvill Horror
18. The reaping
19. You''re Next
20. The game 1997
21. Old 2021
22. Phone Booth 2002
23. Dune 2021
24. Turistas 2006
25. The social network
26. Wrong turn 2021
27. Wolf Creek
28. Eden Lake
29. The Cabin in The Woods
30. The Strangers
31. Evil Dead
32. Cabin Fever
33. Dead End
34. The Hills Have Eyes
35. The Descent
36. The Ward
37. The Texas Chainsaw Massacre
38. The Ward
39. Identity
40. Saw \[all parts\]
41. Sea fever
42. Cabin fever
43. The breed 2006,
44. Vine
45. Host
46. Life Balkore experiment
47. The Thing
48. The Predator \[ all series \]
49. Prometheus
50. Batman \[ all series, including the latest one 2022 \]
51. The Witch \[parts 1 and 2 \]
52. Speed
53. A Beautiful Mind
54. The Fare 2018

I also recently discovered that I really enjoy unusual horror and mystery concepts such as liminal spaces, reality bending stories, strange environments, survival mysteries, and mind bending plots.

Based on this list, what would you recommend?

I will keep commenting/posting, whenever I watch something new that I enjoy, so feel free to check back later if you have similar tastes or are looking for recommendations yourself.', 'DaoistHu', 1781282205, '/r/MoviesThatFeelLike/comments/1u40fup/looking_for_mind_bending_movies_with_reality/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1u40fup/looking_for_mind_bending_movies_with_reality/', 'MoviesThatFeelLike', 'A restless cinephile craving reality-bending psychological puzzles, survival tension, and morally murky thrillers across world cinema.', 'skipped', 'no usable images', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2902, '1w0bc2b', 'Movies Like The Odyssey', 'Movies Like The Odyssey', '', 'Havzino', 1787876503, '/r/MoviesThatFeelLike/comments/1w0bc2b/movies_like_the_odyssey/', '/r/MovieSuggestions/comments/1vyhdfv/movies_like_the_odyssey/', 'MoviesThatFeelLike', 'Epic historical and classical adventure films recommended for their grand scale and moral struggles.', 'skipped', 'no usable images', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2903, '1w0c4jy', 'Film that depicts being a hobo', '', 'Question, has there been a film that depicts homelessness or being a hobo? Like the same pacing and observational style of Perfect Days but instead it''s the opposite(uncomfortable)?', 'SnooRevelations4498', 1787878631, '/r/MoviesThatFeelLike/comments/1w0c4jy/film_that_depicts_being_a_hobo/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1w0c4jy/film_that_depicts_being_a_hobo/', 'MoviesThatFeelLike', 'A request for raw, unglamorous, and uncomfortably realistic portrayals of homelessness in film, emphasizing observational styles.', 'skipped', 'no usable images', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2904, '1w0gydi', 'Movies that feel liminal but warped', 'Movies that feel liminal but warped', '', 'syntheticcontrols', 1787892607, '/r/MoviesThatFeelLike/comments/1w0gydi/movies_that_feel_liminal_but_warped/', 'https://www.reddit.com/gallery/1w0gydi', 'MoviesThatFeelLike', 'Surreal and unsettling dreamscape atmosphere.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2905, '1w0hah1', 'I want to cry', 'I want to cry', 'Please give me movie suggestions that will make me cry', 'hauntedmansion1971', 1787893679, '/r/MoviesThatFeelLike/comments/1w0hah1/i_want_to_cry/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1w0hah1/i_want_to_cry/', 'MoviesThatFeelLike', 'A user seeks emotionally overwhelming movies to induce catharsis through tears.', 'skipped', 'no usable images', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2906, '1w0hrp1', 'Gimme some messy horror', 'Gimme some messy horror', '', 'Bulaum', 1787895226, '/r/MoviesThatFeelLike/comments/1w0hrp1/gimme_some_messy_horror/', '/r/MovieSuggestions/comments/1w0hpcq/gimme_some_messy_horror/', 'MoviesThatFeelLike', 'A direct request for gritty and messy horror films.', 'skipped', 'no usable images', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2907, '1w0j9r6', 'Vast Wild Ancient feeling films?', 'Vast Wild Ancient feeling films', 'What are your film recommendations for films that feel vast, very lonely nature, nostalgic for simpler times, like little islanders trying to survive, grey skies, walking in forests, making the ordinary struggle feel eerie and wistful type films?', 'RustyBucket4745', 1787900457, '/r/MoviesThatFeelLike/comments/1w0j9r6/vast_wild_ancient_feeling_films/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1w0j9r6/vast_wild_ancient_feeling_films/', 'MoviesThatFeelLike', 'Eerie and wistful vastness with lonely natural landscapes and a nostalgic tone.', 'skipped', 'no usable images', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2908, '1w0kon3', 'Large monster - practical effects', 'Large monster - practical effects', '', 'Plus_Ad1745', 1787905592, '/r/MoviesThatFeelLike/comments/1w0kon3/large_monster_practical_effects/', 'https://www.reddit.com/gallery/1w0kon3', 'MoviesThatFeelLike', 'A passionate discussion about movies featuring large monsters created with practical effects, filled with nostalgic and thrilling recommendations.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2909, '1w0lbzw', 'Romantic but weird, and not slow', 'Romantic but weird and not slow', '', 'Dull-Bid9243', 1787907912, '/r/MoviesThatFeelLike/comments/1w0lbzw/romantic_but_weird_and_not_slow/', '/r/MovieSuggestions/comments/1w0lbsd/romantic_but_weird_and_not_slow/', 'MoviesThatFeelLike', 'Offbeat, quirky romance with a touch of the surreal and unconventional, seeking stories that feel emotionally alive without dragging.', 'skipped', 'no usable images', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2910, '1w0nkdh', 'I don''t know what I like about these movies. But I believe there is something common about these movies that I can''t explain.', 'Movies with unexplained common appeal', '', 'Range_King', 1787915383, '/r/MoviesThatFeelLike/comments/1w0nkdh/i_dont_know_what_i_like_about_these_movies_but_i/', '/r/Cinema/comments/1w0nk64/i_dont_know_what_i_like_about_these_movies_but_i/', 'MoviesThatFeelLike', 'Curious exploration of subtle commonalities in film preferences.', 'skipped', 'no usable images', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2911, '1w0o0bd', 'Movies that feel ethereal', 'Movies that feel ethereal', 'watched the French beauty and the beast and fell in love with aesthetics', 'Tzuweee', 1787916701, '/r/MoviesThatFeelLike/comments/1w0o0bd/movies_that_feel_ethereal/', 'https://www.reddit.com/gallery/1w0o0bd', 'MoviesThatFeelLike', 'A dreamy and magical atmosphere focused on visually ethereal and aesthetic cinema.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2912, '1w0p23j', 'Is there movies that got this vibe of ancient civilizations that''s living on ice, mostly night visuals, different kind of human consciousness', 'Ancient civilizations on ice, night visuals, different human consciousness', '', 'Range_King', 1787919679, '/r/MoviesThatFeelLike/comments/1w0p23j/is_there_movies_that_got_this_vibe_of_ancient/', 'https://i.redd.it/2glkq085z3mh1.png', 'MoviesThatFeelLike', 'Eerie, ancient Arctic civilizations under night skies with altered human states.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2913, '1w0pvwg', 'To everyone who is always suggesting Strawberry Mansion… THANK YOU', '', 'I finally watching this movie last night and oh boy. I loved it! I am always looking for weird, surreal movies and this one is perfect. Dreams, futuristic, the glaring colors and lights, the eerie vibe. Everything. Chefs kiss. Thank you for bringing this into my life. That is all. 😌😌 ', 'Environmental_Song99', 1787921901, '/r/MoviesThatFeelLike/comments/1w0pvwg/to_everyone_who_is_always_suggesting_strawberry/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1w0pvwg/to_everyone_who_is_always_suggesting_strawberry/', 'MoviesThatFeelLike', 'Surreal and eerie with vibrant colors and dreamlike sequences.', 'skipped', 'no usable images', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2914, '1w0riwm', 'Mysterious and eerie', 'Mysterious and Eerie', '', 'B_nana81', 1787925892, '/r/MoviesThatFeelLike/comments/1w0riwm/mysterious_and_eerie/', 'https://www.reddit.com/gallery/1w0riwm', 'MoviesThatFeelLike', 'A mysterious and eerie atmosphere, evoking supernatural thrills and unsettling suspense.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2915, '1w0shvp', 'Movies that feel like reminiscing about a life you never got to live to the full :(', '', 'The lovely bones (2009) ', 'f-california', 1787928145, '/r/MoviesThatFeelLike/comments/1w0shvp/movies_that_feel_like_reminiscing_about_a_life/', 'https://i.redd.it/cywj95nbo4mh1.jpeg', 'MoviesThatFeelLike', 'A melancholic reflection on missed opportunities and the poignant beauty of lives that could have been.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2916, '1w0uu1w', 'Movies that feel like mysterious kidnapping', 'Movies that feel like mysterious kidnapping', '', 'S3XY_mis', 1787933370, '/r/MoviesThatFeelLike/comments/1w0uu1w/movies_that_feel_like_mysterious_kidnapping/', 'https://www.reddit.com/gallery/1w0uu1w', 'MoviesThatFeelLike', 'A tense and mysterious atmosphere evoking feelings of abduction and the unknown.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2917, '1w0vd8u', 'Movies that feels like a Asimov robots novel?', '', 'I recently read I, Robot and loved it, but I was a little disappointed by how close to the story and topics the movie adaptation was, so I''d like to know if anyone knows of any closer to the Asimov''s work.', 'Significant-Town-817', 1787934557, '/r/MoviesThatFeelLike/comments/1w0vd8u/movies_that_feels_like_a_asimov_robots_novel/', 'https://www.reddit.com/gallery/1w0vd8u', 'MoviesThatFeelLike', 'A community-driven exploration of science fiction films and series that capture the philosophical and ethical depth of Asimov''s robot stories.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2918, '1w0xrxd', 'Shakespeare''s A Midsummer Night''s Dream', 'Shakespeare''s A Midsummer Night''s Dream', '[deleted]', '[deleted]', 1787939842, '/r/MoviesThatFeelLike/comments/1w0xrxd/shakespeares_a_midsummer_nights_dream/', '', 'MoviesThatFeelLike', 'A whimsical and romantic mood evoking Shakespearean comedy.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2919, '1w0yj2d', 'Post nuclear fallout/post apocalypse', 'Post Nuclear Fallout / Post Apocalypse', 'I want some underrated post fallout or post apocalypse movies 

Not just some cool crazy plot. I want to see a life inside of post apocalypse world

Preferably a little bit comic', 'Equal_Many6470', 1787941449, '/r/MoviesThatFeelLike/comments/1w0yj2d/post_nuclear_falloutpost_apocalypse/', 'https://www.reddit.com/gallery/1w0yj2d', 'MoviesThatFeelLike', 'A craving for lived-in, gritty post-apocalyptic worlds where survival is daily grind rather than spectacle, laced with dark humor and offbeat comic absurdity.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2920, '1w102x6', 'What movies fit the vibe of "The Wolfman"? I''m looking for dark, gothic, foggy, and mysterious films. Any recommendations?', 'What movies fit the vibe of "The Wolfman"? I''m looking for dark, gothic, foggy, and mysterious films. Any recommendations?', 'I am looking for', 'luch_sacude', 1787944869, '/r/MoviesThatFeelLike/comments/1w102x6/what_movies_fit_the_vibe_of_the_wolfman_im/', 'https://i.redd.it/agi2mbhy16mh1.jpeg', 'MoviesThatFeelLike', 'Dark, gothic, and mysterious atmosphere with foggy settings.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2921, '1w10kfr', 'UK/Irish core film/show', 'UK/Irish core film/show', 'I am looking for some chill film or show that feels like Sam Fender... I know it might sound funny but like something that just breathes uk/ireland cloudy quiet suburb pub gray shoreline... similar to "Normal People", "the Outrun", "Skins (UK)",  "The Banshees of Inisherin", "All Of Us Strangers", ideally not too mainstream, that hopefully touches more emotional/psychological themes. Thank you!', 'SlowSlowBluebird', 1787945955, '/r/MoviesThatFeelLike/comments/1w10kfr/ukirish_core_filmshow/', 'https://i.redd.it/qab61g5a56mh1.jpeg', 'MoviesThatFeelLike', 'A melancholic and nostalgic atmosphere seeking UK/Irish suburban and shoreline vibes with emotional depth.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2922, '1w16d0x', 'A movie that feels like this song', 'A movie that feels like this song', 'Song: ∆XIUS LIИK - Iwillnǝvǝrlǝ†yøugø

link: [https://www.youtube.com/watch?v=WYi6wb9OJkY](https://www.youtube.com/watch?v=WYi6wb9OJkY)', 'Original_Recover_452', 1787959736, '/r/MoviesThatFeelLike/comments/1w16d0x/a_movie_that_feels_like_this_song/', 'https://i.redd.it/ms3scr82a7mh1.png', 'MoviesThatFeelLike', 'A user seeks media that captures the emotional essence of a song, suggesting a reflective and atmospheric mood.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2923, '1w176i2', 'Movies that feel Frankenstein-esque', 'Movies that feel Frankenstein-esque', '1. Frankenstein (1931)

2. Bride of Frankenstein (1935)

3-4. Frankenstein (2025)

5. Re-Animator (1985)

6. Frankenhooker

7. Frankenstein (Junji Ito)

8-9. Frankenstein (Bernie Wrighston)', 'Jijolin_Supreme', 1787961884, '/r/MoviesThatFeelLike/comments/1w176i2/movies_that_feel_frankensteinesque/', 'https://www.reddit.com/gallery/1w176i2', 'MoviesThatFeelLike', 'Gothic horror and mad science explorations with a mix of classic and modern creature features.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2924, '1w19i28', 'without the disturbing scenes', 'without the disturbing scenes', '', 'UsedWatercress3700', 1787968454, '/r/MoviesThatFeelLike/comments/1w19i28/without_the_disturbing_scenes/', 'https://www.reddit.com/gallery/1w19i28', 'MoviesThatFeelLike', 'A humorous and sarcastic discussion seeking alternatives to disturbing cult films.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2925, '1w1angy', 'Horror movie/TV shows with a similar vibe of this image', 'Horror movies and TV shows with similar vibe', '', 'CommonWar7535', 1787971802, '/r/MoviesThatFeelLike/comments/1w1angy/horror_movietv_shows_with_a_similar_vibe_of_this/', 'https://i.redd.it/fkkfl805a8mh1.jpeg', 'MoviesThatFeelLike', 'A community sharing eerie and supernatural horror recommendations with a blend of creature features and apocalyptic dread.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2926, '1w1b6zk', 'Cannibal Corpse vibes', 'Cannibal Corpse vibes', '', 'Sea-Conclusion959', 1787973401, '/r/MoviesThatFeelLike/comments/1w1b6zk/cannibal_corpse_vibes/', 'https://www.reddit.com/gallery/1w1b6zk', 'MoviesThatFeelLike', 'A visceral, grotesque, and intense horror atmosphere inspired by death metal aesthetics.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2927, '1w1bsxv', 'Movies/Series with "real life non-actors" in them.', 'Movies/Series with real life non-actors in them', 'Being a tech person, I enjoyed The Big Bang Theory, Silicon Valley, Young Sheldon and I will be happy to see more like those, specially since all those shows feature tech people who are not actors. 

Like Elon Musk (appearing in TBBT, Young Sheldon and Iron Man 2) or Bill Gates, Dick Costolo, Kara Swisher, Winklevoss Twins all appearing in Silicon Valley at some point. 

I need more movies/shows like those. ', 'Haghiri75', 1787975239, '/r/MoviesThatFeelLike/comments/1w1bsxv/moviesseries_with_real_life_nonactors_in_them/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1w1bsxv/moviesseries_with_real_life_nonactors_in_them/', 'MoviesThatFeelLike', 'A tech enthusiast''s request for media with real-world figures is met with a mix of helpful suggestions and critical remarks in the discussion.', 'skipped', 'no usable images', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2928, '1w1cldc', 'TV shows/films that feel like this', 'TV shows/films that feel like this', '', 'Ok-Band1228', 1787977635, '/r/MoviesThatFeelLike/comments/1w1cldc/tv_showsfilms_that_feel_like_this/', 'https://www.reddit.com/gallery/1w1cldc', 'MoviesThatFeelLike', 'Foggy, eerie coastal atmosphere with misty shores, lighthouses, and an unsettling sense of mystery lurking beneath a calm New England-style seaside setting.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2929, '1w1dbea', 'Movies that feel like total confusion', 'Movies that feel like total confusion', '', 'Lazy_One99', 1787979911, '/r/MoviesThatFeelLike/comments/1w1dbea/movies_that_feel_like_total_confusion/', 'https://www.reddit.com/gallery/1w1dbea', 'MoviesThatFeelLike', 'A disorienting journey through mind-bending films that challenge perception and reality.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2930, '1w1dxux', 'Movies/Tv shows that feel like Point break', 'Movies/TV shows that feel like Point Break', '', 'LoudKitty-2401', 1787981892, '/r/MoviesThatFeelLike/comments/1w1dxux/moviestv_shows_that_feel_like_point_break/', 'https://i.redd.it/fwb2jwaw39mh1.jpeg', 'MoviesThatFeelLike', 'Adrenaline-hungry search for high-stakes heist-and-chase action with extreme sports swagger and blurred lines between cops and criminals.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2931, '1w1eqtv', 'MoviesThatFeelLike', '', '[deleted]', '[deleted]', 1787984514, '/r/MoviesThatFeelLike/comments/1w1eqtv/moviesthatfeellike/', '', 'MoviesThatFeelLike', '', 'skipped', 'no usable images; no vibe summary; no enriched recommendation matches', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2932, '1w1et4l', 'MoviesThatFeelLike', '', '', 'musicismytherapy-', 1787984730, '/r/MoviesThatFeelLike/comments/1w1et4l/moviesthatfeellike/', 'https://www.reddit.com/gallery/1w1et4l', 'MoviesThatFeelLike', 'A psychedelic and surreal atmosphere focused on mind-altering and visually intense cinematic experiences.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2933, '1w1g53d', '2000s YA/romance recs?', '2000s YA romance recs', 'Looking for movies/shows with that classic 2000s young-adult romantic vibe. Any recs?', 'LostInVegasNights', 1787989300, '/r/MoviesThatFeelLike/comments/1w1g53d/2000s_yaromance_recs/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1w1g53d/2000s_yaromance_recs/', 'MoviesThatFeelLike', 'A nostalgic request for romantic, youthful entertainment from the early 2000s.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2934, '1w1gyvz', 'Movies that feel like this', 'Movies that feel like this', '', 'CarterDire1', 1787992217, '/r/MoviesThatFeelLike/comments/1w1gyvz/movies_that_feel_like_this/', 'https://i.redd.it/nef9iatry9mh1.png', 'MoviesThatFeelLike', 'Dreamy, surreal, and liminal — a collective yearning for transportive visual experiences that blur the line between reality and imagination.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2935, '1w1l0nl', 'Movies that feel like this song and this edit?', '', 'Like dark fantasy but in a stage setting possibly? First one I thought of was Phantom of the Opera  ', 'throwaway3685343', 1788005770, '/r/MoviesThatFeelLike/comments/1w1l0nl/movies_that_feel_like_this_song_and_this_edit/', 'https://v.redd.it/dibajv553bmh1', 'MoviesThatFeelLike', 'Dark fantasy with a theatrical and dramatic stage atmosphere.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2936, '1w1pajm', 'A priest in love (with a lot of yearning)', 'A priest in love with a lot of yearning', 'BASICALLY SOMETHING LIKE HILDA FURACAO. I WATCHED THE SHOW RECENTLY AND OMFGG CRAVINGG MORE', 'krishna4ever', 1788016822, '/r/MoviesThatFeelLike/comments/1w1pajm/a_priest_in_love_with_a_lot_of_yearning/', 'https://www.reddit.com/gallery/1w1pajm', 'MoviesThatFeelLike', 'A deep craving for passionate, forbidden romances involving priests, evoking intense yearning and emotional tension.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2937, '1w1pm1l', 'Movies that feel like you’re about to uncover an ancient secret (please read description)', '', 'I’ve already watched:

The Ninth Gate  
The Da Vinci Code  
Angels & Demons  
The Mummy  
Indiana Jones  
National Treasure  
The Name of the Rose  
Stargate  
The Librarian- Quest for the Spear  
As above so below

Anything involving ancient mysteries, forgotten civilizations, secret societies and clues that lead to something much bigger. Anything Robert Langdon would do', 'Ordinary-Gal', 1788017580, '/r/MoviesThatFeelLike/comments/1w1pm1l/movies_that_feel_like_youre_about_to_uncover_an/', 'https://www.reddit.com/gallery/1w1pm1l', 'MoviesThatFeelLike', 'A sense of eager anticipation for unraveling ancient mysteries and forgotten secrets through cinematic adventures.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2938, '1w1prrg', 'Movies that feel like living in a village in Europe', 'Movies that feel like living in a village in Europe', '', 'ascyanideco', 1788017965, '/r/MoviesThatFeelLike/comments/1w1prrg/movies_that_feel_like_living_in_a_village_in/', 'https://www.reddit.com/gallery/1w1prrg', 'MoviesThatFeelLike', 'A nostalgic longing for the rustic, historical charm of European village life, blending serious suggestions with humorous pushback about modern realities.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2939, '1w1qo6v', 'Jazzy AmericanWinter vibe', 'Jazzy AmericanWinter vibe', '[deleted]', '[deleted]', 1788020102, '/r/MoviesThatFeelLike/comments/1w1qo6v/jazzy_americanwinter_vibe/', '', 'MoviesThatFeelLike', 'A request for a cozy, jazzy wintery atmosphere evoking a nostalgic Americana feel.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2940, '1w1r0de', 'Retro American Winter', '', 'P.S. Sorry for the AI pictures, Pinterest is really fucking crappy these days. It''ll be nice if anyone could just tell me an alternative.

I want a retro vibe of an American city, suburb or small town in the winter, not necessarily Christmas. No snow is fine, as long as it could show the bare-leaved, gloomy winter atmosphere. 

Modern films are great but preferably 1980-2000. Could be set in anytime, as long as there are no smart phones.

There has to be 50s pop music involved in the movie''s soundtrack, see Frank Sinatra, Tony Bennett, Dean Martin, Frankie Valli... other artists are fine, of course. See Sleepless in Seattle or Goodfellas.

Any genre is fine, as long as it''s not horror. 

Thank you in advance :)', 'Dunder_Mufflins', 1788020924, '/r/MoviesThatFeelLike/comments/1w1r0de/retro_american_winter/', 'https://www.reddit.com/gallery/1w1r0de', 'MoviesThatFeelLike', 'Nostalgic and cozy retro American winter atmosphere with a gloomy, bare-leaved setting and 50s pop music influences.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2941, '1w1t5y8', 'Building movies like dreed type big building', 'Building movies like Dredd type big building', 'Building movies', 'AmanYadav19', 1788026022, '/r/MoviesThatFeelLike/comments/1w1t5y8/building_movies_like_dreed_type_big_building/', 'https://www.reddit.com/gallery/1w1t5y8', 'MoviesThatFeelLike', 'Gritty, adrenaline-fueled action sealed inside claustrophobic megastructures.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2942, '1w1ud48', 'Double identites and secrets', '', '', 'ziziJ123', 1788028836, '/r/MoviesThatFeelLike/comments/1w1ud48/double_identites_and_secrets/', 'https://www.reddit.com/gallery/1w1ud48', 'MoviesThatFeelLike', 'A collection of films featuring hidden identities and unfolding secrets, creating a suspenseful and intriguing atmosphere.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2943, '1w1v12k', 'Movies that feel like dreamcore with angel/heaven vibes', 'Movies that feel like dreamcore with angel/heaven vibes', '', 'Cotofvna', 1788030362, '/r/MoviesThatFeelLike/comments/1w1v12k/movies_that_feel_like_dreamcore_with_angelheaven/', 'https://www.reddit.com/gallery/1w1v12k', 'MoviesThatFeelLike', 'A dreamy and ethereal atmosphere blending surreal dreamcore visuals with angelic and heavenly themes.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2944, '1w1w650', 'Any movies that are like these pictures?', 'Any movies that are like these pictures?', '', 'Ultrakirby78', 1788033057, '/r/MoviesThatFeelLike/comments/1w1w650/any_movies_that_are_like_these_pictures/', 'https://www.reddit.com/gallery/1w1w650', 'MoviesThatFeelLike', 'A nostalgic dive into retro-futuristic sci-fi and surreal alien art with a touch of camp.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2945, '1w1x0r4', 'Movies that feel like growing up in a small rural town in the country?', 'Movies that feel like growing up in a small rural town in the country', '', 'Bluishr3d_', 1788035074, '/r/MoviesThatFeelLike/comments/1w1x0r4/movies_that_feel_like_growing_up_in_a_small_rural/', 'https://www.reddit.com/gallery/1w1x0r4', 'MoviesThatFeelLike', 'Nostalgic and evocative of small-town rural upbringing, blending heartfelt and gritty cinematic moments.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2946, '1w1xy9e', 'Movies that feel like goblin core', 'Movies that feel like goblin core', '', 'pretty_cuddle', 1788037309, '/r/MoviesThatFeelLike/comments/1w1xy9e/movies_that_feel_like_goblin_core/', 'https://www.reddit.com/gallery/1w1xy9e', 'MoviesThatFeelLike', 'Inquisitive search for rustic, whimsical fantasy films with goblin-core aesthetics.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2947, '1w1y1os', 'Movies for a cozy, romantic movie night', 'Movies for a cozy, romantic movie night', '', 'Amazing_Blonde9890', 1788037543, '/r/MoviesThatFeelLike/comments/1w1y1os/movies_for_a_cozy_romantic_movie_night/', 'https://www.reddit.com/gallery/1w1y1os', 'MoviesThatFeelLike', 'A warm, cozy, and romantic atmosphere perfect for a movie night.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2948, '1w1y3uu', 'A film that feels like an intense and beautiful love story, yet one that is doomed - Moulin Rouge (2001)', 'Moulin Rouge (2001)', '', 'f-california', 1788037688, '/r/MoviesThatFeelLike/comments/1w1y3uu/a_film_that_feels_like_an_intense_and_beautiful/', 'https://i.redd.it/ti9zias1qdmh1.jpeg', 'MoviesThatFeelLike', 'Intense and beautiful doomed love stories.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2949, '1w1y5i2', 'Films with highly saturated, unique colour palettes.', 'Films with highly saturated, unique colour palettes.', 'I''ve watched & loved Suspiria (1977 & 2018), Amelie (2001), Paris Texas (1984), Most Wong Kar-Wai films, Helter Skelter (2012) and most David Lynch films and I''m desperate for more films with super unique visuals and colours!', 'seven-saturns', 1788037801, '/r/MoviesThatFeelLike/comments/1w1y5i2/films_with_highly_saturated_unique_colour_palettes/', 'https://www.reddit.com/gallery/1w1y5i2', 'MoviesThatFeelLike', 'Enthusiastic community sharing of visually rich films with bold color palettes, creating a mood of artistic inspiration and cinematic discovery.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2950, '1w1yl1c', 'Movies that a have killer cheerleader', 'Movies that have killer cheerleader', '', 'Idek163', 1788038882, '/r/MoviesThatFeelLike/comments/1w1yl1c/movies_that_a_have_killer_cheerleader/', 'https://www.reddit.com/gallery/1w1yl1c', 'MoviesThatFeelLike', 'Dark and thrilling atmosphere centered on horror tropes involving killer cheerleaders.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2951, '1w1zsiu', 'Movies that feel like Fairytale', '', '', 'NegotiationMean3042', 1788041928, '/r/MoviesThatFeelLike/comments/1w1zsiu/movies_that_feel_like_fairytale/', 'https://www.reddit.com/gallery/1w1zsiu', 'MoviesThatFeelLike', 'A magical and enchanting atmosphere seeking movies with fairytale-like qualities.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2952, '1w1zyer', 'Movies that feel weird', '', '', 'cutie_pri', 1788042349, '/r/MoviesThatFeelLike/comments/1w1zyer/movies_that_feel_weird/', 'https://www.reddit.com/gallery/1w1zyer', 'MoviesThatFeelLike', 'A surreal and whimsical atmosphere of bizarre and haunting cinematic wonders.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2953, '1w20y6b', 'Looking for a Fantasy Series', '', 'I''ve watched merlin and GOT kinda along that vibe fantasy medieval knights magic dragons castles quests destiny fate', 'buffyxoxo', 1788044938, '/r/MoviesThatFeelLike/comments/1w20y6b/looking_for_a_fantasy_series/', 'https://www.reddit.com/gallery/1w20y6b', 'MoviesThatFeelLike', 'Epic medieval fantasy with elements of magic, destiny, and adventure.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2954, '1w210c2', 'Any film that has this kind of element?', 'Cosmic Horror Film Recommendations', 'Id love some kind of cosmic horror film like this', 'Daoyinyang1', 1788045094, '/r/MoviesThatFeelLike/comments/1w210c2/any_film_that_has_this_kind_of_element/', 'https://v.redd.it/2cynd7j2cemh1', 'MoviesThatFeelLike', 'A request for cosmic horror films that evoke a sense of mysterious awe and unsettling dread.', 'publishable', NULL, NULL, '2026-08-30 03:38:44', '2026-08-30 03:38:44');
