-- 0176_seed_20260831T034029Z_01_posts.sql: data seed from pipeline:load run.
-- Generated:  2026-08-31T03:40:49.170260+00:00
-- Run started: 2026-08-31T03:40:29.744056+00:00
-- Source: data/working/load manifest from this run.
--
-- Idempotent: every INSERT is INSERT OR IGNORE, keyed by the
-- table's natural unique constraint.  Wrangler's migration
-- tracking normally prevents re-apply; the OR IGNORE is
-- defense in depth for partial / interrupted re-runs.
--
-- Chunk: 01_posts (1/5)
-- Tables: imported_vibe_posts.
-- Pipeline-state tables (processing_runs, pipeline_artifacts)
-- are intentionally excluded — they're per-run bookkeeping.

INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2955, '1tr2d9p', 'Are there any more movies with the same revenge plot from Harakiri? Slow yet progressive.', 'Are there any more movies with the same revenge plot from Harakiri? Slow yet progressive.', '[deleted]', '[deleted]', 1780062303, '/r/MoviesThatFeelLike/comments/1tr2d9p/are_there_any_more_movies_with_the_same_revenge/', '', 'MoviesThatFeelLike', 'A viewer seeking deliberate, slowly-building revenge narratives with progressive tension, inspired by the contemplative pace of classic samurai cinema.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2956, '1tr2grl', 'Movies that have a similar revenge plot from Harakiri? Slow yet progressive.', 'Movies that have a similar revenge plot from Harakiri? Slow yet progressive.', '', 'Garidur', 1780062521, '/r/MoviesThatFeelLike/comments/1tr2grl/movies_that_have_a_similar_revenge_plot_from/', 'https://i.redd.it/gzjc3u4sz24h1.png', 'MoviesThatFeelLike', 'Seeking slow-burn revenge tales with psychological depth.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2957, '1tr33rf', 'Is there a movie that constantly shifts the "main character" role, or is this just a random, stupid idea of mine?', 'Is there a movie that constantly shifts the "main character" role, or is this just a random, stupid idea of mine?', '', 'andihriakjaarni', 1780063891, '/r/MoviesThatFeelLike/comments/1tr33rf/is_there_a_movie_that_constantly_shifts_the_main/', '/r/MovieSuggestions/comments/1tr3364/is_there_a_movie_that_constantly_shifts_the_main/', 'MoviesThatFeelLike', 'Inquisitive exploration of unconventional film narratives with shifting protagonists.', 'skipped', 'no usable images', NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2958, '1tr376l', 'Is there a movie that constantly shifts the "main character" role, or is this just a random, stupid idea of mine?', 'Movies with Shifting Main Characters', 'I’ve always imagined making a movie where the role of the main character constantly shifts.

Instead of focusing on just one protagonist, the story would give enough screen time and importance to at least 7 or 8 different characters. Just when one character starts to feel like the lead, the focus shifts to someone else entirely and leaves the previous person behind.

For example: Imagine watching a guy working an office job, living a normal life. We focus heavily on him for 30 minutes. Then, through a sudden or random transition, he passes a taxi driver on the street. The camera completely switches to the story of the taxi driver, turning the office worker into a background character and completely dropping his plot line from then on.

I hope you guys get what I''m saying. I''m not talking about a standard ensemble movie like *Magnolia* or *Pulp Fiction* where we keep jumping back and forth between a group of connected stories. I mean a literal "passing of the baton" where the narrative structure keeps moving forward linearly, but the protagonist role continuously drops old characters and picks up new ones.

I''ve seen *Chungking Express*, but that only does it once (switching between 2 distinct stories). I''m looking for something that does this 7 or 8 times in a row like a chain reaction.

Are there any movies out there based on this exact concept, or is this just a crazy formatting idea I came up with?', 'andihriakjaarni', 1780064089, '/r/MoviesThatFeelLike/comments/1tr376l/is_there_a_movie_that_constantly_shifts_the_main/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tr376l/is_there_a_movie_that_constantly_shifts_the_main/', 'MoviesThatFeelLike', 'A curious and collaborative discussion where users explore and recommend movies with innovative narrative structures that shift the main character role.', 'skipped', 'no usable images', NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2959, '1tr4ju9', 'Movie that feels like this?', 'Movie that feels like this?', '', 'cookie12685', 1780066863, '/r/MoviesThatFeelLike/comments/1tr4ju9/movie_that_feels_like_this/', 'https://i.redd.it/f5frssyoc34h1.jpeg', 'MoviesThatFeelLike', 'Eerie and ambiguous phone call mystery.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2960, '1tr5as1', 'Movies that feel like this.', 'Movies that feel like this.', '', 'BlueSM-012', 1780068312, '/r/MoviesThatFeelLike/comments/1tr5as1/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1tr5as1', 'MoviesThatFeelLike', 'A tense and gritty atmosphere evoking war zones, military operations, and intense action.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2961, '1tr9osi', 'i need a movie with this vibe', 'i need a movie with this vibe', '', 'koipoi1', 1780076816, '/r/MoviesThatFeelLike/comments/1tr9osi/i_need_a_movie_with_this_vibe/', 'https://www.reddit.com/gallery/1tr9osi', 'MoviesThatFeelLike', 'Dark, foreboding, and atmospheric horror with a sense of isolation and eerie calm.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2962, '1tra2r3', 'When life hit hard, what song or film actually got you — not distracted you, got you?', 'When life hit hard, what song or film actually got you — not distracted you, got you?', 'Not looking for recommendations.

Looking for something specific.

A phase in your life when things were genuinely hard. Not a bad day. A bad phase. Job loss, divorce, moving cities, feeling invisible, losing someone, feeling like everyone else is moving ahead and you''re standing still.

And in that phase — a song, a film, a concert, an artist that didn''t just distract you. It accompanied you. Like it knew exactly where you were.

What was the phase. What was the thing. What did it feel like to find it.

I''ll go first.

33 today. Feeling the weight of an unfulfilling job, a strained marriage, aging parents I don''t see enough, and a project I''ve been too afraid to ship.

Put on Fix You driving home last week. Cried properly for the first time in months. Felt less alone for exactly four minutes.

That feeling is what I''m building toward.

If this resonates — drop your phase and your song in the comments. Or DM me if you want to talk more.', 'Both-Weight3972', 1780077550, '/r/MoviesThatFeelLike/comments/1tra2r3/when_life_hit_hard_what_song_or_film_actually_got/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tra2r3/when_life_hit_hard_what_song_or_film_actually_got/', 'MoviesThatFeelLike', 'A somber reflection on personal hardships and the brief, cathartic solace found in music.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2963, '1trayql', 'High-society satires', 'High-society satires', '', 'surfsound_swimmers', 1780079209, '/r/MoviesThatFeelLike/comments/1trayql/highsociety_satires/', 'https://i.redd.it/0r6kq8ked44h1.jpeg', 'MoviesThatFeelLike', 'Satirical critique of high-society lifestyles through a discussion of movie recommendations.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2964, '1trbgvk', 'Movie/tv series that feel like', 'Movie/tv series that feel like', '[removed]', 'mutantoracle', 1780080177, '/r/MoviesThatFeelLike/comments/1trbgvk/movietv_series_that_feel_like/', 'https://www.reddit.com/gallery/1trbgvk', 'MoviesThatFeelLike', 'A mood-hunting request seeking visual or emotional parallels in film and television.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2965, '1trbmcx', 'Movies that feel like this?', 'Movies that feel like this', '[removed]', 'mutantoracle', 1780080471, '/r/MoviesThatFeelLike/comments/1trbmcx/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1trbmcx', 'MoviesThatFeelLike', 'A user seeking movies that match a particular mood or aesthetic, but the original context is lost.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2966, '1trc9j5', 'Movies that feel like this?', 'Movies that feel like this?', '[removed]', 'mutantoracle', 1780081660, '/r/MoviesThatFeelLike/comments/1trc9j5/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1trc9j5', 'MoviesThatFeelLike', 'The post conveys a curious search for films that evoke a specific, unstated mood.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2967, '1trfyi6', 'Chill and jazzy', 'Chill and jazzy', '', 'HelpIntelligent6830', 1780089440, '/r/MoviesThatFeelLike/comments/1trfyi6/chill_and_jazzy/', 'https://www.reddit.com/gallery/1trfyi6', 'MoviesThatFeelLike', 'A dreamy, liminal melancholy — like wandering through half-remembered architectural spaces from a jazz-scored film, simultaneously cozy and eerily unfamiliar.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2968, '1trgmyj', 'Hi! Looking for someone who want to verify a memory challenge!', '', 'Yeah so that''s that, also the pillar IS actually there LOL 

There''ll be cube, UFO and wave gp.

If you want to verify, tell me ;) ''D', 'Kylobopiaps_Irirri', 1780090977, '/r/MoviesThatFeelLike/comments/1trgmyj/hi_looking_for_someone_who_want_to_verify_a/', 'https://i.redd.it/nehgfh18c54h1.jpeg', 'MoviesThatFeelLike', 'A playful, game-oriented memory challenge atmosphere with whimsical elements.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2969, '1trh9ku', 'A fantasy film centered on the sun and the moon.', 'A fantasy film centered on the sun and the moon.', '', 'Cold-Bed498', 1780092453, '/r/MoviesThatFeelLike/comments/1trh9ku/a_fantasy_film_centered_on_the_sun_and_the_moon/', 'https://www.reddit.com/gallery/1trh9ku', 'MoviesThatFeelLike', 'A whimsical, celestial longing for mythic fantasy where sun and moon imagery evoke wonder and dreamlike magic.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2970, '1trjdcn', 'Movies that feel like how this song sounds', 'Movies That Feel Like How This Song Sounds', 'Blissful, hopeful, gradual change, etc. Although you can interpret the feeling of this song however you wish.', 'throu1away', 1780097633, '/r/MoviesThatFeelLike/comments/1trjdcn/movies_that_feel_like_how_this_song_sounds/', 'https://i.redd.it/icl3qbx6w54h1.jpeg', 'MoviesThatFeelLike', 'Blissful, hopeful, and evoking a sense of gradual change.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2971, '1trkkd2', 'Help me with a movie?', 'Help me with a movie?', 'There''s a French film I''m looking for, but I can''t find it anywhere online. It''s called "Tout ce qui brille" (All That Glitters), and it''s from 2010. Does anyone know where I can watch it online? Thanks in advance.', 'WebSame6288', 1780100718, '/r/MoviesThatFeelLike/comments/1trkkd2/help_me_with_a_movie/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1trkkd2/help_me_with_a_movie/', 'MoviesThatFeelLike', 'Helpful community discussion about locating an obscure French film with a touch of nostalgia for lost media.', 'skipped', 'no usable images', NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2972, '1trno54', 'movies that feel like an italian summer?', 'movies that feel like an italian summer', '', 'Smexy-bimbo0606', 1780109358, '/r/MoviesThatFeelLike/comments/1trno54/movies_that_feel_like_an_italian_summer/', 'https://www.reddit.com/gallery/1trno54', 'MoviesThatFeelLike', 'Evokes sun-drenched Italian landscapes, romantic encounters, and leisurely summer days filled with beauty and nostalgia.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2973, '1trqpcz', 'Movies that feel like this', 'Movies that feel like 2000s era retrofuturism and design styles.', '2000s era retrofuturism and design styles of the time. ', 'DiamondBreakr', 1780118411, '/r/MoviesThatFeelLike/comments/1trqpcz/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1trqpcz', 'MoviesThatFeelLike', 'A nostalgic, cheesy Y2K retrofuturistic atmosphere with playful sci-fi elements.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2974, '1trvqyc', 'Movies that feel like', '', '', 'Tricky_cielito00', 1780135233, '/r/MoviesThatFeelLike/comments/1trvqyc/movies_that_feel_like/', 'https://www.reddit.com/gallery/1trvqyc', 'MoviesThatFeelLike', 'Sophisticated atmosphere with themes of luxury, suspense, and intrigue.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2975, '1trweau', 'Homoerotic hair-contrast.', 'Homoerotic hair-contrast.', 'So, I noticed this funny trend in LGBTQ+ media, where, if two characters of the same gender happen to have a romantic relationship/a relationship with queer subtext, they tend to have contrasting hair colours.

Usually, it’s a shade of blond contrasted with brunet (brown or black hair). But there are plenty of variations – including dark blonds, dyed blonds, and even a \*\*redhead\*\* in black and white.

Note that the characters don’t HAVE to be a canon couple at all. At least one of my examples is one-sided, and another has, I''m pretty sure, been confirmed as platonic. 

Basically, the only qualifier is that their relationship is at least somewhat \*readable\* as queer-coded, regardless of the director''s intent.

I''m curious as to whether anyone can think of any other examples.', 'MoonlightDahling', 1780137401, '/r/MoviesThatFeelLike/comments/1trweau/homoerotic_haircontrast/', 'https://www.reddit.com/gallery/1trweau', 'MoviesThatFeelLike', 'Curious and analytical inquiry into visual tropes in LGBTQ+ media.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2976, '1trwedj', 'Homoerotic hair-contrast.', 'Homoerotic hair-contrast', 'So, I noticed this funny trend in LGBTQ+ media, where, if two characters of the same gender happen to have a romantic relationship/a relationship with queer subtext, they tend to have contrasting hair colours.

Usually, it’s a shade of blond contrasted with brunet (brown or black hair). But there are plenty of variations – including dark blonds, dyed blonds, and even a \*\*redhead\*\* in black and white.

Note that the characters don’t HAVE to be a canon couple at all. At least one of my examples is one-sided, and another has, I''m pretty sure, been confirmed as platonic. 

Basically, the only qualifier is that their relationship is at least somewhat \*readable\* as queer-coded, regardless of the director''s intent.

I''m curious as to whether anyone can think of any other examples.', 'MoonlightDahling', 1780137408, '/r/MoviesThatFeelLike/comments/1trwedj/homoerotic_haircontrast/', 'https://www.reddit.com/gallery/1trwedj', 'MoviesThatFeelLike', 'An analytical and playful celebration of a recurring visual trope in queer media—contrasting hair colors signaling romantic tension—sparking enthusiastic crowd-sourced cataloguing of examples.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2977, '1ts1iy1', 'movies that feel like this', 'movies about filmmaking, movie sets, and Hollywood studio lots', 'in other words, i’m looking for movies where the story actually takes place on movie sets, or is about making movies, or is set on hollywood studio lots, or anything in that direction… welcoming suggestion for any genre, tv shows also welcome

I know about movies like La La Land and Babylon, or shows like The Studio - that’s exactly the kind of vibe I like, but I’m open to anything else that you’d think would fit this!', 'gingeraleguzzler26', 1780151474, '/r/MoviesThatFeelLike/comments/1ts1iy1/movies_that_feel_like_this/', 'https://v.redd.it/9mxvknb9ca4h1', 'MoviesThatFeelLike', 'A nostalgic, enthusiastic celebration of Hollywood self-referentiality — movies about the magic and madness of filmmaking, from golden-age glamour to behind-the-scenes chaos.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2978, '1ts3foh', 'Movies that feel like this? (pool disco party and stuff like that)', '', '', 'Tenebrae_Hunter', 1780156026, '/r/MoviesThatFeelLike/comments/1ts3foh/movies_that_feel_like_this_pool_disco_party_and/', 'https://i.redd.it/27tgs0sspa4h1.jpeg', 'MoviesThatFeelLike', 'Energetic and nostalgic pool party atmosphere with disco vibes and wild, celebratory energy.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2979, '1ts3tu0', 'Movies with this vibes.', 'Movies with this vibes.', '', 'BlueSM-012', 1780156967, '/r/MoviesThatFeelLike/comments/1ts3tu0/movies_with_this_vibes/', 'https://www.reddit.com/gallery/1ts3tu0', 'MoviesThatFeelLike', 'Intense, gritty military and war atmosphere with smoky, desaturated imagery evoking exhaustion, isolation, and the somber weight of combat.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2980, '1ts4rt2', 'Neon lights (Japan is a bonus)', '', '', 'AmbitionLegal566', 1780159244, '/r/MoviesThatFeelLike/comments/1ts4rt2/neon_lights_japan_is_a_bonus/', 'https://www.reddit.com/gallery/1ts4rt2', 'MoviesThatFeelLike', 'A vibrant, urban night aesthetic seeking neon-lit atmosphere, with an optional Japanese setting as an extra treat.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2981, '1ts65lr', 'Movies that feel like a late night at the Waffle House', 'Movies that feel like a late night at the Waffle House', '', 'smoothpaving', 1780162447, '/r/MoviesThatFeelLike/comments/1ts65lr/movies_that_feel_like_a_late_night_at_the_waffle/', 'https://i.redd.it/lq1lfwxw8b4h1.jpeg', 'MoviesThatFeelLike', 'A late-night, gritty, and eclectic mix of films capturing the chaotic and intimate vibe of a Waffle House after dark.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2982, '1ts8kqc', 'Self made millionaire women', 'Self Made Millionaire Women', 'Boss lady ', 'Brief-Ship-5572', 1780168190, '/r/MoviesThatFeelLike/comments/1ts8kqc/self_made_millionaire_women/', 'https://www.reddit.com/gallery/1ts8kqc', 'MoviesThatFeelLike', 'Aspirational boss-lady energy featuring wealthy, glamorous, powerful women navigating high-stakes worlds with style and ambition.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2983, '1tsarbo', 'Vampire/Gothic Western', 'Vampire/Gothic Western', '', 'ChungusLovr', 1780173327, '/r/MoviesThatFeelLike/comments/1tsarbo/vampiregothic_western/', 'https://www.reddit.com/gallery/1tsarbo', 'MoviesThatFeelLike', 'Dark, atmospheric fusion of gothic horror and western frontier with vampires.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2984, '1tsb9p9', 'Horror movies about heaven', 'Horror movies about heaven', '', 'UnlikelyTwo7070', 1780174573, '/r/MoviesThatFeelLike/comments/1tsb9p9/horror_movies_about_heaven/', 'https://i.redd.it/f01uia2z8c4h1.png', 'MoviesThatFeelLike', 'Darkly curious exploration of the intersection between the divine and the horrifying, with a playful undercurrent of surreal humor.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2985, '1tsbzmn', 'Movies that feel like the photos I took of my drunk friend at a festival in 2011', 'Movies that feel like the photos I took of my drunk friend at a festival in 2011', '', 'citabel', 1780176305, '/r/MoviesThatFeelLike/comments/1tsbzmn/movies_that_feel_like_the_photos_i_took_of_my/', 'https://www.reddit.com/gallery/1tsbzmn', 'MoviesThatFeelLike', 'Chaotic and nostalgic festival vibes with a mix of humor and heartfelt moments.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2986, '1tse3hd', 'Industrial Horror/Retro Liminality', 'Industrial Horror/Retro Liminality', '', 'Technical_Mouse_6365', 1780181665, '/r/MoviesThatFeelLike/comments/1tse3hd/industrial_horrorretro_liminality/', 'https://www.reddit.com/gallery/1tse3hd', 'MoviesThatFeelLike', 'Dark, oppressive industrial atmospheres blending retro-futuristic decay with liminal, unsettling urban spaces that feel both nostalgic and menacing.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2987, '1tsehus', 'Stark Depictions of the Human Body', 'Stark Depictions of the Human Body', 'Looking for films the emphasize the human body in unique contexts ', 'Technical_Mouse_6365', 1780182714, '/r/MoviesThatFeelLike/comments/1tsehus/stark_depictions_of_the_human_body/', 'https://www.reddit.com/gallery/1tsehus', 'MoviesThatFeelLike', 'An intense, visceral exploration of the human body pushed to its extremes—through pain, transformation, physicality, and the grotesque.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2988, '1tsf13g', 'How about this?', '', '', 'Sea-Comedian-4376', 1780184122, '/r/MoviesThatFeelLike/comments/1tsf13g/how_about_this/', 'https://www.reddit.com/gallery/1tsf13g', 'MoviesThatFeelLike', 'A nostalgic and casual exchange of movie recommendations, evoking a sense of cool and action-packed nostalgia.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2989, '1tsfhvo', '2000’s yoga mom', '2000s yoga mom', '', 'the_secret_mermaid_', 1780185404, '/r/MoviesThatFeelLike/comments/1tsfhvo/2000s_yoga_mom/', 'https://www.reddit.com/gallery/1tsfhvo', 'MoviesThatFeelLike', 'A nostalgic glimpse into 2000s suburban mom culture with yoga, activewear, and wellness themes.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2990, '1tsgl0f', 'Movies that look like this', '', 'I just finished Joyland and those lights-off glittery scenes are still replaying in my mind. I need more!! I don’t have any interest in Euphoria the tv show, but other tv shows welcome. TIA! ', 'mellycinderelly', 1780188427, '/r/MoviesThatFeelLike/comments/1tsgl0f/movies_that_look_like_this/', 'https://www.reddit.com/gallery/1tsgl0f', 'MoviesThatFeelLike', 'A yearning for visually immersive, neon-drenched, emotionally resonant cinema with glittery, dark-lit aesthetics.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2991, '1tshge9', 'Movies/TV shows with similar vibe', 'Movies/TV shows with similar vibe', '', 'CommonWar7535', 1780190957, '/r/MoviesThatFeelLike/comments/1tshge9/moviestv_shows_with_similar_vibe/', 'https://i.redd.it/5x623oxold4h1.jpeg', 'MoviesThatFeelLike', 'A dark, atmospheric mood with shadowy armies and sci-fi action undertones.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2992, '1tshgkk', 'Movies/TV shows with a similar vibe of this image', '', '', 'CommonWar7535', 1780190972, '/r/MoviesThatFeelLike/comments/1tshgkk/moviestv_shows_with_a_similar_vibe_of_this_image/', 'https://i.redd.it/sbcmlanqld4h1.jpeg', 'MoviesThatFeelLike', 'A dark and fantastical mood with mythical and supernatural undertones.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2993, '1tshxv4', 'Movies that feel like a Minecraft sunset', 'Movies that feel like a Minecraft sunset', '', 'Double_Concentrate_4', 1780192362, '/r/MoviesThatFeelLike/comments/1tshxv4/movies_that_feel_like_a_minecraft_sunset/', 'https://www.reddit.com/gallery/1tshxv4', 'MoviesThatFeelLike', 'Seeking warm, nostalgic, and dreamy media that captures the peaceful golden-hour glow and quiet contemplation of watching a Minecraft sunset.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2994, '1tsj5yn', 'Slasher/Giallo films with a vampire-like feel', '', '', 'OkCase3935', 1780195934, '/r/MoviesThatFeelLike/comments/1tsj5yn/slashergiallo_films_with_a_vampirelike_feel/', 'https://www.reddit.com/gallery/1tsj5yn', 'MoviesThatFeelLike', 'A dark, atmospheric pursuit of slasher and giallo films with vampire-like undertones.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2995, '1tsl4kn', 'older horror movies that feel like this', '', 'I finished reading Frankenstein for the first time a little while ago and this vibe has been stuck in my head. I need to see it realized. I’ve already seen The Lighthouse, it’s a jump in the right direction. ', 'fearful-flyer', 1780201640, '/r/MoviesThatFeelLike/comments/1tsl4kn/older_horror_movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1tsl4kn', 'MoviesThatFeelLike', 'A gothic and eerie atmosphere inspired by classic literature and vintage horror films.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2996, '1tsmo80', 'Haunted woods or nature', '', 'My roommate loves haunted woods movies like Blair Witch & The Ritual. 

What are some other good ones to check out? ', 'russbuss1123', 1780206489, '/r/MoviesThatFeelLike/comments/1tsmo80/haunted_woods_or_nature/', 'https://www.reddit.com/gallery/1tsmo80', 'MoviesThatFeelLike', 'Eerie forest horror with atmospheric dread and supernatural elements.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2997, '1tsoz2z', 'A film with this kind of coziness?', 'A film with this kind of coziness?', '', 'chiakinanamichan', 1780214219, '/r/MoviesThatFeelLike/comments/1tsoz2z/a_film_with_this_kind_of_coziness/', 'https://www.reddit.com/gallery/1tsoz2z', 'MoviesThatFeelLike', 'A subjective and nostalgic search for cozy urban atmospheres, with some viewers finding warmth in childhood memories while others perceive cold sterility.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2998, '1tspq66', 'Movies that visually explores envy and competitiveness between women', 'Movies that visually explores envy and competitiveness between women', 'Criminally underexplored genre. There''s no healthy representation of jealousy in itself regardless of gender as the protagonist is someone you need to root for. However, I find it an extremely interesting topic when it''s done well, especially against women. ', 'TypicalCartoonist555', 1780216802, '/r/MoviesThatFeelLike/comments/1tspq66/movies_that_visually_explores_envy_and/', 'https://www.reddit.com/gallery/1tspq66', 'MoviesThatFeelLike', 'A dark and intense exploration of female rivalry and jealousy through visually striking films.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (2999, '1tsqms0', 'Films with this vibe', '', '', 'Galaxybluuu', 1780219984, '/r/MoviesThatFeelLike/comments/1tsqms0/films_with_this_vibe/', 'https://www.reddit.com/gallery/1tsqms0', 'MoviesThatFeelLike', 'Dark and intense cinematic experiences with themes of survival and existential dread.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3000, '1tsqnnf', 'Movies that feel like Vietnam War', '', 'US Vietnam confllict or First Indochina War

I''ll start

First Kill 2001

To the Ends of The World 2018', 'bad_grief', 1780220067, '/r/MoviesThatFeelLike/comments/1tsqnnf/movies_that_feel_like_vietnam_war/', 'https://www.reddit.com/gallery/1tsqnnf', 'MoviesThatFeelLike', 'Gritty and intense war atmosphere evoking the Vietnam conflict.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3001, '1tsrul7', 'Movies that feel like two guys are about to kiss the whole time but dont', 'Movies that feel like two guys are about to kiss the whole time but dont', 'Examples of movies I''ve watched:

Trains, planes, and automobiles

Happy gilmore

The road to el dorado

The emporers new groove

Project hail Mary

Tommy boy', 'Galaxybluuu', 1780224106, '/r/MoviesThatFeelLike/comments/1tsrul7/movies_that_feel_like_two_guys_are_about_to_kiss/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tsrul7/movies_that_feel_like_two_guys_are_about_to_kiss/', 'MoviesThatFeelLike', 'Playful and humorous discussion of unspoken bromance and romantic tension in buddy movies.', 'skipped', 'no usable images', NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3002, '1tsuw8u', 'Movies that feel like this?', 'Movies that feel like this?', '', 'Current-Topic6696', 1780232836, '/r/MoviesThatFeelLike/comments/1tsuw8u/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1tsuw8u', 'MoviesThatFeelLike', 'A moody, neon-drenched urban night atmosphere with strong visual aesthetics.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3003, '1tsxbn2', 'Understood obsession after returning home?', 'Understood obsession after returning home?', '', 'Outside_Mind_6640', 1780238841, '/r/MoviesThatFeelLike/comments/1tsxbn2/understood_obsession_after_returning_home/', '/r/moviecritic/comments/1tsx46u/understood_obsession_after_returning_home/', 'MoviesThatFeelLike', 'A reflective moment where life feels like a cinematic plot twist, evoking obsession and realization after returning home.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3004, '1w1ov5j', 'Movies that feel like a slow summer', 'Movies that feel like a slow summer', 'i feel like i’m looking for something like call me by your name but in aesthetic alone ', 'hoogusboogus321', 1788015803, '/r/MoviesThatFeelLike/comments/1w1ov5j/movies_that_feel_like_a_slow_summer/', 'https://www.reddit.com/gallery/1w1ov5j', 'MoviesThatFeelLike', 'A hazy, sun-drenched longing for unhurried summer days filled with quiet beauty, ripe fruit trees, and Mediterranean stillness.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3005, '1w1z6y0', 'Movies that feel like Caribbean pirate life', 'Movies That Feel Like Caribbean Pirate Life', 'Guys, please don’t recommend the pirates of Caribbean!!!', 'S3XY_mis', 1788040417, '/r/MoviesThatFeelLike/comments/1w1z6y0/movies_that_feel_like_caribbean_pirate_life/', 'https://www.reddit.com/gallery/1w1z6y0', 'MoviesThatFeelLike', 'Seeking adventurous and historical nautical tales beyond the mainstream pirate franchise.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3006, '1w2491a', 'Live action movies that fit these pictures.', '', '', 'Ultrakirby78', 1788054048, '/r/MoviesThatFeelLike/comments/1w2491a/live_action_movies_that_fit_these_pictures/', 'https://www.reddit.com/gallery/1w2491a', 'MoviesThatFeelLike', 'A gritty cyberpunk atmosphere filled with robotic futures and action-packed sci-fi elements.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3007, '1w24cqq', 'movies that feature kudzu or a heavy forest?', 'movies featuring kudzu or heavy forest', '', 'KeyElephant4589', 1788054352, '/r/MoviesThatFeelLike/comments/1w24cqq/movies_that_feature_kudzu_or_a_heavy_forest/', 'https://www.reddit.com/gallery/1w24cqq', 'MoviesThatFeelLike', 'Movies evoking dense, overgrown forest settings with an eerie or immersive atmosphere.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3008, '1w24w7t', 'Movies TV shows with a similar vibes to the song cigarette duets by Princess Chelsea', 'Movies and TV shows with similar vibes to ''Cigarette Duets'' by Princess Chelsea', '', 'CommonWar7535', 1788055936, '/r/MoviesThatFeelLike/comments/1w24w7t/movies_tv_shows_with_a_similar_vibes_to_the_song/', 'https://www.reddit.com/gallery/1w24w7t', 'MoviesThatFeelLike', 'A whimsical yet melancholic atmosphere with quirky, offbeat charm.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3009, '1w252ua', 'People trapped in a Dark Old House. Murder, mayhem and expressionism', 'People trapped in a Dark Old House. Murder, mayhem and expressionism', 'Could be modern or vintage but in the style of the 1930s/20s', 'save-me-from-sharon', 1788056489, '/r/MoviesThatFeelLike/comments/1w252ua/people_trapped_in_a_dark_old_house_murder_mayhem/', 'https://www.reddit.com/gallery/1w252ua', 'MoviesThatFeelLike', 'A tense and eerie atmosphere evoking classic haunted house thrillers with expressionist undertones.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3010, '1w25epf', 'Nothing supernatural', 'Nothing supernatural', '', 'LeonardoKlotzFTomaz', 1788057500, '/r/MoviesThatFeelLike/comments/1w25epf/nothing_supernatural/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1w25epf/nothing_supernatural/', 'MoviesThatFeelLike', 'A focus on realistic, non-supernatural themes with a direct emphasis on mundane aspects.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3011, '1w25glq', 'Movies that are not exactly supernatural. But feels like it', 'Movies that are not exactly supernatural. But feels like it', '', 'LeonardoKlotzFTomaz', 1788057664, '/r/MoviesThatFeelLike/comments/1w25glq/movies_that_are_not_exactly_supernatural_but/', 'https://i.redd.it/5ovc8veedfmh1.jpeg', 'MoviesThatFeelLike', 'A sense of uncanny ambiguity where psychological tension blurs with unexplained phenomena.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3012, '1w25i3q', 'Movies that despise having a few musical numbers, are not exactly considered musicals', '', '', 'LeonardoKlotzFTomaz', 1788057787, '/r/MoviesThatFeelLike/comments/1w25i3q/movies_that_despise_having_a_few_musical_numbers/', 'https://i.redd.it/64vrhzosdfmh1.jpeg', 'MoviesThatFeelLike', 'A discussion about movies that include musical numbers or singing scenes but are not traditional musicals, often blending genres like fantasy and drama.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3013, '1w25vu4', 'Movies that are not Christmas movies, but still has some allusions to the event or its characters', 'Movies that are not Christmas movies, but still has some allusions to the event or its characters', '', 'LeonardoKlotzFTomaz', 1788058930, '/r/MoviesThatFeelLike/comments/1w25vu4/movies_that_are_not_christmas_movies_but_still/', 'https://www.reddit.com/gallery/1w25vu4', 'MoviesThatFeelLike', 'A community-driven list of films that subtly incorporate Christmas themes without being traditional holiday movies.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3014, '1w269ba', 'Movies that are not sci-fi, even though it carries some of its elements. (Dystopians do not count)', 'Movies that are not sci-fi, even though it carries some of its elements. (Dystopians do not count)', '', 'LeonardoKlotzFTomaz', 1788060065, '/r/MoviesThatFeelLike/comments/1w269ba/movies_that_are_not_scifi_even_though_it_carries/', 'https://i.redd.it/1pi5sv5hkfmh1.jpeg', 'MoviesThatFeelLike', 'A curious and debate-filled exploration of genre-blending films with subtle sci-fi elements.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3015, '1w26kxd', 'Superhero movies that can''t actually be considered superhero movies', 'Superhero movies that can''t actually be considered superhero movies', '', 'LeonardoKlotzFTomaz', 1788061037, '/r/MoviesThatFeelLike/comments/1w26kxd/superhero_movies_that_cant_actually_be_considered/', 'https://www.reddit.com/gallery/1w26kxd', 'MoviesThatFeelLike', 'A debate-driven discussion analyzing genre boundaries in superhero cinema, filled with examples and differing opinions.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3016, '1w26o7a', 'Movies That Feel Like Analog Horror', 'Movies That Feel Like Analog Horror', '', 'Formal-Ostrich-5404', 1788061320, '/r/MoviesThatFeelLike/comments/1w26o7a/movies_that_feel_like_analog_horror/', 'https://www.reddit.com/gallery/1w26o7a', 'MoviesThatFeelLike', 'Creeping dread through degraded footage, liminal static, and the sickening wrongness of old media playing things it shouldn''t.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3017, '1w26xze', 'Movies that are not Christmas movies, and do NOT take place around Christmas, but still has some allusions to the event and its traditions', 'Movies that are not Christmas movies, and do NOT take place around Christmas, but still has some allusions to the event and its traditions', '', 'LeonardoKlotzFTomaz', 1788062176, '/r/MoviesThatFeelLike/comments/1w26xze/movies_that_are_not_christmas_movies_and_do_not/', 'https://www.reddit.com/gallery/1w26xze', 'MoviesThatFeelLike', 'A targeted discussion seeking films with subtle Christmas references, avoiding traditional holiday movies.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3018, '1w2764t', 'Movies that are not fantasy, but still carries some elements of the genre', 'Movies that are not fantasy but still carry some elements of the genre', '', 'LeonardoKlotzFTomaz', 1788062855, '/r/MoviesThatFeelLike/comments/1w2764t/movies_that_are_not_fantasy_but_still_carries/', 'https://www.reddit.com/gallery/1w2764t', 'MoviesThatFeelLike', 'Whimsical and subtly magical, blending fantasy elements with reality in a low-fantasy or magical realism style.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3019, '1w27bv4', 'Movies that leave ambiguous whether or not the story takes place in a post-apocalyptic setting', 'Movies that leave ambiguous whether or not the story takes place in a post-apocalyptic setting', '', 'LeonardoKlotzFTomaz', 1788063357, '/r/MoviesThatFeelLike/comments/1w27bv4/movies_that_leave_ambiguous_whether_or_not_the/', 'https://i.redd.it/zwogjqkbufmh1.jpeg', 'MoviesThatFeelLike', 'Mysterious and ambiguous atmospheric setting.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3020, '1w27l9f', 'Santa Claus is a humanoid monster, and his little workshop is actually a cave filled with working monsters', 'Santa Claus is a humanoid monster, and his little workshop is actually a cave filled with working monsters', '', 'LeonardoKlotzFTomaz', 1788064169, '/r/MoviesThatFeelLike/comments/1w27l9f/santa_claus_is_a_humanoid_monster_and_his_little/', 'https://i.redd.it/1x2ueyfiwfmh1.jpeg', 'MoviesThatFeelLike', 'A dark, monstrous reimagining of Santa Claus as a cave-dwelling humanoid with an army of working creatures, evoking horror-tinged holiday fantasy.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3021, '1w27pgf', 'Movies/ TV shows that are like NBA 2K16?', 'Movies/TV shows like NBA 2K16', 'I know this is a sports game but Spike Lee directed the story for 2K that year. He even had his name on the cover. The story was named livin da dream and the cutscenes felt like a movie. The story even had a very serious and emotional cutscene where your myplayer loses his best friend in a car crash. This was also the last time 2K had a realistic written story with no cringe characters. I''d say it''s the 2nd game to have a movie-like storyline other than fight night champion. I still can''t believe it was made by Spike Lee the same guy behind classics such as Do The Right Thing, Malcolm X, Crooklyn, Clockers, He Got Game and many more. He also came out with Chiraq only just a few months after the game dropped and used a few actors that were in 2K that same year.', 'naydenthegreatone', 1788064535, '/r/MoviesThatFeelLike/comments/1w27pgf/movies_tv_shows_that_are_like_nba_2k16/', 'https://i.redd.it/e09lkxmvxfmh1.jpeg', 'MoviesThatFeelLike', 'Nostalgic appreciation for emotionally grounded, realistic sports storytelling that blurs the line between video game narrative and cinema.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3022, '1w27ruv', 'Movies that try to be transcendental', 'Movies that try to be transcendental', '', 'LeonardoKlotzFTomaz', 1788064743, '/r/MoviesThatFeelLike/comments/1w27ruv/movies_that_try_to_be_transcendental/', 'https://i.redd.it/9kdf2mreyfmh1.jpeg', 'MoviesThatFeelLike', 'A contemplative search for cinema that reaches beyond the material world into spiritual, philosophical, and metaphysical depths.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3023, '1w28gnf', '“Me and bro in a serious situation” movies?', 'Me and bro in a serious situation movies', '', 'Better-Ad-592', 1788066923, '/r/MoviesThatFeelLike/comments/1w28gnf/me_and_bro_in_a_serious_situation_movies/', 'https://www.reddit.com/gallery/1w28gnf', 'MoviesThatFeelLike', 'Casual camaraderie in tense situations, blending humor and suspense among friends.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3024, '1w28wi4', 'MOVIE ENTHUSIASTS: HELP ME', 'Movie Enthusiasts Help Me', 'Hi guys!! Thanks for being here. I’m looking for a list of movies and tv shows that emulate a specific vibe that I’m going for. I’m not too knowledgeable about the art of cinematography, so I was hoping ppl on here could help me out. 

So what am I looking for?

I essentially want to find work that is similar to The Wonderful Story of Henry Sugar and Six More and The Grand Budapest Hotel and A Series of Unfortunate Events. 

That’s not all too helpful, so here are the features that stuck out to me:

Overall, I like the vibe that Wes Anderson presents. I like that the characters feel a little detached from the setting. Like in the first two movies I mentioned, I enjoy that the whole movie feels like a set. I like that it will cut to a scene and you can focus on the character for a bit, but you also can’t help but look at the background. 

I like the color vibrancy and the modern/contemporary style. If possible, I would want movies/shows made within the last 5-10 years. 20 would be the max. I especially like Henry Sugar because there are so many unique settings, with just enough detail, and there are elements of architecture. I know Wes Anderson has a few movies with this same pop-up movie feel, but they take place outside. If possible, I’d want a majority of the scenes to take place either right in front of a building or indoors. 

Something I also appreciate about all three is that the camera doesn’t do crazy zoom ins or weird angles. I like that the camera stays a distance away from the characters, which allows each element to kind of have a voice of its own. I hope that makes sense. 

Also, I want the movie to be in English or at least have an English version. ', 'Pale-Squirrel-403', 1788068315, '/r/MoviesThatFeelLike/comments/1w28wi4/movie_enthusiasts_help_me/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1w28wi4/movie_enthusiasts_help_me/', 'MoviesThatFeelLike', 'Whimsical and meticulously crafted with vibrant colors and quirky, detached characters in set-like environments.', 'skipped', 'no usable images', NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3025, '1w2c7jv', 'romantic movie with sad Ending like', 'Romantic Movie with Sad Ending', '', 'Sweaty_Maize771', 1788079637, '/r/MoviesThatFeelLike/comments/1w2c7jv/romantic_movie_with_sad_ending_like/', '/r/romancemovies/comments/1w2c6q4/romantic_movie_with_sad_ending/', 'MoviesThatFeelLike', 'A melancholic search for romantic movies with tragic endings.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3026, '1w2d36v', 'Looking for a Royal Fantasy movie or series', '', 'Can anyone suggest a good web series  or movie where there is a King and Queen with several sons, but one son is completely different from the others? He doesn''t want the throne and only wants peace, but in the end, he becomes the King.', 'Extreme_Avocado_2473', 1788082684, '/r/MoviesThatFeelLike/comments/1w2d36v/looking_for_a_royal_fantasy_movie_or_series/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1w2d36v/looking_for_a_royal_fantasy_movie_or_series/', 'MoviesThatFeelLike', 'A curious and longing search for epic royal fantasy narratives with themes of reluctant leadership and familial destiny.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3027, '1w2dyi9', 'Movies that feel like being rich', 'movies that feel like being rich', '', 'ziziJ123', 1788085642, '/r/MoviesThatFeelLike/comments/1w2dyi9/movies_that_feel_like_being_rich/', 'https://www.reddit.com/gallery/1w2dyi9', 'MoviesThatFeelLike', 'An atmosphere of opulent luxury, high-society glamour, and aspirational wealth.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3028, '1w2fv7m', 'Movies that feel like this? Horror movies please and thank you.', 'Movies that feel like this? Horror movies please and thank you.', 'This is just a TikTok, but it looks so spooky to me. Just saw the void two days ago and have been wanting to watch another amazing horror.', 'peace-harmonymoon', 1788091711, '/r/MoviesThatFeelLike/comments/1w2fv7m/movies_that_feel_like_this_horror_movies_please/', 'https://v.redd.it/pdbegpbe6imh1', 'MoviesThatFeelLike', 'Dark, stormy, and eerily medieval horror atmosphere evoking knights and supernatural dread.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3029, '1w2fxbb', 'Movies that feel like this?', '', 'Horror movies please and thank you! ', 'peace-harmonymoon', 1788091880, '/r/MoviesThatFeelLike/comments/1w2fxbb/movies_that_feel_like_this/', 'https://v.redd.it/sl70m4n47imh1', 'MoviesThatFeelLike', 'Eerie, folk-horror atmosphere with supernatural temptation and dark fairy tale elements.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3030, '1w2fxi9', 'Movies that capture that innocent feeling we had when we were younger (also adult), gazing up at the sky in the countryside, with a sense of vastness.', '', '', 'KeepYourWildHeart', 1788091895, '/r/MoviesThatFeelLike/comments/1w2fxi9/movies_that_capture_that_innocent_feeling_we_had/', 'https://www.reddit.com/gallery/1w2fxi9', 'MoviesThatFeelLike', 'Nostalgic and expansive, evoking childhood wonder under vast countryside skies.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3031, '1w2g22y', 'The road 2009 type flim', 'The Road 2009 type film', 'Dreed I have watched destopian that is underrated and lost in time of content', 'AmanYadav19', 1788092267, '/r/MoviesThatFeelLike/comments/1w2g22y/the_road_2009_type_flim/', 'https://i.redd.it/m00z3nd88imh1.png', 'MoviesThatFeelLike', 'A somber search for underrated post-apocalyptic survival stories akin to The Road.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3032, '1w2h3vu', 'Retrofuturism', 'Retrofuturism', 'I want to see optimistic technology, even if it’s impractical and naive. We got the opposite, and it thoroughly bums me out, so I need to live vicariously through the movies? ', 'SnailCooper_', 1788095225, '/r/MoviesThatFeelLike/comments/1w2h3vu/retrofuturism/', 'https://www.reddit.com/gallery/1w2h3vu', 'MoviesThatFeelLike', 'A yearning for the optimistic, starry-eyed vision of the future that mid-century sci-fi promised — gleaming rocket ships, impossible gadgets, and an unshakeable faith that tomorrow would be wonderful.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3033, '1w2hl4h', 'Movies That Feel Like My Photos', '', '', 'PresuminEd74', 1788096502, '/r/MoviesThatFeelLike/comments/1w2hl4h/movies_that_feel_like_my_photos/', 'https://www.reddit.com/gallery/1w2hl4h', 'MoviesThatFeelLike', 'A nostalgic and personal collection of movies that evoke the feeling of one''s own photographs.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3034, '1w2ho3a', 'Movies like this:', '', 'Preferably horror movies where is possible to guess the killer/villain.', 'Friz_Editz', 1788096708, '/r/MoviesThatFeelLike/comments/1w2ho3a/movies_like_this/', 'https://www.reddit.com/gallery/1w2ho3a', 'MoviesThatFeelLike', 'Puzzle-solving suspense in whodunnit horror settings.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3035, '1w2hvid', 'R rated dark fantasy films?', 'R rated dark fantasy films', 'I want sex, violence, royalty, magic, betrayal and overall dark fantasy for adult audiences.

I’m absolutely down for books and shows as well!

Video for inspo ', 'throwaway3685343', 1788097238, '/r/MoviesThatFeelLike/comments/1w2hvid/r_rated_dark_fantasy_films/', 'https://v.redd.it/04x7tqg4nimh1', 'MoviesThatFeelLike', 'A craving for dark, mature, visually lush medieval fantasy dripping with sex, violence, and moral corruption—the grittier and more adult-oriented the better.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3036, '1w2k01h', 'Movies that feels like this', '', '', 'Beanslover0', 1788102382, '/r/MoviesThatFeelLike/comments/1w2k01h/movies_that_feels_like_this/', 'https://i.redd.it/0tyhyz3f2jmh1.jpeg', 'MoviesThatFeelLike', 'An open-ended inquiry seeking movies that evoke a particular, unspecified atmospheric feeling.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3037, '1w2luqb', 'Toxic movie for Yash or Kaira Advani 👀', 'Toxic movie for Yash or Kaira Advani', '', 'Kdkala', 1788106730, '/r/MoviesThatFeelLike/comments/1w2luqb/toxic_movie_for_yash_or_kaira_advani/', 'https://i.redd.it/3h1kpox6djmh1.png', 'MoviesThatFeelLike', 'Speculative inquiry about a potentially toxic movie involving actors Yash or Kaira Advani.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3038, '1w2mkrf', 'Movies that feel like Autumn COMEDY', 'Movies that feel like Autumn COMEDY', '', 'NegotiationMean3042', 1788108401, '/r/MoviesThatFeelLike/comments/1w2mkrf/movies_that_feel_like_autumn_comedy/', 'https://www.reddit.com/gallery/1w2mkrf', 'MoviesThatFeelLike', 'Cozy, nostalgic autumnal comedies with fall foliage and Halloween vibes.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3039, '1w2nbww', 'What movies give you the exact same vibe as my photography series?( i''m the model)Looking for cosmic horror, sci-fi, or dark, dreamlike films. [OC]', 'Movies with cosmic horror, sci-fi, or dark, dreamlike vibes', '', 'Tough-Skill4060', 1788110094, '/r/MoviesThatFeelLike/comments/1w2nbww/what_movies_give_you_the_exact_same_vibe_as_my/', 'https://www.reddit.com/gallery/1w2nbww', 'MoviesThatFeelLike', 'A dark, dreamlike exploration of cosmic horror and sci-fi aesthetics, evoking eerie beauty and introspective unease.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3040, '1w2nctm', 'Millennial Core-esque Films You’d Watch on a Sunday Afternoon', 'Millennial Core-esque Films You''d Watch on a Sunday Afternoon', '', 'ImpressiveIsopod4778', 1788110152, '/r/MoviesThatFeelLike/comments/1w2nctm/millennial_coreesque_films_youd_watch_on_a_sunday/', 'https://v.redd.it/v0fw2s1bojmh1', 'MoviesThatFeelLike', 'A cozy, nostalgic search for laid-back films that evoke a gentle millennial melancholy — perfect for lazy Sunday afternoons.', 'skipped', 'no enriched recommendation matches', NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3041, '1w2oio9', 'For a cup of tea, knitted jumper and a grey day', 'Cozy coastal movies for a grey day', 'Movies that feel like a cozy storm on the coast 

The vibes are (already seen and loved):

Local Hero 

Banshees of Inisherin

Moonrise Kingdom', 'whitest_sneakers', 1788112816, '/r/MoviesThatFeelLike/comments/1w2oio9/for_a_cup_of_tea_knitted_jumper_and_a_grey_day/', 'https://www.reddit.com/gallery/1w2oio9', 'MoviesThatFeelLike', 'Cozy and atmospheric coastal movie recommendations for a grey day, evoking warmth and mild melancholy.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3042, '1w2ojcd', 'movies that feel like this or would be on this moms top 5', 'movies that feel like this or would be on this moms top 5', '', 'liafromtheupsidedown', 1788112852, '/r/MoviesThatFeelLike/comments/1w2ojcd/movies_that_feel_like_this_or_would_be_on_this/', 'https://www.reddit.com/gallery/1w2ojcd', 'MoviesThatFeelLike', 'Nostalgic, cozy early 2000s mom aesthetic with romantic and feel-good movies.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3043, '1w2oqw0', 'End of summer back to school blues', '', '', 'mzingg3', 1788113311, '/r/MoviesThatFeelLike/comments/1w2oqw0/end_of_summer_back_to_school_blues/', 'https://www.reddit.com/gallery/1w2oqw0', 'MoviesThatFeelLike', 'A nostalgic and melancholic mood evoking the end of summer and return to school.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3044, '1w2pe8q', 'Movies inspired on Bosch''s paintings', 'Movies inspired on Bosch''s paintings', '', 'LeonardoKlotzFTomaz', 1788114777, '/r/MoviesThatFeelLike/comments/1w2pe8q/movies_inspired_on_boschs_paintings/', 'https://www.reddit.com/gallery/1w2pe8q', 'MoviesThatFeelLike', 'A search for visually surreal, nightmarish, and fantastical imagery echoing Hieronymus Bosch''s dense otherworldly paintings of demons, creatures, and liminal spaces.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3045, '1w2ps81', 'Movies that make you feel like this', '', 'Some clinical/horror type, thanks for the comments!', 'rhinox-1', 1788115642, '/r/MoviesThatFeelLike/comments/1w2ps81/movies_that_make_you_feel_like_this/', 'https://www.reddit.com/gallery/1w2ps81', 'MoviesThatFeelLike', 'Clinical and horror themes evoke a sense of medical unease and dread.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3046, '1w2s72e', 'Movies that left you truly feeling empty/lonely/staring at the screen as the credits played', 'Movies that left you truly feeling empty/lonely/staring at the screen as the credits played', 'The three images are films that gave me this exact feeling right at the very end for a reason I can’t quite place my finger on. All of them are very different, but something about their endings gave me the same specific feeling that’s hard to describe. Empty.. lonely, and cathartic almost. I truly, truly love when the ending of a film can make me feel like this. I think it’s really powerful. It’s not happiness, sadness, shock, anger, but just gives you that strange feeling of not really knowing how to respond. And makes you think about it for days after you watch it. Any genre is fine. 

I’d love some suggestions of films that gave you this very specific feeling right at the end, or even better if you know of some that makes you feel that way all throughout it. 

*Films in order:*  
*The Blackcoat’s Daughter (2015)*  
*Anora (2024)*  
*The Killing of a Sacred Deer (2017)*  
*Under the Skin (2013)*  
*You Won’t Be Alone (2022)*', 'mrcuddlybuns', 1788121092, '/r/MoviesThatFeelLike/comments/1w2s72e/movies_that_left_you_truly_feeling/', 'https://www.reddit.com/gallery/1w2s72e', 'MoviesThatFeelLike', 'A brooding, melancholic search for films that leave you staring at the credits feeling hollowed out, lonely, and haunted for days.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3047, '1w2szt3', 'Movies that feel like college partying', 'Movies that feel like college partying', '', 'cutie_pri', 1788122929, '/r/MoviesThatFeelLike/comments/1w2szt3/movies_that_feel_like_college_partying/', 'https://www.reddit.com/gallery/1w2szt3', 'MoviesThatFeelLike', 'A nostalgic and rowdy celebration of youthful excess, capturing the chaotic energy of college parties and the carefree spirit of young adulthood.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3048, '1w2trbr', 'Movies that feel like these images - iridescent, utopic, optimistic', 'Movies that feel like these images - iridescent, utopic, optimistic', '', 'prprr', 1788124723, '/r/MoviesThatFeelLike/comments/1w2trbr/movies_that_feel_like_these_images_iridescent/', 'https://www.reddit.com/gallery/1w2trbr', 'MoviesThatFeelLike', 'Iridescent and utopic optimism.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3049, '1w2u7kv', 'Fear of the infinite, thalassaphobia, a great embarkment, "the abyss stares back," and things that should not/could not be', 'Fear of the infinite, thalassophobia, a great embarkment, the abyss stares back, and things that should not or could not be', '', 'HungryOpportunity322', 1788125832, '/r/MoviesThatFeelLike/comments/1w2u7kv/fear_of_the_infinite_thalassaphobia_a_great/', 'https://www.reddit.com/gallery/1w2u7kv', 'MoviesThatFeelLike', 'A haunting exploration of cosmic horror and existential dread, evoking the fear of infinite voids and unknowable entities.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3050, '1w2ucja', 'Movies that feel like ancient mythology', 'Movies that feel like ancient mythology', '', 'PriandTiti', 1788126167, '/r/MoviesThatFeelLike/comments/1w2ucja/movies_that_feel_like_ancient_mythology/', 'https://www.reddit.com/gallery/1w2ucja', 'MoviesThatFeelLike', 'Epic, mythological atmosphere with ancient gods, heroes, and legendary battles.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3051, '1w2vmwf', 'Movies that feel like 20th century illusion', '', '', 'Radiant-Boat-5149', 1788129411, '/r/MoviesThatFeelLike/comments/1w2vmwf/movies_that_feel_like_20th_century_illusion/', 'https://www.reddit.com/gallery/1w2vmwf', 'MoviesThatFeelLike', 'A nostalgic and mysterious exploration of illusion and magic in 20th-century cinema.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3052, '1w2vwcl', 'Movies that feel like Hard Work & Success (inspirational)', 'Movies that feel like Hard Work & Success (inspirational)', '', 'S3XY_mis', 1788130094, '/r/MoviesThatFeelLike/comments/1w2vwcl/movies_that_feel_like_hard_work_success/', 'https://www.reddit.com/gallery/1w2vwcl', 'MoviesThatFeelLike', 'A warm, motivational atmosphere celebrating perseverance, ambition, and the emotional weight of earning success against the odds.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3053, '1w2w3ky', 'Movies that feel like Oppenheimer', 'Movies that feel like Oppenheimer', '', 'Optimal_Prior_2551', 1788130611, '/r/MoviesThatFeelLike/comments/1w2w3ky/movies_that_feel_like_oppenheimer/', 'https://www.reddit.com/gallery/1w2w3ky', 'MoviesThatFeelLike', 'A quest for intense biographical dramas with intellectual and historical depth, akin to Oppenheimer.', 'publishable', NULL, NULL, '2026-08-31 03:40:48', '2026-08-31 03:40:48');
