-- 0181_seed_20260901T034356Z_01_posts.sql: data seed from pipeline:load run.
-- Generated:  2026-09-01T03:44:38.163777+00:00
-- Run started: 2026-09-01T03:43:56.431783+00:00
-- Source: data/working/load manifest from this run.
--
-- Idempotent: every INSERT is INSERT OR IGNORE, keyed by the
-- table's natural unique constraint.  Wrangler's migration
-- tracking normally prevents re-apply; the OR IGNORE is
-- defense in depth for partial / interrupted re-runs.
--
-- Chunk: 01_posts (1/5)
-- Tables: imported_vibe_posts.
-- Pipeline-state tables (processing_runs, pipeline_artifacts)
-- are intentionally excluded — they're per-run bookkeeping.

INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3054, '1towznl', 'Movies/TV shows that give that New York feel', '', 'https://preview.redd.it/og732bpchm3h1.jpg?width=1200&format=pjpg&auto=webp&s=0769cfbfc97c816e067332525d2e7586e3df930f

https://preview.redd.it/jo0s1dpchm3h1.jpg?width=2048&format=pjpg&auto=webp&s=979921ea82384a29fd23174edfcc4d09a2e6350d

https://preview.redd.it/ovo1mcpchm3h1.jpg?width=1440&format=pjpg&auto=webp&s=84fac74612c09d43dd3b8f3b7c444e5df713e1a7

https://preview.redd.it/1pke4dpchm3h1.jpg?width=485&format=pjpg&auto=webp&s=ea569d54cd05ea9a4d6f63a7dda4074a8cc246a7

', 'Mit-Milch', 1779862642, '/r/MoviesThatFeelLike/comments/1towznl/moviestv_shows_that_give_that_new_york_feel/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1towznl/moviestv_shows_that_give_that_new_york_feel/', 'MoviesThatFeelLike', 'A nostalgic and urban cinematic mood evoking the essence of New York City.', 'skipped', 'no usable images', NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3055, '1toxb56', 'Makes you feel like this song and this album in general Christmas kids', 'Makes you feel like this song and this album in general Christmas kids', '', 'melioristic_guy', 1779863642, '/r/MoviesThatFeelLike/comments/1toxb56/makes_you_feel_like_this_song_and_this_album_in/', 'https://i.redd.it/7jkx6bzekm3h1.jpeg', 'MoviesThatFeelLike', 'A wistful, bittersweet longing for youthful nostalgia wrapped in melancholic indie warmth and holiday tinges.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3056, '1tp1ncz', 'Movies that feel like Józef Chełmoński''s art', 'Movies that feel like Józef Chełmoński''s art', '', 'AlmightyHet', 1779878043, '/r/MoviesThatFeelLike/comments/1tp1ncz/movies_that_feel_like_józef_chełmońskis_art/', 'https://www.reddit.com/gallery/1tp1ncz', 'MoviesThatFeelLike', 'A pastoral, painterly appreciation thread seeking films that capture the luminous rural realism and golden-hued landscapes of Polish art.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3057, '1tp1qrb', 'Looking for movies based in bayous, back country etc vibes', 'Looking for movies based in bayous, back country etc vibes', '', 'codependencytapes', 1779878344, '/r/MoviesThatFeelLike/comments/1tp1qrb/looking_for_movies_based_in_bayous_back_country/', 'https://www.reddit.com/gallery/1tp1qrb', 'MoviesThatFeelLike', 'Humid, foreboding Southern Gothic atmosphere dripping with mystery, unease, and swamp-drenched tension.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3058, '1tp3j4u', 'Any movies similar to Fight Night Champion''s story mode?', 'Any movies similar to Fight Night Champion''s story mode?', 'Fight Night Champion''s story was cinematic af and played exactly like a movie. ', 'naydenthegreatone', 1779883479, '/r/MoviesThatFeelLike/comments/1tp3j4u/any_movies_similar_to_fight_night_champions_story/', 'https://i.redd.it/257iijhe7o3h1.jpeg', 'MoviesThatFeelLike', 'Seeking intense, cinematic boxing movies with gritty and dramatic storylines.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3059, '1tp6qrw', 'Movies that feel like this?', 'Movies that feel like this?', '', 'videodrome_victim', 1779891044, '/r/MoviesThatFeelLike/comments/1tp6qrw/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1tp6qrw', 'MoviesThatFeelLike', 'A moody, dreamy atmosphere evoking urban melancholy, neon-lit nights, and surreal introspection.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3060, '1tp71ew', 'Movie that feels like this', 'Gothic Castle and Village Movies, Inspired by Nosferatu', 'It taking place in a creepy vill or castle I love movies like nosferatu I thought it was amazing it can be an International  film as well i love films from other countries as i feel like i don’t watch enough ', 'OsmentArkham', 1779891665, '/r/MoviesThatFeelLike/comments/1tp71ew/movie_that_feels_like_this/', 'https://i.redd.it/4umm8asqvo3h1.jpeg', 'MoviesThatFeelLike', 'A gothic, eerie atmosphere with creepy castles and villages, evoking classic horror films.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3061, '1tp7ije', 'Movies that feel like Bernard Herrmann film scores', '', '', 'elementtwisting', 1779892664, '/r/MoviesThatFeelLike/comments/1tp7ije/movies_that_feel_like_bernard_herrmann_film_scores/', 'https://www.reddit.com/gallery/1tp7ije', 'MoviesThatFeelLike', 'A suspenseful and dramatic cinematic atmosphere reminiscent of Bernard Herrmann''s iconic film scores.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3062, '1tp7uao', 'I just love the goofiness and the animalism in her expression', 'I just love the goofiness and the animalism in her expression', 'Tagged because technically these two are models of a certain type of work, for anyone looking for further info on them.', 'Icy-Personality8496', 1779893382, '/r/MoviesThatFeelLike/comments/1tp7uao/i_just_love_the_goofiness_and_the_animalism_in/', 'https://i.redd.it/sy4dylku0p3h1.jpeg', 'MoviesThatFeelLike', 'A light-hearted and curious appreciation for quirky and animalistic expressions in film, centered around a specific movie recommendation.', 'skipped', 'no enriched recommendation matches', NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3063, '1tp81ko', 'Movies that feel like a Misfits song?', 'Movies that feel like a Misfits song?', '', 'dannzz16', 1779893797, '/r/MoviesThatFeelLike/comments/1tp81ko/movies_that_feel_like_a_misfits_song/', 'https://i.redd.it/h0drwxv22p3h1.jpeg', 'MoviesThatFeelLike', 'Campy, ghoulish horror-punk energy with B-movie charm, blood-soaked fun, and a celebratory love of the macabre.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3064, '1tp8lkx', 'Enola Holmes 3 breaking the 4th wall with style!', 'Enola Holmes 3 breaking the 4th wall with style', '', 'NetflixNerdof95', 1779894960, '/r/MoviesThatFeelLike/comments/1tp8lkx/enola_holmes_3_breaking_the_4th_wall_with_style/', 'https://www.soapcentral.com/entertainment/enola-holmes-3-teases-wedding-proposal-millie-bobby-brown-breaks-4th-wall', 'MoviesThatFeelLike', 'Enthusiastic appreciation for playful, self-aware storytelling that delightfully breaks the fourth wall.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3065, '1tp8yhv', 'Movies that look like this', 'Movies that look like this', '', 'Male-2003', 1779895688, '/r/MoviesThatFeelLike/comments/1tp8yhv/movies_that_look_like_this/', 'https://i.redd.it/ymw5tjcp7p3h1.jpeg', 'MoviesThatFeelLike', 'A thread sharing movie recommendations for their distinctive visual aesthetics, often featuring neo-noir, surreal, or stylistically bold films.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3066, '1tp9aq7', 'Beachy, tropical, pool party vibes', 'Beachy, tropical, pool party vibes', '', 'RickGrimesTheOGx', 1779896393, '/r/MoviesThatFeelLike/comments/1tp9aq7/beachy_tropical_pool_party_vibes/', 'https://www.reddit.com/gallery/1tp9aq7', 'MoviesThatFeelLike', 'A carefree, sunny vibe evoking beach vacations, pool parties, and tropical getaways.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3067, '1tpah09', 'Movies that perfectly illustrate all of this', 'Movies that perfectly illustrate all of this', '', 'Spleen97', 1779898847, '/r/MoviesThatFeelLike/comments/1tpah09/movies_that_perfectly_illustrate_all_of_this/', 'https://www.reddit.com/gallery/1tpah09', 'MoviesThatFeelLike', 'A somber and concerned discussion about movies that evoke deep emotional responses, with users expressing worry for the poster''s well-being.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3068, '1tpbvyl', 'Movies the feature a quarter/mid life crisis. People in their late 20s-40s settling down and struggling', '', 'Movies like The Good Girl, Lovely and Amazing, Friends with Money, The Station Agent. American, 80s till now. Thanks', 'Inner-Day-8920', 1779901771, '/r/MoviesThatFeelLike/comments/1tpbvyl/movies_the_feature_a_quartermid_life_crisis/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tpbvyl/movies_the_feature_a_quartermid_life_crisis/', 'MoviesThatFeelLike', 'A supportive discussion about movies that capture the anxiety and transitions of quarter and mid-life crises.', 'skipped', 'no usable images', NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3069, '1tpby5v', 'Movies or TV show with mechanic vibe', 'Movies or TV show with mechanic vibe', '', 'Romo80s', 1779901904, '/r/MoviesThatFeelLike/comments/1tpby5v/movies_or_tv_show_with_mechanic_vibe/', 'https://www.reddit.com/gallery/1tpby5v', 'MoviesThatFeelLike', 'Seeking movies and TV shows with a mechanic or automotive theme, evoking gritty, hands-on, and action-oriented atmospheres.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3070, '1tpcwz4', 'Movies that feel like Raymond Carver''s short stories?', 'Movies that feel like Raymond Carvers short stories', '', 'uldastormcloak114', 1779903878, '/r/MoviesThatFeelLike/comments/1tpcwz4/movies_that_feel_like_raymond_carvers_short/', 'https://i.redd.it/k7hea322wp3h1.jpeg', 'MoviesThatFeelLike', 'A quiet, contemplative search for films that capture the sparse melancholy and understated desperation of Raymond Carver''s minimalist literary world.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3071, '1tpebii', 'Films with Twin Peaks vibes? ˚｡⋆', 'Films with Twin Peaks vibes? ˚｡⋆', 'I love Twin Peaks and i’m craving a similar atmosphere. I also love the experimental aspects too if that helps', 'avanescense', 1779906739, '/r/MoviesThatFeelLike/comments/1tpebii/films_with_twin_peaks_vibes/', 'https://i.redd.it/we8zl4ek4q3h1.jpeg', 'MoviesThatFeelLike', 'Craving a mysterious, surreal, and experimental atmosphere reminiscent of Twin Peaks.', 'skipped', 'no enriched recommendation matches', NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3072, '1tpebma', 'Films with Twin Peaks vibes? ˚｡⋆', 'Films with Twin Peaks vibes', 'I love Twin Peaks and i’m craving a similar atmosphere. I also love the experimental aspects too if that helps', 'avanescense', 1779906745, '/r/MoviesThatFeelLike/comments/1tpebma/films_with_twin_peaks_vibes/', 'https://i.redd.it/yzhs570l4q3h1.jpeg', 'MoviesThatFeelLike', 'A yearning for the eerie, surreal, and dreamlike atmosphere of small-town mystery blending horror, humor, and experimental storytelling.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3073, '1tpglyr', 'Movies that feel like:', 'Movies that feel like:', '', 'Lucyyyyyy_K', 1779911545, '/r/MoviesThatFeelLike/comments/1tpglyr/movies_that_feel_like/', 'https://www.reddit.com/gallery/1tpglyr', 'MoviesThatFeelLike', 'Surreal and fantastical with an otherworldly charm.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3074, '1tpizkk', 'Movie that feels like Ico', 'Movie that feels like Ico', '', 'Belleagle', 1779916713, '/r/MoviesThatFeelLike/comments/1tpizkk/movie_that_feels_like_ico/', 'https://www.reddit.com/gallery/1tpizkk', 'MoviesThatFeelLike', 'Seeking movies with a whimsical, ethereal atmosphere reminiscent of the game Ico.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3075, '1tpkczx', 'Movie/ Series that feel like this Album', 'Movie/Series that feel like this Album', '', 'hellom8-_', 1779919827, '/r/MoviesThatFeelLike/comments/1tpkczx/movie_series_that_feel_like_this_album/', 'https://i.redd.it/znbh491f7r3h1.jpeg', 'MoviesThatFeelLike', 'A collection of introspective and emotionally nuanced films and series that evoke themes of love, loss, and quiet beauty.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3076, '1tpluyc', 'Films that feel like this', 'Films that feel like this', '', 'OkCase3935', 1779923413, '/r/MoviesThatFeelLike/comments/1tpluyc/films_that_feel_like_this/', 'https://www.reddit.com/gallery/1tpluyc', 'MoviesThatFeelLike', 'A surreal and melancholic artistic vibe with dreamlike and unsettling elements.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3077, '1tpmkm0', 'Movies that feel like..', 'Movies that feel like', '', 'Disastrous-Bag-1725', 1779925198, '/r/MoviesThatFeelLike/comments/1tpmkm0/movies_that_feel_like/', 'https://www.reddit.com/gallery/1tpmkm0', 'MoviesThatFeelLike', 'A playful, chaotic thread where a vague or ironic post image sparked an avalanche of spy-fi, action-comedy, and cult film recommendations with tongue-in-cheek energy.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3078, '1tppf9d', 'A film where the character is not human and struggles to be recognized?', 'A film where a non-human character struggles to be recognized?', 'For example, a film where the character is a monster but fights to make us stop being afraid of them, not too childish, but not aimed at children either

  
I''m feeling a bit down, and this is the kind of film that could cheer me up :\]', 'Big-Tax-8921', 1779932563, '/r/MoviesThatFeelLike/comments/1tppf9d/a_film_where_the_character_is_not_human_and/', 'https://i.redd.it/m6f1y9oq8s3h1.png', 'MoviesThatFeelLike', 'A longing for empathy and recognition, seeking comforting stories of non-human characters overcoming prejudice.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3079, '1tpqzuq', 'Movies that feel like this?', 'Movies that feel like this?', '', 'Tenebrae_Hunter', 1779936805, '/r/MoviesThatFeelLike/comments/1tpqzuq/movies_that_feel_like_this/', 'https://i.redd.it/zhr3b79yls3h1.jpeg', 'MoviesThatFeelLike', 'A haunting, moody coastal atmosphere with grey overcast skies, dark waters, and a sense of isolated melancholy.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3080, '1tpqzzh', 'Movies that feel like Genesis by Grimes', 'Movies that feel like Genesis by Grimes', '', 'Additional_Smile_674', 1779936814, '/r/MoviesThatFeelLike/comments/1tpqzzh/movies_that_feel_like_genesis_by_grimes/', 'https://www.reddit.com/gallery/1tpqzzh', 'MoviesThatFeelLike', 'Atmospheric and ethereal cinematic mood inspired by a surreal, haunting music video.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3081, '1tprca1', 'Movies that feel like this?', 'Movies that feel like this?', 'I’ve been trying to find a movie that genuinely scares me and this is this the kind of stuff that freaks me out. If I can get some or a movie that feels like this that would be much appreciated!', 'Business_Bear14', 1779937755, '/r/MoviesThatFeelLike/comments/1tprca1/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1tprca1', 'MoviesThatFeelLike', 'Visceral body horror with fleshy, grotesque creature designs and cosmic dread.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3082, '1tprzs9', 'Anything feel like this?', 'Anything feel like this?', 'To me it’s when you fall asleep in a cozy bed in a dark dimly lit room and then have beautiful but strange dreams.

Art by Chelsea Cardinal, Kathryn June, Tennessee Charpentier, Serena Maylon, Edward Mason, nendili, Corina Chirila, and Hadshaom', 'FuelEnvironmental506', 1779939587, '/r/MoviesThatFeelLike/comments/1tprzs9/anything_feel_like_this/', 'https://www.reddit.com/gallery/1tprzs9', 'MoviesThatFeelLike', 'A cozy, dreamy atmosphere evoking beautiful and strange dreams.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3083, '1tps541', 'Movies that feel like this?', '', '', 'Ancient_Win_2837', 1779940013, '/r/MoviesThatFeelLike/comments/1tps541/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1tps541', 'MoviesThatFeelLike', 'Gritty, atmospheric urban tension with surreal and intense undertones.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3084, '1tpuz3a', 'movies like this?', 'movies like this?', '', 'k_kalia_k', 1779948572, '/r/MoviesThatFeelLike/comments/1tpuz3a/movies_like_this/', 'https://www.reddit.com/gallery/1tpuz3a', 'MoviesThatFeelLike', 'A community request for surreal, visually intense movies with an otherworldly and psychedelic atmosphere.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3085, '1tpvht9', 'Movies that feel like Jack Kirby (But aren''t at all Marvel)', 'Movies that feel like Jack Kirby (But aren''t at all Marvel)', 'Not even *Spider-Verse*.', 'XipeTotecwithGlitter', 1779950282, '/r/MoviesThatFeelLike/comments/1tpvht9/movies_that_feel_like_jack_kirby_but_arent_at_all/', 'https://www.reddit.com/gallery/1tpvht9', 'MoviesThatFeelLike', 'Cosmic, psychedelic, and fantastical visuals reminiscent of Jack Kirby''s comic art.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3086, '1tpx40n', 'Movies that feel like this.', 'Movies that feel like this.', '[removed]', 'noway_117', 1779955751, '/r/MoviesThatFeelLike/comments/1tpx40n/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1tpx40n', 'MoviesThatFeelLike', 'A vague, mysterious prompt evoking a sense of epic, otherworldly adventure that fans instinctively associate with sprawling fantasy landscapes.', 'skipped', 'no usable images', NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3087, '1tpzx7a', 'Movies that feel like this....', '', '', 'Square-Ad-8911', 1779965137, '/r/MoviesThatFeelLike/comments/1tpzx7a/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1tpzx7a', 'MoviesThatFeelLike', 'Sun-drenched tropical beach getaway with a carefree, oceanic atmosphere.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3088, '1tq725b', 'I''d love some suggestions', 'I''d love some suggestions', '', 'Thatmetalchef', 1779982397, '/r/MoviesThatFeelLike/comments/1tq725b/id_love_some_suggestions/', 'https://i.redd.it/5oxvx4vidw3h1.png', 'MoviesThatFeelLike', 'A casual request for atmospheric, unsettling, and suspenseful films and series, with commenters enthusiastically sharing dark, mystery-laden favorites.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3089, '1tq7rkq', 'Favorite media that feel like a swampy Western?', 'Favorite media that feel like a swampy Western', '', 'LaudanumSerum', 1779983914, '/r/MoviesThatFeelLike/comments/1tq7rkq/favorite_media_that_feel_like_a_swampy_western/', 'https://www.reddit.com/gallery/1tq7ras', 'MoviesThatFeelLike', 'A moody, humid atmosphere blending western tropes with swampy, southern gothic settings.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3090, '1tqal8k', 'Movies that feel like this', 'Movies that feel like this', '[removed]', '[deleted]', 1779989896, '/r/MoviesThatFeelLike/comments/1tqal8k/movies_that_feel_like_this/', '', 'MoviesThatFeelLike', 'An undefined atmospheric mood expressed through a vague request for movies that evoke a particular feeling.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3091, '1tqao0w', 'Movies that feel like this', 'Movies that feel like this', '', 'Worldpeacee007', 1779990056, '/r/MoviesThatFeelLike/comments/1tqao0w/movies_that_feel_like_this/', 'https://www.tiktok.com/@griffinkingg/video/7636572874077113613?is_from_webapp=1&sender_device=pc&web_id=7644998869017658910', 'MoviesThatFeelLike', 'A request for atmospheric, mood-driven film recommendations based on an unspecified visual reference.', 'skipped', 'no enriched recommendation matches', NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3092, '1tqc59k', 'movies that feel like this', 'movies that feel like this', '', 'clitnotfound', 1779993176, '/r/MoviesThatFeelLike/comments/1tqc59k/movies_that_feel_like_this/', 'https://i.redd.it/nc8gf02l9x3h1.jpeg', 'MoviesThatFeelLike', 'A nostalgic and bittersweet feeling of glamorous melancholy with vintage aesthetics.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3093, '1tqdrax', 'Movies involving a leg in a cast ?', 'Movies involving a leg in a cast', 'I broke my ankle and I''m stuck at home with a cast for 6 weeks. Thought it might be fun to have an on-theme watch list.

My first thoughts :

Rear Window - A. HITCHCOCK (1954)

Mon Roi (My king) - MAIWENN (2015)

Honourable mention (arm in a cast)

Aftersun - C. WELLS (2022)', 'emmamon_', 1779996604, '/r/MoviesThatFeelLike/comments/1tqdrax/movies_involving_a_leg_in_a_cast/', 'https://www.reddit.com/gallery/1tqdrax', 'MoviesThatFeelLike', 'A playful, self-deprecatingly humorous community rallying around an injured person''s oddly specific and wholesome watchlist request, mixing genuine helpfulness with lighthearted roasting.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3094, '1tqec0w', 'Discovering abandoned non-human infrastructure, incomprehensible artifacts', 'Discovering abandoned non-human infrastructure, incomprehensible artifacts', 'Got that itch from games, mostly, like Subnautica, Halo, or Mass Effect series. 

Movies I''ve watched, with a similar premise:

* Prometheus
* 2001: a Space Odyssey
* Arrival

Don''t mind whether it''s the main focus, or not. I highly enjoy the mystery aspect.

Thank you in advance!', 'Mickey_AD', 1779997837, '/r/MoviesThatFeelLike/comments/1tqec0w/discovering_abandoned_nonhuman_infrastructure/', 'https://www.reddit.com/gallery/1tqec0w', 'MoviesThatFeelLike', 'Awe-struck exploration of mysterious and incomprehensible alien remnants.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3095, '1tqf4xy', 'Earn money', 'Earn money', '[removed]', 'Mr-Leontark', 1779999494, '/r/MoviesThatFeelLike/comments/1tqf4xy/earn_money/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1tqf4xy/earn_money/', 'MoviesThatFeelLike', 'A bare-bones query about making money with no elaboration or community discussion available.', 'skipped', 'no enriched recommendation matches', NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3096, '1tqhkw6', 'Movies that feel like this?', '', '', 'Harddisksson69', 1780004752, '/r/MoviesThatFeelLike/comments/1tqhkw6/movies_that_feel_like_this/', 'https://i.redd.it/i3kpvfdz7y3h1.png', 'MoviesThatFeelLike', 'A surreal and anxiety-inducing collection of movie recommendations that blend childhood whimsy with dread.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3097, '1tqi1ek', 'Movies that feels rainy', 'Movies that feel rainy', '', 'EliasZav', 1780005771, '/r/MoviesThatFeelLike/comments/1tqi1ek/movies_that_feels_rainy/', 'https://www.reddit.com/gallery/1tqi1ek', 'MoviesThatFeelLike', 'A dark, wet, and immersive atmosphere that evokes feelings of melancholy and tension.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3098, '1tqii0e', 'Star Wars', 'Star Wars', '', 'Bananaman20055', 1780006818, '/r/MoviesThatFeelLike/comments/1tqii0e/star_wars/', '/r/MoviesAnywhere/comments/1tqigvd/star_wars/', 'MoviesThatFeelLike', 'Simple discussion prompt about the Star Wars franchise.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3099, '1tqivbk', 'Looking for a specific vibe', 'Looking for a specific vibe', 'Not sure how to describe it', 'Fout99', 1780007708, '/r/MoviesThatFeelLike/comments/1tqivbk/looking_for_a_specific_vibe/', 'https://www.reddit.com/gallery/1tqivbk', 'MoviesThatFeelLike', 'A gritty, post-apocalyptic wasteland aesthetic filled with tribal gang warfare, urban decay, and ultraviolent survival — equal parts desolate roads and raider strongholds.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3100, '1tqm4z2', '🙏🏻🙏🏻', '', '', 'Infinite_Back_2522', 1780015989, '/r/MoviesThatFeelLike/comments/1tqm4z2/_/', 'https://www.reddit.com/gallery/1tqm4z2', 'MoviesThatFeelLike', 'Rebellious punk-rock and counterculture nostalgia with a raw, intense energy.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3101, '1tqnfgs', 'New armor with missing soft slot. BUG', 'New armor with missing soft slot. BUG', 'Looted from boss guard on reserve. ', 'Big-Knowledge12', 1780019409, '/r/MoviesThatFeelLike/comments/1tqnfgs/new_armor_with_missing_soft_slot_bug/', 'https://i.redd.it/2cohdh1xez3h1.png', 'MoviesThatFeelLike', 'Frustrated bug report from a player encountering an incomplete game mechanic.', 'skipped', 'no enriched recommendation matches', NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3102, '1tqoqex', 'Movies That Feel Like This?', 'Movies That Feel Like This?', '[removed]', '[deleted]', 1780022885, '/r/MoviesThatFeelLike/comments/1tqoqex/movies_that_feel_like_this/', '', 'MoviesThatFeelLike', 'Vague, evocative post seeking films matching an unspecified visual or emotional aesthetic.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3103, '1tqos85', 'Movies That Feel Like This?', 'Movies That Feel Like This', '[removed]', '[deleted]', 1780023023, '/r/MoviesThatFeelLike/comments/1tqos85/movies_that_feel_like_this/', '', 'MoviesThatFeelLike', 'A request for movie recommendations based on a visual aesthetic or mood, though the source image and context were removed.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3104, '1tqosyj', 'Movies That Feel Like This?', 'Movies That Feel Like This?', '', 'Worldpeacee007', 1780023078, '/r/MoviesThatFeelLike/comments/1tqosyj/movies_that_feel_like_this/', 'https://www.tiktok.com/t/ZTBM2kN61/', 'MoviesThatFeelLike', 'Seeking cinematic atmosphere from striking visuals, with viewers drawn to dramatic, tense imagery.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3105, '1tqp78w', 'Movies that feel like this ?', 'Movies that feel like this', 'Romance films are appreciated , by the way ! ', 'epicpersononthisapp', 1780024142, '/r/MoviesThatFeelLike/comments/1tqp78w/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1tqp78w', 'MoviesThatFeelLike', 'Dreamy, melancholic romanticism with a moody introspective edge—vintage-feeling imagery evoking longing, loneliness, and bittersweet intimacy.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3106, '1tquegl', 'Movies that feel like this?', 'Movies that feel like this?', '', 'jeezogee', 1780039926, '/r/MoviesThatFeelLike/comments/1tquegl/movies_that_feel_like_this/', 'https://i.redd.it/garbtchl414h1.jpeg', 'MoviesThatFeelLike', 'A warm, chaotic, and heartfelt family gathering vibe, full of laughter and relatable family drama.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3107, '1tquy26', 'Movies that feel like this?', 'Movies that feel like this', '', 'BlastCombos', 1780041775, '/r/MoviesThatFeelLike/comments/1tquy26/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1tquy26', 'MoviesThatFeelLike', 'The discussion evokes a nostalgic and whimsical atmosphere, with users suggesting animated and fantasy media that capture a sense of adventure and childhood wonder.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3108, '1tqxnan', 'Movies that feel like this?', 'Movies that feel like this?', 'Other than Bugonia ofc', 'Harddisksson69', 1780050519, '/r/MoviesThatFeelLike/comments/1tqxnan/movies_that_feel_like_this/', 'https://i.redd.it/hc686kh1024h1.png', 'MoviesThatFeelLike', 'Surreal and psychological cinematic exploration.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3109, '1tqxy0j', 'Happy Friday!....Party Starts @ 5pm EST @ https://cytu.be/r/Channel-Z', 'Happy Friday! Party Starts @ 5pm EST', '', 'TeenageDX', 1780051398, '/r/MoviesThatFeelLike/comments/1tqxy0j/happy_fridayparty_starts_5pm_est/', 'https://i.redd.it/kmwfokty124h1.gif', 'MoviesThatFeelLike', 'Casual Friday evening social gathering inviting community members to a CyTube watch party.', 'skipped', 'no enriched recommendation matches', NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3110, '1tr0qwv', 'movies that feel like this', 'movies that feel like this', '', 'clitnotfound', 1780058697, '/r/MoviesThatFeelLike/comments/1tr0qwv/movies_that_feel_like_this/', 'https://i.redd.it/4ssb77zeo24h1.jpeg', 'MoviesThatFeelLike', 'Edgy, fashion-forward aesthetic with a dark, stylized, and seductive visual mood.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3111, '1tr1s8s', 'I’m always searching for movies that feel like this', 'I’m always searching for movies that feel like this', '', 'Lovelifeoutside', 1780061021, '/r/MoviesThatFeelLike/comments/1tr1s8s/im_always_searching_for_movies_that_feel_like_this/', 'https://i.redd.it/5pcb1arbv24h1.jpeg', 'MoviesThatFeelLike', 'Nostalgic summer childhood adventures in nature with a sense of wonder and outdoor exploration.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3112, '1tr1vo4', 'HELP ME FIND THIS SHOW', 'Help Me Find This Show', '', 'Upbeat_Leading_7144', 1780061233, '/r/MoviesThatFeelLike/comments/1tr1vo4/help_me_find_this_show/', 'https://www.reddit.com/gallery/1tqz3g1', 'MoviesThatFeelLike', 'Urgent, chaotic crowd-sourced mystery-solving with a mix of genuine help and irreverent humor.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3113, '1w2qrwl', 'Movies That Feel Pure Evil', 'Movies That Feel Pure Evil', 'I''m trying to look for more ''evil feeling'' films with the same vibes, atmosphere, and overall aesthetic as some of these films. Constant dread and fear from even the most mundane moments, environment, and even objects. Films that would hit me on a emotionally draining fashion by the end. Movies with scenes that will take me off guard and come completely out of left field. Trying to explain the best I can.

Not just necessarily in terms of content (Ex. Serial killer, mass killing like genocides, etc), storylines, or ''surface level'' stuff if that makes sense. Doesn''t need to be horror either. Any genre. Not entirely excluding these aspects however.

Already familiar with works by Haneke, Gasper Noe, Come and See, Angst, Henry Portrait of a Serial Killer, and most modern horror.

Obscure suggestions are welcome as well!', 'Siksinaaq', 1788117877, '/r/MoviesThatFeelLike/comments/1w2qrwl/movies_that_feel_pure_evil/', 'https://www.reddit.com/gallery/1w2qrwl', 'MoviesThatFeelLike', 'An intense and emotionally draining search for films that embody pure evil through constant dread and atmospheric unease.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3114, '1w2ykko', 'Movies That Feel Like The Early 1900s', '', 'I’ve seen Titanic (1997) and The Rainbow (1989). Thanks guys!', 'katyreddit00', 1788137167, '/r/MoviesThatFeelLike/comments/1w2ykko/movies_that_feel_like_the_early_1900s/', 'https://www.reddit.com/gallery/1w2ykko', 'MoviesThatFeelLike', 'Seeking nostalgic period pieces evoking the early 1900s era.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3115, '1w2ypv1', 'movie that feel like death note', 'movie that feel like death note', '', 'daddylongjohnsliver', 1788137575, '/r/MoviesThatFeelLike/comments/1w2ypv1/movie_that_feel_like_death_note/', 'https://www.reddit.com/gallery/1w2ypv1', 'MoviesThatFeelLike', 'Dark, tense cat-and-mouse thrillers with clever protagonists, noir atmospheres, and psychological mind games between hunters and hunted.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3116, '1w2yw6w', 'Movies that feel like a fever dream', '', '', 'Lazy_One99', 1788138053, '/r/MoviesThatFeelLike/comments/1w2yw6w/movies_that_feel_like_a_fever_dream/', 'https://www.reddit.com/gallery/1w2yw6w', 'MoviesThatFeelLike', 'A surreal and disorienting exploration of films that mimic the hazy, illogical sensations of a fever dream.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3117, '1w2z9l7', '''Campy'' movies with outrageous lines coming out of almost every character''s mouths', '', 'Can you guys recommend films that have the same vibes as "Drop Dead Gorgeous" and "But I''m a Cheerleader"

Basically comedy movies with trashy/unhinged dialogues where most jokes would now be considered "offensive" pleasee I need more of them 🥹', 'drinkablesausage7', 1788139082, '/r/MoviesThatFeelLike/comments/1w2z9l7/campy_movies_with_outrageous_lines_coming_out_of/', 'https://www.reddit.com/gallery/1w2z9l7', 'MoviesThatFeelLike', 'Unapologetically trashy and offensive camp comedy with outrageous dialogue.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3118, '1w2zd77', 'Movies that feel like this game', '', '', 'SweetPop1996', 1788139365, '/r/MoviesThatFeelLike/comments/1w2zd77/movies_that_feel_like_this_game/', 'https://i.redd.it/5m3ktzzd4mmh1.jpeg', 'MoviesThatFeelLike', 'Intense, violent, and thrilling movies that evoke a sense of danger, suspense, and dark atmosphere, mirroring the tension and peril of a game.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3119, '1w2zeai', 'Life goal', 'Life goal', '[removed]', 'iam_thorsten_kaye', 1788139446, '/r/MoviesThatFeelLike/comments/1w2zeai/life_goal/', 'https://i.redd.it/wm6ma8km4mmh1.jpeg', 'MoviesThatFeelLike', 'An empty or removed post with no discernible vibe.', 'skipped', 'no enriched recommendation matches', NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3120, '1w30xtw', 'Halloween movies', 'Halloween movies', 'I''m looking for movies that aren''t necessarily scary but that have that fall/october feel. Like for instance, Mean Girls isn''t a scary or halloween themed movie but there''s a halloween party during the movie. Stuff like that. I don''t really like the actual halloween themed scary movies, just the nostalgia surrounding halloween and fall time. ', 'Logical-House6004', 1788143752, '/r/MoviesThatFeelLike/comments/1w30xtw/halloween_movies/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1w30xtw/halloween_movies/', 'MoviesThatFeelLike', 'Cozy autumn nostalgia with a touch of Halloween spirit.', 'skipped', 'no usable images', NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3121, '1w31dpi', 'Steamy Noir and Neo Noirs like Body Heat 1981', 'Steamy Noir and Neo Noirs like Body Heat', '', 'WaferRoyal4980', 1788144991, '/r/MoviesThatFeelLike/comments/1w31dpi/steamy_noir_and_neo_noirs_like_body_heat_1981/', '/r/MovieSuggestions/comments/1w31ash/steamy_noir_and_neo_noirs_like_body_heat_1981/', 'MoviesThatFeelLike', 'Dark, seductive, and tense atmosphere reminiscent of classic noir films.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3122, '1w31wjd', 'Movies about Hollywood pre- 2000. Please see description for details.', 'Movies about Hollywood pre-2000. Please see description for details.', 'Need movie suggestions about old Hollywood. Anything made or takes place before the year 2000. I’ve already seen Sunset Blvd, Once Upon a Time in Hollywood. Need some other suggestions, thanks.  ', 'Talilala', 1788146475, '/r/MoviesThatFeelLike/comments/1w31wjd/movies_about_hollywood_pre_2000_please_see/', 'https://www.reddit.com/gallery/1w31wjd', 'MoviesThatFeelLike', 'A nostalgic, collaborative search for classic Hollywood cinema, with commenters enthusiastically sharing deep cuts and well-known favorites alike.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3123, '1w322kn', 'Movies based on Game Theory', '', 'strategic decision-making movie/series where multiple participants,  called players,  or a mastermind make interdependent choices to optimize their outcomes.', 'Adorable-Quarter2994', 1788146951, '/r/MoviesThatFeelLike/comments/1w322kn/movies_based_on_game_theory/', 'https://www.reddit.com/gallery/1w322kn', 'MoviesThatFeelLike', 'Strategic and psychological movies focused on game theory and interdependent decision-making.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3124, '1w32j6w', 'Movies where un-serious things are taken seriously', 'Movies about serious treatment of comedic elements', '', 'Neat_Ostrich9966', 1788148324, '/r/MoviesThatFeelLike/comments/1w32j6w/movies_where_unserious_things_are_taken_seriously/', 'https://i.redd.it/yxzr4c21vmmh1.jpeg', 'MoviesThatFeelLike', 'A playful and ironic atmosphere focusing on films that give serious treatment to absurd situations.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3125, '1w33jpe', 'the overwhelming feeling of gen z childhood nostalgia', 'the overwhelming feeling of gen z childhood nostalgia', 'i’m talking those who were kids in the early 2010s/late 2000s like me! that feeling where you can’t go back but you remember the smells and felt the sunshine on your face. going to target and getting popcorn and icees with mom, going to the scholastic book fair and drawing on the sidewalk with chalk. playing flash games on the family computer all day. ', 'Master-Nectarine-487', 1788151399, '/r/MoviesThatFeelLike/comments/1w33jpe/the_overwhelming_feeling_of_gen_z_childhood/', 'https://www.reddit.com/gallery/1w33jpe', 'MoviesThatFeelLike', 'A warm, nostalgic ache for the simple joys and innocent atmosphere of a late 2000s/early 2010s childhood.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3126, '1w33r92', 'Any action or thriller movie that fits well with this song', 'Any action or thriller movie that fits well with this song', 'Song: (((O))) - Dead Friends

Link: [https://www.youtube.com/watch?v=dOoiq\_s1OQw](https://www.youtube.com/watch?v=dOoiq_s1OQw)', 'Original_Recover_452', 1788152051, '/r/MoviesThatFeelLike/comments/1w33r92/any_action_or_thriller_movie_that_fits_well_with/', 'https://i.redd.it/5d5veldw5nmh1.png', 'MoviesThatFeelLike', 'Dark and intense atmosphere seeking psychological thrillers and surreal cinema to match a song''s mood.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3127, '1w344nl', 'movies that feel like this?', 'movies that feel like this?', 'Are there any moves or shows that have this vibe? anything other than tvd, pll or twilight 😭', 'dobryoesty', 1788153218, '/r/MoviesThatFeelLike/comments/1w344nl/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1w344nl', 'MoviesThatFeelLike', 'Dark, moody teen horror-drama atmosphere with supernatural undertones and gothic high school aesthetics.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3128, '1w34iwx', 'Urban/industrial decay, overcast skies, steam, imposing characters', 'Urban industrial decay overcast skies steam imposing characters', 'I''m looking for films set in gritty, industrial cities where the urban environment drives the narrative, ideally featuring memorable characters and/or hateful antagonists 

Examples:   
NFSMW   
Fight club  
The machinist   
Blade runner 2049  
8 Mile  
Dark city  
Se7en', 'xPaBLuChO', 1788154470, '/r/MoviesThatFeelLike/comments/1w34iwx/urbanindustrial_decay_overcast_skies_steam/', 'https://www.reddit.com/gallery/1w34iwx', 'MoviesThatFeelLike', 'A smog-choked, rain-slicked urban hellscape of rusted steel and looming concrete, where oppressed individuals are crushed by oppressive systems and the city itself is the antagonist.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3129, '1w38vzh', 'Movies like the beginning of Hocus Pocus', 'Movies like the beginning of Hocus Pocus', '', 'Odd-Date3536', 1788169219, '/r/MoviesThatFeelLike/comments/1w38vzh/movies_like_the_beginning_of_hocus_pocus/', '/r/MovieSuggestions/comments/1w38vrp/movies_like_the_beginning_of_hocus_pocus/', 'MoviesThatFeelLike', 'Magical and spooky Halloween atmosphere.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3130, '1w39gzz', 'Movies that feel like ‘colors’ by Halsey?', 'Movies that feel like colors by Halsey', 'Or any song by Halsey', 'maroonsfv', 1788171101, '/r/MoviesThatFeelLike/comments/1w39gzz/movies_that_feel_like_colors_by_halsey/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1w39gzz/movies_that_feel_like_colors_by_halsey/', 'MoviesThatFeelLike', 'A request for movies and series that evoke the emotional and stylistic vibes of Halsey''s songs.', 'skipped', 'no usable images', NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3131, '1w3biw2', 'California in the 1980s', 'California in the 1980s', '', 'trsvrs', 1788177181, '/r/MoviesThatFeelLike/comments/1w3biw2/california_in_the_1980s/', 'https://v.redd.it/bgn0p6d8ulmh1', 'MoviesThatFeelLike', 'A nostalgic, possibly jarring glimpse into 1980s California culture that prompts reflection on how much social attitudes have shifted since then.', 'skipped', 'no enriched recommendation matches', NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3132, '1w3bklm', 'Movies that feel like epic bible studies with dark and grim vibes', 'Movies that feel like epic bible studies with dark and grim vibes', '(spoiler for blood)', 'Alternative_Laugh222', 1788177317, '/r/MoviesThatFeelLike/comments/1w3bklm/movies_that_feel_like_epic_bible_studies_with/', 'https://www.reddit.com/gallery/1w3bklm', 'MoviesThatFeelLike', 'Epic, dark, and grim films with biblical and historical themes, evoking solemn and intense atmospheres.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3133, '1w3dy59', 'Movies that feel like Autumn in New England?', 'Movies that feel like Autumn in New England?', '', 'Such_Plankton_3257', 1788183146, '/r/MoviesThatFeelLike/comments/1w3dy59/movies_that_feel_like_autumn_in_new_england/', 'https://www.reddit.com/gallery/1w3dy59', 'MoviesThatFeelLike', 'Cozy, nostalgic, and crisp autumnal atmosphere with a strong New England small-town aesthetic.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3134, '1w3ehli', 'Baywatch theme', 'Baywatch theme', '[removed]', 'TheHistoryHippo', 1788184406, '/r/MoviesThatFeelLike/comments/1w3ehli/baywatch_theme/', 'https://v.redd.it/z7564s1bupmh1', 'MoviesThatFeelLike', 'Nostalgic and referential mood evoked by the Baywatch theme.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3135, '1w3fb5z', 'Movies that feels like this :)', '', '', 'f-california', 1788186221, '/r/MoviesThatFeelLike/comments/1w3fb5z/movies_that_feels_like_this/', 'https://i.redd.it/lt8171qpzpmh1.jpeg', 'MoviesThatFeelLike', 'A whimsical, theatrical, and visually rich atmosphere evoking circus, stage, and dramatic grandeur.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3136, '1w3ffgv', 'Movies that feel like a fever dream', 'Movies that feel like a fever dream', '', 'cutie_pri', 1788186476, '/r/MoviesThatFeelLike/comments/1w3ffgv/movies_that_feel_like_a_fever_dream/', 'https://www.reddit.com/gallery/1w3ffgv', 'MoviesThatFeelLike', 'Surreal and intense dream-like atmosphere evoking confusion and vivid imagery.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3137, '1w3g534', 'Movies that feel like Horror, portal to afterlife hell', 'Movies that feel like Horror, portal to afterlife hell', '', 'S3XY_mis', 1788188032, '/r/MoviesThatFeelLike/comments/1w3g534/movies_that_feel_like_horror_portal_to_afterlife/', 'https://www.reddit.com/gallery/1w3g534', 'MoviesThatFeelLike', 'A craving for dark, oppressive horror that pulls you through a portal into hellish, otherworldly realms—suffocating dread with religious and occult overtones.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3138, '1w3ga44', 'Movies that feel like small town', 'Movies that feel like small town', '', 'PriandTiti', 1788188338, '/r/MoviesThatFeelLike/comments/1w3ga44/movies_that_feel_like_small_town/', 'https://www.reddit.com/gallery/1w3ga44', 'MoviesThatFeelLike', 'The discussion evokes a nostalgic and atmospheric small-town feel, with recommendations spanning cozy, eerie, and dramatic films and series.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3139, '1w3hgv1', 'Movies that feel like a nightmare', 'Movies that feel like a nightmare', '', 'Optimal_Prior_2551', 1788190873, '/r/MoviesThatFeelLike/comments/1w3hgv1/movies_that_feel_like_a_nightmare/', 'https://www.reddit.com/gallery/1w3hgv1', 'MoviesThatFeelLike', 'A deeply unsettling and surreal atmosphere that evokes the disorienting terror of recurring nightmares.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3140, '1w3ig0h', 'What are the change of thoughts and feelings after watching The Trueman Show ?', 'What are the changes in thoughts and feelings after watching The Truman Show?', '', 'Yooo-ho-ho-ho-ho', 1788192882, '/r/MoviesThatFeelLike/comments/1w3ig0h/what_are_the_change_of_thoughts_and_feelings/', '/r/AskReddit/comments/1w3ia2t/what_are_the_change_of_thoughts_and_feelings/', 'MoviesThatFeelLike', 'Contemplative inquiry into the psychological aftereffects of watching a reality-challenging film.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3141, '1w3isxe', 'Futuristic Post Apocalyptic Military structure at war with a seemingly unbeatable threat', 'Futuristic Post Apocalyptic Military structure at war with a seemingly unbeatable threat', '', 'AggravatingCounter91', 1788193602, '/r/MoviesThatFeelLike/comments/1w3isxe/futuristic_post_apocalyptic_military_structure_at/', 'https://www.reddit.com/gallery/1w3isxe', 'MoviesThatFeelLike', 'Intense sci-fi action with military themes facing overwhelming alien or apocalyptic threats.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3142, '1w3j6py', 'Movies That Feel Like Medieval aged', 'Movies That Feel Like Medieval Aged', '', 'NegotiationMean3042', 1788194420, '/r/MoviesThatFeelLike/comments/1w3j6py/movies_that_feel_like_medieval_aged/', 'https://www.reddit.com/gallery/1w3j6py', 'MoviesThatFeelLike', 'The post evokes a nostalgic and adventurous atmosphere centered on medieval and historical films.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3143, '1w3jln4', 'Movies that feel like this', '', 'Can you recommend me a film that’s a drama, psychological thriller, mystery, or crime? The season/weather should ideally be cold, foggy, gloomy... Location can be a city or small town. 

No historical, horror, fantasy, sci-fi suggestions please ', 'Ashamed-Designer4920', 1788195290, '/r/MoviesThatFeelLike/comments/1w3jln4/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1w3jln4', 'MoviesThatFeelLike', 'A gritty, cold, and suspenseful atmosphere evoking foggy streets and psychological tension.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3144, '1w3k2x6', 'Movies that feel like this', '', '', 'debensam', 1788196273, '/r/MoviesThatFeelLike/comments/1w3k2x6/movies_that_feel_like_this/', 'https://www.reddit.com/gallery/1w3k2x6', 'MoviesThatFeelLike', 'An eclectic array of cinematic suggestions for an implied aesthetic mood.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3145, '1w3l52q', 'Movies that feel like Alan Wake 1/2', 'Movies that feel like Alan Wake 1/2', '', 'InfamousSignature696', 1788198402, '/r/MoviesThatFeelLike/comments/1w3l52q/movies_that_feel_like_alan_wake_12/', 'https://www.reddit.com/gallery/1w3l52q', 'MoviesThatFeelLike', 'Dark, surreal atmosphere of creeping dread where reality unravels around isolated creators confronting sinister forces beyond their understanding.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3146, '1w3nimv', 'Movies that feel like', '', '', 'HeavyCurves03', 1788203191, '/r/MoviesThatFeelLike/comments/1w3nimv/movies_that_feel_like/', 'https://www.reddit.com/gallery/1w3nimv', 'MoviesThatFeelLike', 'An open-ended, unfinished prompt seeking movies with a particular feeling, but with no content or discussion provided.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3147, '1w3o11p', 'I need recommendations similar to "Loving, Vincent"', '', 'Hi need help with this one, I''ve loved the mover for years', 'BearGrace', 1788204226, '/r/MoviesThatFeelLike/comments/1w3o11p/i_need_recommendations_similar_to_loving_vincent/', '/r/findsimilarmovies/comments/1w3o07y/i_need_recommendations_similar_to_loving_vincent/', 'MoviesThatFeelLike', 'Enthusiastic appreciation for artistic animation with a nostalgic tone.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3148, '1w3r1cf', 'Movies that feel like', 'Movies that feel like', '(Could be movies or TV shows in the style of Spartacus, Gladiator or Prince of Persia)', 'HardcoreLatina25', 1788210424, '/r/MoviesThatFeelLike/comments/1w3r1cf/movies_that_feel_like/', 'https://www.reddit.com/gallery/1w3r1cf', 'MoviesThatFeelLike', 'Epic historical and mythological adventures with ancient settings.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3149, '1w3rs2l', 'Movies that feel like dark fairytale', '', '', 'Cobblerotus', 1788212025, '/r/MoviesThatFeelLike/comments/1w3rs2l/movies_that_feel_like_dark_fairytale/', 'https://www.reddit.com/gallery/1w3rs2l', 'MoviesThatFeelLike', 'A dark, eerie, and whimsical atmosphere inspired by twisted fairy tales and fantasy worlds.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3150, '1w3vc6u', 'Urban, hipster, mid 2000s to early 2010s', 'Urban, hipster, mid 2000s to early 2010s', 'Stuff that I''ve seen that captures this aesthetic well: Girls (HBO), LOL, new girl', 'strawberryc0w_', 1788220138, '/r/MoviesThatFeelLike/comments/1w3vc6u/urban_hipster_mid_2000s_to_early_2010s/', 'https://www.reddit.com/gallery/1w3vc6u', 'MoviesThatFeelLike', 'Nostalgic indie, coming-of-age longing for urban millennial life filled with indie-pop soundtracks, record stores, quirky friendships, and bittersweet romance in coffee-shop-dotted city neighborhoods.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
INSERT OR IGNORE INTO "imported_vibe_posts" ("id", "reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at") VALUES (3151, '1w3vgb6', 'The paintings of John Atkinson Grimshaw (6 September 1836 – 13 October 1893) English Victorian-era artist best known for his nocturnal scenes of urban landscapes.', '', 'These paintings are so cozy!! If I could find a movie/series with the same vibe I’d constantly binge that shit', 'ethrowcaways', 1788220420, '/r/MoviesThatFeelLike/comments/1w3vgb6/the_paintings_of_john_atkinson_grimshaw_6/', 'https://www.reddit.com/gallery/1w3skuh', 'MoviesThatFeelLike', 'Cozy and atmospheric nocturnal urban landscapes with a gothic touch.', 'publishable', NULL, NULL, '2026-09-01 03:44:37', '2026-09-01 03:44:37');
