-- 0194_seed_20261010T201940Z_01_posts.sql: data seed from pipeline:load run.
-- Generated:  2026-10-10T20:20:08.423289+00:00
-- Run started: 2026-10-10T20:19:40.422137+00:00
-- Source: data/working/load manifest from this run.
--
-- Idempotent: every row is an upsert keyed by the table's
-- natural unique constraint, and every child resolves its
-- parents through that same key.  Row ids are never copied —
-- the destination allocates them — so re-applying refreshes the
-- row it belongs to instead of colliding with an id D1 already
-- owns.  Wrangler's migration tracking normally prevents
-- re-apply; the upsert is defense in depth for partial /
-- interrupted re-runs, and a conflict target the destination
-- cannot satisfy aborts the apply instead of dropping rows.
--
-- Chunk: 01_posts (1/5)
-- Tables: imported_vibe_posts.
-- Pipeline-state tables (processing_runs, pipeline_artifacts)
-- are intentionally excluded — they're per-run bookkeeping.

INSERT INTO "imported_vibe_posts" ("reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at")
VALUES ('1x1in26', 'Any similiar movie', 'Any similiar movie', 'I am looking a movie that has same atmosphere with little nightmares', 'allah_baba_123', 1791544483, '/r/MoviesThatFeelLike/comments/1x1in26/any_similiar_movie/', 'https://i.redd.it/8gp3upxjdfuh1.jpeg', 'MoviesThatFeelLike', 'Creepy, surreal, and unsettling stop-motion dark fairy tale horror matching Little Nightmares', 'publishable', NULL, NULL, '2026-10-10 20:20:08', '2026-10-10 20:20:08')
ON CONFLICT(reddit_post_id) DO UPDATE SET "title"=excluded."title", "cleaned_title"=excluded."cleaned_title", "selftext"=excluded."selftext", "author"=excluded."author", "created_utc"=excluded."created_utc", "permalink"=excluded."permalink", "url"=excluded."url", "subreddit"=excluded."subreddit", "vibe_summary"=excluded."vibe_summary", "status"=excluded."status", "error_info"=excluded."error_info", "processing_run_id"=excluded."processing_run_id", "updated_at"=excluded."updated_at";
INSERT INTO "imported_vibe_posts" ("reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at")
VALUES ('1x1lsap', 'America shown from foreigner''s perspective', 'America shown from foreigner''s perspective', '', 'Honest_Excitement246', 1791553557, '/r/MoviesThatFeelLike/comments/1x1lsap/america_shown_from_foreigners_perspective/', 'https://i.redd.it/r9ea693j4guh1.jpeg', 'MoviesThatFeelLike', 'Outsider perspectives on American life and culture, ranging from satirical fish-out-of-water journeys to raw character studies', 'publishable', NULL, NULL, '2026-10-10 20:20:08', '2026-10-10 20:20:08')
ON CONFLICT(reddit_post_id) DO UPDATE SET "title"=excluded."title", "cleaned_title"=excluded."cleaned_title", "selftext"=excluded."selftext", "author"=excluded."author", "created_utc"=excluded."created_utc", "permalink"=excluded."permalink", "url"=excluded."url", "subreddit"=excluded."subreddit", "vibe_summary"=excluded."vibe_summary", "status"=excluded."status", "error_info"=excluded."error_info", "processing_run_id"=excluded."processing_run_id", "updated_at"=excluded."updated_at";
INSERT INTO "imported_vibe_posts" ("reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at")
VALUES ('1x1mt62', 'Fun fantastic gang in cosmic action/ quest.', 'Fun fantastic gang in cosmic action/ quest.', 'movies that mix sword-and-sorcery fantasy with cosmic action and quirky characters.

Do Check the Recommendations .TIA❤️', 'Adorable-Quarter2994', 1791556005, '/r/MoviesThatFeelLike/comments/1x1mt62/fun_fantastic_gang_in_cosmic_action_quest/', 'https://www.reddit.com/gallery/1x1mt62', 'MoviesThatFeelLike', 'Quirky ensemble cosmic adventures blending sword-and-sorcery fantasy and sci-fi quest action', 'publishable', NULL, NULL, '2026-10-10 20:20:08', '2026-10-10 20:20:08')
ON CONFLICT(reddit_post_id) DO UPDATE SET "title"=excluded."title", "cleaned_title"=excluded."cleaned_title", "selftext"=excluded."selftext", "author"=excluded."author", "created_utc"=excluded."created_utc", "permalink"=excluded."permalink", "url"=excluded."url", "subreddit"=excluded."subreddit", "vibe_summary"=excluded."vibe_summary", "status"=excluded."status", "error_info"=excluded."error_info", "processing_run_id"=excluded."processing_run_id", "updated_at"=excluded."updated_at";
INSERT INTO "imported_vibe_posts" ("reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at")
VALUES ('1x1pesr', 'Snowy, Old-World European Cityscapes and Architecture', 'Snowy, Old-World European Cityscapes and Architecture', 'I’m obsessed with the look of these pictures — what movies come to mind when you see them?', 'ZElves100', 1791562139, '/r/MoviesThatFeelLike/comments/1x1pesr/snowy_oldworld_european_cityscapes_and/', 'https://www.reddit.com/gallery/1x1pesr', 'MoviesThatFeelLike', 'Snowy, atmospheric historic European cityscapes and old-world architecture', 'publishable', NULL, NULL, '2026-10-10 20:20:08', '2026-10-10 20:20:08')
ON CONFLICT(reddit_post_id) DO UPDATE SET "title"=excluded."title", "cleaned_title"=excluded."cleaned_title", "selftext"=excluded."selftext", "author"=excluded."author", "created_utc"=excluded."created_utc", "permalink"=excluded."permalink", "url"=excluded."url", "subreddit"=excluded."subreddit", "vibe_summary"=excluded."vibe_summary", "status"=excluded."status", "error_info"=excluded."error_info", "processing_run_id"=excluded."processing_run_id", "updated_at"=excluded."updated_at";
INSERT INTO "imported_vibe_posts" ("reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at")
VALUES ('1x1pza6', 'Movies with Woody Allen vibes but gay', 'Movies with Woody Allen vibes but gay', 'im looking for romance dramedy movie recs with the same vibes as woody allen (possibly by a director who''s not problematic as him lol) with gay themes or protagonists', 'LeadingRadiant9012', 1791563448, '/r/MoviesThatFeelLike/comments/1x1pza6/movies_with_woody_allen_vibes_but_gay/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1x1pza6/movies_with_woody_allen_vibes_but_gay/', 'MoviesThatFeelLike', 'Talky, neurotic queer romantic comedy and urban dramedy', 'skipped', 'no usable images', NULL, '2026-10-10 20:20:08', '2026-10-10 20:20:08')
ON CONFLICT(reddit_post_id) DO UPDATE SET "title"=excluded."title", "cleaned_title"=excluded."cleaned_title", "selftext"=excluded."selftext", "author"=excluded."author", "created_utc"=excluded."created_utc", "permalink"=excluded."permalink", "url"=excluded."url", "subreddit"=excluded."subreddit", "vibe_summary"=excluded."vibe_summary", "status"=excluded."status", "error_info"=excluded."error_info", "processing_run_id"=excluded."processing_run_id", "updated_at"=excluded."updated_at";
INSERT INTO "imported_vibe_posts" ("reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at")
VALUES ('1x1qb8s', 'Movies with a similar vibe to Planet Caravan by Black Sabbath', 'Movies with a similar vibe to Planet Caravan by Black Sabbath', 'Smooth, chill, psychedelic, but can also be haunting, otherworldly or cosmic', 'YipeeKiYouCompleteMe', 1791564232, '/r/MoviesThatFeelLike/comments/1x1qb8s/movies_with_a_similar_vibe_to_planet_caravan_by/', 'https://v.redd.it/xojprw550huh1', 'MoviesThatFeelLike', 'Chill, hypnotic psychedelia blending slow-tempo cosmic drifting with dark, otherworldly, and haunting undertones.', 'publishable', NULL, NULL, '2026-10-10 20:20:08', '2026-10-10 20:20:08')
ON CONFLICT(reddit_post_id) DO UPDATE SET "title"=excluded."title", "cleaned_title"=excluded."cleaned_title", "selftext"=excluded."selftext", "author"=excluded."author", "created_utc"=excluded."created_utc", "permalink"=excluded."permalink", "url"=excluded."url", "subreddit"=excluded."subreddit", "vibe_summary"=excluded."vibe_summary", "status"=excluded."status", "error_info"=excluded."error_info", "processing_run_id"=excluded."processing_run_id", "updated_at"=excluded."updated_at";
INSERT INTO "imported_vibe_posts" ("reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at")
VALUES ('1x1sgd8', 'Movies that feel like this? (Please read description)', 'Movies that feel like this? (Please read description)', 'I’ve already seen

One Flew Over the Cuckoo''s Nest (1975)  
Gothika (2003)  
Shutter Island (2010)  
A Clockwork Orange (1971)  
Girl, Interrupted (1999)  
Session 9 (2001)  
Stonehearst Asylum (2013)  
In the mouth of madness  
Unsane (2018)  
AHS: Asylum', 'Ordinary-Gal', 1791569205, '/r/MoviesThatFeelLike/comments/1x1sgd8/movies_that_feel_like_this_please_read_description/', 'https://www.reddit.com/gallery/1x1sgd8', 'MoviesThatFeelLike', 'Claustrophobic, sterile, and psychologically disorienting atmospheric tension centered around mental institutions and psychological confinement.', 'publishable', NULL, NULL, '2026-10-10 20:20:08', '2026-10-10 20:20:08')
ON CONFLICT(reddit_post_id) DO UPDATE SET "title"=excluded."title", "cleaned_title"=excluded."cleaned_title", "selftext"=excluded."selftext", "author"=excluded."author", "created_utc"=excluded."created_utc", "permalink"=excluded."permalink", "url"=excluded."url", "subreddit"=excluded."subreddit", "vibe_summary"=excluded."vibe_summary", "status"=excluded."status", "error_info"=excluded."error_info", "processing_run_id"=excluded."processing_run_id", "updated_at"=excluded."updated_at";
INSERT INTO "imported_vibe_posts" ("reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at")
VALUES ('1x1t3pu', 'Similar movie suggestions', 'Similar movie suggestions', 'Hey! I recently watched chunking express and I''m in love with the vibe of that movie and direction. Especially the reference of california dreamin... would love to know more similar movies to watch ... and if u love this movie as well.. let''s talk bout that!!', 'Expert_Drawing1920', 1791570708, '/r/MoviesThatFeelLike/comments/1x1t3pu/similar_movie_suggestions/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1x1t3pu/similar_movie_suggestions/', 'MoviesThatFeelLike', 'A dreamy, neon-drenched urban longing infused with wistful romance and vibrant pop aesthetics inspired by Chungking Express.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-10-10 20:20:08', '2026-10-10 20:20:08')
ON CONFLICT(reddit_post_id) DO UPDATE SET "title"=excluded."title", "cleaned_title"=excluded."cleaned_title", "selftext"=excluded."selftext", "author"=excluded."author", "created_utc"=excluded."created_utc", "permalink"=excluded."permalink", "url"=excluded."url", "subreddit"=excluded."subreddit", "vibe_summary"=excluded."vibe_summary", "status"=excluded."status", "error_info"=excluded."error_info", "processing_run_id"=excluded."processing_run_id", "updated_at"=excluded."updated_at";
INSERT INTO "imported_vibe_posts" ("reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at")
VALUES ('1x1u9lr', 'Movies that feel like 1970s/Early 80s New York', 'Movies that feel like 1970s/Early 80s New York', '', 'Radiant-Boat-5149', 1791573393, '/r/MoviesThatFeelLike/comments/1x1u9lr/movies_that_feel_like_1970searly_80s_new_york/', 'https://www.reddit.com/gallery/1x1u9lr', 'MoviesThatFeelLike', 'Gritty, asphalt-soaked urban nostalgia evoking neon-lit grime, subways, and street crime in 1970s and 1980s New York City.', 'publishable', NULL, NULL, '2026-10-10 20:20:08', '2026-10-10 20:20:08')
ON CONFLICT(reddit_post_id) DO UPDATE SET "title"=excluded."title", "cleaned_title"=excluded."cleaned_title", "selftext"=excluded."selftext", "author"=excluded."author", "created_utc"=excluded."created_utc", "permalink"=excluded."permalink", "url"=excluded."url", "subreddit"=excluded."subreddit", "vibe_summary"=excluded."vibe_summary", "status"=excluded."status", "error_info"=excluded."error_info", "processing_run_id"=excluded."processing_run_id", "updated_at"=excluded."updated_at";
INSERT INTO "imported_vibe_posts" ("reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at")
VALUES ('1x1uwb9', '🎬 Recommend me a movie that you think EVERYONE should watch at least once!', 'Recommend me a movie that you think EVERYONE should watch at least once!', '', 'rollOnBro', 1791574865, '/r/MoviesThatFeelLike/comments/1x1uwb9/recommend_me_a_movie_that_you_think_everyone/', '/r/MovieIt/comments/1x1uw14/recommend_me_a_movie_that_you_think_everyone/', 'MoviesThatFeelLike', 'An open and enthusiastic quest for essential, universally impactful films that everyone ought to experience at least once.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-10-10 20:20:08', '2026-10-10 20:20:08')
ON CONFLICT(reddit_post_id) DO UPDATE SET "title"=excluded."title", "cleaned_title"=excluded."cleaned_title", "selftext"=excluded."selftext", "author"=excluded."author", "created_utc"=excluded."created_utc", "permalink"=excluded."permalink", "url"=excluded."url", "subreddit"=excluded."subreddit", "vibe_summary"=excluded."vibe_summary", "status"=excluded."status", "error_info"=excluded."error_info", "processing_run_id"=excluded."processing_run_id", "updated_at"=excluded."updated_at";
INSERT INTO "imported_vibe_posts" ("reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at")
VALUES ('1x1uwpw', 'Movies that feels like Anne of Green Gables, but male MC', 'Movies that feels like Anne of Green Gables, but male MC', 'https://preview.redd.it/0tut9i5yvhuh1.png?width=1200&format=png&auto=webp&s=2db6db1d8a319ebc58bb292c7cadbea0dff820be

', 'Innevitable_Scar', 1791574895, '/r/MoviesThatFeelLike/comments/1x1uwpw/movies_that_feels_like_anne_of_green_gables_but/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1x1uwpw/movies_that_feels_like_anne_of_green_gables_but/', 'MoviesThatFeelLike', 'Wholesome, nostalgic, and daydreamy coming-of-age warmth.', 'skipped', 'no usable images', NULL, '2026-10-10 20:20:08', '2026-10-10 20:20:08')
ON CONFLICT(reddit_post_id) DO UPDATE SET "title"=excluded."title", "cleaned_title"=excluded."cleaned_title", "selftext"=excluded."selftext", "author"=excluded."author", "created_utc"=excluded."created_utc", "permalink"=excluded."permalink", "url"=excluded."url", "subreddit"=excluded."subreddit", "vibe_summary"=excluded."vibe_summary", "status"=excluded."status", "error_info"=excluded."error_info", "processing_run_id"=excluded."processing_run_id", "updated_at"=excluded."updated_at";
INSERT INTO "imported_vibe_posts" ("reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at")
VALUES ('1x1v3o1', 'Movies that feel like', 'Movies that feel like', '[removed]', '[deleted]', 1791575350, '/r/MoviesThatFeelLike/comments/1x1v3o1/movies_that_feel_like/', '', 'MoviesThatFeelLike', 'Unspecified mood from an empty removed submission.', 'skipped', 'no usable images; no enriched recommendation matches', NULL, '2026-10-10 20:20:08', '2026-10-10 20:20:08')
ON CONFLICT(reddit_post_id) DO UPDATE SET "title"=excluded."title", "cleaned_title"=excluded."cleaned_title", "selftext"=excluded."selftext", "author"=excluded."author", "created_utc"=excluded."created_utc", "permalink"=excluded."permalink", "url"=excluded."url", "subreddit"=excluded."subreddit", "vibe_summary"=excluded."vibe_summary", "status"=excluded."status", "error_info"=excluded."error_info", "processing_run_id"=excluded."processing_run_id", "updated_at"=excluded."updated_at";
INSERT INTO "imported_vibe_posts" ("reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at")
VALUES ('1x1xeg3', 'Need help for my girl night,similar to Fast and Furious', 'Need help for my girl night,similar to Fast and Furious', 'What movies can i binge watch with my girl friends???Every week we meet up and watch something,but I have no ideas left. It will be nice to watch something like \*\*Fast and Furious\*\*. Part 9 is my favourite,', 'Background_Lack_1481', 1791580932, '/r/MoviesThatFeelLike/comments/1x1xeg3/need_help_for_my_girl_nightsimilar_to_fast_and/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1x1xeg3/need_help_for_my_girl_nightsimilar_to_fast_and/', 'MoviesThatFeelLike', 'High-octane, adrenaline-fueled, and entertaining action-packed popcorn thrills.', 'skipped', 'no usable images', NULL, '2026-10-10 20:20:08', '2026-10-10 20:20:08')
ON CONFLICT(reddit_post_id) DO UPDATE SET "title"=excluded."title", "cleaned_title"=excluded."cleaned_title", "selftext"=excluded."selftext", "author"=excluded."author", "created_utc"=excluded."created_utc", "permalink"=excluded."permalink", "url"=excluded."url", "subreddit"=excluded."subreddit", "vibe_summary"=excluded."vibe_summary", "status"=excluded."status", "error_info"=excluded."error_info", "processing_run_id"=excluded."processing_run_id", "updated_at"=excluded."updated_at";
INSERT INTO "imported_vibe_posts" ("reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at")
VALUES ('1x1xjdm', 'Movies about a group of people or couple experiencing apocalypsis or natural disaster', 'Movies about a group of people or couple experiencing apocalypsis or natural disaster', 'Important that...

\- the characters are well-written, there is a focus on their character/personalities before things unfold

\- it''s not historical or fantasy

', 'Ashamed-Designer4920', 1791581291, '/r/MoviesThatFeelLike/comments/1x1xjdm/movies_about_a_group_of_people_or_couple/', 'https://www.reddit.com/r/MoviesThatFeelLike/comments/1x1xjdm/movies_about_a_group_of_people_or_couple/', 'MoviesThatFeelLike', 'Somber and character-driven psychological tension facing catastrophic impending doom.', 'skipped', 'no usable images', NULL, '2026-10-10 20:20:08', '2026-10-10 20:20:08')
ON CONFLICT(reddit_post_id) DO UPDATE SET "title"=excluded."title", "cleaned_title"=excluded."cleaned_title", "selftext"=excluded."selftext", "author"=excluded."author", "created_utc"=excluded."created_utc", "permalink"=excluded."permalink", "url"=excluded."url", "subreddit"=excluded."subreddit", "vibe_summary"=excluded."vibe_summary", "status"=excluded."status", "error_info"=excluded."error_info", "processing_run_id"=excluded."processing_run_id", "updated_at"=excluded."updated_at";
INSERT INTO "imported_vibe_posts" ("reddit_post_id", "title", "cleaned_title", "selftext", "author", "created_utc", "permalink", "url", "subreddit", "vibe_summary", "status", "error_info", "processing_run_id", "created_at", "updated_at")
VALUES ('1x20dtr', 'Movies that are like these? Movies about war that can fit this list.', 'Movies that are like these? Movies about war that can fit this list.', '', 'Jolly-Yellow7369', 1791588943, '/r/MoviesThatFeelLike/comments/1x20dtr/movies_that_are_like_these_movies_about_war_that/', 'https://www.reddit.com/gallery/1x20cis', 'MoviesThatFeelLike', 'Grand, classic, and intense wartime cinematic epics exploring historical battles and leadership.', 'publishable', NULL, NULL, '2026-10-10 20:20:08', '2026-10-10 20:20:08')
ON CONFLICT(reddit_post_id) DO UPDATE SET "title"=excluded."title", "cleaned_title"=excluded."cleaned_title", "selftext"=excluded."selftext", "author"=excluded."author", "created_utc"=excluded."created_utc", "permalink"=excluded."permalink", "url"=excluded."url", "subreddit"=excluded."subreddit", "vibe_summary"=excluded."vibe_summary", "status"=excluded."status", "error_info"=excluded."error_info", "processing_run_id"=excluded."processing_run_id", "updated_at"=excluded."updated_at";
